### ISSUE TITLE
Diakriitittömät termivariantit

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#10]
_From [sini.pes...@gmail.com](https://code.google.com/u/106658693216861444572/) on October 04, 2013 12:55:19_

Jotta käsitteitä pystyisi hakemaan myös silloin, kun ei tiedä sanan diakriittejä, tulisi tällaisiin käsitteisiin lisätä myös diakriititön versio.

Esim.
déjà vu -ilmiö -> deja vu -ilmiö

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=6_

**Comment by mirmaid** [comment]
Ks. issue #11
