### ISSUE TITLE
Hierarkia pelit/urheilu

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#1001]
Pitäisikö ainakin biljardi ja snooker siirtää urheilu-hierarkiaan? Entä tikanheitto, mölkky, shakki? Airsoft? Myös kuulapelien alla vastaavia.

**Comment by mariaforsen** [comment]
Käsitteenmuodostus on ruotsiksi erilainen kuin suomeksi, urheilu-termin ongelmallisuudesta on tehty issue: https://github.com/Finto-ehdotus/YSE/issues/9816

**Comment by mirmaid** [comment]
Jos päätermi muuttuu > idrott och sport tms., siirretään urheilu-hierarkiaan: 
biljardi
snooker
tikanheitto + darts
boccia
petankki
mölkky

**Comment by mirmaid** [comment]
Siirretty.
