### ISSUE TITLE
Vanhat suljetut issuet eivät poistu YSEstä

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#1002]
Kun YSOon hyväksytään käsite, jonka alkuperäinen ehdotus on vanha, issuen sulkeminen GitHubissa ei poista ehdotusta YSEstä. Sama käsite on tämän jälkeen sekä YSEssä: http://www.yso.fi/onto/ysa/Y314217, että YSOssa: http://www.yso.fi/onto/yso/p30039. Tämä herättää hämmennystä käyttäjissä: https://github.com/Finto-ehdotus/YSE/issues/258.

**Comment by mirmaid** [comment]
Ks. myös https://www.kiwi.fi/pages/viewpage.action?pageId=242385070

**Comment by miguelvaara** [comment]
done
