### ISSUE TITLE
Lakien vakiintuneita säädösnimikkeitä Finlexissä

### ISSUE THREAD

**Issue by jarmosaarikko** [NatLibFi/Finto-data#1008]
Finlexistä löytyy tarkistuslista "vakiintuneista" säädösnimikkeistä:  
- https://www.finlex.fi/fi/laki/smur/vakiintuneet/

Näitä voisi lisätä ohjautermeiksi, jos puuttuvat.

Lähde: Säädöksille käytännössä vakiintuneita nimikkeitä - Säädösmuutosten hakemisto - FINLEX ®

**Comment by mirmaid** [comment]
Lisätään puuttuvat.

**Comment by mariaforsen** [comment]
En löytänyt vastaavaa listausta ruotsiksi. Lisätään sen mukaan kun tulee vastaan (kuten tähänkin asti).
