### ISSUE TITLE
YSE: new concepts don't have preflabels or other properties

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#1013]
**URL-address of the Finto.fi-page where you encountered the problem**
http://www.yso.fi/onto/ysa/Y510924

**Description of the problem, and the expected outcome after it has been fixed**
When a new issue in https://github.com/Finto-ehdotus/ is given "vastaanotettu"-label, a new YSE-entry is correctly created, but this is lacking a preflabel and apparently all other properties as well, and only has a URI. 

Correctly created YSE-entry should look like this: http://www.yso.fi/onto/ysa/Y509332

**Additional information about the problem**
Has appeared already last year (http://www.yso.fi/onto/ysa/Y509420), but back then some issues had properties, while others did not. This year all issues are lacking properties.

**The browser you used when the problem appeared**
Firefox, Chrome

**Comment by miguelvaara** [comment]
Done
