### ISSUE TITLE
Uudet YSE-ehdotukset eivät näy Fintossa "uudet" välilehdellä

### ISSUE THREAD

**Issue by jarmosaarikko** [NatLibFi/Finto-data#1036]
#Ongelma
- uudet ehdotukset eivät ilmesty Fintoon "uudet" lehden näkymään:  https://finto.fi/yse/fi/new 

#Kuvaus
- Uudet-listalla viimeisin on "basilikat" päivitetty 15.10.2023  issue: https://github.com/Finto-ehdotus/YSE/issues/12192
- Sen jälkeen on ilmestynyt kymmeniä uusia ehdotuksia ja viimeisin issue, jonka löysin on:  
  - https://github.com/Finto-ehdotus/YSE/issues/12278

**Comment by miguelvaara** [comment]
Ongelma johtui siitä, ettei "puuttuviin" käsitteisiin ollut lisätty vastaanotettu-labelia. Testattiin testiehdotuksen kanssa jo todettiin toimivaksi - uudet, mutta vastaanotetuiksi merkityt ehdotukset siirtyvät YSEen.
