### ISSUE TITLE
Uralilaiset kansat ja uralilaiset kielet

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#1044]
Näissä hierarkioissa ja käsitteiden keskinäisissä suhteissa heijastuu osin vanhentunut ajatus uralilaisten kielten taksonomiasta. Tutkimus on edennyt ja sitä myötä käsitys kielipuun tarkemmasta jaottelusta. Käsitteiden suhteita olisi syytä tarkistaa.

**Comment by mirmaid** [comment]
Ei muutoksia tässä vaiheessa, noudatetaan Kotuksen näkemystä kun saadaan heiltä päivitys kielikuntiin.
