### ISSUE TITLE
uskonnot

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#107]
_From [mafors...@gmail.com](https://code.google.com/u/100004162283516840686/) on January 30, 2014 14:31:44_

1. What is to be changed/Mitä muutetaan uskonnot (opit) 2. Why the change is needed/Miksi muutetaan Eikö uskonnot riittäisi? Ainakin jos tietää miten tesaurus/ontologia toimii merkitysero verrattuna uskonto (uskominen) pitäisi olla selvää. Nykyiset sulut hieman hämmentäviä. 

Siinä näkyy myös vapaaindeksoinnin kommentti, pitäisikö ne poistaa ja miten, niitä on paljon. 3. Realized changes/Toteutetut muutokset

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=104_

**Comment by tpalonen** [comment]
Koostekäsitepalavereissa sulkutarkenteiden keksimisessä kunnostautunut tehotiimi asialle tätä ja vastaavia miettimään?
