### ISSUE TITLE
Diakriitittömien termivarianttien esittäminen

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#11]
_From [sini.pes...@gmail.com](https://code.google.com/u/106658693216861444572/) on October 04, 2013 12:56:54_

Diakriitittömät termivariantit tulisi olla YSOssa haettavuuden parantamiseksi.

Tulisi miettiä mikä olisi sopiva ominaisuus tälle ja lisätä ominaisuus YSOon.

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=7_

**Comment by osma** [comment]
Tämä etenee, puuttuva pala on enää tuki diakriittien poistolle Jenassa. Bruno on tekemässä tähän komponenttia.

**Comment by MikkoAleksanteri** [comment]
Mikä tämän tilanne on @osma ?

**Comment by osma** [comment]
Kaikki komponentit ovat nyt olemassa, mutta tätä ei ole meillä otettu käyttöön. Vaatisi Jenan teksti-indeksin uudelleenkonfigurointia ja sen jälkeen sen *pitäisi* toimia - mutta ei ole siis testattu.

**Comment by osma** [comment]
Tai siis toki ohjelmistokomponentit on testattu pienessä mittakaavassa eli toimivat siten kuin on speksattu, mutta se ei vielä takaa, että lopputulos on hyvä ;)
