### ISSUE TITLE
Tilannekuva englanniksi

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#117]
_From [satu.nii...@gmail.com](https://code.google.com/u/110842852617286366306/) on February 04, 2014 08:41:26_
1. What is to be changed/Mitä muutetaan Tilannekuva =  tiettyä tilannetta esittävä kuva t. kuvaus; vrt. tuokiokuva. Novellin hauskat tilannekuvat. Ottelusta näpätty tilannekuva. 2. Why the change is needed/Miksi muutetaan Myös valokuvaustermi? Ryhmitelty yleistermiksi, mutta Melindassa käytössä sodankäyntiterminä, joka kääntyisi luontevasti termillä "situational awareness". Pitäisikö merkitystä rajata? 3. Realized changes/Toteutetut muutokset

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=114_

**Comment by mirmaid** [comment]
Muutosehdotus YSEssä https://github.com/Finto-ehdotus/YSE/issues/4785

**Comment by mirmaid** [comment]
Lisätty määritelmä: _Kuvaus tai käsitys vallitsevasta tilanteesta, sen taustatekijöistä ja tilanteen kehittymisen mahdollisista vaihtoehdoista._

YSOn yläkäsite pitäisi muuttaa.

**Comment by YSO-kokous** [comment]
YK käsitykset
