### ISSUE TITLE
YSA-, Allärs- ja MUSA-käsitteiden luonti- ja muutospäivät SKOSiin

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#124]
_From [osma.suominen@helsinki.fi](https://code.google.com/u/osma.suominen@helsinki.fi/) on February 05, 2014 10:36:06_

YSAn, Allärsin ja MUSAn MARC-tietueissa on tieto tietueen luonti- ja muutospäivämääristä (luonti 008, muutos 008):

<controlfield tag="005">20081216145035.0</controlfield>
<controlfield tag="008">990818| |a|z||bab|           | ana      </controlfield>

Nämä olisi kiva saada mukaan SKOS-muotoon esim. seuraavaan tyyliin:

  dct:created "1999-08-18"^^xsd:date ;
  dct:modified "2008-12-16"^^xsd:date .

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=121_

**Comment by osma** [comment]
Tämä on tehty osana uutta muunninta jo aikaa sitten, unohtunut sulkea.
