### ISSUE TITLE
KOKO kielitiede deprekointi ja broaderit sekaisin

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#126]
_From [henri.ylikotila@gmail.com](https://code.google.com/u/henri.ylikotila@gmail.com/) on February 07, 2014 10:08:08_

What steps will reproduce the problem? http://api.finto.fi/rest/v1/koko/broaderTransitive?uri=http://www.yso.fi/onto/koko/p11414 Kielitiede on itsensä broader ja käsite vaikuttaa muutenkin erikoiselta myös suoraan datasta katsottuna.

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=123_

**Comment by frosterus** [comment]
Korjautui uudella kokoamisella.
