### ISSUE TITLE
BaseURIn määrittely

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#14]
_From [sini.pes...@gmail.com](https://code.google.com/u/106658693216861444572/) on October 08, 2013 17:20:39_

Jokaisella kehitettävällä ontologialla pitäisi olla baseURI määritelty, jotta TBC osaisi näyttää ontologian tiedot oikein.

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=10_

**Comment by osma** [comment]
Ei enää relevantti. Tämä on tehty jo kaikille niille ontologioille, joita kehitetään TBC:llä, ja skriptit tekevät sen tarvittaessa muillekin.
