### ISSUE TITLE
Ontologiamäärittelyn lisääminen kehitysontologioihin

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#15]
_From [sini.pes...@gmail.com](https://code.google.com/u/106658693216861444572/) on October 08, 2013 17:26:57_

Jokaiseen kehitysontologiaan pitäisi olla määritelty triple:
<baseURI> rdf:type owl:Ontology

Tämä mahdollistaa ontologian tietojen näkymisen oikein TBC:ssä.

Lisäksi mahdolliset vanhat päällekkäiset määrittelyt tulisi poistaa.

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=11_

**Comment by osma** [comment]
Eiköhän tämä ole jo kunnossa siinä määrin kuin on tarpeen.
