### ISSUE TITLE
Changes in YSA comments do not come to YSO

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#164]
_From [mikko.al...@gmail.com](https://code.google.com/u/110439846636887938592/) on February 14, 2014 10:26:15_

It seems that chances made in YSA in comments properties do not come to YSO

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=161_

**Comment by frosterus** [comment]
Osman uusi YSA-YSO-päivitin ratkaisi ongelman.
