### ISSUE TITLE
tekniset järjestelmät -käsitteen paikka

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#166]
_From [tuomas.p...@gmail.com](https://code.google.com/u/114029607375739102692/) on February 14, 2014 13:41:41_

1. What is to be changed/Mitä muutetaan tekniset järjestelmät tällä hetkellä järjestelmät-käsitteen alla. muut järjestelmät-hierarkiassa olevat käsitteistöt ovat kuitenkin erityyppisiä (mm. luonnontieteelliset järjestelmät kuten eliöyhteisöt, galaksit jne). tekniset järjestelmät kuitenkin pikemmin tuotteita kuin järjestelmiä tässä kontekstissa. 2. Why the change is needed/Miksi muutetaan 3. Realized changes/Toteutetut muutokset Ehdotus: olisi tekniset tuotokset parempi yläkäsite?

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=163_

**Comment by mirmaid** [comment]
YSO-kokous 27.10.
- nykyinen ratkaisu on toimiva
