### ISSUE TITLE
Sana-ongelma: jäätelö

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#17]
_From [mafors...@gmail.com](https://code.google.com/u/100004162283516840686/) on October 10, 2013 13:04:08_

Jäätelö on nyt maitovalmisteiden alla, mutta kieli on tässä tapauksessa muuttunut ja jäätelöä tehdään nykyään muistakin aineista (kasviperäisiä, esim. soija). Olisiko jälkiruoat kuitenkin parempi yläkäsitteenä (koska se ei ainakaan ole suorastaan virheellinen) vai mitä ratkaisua tähän voisi olla? Ainakin ruotsiksi on kavsiperäiset jäätelöt jo niin tavallisia ettemme oikein voida pitää niitä maitotuotteiden alakäsitteenä.

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=14_

**Comment by mirmaid** [comment]
YSO-kokous 27.10. 
- toteutetaan muutos YSOssa
