### ISSUE TITLE
Kulttuuriset ja yhteiskunnalliset kategoriat ylähierarkiassa

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#2]
YSOn hierarkiassa on useampi jako kulttuuristen ja yhteiskunnallisten käsitteiden välillä. Nämä on listattu alla. Näiden kesken on vaikea tehdä selvää eroa ja käsitteitä hierarkisoitaessa valinta näiden välillä on usein vaikeaa. 
- kulttuuriset ilmiöt & yhteiskunnalliset ilmiöt
- kulttuuriset tuotokset & yhteiskunnalliset tuotokset
- kulttuuriset järjestelmät & yhteiskunnalliset järjestelmät
- kulttuuriset ominaisuudet & yhteiskunnalliset ominaisuudet
- kulttuuritapahtumat (YSAsta) & yhteiskunnalliset tapahtumat

Katri Seppälän kommentti:
"Kulttuurinen ei ole tässä yhteydessä laajassa merkityksessään eli ei viittaa kaikkiin ihmiskunnan tuotoksiin/ilmiöihin/järjestelmiin - muutenhan jakoa ei olisi - vaan painottuu luovaan toimintaan/taiteeseen/populaarikulttuuriin jne. Yhteiskunnallinen taas painottuu yhteiskunnan säädeltyyn toimintaan. Ilman tällaista jakoa esimerkiksi horoskoopit ja säädökset päätyisivät samaan hierarkiaan eli on yritetty edes vähän ryhmitellä."

**Comment by YSO-kokous** [comment]
PÄÄTÖS

- ominaisuuksien yhteydessä päätettiin rajata "kulttuuriset ominaisuudet"-käsite kattamaan taiteet, mutta ei muuta "kulttuurillista"
- sovelletaan tätä samaa periaatetta (vrt. myös Katri Seppälän kommentti yllä) muihinkin yhteiskunnalliset/kulttuurit-kategorioihin eli käydään kaikki kulttuuriset-kategoriat läpi ja siirretään sinne kuulumattomat toisaanne
- Tuomas tuottaa Excel-listat kaikista em. kulttuuriset-kategorioista. Aletaan käydä näitä läpi. Tuomas silmäilee läpi yhteiskunnalliset-kategoriat ja tutkii, onko siellä jotain joka kuuluisi nykyisen tulkinnan mukaisesti kulttuuriset-kategorioihin

**Comment by tpalonen** [comment]
Tässä ensinnäkin taulukko, jossa on yhteiskunnalliset*-kategorioiden sellaiset alakäsitteet, joilla on jokin kulttuuri-/taidealan YSA-ryhmä. https://docs.google.com/spreadsheets/d/1GM75dkeXHVV9zsro-NBtHbrslUGtj6HTEJlZ7t7lM58/edit?usp=sharing

Muuta ongelmaa en listassa nähnyt, mutta alla olevat ratkaisut ovat minusta kyseenalaistettavissa:

kirjasodat YK yhteiskunnalliset tapahtumat
taiteilijuus YK yhteiskunnalliset ominaisuudet (+ mentaaliset ominaisuudet)
tekijyys YK yhteiskunnalliset ominaisuudet (+ mentaaliset ominaisuudet)
tyylikaudet YK yhteiskunnalliset ajanjaksot

Mennäänkö kuitenkin edelleen näillä tulkinnoilla? Mitään kulttuurisia ajanjaksojahan ei ole.
