### ISSUE TITLE
Sanakirjamaisia ja puutteellisia huomautuksia

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#200]
_From [mafors...@gmail.com](https://code.google.com/u/100004162283516840686/) on February 17, 2014 16:22:37_
1. What is to be changed/Mitä muutetaan esim. kaavat-käsitteen huomautus 2. Why the change is needed/Miksi muutetaan Nyt löytyy paljon sanakirjasta kopioituja huomautuksia, joissa ei seurata linjausta että aloitetaan huomautusta isolla kirjaimella ja lopetetaan pisteellä, vältetään lyhennyksiä yms. 3. Realized changes/Toteutetut muutokset

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=197_

**Comment by mirmaid** [comment]
Mahdollisesti jaettavat - monimerkityksiset - käsitellään yhdessä ja/tai viedään YSA-kokoukseen.

**Comment by mariaforsen** [comment]
Lista tässä: https://docs.google.com/spreadsheets/d/1igl6qGGXJE0q0s_be_iawWIyuZEze2bFg2ldZlzU6KA/edit#gid=1100133302

**Comment by mirmaid** [comment]
YSO-kokous 27.10.
- kun on käsitelty lista monimerkityksisistä käsitteistä, jatketaan käymällä läpi pienellä kirjaimella olevat huomautukset (mahd. huomautukset jotka ovat vain yhdellä kielellä)

**Comment by mirmaid** [comment]
Kaikki minulle merkityt termit joko ratkaistu, YSEssä tai erillinen issue. (Kirjattu listaan tilanne.)

- listalla visiot-termin kohdalle merkitty: YSO-kokous, vrt. näyt. En löytänyt näistä issueta.

Listalla vielä ALLFO-ongelmia, onko kaikki myös ongelmalistalla tai issueina?

**Comment by tpalonen** [comment]
YSO-kokous 4.11.2016:
- Lisätään seuraava huomautus:
visiot: "Tulevaisuudenkuva, näkymä tai hahmotelma."
- Poistetaan vapautus-käsitteestä lähdetieto.

Edellä oleva taulukko on loppuunkäsitelty. Taulukossa olleet ALLFO-ongelmat on muualla käsiteltävänä.

**Comment by tpalonen** [comment]
Tässä taulukko YSOn suomen-, ruotsin- ja englanninkielisistä huomautuksista, jotka alkavat pienellä kirjaimella. Suomen kielellä näitä on 603, ruotsiksi 43 ja englanniksi 24.

https://docs.google.com/spreadsheets/d/1HRRcEwv1Ph0OYqRHSBrLFeoypxzBttB0od0OO8AP2Ak/edit?usp=sharing

**Comment by mariaforsen** [comment]
Ok ruotsin osalta (puutteelliset ja vanhentuneet ruotsinkieliset huomautukset poistettu).

**Comment by mirmaid** [comment]
Miten käsitellään suomenkieliset?

**Comment by satuniininen** [comment]
Englanninkieliset liittyvät pääasiassa tapauksiin, joissa on ollut pakko käyttää samaa termiä kahdesta eri käsitteestä. Päällekkäisyydestä olisi kuitenkin tarkoitus päästä kokonaan eroon, joten poistelen kommentteja sitä mukaa kun käännökset ratkeavat.

**Comment by tpalonen** [comment]
PÄÄTÖS 14.11.2016:
- Mirja koordinoi suomenkielisten huomautusten läpikäyntiä

**Comment by mirmaid** [comment]
Taulukon keltaiset rivit vielä.

**Comment by YSO-kokous** [comment]
Tehdään uusi issue toiminnan ja tapahtumien määritelmistä. Molempien määritelmässä esiintyy ilmaisu "jokin joka toteutuu", mutta eikö toiminta vaadi kuitenkin tekijän eikä voi toteutua ilman tekijää?

**Comment by mirmaid** [comment]
Ei tarvetta muutoksiin.
