### ISSUE TITLE
keliakiaruokavalio ja gluteeniton ruokavalio

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#247]
_From [satu.nii...@gmail.com](https://code.google.com/u/110842852617286366306/) on March 07, 2014 12:52:32_

1. The problem / Ongelman tausta: Tarvitaanko molemmat? 2. Suggested solution / Ehdotettu ratkaisu:

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=244_

**Comment by mirmaid** [comment]
Ratkaistu jos YSAssa.
