### ISSUE TITLE
tekninen objekti

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#263]
_From [mafors...@gmail.com](https://code.google.com/u/100004162283516840686/) on March 12, 2014 11:21:21_

1. The problem / Ongelman tausta: Nyt kaikilla kielillä yksikössä, onko syytä olla vai pitäisikö muuttaa monikkoon?

Myös muita Secon luomia yksikössä, vaikka sääntöjen mukaan pitäisi olla monikossa. 2. Suggested solution / Ehdotettu ratkaisu:

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=260_

**Comment by tpalonen** [comment]
Tällaiset käsitellään issuessa #548
