### ISSUE TITLE
Mäppäys ja LCSH:n variantit (altlabelit)

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#264]
_From [satu.nii...@gmail.com](https://code.google.com/u/110842852617286366306/) on March 12, 2014 12:28:05_
1. The problem / Ongelman tausta: (sama teksti myös oheisessa liitteessä sisältäen linkit)

Minkälainen painoarvo annetaan LCSH:n varinteille esim. silloin, kun preflabel ei sovi siltauskohteeksi mutta altlabel sopii?

Aihetta sivuttiin 12.12. Yso-kokouksessa, jossa käytiin läpi siltauksen alkuvaiheessa vastaantulleita ongelmia, esim:
@fi Avioparit ; @en spouses ; @LCSH Married people (varianttina Married couples)
-> Käsiteltiin 12.12., päätettiin sillata closeMatch -suhteella.

Tuolloisista yksittäistapauksista ei kuitenkaan pysty vielä muodostamaan kattavaa linjausta (onko ylipäätään mahdollista?), joten keskustelua olisi syytä jatkaa. 

LCSH:ssa käsitteen variantteina käytetään sekä synonyymejä / erilaisia kirjoitusasuja preflabelista esim: 
preflabel "Coppice forests" ; altlabel "Coppice woodlands" ; "Coppices" 

että toisaalta myös alakäsitteiltä vaikuttavia käsitteitä esim. "flour" ja "wheat flour" toistensa variantteina.

Ongelmatyyppejä:

preflabel ja altlabel yhdessä muodostavat YSO-käsitettä laajemman käsitekokonaisuuden:

Esim1
@fi naamiaisasut ; @en fancy dresses ; @LCSH Costume
->  en siltaisi

Esim2
@fi tuholaiskestävyys ; @en pest resistance ; @LCSH Disease and pest resistance 
pest resistance varianttina
->  en siltaisi

Esim3
@fi soveltava taide ; @en applied arts ; @LCSH Decorative arts 
Applied arts varianttina, 
Here are entered comprehensive works on the various art forms having some utilitarian as well as decorative purpose, including furniture, woodwork, silverware, glassware, ceramics, textiles, the decoration of buildings, etc.)
->  en siltaisi

altlabel löytyy YSOsta omana käsitteenään:

Esim1
@fi jauhot ; @en flour ; @LCSH flour 
@fi vehnäjauhot ; @en wheat flour ; @LCSH flour ja sen varianttina wheat flour
(myös hierarkia omituinen)
->  en siltaisi kumpaakaan

vaikea/mahdotonta arvioida, onko variantti vaihtoehtoinen kirjoitusasu / synonyymi vai kokonaan eri käsite:

@fi ksenotransplantaatio ; @en xenotransplantation ; @LCSH Xenografts (xenotransplantations varianttina)
@fi tamašekin kieli ; @en Tuareg language (lexvossa Tuareg languages) ;  @LCSH Tamashek language 2. Suggested solution / Ehdotettu ratkaisu:

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=261_

**Comment by YacoubAgBaye** [comment]
I am a Tamasheq translator who translates Tamasheq to French and French to Tamachak, I am interested in all projects concerning translation especially that of Mali
