### ISSUE TITLE
"Värinpoisto"-käsite eri aloilla

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#270]
_From [satu.nii...@gmail.com](https://code.google.com/u/110842852617286366306/) on March 18, 2014 13:13:08_

1. The problem / Ongelman tausta: Käsite "värinpoisto" vaikuttaisi assosiatiivisten suhteiden perusteella olevan paperiteollisuuden käsite, ryhmää ei ole. 

Käsitettä kuitenkin käytetään muillakin aloilla, esim kampaamoalalla, elintarviketeollisuudessa yms. 2. Suggested solution / Ehdotettu ratkaisu: Tarttisko käsite joko rajata paperiteollisuuteen tai vaihtoehtoisesti kattaa kaikki käyttötarkoitukset lisäämällä assoja.

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=268_

**Comment by mirmaid** [comment]
YSO-kokous 27.10.
- jätetään, poistetaan assosiatiiviset suhteet
- eng. color removal (?)
- lisätään YSAan
