### ISSUE TITLE
kohdentuminen ja allokointi - mitä eroa ja  tarvitaanko molemmat?

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#272]
_From [satu.nii...@gmail.com](https://code.google.com/u/110842852617286366306/) on March 20, 2014 11:51:56_
1. The problem / Ongelman tausta: kohdentuminen Melindassa 56 kertaa
   allokointi Melindassa 95 kertaa

Molemmat englanniksi "allocation"

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=271_

**Comment by mariaforsen** [comment]
Jäi siis ruotsin osalta ratkaisematta.
