### ISSUE TITLE
eroaminen

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#275]
_From [mafors...@gmail.com](https://code.google.com/u/100004162283516840686/) on March 25, 2014 13:54:10_
1. The problem / Ongelman tausta: eroaminen

RT asumusero

Ontologiassa huomautus: sanoutua irti työsuhteestaan, jonkin yhteisön jäsenyydestä tms. {@fi}

Ysa:ssa ST kirkosta eroaminen mutta kuitenkin RT asumusero, avioero, avoero. eikä mitään työstä.

Melindassa paljon avioeroon liittyvää yms. 

Ruotsiksi nyt utträde, mikä sopii näistä lähinnä kirkosta eroamiseen-kontekstiin. Muitakin tarvitaan!

Motissa 5 eri merkitystä ruotsiksi. 2. Suggested solution / Ehdotettu ratkaisu:

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=274_

**Comment by mariaforsen** [comment]
Suhteet edelleen sekalaisia. Tämä ei ole siis ruotsin kannalta tyydyttävä ratkaisu.

**Comment by mariaforsen** [comment]
YSAssa hierarkia parempi, onko tulossa YSOonkin?

**Comment by mirmaid** [comment]
Käytetty: eniten: parisuhteesta (myös paljon aineistoa vanhempien erosta lasten kannalta) (löytyy myös tervapääskyn eroaminen), runsaasti myös: uskonnollisesta tai muusta yhteisöstä, jonkin verran: EU:sta tai EMUsta, vähän: työstä irtisanoutuminen, eroaminen virasta.

**Comment by YSO-kokous** [comment]
Tehdään YSE-ehdotus (jako/ohjaustermit).

**Comment by mirmaid** [comment]
Huom. myös _poistuma_ (Allärs avgång)

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/7003
