### ISSUE TITLE
Valmuskataksonomiassa virhe?

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#277]
_From [satu.nii...@gmail.com](https://code.google.com/u/110842852617286366306/) on March 31, 2014 10:33:04_

1. The problem / Ongelman tausta: Yson hierarkiassa on  valmuskat -> tuoksuvalmuskat -> männyntuoksuvalmuskat

Tuoksuvalmuskasta kuitenkin sanotaan: "Myös nimeä männyntuoksuvalmuska näkee käytettävän erotuksena lähilajista kuusentuoksuvalmuskasta. Virallinen suomenkielinen nimi on kuitenkin tuoksuvalmuska." (lähde: http://pinkka.helsinki.fi/virtuaalikasvio/plant.php?id=14007 )

Lisäksi tuoksuvalmuskat on käännetty ruotsiksi Tricholoma caligatum, vaikka kyseessä pohjoismaisen tuoksuvalmuskan Välimeren alueella esiintyvä sisarlaji ( fi.wikipedia.org/wiki/Männyntuoksuvalmuska ) 2. Suggested solution / Ehdotettu ratkaisu: Poistetaan männyntuoksuvalmuska ; korjataan tuoksuvalmuskan ruotsinnos

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=276_

**Comment by mirmaid** [comment]
Ratkaistu YSAssa.
