### ISSUE TITLE
(valokuvaus) + (elokuvaus) tyyppiset koostekäsitteet

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#281]
_From [tuomas.p...@gmail.com](https://code.google.com/u/114029607375739102692/) on March 31, 2014 15:13:22_

1. The problem / Ongelman tausta: - seuraavat koostekäsitteet:
  - digitaalikuvaus, trikkikuvaus, vedenalainen kuvaus
    
- näin tarkka hienojako ei liene tarpeen 2. Suggested solution / Ehdotettu ratkaisu: - ehdotetaan kunkin tapauksen kohdalla koostekäsitteiden purkamista, sulkutarkenteen poistamista ja koosteen korvaamista monihierarkialla (jäljelle jääneelle käsitteelle lisätään poistetun käsitteen hierarkia).

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=280_

**Comment by mirmaid** [comment]
Onko toteutettu? @satuniininen

**Comment by satuniininen** [comment]
Enkku tehty
