### ISSUE TITLE
Kotiutuminen ja kotiutus - mitä eroa?

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#289]
_From [satu.nii...@gmail.com](https://code.google.com/u/110842852617286366306/) on April 10, 2014 10:38:38_
1. The problem / Ongelman tausta: kotiutus - Melindassa 151 kertaa, pääasiassa sairaalasta kotiutuksen kontekstissa

kotiutuminen - 14 kertaa, sairaalasta kotiutumista ja (maahan)muuttajien kotiutumista 2. Suggested solution / Ehdotettu ratkaisu:

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=288_

**Comment by mirmaid** [comment]
Muutosehdotus YSEssä.
