### ISSUE TITLE
Aatteet vs. asenteet vs. ideologiat

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#299]
Ongelman tausta: YSOssa rasismi on asenne, antirasismi on aate. Epäjohdonmukaisuutta aatteet vs. asenteet vs. ideologiat -jaottelussa, rajanvetoa vaikea tehdä. YSAssa "aatteiden" alla ei mitään käsitteitä.

YSOssa ideologiat aatteiden alakäsite, vaikka yleisesti ideologiat laajempi, "aatejärjestelmä"...

YSO:
asenteet http://www.yso.fi/onto/yso/p5619
aatteet http://www.yso.fi/onto/yso/p220
ideologiat  http://www.yso.fi/onto/yso/p216

YSA:
asenteet http://www.yso.fi/onto/ysa/Y94725
aatteet http://www.yso.fi/onto/ysa/Y107785
ideologiat http://www.yso.fi/onto/ysa/Y101775

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=298_

**Comment by mirmaid** [comment]
YSO-kokous 6.11.2015
- ideologiat ei aatteiden alakäsite. Kaikille pitää päättää yläkäsitteet, yhteiskunnallinen vai kulttuurinen?

**Comment by MikkoAleksanteri** [comment]
Lähtökohtaisesti ideologia on laajempi kuin aate kaikkien saatavilla olevien määritelmien mukaan. Rajanveto sen välillä, onko joku tietty käsite ideologia vai aate, on kuitenkin mahdotonta. Vaihtoehtoisia ratkaisumalleja:

a. Siirretään kaikki ideologioiden alakäsitteet aatteiden alle

b. Siirretään kaikki ideologioiden _ja_ aatteiden alakäsitteet esim. teoriat (http://www.yso.fi/onto/yso/p127) -käsitteen alle

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus a: siirretään kaikki ideologioiden alakäsitteet aatteiden alle
Lisäksi muutetaan yläkäsitteet seuraavasti:
aatteet YK yhteiskunnalliset objektit
ideologiat YK yhteiskunnalliset objektit
