### ISSUE TITLE
Väreihin liittyvä käsitteistö

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#306]
_From [SNyk...@gmail.com](https://code.google.com/u/112439428317292360191/) on April 17, 2014 16:31:38_

1. The problem / Ongelman tausta: YSOssa käsitteet "värit (aine)" ja "väri (ominaisuus)", ja niiden alla värien nimityksiä. (Lisäksi myös mm. "väriaineet".) Väreihin liittyvä käsitteistö tulisi käydä läpi kokonaisuutena ja miettiä jakoa etenkin tiedonhaun kannalta. 2. Suggested solution / Ehdotettu ratkaisu:

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=305_

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 4.2.2015

korjataan ysossa ysaa vastaavaksi

**Comment by tpalonen** [comment]
Tein päätetyt muutokset. Alla olevilla ei YSAssa ole LT:tä, mutta YSOssa on seuraavat:

ihonväri LT väri (ominaisuudet)
väriaineet LT aine käytön mukaan
