### ISSUE TITLE
kielet (asema tai alkuperä)

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#309]
_From [mafors...@gmail.com](https://code.google.com/u/100004162283516840686/) on April 22, 2014 11:39:10_
1. The problem / Ongelman tausta: Onko yllä oleva sulkutarkenne selkeä ja oikein? Mihin tarkalleen viittaa?
   Ruotsiksi valittu språk (typer)

Löytyy myös yksikössä oleva kieli (kielenkäyttö). 2. Suggested solution / Ehdotettu ratkaisu:

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=308_

**Comment by mariaforsen** [comment]
Millä perusteella on poistettu tarkenne myös "kieli"-termiltä (luultavasti aiemman, nykyään vanhentuneen säännön perusteella) ? Sehän voi yhtä hyvin viitata kieleen ilmiönä että kieleen "jonakin kielenä", sekä sen lisäksi kieleen ruumiinosana. Niin kauan kuin pidetään molemmat sanastossa olisi varmaan syytä pitää tarkenne yksikkömuodolla (nykyisten sääntöjemme mukaan).

**Comment by mirmaid** [comment]
Käsittelyssä myös laajemmassa issuessa https://github.com/NatLibFi/Finto-data/issues/536
