### ISSUE TITLE
Oppiaineet

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#311]
_From [livir...@gmail.com](https://code.google.com/u/102090373205572715207/) on April 22, 2014 13:47:04_
1. The problem / Ongelman tausta: Mitä kaikkea kootaan tämän alle? Täällä ei voi olla kaikkia oppiaineita(?), mutta jotenkin pitäisi voida ilmaista, minkälaisia tänne kerätään.  Nyt täällä on esim. äidinkieli (oppiaineet) (peruskoulussa ja lukiossa on oppiaine nimeltä ”äidinkieli ja kirjallisuus”), mutta ei esim. matematiikkaa eikä liikuntaa. Kuvaamataidon (LT taideaineet) nykyinen nimitys koulussa on kuvataide, mutta se ei käy ilmi mistään. - Maantuntemus voisi olla ennemminkin suoraan tieto-käsitteen alla. 2. Suggested solution / Ehdotettu ratkaisu:

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=310_

**Comment by mirmaid** [comment]
Ainakin katsomusaineet, reaaliaineet, taideaineet, taitoaineet ja valinnaisaineet sopivat hyvin tänne. Myös sivuaineet olisi ok? 

En kyllä keksi muillekaan nykyistä parempaa yläkäsitettä ja minusta huomautus riittää kertomaan miksi kaikki oppiaineet eivät löydy listasta. Sen sijaan on ehkä vähän kummallista että tieteet löytyvät hierarkiassa kohdasta _yhteiskunnalliset järjestelmät_ kun taas oppiaineet ovat _tiedon_ alla, _yhteiskunnallisten objektien_ hierarkiassa.

**Comment by mirmaid** [comment]
Ehdotus: sivuaineet YK oppiaineet

Voiko tieteiden ja oppiaineiden yläkäsitettä muuttaa samaksi?

**Comment by mirmaid** [comment]
YSO-kokous 24.3.2017:

- sivuaineet oppiaineiden alle YSAssa
- oppiaineet RT tieteet
