### ISSUE TITLE
Käsitteitä ilman labelia

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#314]
_From [tuomas.p...@gmail.com](https://code.google.com/u/114029607375739102692/) on April 24, 2014 13:03:49_

What steps will reproduce the problem? YSOsta löytyy sienet-hierarkiasta kolme käsitettä (groupconcepteja) joilla ei ole labelia. Ongelma on ilmeisesti antiikkinen, koska niillä ei ole labelia myöskään ONKI3:ssa.

yso:p52006
yso:p24943
yso:p24841

Kaikki ovat sienet-käsitteen alakäsitteitä ja kaikilla on 2-3 alakäsitettä (esim. homesienet, hiivasienet, jäkälät). Nämä alakäsitteet näkyvät normaalisti ONKI3:ssa ja Fintossa sienet-käsitteen alla. What is the expected output? What do you see instead? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=313_

**Comment by MikkoAleksanteri** [comment]
Käsitteet poistettu.
