### ISSUE TITLE
Aikamääreet YSO-käsitteille

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#32]
_From [osma.suominen@helsinki.fi](https://code.google.com/u/osma.suominen@helsinki.fi/) on November 15, 2013 09:49:59_

Ainakin EVN:ssä ja PoolPartyssa käsitteille tulee automaattisesti päivittyvä tieto luonti- ja muutosajoista. Näiden perusteella on helppo tuottaa listauksia tyyliin "uusimmat käsitteet" ja "muuttuneet käsitteet".

Pitäisi selvittää voisiko tällaiset automaattisesti päivittyvät timestampit tuottaa myös TBC:llä. Ainakin tämän perusteella jotain tällaista tukea on olemassa TBC:ssä: http://topquadrantblog.blogspot.fi/2009/09/creating-and-managing-metadata-about.html

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=29_

**Comment by osma** [comment]
Tehty, kts. http://jira.kansalliskirjasto.fi/browse/FINTO-196
