### ISSUE TITLE
lämpöpatterit (lämmönvaihtimet) + lämpöpatterit (lämmityslaitteet)

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#327]
_From [tuomas.p...@gmail.com](https://code.google.com/u/114029607375739102692/) on May 06, 2014 17:18:09_

1. The problem / Ongelman tausta: - vesilämmitykseen liittyvä patteri ja sähköpatteri; hierarkkisesti lähellä toisiaan; monihierarkia riittäisi 2. Suggested solution / Ehdotettu ratkaisu: - monihierarkia
- koostekäsitteen poistaminen

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=326_

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 4.2.2015

korjataan vielä:

lämmönvaihtimet ST lämmityslaitteet ST lämpöpatterit ja
lämmönvaihtimet ST jäähdytyslaitteet 

HUOM! ks myös issue #429
