### ISSUE TITLE
"communication" englanninkielisenä prefLabelina kahdella käsitteellä

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#334]
_From [sini.pes...@gmail.com](https://code.google.com/u/106658693216861444572/) on May 07, 2014 15:59:30_

1. The problem / Ongelman tausta: Kahdella YSO-käsitteellä on sama englanninkielinen prefLabel "communication"

viestintä: http://www.yso.fi/onto/yso/p36 tiedonvälitys: http://www.yso.fi/onto/yso/p870 2. Suggested solution / Ehdotettu ratkaisu: Toisen englanninkielisen prefLabelin vaihtaminen.

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=333_

**Comment by tpalonen** [comment]
Eikös tällainen käytäntö ole todettu ookooksi? Suljetaanko issue?

**Comment by satuniininen** [comment]
Joo, voi sulkea.
