### ISSUE TITLE
ääni / äänet alakäsitteet

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#349]
_From [mafors...@gmail.com](https://code.google.com/u/100004162283516840686/) on May 21, 2014 13:40:55_
1. The problem / Ongelman tausta: Kun käsittelimme ruotsin ongelma ljud/röst todettiin että ääni viittaa yleensä röst sanaan ja äänet yleensä ljud sanaan asiasanoituskontekstissa. Nyt on kuitenkin hierarkia sekaisin ja ruotsin osalta aivan väärä. Ellei haluta asialle tehdä mitään, täytyy varmaan miettiä uudestaan miten ratkaista röst/ljud -ongelmaa. 

Pitäisikö myös lisätä huomautus käytöstä? 

Toisaalta nyt tulee vielä puheäänikin (YSAlta). 2. Suggested solution / Ehdotettu ratkaisu: ääni = röst

suppeammat: -

äänet = ljud 

suppeammat: luonnonäänet, infraääni, melu, ultraääni

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=348_

**Comment by mirmaid** [comment]
ongelma 1, röst

Tähän tarvitaan siis suomenkielinen vastine, koska puheääni ei kata kaikkia tapauksia ja ljud ei voi viitata ihmisen ääneen. 

_ihmisen ääni_ kuulostaa kuvailuterminä ainakin joissakin tapauksissa vieraannuttavalta, ikäänkuin sitä tarkasteltaisiin suhteessa muihin lajeihin tai jotenkin abstraktina ilmiönä. 
_ääni (ihmiset)_
_ääni (ihmisen)_

Esim. 
lapset - kielellinen kehitys - ihmisen ääni
lapset - kielellinen kehitys - ääni (ihmiset)
lapset - kielellinen kehitys - ääni (ihmisen)

opiskelijat - ihmisen ääni - ongelmat
opiskelijat - ääni (ihmiset) - ongelmat
opiskelijat - ääni (ihmisen) - ongelmat

siitepölyallergia - ihmisen ääni - äänentuotto
siitepölyallergia - ääni (ihmiset) - äänentuotto
siitepölyallergia - ääni (ihmisen) - äänentuotto

**Comment by mirmaid** [comment]
ongelma 2, ljud

Ljud on siis sekä yksikkö että monikko, joten tarkenteita tarvitaan sekä suomeksi että ruotsiksi paitsi siinä tapauksessa, että jätetään suomeksi vain monikollinen _äänet_.

**Comment by YSO-kokous** [comment]
Kaikki tutkivat asiaa vielä Melindan viitteiden kautta, ratkaistaan seuraavassa kokouksessa.

**Comment by satuniininen** [comment]
**ongelma 1, röst**

Viides mahdollinen ratkaisu olisi _ääni (ihmisääni)_
Kannatan sulkutarkenteellista muotoa, sillä _ihmisen ääni_ (samoin kuin _ihmisääni_) näyttää kuvailuissa oudolta ja sikäli myös harhaanjohtavalta, että se vaikuttaisi painottavan väärää aspektia käsitteestä.

**Comment by satuniininen** [comment]
**ongelma 2, ljud**

Melindan perusteella näyttäisi, että yksiköllinen _ääni_ sopii erityisen hyvin aineistoihin, joissa käsitellään ääntä aika abstraktilla tasolla, eräänlaisena ilmiönä. Esim. juuri tuo edellä mainittu fysiikan näkökulma sekä myös tekniset kontekstit, joissa ääntä tallennetaan, editoidaan, siirrettään, lähetetään jne.
Monikollinen _äänet_ taas sopii parhaiten konkreettisempiin käyttötapauksiin, joissa käsitellään esim. äänimaisemaa, ympäristön ääniä jne.

Jos sanastoon jäisi pelkästään monikollinen äänet, voidaan _äänet (harha-aistimukset) KÄ harha-aistimukset_ -ohjauksen lisäksi ohjata myös 

- äänet (fysiikka) KÄ ääniaallot (tulisi uutena sanastoon)
- äänet (tekniikka) KÄ äänitekniikka tai äänenkäsittely

Nämä auttaisivat ainakin seuraavissa käyttöyhteyksissä, joihin monikollinen äänet istuu huonosti:

äänenkäsittely - digitaalitekniikka - ääni - miksaus - musiikki >
äänenkäsittely - digitaalitekniikka - äänitekniikka - miksaus - musiikki

fysiikka - aaltoliike - ääni - sähkömagnetismi >
fysiikka - aaltoliike - ääniaallot - sähkömagnetismi

**Comment by MikkoAleksanteri** [comment]
Ehdotus:

**1. röst = ihmisääni = voice
2. ljud = äänet = sounds**

Kakkoskohtaan lisäksi Satun ehdottamat ohjaukset.

**Comment by YSO-kokous** [comment]
Ongelma 1: YSA-kokoukseen ratkaisuehdotus 

ääni (ihmisen ääni) / ääni (ihmisääni) 
ääni (ihmiset/ihminen)
ihmisen ääni / ihmisääni

**Comment by YSO-kokous** [comment]
Ongelma 2: äänet (fysikaaliset ilmiöt)

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/5428
https://github.com/Finto-ehdotus/YSE/issues/5427
