### ISSUE TITLE
"ammatit"-käsitteen alla myös muita kuin ammatteja

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#352]
_From [mikko.al...@gmail.com](https://code.google.com/u/110439846636887938592/) on May 21, 2014 16:38:04_
1. The problem / Ongelman tausta: osa ammateista http://finto.fi/yso/fi/page/p1179 tulisi siirtää suoraan "toimintaan liittyvään rooliin", ks. yso-kokouksen muistiinpanot 21.5.2014 https://www.kiwi.fi/pages/viewpage.action?pageId=19470084

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=351_

**Comment by mirmaid** [comment]
YSO-kokous 27.10.
- yksi mahdollinen ratkaisu olisi siirtää kaikki alakäsitteet pois ammattien alta (paitsi ammatit-loppuiset)? (suoraan toimintaan liittyvän roolin alle)

**Comment by mirmaid** [comment]
Ehdotetaan yllä esitettyä muutosta, käsitteille RT ammatit. Viikkopalaveri/OY(/jos tarpeen?).

**Comment by mirmaid** [comment]
OY:n päätös: https://www.kiwi.fi/pages/viewpage.action?pageId=103196240
YSOn "ammatit" käsite voidaan siirtää yhteiskunnallisiin objektit -käsitteen alle.
YSO-toimitus ryhmittelee osa nykyisistä ammateistä alakäsitteistä esim. "ammattiin liittyvä rooli" -käsitteen alle. Ne jotka eivät ole ammatteja toimitus voi siirtää suoraan "toimintaan liittyvä rooli" alle.

**Comment by mirmaid** [comment]
Siirretään ammatit-käsite, luodaan tilalle hierarkisoiva käsite "ammattiin tai tehtävään liittyvä rooli". Ei siirretä alakäsitteitä muualle, lisätään niille RT ammatit.

**Comment by mirmaid** [comment]
Käydään läpi työpajapäivänä 30.1.2024.

**Comment by fantsby-m** [comment]
Matti A-J

Ehdotukset siirrettäviksi:

akateemikot
alaiset
ammatinharjoittajat
ammattilaiset
asevelvolliset
asiantuntijat
astrologit
au pairit
dosentit
druidit
elinkeinonharjoittajat
ennustajat
esittelijät (päätöksentekomenettely)
gladiaattorit
gurut
haamukirjoittajat
haastattelijat
haavurit
hallitsijat
harjoittelijat
hovinaiset
hovioikeudenneuvokset
intiaanipäälliköt
joulupukit

**Comment by tpalonen** [comment]
Mikä lienee tässä nykyisessä visiossa kategorioiden _toimintaan liittyvä rooli_ ja _ammattiin tai tehtävään liittyvä rooli_ ero? Kalskahtavat minusta vahvasti päällekkäisiltä. Melkeinpä kaikki tuossa T-Ö-setissä voisivat mennä kumpaan vain. Ehkä tällaisiä merkitykseltään päällekkäisiä kategorioita ei kannata YSOon ottaa vaan valitaan jompi kumpi?

Seuraavat käsitteet voisi minusta joka tapauksessa siirtää toisaanne:

_toimet > yhteiskunnalliset objektit_ [vrt. virat]
_toipilaat > terveydentilaan liittyvä rooli
valkoiset (Suomen sisällissota) > aatteelliseen ryhmään liittyvä rooli
valkoiset (Venäjän sisällissota) > aatteelliseen ryhmään liittyvä rooli
viikingit > muinaiskansat
yksilö > yhteiskunnalliset objektit_ [vrt. kansa (kansanihmiset)]

Lisäksi sain villin idean, jossa yhdistettäisiin seuraavat hierarkisoivat käsitteet yhdeksi: _arvoon liittyvä rooli, oikeudelliseen asemaan liittyvä rooli ja sosioekonomiseen asemaan liittyvä rooli._ Otsikoksi tälle uudelle yhdistelmäkategorialle esim. **asemaan liittyvä rooli**.
Tänne voisi sitten siirtää nämä tuosta minun T-Ö-setistä:

_teloitetut
tutkinnon suorittaneet [alakäsitteineen]
tyttöystävät
työnantajat (?)
valamiehet
valtionpäämiehet
valtuutetut
vapaaehtoiset
varahenkilöt
varapresidentit
vartiopäälliköt (?)
vasta-alkajat
vastavalmistuneet
vihkiparit
viholliset
viranhaltijat
virkamiehet
voittajat
vuokranantajat (?)
yhteiskunnalliset vaikuttajat
yksinhuoltajat
ystävät
äänestäjät (?)_

Joissakin tapauksissa toiminta/tehtävä ja asema menevät päällekkäin eli tietyssä asemassa olevalla on myös tietty tehtävä. Mutta tämä ongelma oli olemassa joka tapauksessa jo ennen tätä ehdotustani. Tällaisellä yhdistämisellä saataisiin vähän hienojakoa pois rooli-hierarkiasta.

**Comment by mirmaid** [comment]
^ Muinaiskansat on väestöryhmään liittyvän roolin alla, mutta kansat väestöryhmien alla, eli eri päähaaroissa. Aika paha ristiriita...

**Comment by mirmaid** [comment]
Siirretään (ehdotus):
* kasvattajat
* kauneuskuningattaret
* kaupanvahvistajat
* keksijät
* kenraalikuvernöörit
* kerjäläiset
* kirjurit
* kissankasvattajat
* koirankasvattajat
* kolumnistit
* konsulit (Rooman valtakunta)
* korkeimman hallinto-oikeuden presidentit
* kotitalousneuvojat
* kuraattorit (kulttuuri)
* kustantajat
* kykyjenetsijät
* laamannit
* lobbarit
* lotat
* luennoitsijat
* luottamushenkilöt
* lähetit
* maahantuojat
* mainostajat
* matkanjärjestäjät
* meediot
* ministerit
* missit

Ehkä (?):
kaasot
kerääjät
koehenkilöt
kollaboraattorit
konkistadorit
koululaiset
kummit
lehdistöneuvokset (vastaavat?)
luonnonsuojelijat
löytöretkeilijät
merenkulkijat
metsästäjät 

Ei
kadonneet
kannattajat
kertoja
kirkkoon kuulumattomat
kollegat
kuluttajat
kummilapset
kuninkaalliset
kuolleet
kylähullut
kävijät
käyttäjät 
lahjoittajat
loikkarit
lukijat
lähimmäinen
maahanmuuttajat
maallemuuttajat
maallikot
maaltamuuttajat
maastamuuttajat
matkailijat
matkustajat
mesenaatit
metsästäjä-keräilijät
mielipidejohtajat
monisynnyttäjät
muusat

**Comment by ilona-x** [comment]
N-S:

Ehdotukset

**siirretään -> ammattiin tai tehtävään liittyvä rooli**

narrit 
näyttötutkintomestarit 
oikeusneuvokset
omahoitajat 
opetusneuvokset
oraakkelit (vrt. ennustajat)
paimenet 
paimentolaiset 
pakinoitsijat 
parantajat (vrt. noidat, šamaanit)
parapsykologit 
partisaanit (vrt. sissit)
pelastusarmeijan upseerit 
poliitikot
poliittiset johtajat
prokuraattorit  (vrt. virkamiehet)
prostituoidut 
puheenjohtajat 
puolueaktiivit
pääsihteerit
päättäjät 
raatimiehet 
rakennuttajat
rauhanneuvottelijat
ruukinpatruunat
santarmit 
sijaiset 
sijaisvanhemmat 
sijoittajat 
sissit (vrt. partisaanit)
sofistit 
somevaikuttajat 
sosiaalipoliitikot 
sotaveteraanit
sotaväen päälliköt 
sotilaat
sotilashenkilöt
sovittelijat


**siirretään muualle?**

noviisit ? pitäisikö olla samassa paikassa kuin munkit (uskonto) & nunnat eli uskontoon liittyvä rooli 
punaiset (Suomen sisällissota) -> aatteelliseen ryhmään liittyvä rooli  (vrt. valkoiset)
punaiset (Venäjän sisällissota) -> aatteelliseen ryhmään liittyvä rooli (vrt. valkoiset)
senaattorit -> siiretään luottamus-henkilöt käsitteen alle? (vrt. kansanedustajat)

**epävarmat** 

noidat ? (vrt. parantajat, šamaanit)
opiskelijat ? (vrt. koululaiset)
oppilaat ? (vrt. koululaiset)
perinteentaitajat ?
šamaanit ? (vrt. parantajat, noidat)
šeikit ?
sotilaspojat ?
soturit ?


**ei siirretä**

naistenmiehet 
nobelistit (vrt. voittajat)
originellit 
osallistujat 
partiolaiset 
pelaajat 
pirkkalaiset (historia) 
poikaystävät (vrt. tyttöystävät)
puukkojunkkarit 
pyhiinvaeltajat 
pyöräilijät 
päihdeongelmaiset 
rahoittajat 
rakastajat 
rakastajattaret 
rikoksentekijät 
rikolliset 
roolimallit
sankarit 
seikkailijat 
silminnäkijät

**Comment by mirmaid** [comment]
alaiset YK toimintaan liittyvä rooli
dosentit YK arvoon liittyvä rooli
teloitetut > kuolleet
toimet > yhteiskunnalliset objektit
toipilaat > terveydentilaan liittyvä rooli
valkoiset (Suomen sisällissota) > aatteelliseen ryhmään liittyvä rooli
valkoiset (Venäjän sisällissota) > aatteelliseen ryhmään liittyvä rooli
viikingit > toimintaan liittyvä rooli
yksilö > yhteiskunnalliset objektit (lisäksi ryhmä 00 Yleistermit)

muinaiskansat > issue

**Comment by mirmaid** [comment]
Kirjataan yllä ehdotetut kriteerit hierarkisoivan käsitteen editorial noteen. Muutetaan nimi > ammattiin tai työtehtävään. Käydään läpi aakkoset uudelleen.

**Comment by mirmaid** [comment]
Sprintti 10.4.2024
- uskonnolliset johtajat: toinen YK uskontoon liittyvä rooli (samoin papit)
- uskontoon liittyvä rooli: mitä pitäisi vielä muualta lisätä tänne (tuplahierarkia) ja toisin päin mitkä täällä ovat myös ammatteja?

**Comment by mirmaid** [comment]
Pitäisikö olla vielä lisäkriteeri "käsite kuvaa tehtävän luonnetta", jos ei haluta että esim. kollegat tulee tähän jaotteluun?

**Comment by ilona-x** [comment]
agitaattorit
    akateemikot
    aktivistit
    alaiset
    alumnit
    ammatinharjoittajat
    ammatit
    ammattilaiset
    asevelvolliset
    asiakkaat
    asiantuntijat
    astrologit
    asukkaat
    ateistit
    au pairit
    autoilijat
    beatnikit
    bestmanit
    bloggaajat
    boheemit
    desantit
    diginatiivit
    diginomadit
    dosentit
    druidit
    edelläkävijät
    ehdokkaat
    ekspatriaatit
    elinkeinonharjoittajat
    ennustajat
    ensisynnyttäjät
    epäjumalat
    erakot
    erilaiset oppijat
    esiintyjät
    esittelijät (päätöksentekomenettely)
    esittäjät
    gladiaattorit
    gurut
    haamukirjoittajat
    haastattelijat
    haavurit
    hakijat
    hakkerit
    hallitsijat
    harjoittelijat
    harrastajat
    henkilöt
    hovinaiset
    hovioikeudenneuvokset
    huijarit
    idolit
    ihailijat
    imitaattorit
    informantit
    intiaanipäälliköt
    jalankulkijat
    joogit
    joulupukit
    julkaisijat
    järjestöaktiivit
    jäsenet
    kaasot
    kadonneet
    kannattajat
    kasvattajat (lasten ja nuorten)
    kauneuskuningattaret
    kaupanvahvistajat
    keksijät
    kenraalikuvernöörit
    kerjäläiset
    kertoja
    kerääjät
    kirjurit
    kirkkoon kuulumattomat
    kissankasvattajat
    koehenkilöt
    koirankasvattajat
    kollaboraattorit
    kollegat
    kolumnistit
    konkistadorit
    konsulit (Rooman valtakunta)
    korkeimman hallinto-oikeuden presidentit
    kotitalousneuvojat
    koululaiset
    kuluttajat
    kummilapset
    kummit
    kuninkaalliset
    kuolleet
    kuraattorit (kulttuuri)
    kustantajat
    kykyjenetsijät
    kylähullut
    kävijät
    käyttäjät
    laamannit
    lahjoittajat
    lehdistöneuvokset
    lobbarit
    loikkarit
    lotat
    luennoitsijat
    lukijat
    luonnonsuojelijat
    luottamushenkilöt
    lähetit
    lähimmäinen
    löytöretkeilijät
    maahanmuuttajat
    maahantuojat
    maallemuuttajat
    maallikot
    maaltamuuttajat
    maastamuuttajat
    mainostajat
    matkailijat
    matkanjärjestäjät
    matkustajat
    meediot
    merenkulkijat
    mesenaatit
    metsästäjä-keräilijät
    metsästäjät
    mielipidejohtajat
    ministerit
    missit
    monisynnyttäjät
    muusat
    naistenmiehet
    narrit
    nobelistit
    noidat
    noviisit
    näyttötutkintomestarit
    oikeusneuvokset
    omahoitajat
    omaishoitajat
    opetusneuvokset
    opiskelijat
    oppilaat
    oraakkelit
    originellit
    osallistujat
    paimenet
    paimentolaiset
    pakinoitsijat
    parantajat
    parapsykologit
    partiolaiset
    partisaanit
    pelaajat
    pelastusarmeijan upseerit
    perinteentaitajat
    pirkkalaiset (historia)
    poikaystävät
    poliitikot
    poliittiset johtajat
    prokuraattorit
    prostituoidut
    puheenjohtajat
    punaiset (Suomen sisällissota)
    punaiset (Venäjän sisällissota)
    puolueaktiivit
    puukkojunkkarit
    pyhiinvaeltajat
    pyöräilijät
    päihdeongelmaiset
    pääsihteerit
    päättäjät
    raatimiehet
    rahoittajat
    rakastajat
    rakastajattaret
    rakennuttajat
    rauhanneuvottelijat
    rikoksentekijät
    rikolliset
    roolimallit
    ruukinpatruunat
    šamaanit
    sankarit
    santarmit
    šeikit
    seikkailijat
    senaattorit
    sijaiset
    sijaisvanhemmat
    sijoittajat
    silminnäkijät
    sissit
    sofistit
    somevaikuttajat
    sosiaalipoliitikot
    sotaveteraanit
    sotaväen päälliköt
    sotilaat
    sotilashenkilöt
    sotilaspojat
    soturit
    sovittelijat
    taiteilijat
    taloudenhoitajat (yhdistykset)
    tarkka-ampujat
    tavarantoimittajat
    tehtailijat
    teloitetut
    teologit
    terroristit
    tiedontuottajat
    tiernapojat
    tieteentekijät
    tietäjät
    tilaajat
    toimet
    toimihenkilöt
    toimijat
    toimitsijat
    toipilaat
    tricksterit
    tugeenit
    tukihenkilöt
    tuottajat
    tutkinnon suorittaneet
    tyttöystävät
    työnantajat
    työntekijät
    työparit
    työtoverit
    urheilijat
    vakoilijat
    valamiehet
    valkoiset (Suomen sisällissota)
    valkoiset (Venäjän sisällissota)
    valmistajat
    valtaneuvokset (Ruotsi)
    valtionpäämiehet
    valtuutetut
    vapaaehtoiset
    vapaustaistelijat
    varahenkilöt
    varapresidentit
    vartiopäälliköt
    vasta-alkajat
    vastavalmistuneet
    vihkiparit
    viholliset
    viikingit
    viranhaltijat
    virkamiehet
    vloggaajat
    voittajat
    vuokranantajat
    yhteiskunnalliset vaikuttajat
    yksilö
    yksinhuoltajat
    ystävät
    äänestäjät

**Comment by ilona-x** [comment]
agitaattorit
akateemikot
aktivistit
alaiset
alumnit
ammatinharjoittajat
ammatit
ammattilaiset
asevelvolliset
asiakkaat
asiantuntijat
astrologit
asukkaat
ateistit
au pairit
autoilijat
beatnikit
bestmanit
bloggaajat
boheemit
desantit
diginatiivit
diginomadit
dosentit
druidit
edelläkävijät
ehdokkaat
ekspatriaatit
elinkeinonharjoittajat
ennustajat
ensisynnyttäjät
epäjumalat
erakot
erilaiset oppijat
esiintyjät
esittelijät (päätöksentekomenettely)
esittäjät
gladiaattorit
gurut
haamukirjoittajat
haastattelijat
haavurit
hakijat
hakkerit
hallitsijat
harjoittelijat
harrastajat
henkilöt
hovinaiset
hovioikeudenneuvokset
huijarit
idolit
ihailijat
imitaattorit
informantit
intiaanipäälliköt
jalankulkijat
joogit
joulupukit
julkaisijat
järjestöaktiivit
jäsenet
kaasot
kadonneet
kannattajat
kasvattajat (lasten ja nuorten)
kauneuskuningattaret
kaupanvahvistajat
keksijät
kenraalikuvernöörit
kerjäläiset
kertoja
kerääjät
kirjurit
kirkkoon kuulumattomat
kissankasvattajat
koehenkilöt
koirankasvattajat
kollaboraattorit
kollegat
kolumnistit
konkistadorit
konsulit (Rooman valtakunta)
korkeimman hallinto-oikeuden presidentit
kotitalousneuvojat
koululaiset
kuluttajat
kummilapset
kummit
kuninkaalliset
kuolleet
kuraattorit (kulttuuri)
kustantajat
kykyjenetsijät
kylähullut
kävijät
käyttäjät
laamannit
lahjoittajat
lehdistöneuvokset
lobbarit
loikkarit
lotat
luennoitsijat
lukijat
luonnonsuojelijat
luottamushenkilöt
lähetit
lähimmäinen
löytöretkeilijät
maahanmuuttajat
maahantuojat
maallemuuttajat
maallikot
maaltamuuttajat
maastamuuttajat
mainostajat
matkailijat
matkanjärjestäjät
matkustajat
meediot
merenkulkijat
mesenaatit
metsästäjä-keräilijät
metsästäjät
mielipidejohtajat
ministerit
missit
monisynnyttäjät
muusat
naistenmiehet
narrit
nobelistit
noidat
noviisit
näyttötutkintomestarit
oikeusneuvokset
omahoitajat
omaishoitajat
opetusneuvokset
opiskelijat
oppilaat
oraakkelit
originellit
osallistujat
paimenet
paimentolaiset
pakinoitsijat
parantajat
parapsykologit
partiolaiset
partisaanit
pelaajat
pelastusarmeijan upseerit
perinteentaitajat
pirkkalaiset (historia)
poikaystävät
poliitikot
poliittiset johtajat
prokuraattorit
prostituoidut
puheenjohtajat
punaiset (Suomen sisällissota)
punaiset (Venäjän sisällissota)
puolueaktiivit
puukkojunkkarit
pyhiinvaeltajat
pyöräilijät
päihdeongelmaiset
pääsihteerit
päättäjät
raatimiehet
rahoittajat
rakastajat
rakastajattaret
rakennuttajat
rauhanneuvottelijat
rikoksentekijät
rikolliset
roolimallit
ruukinpatruunat
šamaanit
sankarit
santarmit
šeikit
seikkailijat
senaattorit
sijaiset
sijaisvanhemmat
sijoittajat
silminnäkijät
sissit
sofistit
somevaikuttajat
sosiaalipoliitikot
sotaveteraanit
sotaväen päälliköt
sotilaat
sotilashenkilöt
sotilaspojat
soturit
sovittelijat
taiteilijat
taloudenhoitajat (yhdistykset)
tarkka-ampujat
tavarantoimittajat
tehtailijat
teloitetut
teologit
terroristit
tiedontuottajat
tiernapojat
tieteentekijät
tietäjät
tilaajat
toimet
toimihenkilöt
toimijat
toimitsijat
toipilaat
tricksterit
tugeenit
tukihenkilöt
tuottajat
tutkinnon suorittaneet
tyttöystävät
työnantajat
työntekijät
työparit
työtoverit
urheilijat
vakoilijat
valamiehet
valkoiset (Suomen sisällissota)
valkoiset (Venäjän sisällissota)
valmistajat
valtaneuvokset (Ruotsi)
valtionpäämiehet
valtuutetut
vapaaehtoiset
vapaustaistelijat
varahenkilöt
varapresidentit
vartiopäälliköt
vasta-alkajat
vastavalmistuneet
vihkiparit
viholliset
viikingit
viranhaltijat
virkamiehet
vloggaajat
voittajat
vuokranantajat
yhteiskunnalliset vaikuttajat
yksilö
yksinhuoltajat
ystävät
äänestäjät

**Comment by mirmaid** [comment]
Listataan tähän vielä uudestaan 
- ammattilaiset, työntekijät (huom. myös tämän alakäsitteet), kollegat jne. "ei tiettyyn ammattiin liittyvät termit"
- toteutetaan muut muutokset

**Comment by mirmaid** [comment]
Epävarmat tapaukset:

alaiset
ammatinharjoittajat
ammattilaiset
asiantuntijat
elinkeinonharjoittajat
harjoittelijat

**Comment by mirmaid** [comment]
tarkka-ampujat /YK sotilaat?

**Comment by ilona-x** [comment]
> tarkka-ampujat /YK sotilaat?

Voiko tarkka-ampuja olla myös poliisi? Ainakin Wikipedian mukaan tarkka-ampujia työskentelee myös polisiissa. https://fi.wikipedia.org/wiki/Tarkka-ampuja

**Comment by mirmaid** [comment]
Teologit ja vastaavat: onko osa "logeista" ammatteja? Esim. arkeologit? Entä esim. biokemistit, eläintieteilijät, filosofit? Voisi katsoa näitäkin yhdessä.

**Comment by mirmaid** [comment]
alaiset: jää nykyiselle paikalle
ammatinharjoittajat: jää nykyiselle paikalle
ammattilaiset: jää nykyiselle paikalle
asiantuntijat: jää nykyiselle paikalle (tietoasiantuntijat > ammattiin...)
elinkeinonharjoittajat: jää nykyiselle paikalle
harjoittelijat: jää nykyiselle paikalle
kollegat: jää nykyiselle paikalle
sijaiset: jää nykyiselle paikalle
työntekijät
varahenkilöt: jää nykyiselle paikalle
viranhaltijat: alakäsitteet > ammattiin tai työtehtävään liittyvä rooli (myös viranhaltijat > ammattiin...)
virkamiehet: alakäsitteet > ammattiin tai työtehtävään liittyvä rooli (virkamiehet eng. termi tarkistettava) (myös virkamiehet > ammattiin...) (tullivirkamiehet, poistetaan tuplahierarkia)

**Comment by mirmaid** [comment]
Teologit ja vastaavat: onko osa "logeista" ammatteja? Esim. arkeologit? Entä esim. biokemistit, eläintieteilijät, filosofit? Voisi katsoa näitäkin yhdessä. Muut ammatit-alakäsitteet: voiko siirtää sparkkelilla uuteen ryhmään?

Ratkaisu: jätetään nämä ammattiin tai tehtävään liittyvään rooliin.

**Comment by mirmaid** [comment]
Ryhmä **tutkinnon suorittaneet**: siirretäänkö myös täältä ammattiin tai tehtävään liittyvään rooliin ne tutkintonimikkeet, joiden voidaan tulkita olevan myös ammatteja (esim. floristit)?

**Comment by YSO-kokous** [comment]
PÄÄTÖS:
Siirretään kaikki _ammatit_-käsitteen alla olevat käsitteet _ammattiin tai työtehtävään liittyvä rooli_ -käsitteen alle

**Comment by mirmaid** [comment]
Tutkinnon suorittaneet -ryhmästä ei vielä päätöstä.

**Comment by mariaforsen** [comment]
Ainakin floristit ja rakennusarkkitehdit ovat (ruotsiksi) ammatteja. Olisiko tutkinnon suorittaneet  RT?

**Comment by ilona-x** [comment]
tutkinnon suorittaneet -alakäsitteistä myös ainakin **yhteisöpedagogit** voisi sopia myös ammattiin tai tehtävään liittyvään rooliin alle https://tyomarkkinatori.fi/ammattitieto/ammatit/yhteisopedagogi

**Comment by mirmaid** [comment]
rakennusarkkitehdit, sistustusarkkitehdit YK arkkitehdit 
yhteisöpedagogit YK ammattiin tai tehtävään
diplomi-insinöörit YK insinöörit
floristit YK ammattiin tai...

**Comment by mirmaid** [comment]
agrologit
agronomit
artenomit
artesaanit
datanomit
ekonomit
geronomit
hortonomit
iktyonomit
kandidaatit (oppiarvot)
koiranomit
lisensiaatit
logonomit
maisterit
medianomit
merkantit
merkonomit
restonomit
sosionomit
tohtorit
tradenomit
ylioppilaat
