### ISSUE TITLE
YSAan ruotsinkieliset ja Allärsiin suomenkieliset labelit

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#364]
_From [osma.suominen@helsinki.fi](https://code.google.com/u/osma.suominen@helsinki.fi/) on June 03, 2014 13:44:21_

YSAssa ruotsinkieliset termit ja Allärsissa suomenkieliset termit on esitetty tällä hetkellä vain mäppäyssuhteilla. Seurauksena on mm. se, että yhteishaku Fintossa ei toimi kovin hyvin, koska vastineet eivät näy eikä niillä voi hakea ristiin.

Pitäisi lisätä YSAn sisältämät ruotsinkieliset labelit ja Allärsin sisältämät suomenkieliset labelit SKOS-versioihin näistä sanastoista.

Kysymysmerkkinä on se, mitä tehdään, jos YSAssa mainitaan ruotsinkielinen termi jota ei löydykään Allärsista, tai päinvastoin. Mutta ehkä nämä voisi vain lisätä joka tapauksessa (VESA luultavasti toimii näin) ja murehtia löytymisestä vasta mäppäysvaiheessa.

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=363_

**Comment by osma** [comment]
Tämä päätettiin aikanaan ratkaista toisella tavalla, eli suomen/ruotsinkielisiä labeleita ei lisätty SKOS-dataan, vaan sen sijaan Finton hakutuloslistaa kehitettiin ja se näyttää nykyään vastineet YSAsta Allärsiin ja toisinpäin.
