### ISSUE TITLE
YSOn "kansat" pitäisi tarkistaa

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#368]
_From [SNyk...@gmail.com](https://code.google.com/u/112439428317292360191/) on June 05, 2014 12:58:52_

1. The problem / Ongelman tausta: YSOn "kansat" pitäisi tarkistaa (vrt. "väestöryhmään liittyvä rooli") 2. Suggested solution / Ehdotettu ratkaisu:

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=367_

**Comment by tpalonen** [comment]
Ratkaisua ehdotetaan issuessa #645.
