### ISSUE TITLE
YSOn "arvot (ilmiöt)" kokonaisuudessaan katsottava

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#369]
_From [SNyk...@gmail.com](https://code.google.com/u/112439428317292360191/) on June 05, 2014 13:01:13_

1. The problem / Ongelman tausta: YSOn "arvot (ilmiöt)" kokonaisuudessaan katsottava, lisättävä esmes määritelmiä, joista ilmenee, millä perusteella minkäkin alla tietynlaisia alakäsitteitä. 2. Suggested solution / Ehdotettu ratkaisu:

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=368_

**Comment by tpalonen** [comment]
Esim. "kauneus" ja "viisaus" po. ominaisuuksia.

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 30.10.2015

altruismi LT aatteet
hyöty LT vaikutukset
kauneus LT ulkoiset ominaisuudet
oikeudenmukaisuus LT sisäiset ominaisuudet
rehellisyys LT sisäiset ominaisuudet
sankaruus LT sisäiset ominaisuudet
viisaus LT sisäiset ominaisuudet

-> loput jätetään arvoihin

**Comment by tpalonen** [comment]
Jako sisäisiin ja ulkoisiin ominaisuuksiin poistuu. Kauneudelle ym. on löydettävä uusi yläkäsite.

**Comment by MikkoAleksanteri** [comment]
Ominaisuuksiin siirretyt käsitelty ominaisuusuudistuksen yhteydessä.
