### ISSUE TITLE
"yhteiskunnalliset tapahtumat" epäkoherentti kokonaisuus

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#371]
_From [SNyk...@gmail.com](https://code.google.com/u/112439428317292360191/) on June 05, 2014 13:13:12_

1. The problem / Ongelman tausta: "yhteiskunnalliset tapahtumat" syönyt epäkoherentisti, sisältää esmes Viipurin pamauksen 2. Suggested solution / Ehdotettu ratkaisu:

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=370_

**Comment by MikkoAleksanteri** [comment]
ks. issue #496
