### ISSUE TITLE
"vapaus" ja sen alakäsitteet sekä muut vapauden "alalajit" tulisi katsoa kokonaisuutena

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#372]
"vapaus" ja sen alakäsitteet sekä muut vapauden "alalajit", ja muualla hierarkiassa olevat *vapaus-tyyppiset käsitteet, tulisi katsoa kokonaisuutena ja miettiä niiden nykyinen palastelu - onko järkevä?

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=371_

**Comment by MikkoAleksanteri** [comment]
Mikko alustaa tulevaan kokoukseen.

**Comment by MikkoAleksanteri** [comment]
vapaus-käsitteen (http://www.yso.fi/onto/yso/p4064) alakäsitteet:

-     elinkeinovapaus
-     valinnanvapaus
-     vastuuvapaus
-     verovapaus
-     viisumivapaus

muita *vapaus-käsitteitä:

ajatuksenvapaus
LT perusoikeudet

erivapaus
LT poikkeusluvat

kokoontumisvapaus
LT perusoikeudet

liikkumisvapaus
LT perusoikeudet

mielipiteenvapaus
LT perusoikeudet

omantunnonvapaus
LT perusoikeudet

painovapaus
LT sananvapaus

sananvapaus
LT perusoikeudet

tahdonvapaus
LT käsitteet

uskonnonvapaus
LT perusoikeudet

yhdistymisvapaus
LT perusoikeudet

yksilönvapaus
LT perusoikeudet

**Comment by MikkoAleksanteri** [comment]
Ratkaisuehdotus:

siirretään kaikki alakäsitteet käsitteen oikeudet (edut)  http://www.yso.fi/onto/yso/p152 alle.

**Comment by mirmaid** [comment]
Myös monihierarkia on tässä mahdollinen, koska sekä _perusoikeudet_, että _vapaus_ ovat _abstraktien objektien_ hierarkiassa. Itse tekisin ehkä niin, ja siirtäisin _tahdonvapauden_ vapauden alle _käsitteistä_.

**Comment by mirmaid** [comment]
tahdonvapaus YK vapaus
Ei muita muutoksia.
