### ISSUE TITLE
ympäristövahingot, ympäristövauriot

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#374]
_From [mafors...@gmail.com](https://code.google.com/u/100004162283516840686/) on June 09, 2014 13:00:00_

1. The problem / Ongelman tausta: Nyt ympäristövauriot=miljöförstöring, joka ei oikein täsmää.

Mikä on näiden ero? 

MOT: ympäristövahinko: ympäristölle aiheutunut vahinko
-vauriot ei löydy.

Esim. Eurovociassa sama käsite, toinen korvattuna.

Ks. Google. 

Tämä on vanha ongelma. Onko mitenkään mahdollista korvata toinen? 2. Suggested solution / Ehdotettu ratkaisu:

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=373_

**Comment by mirmaid** [comment]
Ratkaistu YSA-kokouksessa 4-2016.
