### ISSUE TITLE
modernisaatio, uudenaikaistuminen

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#375]
_From [mafors...@gmail.com](https://code.google.com/u/100004162283516840686/) on June 09, 2014 13:07:04_
1. The problem / Ongelman tausta: Ruotsin ratkaisu puutteellinen. 

Mikä on näiden tarkka määritelmä ja ero? 2. Suggested solution / Ehdotettu ratkaisu:

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=374_

**Comment by MikkoAleksanteri** [comment]
YSA-kokous päätti säilyttää erillisinä.

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 30.10.2015

modernisaatiolle tarkenne -> modernisaatio (yhteiskunta)

uudenaikaistumiselle uusi LT -> LT muutos

**Comment by mirmaid** [comment]
Muutosehdotus YSEssä https://github.com/Finto-ehdotus/YSE/issues/4786
