### ISSUE TITLE
sulkutarkenne yhdelle vai usealle...

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#377]
_From [mafors...@gmail.com](https://code.google.com/u/100004162283516840686/) on June 10, 2014 10:44:39_

1. The problem / Ongelman tausta: Päätöstä sulkutarkenteen käytöstä ei vielä tehty. Vaihtoehdot:

    1) sulkutarkenteet aina molemmille käsitteille
    2) sulkutarkenne vain toiselle: spesifisemmälle sulkutarkenne, jolloin sulkutarkenteeton tarkoittaa kaikkea muuta (näin vain joissakin tapauksissa, ei esim. yksikkö/monikko-tapauksissa!)

-Ks. standardi ISO 25964-1, kohta 6.2.2 (s. 22) : tarkenne molemmille...

-Vrt. esim. leikki / leikit, joista ensimmäinen voisi tarvita sulkutarkenteen, mutta jälkimmäinen on yksiselitteinen..? Tällaiset yksikkö/monikko-tapaukset ovat ihan eri verrattuna esim. parantaminen-kaltaisiin jakoihin.

-Pitäisikö olla eri periaatteita riippuen minkälainen tapaus kyseessä, ettei tarvitse turhia tarkenteita laittaa? 2. Suggested solution / Ehdotettu ratkaisu:

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=376_

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 30.10.2015:

On jo päätetty:

->sulkutarkenne molemmille aina
