### ISSUE TITLE
Paikannimirekisteriin kuntatiedot

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#38]
_From [osma.suominen@helsinki.fi](https://code.google.com/u/osma.suominen@helsinki.fi/) on December 04, 2013 15:58:25_

Paikannimirekisterissä on kaikista(?) paikoista kuntatieto ja lisäksi siihen kuuluu lista kunnista erikielisine nimineen.

Tämä pitäisi lisätä SKOS-versioon (Kunnat omana luokkanaan), koska siitä tiedosta olisi hyötyä disambiguoinnissa.

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=35_

**Comment by osma** [comment]
Paikannimirekisterin julkaisu on MML:n vastuulla.
