### ISSUE TITLE
Uskonnon alkuperäteoriat

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#382]
_From [tuomas.p...@gmail.com](https://code.google.com/u/114029607375739102692/) on June 12, 2014 10:47:06_

1. The problem / Ongelman tausta: uskonnon alkuperäteoriat

Tämän alakäsitteet kummastuttavat (tulevat YSAsta, tietenkin). ovatko varsinaisia alakäsitteitä? sopisiko niille joku toinen paikka. eivät ole teorioita. 

Huom! vainajainpalvonta poistettu koostekäsitepalaverissa.

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=381_

**Comment by mariaforsen** [comment]
Muutettu nyt myös YSOssa.
