### ISSUE TITLE
Säilytettäviä koostekäsitteitä: maalaus, hallitukset, parantaminen, kilvet, voitelu

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#384]
_From [tuomas.p...@gmail.com](https://code.google.com/u/114029607375739102692/) on June 16, 2014 16:17:58_

1.
maalaus (pintakäsittely)
maalaus (taiteellinen luonti)

Melindassa käytetty molemmissa merkityksissä. Jakoa kaivataan myös ruotsin kielen puolella. Olisiko mahdollista keksiä paremmat sulkutarkenteet?

2.
hallitukset (hallintoelimet)
hallitukset (hallintoviranomaiset)

Melindassa käytetty molemmissa merkityksissä. Paremmat sulkutarkenteet, anybody?

3.
parantaminen (kohentaminen)
parantaminen (tervehdyttäminen)

Melinda-käyttö viittaa jaon säilyttämiseen. Sulkutarkenteet kaipaisivat kohentamista. Get it?

4.
kilvet (konkreettinen eloton objekti)
kilvet (orgaaninen rakenne)
kilvet (varusteet)

Päätös: poistetaan "kilvet (orgaaninen rakenne)". Ei käytetty tässä merkityksessä kuvailussa.
Ratkaistava: Säilytetäänkö muut merkitykset? Molemmissa merkityksissä käytetty Melindassa. Sulkutarkenteet kaipaisivat fiksaamista.

5.
voitelu (tapahtuma)
voitelu (toisenlaiseksi muuttaminen)

Melinda-käyttö tässäkin puoltaisi jaon säilyttämistä. Tapahtuma-merkitys viittaa tässä ritualistiseen merkitykseen. Sulkutarkenteet kaipaisivat toisenlaiseksi muuttamista.

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=383_

**Comment by MikkoAleksanteri** [comment]
YSO-kokous:
Koostekokouksissa tehdyt päätökset säilytettävistä jaoista ovat ok. Ei tarvitse hyväksyttää YSO-kokouksessa.
Yleistä sulkutarkenteista: kannattaa edelleen suosia yläkäsitettä, jos on käyttökelpoinen (esim. taiteellinen luonti on riittävän hyvä ja selkeä).

1. Nykyiset sulkutarkenteet ok.
2. 
hallitukset (julkinen hallinto)
hallitukset (yhdistykset ja yritykset)

**Comment by tpalonen** [comment]
4.
Päätös: säilytetään vain yksi käsite, eli suojavaruste-merkityksinen säilytetään. Tämän preflabel muotoon: "kilvet (suojavarusteet)". Luodaan uusi käsite, jossa rekisterikilpi-merkitys yhdistyy aiemmin käytössä olleesee kyltit-käsitteeseen. Poistetaan sekä aiempi kyltit-käsite että "kilvet (elottomat objektit)" ja näille seuraajasuhde tähän uuteen käsitteeseen, jolle preflabeliski "kilvet ja kyltit" ja oldlabeliksi "kilvet (elottomat objektit)" sekä "kyltit".

**Comment by tpalonen** [comment]
5.
voitelu (uskonto)

voitelu (kitka)
voitelu (käsittely)
voitelu (tekniikka)
