### ISSUE TITLE
Paikannimirekisterin automaattipäivitys

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#39]
_From [osma.suominen@helsinki.fi](https://code.google.com/u/osma.suominen@helsinki.fi/) on December 04, 2013 15:59:54_

Paikannimirekisteri ei päivity automaattisesti, vaan tehdään xml-dumpista.

Pitäisi hakea ajantasaiset datat WFS-rajapinnasta.

Data alkaa päivittyä useammin maaliskuussa 2014. Tällä hetkellä sitä päivitetään vain kerran vuodessa, joten tämä ei ole akuutti kysymys.

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=36_

**Comment by osma** [comment]
Paikannimirekisterin julkaisu on MML:n vastuulla.
