### ISSUE TITLE
Koostekäsitepäätöksiä: sijoitus, kylmäkäsittely, luovutus, keskustelu jne.

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#390]
_From [tuomas.p...@gmail.com](https://code.google.com/u/114029607375739102692/) on June 25, 2014 12:47:13_

1.
sijoitus (henkilön aseman muuttaminen)
sijoitus (liikuttaminen)
sijoitus (tilanteeseen)

Säilytetään liikuttaminen-merkitys, poistetaan muut. YSAssa tehdään käytä-viittaus [sijoitus (varainhoito) KÄYTÄ sijoitustoiminta]. Tällainen hienojako ei tarpeen. Konteksti kertoo mistä on kyse.

2.
kylmäkäsittely (kasvit)
kylmäkäsittely (metallityö)

Poistetaan metallityö-käsite, koska ei ole käytetty tässä merkityksessä. Maria miettii ruotsin vastineen.

3.
luovutus (lahjoitus)
luovutus (laillinen)

Poistetaan lahjoitus-merkitys, koska sama yläkäsite ja merkitysero epäselvä.

4.

lainat (luovutettu esine)
lainat (rahasumma)

Poistetaan luovutettu esine -merkitys koska ei lähestulkoon lainkaan käyttöä Melindassa tässä merkityksessä.

5.
spiritualismi (filosofian)
spiritualismi (teologian)

Poistetaan uudempi, koska esim. Melinda-käyttö väljää eikä käsitteillä ole selvää rajaa. Mirja selvittää laitetaanko spiritismille KT spiritualismi (okkultismi).

5.
tunnustus (hyväksyminen)
tunnustus (oikeaksi myöntäminen)
tunnustus (vakaumuksen)

Yhdistetään hyväksyminen ja oikeaksi myöntäminen. Siirretään jäljelle jäävä keskinäiseen toimintaan. Mirja tutkii, mitä "tunnustus (vakaumuksen)"-käsitteelle tehdään.

6.
valvonta (vartiointi)
valvonta (huolehtiminen)

Poistetaan "valvonta (huolehtiminen)", koska suomeksi merkitysero ei ole huomattava ja ruotsin puolella voidaan taipua kompromissiin.

7.
toimintarajoitteet (ominaisuudet)
toimintarajoitteet (yhteiskunnalliset ilmiöt)

Poistetaan "toimintarajoitteet (yhteiskunnalliset ilmiöt)", koska ei käytetty tässä merkityksessä, joka on muutenkin epäselvä.

8.
varhaiskasvatus (esikoulu)
varhaiskasvatus (koulua edeltävä)

Poistetaan uudempi, koska ero ei merkittävä (suomen kielessä). Maria miettii ruotsin kielen.

9.
kertomukset (yhteiskunnalliset tuotokset)

Poistetaan yhteiskunnalliset tuotokset -merkitys ja siirretään sen alakäsitteet suoraan yhteiskunnallisten tuotosten alle. Loput kertomukset-käsitteet päätettäväksi YSO-kokouksessa.

10.
uudelleensijoitus (henkilön aseman muuttaminen)
uudelleensijoitus (liikuttaminen)

Säilytetään liikuttaminen-merkitys. Ks. sijoitus.

11.
kuoret (konkreettinen eloton objekti)
kuori (kasvinosat)

Poistetaan "konkreettinen eloton objekti" koska ei käyttöä tässä merkityksessä.

12.
laskentatoimi (liiketaloustiede)
laskentatoimi (tiedollinen luonti)

Poistetaan liiketaloustiede-käsite, koska on epäolennainen.

13.
rakenne (abstraktin koostumistapa)
rakenne (konkreettinen eloton objekti)
rakenne (konkreettinen koostumistapa)

Poistetaan "rakenne (konkreettinen eloton objekti)", poistetaan myös "rakenne (konkreettisen koostumistapa)" ja koostekäsite. Siirretään mikrorakenteet ja nanorakenteet "rakenteet"-käsitteen alle. Tekstuuri "sisäiset ominaisuudet"-käsitteen alle. Saumat "konkreettinen eloton objekti" alle (paremman puutteessa).

14.
toleranssit (fyysiset ominaisuudet)
toleranssit (tieto)

Poistetaan tieto-käsite, koska ei käyttöä tässä merkityksessä.

15.
mitat (fyysiset ominaisuudet)
mitat (konkreettinen eloton objekti)
mitat (mittaustapa)

Poistetaan muut kuin fyysiset ominaisuudet -merkitykset. Mittauslaitteet ja mittarit löytyy jo ontologiasta. Mietitään vielä mittaustapa-käsitteen alakäsitteille uudet paikat hierarkiassa.

15.
palvelut (tuotokset)
palvelut (toiminta)

Poistetaan tuotokset-käsite mm. siksi, että sillä ei ole alakäsitteitä. Mietitään jäljelle jäävän palvelut-käsitteen hierarkia ja alakäsitteet myöhemmin.

16.
lennonjohto (organisaatiot)
lennonjohto (toiminta)

Poistetaan organisaatio-käsite. Vrt. liikkeenjohto, sodanjohto.

17.
jakaminen (osiin)
jakaminen (usealle)

Poistetaan jakaminen (usealle) ja kooste, koska käsitteen jakaminen ei ole olennainen käyttäjälle. Yhdistetään alakäsitteet.

18.
stabiilius (fyysiset ominaisuudet)
stabiilius (mentaaliset ominaisuudet)

Poistetaan sulkutarkenne ja koostekäsite. Fyysiset ominaisuudet -merkitys on jo deprikoitu aiemmin [emme löytäneet tästä muistiinpanoja].

19.
talous (organisaatiot)
talous (taloudelliset ilmiöt)

Poistetaan talous (organisaatiot) ja kooste, siirretään alakäsitteet poistetun käsitteen yläkäsitteen alle.

20.
ufologia (kulttuuriset ilmiöt)
ufologia (tutkimustoiminta)

Poistetaan ufologia (tutkimustoiminta) ja kooste, jäljelle jäävän LT rajatieto.

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=389_

**Comment by mirmaid** [comment]
15.
palvelut (tuotokset)
palvelut (toiminta)

Poistetaan tuotokset-käsite mm. siksi, että sillä ei ole alakäsitteitä. Mietitään jäljelle jäävän palvelut-käsitteen hierarkia ja alakäsitteet myöhemmin.

HIERARKIA: palvelut LT yhteiskunnalliset objektit. Yksikölliset alakäsitteet LT keskinäinen toiminta. Vakuutus käsitellään erillisessä issuessa.
