### ISSUE TITLE
Mahdollisesti säilytettäviä koostekäsitteitä: keskustelu, hyvinvointi, aloitteet

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#391]
_From [tuomas.p...@gmail.com](https://code.google.com/u/114029607375739102692/) on June 25, 2014 13:06:22_

1.
keskustelu (pohdinta)
keskustelu (puhe)
keskustelu (väittely)

Mahdollinen säilytettävä kokonaisuus ruotsin kielen vuoksi: Allärsista löytyy diskussion, samtal ja debatt ja näiden erillään pitäminen olisi tärkeää. "Keskustelu (väittely)" olisi mahdollinen poistaa koska löytyy jo "väittely" ja tämän ruotsinkielinen vastine voisi olla debatt.

2.
hyvinvointi (henkilökohtainen)
hyvinvointi (taloudellinen)

Mahdollinen säilytettävä kooste ruotsin vuoksi: välmående ja välfärd. Välmående fyysisempi, välfärd useimmiten aineellinen yms. Sulkutarkenteissa parantamisen varaa.

3.
aloitteet (hallinto- ja lakialoitteet)
aloitteet (pyrkimykset)

Jako mahdollisesti säilytettävä. Ruotsiksi initiativ ja motioner. Melinda-käyttöä on ollut molemmissa merkityksissä (esim. lapsen aloitteellisuus).

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=390_

**Comment by tpalonen** [comment]
1.
Säilytetään vain yksi käsite samtal-merkityksessä. Poistetaan muut. Yhdistetään poistuvien alakäsitteet jäljelle jäävän alakäsitteiksi (huom! myös "julkinen keskustelu"). Korjataan väittely-käsitteen (www.yso.fi/onto/yso/p8613) ruotsinkielinen termi.
