### ISSUE TITLE
Koostekäsitteitä: kasvatus, kommunismi, kertomukset, valtiopäivät

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#392]
_From [tuomas.p...@gmail.com](https://code.google.com/u/114029607375739102692/) on June 25, 2014 14:02:43_

1.
kasvatus (ihmisen)
kasvatus (kasvien tai eläinten)

Taustaa: Merkitysero lienee selvä. Molemmilla käsitteillä useita alakäsitteitä. Ruotsin vastineet viittaavat täysin eri asioihin (forstan, uppfödning).

Vaihtoehdot: 1. Poistetaan kasvi/eläin-merkitys ja kooste. YSAsan käyttöhuomautus: kasvatus-termiä ei tarkoitettu käytettäväksi kasvi/eläin-merkityksessä. 2. Poistetaan kasvi/eläin-merkitys ja kooste. Tehdään sulkutarkenteellinen ohjaustermi "kasvatus (tuotanto)" [tai jokin parempi sulkumääre] ja liitetään se kaikkiin tarpeellisiin käsitteisiin. (Esim jalostus, kotieläintuotanto) 3. Otetaan "kasvatus (tuotanto)" [tai jokin parempi sulkumääre] YSAan ja säilytetään koostekäsite. (Tarkistettava, miten tämä vaikuttaa YSOon: "kasvatus (kasvien ja eläinten)" poistettaneen ja lisättäneen seuraaja-suhde uuteen "kasvatus (tuotanto)"-käsitteeseen?)

Huom! Jos kasvi/eläin-merkitys poistetaan, sen alakäsitteille pitää löytää uusi paikka hierarkiassa.

2.
kommunismi (ideologiat)
kommunismi (talousjärjestelmät)

Ehdotus: Korvataan jako monihierarkialla. Ongelma: Ideologiat ovat ilmiöitä. Ilmiöiden  ja järjestelmien välillä ei (tällä hetkellä) sallita monihierarkiaa. Yhteiskunnalliset järjestelmät voisivat potentiaalisesti olla myös ilmiöit-hierarkiassa. (esim. diktatuuri = järjestelmä; yksinvalta = ilmiö)

3.
kertomukset (kirjalliset teokset)
kertomukset (kulttuuriset tuotokset)

Taustaa: Näillä on alakäsitteitä. Jako kirjallisiin teoksiin ja kulttuurisiin tuotoksiin perustuu siihen, että tietyt kertomukset voivat olla myös suullisia (kansankertomukset, matkakertomukset, sadut jne), eivät siis ensisijaisesti kirjallisia, joten hierarkia ei pätisi näiden osalta.

Ehdotus: Voitaisiinko loput kaksi korvata monihierarkiametodilla: poistettaisiin toinen kertomukset-käsitteistä. Jäljelle jäävä kertomukset-käsite siirrettäisiin kulttuuriset tuotokset -käsitteen alle. Ne alakäsitteet, jotka voivat olla myös kirjallisia (esim. matkakertomukset, sadut, sarjakertomukset), olisivat sekä kertomusten alla että "kirjalliset teokset"-käsitteen alla.

(Huom: löytyy myös "kertomukset (yhteiskunnalliset tuotokset)", mutta se päätettiin jo poistaa, eikä sitä tarvitse tässä enää puida. Ks. Issue 389 .)

4.
valtiopäivät (kansanedustajalaitokset)
valtiopäivät (maapäivät)
valtiopäivät (poliittinen historia)

Tausta: Merkitysero lienee selvä.
Ehdotus: Poistetaan maapäivät-käsite. YSAan otettaneen erillinen "maapäivät"-termi. Jäljelle jäävien osalta kaksi vaihtoehtoa: 1. Säilytetään jako. Paremmat sulkutarkenteet? 2. Vain yksi valtiopäivät-käsite.

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=391_

**Comment by mirmaid** [comment]
4.
valtiopäivät (kansanedustajalaitokset)
valtiopäivät (maapäivät)
valtiopäivät (poliittinen historia)

Tausta: Merkitysero lienee selvä.
Ehdotus: Poistetaan maapäivät-käsite. YSAan otettaneen erillinen "maapäivät"-termi. Jäljelle jäävien osalta kaksi vaihtoehtoa: 1. Säilytetään jako. Paremmat sulkutarkenteet? 2. Vain yksi valtiopäivät-käsite.
