### ISSUE TITLE
keho, ruumis

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#397]
_From [mafors...@gmail.com](https://code.google.com/u/100004162283516840686/) on June 27, 2014 15:31:09_
1. The problem / Ongelman tausta: Molemmat ja huomautukset: 

-elävän ihmisen tai eläimen ruumis 
-kuolleen ihmisen tai eläimen ruumis; voi viitata myös elävän ihmisen tai eläimen ruumiseen {@fi}

Ruotsiksi on toinen nyt vain kuollut. Pitäisi kai muuttaa jotenkin niin ettei sanastosta löydy samaan käsitteeseen viittavia useita eri termejä. 2. Suggested solution / Ehdotettu ratkaisu:

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=397_

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 30.10.2015

Mirja selvittää

**Comment by mirmaid** [comment]
Yhdistetty YSAssa: keho KÄ ruumis. Muutoksesta saatiin vielä kriittistä palautetta, joka käsitellään YSA-kokouksessa 5/2016.

**Comment by mirmaid** [comment]
Yhdistetty YSAssa ja YSOssa.
