### ISSUE TITLE
Edeltäjä-seuraaja -käsiteparien käsittely ontologiassa, esim. "Elektroniset sopimukset = Sähköisistä sopimuksista vuoteen 2004 asti käytetty nimitys"

### ISSUE THREAD

**Issue by satuniininen** [NatLibFi/Finto-data#4]
YSOssa on seuraavat käsitteet:
sähköiset sopimukset + huomautus "Nimitys käytössä vuodesta 2004 alkaen, aiemmat katso elektroniset sopimukset"
elektroniset sopimukset + huomautus: "Sähköisistä sopimuksista vuoteen 2004 asti käytetty nimitys"

Vastaavanlaisia tapauksia on muitakin (ks. alla), joissa suomeksi käytetty termi on muuttunut, mutta sekä uusi että vanha ovat omina käsitteinään. Pitäisikö näillä olla samanlainen edeltäjä-seuraaja-suhde kuin ATK-ohjelmat -> tietokoneohjelmat -käsitteillä? Miten näiden kanssa pitäisi toimia? Tällaisenaan hankala kääntää, sillä englanniksi termi ei ole muuttunut. Ainakin pitäisi määritellä, miten tarkka huomautusteksti tarvitaan.

Vastaavia:
ammatillisten opintojen opettajat / ammattiopettajat
isyysloma / isyysvapaa
äitiysloma / äitiysvapaa
vanhempainloma / vanhenpainvapaa
värvätyt / sotilashenkilöstö

**Comment by mirmaid** [comment]
Lista pitäisi tuottaa YSAn pohjalta, koska osa huomautuksista saattaa puuttua YSOsta.

**Comment by tpalonen** [comment]
YSO-kokouksen päätös:
Tuomas tekee SPARQL:n YSAan, jossa huomioidaan "vuodesta", "vuoteen", "asti", "lähtien". Ja mahdollisesti "käyt". Exceliin voisi tuottaa taulukon, jossa näkyy sekä edeltäjäkäsite että seuraaja.
Tuomas ottaa vetovastuun issuesta. Läpikäyntiin mennee muutama YSO-kokous.

**Comment by tpalonen** [comment]
Taulukko löytyy täältä: https://docs.google.com/spreadsheets/d/1cAAOh1GCxVY3GD3gCGz8hYUcXdFG0PByeXWST9J1JaA/edit#gid=48493359

**Comment by MikkoAleksanteri** [comment]
Tehdään uusi taulukko, jossa sparkkelit tehdään YSAan jotta kaikki kommentit saadaan varmasti haaviin.

**Comment by tpalonen** [comment]
Uusi YSAan tehty taulukko löytyy täältä:

https://docs.google.com/spreadsheets/d/1bG8EgqP1Ya-sNPhFKmhYQwwsWuaIX57Ch1y6G1TalG0/edit#gid=202616320

**Comment by tpalonen** [comment]
Käsitteistä, jotka on yhdistetty YSOssa (esim. isyysvapaa), pitää laittaa defined concept -suhde molempiin YSAan jääviin ja Allärsiin jääviin käsitteisiin (esim. isyysvapaa ja isyysloma). Tuomas hoitaa YSAn osalta, Maria Allärsin osalta.

**Comment by tpalonen** [comment]
Edit: Toteutettu defined concept -suhde molempiin YSAan jääviin käsitteisiin. Allärsin osalta ei vielä toteutettu. Osa taulukossa olevista tapauksista selvitetään erikseen.

**Comment by mariaforsen** [comment]
Kirjaaminen on tainnut unohtua, mutta tarkistin että on myös tehty Allärsin osalta.

**Comment by mirmaid** [comment]
YSO-kokous 21.10.2016:
Osa taulukossa olevista tapauksista selvitetään erikseen. - Mirja siirtää ysa-käsittelyä odottavat ehdotusjärjestelmään.

**Comment by mirmaid** [comment]
evoluutioteoria/kehitysoppi: mitä tässä toivottiin muutettavan?

yleinen oikeusapu: kohdassa oikeusapu lukee "ei toimenpiteitä", tässä "Mirja tutkii".

Onko taulukko muuten nyt valmis? vrt. esim. rivit 7 ja 129.

**Comment by mirmaid** [comment]
YSO-kokous 24.3.2017:

yleinen oikeusapu: kohdassa oikeusapu lukee "ei toimenpiteitä", tässä "Mirja tutkii" > muutosehdotus YSEen (Mirja tekee).
