### ISSUE TITLE
MUSA sisältää blank nodeja

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#40]
_From [osma.suominen@helsinki.fi](https://code.google.com/u/osma.suominen@helsinki.fi/) on December 14, 2013 09:27:53_

MUSAn automaattipäivityksessä näkyy, että se sisältää blank nodeja. Tämän vuoksi data "muuttuu" joka kerta, vaikka oikeasti sisältö on sama. Esim. https://code.google.com/p/onki-data/source/detail?r=144 Pitäisi selvittää mistä nämä johtuvat ja korjata muunnostyökalu siten, että kaikilla resursseilla on URI.

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=37_

**Comment by osma** [comment]
Ei sisällä enää, uuden muuntimen myötä.
