### ISSUE TITLE
ajoitus

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#401]
_From [mafors...@gmail.com](https://code.google.com/u/100004162283516840686/) on July 04, 2014 10:54:32_

1. The problem / Ongelman tausta: Nyt kaksi eri merkitystä, ks. huomautus. 

Oli aikaisemmin åldersbestämning ruotsiksi, nyt datering, eli ensimmäinen tbc:ssä mainittu merkitys. 

Melindassa molemmissa käytetty. 2. Suggested solution / Ehdotettu ratkaisu:

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=401_

**Comment by tpalonen** [comment]
Nyt on kaksi käsitettä, mutta koostekäsite puuttuupi.
