### ISSUE TITLE
Säilytettäviä koostekäsitteitä: itsenäisyys, kalvot, kannet

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#405]
_From [tuomas.p...@gmail.com](https://code.google.com/u/114029607375739102692/) on July 08, 2014 12:57:12_

1.
itsenäisyys (vaikutteista)
itsenäisyys (vallasta)

Mahdollinen säilytettävä jako. Paremmat sulkutarkenteet olisi hyvä olla. Mitä on itsenäisyys?

2.
kalvot (konkreettinen eloton objekti)
kalvot (orgaaninen rakenne)

Mahdollinen säilytettävä jako. Ruotsin kielen vastineet mietittävä uudestaan. Sulkutarkenteet?

3.
kannet (alukset)
kannet (nidokset)
kannet (säilytys)

Mahdollinen säilytettävä jako. Paremmat sulkutarkenteet. nidokset = painotuotteet?

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=406_

**Comment by tpalonen** [comment]
1.
itsenäisyys (valtiot ja yhteisöt) 
itsenäisyys (yksilöt)
Korjaa huomautukset ja ryhmät.

2.
