### ISSUE TITLE
Koostekäsitteitä: liikkeet, vastaanotot etc

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#406]
_From [tuomas.p...@gmail.com](https://code.google.com/u/114029607375739102692/) on July 08, 2014 13:18:47_

1.
liikkeet (liikkuminen)
liikkeet (organisaatiot)

"liikkeet (organisaatiot)" koettiin hieman turhaksi, koska se on ontologiassa vain luomassa hierarkiaa. Kuvailussa ei ole käytetty tässä merkityksessä. Ongelmana kuitenkin on, että sillä on paljon alakäsitteitä. Mihin nämä laitettaisiin? Suoraa "organisaatiot" alle? Vai esim LT yhteiskunnalliset liikkeet. Toinen ongelma: pitäisikö jäljelle jäävälle "liikkeet"-käsitteelle jättää kuitenkin jonkinlainen opastava sulkutarkenne tai käyttöhuomautus, koska ontologiasta löytyy myös "liikkeet -- liikerakennukset" KÄYTÄ myymälät?

2.
vastaanotot (järjestetty tapahtuma)
vastaanotto (ajanjakso)
vastaanotto (liikuttaminen)
vastaanotto (paikka)
vastaanotto (ymmärtäminen)

Ovat kaikki samaa koostekokonaisuutta. Ehdotus: poistetaan kaikki muut ja säilytetään kaksi merkitystä: ymmärtäminen (taiteen yms) ja vastaanotto yleisterminä (liikkutaminen?). Pitäisi kuitenkin löytää paremmat sulkutarkenteet. Täytyy säilyttää kooste.

3.
lisääntyminen (biologiset ilmiöt)
lisääntyminen (muutos)

Ehdotus: poistetaan muutos-merkitys, koska ei käytetty tässä merkityksessä. Kelpaa esimerkiksi YSO-kokoukseen: voimmeko tehdä vapaasti tällaisia päätöksiä jatkossa?

4.
käsittely (keskustelu ja päättäminen)
käsittely (toisenlaiseksi muuttaminen)

Vaihtoehdot: 1. Säilytetään jako. Paremmat sulkutarkenteet. 2. Poistetaan toinen. Mitä tässä tapauksessa tehdään alakäsitteille? Ovatko nämä selkeästi kaksi eri käsitettä vai eivät?

5.
piirtäjät (kuvataiteilijat)
piirtäjät (ammatit)

Kaksi ongelmaa: 1. ruotsiksi eri termit. 2. Alakäsitteiden vuoksi vaikea korvata monihierarkialla, koska tällöin tulemme väittäneeksi, että kartanpiirtäjä on myös kuvataiteilija yms. Vaihtoehdot: 1. Säilytetään nykyinen jako. Eri sulkutarkenteet (vrt. esim. piirustukset)? 2. Poistetaan jako ja korvataan monihierarkialla. 3. Poistetaan jako ja korvataan RT-suhteilla. Esim. piirtäjät LT ammatit + RT kuvataiteilijat tms.

6.
valokuvaajat (kuvaajat)
valokuvaajat (kuvataiteilijat)

Hieman piirtäjien kaltainen ongelma. Tosin ruotsin kielistä eroa ei ole eikä alakäsiteongelmaakaan ole. Vaihtoehdot: 1. Säilytetään nykyinen jako. Eri sulkutarkenteet (vrt. esim. piirustukset)? 2. Poistetaan jako ja korvataan monihierarkialla. 3. Poistetaan jako ja korvataan RT-suhteilla. Esim. valokuvaajat LT ammatit + RT kuvataiteilijat tms.

7.
altaat (ihmisen määrittämä paikka)
altaat (konkreettinen eloton objekti)

Olisi yhdistettävissä, mutta aiheuttaa ongelmia hierarkian ja alakäsitteiden vuoksi. Vaihtoehdot: 1. Säilytetään kooste. Lisätään altaat-käsitteelle LT luonnon muodostama paikka. 2. Poistetaan toinen, esim. konkreettinen eloton objekti ja siirretään tämän alakäsitteet toisaanne. Mikä on jäljelle jäävän paikka hierarkiassa?

8.
sosialismi (ideologiat)
sosialismi (talousjärjestelmät)

Ehdotetaan moniperintää, mutta ilmiöiden ja järjestelmien välillä ei (tällä hetkellä) voi olla moniperintää. Yhteiskunnalliset järjestelmät (esim. diktatuuri = järjestelmä; yksinvalta = ilmiö) voisivat yhtä hyvin olla myös ilmiöitä.

9.
kasvu (luonnontieteellinen muutos)
kasvu (yhteiskunnalliset ilmiöt)

Jaolla tässä lähinnä hierarkisoiva funktio. Rajanveto näiden kahden käsitteen välillä epäselvä. Vaihtoehdot: 1. Poistetaan jako ja päätetään alakäsitteiden paikat. (Kaikki saman kasvun alle?) 2. Säilytetään nykyinen jako.

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=407_

**Comment by mirmaid** [comment]
1.
liikkeet (liikkuminen)
liikkeet (organisaatiot)

"liikkeet (organisaatiot)" koettiin hieman turhaksi, koska se on ontologiassa vain luomassa hierarkiaa. Kuvailussa ei ole käytetty tässä merkityksessä. Ongelmana kuitenkin on, että sillä on paljon alakäsitteitä. Mihin nämä laitettaisiin? Suoraa "organisaatiot" alle? Vai esim LT yhteiskunnalliset liikkeet. Toinen ongelma: pitäisikö jäljelle jäävälle "liikkeet"-käsitteelle jättää kuitenkin jonkinlainen opastava sulkutarkenne tai käyttöhuomautus, koska ontologiasta löytyy myös "liikkeet -- liikerakennukset" KÄYTÄ myymälät?

RATKAISU: siirretään alakäsitteet käsitteen "organisaatiot" alle. Ei jätetä liikkeet-käsitteelle sulkutarkennetta preflabeliin (oldlabeliin sulkutarkenne).

**Comment by mirmaid** [comment]
2.
vastaanotot (järjestetty tapahtuma)
vastaanotto (ajanjakso)
vastaanotto (liikuttaminen)
vastaanotto (paikka)
vastaanotto (ymmärtäminen)

Ovat kaikki samaa koostekokonaisuutta. Ehdotus: poistetaan kaikki muut ja säilytetään kaksi merkitystä: ymmärtäminen (taiteen yms) ja vastaanotto yleisterminä (liikkutaminen?). Pitäisi kuitenkin löytää paremmat sulkutarkenteet. Täytyy säilyttää kooste.

RATKAISU: jätetään vastaanotto (reseptio) [nyt "ymmärtäminen"] ja vastaanotto ilman sulkutarkennetta [nyt "liikuttaminen"]. Palataan kysymykseen vielä sen jälkeen kun sulkutarkenteita on käsitelty viikkokokouksessa 13.1. (Mirja lisää listaan).

**Comment by mariaforsen** [comment]
Ruotsiksi muutetaan myös: 
vastaanotto (reseptio) = reception 
vastaanotto... = mottagande

**Comment by mirmaid** [comment]
4.
käsittely (keskustelu ja päättäminen)
käsittely (toisenlaiseksi muuttaminen)

Vaihtoehdot: 1. Säilytetään jako. Paremmat sulkutarkenteet. 2. Poistetaan toinen. Mitä tässä tapauksessa tehdään alakäsitteille? Ovatko nämä selkeästi kaksi eri käsitettä vai eivät?

RATKAISU: vaihtoehto 2. Kaikille alakäsitteille tämä LT. Ruotsiksi behandling KT hantering TAI behandling, hantering.

**Comment by mirmaid** [comment]
5.
piirtäjät (kuvataiteilijat)
piirtäjät (ammatit)

Kaksi ongelmaa: 1. ruotsiksi eri termit. 2. Alakäsitteiden vuoksi vaikea korvata monihierarkialla, koska tällöin tulemme väittäneeksi, että kartanpiirtäjä on myös kuvataiteilija yms. Vaihtoehdot: 1. Säilytetään nykyinen jako. Eri sulkutarkenteet (vrt. esim. piirustukset)? 2. Poistetaan jako ja korvataan monihierarkialla. 3. Poistetaan jako ja korvataan RT-suhteilla. Esim. piirtäjät LT ammatit + RT kuvataiteilijat tms.

RATKAISU: jätetään piirtäjät merkityksessä kuvataiteilijat, siirretään kartanpiirtäjät ja tekniset piirtäjät suoraan käsitteen "ammatit" alle (RT piirtäjät). Siirretään muotipiirtäjät jäljellejäävän piirtäjät-käsitteen alle.

**Comment by mirmaid** [comment]
6.
valokuvaajat (kuvaajat)
valokuvaajat (kuvataiteilijat)

Hieman piirtäjien kaltainen ongelma. Tosin ruotsin kielistä eroa ei ole eikä alakäsiteongelmaakaan ole. Vaihtoehdot: 1. Säilytetään nykyinen jako. Eri sulkutarkenteet (vrt. esim. piirustukset)? 2. Poistetaan jako ja korvataan monihierarkialla. 3. Poistetaan jako ja korvataan RT-suhteilla. Esim. valokuvaajat LT ammatit + RT kuvataiteilijat tms.

RATKAISU: jätetään yksi käsite (LT kuvataiteilijat), sen alakäsitteiksi lehtikuvaajat ja paparazzit.

**Comment by mirmaid** [comment]
3.
lisääntyminen (biologiset ilmiöt)
lisääntyminen (muutos)

Ehdotus: poistetaan muutos-merkitys, koska ei käytetty tässä merkityksessä. Kelpaa esimerkiksi YSO-kokoukseen: voimmeko tehdä vapaasti tällaisia päätöksiä jatkossa?

RATKAISU: Ok, 12.1. päätetty YSO-kokouksessa

**Comment by mirmaid** [comment]
7.
altaat (ihmisen määrittämä paikka)
altaat (konkreettinen eloton objekti)

Olisi yhdistettävissä, mutta aiheuttaa ongelmia hierarkian ja alakäsitteiden vuoksi. Vaihtoehdot: 1. Säilytetään kooste. Lisätään altaat-käsitteelle LT luonnon muodostama paikka. 2. Poistetaan toinen, esim. konkreettinen eloton objekti ja siirretään tämän alakäsitteet toisaanne. Mikä on jäljelle jäävän paikka hierarkiassa?

RATKAISU: 

kastealtaat LT uskontoon liittyvä objekti
ammeet LT elottomat objektit
kylpytynnyrit LT ammeet
uima-altaat, laskeutusaltaat, patoaltaat, tekoaltaat  LT altaat = bassänger
pesualtaat?

**Comment by mirmaid** [comment]
8.
sosialismi (ideologiat)
sosialismi (talousjärjestelmät)

Ehdotetaan moniperintää, mutta ilmiöiden ja järjestelmien välillä ei (tällä hetkellä) voi olla moniperintää. Yhteiskunnalliset järjestelmät (esim. diktatuuri = järjestelmä; yksinvalta = ilmiö) voisivat yhtä hyvin olla myös ilmiöitä.

**Comment by mirmaid** [comment]
9.
kasvu (luonnontieteellinen muutos)
kasvu (yhteiskunnalliset ilmiöt)

Jaolla tässä lähinnä hierarkisoiva funktio. Rajanveto näiden kahden käsitteen välillä epäselvä. Vaihtoehdot: 1. Poistetaan jako ja päätetään alakäsitteiden paikat. (Kaikki saman kasvun alle?) 2. Säilytetään nykyinen jako.

RATKAISU: jätetään yksi kasvu, LT muutos. Kaikki kummankin kasvu-käsitteen alakäsitteet jäävät tämän alakäsitteiksi.

**Comment by tpalonen** [comment]
Toteutettu kohdat 1,3,4 ja 5. En toteuttanut vielä kohtaa 2, koska sulkutarkenneasia on käsittelemättä.

**Comment by tpalonen** [comment]
Toteutettu kaikki muut paitsi kohta 2 (vastaanotto), koska sulkutarkenneasia on käsittelemättä.

**Comment by tpalonen** [comment]
Keskustelua: olisiko sittenkin parempi ottaa YSAan reseptio, jolle ohjaustermiksi "vastaanotto (reseptio)" tai jotain tuon tapaista?

**Comment by mirmaid** [comment]
Muutosehdotus YSEssä https://github.com/Finto-ehdotus/YSE/issues/4789
