### ISSUE TITLE
ominaisuudet-käsitteen alajaottelu

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#412]
_From [SNyk...@gmail.com](https://code.google.com/u/112439428317292360191/) on July 11, 2014 12:17:04_
1. The problem / Ongelman tausta: •   Ominaisuuksien (yht. 3368 käsitettä) jako sisäisiin (788) ja ulkoisiin (2578) on useiden käsitteiden kohdalla epäintuitiivinen.
   • Sisäiset ja ulkoiset ominaisuudet ovat käytön kannalta liian suuret ja heterogeeniset luokat. Ei ole realistista ajatella esim. absoluuttisen sävelkorvan, piilokiveksisyyden, kaksikielisyyden, uusavuttomuuden, jumaluuden ja lattajalkaisuuden esiintyvän tiedonhakijan kannalta relevantteina samassa hakutuloksessa.
   • Ominaisuudet sisältävät myös nimityksiä, jotka esitetään sekä yleis- että erikoisterminä ja jotka eivät siten viittaa yhteen käsitteeseen.

Esim. rajat
yläkäsite: ulkoiset ominaisuudet
alakäsite: kuntarajat
Kuuluu ryhmiin: 00 Yleistermit, 11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia, 65 Valtio-oppi. Politiikka. Kansainvälinen politiikka
Tällaisissa tapauksissa tulisi katsoa onko kyse yhdestä vai useammasta käsitteestä. Mikäli on kyse useammasta niin arvioida, että tarvitaanko kaikkia mahdollisia merkityksiä vai rajataanko nimitys koskemaan vain yhtä käsitettä vai muodostetaanko koostekäsite. On myös katsottava, onko ylipäänsä ominaisuudet oikea paikka käsitteelle, ja mikä on ominaisuuksien suhde esim. olioihin.
• valtion alue vs. rajat vs. kuntajako
oliot > järjestelmät > yhteiskunnalliset järjestelmät > kuntajako
oliot > paikka > alueet > ihmisen määrittämät alueet > valtion alue
ominaisuudet > ulkoiset ominaisuudet > rajat (kuitenkin usein ihmisten määrittämiä)
On myös tapauksia, joissa sanalle on huomautuksessa annettu kaksi eri merkitystä, esim. ”vuorokausirytmi (toimintojen)”, jolla on käyttöhuomautus ja huomautus. Tapa on harhaanjohtava ja rikkoo niin tesaurusten kuin YSOnkin laadintaperiaatetta esittäessään yhden haku-/indeksointitermin viittaavan useaan eri käsitteeseen. (Ko. tapauksessa voidaan ajatella sanan viittaavan käytännössä yhteen käsitteeseen, joka kattaa nämä kaksi merkitystä.)
”KÄYTTÖHUOMAUTUS  
Sanalla on kaksi merkitystä. 1) Ulkoisten tekijöiden (aamuherätys, työaikataulu) ohjaama, tarkalleen vuorokauden pituisia jaksoja käsittävä rytmi. 2) Niiden elintoimintojen sisäsyntyinen rytmi, joiden toistuvan jakson pituus on suunnilleen 24 tuntia
HUOMAUTUS  
Ulkoisten tekijöiden (aamuherätys, työaikataulu) ohjaama, tarkalleen vuorokauden pituisia jaksoja käsittävä rytmi.” http://dev.finto.fi/yso/fi/page/p16620 2. Suggested solution / Ehdotettu ratkaisu: Ominaisuuksien jaottelu sisäisiin ja ulkoisiin poistetaan, ja tilalle luodaan haun laajennuksen kannalta toimivampi ratkaisu.

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=413_

**Comment by MikkoAleksanteri** [comment]
![photo 19 1 2015 13 34 32](https://cloud.githubusercontent.com/assets/8804680/5799950/26879366-9fe1-11e4-9afd-2cafcc33d0dc.jpg)
![photo 19 1 2015 13 34 41](https://cloud.githubusercontent.com/assets/8804680/5799951/2b3e2bcc-9fe1-11e4-8310-d8e5d87ce826.jpg)
![photo 19 1 2015 13 34 49](https://cloud.githubusercontent.com/assets/8804680/5799953/2f2eb044-9fe1-11e4-82a8-f7f5271125bb.jpg)
![Uploading Photo 19.1.2015 13.35.04.jpg . . .]()

**Comment by MikkoAleksanteri** [comment]
![photo 19 1 2015 13 35 04](https://cloud.githubusercontent.com/assets/8804680/5799973/7e0812aa-9fe1-11e4-92ef-faf734897d04.jpg)

**Comment by MikkoAleksanteri** [comment]
Kuvissa esiintyvät määritelmät ovat FinnONTOlaisten mukaan alkuperäisen jaottelun (sisäiset-ulkoiset) taustalla.

**Comment by tpalonen** [comment]
Sivuhuomautus: tein rajat-käsitteestä oman issuen, ks. #525

**Comment by tpalonen** [comment]
Liisan ehdotus: "Hei!

Olen nyt käynyt läpi Driven ominaisuuslistan, johon olen merkinnyt uuden yläkäsitteen sekä huomautuksia selitykseksi tai muita mahdollisina pitämiäni yläkäsitteitä. Ohessa myös PDF-dokumenttina ehdotukseni ominaisuuksien jaoksi ja keskinäiseksi hierarkiaksi.

Näyttää siltä, etteivät aivan kaikki ominaisuudet, joilla ei ole YSAssa yläkäsitettä, ole Drive-listalla (esim. vanhurskaus, volatiliteetti). En tehnyt kuitenkaan systemaattista tutkimusta asiasta."

**Comment by tpalonen** [comment]
[YSOn ominaisuudet.pdf](https://github.com/NatLibFi/Finto-data/files/85428/YSOn.ominaisuudet.pdf)

**Comment by tpalonen** [comment]
https://docs.google.com/spreadsheets/d/1Qx5t3k75yufud-c66oVQn76HmzWX8TRh8B1p8WKjKoA/edit?usp=sharing

**Comment by tpalonen** [comment]
YSO-kokouksen kommentteja Liisan ehdotukseen:
1) Yhteiskunnan rakenteeseen liittyvät ominaisuudet voisi olla ryhmittelevä käsite, jolla LT yhteiskunnalliset ominaisuudet
2) Keskinäiseen toimintaan ja suhteisiin liittyvät ominaisuudet käytävä läpi ja pohdittava, ml. sukulaisuussuhteet
3) Uskontoon liittyvät ja kultuuriset ominaisuudet käytävä läpi ja pohdittava. Ovatko yhteiskunnallisten ominaisuuksien alakäsitteitä vai eivät. Tämä on laajempi kysymys ja liittyy muihinkin YSOn vastaaviin hierarkioihin. Kulttuurisissa ominaisuuksissa osa voisi olla myös mentaalisissa ominaisuuksissa. 
4) Oikeudelliset / oikeuden alaan liittyvät ominaisuudet on ok
5) Yleiset ominaisuudet käytävä läpi. Jokunen näistä voisi sopia yhteiskunnallisiin tai muualle.
6) Ehdotetaan siirrettäväksi pois ominaisuuksista: nämä käytävä läpi.

**Comment by MikkoAleksanteri** [comment]
Taulukko läpikäyty, toteutetaan dataan käsin seuraavasti:

Mikko luo uudet yläkäsitteet, jonka jälkeen

rivit 
1-267: @mirmaid 
268-534: @MikkoAleksanteri
535-801: @tpalonen

**Comment by MikkoAleksanteri** [comment]
Uudet yläkäsitteet luotu. Tarvitaan vielä ruotsin- ja englanninkieliset käännökset labeleille ja mahdollisille kommenteille @satuniininen  @mariaforsen  Kokonaan uusia käsitteitä ovat siis 

- yhteiskunnalliset ominaisuudet
- oikeudelliset ominaisuudet
- uskontoon liittyvät ominaisuudet
- keskinäiseen toimintaan ja suhteisiin liittyvät ominaisuudet
- sukulaisuuteen liittyvät ominaisuudet
- yhteiskunnan rakenteeseen liittyvät ominaisuudet
- kulttuuriset ominaisuudet

Muuttuneita huomautuksia käsitteillä

- biologiset ominaisuudet
- fyysiset ominaisuudet
- mentaaliset ominaisuudet

**Comment by satuniininen** [comment]
Enkku tehty

**Comment by mariaforsen** [comment]
Termit käännetty ruotsiksi, alustavasti.

**Comment by kseppala** [comment]
Kaipaisin seuraavia tietoja:
- Onko 11.4. tehdyllä listalla kaikki ominaisuuksien alakäsitteet ja onko listattujen käsitteiden tarkoitus olla samalla hierarkiatasolla?
- Millä perusteella alakäsitteet on valittu?
- Mitä hyötyä ominaisuuksien jaottelusta ehdotetulla tavalla oletetaan saatavan ja millainen on vaaditun työn ja lopputuloksesta saatavan hyödyn arvioitu suhde?

**Comment by tpalonen** [comment]
Kiitoksia hyvistä kysymyksistä! Ominaisuus-kategorian käsittelemiseksi ja jatkokehittelyn pohjaksi tehtiin ehdotus, jota KK:n ontologiatyöryhmä on sittemmin työstänyt. Ominaisuusryhmien muodostamisessa on pyritty saamaan aikaan jaottelu, joka on linjassa muiden kategorioiden ryhmittelyiden kanssa ja jossa alaryhmät muodostavat temaattisesti järkeviä kokonaisuuksia. Useat entiset ryhmät ovat säilyneet (biologiset, mentaaliset ym.), joskin niiden sisältö on käyty läpi ja käsitteitä on siirretty tarvittaessa toisaalle. Uusia ryhmiä on muodostettu, jotta iso käsitemäärä, jolla oli ainoana yläkäsitteenä joko sisäiset tai ulkoiset ominaisuudet, saataisiin jaetuksi pienempiin, sisällöllisesti koherentimpiin ryhmiin. Samantapaisia ryhmityksiä on myös muissa kategorioissa (yhteiskunnalliset, kulttuuriset, oikeudelliset jne.).
 
Miksi moiseen ryhdyttiin? Jo ennen tätä uutta ryhmittelyä oli yhteisesti päätetty, että jako sisäisiin ja ulkoisiin ominaisuuksiin poistetaan. Tätä FinnONTO-projektin ajalta periytynyttä jakoa oli uudessa, todelliseen käyttöön tähtäävässä toimintaympäristössä vaikea käyttää: se  oli teoreettinen eikä tarjonnut kiinnekohtia käytännön indeksointi- tai tiedonhakutyöhön. Se ei myöskään palvellut riittävästi ontologian yhtä perusideaa eli haun laajennusmahdollisuutta. Uusien käsitteiden upottaminen sisäiset/ulkoiset-jakoon tuotti sekin usein runsaasti päänvaivaa ja eriäviä mielipiteitä ontologien kesken - mikä on sisäistä, mikä ulkoista, ei ollut selvää, vaikka teoreettista tietoa asiasta olikin saatavilla. Käyttäjien ymmärryksen asiasta ei voinut olettaa olevan sen parempi.
 
Uuden jaottelun toivotaan palvelevan tehokkaammin, mutta on kai mahdotonta muodostaa hierarkiaa, johon kaikki olisivat tyytyväisiä ja joka toimisi aina ja kaikkialla. Erityisen haasteellista se on yleisen ontologian, kuten YSOn, kohdalla. Ontologia näyttää olevan prosessi, jopa eräänlainen oppiva organisaatio, joka muotoutuu tiedon kumuloituessa, tekijöiden kehittyessä työssään ja käyttäjien tarpeiden täsmentyessä.
 
Viimeinen kysymys on mielenkiintoinen, itse asiassa perinteinen "tuhannen taalan kysymys".  "[M]itä hyötyä ominaisuuksien jaottelusta ehdotetulla tavalla oletetaan saatavan ja millainen on vaaditun työn ja lopputuloksesta saatavan hyödyn arvioitu suhde?". Vastaus löytyy osin jo yllä olevasta tekstistä eli hyötyjä ovat parempi mahdollisuus haun laajennukseen/ supistukseen, yhtenevyys muiden kategorioiden kanssa samantyyppisten ryhmitysten kautta sekä käytännönläheisemmät, ymmärrettävämmät ja tarkemmat jaottelut.
 
Viimeistä kysymystä ei kuitenkaan ole järkevää käsitellä irrallisena vain ominaisuuksiin keskittymällä. On kyse suuremmasta ontologiakokonaisuudesta, johon ominaisuudet sijoittuvat yhtenä osana täydentäen sitä osaltaan. Osia kehittämällä kehittyy kokonaisuuskin, ja muitakin kategorioita kuin ominaisuuksia on muutettu vuosien kuluessa. Olemme pyrkineet ratkaisuja tehdessämme huomioimaan ennen kaikkea käyttäjänäkökulman, pohtien sitä, mikä olisi käyttäjän kannalta looginen ja intuitiivinen tapa hahmottaa ja selailla ontologiaa. Käyttäjänäkökulman painottaminen on koettu erityisen tärkeäksi vaiheessa, jossa tutkimusprojektin kehittämä tuote siirtyy tuotantokäyttöön. Kustannus-hyötysuhteen arviointiin on varmasti vaikea löytää absoluuttista mittaria. Joka tapauksessa saamamme palaute tähän mennessä tehdyistä muutoksista on ollut positiivista.

Olemme puhuneet Finto-palvelussa ontologiatyön avoimuudesta, läpinäkyvyydestä ja vuorovaikutuksesta sidosryhmien kanssa. Tässä meillä on varmasti vielä kehitettävää. Kaikille avoimen Github-ympäristön tavoitteena on pitää ontologiatyötä keskustelevana ja vuorovaikutteisena, mutta haasteena on edelleen, miten saisimme tiedotettua työn alla olevista asioista jo työstämisvaiheessa. Tätä kautta sidosryhmillä olisi entistä parempi mahdollisuus osallistua keskusteluun ja me voisimme paremmin huomioida sidosryhmien näkemykset päätöksenteossa.

Ensimmäiseen kysymykseen vielä: yläkategorioille on mietitty keskinäistä hierarkiaa, esim. uskontoon liittyvät ominaisuudet yhteiskunnallisten ominaisuuksien alle. Emme ole kuitenkaan vielä saaneet ehdotusta tältä osin valmiiksi. Uuden jaon pitäisi koskea ominaisuudet-hierarkian kaikkia alakäsitteitä. Tosin rooli-hierarkia on vielä erillinen tapaus, jota pohdimme erikseen.

**Comment by tpalonen** [comment]
Ominaisuuksien sisäisestä hierarkiasta vielä:

Yllä olevassa keskustelussa on liitetiedostona "YSOn ominaisuudet pdf", Liisa Virtasen laatima ehdotus hierarkiasta, johon sisältyy myös ominaisuuksien sisäinen hierarkia. Tätä olemme noudattaneet, sillä poikkeuksella, että emme ole luoneet Liisan ehdottamaa "yleiset ominaisuudet"-kategoriaa, vaan sen korvaa yläkäsite "ominaisuudet".  Huomiona vielä, että vanhan YSOn ominaisuudet-hierarkiasta poiketen nyt myös suoraan ominaisuudet-käsitteen alle on laitettu käsitteitä, sellaisia, jotka ovat ominaisuuksina yleisiä ja moneen eri alaan liittyviä (abstraktiivisuus, aitous, epävarmuus jne).

ominaisuudet
. . biologiset ominaisuudet
. . fyysiset ominaisuudet
. . . . fysikaaliset ominaisuudet
. . . . kemialliset ominaisuudet
. . mentaaliset ominaisuudet
. . yhteiskunnalliset ominaisuudet
. . . . keskinäiseen toimintaan ja suhteisiin liittyvät ominaisuudet
. . . . . . sukulaisuussuhteisiin liittyvät ominaisuudet
. . . . yhteiskunnan rakenteeseen liittyvät ominaisuudet
. . . . uskontoon liittyvät ominaisuudet
. . . . oikeudelliset ominaisuudet
. . . . kulttuuriset ominaisuudet

Näiden lisäksi on vielä "aineen ominaisuudet", jonka paikkaa hierarkiassa emme ole vielä ratkaisseet.

**Comment by mariaforsen** [comment]
Oliko todella tarkoitus säilyttää "yhteiskunnan rakenteeseen liittyvät ominaisuudet"? Ehdotuksessahan alakäsitteinä ovat vain rakenne-loppuisia sanoja, jotka yhtä hyvin ovat yhteiskunnallisia kuin muutkin "yhteiskunnalliset". Esim. "yhteiskuntarakenne" on varmaan samalla tavalla "yhteiskunnallinen" kuin vaikka "työllisyysastekin".

**Comment by tpalonen** [comment]
Olet oikeassa, Maria. "Yhteiskunnan rakenteeseen liittyvät ominaisuudet" on nyt poistettu hierarkiasta ja edellä olevasta viestistäni myös.

**Comment by kseppala** [comment]
Tuntuu, että on myöhäistä kommentoida ominaisuushierarkiaa nyt, kun kyse ei ole enää ehdotuksesta, vaan muutokset on jo otettu osaksi julkaistua YSOa, mutta tässä kuitenkin muutama kommentti. Kun olette päättäneet, että erityyppisille ominaisuuksille ei välttämättä tarvita tarkempaa yläkäsitettä kuin ominaisuudet, ominaisuuksien alakäsitehierarkialla ei ole niin suurta merkitystä kuin jos kaikille ominaisuuksille pitäisi löytää tarkempi yläkäsite (aluksi luulin, että haluatte hierarkisoida kaikki ominaisuudet tarkemmin).
Ominaisuuksien alahierarkian tulisi mielestäni olla sellainen, ettei se esimerkiksi aiheuttaisi runsaasti moniperintää tai olisi muuten työläs käyttää, koska monet ominaisuuksista voivat todennäköisesti liittyä useisiin erilaisiin käsitteisiin. Tästä syystä myöskään se, että ominaisuuksien alahierarkian uudet käsitteet on muodostettu samankaltaisila perusteilla kuin muiden pääluokkien, ei välttämättä takaa hierarkian toimivuutta. Toimivuus paljastuu vasta laajalla, myös erikoisalojen tarpeet huomioon ottavalla testauksella. Edellä esitetyssä versiossa sukulaisuussuhteisiin liittyvät ominaisuudet tuntuu olevan huomattavasti tarkemmalla tasolla kuin muut hierarkian käsitteet. YSAsta peräisin oleva aineen ominaisuudet puolestaan tuntuisi perustuvan toisenlaiseen näkökulmaan kuin muut käsitteet ja siksi sen kautta voi syntyä ongelmia esim. suhteessa fysikaalisiin ominaisuuksiin.
Ymmärrän että jos pystytään erittelemään kulttuurisia ominaisuuksia, niitä voidaan verrata kulttuurisiin ilmiöihin, mutta miten ontologian käyttäjä konkreettisesti hyötyy tästä? Tai milloin haun laajentamisesta/supistamisesta nimenomaan ominaisuushierarkian avulla on hyötyä? Jos näistä löytyy esimerkkejä, niiden avulla voidaan perustella erikoisontologioiden ylläpitäjille työtä, joka tulee heidän tehtäväkseen/kustannettavakseen YSO-muutoksen myötä.

**Comment by tpalonen** [comment]
Ominaisuudet-hierarkian päätökset on nyt toteutettu YSOon ja hierarkia on edellä esitetyn mukainen (ks. kommentti 8.6.2016 tässä issuessa). Hierarkiasta löytyy nyt kolme hierarkisoivaa käsitettä, joilla ei ole enää lainkaan alakäsitteitä. Pitäisikö nämä poistaa?

sisäiset ominaisuudet
ulkoiset ominaisuudet
yhteiskunnan rakenteeseen liittyvät ominaisuudet

**Comment by tpalonen** [comment]
PÄÄTÖS 14.11.2016:

poistetaan sisäiset ominaisuudet, ulkoiset ominaisuudet ja yhteiskunnan rakenteeseen liittyvät ominaisuudet. Replacedby-suhde: ominaisuudet, paitsi yhteiskunnan rakenteeseen liittyville ominaisuuksille replacedby: yhteiskunnalliset ominaisuudet.

**Comment by tpalonen** [comment]
Keskinäiseen toimintaan liittyvät ominaisuudet nyt yhteiskunnallisten ominaisuuksien alla. Olisiko parempi siirtää suoraan ominaisuuksien alle.

Vrt. keskinäiseen toimintaan liittyvät tapahtumat on suoraan tapahtumien alla.

Huom! keskinäiseen toimintaan liittyvien ominaisuuksien alla on myös sukulaisuuteen liittyvät ominaisuudet.

(Päätöksen jälkeen issuen voisi sulkea)

**Comment by MikkoAleksanteri** [comment]
YSO-kokous:

uskontoon liittyvät ominaisuudet päätettiin siirtää suoraan ominaisuuksien alle.

@tpalonen 
> Keskinäiseen toimintaan liittyvät ominaisuudet nyt yhteiskunnallisten ominaisuuksien alla. Olisiko parempi siirtää suoraan ominaisuuksien alle?

Päätettiin olla siirtämättä.

> 
Edellä on mainittu: "Näiden lisäksi on vielä "aineen ominaisuudet", jonka paikkaa hierarkiassa emme ole vielä ratkaisseet." Onko nykyinen hierarkia "aineen ominaisuudet" YK "fyysiset ominaisuudet" ok?

Käsitelty taulukossa.

**Comment by mirmaid** [comment]
Voiko sulkea?

**Comment by mariaforsen** [comment]
Olisiko ulkonäkö YK fyysiset ominaisuudet (vrt muut sen alla olevat käsitteet)

**Comment by YSO-kokous** [comment]
ulkonäkö YK fyysiset ominaisuudet
rajat YK yhteiskunnalliset objektit

Suljetaan issue.
