### ISSUE TITLE
Luun paikka

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#414]
_From [livir...@gmail.com](https://code.google.com/u/102090373205572715207/) on August 04, 2014 08:43:22_

1. The problem / Ongelman tausta: Luu-käsitteen yläkäsitteenä on nyt ruumiinosat. Eikö luu (yksikössä) ole pikemminkin ainetta (luonnonmateriaali tms.)? 

Ruumiinosissa on luusto, mikä on ok.
Luukudokset on myös (kudokset - ruumiinosat). 2. Suggested solution / Ehdotettu ratkaisu:

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=415_

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 19.1.2015

Siirretään käsite luu käsitteen luukudokset alakäsitteeksi
