### ISSUE TITLE
pohjalaiset murheet yms.

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#415]
_From [mafors...@gmail.com](https://code.google.com/u/100004162283516840686/) on August 12, 2014 13:07:36_

Palautetta tullut:

"Vi är lite konfunderade över hur det är meningen att man ska indexera litteratur om svenska österbottniska dialekter. Vesa säger så här:

Asiasana/Ämnesord:      österbottniska dialekter (finska)< http://vesa.lib.helsinki.fi/allars/aakkoset/oe.html#österbottn >

Laajemmat termit/Vidare termer:         västfinska dialekter< http://vesa.lib.helsinki.fi/cgi-bin/allars.pl?h=västfinska&#37;20dialekter >

Suppeammat termit/Snävare termer:       mellan- och nordösterbottniska dialekter< http://vesa.lib.helsinki.fi/cgi-bin/allars.pl?h=mellan-&#37;20och&#37;20nordösterbottniska&#37;20dialekter >
nordbottniska dialekter< http://vesa.lib.helsinki.fi/cgi-bin/allars.pl?h=nordbottniska&#37;20dialekter >
sydösterbottniska dialekter< http://vesa.lib.helsinki.fi/cgi-bin/allars.pl?h=sydösterbottniska&#37;20dialekter >

Rinnakkaistermit/Relaterade termer:     kven< http://vesa.lib.helsinki.fi/cgi-bin/allars.pl?h=kven >
tornedalsfinska< http://vesa.lib.helsinki.fi/cgi-bin/allars.pl?h=tornedalsfinska >

Kuuluu ryhmiin/Hör till grupper:        [85] Språkvetenskap. Språk< http://vesa.lib.helsinki.fi/allars/ryhmat/ryhma85.html >

Suomenkielinen asiasana/Finskt ämnesord:        pohjalaismurteet< http://vesa.lib.helsinki.fi/cgi-bin/ysa.pl?h=pohjalaismurteet> "

...Jossain vaiheessa sanottiin että koskevat suomen kieltä ja sen takia lisätty "(finska)" Nyt kun myös ruotsiksi on tullut kysyntää, pitää ehkä jakaa näitä niin että on sekä "(finska)" että "(svenska)" ja vastaava suomeksi, vai halutaanko että jokainen näistä voi tarkoittaa sekä ruotsia että suomea? Jokin muutos täytyy nyt miten vain tehdä ruotsiksi.

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=416_

**Comment by satuniininen** [comment]
Englanti tehty.

**Comment by mariaforsen** [comment]
Kaikista paras olisi tietty jos saataisiin ruotsiksi ihan oma kielitieteellisesti korrekti jako näille murteille (tämä ehdotus ymmärtääkseni nyt menossa YSAan). Eli svenska > östsvenska dialekter > finlandssvenska dialekter > nyländska dialekter, åbolänska dialekter, åländska dialekter, österbottniska dialekter. Tämä voi tosin olla vaikeaa kääntää.

**Comment by tpalonen** [comment]
No niin! Tämä Marian esittämä murrejako näyttää huomattavasti paremmalta kuin jako keski- ja peräpohjalaisiin ruotsin kielen murteisiin, kun sellaisia murrealueita ei mitä ilmeisimmin ruotsin kielen puolella ole. Maria, mistä lähteestä poimit tämän murrejaon?

Eli tilanne pitäisi ruotsin kielen osalta korjata siten, että poistetaan nyt ontologiassa olevat virheelliset murteet ja lisätään sinne nämä neljä: nyländska dialekter, åbolänska dialekter, åländska dialekter, österbottniska dialekter. Nämä voi sijoittaa suomenruotsi/finlandssvenska-käsitteen alakäsitteiksi samaan tapaan kuin suomen murteet ovat suomen kielen alakäsitteitä. Myös nykyinen "pohjalaismurteet (ruotsin kieli)" pitäisi mitä ilmeisimmin poistaa, koska Marian esittämässä murrejaossa puhutaan vain eteläpohjalaisesta murrealueesta. Suomen kielen puolella pohjalaismurteet on hahmotettu kokonaisuutena, mutta epäilen erittäin vahvasti että murrealueet jakautuisivat täsmälleen samalla tavalla ruotsin puolella.

Itse en pitäisi tuota "östsvenska dialekter"-käsitteen ottamista ontologiaan olennaisena.

**Comment by mariaforsen** [comment]
Kyllä ruotsiksikin voi jakaa pohjalaismurteet tarkemmalla tasolla, mutta oikein hyvä olisi jos saataisiin neljä pääaluetta, eli pohjalaismurteet (edelleen), "Uudenmaan murteet", "Turunmaan murteet" ja "Ahvenanmaan murteet". Nykyisessä versiossahan puuttuu kolme tärkeää aluetta kokonaan.

**Comment by mirmaid** [comment]
Nyt vasta huomasin että tämä issue on pohjalaiset murheet :-D. 

Maria, onko jotain tahoa josta voi tarkistaa onko näille suomenruotsin murteiden nimille olemassa virallisia suomenkielisiä käännöksiä?

**Comment by mariaforsen** [comment]
Ei ole valitettavasti täällä ainakaan sellaista, mutta ehkä Kotus olisi paras taho tässä asiassa. Niiden sivulla ei tosin puhuta muusta kuin Ahvenanmaa, Turunmaa, Uusimaa ja Pohjanmaa murrealueina.

**Comment by MikkoAleksanteri** [comment]
Mirja seuraa johtolankoja, melkein ratkaistu.

**Comment by mirmaid** [comment]
YSAan on nyt lisätty suomenruotsin jako neljään pääalueeseen. Pohjalaismurteiden tarkempaa jaottelua en lisännyt, ennenkuin sellaiseen ryhdytään, olisi hyvä tiedää miten tarpeellinen se on - varmaan muillakin pääalueilla on alajakoa ja näiden pääalueidenkin nimien varmentaminen suomeksi osoittautui käytännössä mahdottomaksi. YSOssahan se nyt on, mutta murteiden nimet ovat suomalaisen murrealuejaon mukaiset, en tiedä puhutaanko ruotsinkielen pohjalaismurteista samoilla (tai millään) nimillä suomeksi.

**Comment by mirmaid** [comment]
Yllä mainitut on ilmeisesti poistettu, tarvitaanko suomenkielisissä edelleen sulkutarkennetta?

**Comment by mirmaid** [comment]
YSO-kokous 24.3.2017:

Jätetään sulkutarkenteet.
