### ISSUE TITLE
Mielenterveyskuntoutus

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#417]
_From [livir...@gmail.com](https://code.google.com/u/102090373205572715207/) on August 19, 2014 13:53:01_

1. The problem / Ongelman tausta: Mielenterveyskuntoutus sekä sallittuna että korvattuna käsitteenä 2. Suggested solution / Ehdotettu ratkaisu:

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=418_

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 19.1.2015

poistetaan ohjaustermi käsitteeltä "psykiatrinen kuntoutus"
