### ISSUE TITLE
Kouluneuvokset - huomautus

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#419]
_From [livir...@gmail.com](https://code.google.com/u/102090373205572715207/) on August 21, 2014 10:14:15_

1. The problem / Ongelman tausta: Kouluneuvokset-käsitteellä on englannin kieleen liittyvä huomautus. Onko oikeassa paikassa/tarpeen? 2. Suggested solution / Ehdotettu ratkaisu:

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=420_

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 19.1.2015

korjataan huomautuksen kielikoodi en
