### ISSUE TITLE
Ratkaistuja koostekäsitekokonaisuuksia: PALJON KÄSITTEITÄ!

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#420]
_From [tuomas.p...@gmail.com](https://code.google.com/u/114029607375739102692/) on August 25, 2014 13:37:33_

1. 
(kaunokirjallisuus) + (tietokirjallisuus) tyyppiset koostekäsitteet.
- dokumenttikirjallisuus, eräkirjallisuus, matkakirjallisuus, sotakirjallisuus

- Mirja: Tämäpä erikoinen tilanne - sanat on otettu YSAan selkeästi merkityksessä kaunokirjallisuus ja YSOon on otettu silti samat lisäksi tietokirjallisuutena? Selvittelen tätä...

RATKAISU: poistetaan jako ja siirretään jäljellä olevat pykälää ylemmäksi LT kirjallisuus (erikoisala)

2.
(miehet) + (naiset) tyyppiset koostekäsitteet.
- lesket (miehet/naiset), tietäjät (miehet/naiset), polttarit (miesten/naisten)

Tuomas: Jako hämmentävä eikä vaikuta edes hierarkisointiin. Ehdotan poistamista.
Mirja: Jako tulee ruotsista...
    
RATKAISU: yhdistetään ja käytetään ruotsinkielisessä labelissa och-muotoa (vrt. isovanhemmat)

3.
(palkat) + (palkkajärjestelmät) tyyppiset koostekäsitteet.
- aikapalkka, sopimuspalkka, suorituspalkka, tulospalkka, urakkapalkka

Tuomas: jakoon saatu inspiraatiota YSAsta, jossa nämä asiasanoilla on LT palkat & palkkajärjestelmät.

RATKAISU: moniperintä. Palkat siirtynevät oliot-hierarkiaan.

4.
(yritysmuodot) + organisaatiot tyyppiset koostekäsitteet.
- asunto-osakeyhtiöt, eurooppaosuuskunnat, henkilöyhtiöt, julkiset osakeyhtiöt, kiinteistöosakeyhtiöt, osakeyhtiöt, osuuskunnat

Tuomas: en pidä jakoa tarpeellisena. Ehkä organisaatio puoli tässä olennaisempi. Yritysmuoto-tyyppiset käsitteet voisi poistaa ja lisätä jäljelle jääneisiin RT yritysmuodot?

RATKAISU: poistetaan yritysmuodot. Jäljelle oleviin RT yritysmuodot.

5.
(ammatit) + (oppiarvot) tyyppiset koostekäsitteet.
apuneuvoteknikot, autoteknikot, floristit, hammasteknikot, insinöörit, maanmittausteknikot, metsätalousinsinöörit, metsäteknikot, rakennusinsinöörit, sähköteknikot, teknikot

Tuomas:  Ammatit ovat roolihierarkiassa, oppiarvot yhteiskunnallisissa tuotoksissa. Voisiko tällaisia varten luoda jonkin uuden "arvonimeen liittyvät roolit" tyyppisen käsitteen niin ei tarvitsisi jakaa käsitteitä. Näin ainakin tilapäisratkaisuna. Voisivat olla sen alla ja lisäksi ammateiden alla monihierarkkisesti. Jako tuntuu tiedonhaussa täysin tarpeettomalta.

RATKAISU: Luodaan "arvoon liittyvä rooli"-käsite. Siirretään aatelisarvot, arvonimet, oppiarvot, sotilasarvot ja virka-arvot tämän alle alakäsitteineen. Poistetaan koostekäsitejako ja korvataan monihierarkialla LT ammatit ja oppiarvot.

6.
(arvonimet) + ammatit/yms tyyppiset koostekäsitteet. 24kpl.
- asessorit, hovioikeudenneuvokset, imaamit, laamannit, lehdistöneuvokset, opetusneuvokset, rovastit, teollisuusneuvokset

Tuomas: Voisiko tällaisia varten luoda jonkin uuden "arvonimeen liittyvät roolit" tyyppisen käsitteen niin ei tarvitsisi jakaa käsitteitä. Voisivat olla sen alla ja lisäksi ammateiden alla monihierarkkisesti. Näin ainakin tilapäisratkaisuna. Jako tuntuu tiedonhaussa täysin tarpeettomalta.
Mirja: Toisaalta ammatit ovat hyvin samantyyppisiä "tuotoksia" kuin oppiarvot tai arvonimet. Eikö niiden pitäisi oikeastaan sijaita samassa paikassa hierarkiassa? Joko kaikki rooleissa tai kaikki yhteiskunnallisissa tuotoksissa? Kaikki ovat joka tapauksessa sikäli monimerkityksisiä että sanalla viitataan sekä ammatin/arvonimen haltijoihin (rooli) että ammattiin/arvonimeen itseensä (tuotos tai ilmiö)...
Mirja: Osittain näissä on myös se tilanne, että ovat oikeasti monimerkityksisiä, pitäisi käydä läpi ja palauttaa tarvittavat myös YSA-kokoukseen.

RATKAISU: Luodaan "arvoon liittyvä rooli"-käsite. Siirretään aatelisarvot, arvonimet, oppiarvot, sotilasarvot ja virka-arvot tämän alle alakäsitteineen. Poistetaan koostekäsitejako ja korvataan monihierarkialla LT ammatit ja arvonimet.

7.
erotusmenetelmät + toisenlaiseksi muuttaminen -tyyppiset koosteet
- haihdutus, kaasutus, kiteytys, linkoaminen, liuotus, nesteytys, rikastus, saostus, sedimentointi, seulonta, suodatus, tislaus, uutto, väkevöinti
        
RATKAISU: Puretaan hierarkia. LT toisenlaiseksi muuttaminen, RT erotusmenetelmät. Huom! Tarkista alakäsitteet!

8.
(*menetelmät) + (toiminta) tyyppiset koostekäsitteet.
- biokronologia, dendrokronologia, derivoiminen (matemaattiset menetelmät), fysiognomia, geokronologia, kasvullinen lisäys (biologiset menetelmät), kemiallinen analyysi (analyysimenetelmät), luonnonparannus (hoitomenetelmät), mikrolisäys.

RATKAISUT
        biokronologia, dendrokronologia, geokronologia. Poistetaan jako. LT kronologia. RT iänmääritys.
        derivoiminen. Poistetaan jako. LT kognitio.
        fysiognomia. Poistetaan jako. LT teoriat (tuotokset).
        kasvullinen lisäys, mikrolisäys. Poistetaan jako. LT kasvullinen luonti.
        kemiallinen analyysi. Puretaan jako. LT analyysi analyysitavan mukaan.
        luonnonparannus. Puretaan jako. LT parantaminen (tervehdyttäminen)
        Huom! Lisäksi: ihmeparannus LT parantaminen (tervehdyttäminen)

9.
hyödykkeet, julkishyödykkeet, kulutushyödykkeet, kertakäyttötuotteet, kestohyödykkeet, tuotantohyödykkeet

kaikki ovat hyödykkeet-käsitteen alakäsitteitä

RATKAISUT
            hyödykkeet. Puretaan jako. LT muu rooli. (vrt tuotteet)
            julkishyödykkeet, kulutushyödykkeet, tuotantohyödykkeet. Puretaan jako. LT jäljellejäävä hyödykkeet-käsite
            kestohyödykkeet. Puretaan jako. LT jäljellejäävä kulutushyödykkeet-käsite.
            kestovaipat. LT vaipat.
            perushyödykkeet. LT jäljellejäävä hyödykkeet-käsite.
            kertakäyttötuotteet. Puretaan jako. LT tuotteet.

10.
litografia, offsetlitografia, serigrafia

        Mirja: ratkaisisin tämänkin moniperintänä (grafiikan ja laaka/syväpainon menetelmiä/tekniikoita, koska taidelajikin liittyy kiinteästi tekniikkaan - mitä oikeastaan on taidelaji? vrt. esim. kuvanveisto - voisi olla muotonsa puolesta toimintaa, nyt LT kuvataide LT taide + taidelajit)
        Tuomas: monihierarkia ei tällä hetkellä YSOssa käypä, koska painomenetelmät ovat oliot-hierarkiassa (menetelmät > yhteiskunnalliset tuotokset); taidelajit taas ovat ilmiöitä (tapahtumat ja toiminta)
        
RATKAISU: Puretaan jako. Monihierarkia. LT painomenetelmät ja taidelajit. Taidelajit tulevat todennäköisesti siirtymään pois ilmiöt-hierarkiasta.

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=421_

**Comment by mariaforsen** [comment]
Polttarit näyttää olevan vielä toteuttamatta. Eli pitäisi yhdistää, ks. yllä.

**Comment by mariaforsen** [comment]
Saostus ja suodatus on ehkä toteuttamatta myös? Löytyy vielä kahdesti ja yhdellä sulkutarkenne.

**Comment by mariaforsen** [comment]
Totesimme YSO-kokouksessa tänään että nämä toteuttamatta jääneet (polttarit, saostus, suodatus) on parempi antaa Tuomaksen hoidettavaksi.

**Comment by tpalonen** [comment]
Kiitos huomiosta, Maria. Korjasin! Saostuksesta ja suodatuksesta oli näköjään jäänyt deprikointi väliin.
