### ISSUE TITLE
Hallintopiirit/organisaatio/kuntamuodot-tyyppiset koostekäsitteet

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#421]
_From [tuomas.p...@gmail.com](https://code.google.com/u/114029607375739102692/) on August 25, 2014 13:40:26_

(hallintopiirit) + (organisaatiot) (+ (kuntamuodot)) tyyppiset koostekäsitteet. (Ks. Issue 53 )
- hallinnollinen piiri, kauppalat, kaupungit, kunnat, maalaiskunnat, nimismiespiirit, riistanhoitopiirit, sairaanhoitopiirit, seurakunnat, sotilaspiirit, työsuojelupiirit, vesi- ja ympäristöpiirit, vesipiirit
- huom! myös "tuomiokunnat (alueet)", "tuomiokunnat (hallintoelimet)"

Tuomas: YSO-kokouksessa todettua: "YSAn kaupunkien alakäsitteet on YSOssa kunnat (julkisyhteisöt) alakäsitteinä: puutarhakaupungit ovat julkisyhteisöjä. YSOn nykyinen hierarkia sallisi monihierarkian julkisyhteisöjen (organisaatio) ja hallintoalueet (paikka) välillä."
Tuomas: suosittelen monihierarkiaa ja (kuntamuodot)-käsitteiden poistamista; jäljelle jääviin RT kuntamuodot

RATKAISUEHDOTUS: Poistetaan kuntamuodot-tyyppiset. Korvataan jäljellejäävä kahtiajako monihierarkialla. Lisätään poistettujen kuntamuoto-käsitteiden vastineille RT kuntamuodot. Ongelma: puukaupungit on julkisyhteisö. Voimmeko elää tämän kanssa vai onko meidän kuoltava?

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=422_

**Comment by tpalonen** [comment]
Toteutettu näiden osalta: hallinnollinen piiri, nimismiespiirit, riistainhoitopiirit, sairaanhoitopiirit, sotilaspiirit, työsuojelupiirit, vesipiirit, vesi- ja ympäristöpiirit.
