### ISSUE TITLE
Koosteissueita: maku, maito, mousset, suolaus, idealismi

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#422]
_From [tuomas.p...@gmail.com](https://code.google.com/u/114029607375739102692/) on August 25, 2014 13:59:01_

1.
maku (arvostelukyky)
maku (aineen)

Jako säilytettävä, mutta sulkutarkenteet pitäisi miettiä.

2.
maito (eritteet)
maito (maitovalmisteet)

Monihierarkia olisi hyvä ratkaisu. Voidaanko tässä tapauksessa tehdä monihierarkiaa? Vrt esim. lämpöpatterit. Monihierarkia (ilmeisesti) väittäisi, että maito on aina elintarvike.

3.
mousset (jälkiruoat
mousset (murekkeet)

Toimisiko monihierarkia? Sama ongelma kuin maidon kanssa.

4.
suolaus (säilöntä
suolaus (tiesuolan käyttö)

Säilytetään suolaus, ehdotetaan YSAan "tiesuolaus" tms. Liitetään tähän oldlabel suolaus (tiet).
Päätettävä: Tarviiko jäljellä jäävän suolaus-käsitteen preflabelilla olla sulkutarkenne, kun YSAan ehdotettavalle uudelle käsitteelle tulisi oldlabeliksi sulkutarkenteellinen muoto ["suolaus (tiet)"]?

5.
idealismi (aatteet)
idealismi (teoriat)

Säilytetään jako. Sulkutarkenne-ehdotus: asenteet + filosofia. TAI asenteet + teoriat.

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=423_

**Comment by tpalonen** [comment]
Toteutettu. Siirsin "idealismi (asenteet)" LT asenteet, että olisi linjassa sulkutarkenteen kanssa.
