### ISSUE TITLE
kysymys / kysymykset

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#425]
_From [mafors...@gmail.com](https://code.google.com/u/100004162283516840686/) on September 08, 2014 10:27:07_

1. The problem / Ongelman tausta: Ontologiaan on luotu asiasana "kysymys (ilmiöt)"(ei YSA:ssa) ja sen alla on erilaisia "keskustelun aiheita". Erikseen löytyy kysymykset (tuotokset). Mikä näiden merkitys on? Varsinkin ensin mainittu näyttää epäloogiselta (esim. miksi yksikössä?) Palautetta tullut. 2. Suggested solution / Ehdotettu ratkaisu:

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=426_

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 30.10.2015

poistetaan kysymys (ilmiöt), alakäsitteet: kaikille LT yhteiskunnalliset objektit
