### ISSUE TITLE
musiikkileikkikoulut ovat ammatillisia oppilaitoksia

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#427]
_From [tuomas.p...@gmail.com](https://code.google.com/u/114029607375739102692/) on September 10, 2014 11:22:56_

YSOn mukaan musiikkileikkikoulut ovat ammatillisia oppilaitoksia.

ammatilliset oppilaitokset > taideoppilaitokset > musiikkioppilaitokset > musiikkileikkikoulut

Ei näin.

YSOssa päiväkodit LT organisaatiot; liikuntaleikkikoulut LT päiväkodit. 

YSAssa musiikkileikkikoulut LT musiikkioppilaitokset. liikuntaleikkikouluilla ei LT:tä.

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=428_

**Comment by tpalonen** [comment]
YSO-kokouksessa 25.3.2015 todettua:
YSAssa on nyt leikkikoulut KÄYTÄ päiväkodit. Leikkikouluista tehdään mahdollisesti oma käsitteensä, koska tarkoittaa eri asiaa. Sinne voisi sijoittaa musiikkileikkikoulutkin.

**Comment by mirmaid** [comment]
YSA 2/2015
