### ISSUE TITLE
kaanonit (sävellykset) + kaanonit (valikoimat) - oikeat definedconcept-suhteet YSAan

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#428]
_From [tuomas.p...@gmail.com](https://code.google.com/u/114029607375739102692/) on September 11, 2014 08:42:35_

Aiemmin päätettiin seuraavaa (ks. Issue 405 ):

kaanonit (koko)
kaanonit (ohjeet)
kaanonit (sävellykset)
kaanonit (uskonnolliset tuotokset)

Säilytetään uskonnolliset tuotokset ja sävellykset. Uskonnolliset tuotokset-käsite jää edustamaan tässä merkitystä: kanonisoidut teokset yms. Muut poistetaan. YSAssa on juuri jaettu termi kahtia: "kaanonit (sävellykset)", "kaanonit (valikoimat)". 

TODO:

YSOon on siis liitettävä nyt oikeat defineconceptit jahka YSA-muutokset tulevat YSOon!

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=429_

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 19.1.2015

päivitys tullut ysasta ysoon, korjaus täytyy tehdä.
