### ISSUE TITLE
Monihierarkiaratkaisujen uudelleen läpikäyntiä

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#429]
_From [tuomas.p...@gmail.com](https://code.google.com/u/114029607375739102692/) on September 11, 2014 15:13:48_

YSO-kokouksissa ja koostekäsitepalavereissa tehdyt monihierarkiaratkaisut ovat herättäneet keskustelua. Ontologiaperiaatteiden mukaan ISA-suhteen pitäisi päteä kaikissa tapauksissa eli jos käsitteellä on monihierarkia, sen kaikkien ilmentymien pitäisi olla sekä a että b. Seppälä & Hyvönen -raportti: "Aina kun käsitteelle annetaan useampia hierarkkisia yläkäsitteitä, on varmistettava, että kaikkien yläkäsitteiden piirteet periytyvät alakäsitteelle. Esimerkiksi 'valotusmittarit LT mittarit, valokuvausvälineet'. Esimerkkitapauksessa moniperintä on sallittu, koska ei ole olemassa erikseen valotusmittaria, joka olisi mittari, mutta ei valokuvausväline, vaan valotusmittari on aina molempia."

Tässä listaus käsitteistä, jotka on ratkaistu monihierarkiala:

I (ks Issue 234 )

- farssit (näytelmät) + (elokuvat)
- komediat (näytelmät) + (elokuvat)+ (sarjaohjelmat)
- melodraamat (näytelmät) + (elokuvat) + (musiikkinäytelmät)
- musikaalit (näytelmät) + (elokuvat) + (musiikkinäytelmät)
- romanttiset komediat (näytelmät) + (elokuvat)
- sotilasfarssit (näytelmät) + (elokuvat)
- tragediat (näytelmät) + (elokuvat)
- tragikomediat (näytelmät) + (elokuvat)
- animet (animaatioelokuvat) + (sarjaohjelmat)

ISA-suhteet eivät toteudu 100&#37; tässä monihierarkiassa.

EHDOTUS: LT + RT tapauskohtaisesti. Tai kaikille LT teokset.

II (ks Issue 235 )

kaakao, tee, kahvi
(nautintoaineet) + (juomat)

Mielestäni monihierarkia on tässä täysin ok.

III (ks Issue 278 )

- (onnettomuudet) + (sääilmiöt) tyyppiset koostekäsitteet:
   - hirmumyrskyt, myrskyt (luonnononnettomuudet), pyörremyrskyt
- (luonnononnettomuudet) + (fysikaaliset ilmiöt) tyyppiset koostekäsitteet:
   - hyökyaallot (aallot), lumivyöryt, määnjäristykset, maanvyörymät, tulvat

Mielestäni monihierarkia tässäkin ok.

IV (ks Issue 284 )

selkolehdet (aikakauslehdet) + (sanomalehdet)
sensaatiolehdet (aikakauslehdet) + (sanomalehdet)

Tässä ISA ei toimi.

EHDOTUS: LT + RT

V (ks Issue 326 )

lämpöpatterit (lämmönvaihtimet) + lämpöpatterit (lämmityslaitteet)

Tässä ISA ei skulaa.

EHDOTUS: LT + RT

VI (ks Issue 384 )

marmori LT kalkkikivi + LT metamorfiset kivilajit

Tämä monihierarkia ilmeisesti ok?

VII (ks Issue 386 )

porvaristo (historialliset säädyt) + (yhteiskuntaluokat)

Monihierarkia ok vai ei ok?

VIII (ks Issue 421 )

(palkat) + (palkkajärjestelmät) tyyppiset koostekäsitteet.
- aikapalkka, sopimuspalkka, suorituspalkka, tulospalkka, urakkapalkka

Monihierarkia ei toimi.
EHDOTUS: LT palkat

IX (ks Issue 421 )

(ammatit) + (oppiarvot) tyyppiset koostekäsitteet.
apuneuvoteknikot, autoteknikot, floristit, hammasteknikot, insinöörit, maanmittausteknikot, metsätalousinsinöörit, metsäteknikot, rakennusinsinöörit, sähköteknikot, teknikot

Monihierarkia ei toimi, vaikka siirretäänkin rooli-hierarkiaan.

EHDOTUS:
apuneuvoteknikot LT ammatit
autoteknikot LT ammatit
floristit LT ammatit tai LT oppiarvot
hammasteknikot LT ammatit tai LT oppiarvot
insinöörit LT oppiarvot 
maanmittausteknikot LT ammatit
metsätalousinsinöörit LT oppiarvot
metsäteknikot LT ammatit tai LT oppiarvot
rakennusinsinöörit LT ammatit
sähköteknikot LT ammatit tai LT oppiarvot
teknikot LT oppiarvot

X (ks Issue 421 )

(arvonimet) + ammatit/yms tyyppiset koostekäsitteet.
- asessorit, hovioikeudenneuvokset, imaamit, laamannit, lehdistöneuvokset, opetusneuvokset, rovastit, teollisuusneuvokset

Monihierarkia ei toimi, vaikka siirretäänkin rooli-hierarkiaan.

EHDOTUS: 
asessorit: säilytetään jako
hovioikeudenneuvokset: LT ammatit
imaamit: LT arvonimet
laamannit: LT toimintaan liityvä rooli?
lehdistöneuvokset: LT arvonimet
opetusneuvokset: LT arvonimet
rovastit: LT arvonimet
teollisuusneuvokset: LT arvonimet

XI (ks Issue 421 )

(taidelajit) + (painomenetelmät)
- litografia, offsetlitografia, serigrafia

Toimiiko monihierarkia vai ei? Ainakaan Mikon mielestä ei toiminut: litografian instanssi ei ole eräänlainen painomenetelmä.
EHDOTUS: LT painomenetelmät

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=430_

**Comment by tpalonen** [comment]
Toteutettu kaikki.
