### ISSUE TITLE
YSAn naistyö-käsite tuplana SKOS-versiossa

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#43]
_From [osma.suominen@helsinki.fi](https://code.google.com/u/osma.suominen@helsinki.fi/) on January 02, 2014 09:25:37_

What steps will reproduce the problem? 1. hae Finton YSAsta "naistyö" What is the expected output? What do you see instead? Tulee kaksi viitettä, vaikka ilmeisesti toinen näistä on jollain MARC-koodilla merkitty poistetuksi ja VESA ei sitä näytä.

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=40_

**Comment by osma** [comment]
Tätä ei tapahdu enää, johtuu kaiketi uudesta muuntimesta.
