### ISSUE TITLE
Valtiopäivät-kooste: YSO-kokoukseen

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#437]
Tämän käsittely unohtui vanhassa onki-data-issuessa 391, jossa oli muitakin koostekäsitteitä (ja nämä muut on jo ratkaistu)

valtiopäivät (kansanedustajalaitokset)
valtiopäivät (maapäivät)
valtiopäivät (poliittinen historia)

Tausta: Merkitysero lienee selvä.
Ehdotus: Poistetaan maapäivät-käsite. YSAan otettaneen erillinen "maapäivät"-termi. Jäljelle jäävien osalta kaksi vaihtoehtoa: 1. Säilytetään jako. Paremmat sulkutarkenteet? 2. Vain yksi valtiopäivät-käsite.

**Comment by MikkoAleksanteri** [comment]
YSOkokous 30102015:

Mirja selvittää.

**Comment by mirmaid** [comment]
Muutosehdotus YSEssä https://github.com/Finto-ehdotus/YSE/issues/4787

**Comment by mariaforsen** [comment]
YSAan otettu "maapäivät", päivitetäänkö myös YSOon muotoon "maapäivät" (nyt "valtiopäivät (maapäivät)").

**Comment by mirmaid** [comment]
YSO-kokous 24.3.2017:

Korjattu YSOon.
