### ISSUE TITLE
Käsitteet joilla ei definedconcept-suhdetta YSAan

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#438]
Näillä ei ole definedconcept-suhdetta YSAan. Näiden käsittely on kesken joko YSO-kokouksessa / YSA-kokouksessa tai muuten, joten definedconcept-suhdetta ei voi päättää ennen kuin on päätetty käsitteen kohtalo muuten.

Pyhän kolminaisuuden kirkko (Helsinki) 
aloitteet (hallinto- ja lakialoitteet) 
hävittäjät (laivat) 
jalustat (korokkeet) - ks issue  #434
jalustat (siirrettävä) - ks  issue #434
keskustelu (väittely) 
kilvet (konkreettinen eloton objekti) 
kilvet (orgaaninen rakenne)
kirjallisuus (erikoisala) 
kokoelmatietokannat (kirjastot) - ks issue #436
lähitaistelu (urheilu)  - ks issue #436
piirustukset (taideteokset) 
polarisaatio (yhteiskunnalliset ilmiöt) 
runot (kulttuuriset tuotokset)  - ks issue #436
valtiopäivät (maapäivät)  - ks issue #437
vastaanotto (ymmärtäminen) 
kuvaukset (tuotokset) - käsitteellä ei vastaavaa termiä YSAssa. Ei myöskään defined concept -suhdetta YSAan.

**Comment by mirmaid** [comment]
~~Pyhän kolminaisuuden kirkko (Helsinki)~~
aloitteet (hallinto- ja lakialoitteet)
hävittäjät (laivat)
jalustat (korokkeet) - ks issue #434
jalustat (siirrettävä) - ks issue #434
keskustelu (väittely)
kilvet (konkreettinen eloton objekti)
kilvet (orgaaninen rakenne)
kirjallisuus (erikoisala)
kokoelmatietokannat (kirjastot) - ks issue #436
lähitaistelu (urheilu) - ks issue #436
piirustukset (taideteokset)
polarisaatio (yhteiskunnalliset ilmiöt)
runot (kulttuuriset tuotokset) - ks issue #436
valtiopäivät (maapäivät) - ks issue #437
vastaanotto (ymmärtäminen)
kuvaukset (tuotokset) - käsitteellä ei vastaavaa termiä YSAssa. Ei myöskään defined concept -suhdetta YSAan.
