### ISSUE TITLE
uhrit

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#440]
Termi uhrit näyttää nyt olevan monimerkityksinen (ja on käytettykin Melindassa niin). Termin kohdalla luokat:  
 50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi
 53 Uskonto. Teologia. Uskontotiede
 67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet
 69 Oikeus. Lainsäädäntö

MOT: 
1. uhrattava t. uhrattu esine, eläin tms., uhrilahja. Lahja-, sovitusuhri. Kiitosuhri. Eläin-, ihmis-, ruokauhri. Poltto-, teurasuhri. Jumalille annetut, uhratut uhrit. Polttaa uhri alttarilla. Uhriksi teurastettu karitsa. Murtunut mieli on minun uhrini VT.
Kuv. Antaa henkensä uhriksi isänmaalleen. Vapauden puolustamiseksi ei mikään uhri ole liian suuri.
Usk. Kristuksen sovituskuolemasta. Ristinuhri Golgatan VIRSIKIRJA.
2. uhraaminen, uhrimenot. Toimittaa uhri.
3. jksta joka joutuu kärsimään, vahingoittuu t. menettää henkensä jnk vuoksi t. on jnk vahingollisen toiminnan kohteena t. alttiina jllek (kielteiselle). Pahoinpitelijän uhri. Rikoksen, väkivallan uhri. Pilanteon uhri. Kuolonuhri. Onnettomuuden uhrien hautaus. Heikot jäät ovat vaatineet uhrinsa. Joutui ennakkoluulojen uhriksi. 

Yleisimmin varmaan käytetty 3. merkityksessä. Olisiko syytä jakaa tai rajoittaa luokkien avulla? Tuskin se joka on kiinnostunut rikoksen uhreista yms. olisi kiinnostunut uhrista uskonnollisena käsitteenä.

**Comment by mirmaid** [comment]
YSA 2/2015

**Comment by mirmaid** [comment]
YSO-kokous 2.11.2015
- ratkaistu YSAssa, korjataan YSOssa muutospäivitysten yhteydessä

**Comment by mariaforsen** [comment]
Ei ole näköjään vieläkään päivittynyt, koska YSOssa on uhrit myös luokissa:

    50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi
    53 Uskonto. Teologia. Uskontotiede

**Comment by mirmaid** [comment]
Oliko siis niin että muuttuneet luokat ei vielä viime vuonna siirtyneet (kuinkahan paljon näitäkin on)? @osma

**Comment by osma** [comment]
Muuttuneista luokista on kyllä tehty muutospropertyt (newGroup, removedGroup) jo silloin, kun uudenmallinen päivitin ensimmäisen kerran ajettiin helmikuussa 2016. Nämä täytyy toki käsipelillä sitten toistaa YSOn puolella.

**Comment by tpalonen** [comment]
@osma voitko tarkentaa mitä tarkoittaa "Nämä täytyy toki käsipelillä sitten toistaa YSOn puolella."

**Comment by osma** [comment]
Siis tarkoitin, että muuttuneet täytyy käydä läpi ja ryhmämuutokset siinä yhteydessä toistaa YSOssa. Eli kuten te jo teettekin.
