### ISSUE TITLE
MUSAn päivitys Fintoon: kommenttikenttä ei päivity

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#441]
Huomattiin, että MUSAa päivitettäessä asiasanan muut päivitetyt tiedot (lisätyt korvatut termit) päivittyivät Fintoon, mutta kommenttikenttään lisätty kommentti ei päivittynyt. Tämä huomattiin 13.10.2014 editoidussa asiasanassa "cover-versiot", johon on lisätty useita korvattuja termejä (cover-esitykset, cover-levytykset jne) sekä 680i-kenttään kommentti: "Populaarimusiikissa kappaleen ensimmäisen levytyksen jälkeen jonkun toisen esittäjän siitä tekemä levytys tai esitys. Termiä voidaan myös käyttää lisämääreenä kokonaista cover-versioita sisältävää albumia tai niihin erikoistunutta esittäjää indeksoitaessa." Lisätyt korvatut termit näkyvät Fintossakin mutta kommentti näkyy vain Vesassa, ei Fintossa. Ilmeisesti tämä on laajempikin ongelma eikä rajoitu vain tähän asiasanaan.

**Comment by osma** [comment]
Tämä korjautui jo aikaa sitten uuden MARC-SKOS-muuntimen myötä. Kts http://finto.fi/musa/fi/page/p73540
