### ISSUE TITLE
tuulimyllyt

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#442]
Allärsissa tuulimyllyt=väderkvarnar+vindkraftsaggregat

MOTin ja esim. Wikipedian perusteella viittaa tuulimylly sana niihin vanhoihin myllyihin, joiden käyttö perustuu tuulen energian hyödyntämiseen erityisten pyörivien siivekkeiden avulla. Näin valittu myös ALLFOon, mutta toisaalta Melindassa näyttää olevan käytetty myös tuulivoimaloista? Ks. myös RT-käsitteet YSOssa. Onko niin ettei viittaa tulivoimaloihin ollenkaan ja jos näin on, onko se kaikille käyttäjille selvää? Ruotsink. ratkaisu riippuu tästä.

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 19.1.2015

hyväksytään Liisan ehdotus, eli toteutetaan:

tuulimyllyt (myllyt) KÄ tuulimyllyt ja tuulimyllyt (voimalat) KÄ tuulivoimalat

Vanhoille tuulimyllyille selitys: "Tarkoittaa perinteisiä, etupäässä viljanjauhatusta varten rakennettuja myllyjä. Sähköntuotannon yhteydessä käytä käsitettä tuulivoimalat."
