### ISSUE TITLE
Kielioppi-käsite alakäsitteineen

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#448]
kielioppi
     - dependenssikielioppi
     - funktiokielioppi
     - generatiivinen kielioppi
     - kognitiivinen kielioppi
     - konstruktiokielioppi
     - lauseoppi
     - muoto-oppi -- kielitiede
     - systeemis-funktionaalinen kielioppi
     - äänneoppi
       - - fonologia
        - - - fonotaksi

Kielioppi-käsitteen hierarkia on sekava. Se on tieteiden alakäsite. Toisaalta sen alla on 1) kielitieteen teorioita (jotka ovat muotoa *kielioppi) ja lisäksi siellä on 2) lauseoppi, muoto-oppi ja äänneoppi alakäsitteineen. Ensimmäisen joukon osalta (dependenssikielioppi, funktiokielioppi, generatiivinen kielioppi, konstruktiokielioppi, systeemis-funktionaalinen kielioppi) ehdotukseni on yksinkertainen: siirretään nämä kielioppiteoriat-käsitteen alle.

Kielioppi-termi ja muutama sen alakäsitteistä viittaavat oikeastaan useampaan eri käsitteeseen. Tieteen termipankin mukaan kielioppi = "kielen järjestelmä ja rakenne tai sen kuvaus Kieliopin osa-alueita ovat morfologia, syntaksi ja fonologia sekä monien kuvausten mukaan semantiikkakin. Deskriptiivisen eli kuvailevan tieteellisen kieliopin lisäksi termiä käytetään myös kielenkäyttöä ohjailevista (normatiivisista) kieliopeista eli kielioppaista, joihin sisällytetään lisäksi oikeinkirjoitusohjeita.". Collins Cobuild English Language Dictionary (1988) tekee vastaavanlaisen jaon:  "grammar 1.1. the rules of a language; 1.2. the way someone either obeys or does not obey the rules of grammar; 2.1. a book that describes the rules of a language; 2.2. a theory that is intended to explain the rules of a language." Englanninkielinen Wikipedia lisää vielä yhden merkityksen: "The term refers also to the study of such rules, and this field includes morphology, syntax, and phonology, often complemented by phonetics, semantics, and pragmatics." Samaa hajontaa on myös termeissä lauseoppi, muoto-oppi, äänneoppi, fonologia ja fonotaksi. Viimeksi mainittun merkitys Tieteen termipankin mukaan on "foneemien ja foneemijonojen yhdistelyrajoitukset". Toisaalta Gummeruksen Kultaisen sivistyssanakirjan (2005) mukaan fonotaksi on "fonologian ala, jossa tutkitaan foneemijonoja". Englannin kielessä phonotactics taas tuntuu viittaavan nimenomaan fonologian osa-alueeseen, kun taas rajoituksista/säännöstöstä puhuttaessa käytetään nimitystä "phonotactic contraints".

Erillinen asia on vielä se, että lauseopilla, muoto-opilla ja äänneopilla on kullakin synonyyminen sivistyssanavastineensa: syntaksi, morfologia ja fonologia. YSOssa äänneoppi ja fonologia löytyvät erillisinä käsitteinään. Syntaksi taas on ohjausterminä lauseopilla ja morfologia löytyy erillisenä käsitteenä, mutta viittaa biologiaan.

Joka tapauksessa minusta tässä sotkussa erottuu kunkin käsitteen kohdalla kolme olennaista merkitystä: 1) tietyn kielen säännöstö; 2) tuon kielen säännöstön kuvaus; 3) oppi tai teoria kielten säännöstön kuvaamisesta. Tahtotila ei varmaankaan ole, että käsitteet jaettaisiin, koska merkitykset ovat osin päällekkäisiä. Lisäksi minusta edellä mainituista merkityksistä sekä 2 että 3 voidaan tulkita kielitieteen osa-alueiksi: suomen kielen kieliopin kuvaus on kielitieteellistä tutkimusta. Isoin henkilökohtainen ongelma minulla on kielioppi-termin kanssa. Se assosioituu (ainakin suomen kielessä) muita vahvemmin merkitykseen "tietyn kielen säännöstö". Lauseoppi (eli syntaksi), muoto-oppi (eli morfologia), äänneoppi (eli fonologia) taas viittaavat vahvemmin kielitieteen tutkimushaaroihin, joihin lingvisti voi erikoistua. Syntaksista on kielitieteessä tarjolla paljon erillisiä kursseja, mutta kielioppikursseihin en ole koskaan törmännyt. Kielioppi esiintyykin harvoin tässä merkityksessä. Tästä syystä olen sitä mieltä, että lauseopille, muoto-opille ja äänneopille hyvä vaihtoehto yläkäsitteeksi olisi kielitiede.

Tästä pääsemmekin vielä yhteen ongelmaan: voiko tietyn tieteen osa-alue olla tuon tieteen alakäsite? Ongelma ulottuu YSOssa kielitieteen lisäksi mm. historiakäsitteisiin. Tätä problematiikka pitäisi tutkia vielä lisää. Joka tapauksessa tässä summa summarumina ehdotukseni:

I EHDOTUS 1

dependenssikielioppi LT kielioppiteoriat
funktiokielioppi LT kielioppiteoriat
generatiivinen kielioppi LT kielioppiteoriat
kognitiivinen kielioppi LT kielioppiteoriat
konstruktiokielioppi LT kielioppiteoriat
systeemis-funktionaalinen kielioppi LT kielioppiteoriat

II EHDOTUS 2 

poistetaan fonologia-käsite
lisätään äänneoppi-käsitteelle ohjaustermi fonologia

III EHDOTUS 3 A) 

säilytetään nykyinen hierarkia muutoin kuin ehdotusten 1 ja 2 osalta

EHDOTUS 3 B)

kielioppi LT kielitiede
lauseoppi LT kielitiede + RT kielioppi
muoto-oppi -- kielitiede LT kielitiede + RT kielioppi
äänneoppi LT kielitiede + RT kielioppi
fonotaksi LT äänneoppi

EHDOTUS 3 C) ??

Jos olemme sitä mieltä, että tieteen osa-alueet eivät ole ko. tieteen alakäsitteitä, näille pitäisi löytää uusi paikka hierarkiassa. Mikä?

**Comment by mirmaid** [comment]
Liisan 2014 lähettämä ehdotus "YSAn tarpeisiin":

**kielioppi**
ST fonologia
     muoto-oppi – kielitiede
     lauseoppi
RT kielioppiteoriat
     äänneoppi (?)
     sanaluokat
     RT:nä voisi olla paljon muutakin, esim. taivutus – kielitiede, sananmuodostus, definiittisyys…

(voisiko kielioppia ajatella YSOssa järjestelmänä? kieli on järjestelmissä)

**kielioppiteoriat**
LT teoriat
ST dependenssikielioppi
      funktiokielioppi
      generatiivinen kielioppi
      kognitiivinen kielioppi
      konstruktiivinen kielioppi
      systeemis-funktionaalinen kielioppi	
RT kielioppi

**Comment by mirmaid** [comment]
Ratkaisu:
kielioppi YK kielitiede
dependenssikielioppi LT kielioppiteoriat
funktiokielioppi LT kielioppiteoriat
generatiivinen kielioppi LT kielioppiteoriat
kognitiivinen kielioppi LT kielioppiteoriat
konstruktiokielioppi LT kielioppiteoriat
systeemis-funktionaalinen kielioppi LT kielioppiteoriat

**Comment by mirmaid** [comment]
^ Onkohan tuo RT tarpeen, kun kielioppi RT kielioppiteoriat on olemassa?

Onko kieliopin hierarkia nyt ok? Universaalikieliopista ei mainintaa...

**Comment by mirmaid** [comment]
Siirretään UG, muuten ok.
