### ISSUE TITLE
selittämättömät ilmiöt ST paranormaalit ilmiöt

### ISSUE THREAD

**Issue by satuniininen** [NatLibFi/Finto-data#449]
Ovatko nämä todellakin hierarkkisessa suhteessa toisiinsa vai pitäisikö niiden mieluummin olla toistensa rinnakkaiskäsitteitä (kuten YSAssa)?

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 19.1.2015

hierarkia ok, voisiko ongelman taustaa avata lisää?

**Comment by satuniininen** [comment]
Turha, poistan.
