### ISSUE TITLE
Kiwissä käsitellyt isot koostekäsitekokonaisuudet

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#450]
Näitä on käyty läpi Kiwissä, mutta poimitaan nämä selkeyden vuoksi nyt tänne Githubiin muiden issueiden joukkoon. Läpikäymättä siis vielä seuraavat.

I (taidelajit) + (erikoisala) - tyyppiset koosteet
- mediataide
- musiikki
- tanssi
- teatteri
- flamenco (taidelajit) + flamenco (perinnemusiikki)
-"skenografia (taidelajit)" + "skenografia (taiteellinen luonti)"

Myös kirjallisuus on jaettu vastaavasti, mutta ei itse asiassa sisällä koostekäsitettä. Kirjallisuudesta on erillinen issue. Ks. #435 . Vrt. myös taidelajit+painomenetelmät tyyppiset koostekäsitteet, joita on käsitelty issuessa #420 ja käsitellään uudelleen issuessa #429 (ratkaistiin ensin monihierarkialla mutta todettiin ratkaisu ristiriitaiseksi ontologiaperiaatteiden kanssa). Vrt myös "baletti (taidelajit)", "balettimusiikki". (Ei ole koostekäsite), "ooppera (taidelajit) + "oopperat (teokset)" (ei ole koostekäsite), "kansantanssi (taidelajit)", "kansantanssi (tanssi)", (ei ole koostekäsite). HUOM! YSOsta löytyy myös "tanssiala" ja "teatteriala" erikseen. 

II (tanssit) + (tanssimusiikki) tyyppiset koostekäsitteet (hieman varioivia sulkutarkenteita tässä).
- cha-cha-chat 
- foxtrotit
- humpat
- jenkat
- jivet
- kansantanssit
- masurkat
- menuetit
- polkat
- poloneesit
- polskat
- purpurit
- rumbat (latinalaistanssit)
- sambat (latinalaistanssit)
- tangot
- valssit
 
Keskustelua: Mirja: Otan tämän esille MUSAn ylläpidon kanssa. Yksi sana musiikinlajille ja tanssille olisi käyttäjäystävällistä, mutta monikko on tässä ongelmallinen. Tuomas: Tähän jakoon on vaikuttanut YSAssa oleva monihierarkia. Käsitteet ovat LT tanssimusiikki + tanssit. Purpurit asiaa käsiteltiin käännösten osalta issuessa #432 . 

III (aatteet) + (tyylit) tyyppiset koostekäsitteet.
- estetismi
- formalismi
- illusionismi
- realismi
- valistus (aatteet), valistus (keskinäinen toiminta). Ei sisällä koostekäsitettä.
- idealismi (aatteet) + idealismi (teoriat)

IV  (maalaustaide/piirustustaide) + (toiminta) tyyppiset koostekäsitteet.

- elävän mallin maalaus
- elävän mallin piirustus
- henkilömaalaus
- historiamaalaus
- maisemamaalaus
- merimaalaus

Tästä käyty keskustelua issuessa #400 .

**Comment by mirmaid** [comment]
I (taidelajit) + (erikoisala) - tyyppiset koosteet:
Ratkaistaan issuessa #59

**Comment by mirmaid** [comment]
II (tanssit) + (tanssimusiikki) tyyppiset koostekäsitteet (hieman varioivia sulkutarkenteita tässä):
Ratkaistaan issuessa #484

**Comment by tpalonen** [comment]
Toteutettu kohta 4 (maalaustaide etc).

**Comment by tpalonen** [comment]
Kohta 3 (eli ainoa kohta joka tässä issuessa on vielä "ratkaisematta") on vielä epäselvä valistus-käsitteiden osalta. Miten YSA-muutos vaikuttaa YSOon ja pitäisikö "valistus (keskinäinen toiminta)" poistaa?

**Comment by mariaforsen** [comment]
Jos YSA/Allärsissa halutaan rajata valistus termin käyttö siihen historialliseen kontekstiin, pitäisikö luokka 57 poistaa? Ruotsiksi on tosiaan "upplysningen" vastine ja kun olen korjannut upplysning-sotkua tietokannoissa olen huomannut se olevan hyvin ongelmallista, koska valistus on usein kyllä käytetty  "tiedotustoiminnasta" ja kasvatuksesta. En poistaisi YSOn ratkaisua, joka on selkeämpi ja toimiva ruotsiksikin.

**Comment by tpalonen** [comment]
Suljen tämän issuen ja luon uuden valistukselle selkeyden vuoksi.
