### ISSUE TITLE
Talonpojat

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#458]
Nykyisin "talonpojat" on säädyt-käsitteen alakäsite. Varmaankin tämä olisi ok, jos muoto olisi "talonpoikaissääty" vaan kun ei ole. Olisiko käsitteelle löydettävissä parempi paikka hierarkiassa?

**Comment by mirmaid** [comment]
YSO-kokous 2.11.2015
- LT sosioekonomiseen ryhmään liittyvä rooli
