### ISSUE TITLE
YSOssa päällekkäisiä termejä ruotsiksi

### ISSUE THREAD

**Issue by osma** [NatLibFi/Finto-data#461]
Huomasin että YSOssa on jonkin verran tapauksia joissa samaa termiä käytetty (prefLabelina) useammalla eri käsitteellä, vaikka termien kai pitäisi YSOssakin olla yksilöiviä (paitsi englanninkielisten).

Tällä YSAGUIn SPARQL-kyselyllä saa listattua ne kaikki: http://bit.ly/1ASS19H
(korjattu kysely niin, ettei deprekoituja lasketa)

Tällä hetkellä (15.1.2015) suomenkielisiä ei yhtään ja ruotsinkielisiä 19 kpl.

**Comment by mirmaid** [comment]
YSO-kokous 18.4.2016

Tuomas tekee uuden SPARQL-kyselyn.

**Comment by mariaforsen** [comment]
Melkein kaikki ovat sellaisia ettei tupla saada pois ennen kuin suomeksi on tehty muutoksia (mm. edeltäjä-seuraajia)

**Comment by mariaforsen** [comment]
Huom. asetyylikoliini nyt kahdesti!
