### ISSUE TITLE
YSOssa rikkinäisiä linkkejä YSAan ja Allärsiin

### ISSUE THREAD

**Issue by osma** [NatLibFi/Finto-data#462]
YSOssa on closeMatch-suhteita YSA- ja Allärs-käsitteisiin, joita ei (enää?) löydy. Tilalle pitäisi varmaan etsiä oikeat vastaavuudet.

Tässä YASGUI-kyselyt joilla löytää tällaiset tapaukset:
YSO-YSA http://bit.ly/1F3Xpqn
YSO-Allärs http://bit.ly/1F3XMRO

Tässä vielä lista tämänhetkisistä tapauksista:

YSO concept http://www.yso.fi/onto/yso/p13977 linked to nonexistent Allars concept http://www.yso.fi/onto/allars/Y18285
YSO concept http://www.yso.fi/onto/yso/p26434 linked to nonexistent Allars concept http://www.yso.fi/onto/allars/Y44650
YSO concept http://www.yso.fi/onto/yso/p22093 linked to nonexistent Allars concept http://www.yso.fi/onto/allars/Y36187
YSO concept http://www.yso.fi/onto/yso/p25008 linked to nonexistent YSA concept http://www.yso.fi/onto/ysa/Y182138
YSO concept http://www.yso.fi/onto/yso/p3438 linked to nonexistent Allars concept http://www.yso.fi/onto/allars/Y27937
YSO concept http://www.yso.fi/onto/yso/p4347 linked to nonexistent Allars concept http://www.yso.fi/onto/allars/Y30412
YSO concept http://www.yso.fi/onto/yso/p12698 linked to nonexistent Allars concept http://www.yso.fi/onto/allars/Y30273
YSO concept http://www.yso.fi/onto/yso/p21485 linked to nonexistent Allars concept http://www.yso.fi/onto/allars/Y18420
YSO concept http://www.yso.fi/onto/yso/p16194 linked to nonexistent Allars concept http://www.yso.fi/onto/allars/Y29867
YSO concept http://www.yso.fi/onto/yso/p16274 linked to nonexistent Allars concept http://www.yso.fi/onto/allars/Y40246
YSO concept http://www.yso.fi/onto/yso/p25624 linked to nonexistent YSA concept http://www.yso.fi/onto/ysa/Y181838
YSO concept http://www.yso.fi/onto/yso/p10939 linked to nonexistent Allars concept http://www.yso.fi/onto/allars/Y30729
YSO concept http://www.yso.fi/onto/yso/p8462 linked to nonexistent Allars concept http://www.yso.fi/onto/allars/Y25285
YSO concept http://www.yso.fi/onto/yso/p12563 linked to nonexistent YSA concept http://www.yso.fi/onto/ysa/Y149006
YSO concept http://www.yso.fi/onto/yso/p21456 linked to nonexistent Allars concept http://www.yso.fi/onto/allars/Y40213
YSO concept http://www.yso.fi/onto/yso/p18896 linked to nonexistent Allars concept http://www.yso.fi/onto/allars/Y27348
YSO concept http://www.yso.fi/onto/yso/p1677 linked to nonexistent Allars concept http://www.yso.fi/onto/allars/Y41286
YSO concept http://www.yso.fi/onto/yso/p5658 linked to nonexistent Allars concept http://www.yso.fi/onto/allars/Y31140
YSO concept http://www.yso.fi/onto/yso/p18895 linked to nonexistent Allars concept http://www.yso.fi/onto/allars/Y27350
YSO concept http://www.yso.fi/onto/yso/p19469 linked to nonexistent Allars concept http://www.yso.fi/onto/allars/Y29496
YSO concept http://www.yso.fi/onto/yso/p8377 linked to nonexistent Allars concept http://www.yso.fi/onto/allars/Y17392
YSO concept http://www.yso.fi/onto/yso/p21756 linked to nonexistent Allars concept http://www.yso.fi/onto/allars/Y31936
YSO concept http://www.yso.fi/onto/yso/p16194 linked to nonexistent YSA concept http://www.yso.fi/onto/ysa/Y112093
YSO concept http://www.yso.fi/onto/yso/p27125 linked to nonexistent Allars concept http://www.yso.fi/onto/allars/Y45672
YSO concept http://www.yso.fi/onto/yso/p23232 linked to nonexistent Allars concept http://www.yso.fi/onto/allars/Y15607
YSO concept http://www.yso.fi/onto/yso/p1677 linked to nonexistent YSA concept http://www.yso.fi/onto/ysa/Y126730
YSO concept http://www.yso.fi/onto/yso/p11689 linked to nonexistent Allars concept http://www.yso.fi/onto/allars/Y34299
YSO concept http://www.yso.fi/onto/yso/p6221 linked to nonexistent Allars concept http://www.yso.fi/onto/allars/Y29144
YSO concept http://www.yso.fi/onto/yso/p9577 linked to nonexistent Allars concept http://www.yso.fi/onto/allars/Y30983
YSO concept http://www.yso.fi/onto/yso/p10939 linked to nonexistent YSA concept http://www.yso.fi/onto/ysa/Y136018
YSO concept http://www.yso.fi/onto/yso/p23326 linked to nonexistent Allars concept http://www.yso.fi/onto/allars/Y27350
YSO concept http://www.yso.fi/onto/yso/p8994 linked to nonexistent Allars concept http://www.yso.fi/onto/allars/Y30983
YSO concept http://www.yso.fi/onto/yso/p22959 linked to nonexistent Allars concept http://www.yso.fi/onto/allars/Y17392
YSO concept http://www.yso.fi/onto/yso/p17719 linked to nonexistent YSA concept http://www.yso.fi/onto/ysa/Y17422
YSO concept http://www.yso.fi/onto/yso/p9956 linked to nonexistent YSA concept http://www.yso.fi/onto/ysa/Y106554
YSO concept http://www.yso.fi/onto/yso/p1811 linked to nonexistent Allars concept http://www.yso.fi/onto/allars/Y18901
YSO concept http://www.yso.fi/onto/yso/p23337 linked to nonexistent Allars concept http://www.yso.fi/onto/allars/Y37230
YSO concept http://www.yso.fi/onto/yso/p16815 linked to nonexistent Allars concept http://www.yso.fi/onto/allars/Y36503
YSO concept http://www.yso.fi/onto/yso/p26200 linked to nonexistent Allars concept http://www.yso.fi/onto/allars/Y44505

**Comment by tpalonen** [comment]
Lista ei ole enää näin pitkä. Tein muutokset YASGUI-kyselyn avulla YSAn puolesta. Allärs pitäisi vielä tarkistaa.

**Comment by mariaforsen** [comment]
Tarkistettu.
