### ISSUE TITLE
YSAn ketjumuotoiset preflabelit YSOssa

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#465]
YSAsta periytyviä ketjumuotoisia preflabeleja löytyy YSOsta jonkin verran, esim. juuri YSAssa muokattu "Musiikkitalo -- Helsinki" tai esim. Pyhän Marian kirkko -- Hollola, Pyhän Marian kirkko -- Pietari, Pyhän Marian kirkko -- Pohja. Kiwistä löytyy tammikuussa tehty listaus tällaisista:

https://www.kiwi.fi/pages/viewpage.action?pageId=21762412

Mikä olikaan lopullinen ratkaisu tällaisten suhteen YSAn puolella?

Ehdotus: Etsitään tällaiset SPARQL-kyselyllä ja muutetaan YSOn puolella sulkutarkenteellisiksi muodoiksi.

**Comment by mirmaid** [comment]
YSO-kokous 18.4.2016:

Tuomas tekee listan näistä kun tähänastiset muuttuneet on käyty läpi.

**Comment by tpalonen** [comment]
Ongelmaa käsitellään toisessa issuessa: https://github.com/NatLibFi/Finto-data/issues/747
