### ISSUE TITLE
koiraat + urokset = hanar

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#466]
Ruotsiksi erilainen käsitemuodostus verrattuna suomenkieliseen. Voisiko suomeksi tyytyä siihen että kaikki urospuoliset eläimet niputettaisiin samaan käsitteeseen (vrt. esim. joet) esim. urokset alt label koiraat vai pitääkö ruotsiksi keksiä sulkutarkenteita - sitten pitää ensin tietää mikä on erotteleva tekijä, koko? Esim. hanar (stora djur), hanar (små djur) ?

**Comment by mariaforsen** [comment]
On nyt tässä listassa http://yasgui.laurensrietveld.nl/?contentTypeConstruct=text/turtle&contentTypeSelect=application/sparql-results%2Bxml&endpoint=http://api.dev.finto.fi/sparql&outputFormat=table&query=PREFIX+skos:+%3Chttp://www.w3.org/2004/02/skos/core%23%3E%0APREFIX+owl:+%3Chttp://www.w3.org/2002/07/owl%23%3E%0A%0ASELECT+%3Fs1+%3Fs2+%3Fl+{%0A++GRAPH+%3Chttp://www.yso.fi/onto/yso/%3E+{%0A++++%3Fs1+skos:prefLabel+%3Fl+.%0A++++%3Fs2+skos:prefLabel+%3Fl+.%0A++++FILTER+%28str%28%3Fs1%29+%3C+str%28%3Fs2%29+%26%26+LANG%28%3Fl%29+!%3D+%27en%27%29%0A++++FILTER+NOT+EXISTS+{%3Fs1+owl:deprecated+true}%0A++++FILTER+NOT+EXISTS+{%3Fs2+owl:deprecated+true}%0A++}%0A}%0AORDER+BY+LANG%28%3Fl%29+LCASE%28%3Fl%29&requestMethod=POST&tabTitle=Query%281%29

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 26.1.2015

Yhdistetään suomenkieliset. Preflabel: "koiraat", alLabel: "urokset"
