### ISSUE TITLE
Päiväkodit

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#468]
Allärs: päiväkodit = daghem + dagcentra

Viittaako päiväkodit-termi todella myös vanhuksille tarkoitettuihin  "päiväkoteihin"? Ei jotenkin kuulosta kovin asialliselta ja eikö nykyään kuitenkin päiväkoti yleensä tarkoittaa lasten päiväkodit? Jos hakee googlesta päiväkodit + vanhukset, seniorit, ikääntyneet jne. ei oikein tule sellaisia viittauksia että ihmiset käsittelisi päiväkoti-sanaa vanhuksille tarkoitettuna. Pitää vielä varmistaa tätä koska daghem ei ainakaan ruotsiksi ole vanhuksille tarkoitettu. Nyt on kuitenkin YSOssakin RT vanhustenhuoltolaitokset. Jos päiväkodit myös ovat vanhuksille niin missä mielessä ne ovat "päiväkoteja"? Vrt. päivätoiminta, päiväkeskukset... Yhteen ja samaan termiin ei ainakaan voi ruotsiksi laittaa sekä lasten että vanhusten asiat tässä kontekstissa.

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 26.1.2015

Käsite viittaa vain lasten päiväkoteihin. Mirja selvittää assoviittaukset ysassa. Lisätään käsitteelle ysoon huomautus: "Tarkoittaa lasten päivähoitolaitosta."
