### ISSUE TITLE
seksuaalinen hyväksikäyttö LT hyväksikäyttö

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#469]
Hierarkia hieman kyseenalainen:  toiminta > kulutus ja käyttö > käyttö > hyväksikäyttö > seksuaalinen hyväksikäyttö

Eikö tämä ole lähinnä sanaan hyväksikäyttö perustuva hierarkisointi, pitäisikö seksuaalinen hyväksikäyttö olla mieluummin väkivallan tai seksuaalirikosten alla, mihin sopisi temaattisesti paremmin?

Ks. myös MOT 

Ruotsiksi lisättiin sana sexuella övergrepp KT:ksi ja siitä tulee mieleen että kyllä se aina väkivalta on, eikä utnyttjande neutraalisempana sana oikein sovi yläkäsitteeksi.

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 26.1.2015

Uusi yläkäsite: seksuaalinen hyväksikäyttö LT seksuaalirikokset
