### ISSUE TITLE
WGS84-koordinaatit paikoille

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#47]
_From [osma.suominen@helsinki.fi](https://code.google.com/u/osma.suominen@helsinki.fi/) on January 14, 2014 17:45:06_

Nykyisessä Paikannimirekisterissä on vain alkuperäiset EPSG 3067 -koordinaatit. Ne eivät kuitenkaan ole kovin hyödyllisiä esim. Google Mapsin tai OSM:n kanssa. Kannattaisi lisätä mukaan myös WGS84-koordinaatit, mutta se edellyttää sopivaa koordinaattimuunnosohjelmaa, -algoritmia tai -rajapintaa.

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=44_

**Comment by osma** [comment]
Paikannimirekisterin julkaisu on MML:n vastuulla.
