### ISSUE TITLE
ihmeet + inkarnaatio, jälleensyntyminen, ylösnousemus

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#477]
Ks. http://finto.fi/yso/fi/page/p627

Eli hierarkia on spontaani tapahtuma > ihmeet > inkarnaatio, jälleensyntyminen, ylösnousemus.
Ihmeet on siten joutunut pois temaattisesta kontekstistaan ja vieruskäsitteinä ovat ihan toisenlaisia asioita. Ei myöskään täsmää spontaani tapahtuman määritelmän mukaan (tapahtuma, jota ei ole järjestetty tarkoituksellisesti, vrt. ihmeen määritelmä eli jumala tms. on nimenomaan järjestänyt sitä tarkoituksella). 

Parempi yläkäsite ihmeet-sanalle voisi olla selittämättömät ilmiöt (tai uskonnolliset ilmiöt) koska sitä nimenomaan ovat, eli tapahtuma jota ei voida luonnontieteellisesti selittää tai joka ylittää luonnontieteiden asettamia lakeja. Ks. esim. 	https://helda.helsinki.fi/handle/10138/21581 wikipedia jne. 

Alakäsitteet inkarnaatio, jälleensyntyminen ja ylösnousemus sopisivat paremmin uskonnolliset ilmiöt-käsitteen alle. Ne ovat uskonnollisia käsityksiä/uskomuksia, eivät ihmeitä ainakaan sanan uskonnollisessa merkityksessä (eli myös Melindan käytön mukainen merkitys). Ks. myös muut uskonnollisten ilmiöiden alakäsitteet, niiden kanssa sopii olla eikä ole mitään syytä pitää nämä ihan eri paikassa jossa on enemmän ihan luonnontieteellisiä ja yhteiskunnallisia asioita. 

Nämä muutokset lisäisivät myös temaattisuutta.

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 26.1.2015

Luodaan uusi käsite, "uskonnolliset tapahtumat", LT tapahtumat. Lisätään uudelle käsitteelle huomautus: "Uskonnollisten yhteisöjen järjestämistä tms. tapahtumista käytä "uskonnolliset tilaisuudet".

-> inkarnaatio, jälleensyntyminen, ylösnousemus LT uskonnolliset tapahtumat
