### ISSUE TITLE
leikkaus

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#478]
Monimerkityksinen ja niin on myös huomautus YSOssa. Ruotsin vastineen valinta riippuu merkityksestä. Allärsissa: leikkaus =beskärning+skärning+klippning.

Mot:
1. leikkaaminen. Nurmikon, kynsien, tukan leikkaus. Lasinleikkaus.
Erik.
a. lääk. kirurginen toimenpide, jossa esim. poistetaan sairas kudos t. korjataan tapaturman aiheuttamia vaurioita, operaatio. Umpilisäkkeen leikkaus. Silmä-, syöpäleikkaus. Keisarileikkaus. Kauneusleikkaus. Tehdä jklle leikkaus. Joutua leikkaukseen. Toipua leikkauksesta.
Kuv. Henkilökunnan vähentäminen oli kipeä leikkaus. Talouselämää tervehdyttävä leikkaus. Tulojen leikkaus.
b. filmi- t. magneettinauhan leikkaaminen pätkiksi ja niiden liittäminen kokonaisuudeksi, montaasi.
2. leikkaamisen tuloksesta.
a. puuhun tms. leikattu koriste t. kuvio. Puuleikkaus. Leikkauksin koristettu kaappi.
b. leikkaamalla aikaansaatu vaatekappaleen kuosi t. tukan malli. Kevään takeissa uusi leikkaus. Kampaajan tekemä muodikas leikkaus.
c. maaston kohta, josta tietä tm. varten on poistettu maata t. kalliota. Kallio-, maaleikkaus. Leikkauksessa kulkeva rautatie.
d. esineen (ajateltu, piirretty) halkaisu- t. katkaisupinta. Pitkittäis-, poikkileikkaus.
e. mat. Kultainen leikkaus ks. kultainen 1. 

leikkaus 
1 (kuosi; puvun tms) skärning [-en,-ar,-arna], tillskärning [-en,-ar,-arna], snitt [-et,=,-en]
Takissa on kaunis leikkaus/Takki on kauniisti leikattu Kappan har snygg skärning
2 (leikkaaminen) beskärning [-en,-ar,-arna]
3 lääk (leikkauksen tekeminen) operation [-en,-er,-erna]
4 geom sektion [-en,-er,-erna]
5 tekn snitt [-et,=,-en], skjuvning [-en,-ar,-arna]
leikkauspinta snittyta
6 tal (menojen vähentäminen) nedskärning [-en,-ar,-arna]
7 (elokuvan) klippning [-en,-ar,-arna]
Ohjaajan panos on tärkeä pitkän elokuvan leikkauksessa Regissörens insats är viktig i klippningen av en långfilm
8 (piirto) inskärning [-en,-ar,-arna]
9 (tieleikkaus) schakt [-en,-er,-erna]

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 26.1.2015

Mirja&Maria tutkii lisää.

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 4.12.2015:

Asiaa käsitellään tulevissa YSA-kokouksissa, palataan sitten asiaan

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/5257
