### ISSUE TITLE
nesteytys

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#479]
Näyttää siltä että molemmat nesteytys-käsitteet on vahingossa poistettu, tarkoitus oli varmaan purkaa jako ja pitää vain "nesteytys"? Huom. ei ole samaa kuin nestehoitoa, ks. esim TEPA, MOT... Temaattinen ryhmä onkin 30. Pitäisikö kondensaatio olla korvattuna? "Nesteytys eli kondensaatio, kaasun saattaminen nestemäiseen tilaan" / Facta

**Comment by mariaforsen** [comment]
Totesimme YSO-kokouksessa tänään että tämä on parempi antaa Tuomakselle hoidettavaksi.

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 4.12.2015:

@tpalonen onko asia kunnossa?

**Comment by tpalonen** [comment]
Kappas, vahinko sattunut koosteita työstäessä! Hyvä Maria kun huomasit! Nyt on korjattu. En laittanut kondensaatiota, koska YSAssakaan ei sitä ole korvattuna.
