### ISSUE TITLE
kuormalavat

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#480]
Ruotsink. vastine riippuu merkityksestä. Onko kyseessä  "tavaran kuljetuksessa ja varastoinnissa käytettävä määräkokoinen matala (puu)lava" vai kuormaauton kuormalavasta. Melindassa vaihtelevasti? Ruotsiksi joko lastpallar tai lastflak. Allärs: lastpallar + lastflak

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 26.1.2015

Jaetaan käsite. PrefLabelit edelleen harkinnassa... Ehkä:

1. kuormalavat (ajoneuvot)
2. kuormalavat (alustat)

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 4.12.2015

Hyväksytään sulkutarkenteet. Lisäksi käsitteelle "kuormalavat (alustat)" huomautus: "Tavaran kuljetuksessa ja varastoinnissa käytettävä määräkokoinen matala (puu)lava."

**Comment by MikkoAleksanteri** [comment]
Jaettu YSAssa tämän päätöksen mukaisesti, ei kuitenkaan lisätty päätettyä huomautusta? @mirmaid

**Comment by mariaforsen** [comment]
Tähän laitettu "Maria", mutta tätä ei voi ruotsiksi korjata ennen kuin käsite on jaettu myös YSOssa (nyt vain kuormalavat)

**Comment by mirmaid** [comment]
Huomautus lisätty.

**Comment by mirmaid** [comment]
Jaettu nyt myös YSOssa, toinen YSO-käsite ohjaa edelleen kahteen Allärs-vastineeseen?

**Comment by mariaforsen** [comment]
Ruotsiksi ok.
