### ISSUE TITLE
Barbarossa-suunnitelma

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#481]
Vieruskäsitteitä nyt:	
    liiketoimintasuunnitelmat
    opetussuunnitelmat
    pelastussuunnitelmat
    suojelusuunnitelmat
    taloussuunnitelmat
    tasa-arvosuunnitelmat
    toimintasuunnitelmat
    tuntisuunnitelmat
    ympäristösuunnitelmat

Oli enemmän kuin suunnitelma (hyökkäys). Olisiko temaattisesti parempi paikka hierarkiassa, esim. sotatoimet? Sen alakäsitteinä myös muita vastaavia. 
Pitäisi varmaan lisätä Operaatio Barbarossa korvatuksi, näin on jo YSAssa (miksihän ei YSOssa?)

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 26.1.2015

siirretään käsite LT sotatoimet. Mirja miettiin prefLabelin muttamista Operaatio Barbarossa :ksi.
