### ISSUE TITLE
YSAn maantieteellisten nimien edeltäjä-seuraajasuhde

### ISSUE THREAD

**Issue by livirtan** [NatLibFi/Finto-data#482]
YSAssa maantieteellisten nimien edeltäjä-seuraajasuhde ei näy oikein fintossa, ks. esim. benin-dahomey. Suhde näkyy vain toispuoleisena ja selitteenä on korvaava käsite, joka antaa asiasta väärän kuvan. Pohdittava myös, ovatko termit edeltäjä ja seuraaja hyviä selitteenä, muita mahdollisia esim: aiemmin - myöhemmin. Näitä suhteita ei ole YSAssa monia, mutta ehkä jatkossa enemmän.

**Comment by osma** [comment]
Tämä korjaantui jo kauan sitten uuden MARC-SKOS-muuntimen myötä.
