### ISSUE TITLE
Tanssit ja tanssimusiikki

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#484]
(tanssit) + (tanssimusiikki) tyyppiset koostekäsitteet (hieman varioivia sulkutarkenteita tässä).

```
cha-cha-chat
foxtrotit
humpat
jenkat
jivet
kansantanssit
masurkat
menuetit
polkat
poloneesit
polskat
purpurit
rumbat (latinalaistanssit)
sambat (latinalaistanssit)
tangot
valssit
```

Keskustelua: Mirja: Otan tämän esille MUSAn ylläpidon kanssa. Yksi sana musiikinlajille ja tanssille olisi käyttäjäystävällistä, mutta monikko on tässä ongelmallinen. Tuomas: Tähän jakoon on vaikuttanut YSAssa oleva monihierarkia. Käsitteet ovat LT tanssimusiikki + tanssit. Purpurit asiaa käsiteltiin käännösten osalta issuessa #432.

**Comment by tpalonen** [comment]
Kansantanssi vs kansantanssit ei oo koostekäsite.

**Comment by mirmaid** [comment]
Ne jotka jaettu musiikki vs. tanssi ovat edelleen monikossa myös tanssimusiikkina. Kuuluuko sellaiset todella olla monikossa (jos ylipäätään pidetään tämä jako)? Ruotsiksi ei ole luontevaa, mutta haluan varmistaa ennen kuin muutan mitään. Svenska ämnesord:issa on myös yksikössä. Nyt on YSOssa osa musiikista monikossa ja osa yksikössä, esim. salsa, humpat, blues, country, jivet jne.

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 18.1.16:

"Genret" eli tanssimusiikki-käsitteen alakäsitteet voitaisiin muuttaa yksikköön. Konsultoidaan kutenkin vielä MUSAn ylläpitoa.

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 21.10.2016:

-muutetaan "tanssimusiikki"-käsitteen alakäsitteiden termit yksikköön (sulkutarkenteet jätetään)

**Comment by tpalonen** [comment]
Tehty muutokset. Säilytin ohjausterminä sulkutarkenteettoman monikko muodon. Esim. "foxtrot (tanssimusiikki)"-käsitteellä ohjaustermit "foxtrotit".

**Comment by tpalonen** [comment]
@satuniininen ja @mariaforsen : tarkistattehan vielä nuo mahdolliset monikkomuodot ja niiden muuttamisen yksikköön ruotsin ja englannin osalta?

**Comment by satuniininen** [comment]
Englanti valmis.

**Comment by mariaforsen** [comment]
Ruotsin osalta ok.

**Comment by MikkoAleksanteri** [comment]
Hei,

asiasta tullut lisäpalautetta Luumu-ryhmältä. Avataan issue uudelleen.

**Comment by tpalonen** [comment]
Olemme saaneet palautetta tanssit ja tanssimusiikki käsitteiden alakäsitteistä, yksikkö/monikko-nimeämisen perusteista sekä hierarkisoinnin logiikasta. On pidetty ongelmallisena, että tanssit tuotoksina tulkitaan laskettavissa oleviksi (monikkomuotoisia), mutta tanssimusiikki ei (yksikkömuotoisia), vaikka nekin voitaisiin tulkita sävellyksiksi. Tälle likeinen ongelma on se, että osa YSOssa olevista eri tyylisistä tansseista on nyt tulkittu tanssiesityksiksi/tuotoksiksi (esim. foxtrotit, rumbat, tangot; löytyvät tanssit-käsitteen alta) ja osa genreiksi (esim. breakdance, jazztanssi, reggaeton; löytyvät tanssi-käsitteen alta).

Jaakko Tuohiniemi:
"vielä enemmän kuin menuetit tanssittuina ovat laskettavissa, ovat sellaisia menuettisävellykset. Jos musiikin osalta käytettäisiin yksikköä tanssisävellyksistä (”menuetti (tanssimusiikki)”), niin miksi ei muista sävellyksistä (”messut (musiikki)”, ”oratoriot”)?
Tämä tietysti johtaa perusteluissa mainittuihin yläkäsitteisiin: miksi tanssisävellysten LT-suhde yleensäkään johtaa musiikinlajiin (menuettien tapauksessa ”tanssimusiikki”-käsitteeseen), kun messuilla ja oratorioilla se on ”sävellykset” ja vastaavasti musiikinlaji vain assosiatiivisessa suhteessa (oratorioilla vielä lisäksi kummallisesti ”libretot”)?
Kaikkia sävellyksiä pitäisi käsitellä sanastossa samalla logiikalla, ja nykyinen LT-RT-jaottelu, jossa varsinainen kattotermi on vain RT-suhteessa on suorastaan virheellinen. Vrt LCSH:n ratkaisut, jotka ovat loogisia (kaikki menuettisävellykset ovat tanssimusiikia, kaikki (lauletut) messut ovat uskonnollista laulumusiikkia, kaikki oratoriot ovat uskonnollisia musiikkidraamoja).
Erittäin vakavissani pyydän harkitsemaan uudelleen YSOn nykyisiä tanssisävellysten kuvailuun tarkoitettujen termien muotoja ja ”sävellykset”-termin ST-suhteisten termien LT- ja RT-suhteita yleisemminkin."

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 23.1.2017:

Luumun ehdotus:

**polkka (tanssimusiikki) YK tanssimusiikki**-> **polkat (sävellykset) YK sävellykset**


**polkat (tanssit) YK tanssit** -> **polkka (tanssi) YK tanssi**

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 23.1.2017:

Onko **polkat (sävellykset) YK sävellykset** liiaan rajaava esimerkiksi tekstiaineiston kuvailussa? Jos esimerkiksi teos käsittelee polkkamusiikkia mutta ei tiettyjä sävellyksiä, uskaltaako kuvailija valita termiä.

Haasteena myös se, että ehdotetussa ratkaisussa tanssinäkökulmasta edustettuna on "genre", mutta musiikkinäkökulmasta yksittäiset sävellykset.

**Comment by jtuohini** [comment]
Mielestäni ei pitäisi olla ongelmaa. Nykyinen käsitejaottelu "musiikki" / "sävellykset" on tähän kaikkeen liittyvän sotkun taustalla, koska se tuottaa läpi sanaston ja ontologian johtavaan keinotekoiseen jakoon lajin / kyseisen lajin edustajiin, mutta jos siihen ollaan jo hirttäydytty, niin kyllä kuvailijan pitäisi kyetä erottamaan nämä kaksi asiaa toisistaan. 
"polkat (sävellykset)", pääryhmä 89
"polkka (tanssi)", pääryhmä 95
Teos ei voi käsitellä 'polkkamusiikkia', koska kyseinen musiikki on suunnilleen yhtä kuin polkkasävellykset. Jos tuota rupeaa enemmälti teoretisoimaan, ollaan pian tilanteessa, että "vasta" ja "vihta" ovat eri asiat tms. Selkeä ero tulee voida tehdä vain siltä osin, onko kyseessä musiikki (korvin aistittava sävelteosten joukko) vai tanssi (määriteltyjen liikesarjojen muodostama koreagrafinen kokonaisuus).

**Comment by jtuohini** [comment]
Vielä analoginen tarkennus, jos se vaikka selkiyttäisi: yksittäiset tanssit (sanaryhmä 95) pitäisi olla yksikössä samalla logiikassa kuin ovat urheilulajit, esim. "keihäänheitto, LT heittolajit, LT yleisurheilu": ei ole "keihäänheitot", kuten ei ole "valssit" (tanssina/tanssimisena, vaan vain sävelteoksena). Ja toinen, josta tulisi vielä hullumpi "jalkapallo, LT joukkuepelit, LT pelit" ynnä "jalkapallo, LT palloilu": siis ei "jalkapallot" lajista.

**Comment by tpalonen** [comment]
YSO-kokous 8.2.:

Käsitellään Luumun ehdotus seuraavassa YSA-kokouksessa.

**Comment by jtuohini** [comment]
Kyllä, Luumu rupesi jakamaan noita. Se selkiyttää ennestään tuota yksikkö/monikko-jakoa siihen suuntaan, kummat ovat laskettavissa, (tanssi)sävellykset vai yksittäisten tanssi(laji)en askellus. Toivottavasti tulee hyvä kokous!

**Comment by jtuohini** [comment]
Vielä täsmennys Tuomaksen eiliseen kommenttiin: "kun taas "cha cha chat (sävellykset)", "valssit (sävellykset)" ynnä muut musiikkigenrejä edustavat käsitteet menisivät ehdotuksen mukaan sävellykset-hierarkiaan." Valssit ei ole genre (musiikinlaji) vaan sävellysmuoto. Rock on musiikinlaji, jazz on musiikinlaji, kansanmusiikki on musiikinlaji, taidemusiikki on musiikinlaji; menuetit on sävellysmuodon edustaja (ja voi lajiltaan olla esimerkiksi taidemusiikkia tai kansanmusiikkia), valssit samoin jne. En enää keksi, mistä tämä voi kiikastaa. "Valssit", "menuetit", "sinfoniat", "kantaatit" jne. ovat kaikki sävellysmuotojen edustajia, laskettavissa olevia sävellyksiä. Valssi on tanssi (koreagrafinen), keihäänheitto eräänlainen koreografinen suoritus sekin. Jos yllä olevat kommentit eivät valaise, niin mikä sitten?

**Comment by tpalonen** [comment]
Kiitos kommentista! Mihin perustuu väittämä, että valssi ei ole genre vaan sävellysmuoto? Esim. The New Grove Dictionary of Music & Musicians puhuu valssista genrenä, "this article is devoted to the consideration of the genre's history". Ymmärrän kyllä, että valssiin klassisessa musiikissa liitetään yleensä erilaisia rakenteellisia erityispiirteitä, esim. Suuri musiikkitietosanakirja: "sille on ominaista 'viisi-v'-rakenne; johdanto, viisi taitetta, joita erottavat välikkeet, ja coda." Mutta tämä rakenneajattelu ei kuitenkaan ole olennainen populaarimusiikin puolella, (vrt. "Kulkurin valssi").

Onko Luumun näkökulmasta myös cha cha cha sävellysmuoto? Entä foxtrot, jenkka, jive? Esim. cha cha cha määritellään Wikipediassa seuraavasti: "Cha-cha-chá is a genre of Cuban music." Itse en näe mitään perusteita pitää näitä käsitteitä sävellysmuotona.

Toistan: on epäjohdonmukaista ja käyttäjän kannalta hankalaa, että tietyt genre-tyyppiset käsitteet määritellään sävellysmuodoksi ja toiset genreiksi, jolloin ne päätyvät eri hierarkioihin ontologiassa. Yksinkertaisempaa on tulkita kaikki genreiksi ja hierarkisoida sen mukaan.

Ylipäätään sävellysmuodon ja genren ero on (ainakin itselleni) hämärä, joten määritelmät auttaisivat. Onko kyse lopulta vain siitä, että klassisen musiikin puolella ollaan ilmeisesti miellytty enemmän sävellysmuoto-termiin, pop-puolella taas genreen? Encyclopaedia Britannicassa ja Wikipediassa puhutaan sinfoniastakin genrenä.

Olisi varmaankin hyvä listata kaikki YSOn tämän tyyppiset käsitteet ja miettiä, voidaanko ne ratkaista jotenkin konsistentisti.

**Comment by TommiViitamies** [comment]
Tämä on kieltämättä vaikeasti hahmotettava kokonaisuus. MUSAssa on tosiaan tehty ero genrejen ja "sävellysmuotojen" (=tanssisävellysten) välillä yksikkö-monikko-vaihtelulla. Tämä ei välttämättä aina ole ollut "konsistenttia", mutta siihen on pyritty. Kannatan ehdotusta, että tanssilajit yksikössä ja sävellykset monikossa.

**Comment by jtuohini** [comment]
Ihan lyhyt analogia vielä: "valssit", "menuetit" sävellyksinä ovat itsenäisiä taideteoksia vastaavalla tavalla kuin "muotokuvat" kuvataiteen puolella, "romaanit" ja "runot" kaunokirjallisuuden puolella jne. Valssit voivat olla taidemusiikki tai populaarimusiikkia, muotokuvat valokuvaamalla tai maalaamassa tai kuvanveiston keinoin tehtyinä, romaanit yhtä lailla chick litiä kuin sotakirjallisuutta. Tämä on ydin: teokset vastaan tyylilaji. Ja siksi monikossa, koska teokset ovat aina monikossa. Tanssilaji "menuetti" taas ei ole teos sen enempää kuin "keihäänheitto" urheilulajina, ja siksi ne ovat yksikössä.
 
Toki kirjallisuudessa puhutaan sinfonioista genrenä, mutta kyllä sisällönkuvailussa viitataan teoksiin, jotka sitten muodostavat sen genreksi nimettävän teosjoukon kaikkine yhteisine ja erottavine piirteineen. Mutta ytimessä on joka tapauksessa laskettavissa olevat sävellykset, siis teokset. Jos musiikissa teoksen tulkitaan lajityypiksi (ilman sen edustajia?), niin miksei samalla tavoin toimittaisi muiden taiteenlajien puolella?

**Comment by mirmaid** [comment]
LCSH:

Foxtrot (Dance) BT Dance
Foxtrots BT Dance music
Foxtrots (Music) = 155 genre, BT Dance music

YSA-kokousta parempi foorumi voisi kuitenkin olla MUSA-YSA-palaveri, koska YSA-kokouksissa aikaa on vähän. Jos haluamme muuttaa YSAa vastaamaan paremmin tätä ehdotettua jaottelua, jäisivät nykyiset monikolliset termit musiikki-hierarkiaan tai siirtyisivät teos-hierarkiaan (LCSH:ssa kuitenkin valittu music, ei compositions). Tansseja varten pitäisi muodostaa uudet yksikkömuotoiset termit (YSOssa on jo, mutta monikossa), joiden yläkäsite olisi _tanssi_ tai _tanssit_? (LCSH:ssa ei ole monikollista Dances-termiä.)

Olisi hyvä myös samalla miettiä miten nämä suhteutuvat vastaaviin genre-sanaston termeihin ja mikä on paras sulkutarkenne silloin kun kyse on genrestä kentässä 155 ja silloin kun kyse on aiheesta kentässä 150.

**Comment by TommiViitamies** [comment]
Kannatan sitä, että tästä kokonaisuudesta puhutaan vielä YSA-kokouksen ulkopuolella, esimerkiksi erillisessä MUSA-YSA-palaverissa.

**Comment by MUUSA-kokous** [comment]
Pitäydytään Luumun päätöksessä:

Luumun ehdotus:

polkka (tanssimusiikki) YK tanssimusiikki-> polkat (sävellykset) YK sävellykset

polkat (tanssit) YK tanssit -> polkka (tanssi) YK tanssi

VRT. LCSH

Polka (Dance) YK Dance
Here are entered works on the polka as a dance. Musical compositions are entered under the heading |a Polkas.

Polkas YK Dance music
Here are entered musical compositions. Works on the polka as a dance are entered under the heading |a Polka (Dance).
This heading is not qualified by medium of performance. For polkas for a specific medium, an additional heading is assigned for the medium of performance.

**Comment by mirmaid** [comment]
Nyt siis polkka (tanssit) YK tanssilajit. Tämä ok?

**Comment by jtuohini** [comment]
Nimenomaan noin!
