### ISSUE TITLE
Henkilöhistoria-käsitteen merkitys ja käännökset

### ISSUE THREAD

**Issue by MikkoAleksanteri** [NatLibFi/Finto-data#486]
YSOn käsite henkilöhistoria, http://www.yso.fi/onto/yso/p2718

tapahtumat ja toiminta > ilmiöt > yhteiskunnalliset ilmiöt > erikoisala > tieteet (erikoisala) > historia > henkilöhistoria 

viittaa historiantutkimuksen osa-alueeseen. Sama kuin KTSn merkitys: "jkn merkkihenkilön t. -henkilöiden historia".

Ongelmat:
1. Englanninkielinen käännös "personal history" ei historiantutkimuksen osa-alueen nimitys, parempi olisi esim "biographical history" tms.
2. YSAssa huomautus, "Käytetään asiasanana silloin, kun julkaisu sisältää katkelmia henkilön elämästä. Voidaan käyttää myös tarkoittamassa historiantutkimuksen osa-aluetta."
   Huomautuksesta johtuen fennicassa 5383 hittiä, melindassa 25 598. YSA-YSO konversion yhteydessä ei siis voida säilyttää vain nykyisen YSOn tieteenalamerkitystä.

**Comment by satuniininen** [comment]
Käännös ok
