### ISSUE TITLE
Arvoon liittyvä rooli alakäsitteineen

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#488]
TAUSTAA: To make the long story short, koostekäsitteiden läpikäynnin jäljiltä roolihierarkiassa on "arvoon liittyvä rooli" alla kategorisoivia käsitteitä, jotka eivät oikeastaan ehkä kuulu roolihierarkiaan vaikka niiden alakäsitteet kuuluvatkin. Oppiarvot-käsitteen jo siirsimme sieltä pois "yhteiskunnalliset tuotokset"-käsitteen alle ja sen alakäsitteet (mm. agronomit, maisterit, medianomit jne) "tutkinnon suorittaneet"-käsitteen alle. Ks. #429. Ehdotan, että samantapainen muutos tehtäisiin muillekin tässä hierarkiassa oleville.

aatelisarvot [alakäsitteinä: herttuat, kreivit jne]
arvonimet [alakäsitteinä: elokuvaneuvokset, herastuomarit jne]
sotilasarvot [ei alakäsitteitä]
virka-arvot [ei alakäsitteitä]

EHDOTUS: Eli ehdotan, että yllämainitut neljä käsitettä siirretään "yhteiskunnalliset tuotokset"-käsitteen alle kuten oppiarvot-käsitekin. Kuitenkin näiden alakäsitteet (herttuat, elokuvaneuvokset jne) pitäisi säilyttää roolihierarkiassa. Olisiko näille hyvä luoda uudet yläkäsitteet: aatelisarvoon liittyvät roolit tms?

**Comment by mirmaid** [comment]
YSO-kokous 18.4.2016

Tehdään Tuomaksen ehdottama muutos ja siirretään alakäsitteet suoraan käsitteen "arvoon liittyvä rooli" alle. Lisätään RT-suhde entiseen yläkäsitteeseen.
