### ISSUE TITLE
liput RT pääsyliput

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#489]
Pääasiallinen ongelma ratkaistu https://github.com/NatLibFi/Finto-data/issues/73, mutta ei kai RT pidä olla pääsyliput, eli pitäisikö se suhde poistaa?

**Comment by MikkoAleksanteri** [comment]
Tulee YSAsta, eli pitänee korjata siellä päässä?

**Comment by mirmaid** [comment]
Poistettu RT-suhde YSAsta.
