### ISSUE TITLE
Purettujen koostekäsitteiden oldlabelit

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#494]
Esim. komediat. Onko syytä jättää oldlabeliksi sulkutarkenteelliset muodot, vai riittääkö deprecated-relation -suhde?

**Comment by mariaforsen** [comment]
Ongelmana on nyt että joidenkin termien kohdalla voi käyttäjälle helposti tulla harhakäsitys termin merkityksestä, jos siis jätetään toinen termi old-labelina mutta toinen poistuu kokonaan. Tämä koskee varsinkin niitä tapauksia, joissa asiasanan merkitys voi olla ennestäänkin hieman epäselvä. Esimerkkitapaus komediat ei ole sitä, mutta jo sekin voi pistää käyttäjää mietteliääksi ("saako komediat käyttää elokuviin kun korvattuna on vain komediat (näytelmät)"?) jos ei ole perehtynyt meidän periaatteisiin tehdä tätä.

**Comment by tpalonen** [comment]
Joo, tästä on viime aikoina keskusteltu käytävillä paljon. Olen siirtänyt sulkutarkenteellisia oldlabeleiksi, koska niin alun perin päätettiin. Myös deprecated-replaced-by-suhteesta on nyt ollut keskustelua. Onko oikein, että "radat (liikeradat)"-käsitteestä on replaced-by-suhde käsitteeseen "radat", joka tarkoittaa nykyään liikuntaratoja?

**Comment by tpalonen** [comment]
RATKAISUEHDOTUS: 
a) siirretään hiddenlabeleiksi kaikki vanhat koostekäsite-oldlabelit, joissa on (vanhentunut tai minkälainen tahansa) sulkutarkenne. Tällaiset saa varmaankin korjattua takautuvasti SPARQL-kyselyllä.
b) deprecated-replaced-by-suhteet kerätään yhteen SPARL-kyselyllä ja käydään käsin läpi pienemmällä porukalla - tai ainakin päätetään pienemmällä porukalla läpikäynnin ja ratkaisujen periaatteista ja joku käy ne sitten läpi.

**Comment by mariaforsen** [comment]
Ainoa mahdollinen ongelma joka tulee mieleen ratkaisuehdotuksesta a on että joitakin sulkutarkenteellisia muotoja haluttaisiin ehkä nimenomaan näyttää käyttäjille? On kai niitä tapauksia joissa on laitettu sulkutarkenteellinen muoto KT:ksi koska halutaan ohjata käyttöä tietyllä tavalla. Hyviä esimerkkejä ei tule mieleen, mutta niitä on ollut, esim. kooste-kokouksissa on välillä päätetty laittaa sellaisia korvattuja (ks. esim. valistus-ehdotus).

**Comment by mirmaid** [comment]
Pitäisi kyllä valita mitkä merkitään hidden-labeleiksi, koska osa on tarpeellista näkyä - toisaalta viikkopalaverissa taisi käydä ilmi että hidden-labelitkin näkyvät autocompletessa eli sillä ei voida ratkaista tätä ongelmaa. Minusta parasta olisi poistaa viittauskentistä harhaanjohtavat.

**Comment by henriyli** [comment]
Kysymys:
Jos järjestelmän tietueessa on käytetty deprikoitua käsitettä, löytyykö kyseinen tietue edelleen, kun käsite on haudattu Fintossa

**Comment by tpalonen** [comment]
Ks. myös issue #707

**Comment by tpalonen** [comment]
Harhaanjohtavista oldlabeleistä päätettiin 1.3.2016 viikkopalaverissa seuraavaa: tehdään syntaktinen developmentComment muotoa "jaettuja käsitteitä yhdistettäessä poistettu label: anime (elokuvat)". Eli siirretään label developmentcommenttiin.

LISÄKYSYMYS: Lisätäänkö developmentcommenttiin myös deprekoidun koostekäsitteen label. Tässä lista deprekoiduista käsitteistä ja seuraajistaan. Lisättävää olisi paljon. Ei ainakaan kannata tehdä käsin.

https://docs.google.com/spreadsheets/d/1wB2Yc8RKQ5wharyUQ8wH1624Y3dFgMXqKj0fCd0nBBM/edit#gid=1975078764

**Comment by tpalonen** [comment]
Kävin läpi kaikki Mirjan avustamana ja poistin suurimman osan sulkutarkenteellisista labeleista, jotka siirtsin development commenttiin varustettuna fraasilla "Käsite on aiemmin ollut jaettu. Jaetun käsitteen preflabel oli "xx".
