### ISSUE TITLE
tapahtumat-kategoria 

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#496]
Ks. "tapahtumat" : http://finto.fi/yso/fi/page/p2108

Eli näyttää nyt olevan jaoteltu usealla eri periaatteella ja alakäsitteitä on eri tasoilla. 

Olisiko mahdollista jaotella temaattisesti esim.:

luonnontieteelliset tapahtumat 

   ST biologiset tapahtumat
   alakäsitteinä voisi mahdollisesti olla mm. näitä jotka nyt ovat suoraan tapahtumien alla:
   syntymä

   ST fysikaaliset tapahtumat 
   alakäsitteinä voisi mahdollisesti olla mm. näitä jotka nyt ovat suoraan tapahtumien alla:
   räjähdykset
   törmäys?

yhteiskunnalliset tapahtumat (entä "kulttuuriset tapahtumat", voisi myös jakaa vielä pienempiin ryhmiin)
   alakäsitteinä voisi mahdollisesti olla mm. näitä jotka nyt ovat suoraan tapahtumien alla: 
   alueloukkaukset
   hätätilanteet
   ihmisoikeusloukkaukset
   järjestetyt tapahtumat (kaikki alakäsitteet näyttää olevan yhteiskunnallisia, kulttuurisia, uskonnollisia, historiallisia (sodat..)  tms. )
   konfliktit
   mellakat
   prosessit
   provokaatiot 
   riidat
   rikkomukset
   skandaalit
   tappelut
   vaaratilanteet
   virhetilanteet

taloudelliset tapahtumat (näihin voisi kuulua myös osa kaupankäyntiin liittyvistä..)

Vaihtoehto jossa tapahtumat ST 
biologiset
fysikaaliset/fyysiset
tekniset
yhteiskunnalliset 
kulttuuriset 
taloudelliset 
uskonnolliset
kielelliset
mentaaliset ...? 

Entä "historialliset tapahtumat" sellaisista jotka tapahtuvat vain kerran, esim. sodat? Vai pidetäänkö kiinni väkivaltaiset-jaottelusta? 

spontaani tapahtuma poistettaisiin? alakäsitteet:
    alkuräjähdys fysikaaliset tapahtumat?
    ihmeet uskonnolliset tapahtumat?
    kriisit yhteiskunnalliset tapahtumat?
    maailmanloppu yhteiskunnalliset tapahtumat? ks. ryhmä 53 uskonnolliset?
    onnettomuudet yhteiskunnalliset tapahtumat?
    ruuhkat yhteiskunnalliset tapahtumat?
    sattuma ? ks. ryhmä 02 
    tapaturmat yhteiskunnalliset tapahtumat
    tulivuorenpurkaukset fysikaaliset tapahtumat 

Uusia tapahtumia myös "ilmiöt"-käsittelyn seurauksena? Miten nämä vaikuttavat, tuleeko olemaan paljon enemmän "tapahtumia"? Moni toiminta tai ilmiö voisi ehkä periaatteessa yhtä hyvin nähdä jonkinlaisena tapahtumana...

**Comment by mariaforsen** [comment]
Huom. myös yhteiskunnalliset tapahtumat ST:
kaupankäyntiin liittyvät tapahtumat  
oikeudelliset tapahtumat
opiskeluun liittyvät tapahtumat
väkivaltaiset tapahtumat 

Pitäisikö nämä tai osa näistä poistaa, ks. esim . ensimmäisen ST:t ? Ellei haluta tehdä tällaisia spesifimpiä lisää..

**Comment by mirmaid** [comment]
YSO-kokous 18.4.2016

Tuomas tekee taulukon tapahtumista. Jatketaan käsittelyä seuraavassa kokouksessa Marian ehdotuksen pohjalta.

**Comment by tpalonen** [comment]
Taulukko löytyy täältä:
https://docs.google.com/spreadsheets/d/1XuBIkSjcBXUWBLBusLwbSGmYnyap-wOfKAieCU3cqfY/edit#gid=1938738597

**Comment by tpalonen** [comment]
EHDOTETTU JAOTTELU:
biologiset
fysikaaliset/fyysiset
tekniset
yhteiskunnalliset
kulttuuriset
taloudelliset
uskonnolliset
kielelliset
mentaaliset ...? 

Vrt. ominaisuuksien jako:
biologiset
fyysiset
fysikaaliset
kielelliset
mentaaliset
yhteiskunnalliset
. . kulttuuriset
. . keskinäiseen toimintaan ja suhteisiin liittyvät
. . . . sukulaisuuteen liittyvät
. . oikeudelliset

**Comment by tpalonen** [comment]
Keskustelussa mainittu taulukko on nyt käyty kokonaisuudessaan läpi, tapahtuma-hierarkiaa koskevat päätökset on merkitty taulukkoon ja päätökset on toteutettu YSOon. Yksittäiset päätökset löytyvät siis kyseisestä taulukosta:

https://docs.google.com/spreadsheets/d/1XuBIkSjcBXUWBLBusLwbSGmYnyap-wOfKAieCU3cqfY/edit#gid=1938738597

Edellä esitetty hierarkiaehdotus ei ole enää voimassa. Tapahtumat-hierarkiasta muodostui lopulta seuraavanlainen:

**Comment by tpalonen** [comment]
PÄÄTÖS 23.2.2017

Aiempien päätösten lisäksi tehtiin vielä seuraavaa:
- taloudelliset tapahtumat YK yhteiskunnalliset tapahtumat
- keskinäiseen toimintaan liittyvät tapahtumat YK yhteiskunnalliset tapahtumat
