### ISSUE TITLE
Entropia

### ISSUE THREAD

**Issue by MikkoAleksanteri** [NatLibFi/Finto-data#497]
http://www.yso.fi/onto/yso/p5009 

YSOssa ryhmät 
60 Sosiologia. Sosiaalipsykologia ja 
07 Fysiikka  
huomautus: "eräs termodynamiikan ja informaatioteorian perussuure, haje"
LT "fysikaaliset ilmiöt"

Ainakin kaksi merkitystä, fysikaalinen sekä "humanistinen": http://fi.wikipedia.org/wiki/Entropia Molempia kuvailluissa teoksissa.

-> käsite tulisi varmaan jakaa?

**Comment by mirmaid** [comment]
Muutosehdotus YSEssä https://github.com/Finto-ehdotus/YSE/issues/4793
