### ISSUE TITLE
Assosiatiivisia ja alakäsitesuhteita poistettuihin käsitteisiin

### ISSUE THREAD

**Issue by MikkoAleksanteri** [NatLibFi/Finto-data#503]
Ks esim

http://dev.finto.fi/yso/fi/page/p26434

käsitteellä assosuhde käsitteeseen "viralliset kielenkääntäjät" http://www.yso.fi/onto/yso/p20963, joka on deprekoitu käsite.

Näitä ei saisi olla näkyvissä.

**Comment by MikkoAleksanteri** [comment]
@frosterus Onko tämä jo korjattu? Jos on niin issuen voinee sulkea.

**Comment by frosterus** [comment]
Korjattu. Vika saattoi olla muuttuneissa property-nimissä tai sitten assosuhteiden massa-ajossa - ei näyttäisi voivan toistua tulevaisuudessa.

**Comment by MikkoAleksanteri** [comment]
Avattu uudelleen, poistettuja vielä ainakin alakäsitteinä, ks. esim. "floristit": http://finto.fi/yso/fi/page/p1153

**Comment by tpalonen** [comment]
Ei toimi vieläkään automatik. Ks. esim. päättely, jonka alakäsite "abduktio -- filosofia" poistettiin juuri, mutta abduktio näkyy edelleen hierarkiassa.

**Comment by tpalonen** [comment]
Ainakaan päättely-käsitteellä ei nyt näy deprekoituja suhteita Fintossa. Suljen issuen. Avataan, jos vastaavia vielä löytyy Fintosta.
