### ISSUE TITLE
Käsitteet

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#505]
YSOssa useita alakäsitteitä (YSAssa vain lukukäsite ja yleiskäsitteet). Kaikki YSOn käsitteet voisivat olla tämän alakäsitteitä, joten nykyisten paikka on mietittävä uudestaan.

**Comment by mariaforsen** [comment]
ALAKÄSITTEET

    elämismaailma YK teoriat, abstraktit objektit?
    elämän tarkoitus YK abstraktit objektit (siinä myös esim. päämäärät, tavoitteet) tai mentaaliset objektit
    henki (filosofia) abstraktit objektit?
    hyvä elämä  YK elämä
    hyvä abstraktit objektit (vai olisiko poistettavissa, sanastossa myös hyvyys ja sehän on ominaisuuksien alla)
    ikuisuus
    itse
    jin ja jang
    järki
    kohtalo
    lukukäsite
    maailma
    mahdollisuus
    matemaattiset käsitteet
    merkitys (tärkeys)
    mind and body
    minä
    oikeutus
    olemus (filosofia)
    oleva
    oliot (filosofia)
    onni
    paha
    paradoksit
    persoona
    profaani
    pyhä (uskonnolliset käsitteet)
    qi
    sattuma
    sofismi
    subjekti (filosofia)
    substanssi
    substraatti (filosofia)
    tahdonvapaus
    totuus
    viisi elementtiä
    vääryys
    wabi-sabi
    yleiskäsitteet
    ylevä

**Comment by mirmaid** [comment]
elämismaailma YK yhteiskunnalliset objektit
elämän tarkoitus YK abstraktit objektit
henki (filosofia) YK abstraktit objektit
hyvä elämä YK elämä
hyvä YK yhteiskunnalliset objektit
ikuisuus YK abstraktit objektit
itse YK mentaaliset objektit
jin ja jang YK uskontoon liittyvät abstraktit objektit
järki YK mentaaliset objektit
kohtalo YK uskontoon liittyvät abstraktit objektit
lukukäsite YK käsitteet RT matemaattiset taidot

maailma YK fyysiset kokonaisuudet, mahd. paikka?

mahdollisuus YK ominaisuudet

matemaattiset käsitteet YK käsitteet

merkitys (tärkeys) YK minaisuudet/mentaaliset ominaisuudet

mind and body YK teoriat

minä YK mentaaliset objektit

oikeutus YK yhteiskunnalliset ominaisuudet?

olemus (filosofia) YK ominaisuudet (olemus:tarkoittaa metafysiikassa sitä ominaisuutta tai ominaisuusjoukkoa, joka tekee jostakin oliosta tai substanssista sen, mitä se pohjimmiltaan on)

oleva YK ilmiöt

oliot (filosofia) YK oliot? ongelmallinen, sanastossa nyt sekä oliot että oliot (filosofia), ensimmäinen on toki hierarkisoiva, mutta kai tarkenne olisi tarpeen jos molemmat pidetään?

onni YK mentaaliset ominaisuudet?

paha YK abstraktit objektit? sanastossa myös pahuus joka on ominaisuuksien alla

paradoksit YK ristiriidat tai ominaisuudet

persoona YK ominaisuudet? (myös esim. toimijat ovat ominaisuushierarkiassa)

profaani YK uskontoon liittyvät ominaisuudet?

pyhä (uskonnolliset käsitteet) YK uskontoon liittyvät abstraktit objektit (sanastossa myös pyhyys joka on ominaisuuksien alla)

qi YK uskontoon liittyvät abstraktit objektit (siinä myös esim. karma)

sattuma YK ilmiöt, ominaisuudet tai tapahtumat ja toiminta?

sofismi YK virhepäätelmät? ominaisuudet?

subjekti (filosofia) YK mentaaliset objektit?

substanssi YK abstraktit objektit?

substraatti (filosofia) YK abstraktit objektit?

tahdonvapaus YK mentaaliset ominaisuudet?

totuus YK ominaisuudet?

viisi elementtiä YK uskontoon liittyvät abstraktit objektit (ks. vastaavat yllä)

vääryys YK mentaaliset ominaisuudet

wabi-sabi YK ominaisuudet?

yleiskäsitteet YK käsitteet

ylevä YK ominaisuudet?

**Comment by mirmaid** [comment]
Matemaattiset käsitteet -ratkaistava myös.

**Comment by mirmaid** [comment]
Sovitaan palaveri lopuille v. 2022 alkuun.

**Comment by mirmaid** [comment]
Matemaattiset käsitteet:
asymptootti
determinantit
graafit
itseisarvo (matematiikka)
jatkumo
joukot (matematiikka)
keskiarvot
koordinaatit
likiarvot
lukujonot
matriisit
mediaanit
mittakaava
modulit (matematiikka)
muuttujat
ominaisarvot
parametrit
raja-arvo (matematiikka)
topologiset avaruudet
vakiot
vektorit (matematiikka)
ääriarvot

**Comment by mirmaid** [comment]
Yksi vaihtoehto voisi olla muuttaa matemaattiset käsitteet muotoon matemaattiset objektit (YK abstraktit objektit tai yhteiskunnalliset objektit), jos ei ole jotenkin ristiriidassa tämän kanssa https://en.wikipedia.org/wiki/Mathematical_object.

**Comment by mirmaid** [comment]
Muutetaan > matemaattiset objektit. Mirja käy alakäsitteet läpi + matemaattiset menetelmät. Listataan ongelmatapaukset tähän tai käsitellään slackissä.

**Comment by mirmaid** [comment]
**OK:**
joukot
vektorit (matematiikka)
topologiset avaruudet
matriisit
vakiot
modulit (matematiikka)
asymptootti
determinantit
lukujonot
koordinaatit

**Ongelmat:**
muuttujat: https://en.wikipedia.org/wiki/Variable_(mathematics). Vakiot olisi kuitenkin ok, joten käykö tämäkin?
mittakaava /ei > kaavat (tieteet ja tekniikka)?
jatkumo /ei, myös 00
parametrit (?)

**Arvo(t):**
itseisarvo, https://en.wikipedia.org/wiki/Value_(mathematics)
keskiarvot
likiarvot
mediaanit
ominaisarvot
raja-arvo (matematiikka)
ääriarvot

**Comment by mirmaid** [comment]
Matemaattisista menetelmistä siirretään:
funktiot
hyperbelit
paraabelit
polynomit
logaritmit
potenssit
yhtälöt
epäyhtälöt

**Comment by mirmaid** [comment]
jatkumo: tehdään issue
mittakaava YK kaavat (tieteet ja tekniikka)
parametrit YK yhteiskunnalliset objektit (?)

itseisarvo, https://en.wikipedia.org/wiki/Value_(mathematics)
keskiarvot
likiarvot
mediaanit
ominaisarvot
raja-arvo (matematiikka)
ääriarvot

Mirja tutkii vielä arvot-joukon ja parametrit, palataan tähänkin tammikuun työpajapäivässä.

**Comment by mirmaid** [comment]
Edellä mainittujen lisäksi matemaattiset objektit -käsitteen yläkäsite?

**Comment by mariaforsen** [comment]
Alakäsitteenä on vielä "lukukäsite", jos tämä on tällainen merkitykseltään "[Lukukäsite](http://docplayer.fi/19664384-Matemaattisen-ajattelun-kehittyminen-lukukasitteen-synty.html) on intuitiivinen ymmärrys siitä miten luvut muodostuvat ja miten niitä voidaan manipuloida matemaattisten operaatioiden kautta. Miten luvut toimivat, mitä ne edustavat ja mitä kaikkea niillä voi tehdä."

**Comment by mirmaid** [comment]
Matemaattiset objektit YK abstraktit objektit

**Comment by ilona-x** [comment]
Vähän ohi aiheen, mutta kirjaan nyt tähän, kun huomasin, että lukukäsite on linkattu Wikidatan käsitteeseen luku http://www.wikidata.org/entity/Q11563. Tuohon Wikidata-käsitteeseen on näköjään Jarmo lisännyt v. 2021 vaihtoehtoisiksi muodoiksi lukukäsite / talbegrepp / number concept, mutta noista on enkkutermi sittemmin poistettu. Oikeampi linkkaus olisi YSOssa luvut http://www.yso.fi/onto/yso/p1568 ja nuo vaihtoehtoiset termimuodot varmaan pitäisi poistaa Wikidatasta.

**Comment by ilona-x** [comment]
Yritin tutkia lukukäsite-termiä, mutta tämän merkitys ja kielivastineet eivät ihan täysin selvinneet.

Esimerkiksi tässä väitöskirjassa http://urn.fi/URN:ISBN:952-10-3007-0 käytetään lukukäsitteen vastineena "number sense". 🤔 
YSO:n lukukäsite on linkattu LCSH-termiin [Number concept](http://id.loc.gov/authorities/subjects/sh85093206 ), jolla on alakäsitteenä signed numbers 

Ja myös suomenkielinen termi lukukäsite ilmeisesti voi viitata muuhunkin kuin tuohon ymmärrykseen, kun googlatessa tuli vastaan tämä graudu: Lukukäsitteen historia  https://urn.fi/URN:NBN:fi:tuni-202306307010 

Melindassa lukukäsite-termiä on kuitenkin käytetty vain tuossa ymmärrys-merkityksessä. 

Lukukäsitteen yläkäsitteeksi voisi sopia kognitio, mutta sille ei taideta tässä vaiheessa haluta uusia alakäsitteitä. 😄 Voisiko yläkäsite mahdollisesti olla kognitiiviset prosessit tai sen alakäsite ymmärtäminen?

**Comment by mirmaid** [comment]
Matemaattisesta arvosta: https://kansalliskirjasto.slack.com/archives/CB3FTAFK7/p1712570902506529

**Comment by mariaforsen** [comment]
Kannatan lukukäsite YK matemaattiset taidot

**Comment by mirmaid** [comment]
^ Lisätään sille KT lukukäsitetaidot.
