### ISSUE TITLE
Koostekäsite: ohjaus

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#513]
Yhdistetään ohjaus (neuvonta) ja ohjaus (opastaminen). Siirretään ohjaus (opastaminen) -käsitteen alakäsitteet käsitteen ohjaus (suunnan säätely) alle. Jatketaan käsittelyä tämän jälkeen.

**Comment by tpalonen** [comment]
Toteutettu yllä mainitut.

**Comment by mirmaid** [comment]
Siirretään ne ohjaus (neuvominen) käsitteen alakäsitteet jotka ovat tai vastaavat ruotsiksi käsitettä styrning, käsitteen ohjaus (suunnan säätely alle). Ohjaus (suunnan säätely) sulkutarkenne muutetaan muotoon (?). Käsitteen ohjaus (esityksen) sulkutarkenne muutetaan muotoon (taide)?

**Comment by mariaforsen** [comment]
Seuraavat alakäsitteet käsitteelle ohjaus (neuvominen) voisi ruotsin kannalta siirtää käsitteen ohjaus (suuntaaminen) alle:
    konserniohjaus
    omistajaohjaus
    sijainninohjaus
    sopimusohjaus
    strateginen ohjaus
    taloudellinen ohjaus
    toiminnanohjaus
    tulosohjaus
    tuotannonohjaus
    valtionohjaus
    ympäristöohjaus
