### ISSUE TITLE
Koostekäsite: edut

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#514]
Otetaan YSAan erikseen etuudet, joka korvaa käsitteen edut (etuudet). Edut (hyödyt) sulkutarkenne poistetaan.

**Comment by tpalonen** [comment]
Koska "edut (etuudet)"-käsitteellä on nyt yht. 34 alakäsitettä, en lähde poistamaan käsitettä ja miettimään alakäsitteille uutta paikkaa, vaan korjaan preflabelin muotoon "etuudet". Tälle ja tulevalle YSAn etuudet-käsitteelle pitäisi liittää definedconcept-suhde, kun aika on kypsä.

**Comment by mirmaid** [comment]
YSAssa on nyt etuudet KT edut (etuudet).

**Comment by mirmaid** [comment]
YSO-kokous 18.4.2016:

Edut (etuudet) poistettu YSOssa, oldLabel korjattu. Poistettava vielä kooste ja sulkutarkenne käsitteeltä edut (hyödyt).

**Comment by tpalonen** [comment]
Fixed
