### ISSUE TITLE
Vastaanotto

### ISSUE THREAD

**Issue by sinipessala** [NatLibFi/Finto-data#517]
Erilaisia vastaanotto-termejä on
- vastaanotot (järjestetty tapahtuma)
- vastaanotto (ajanjakso)
- vastaanotto (liikuttaminen)
- vastaanotto (paikka)
- vastaanotto (ymmärtäminen)

Vastaanotot vaikuttavat kokonaisuutena hämmentäviltä; mahdollisuus selkeyttää?. Suomeksi ei tule selväksi mikä "järjestetyn tapahtuman" ja "ajanjakson" ero on.

Lisäksi "vastaanotto (kooste)"-käsitteellä on assosiatiivinen suhde "taidemaku"-käsitteeseen, mikä lienee virhe, ja siitä puuttuu "vastaanotto (ymmärtäminen)" puuttuu sen alakäsitteistä.

**Comment by tpalonen** [comment]
Ratkaistu issuessa #406.
