### ISSUE TITLE
Lämmityslaitteet - tulisijat - uunit jne.

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#519]
Lämpöpatterit ovat lämmityslaitteita ja lämmönvaihtimia. En osaa sanoa ovatko kiukaat ja kamiinat lämmönvaihtimia, yleensä termiä ei käytetä näin laajasti. Osa lämmityslaitteista on YSOssa käsitteen "tulisijat" alla. Näistä uunit on ongelmallinen, koska sanaa käytetään kaikentyyppisistä uuneista. Melindan viitteistä ei pysty aina päättelemään, onko kyseessä varsinainen tulisija, jos esim. nimekkeessä eng. "furnace".

**Comment by mirmaid** [comment]
YSO-kokous 18.4.2016:

Uunit LT tekniset objektit (fyysiset objektit), RT tulisijat.

Lämmönvaihtimet RT lämmityslaitteet, jäähdytyslaitteet (joiden uusi LT laitteet).

**Comment by mirmaid** [comment]
@satuniininen: onko eng. ok uunit = ovens vai pitäisikö olla muutakin (furnaces)?

**Comment by satuniininen** [comment]
Enkkuun lisätty altlabel furnaces.
