### ISSUE TITLE
"ilmiöt"-kokonaisuuden läpikäynti

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#52]
1. What is to be changed/Mitä muutetaan: YSOn "ilmiöt"-käsite 
2. Why the change is needed/Miksi muutetaan: sisältää sekä toiminnallis-tapahtumallisia, että staattisia ("oliot") entiteettejä

Tausta:

"ilmiöt"-määritelmä Aallon YSOssa: tapahtuman tai tapahtumasarjan tuloksena syntynyt havaittavissa oleva asiaintila tai asiaintilan vaihtelu → kaksi eri asiaa!

"ilmöt"-Aallon YSOssa: kuului "pysyviin", vaikka pohjalla olleessa DOLCE-mallissa "muuttuva"

KKn ONKI-projektin uusi ylärakenne: "ilmiöt" "muuttuviin", "eli tapahtumiin ja toimintaan"
Katri Seppälän huomioita Aallon aikaisesta näkemyksestä (url: https://www.kiwi.fi/pages/viewpage.action?pageId=20123575 ): 2013-10-17 ONKI-Katri Seppälä tapaaminen (uudet YSO-käsitteet) (sivun alareuna)

"ilmiöt"-käsitteen määritelmiä muualla:
jllak tavalla ilmenevä, havaittavissa oleva (vars. mielenkiintoinen t. huomattava) tapahtuma t. tapahtumasarja. Kemiallinen ilmiö. Ukkonen ym. luonnonilmiöt. Sähkö-, valoilmiö. Kasvihuoneilmiö. Huumeiden käyttö aikamme sairaalloisena ilmiönä.(Kielitoimiston sanakirja)

a fact or situation that is observed to exist or happen, especially one whose cause or explanation is in question (Oxford dictionary)

A phenomenon is any observable occurrence (Wikipedia)

Ilmiö tai fenomeeni on jotain mitä voidaan havaita aistein, kuten havaittavissa oleva tapahtuma tai se voi olla matemaattinen. Se voi olla kulttuurinen tapahtuma, evoluutioon liittyvä tai illuusio. Ilmiö voi olla jaksollinen, fyysinen tai kertakaikkinen. (Wikipedia)

phenomenon (any state or process known through the senses rather than by intuition or reasoning)(Wordnet) HUOM! yläkäsite "prosessit"
phenomenon (a remarkable development)(Wordnet), yläkäsite "development" 3. Realized changes/Toteutetut muutokset Ehdotus:
tulee jakaa staattiset ilmöt erilleen tapahtumallisista ilmiöistä, näin saadaan ontologian perusjako tapahtumat-objektit toimimaan

12.11.2013: vaatii lisää selvitystyötä!

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=49_

**Comment by tpalonen** [comment]
Ilmiöt-kokonaisuutta on käsitekohtaisesti käyty läpi alla olevassa Google-taulukossa. C-sarakkeeseen on merkitty muutos, mikäli sellainen on kyseiselle käsitteelle tehty. Keltaisella värikoodilla oleville käsitteille ei ole tehty muutosta. Vihreille on tehty ja värittömien käsittely on kesken tai käsitellään muussa yhteydessä.
https://docs.google.com/spreadsheets/d/1gHoHdCz1HRChT4gPuPY23ILkKxvAweLW4kxTY7EJccc/edit?usp=sharing

@kseppala nosti ilmiöt-läpikäynnin esille. Tässä siis tietoja tehdyistä muutoksista.

**Comment by tpalonen** [comment]
Ilmiöt-kokonaisuus on käyty läpi ja muutokset on toteutettu YSOon. Merkittävä osa kokonaisuuteen sisältyneistä käsitteistä on siirtynyt muualle YSOn hierarkiassa. Kaikki päätökset on käsitekohtaisesti merkitty alla olevaan Google-dokumenttiin.
https://docs.google.com/spreadsheets/d/1gHoHdCz1HRChT4gPuPY23ILkKxvAweLW4kxTY7EJccc/edit?usp=sharing

Ilmiöt-hierarkiasta poistui seuraavat hierarkisoivat käsitteet: kulttuuriset ilmiöt, luonnontieteelliset ilmiöt, oikeustekniset ilmiöt, mentaaliset ilmiöt, muut ilmiöt ja taloudelliset ilmiöt. Ilmiöt-käsitteen välittömiksi alakäsitteiksi jäivät seuraavat käsitteet:

biologiset ilmiöt
fysikaaliset ilmiöt
kemialliset ilmiöt
luonnonilmiöt
olosuhteet
selittämättömät ilmiöt
yhteiskunnalliset ilmiöt
ääri-ilmiöt

**Comment by tpalonen** [comment]
PÄÄTÖS 14.11.2016:

Hyväksytään määritelmä:
"Tila tai tapahtuma, jolle ei voida määritellä selkeää alku- ja loppupistettä."

**Comment by satuniininen** [comment]
Määritelmä käännetty englanniksi.

**Comment by MikkoAleksanteri** [comment]
PÄÄTÖS 19.12.2016:

> Kulttuuriset ilmiöt -käsitteen kohtalo vielä selvittämättä.

Jätetään käsite, mutta siirretään se "yhteiskunnalliset ilmiöt"-käsiteen alle (kuten ominaisuuksien puolella)

**Comment by MikkoAleksanteri** [comment]
> PÄÄTÖS 19.12.2016:
> Jätetään käsite, mutta siirretään se "yhteiskunnalliset ilmiöt"-käsiteen alle (kuten ominaisuuksien puolella)

toteutettu dataan
