### ISSUE TITLE
Rajat

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#525]
Saimme palautetta TSK:lta, Riina Kosuselta, rajat-käsitteeseen liittyen: 

"YSOssa käsite "rajat" on "ulkoiset ominaisuudet"-käsitteen alakäsite. Paikkatieto-ontologian oma "raja"-käsite päätettiin ripustaa  käsitteen ”ihmisen määrittämä paikka” alakäsitteeksi. Seppälän Katri oli sitä mieltä, että kannattaisi kysyä teiltä, voisiko myös YSOn "rajat"-käsitteen ripustaa "ihmisen määrittämä paikka"-käsitteen alakäsitteeksi. Tällöin Paikkatieto-ontologian "raja"- ja YSOn "rajat"-käsitteet olisivat keskenään ekvivalentteja ja niiden alakäsitteet (esim. kiinteistöraja, kuntarajat) tulisivat toistensa vieruskäsitteiksi."

Riina Kosunen pyysi myös, että häneen otettaisiin yhteyttä, kun olemme tehneet päätöksen ja mahdollinen muutos on toteutunut Fintoon.
riina.kosunen@tsk.fi

**Comment by livirtan** [comment]
Rajat-käsitteellä on monenlaista käyttöä Melindassa. Jakamista harkitaan YSAssa.

**Comment by mirmaid** [comment]
Rajat (alueet) voisi jotenkin toimia, vaikka tuntuu melko konkreettiselta, useinhan rajat ovat vain sopimuksia, eivät "fyysisesti olemassa". Rajat (paikat) tuntuu jotenkin liian "pistemäiseltä"? Rajat (alueet) tuntuu paremmalta kun kyse on valtion rajoista, pienemmässä mittakaavassa se ei sovi yhtä hyvin (kiinteistöjen rajat, kunnan rajat). Samoin silloin kun valtion rajoja käsitellään enemmän muulta kuin maantieteen kannalta (esim. _The European Union and peacebuilding_, _Tilapäinen elämä, joustava työ: rajat maahanmuuton ja työvoiman prekarisaation mekanismina_, _Walls: travels along the barricades_) alueet-tarkenne tuntuu turhan konkreettiselta, rajat ovat näissä enemmän poliittisia kuin konkreettisia.

Melindassa yllättävän suuri osa viitteistä käsittelee nimenomaan alueiden rajoja. Muista löytyy ainakin sosiaalipsykologiaa, mutta myös hyvinkin vaikeasti määriteltävää

**Comment by mirmaid** [comment]
https://rajatontatiedekasvatusta.wordpress.com/oppimateriaali/rajoja-on-monenlaisia/

**Comment by YSO-kokous** [comment]
Voisko prefLabel voisi olla **aluerajat** tai **alueiden rajat**?
