### ISSUE TITLE
Jumalan teatteri

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#533]
Missä menee raja kuuluuko termi yhteisöihin/nimiin tai yleissanoihin? Huomautusta ei näy YSOssa.

**Comment by mirmaid** [comment]
Tämä siirretään YSAsta yhteisöauktoriteetiksi ja vastaavia tutkitaan.

**Comment by mirmaid** [comment]
Poistettu YSAsta.
