### ISSUE TITLE
Yksikkö-monikko (sulkutarkenteet ja kahden käsitteen termien samankaltaisuus)

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#536]
Sulkutarkenteisiin ja kahden eri käsitteen samankaltaiseen termiin (pref tai old) kaivataan linjanvetoa. Koostekäsitteiden läpikäynnissä ja toisaalta englantia käännettäessä on tullut haasteita keksiä kahdelle käsitteelle eriävä label. Tässä 

Ongelma 1: Tarvitaanko jaetuilla käsitteillä sulkutarkenne molemmille?
- CASE vastaanotto: päätettiin että jätetään ontologiaan "vastaanotto (reseptio)" [nykyinen "vastaanotto (ymmärtäminen)"] sekä "vastaanotto" ilman sulkutarkennetta [nykyinen "vastaanotto (liikuttaminen)"]. Järkevän sulkutarkenteen keksiminen jälkimmäiselle koettiin haasteelliseksi. Jos sulkutarkenne tarvitaan ehdottomasti, on ehdotettu mm. "(vastaanottaminen)" tai "(fyysinen)". Tarvitaanko sulkutarkenne ehdottomasti?

Ongelma 2: Tarvitaanko käsitteen A preflabeliln sulkutarkenne, jos käsitteellä B on oldlabelina sulkutarkenteellinen versio samasta termistä? 
- CASE suolaus. Aiemmin YSOssa oli kaksi suolaus käsitettä: "suolaus (säilöntä)" ja "suolaus (tiesuolan käyttö)". Päätettiin että jätetään vain yksi "suolaus"-käsite säilöntämerkityksessä, ilman sulkutarkennetta ja ehdotetaan YSAan uusi termi "tiesuolaus". Tähän liitettäisiin oldlabel "suolaus (tiet)". Päätettävä: Tarvitaanko jäljellä jäävän suolaus-käsitteen preflabelilla olla sulkutarkenne, kun YSAan ehdotettavalle uudelle käsitteelle tulisi oldlabeliksi sulkutarkenteellinen muoto ["suolaus (tiet)"]?

Ongelma 3: Sulkutarkenne yksikkö/monikko-tapauksissa?
- CASE merkintä: aiemmin oli "merkintä (tieto)" ja "merkintä (toisenlaiseksi muuttaminen)". Päätettiin muuttaa nämä muotoon "merkinnät" ja "merkintä (toiminta)", respectively. Todettiin kuitenkin samalla, että jos preflabel on yksilöivä, sulkutarkenne ei ole välttämätön erityisesti jos se ei selvennä käsitteen merkitystä. Päätös kuitenkin herätti myöhemmin vielä keskustelua ja mainittiin ISO-standardi, jossa todetaan tällaisista tapauksista: "the distinction between them should be reinforced by adding a scope note and if possible a qualifying term or phrase". Katri Seppälä on lisännyt YSOon jonkin verran tällaisia sulkutarkenteita (esim. "oikeus (erikoisala)" ja "oikeudet (edut)"), mutta ei systemaattisesti.

---

Sivuhuomautus: YSOssa on päätetty, että englannin kielessä saa olla kahdella (tai useammalla) käsitteellä sama preflabel, jos erottavaa ja käyttäjälle hyödyllistä preflabel-eroa on hyvin vaikea tehdä. Vrt. julkaisijat ja kustantajat (molemmilla englannin kielen vastine "publishers").

**Comment by tpalonen** [comment]
Finto viikkopalaverin päätös 24.2.2015:

Kohta 1:
Laitetaan tällaisissa tapauksissa sulkutarkenteet molemmille ISO-standardiin vedoten.

Kohta 2:
Tällaisissa tapauksissa ei tarvita preflabeliin sulkutarkennetta.

Kohta 3:
Kyseisessä tapauksessa ei tarvita sulkutarkennetta "merkinnät"-käsitteelle, koska merkintä viittaa tässä selvästi toimintaan, mikä käy riittävän hyvin ilmi termistä. Koulu-koulut-tyyppinen erottelu vaatii kuitenkin erillisen keskustelunsa.

**Comment by tpalonen** [comment]
Tehdään listaus kaikista yksikkö-monikko-käsitteistä ja käydä nämä systemaattisesti läpi. Onko sulkutarkenne tarpeen, toisin sanoen selkeyttääkö se merkityseroa käyttäjälle vai ei? SPARQL vaatinee ekspertiisiä Leipätehtaan puolelta.

**Comment by tpalonen** [comment]
Tehdään listaus tähän issueeseen käsin muistinvaraisesti, pohjustetaan ja annetaan sulkutarkenne-ehdotukset.

**Comment by mirmaid** [comment]
kieli / kielet
kirkko (ilmiöt) / kirkot (organisaatiot)
koulu (ilmiöt) / koulu (oppilaitokset)
kulttuuri (toimintatavat) / kulttuurit (kulttuurimuodot)
kuvaus (luonti) / kuvaukset (tuotokset)
organisaatio (ilmiöt) / organisaatiot (järjestelmät)
rukous (toiminta) / rukoukset (tuotokset) (muutosehdotus YSEssä https://github.com/Finto-ehdotus/YSE/issues/4801)
seurakunta (ryhmät) / seurakunnat
taide / taiteet
tiede (ilmiöt) / tieteet (erikoisalat)
uskonto (uskominen) / uskonnot (opit)

**Comment by mirmaid** [comment]
https://github.com/NatLibFi/Finto-data/issues/715

**Comment by mirmaid** [comment]
rakenne, rakenteet
taide, taiteet
teatteri, teatterit

**Comment by mirmaid** [comment]
YSO-kokous 9.2.2017:

kala (elintarvikkeet) / kalat (eläimet): ok, ei muutosta

**Comment by mariaforsen** [comment]
Onko rasva vs. rasvat käsitelty?

**Comment by mirmaid** [comment]
kieli / kielet: kävisikö kieli (järjestelmät) TAI (viestintä)? YSOn aikaisempi tarkenne (kielenkäyttö) sopisi välillä jopa paremmin (esim. kun käytetään tekstin tyylistä), mutta sanastossa on myös _kielenkäyttö_, ja näiden välistä eroa olisi silloin vaikea hahmottaa labeleista.

**Comment by mirmaid** [comment]
rasva / rasvat: onnistuisikohan tässä yhdistäminen? Sanastossa on myös _rasvapitoisuus_ ja _rasvakudokset_.

**Comment by mariaforsen** [comment]
Onko risti / ristit käsitelty?

**Comment by YSO-kokous** [comment]
Nakitetaan läpikäytävät yksittäin jollekulle vastuuhenkilölle, joka ehdottaa ratkaisua. Käydään läpi seuraavassa YSO-kokouksessa.

**Comment by YSO-kokous** [comment]
Käydään läpi ylläoleva kesken-lista: vastuuhenkilö vertaa Melindan tietueita nykyiseen jakoon ja ehdottaa tarpeen mukaan joko yhdistämistä tai jaon säilyttämistä, sekä tutkii ovatko sulkutarkenteet käyttökelpoiset hakijaa ja kuvailijaa ajatellen ja tarvittaessa ehdottaa selkeämpiä. Muutosehdotukset tehdään suoraan YSEen ja linkitetään ylläolevaan listaan.

**Comment by mirmaid** [comment]
Listalta puuttuu vielä:
siirto (jaettu ysossa) / siirrot

**Comment by MikkoAleksanteri** [comment]
arvo / arvot [Mikko]
ensimmäinen viittaa ensiaijaisesti taloudelliseen arvoon, eli kielitoimiston sanakirjan määritelmän 

_arvo1
1. se minkä perusteella jtak pidetään merkityksellisenä, hyvänä, arvokkaana tms., merkitys, kantavuus. Mainos-, uutisarvo. Tunnearvo. Arvonsa säilyttävä keksintö. Vain tosiasioilla on pysyvä arvo.
2. us. mon. arvokas, merkitsevä asia. Elämän tärkeimmät arvot. Kauneus-, kulttuuriarvo. Korvaamattomia taidearvoja. Kaikkien arvojen uudelleenarviointi.
3. kunnia, arvokkuus, arvovalta, vaikutusvalta. Ihmisarvo. Arvonsa tunteva. Olla arka arvostaan. Jkn arvon mukainen, arvolle sopiva. Arvoa alentava, loukkaava. Arvossa pidetty [= arvostettu] taiteilija, koulu. Isänmaallisuus oli taas arvossaan. Asettaa t. kohottaa jku, jk oikeaan arvoonsa. Hänen arvonsa on noussut silmissäni. Antaa arvoa toisten mielipiteille kunnioittaa, arvostaa toisten mielipiteitä. Jättää loukkaus omaan arvoonsa sivuuttaa merkityksettömänä, harkitsemattomana, mielettömänä tms.
4. arvoaste; arvonimi, titteli. Oppiarvo. Tohtorinarvo. Sotilasarvoltaan kersantti. Saada kauppaneuvoksen arvo.
5. käypä hinta. Maatilan, irtaimiston arvo. Rahan arvo eli ostovoima. Kauppa-arvo. Nimellisarvo. Auton jälleenmyyntiarvo. Osakkeiden arvo nousee, laskee, pienenee, suurenee. Taulu myytiin alle todellisen arvonsa. Tavaroita 50 euron arvosta.
6. suureen t. luvun suuruus, numero, luku. Liki-, maksimiarvo. Itseisarvo. Mittarin asteikosta luetut arvot. Yhtälön x:n arvot.
7. Arvon us. iron. arvoisa, kunnioitettava. Kas, arvon herrat suvaitsevat lopulta saapua!_

**Comment by MikkoAleksanteri** [comment]
[kulttuuri (toimintatavat)](http://www.yso.fi/onto/yso/p372) / [kulttuurit (kulttuurimuodot)](http://www.yso.fi/onto/yso/p1546) [Mikko]
ehdotus: ei muutosta

**Comment by satuniininen** [comment]
[kotitalous (oppiaineet)](https://finto.fi/yso/en/page/p7116?clang=fi)
[kotitaloudet (organisaatiot)](https://finto.fi/yso/en/page/p8562?clang=fi)

Yksiköllisen kuvailukäytössä on hajontaa, joten tarvitsee sulkutarkenteen. Ei siis muutoksia.
Monikollisen sulkutarkenteelle ei ole varsinaista tarvetta. Käsite on yksiselitteinen ja kuvailukäyttö yhtenäistä.

**Comment by satuniininen** [comment]
Listalle lisätty raja-arvo / raja-arvot

**Comment by satuniininen** [comment]
Sulkutarkenteiden säilyttämisestä myös #924

**Comment by mariaforsen** [comment]
Listalle lisätty leikki, leikit

**Comment by satuniininen** [comment]
Lisätty poliisit (ammatit) / poliisi (organisaatiot)

**Comment by satuniininen** [comment]
lisätty perhe / perheet

**Comment by mariaforsen** [comment]
lisätty esittely / esittelyt

**Comment by mariaforsen** [comment]
lisätty itku / itkut

**Comment by mariaforsen** [comment]
lisätty sijoitus / sijoitukset

**Comment by mariaforsen** [comment]
Yllä olevista ratkaisematta vielä: arvo/arvot ja tila/tilat, ja niistä on jo tehty yse-issueita, joten onko tämä nyt suljettavissa?
