### ISSUE TITLE
Koostekäsite: ilmatorjunta

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#537]
RATKAISU: YSAan otetaan ilmatorjuntajoukot, joka vastaa käsitettä ilmatorjunta (maavoimat). Kun käsite on päivittynyt uutena YSOon, poistetaan sulkutarkenne käsitteeltä ilmatorjunta (ilmapuolustus) ja päätetään mitä tehdään ilmatorjunta (maavoimat) -käsitteelle.

**Comment by MikkoAleksanteri** [comment]
YSO-kokous:

# poistetaan ilmatorjunta (maavoimat) ja tehdään sille uudelleenohjaus käsitteeseen http://finto.fi/yso/fi/page/p2369
