### ISSUE TITLE
"muotit"-käsitteen assosiatiiviset

### ISSUE THREAD

**Issue by MikkoAleksanteri** [NatLibFi/Finto-data#542]
Käsitteellä "muotit"  	http://www.yso.fi/onto/yso/p17705
 oliot > fyysiset objektit > elottomat objektit > muotit 

on assosiatiivisina käsitteinä

    mallit (havainnointimallit)
    mallit (samaistumismallit)
    mallit (tehtävä)
    mallit (tekninen objekti)

Kaikki eivät varmaan sovi, onko esim samaistumismalleilla mitään tekemistä näiden kanssa?

**Comment by tpalonen** [comment]
Kaikki muut paitsi "mallit (tuotokset)" (oldlabel: mallit (havaintomallit)) on poistettuja käsitteitä.

**Comment by tpalonen** [comment]
Asia on ratkennut jaettujen käsitteiden poistamisen myötä.
