### ISSUE TITLE
"tekninen objekti" ja "fyysinen kokonaisuus"

### ISSUE THREAD

**Issue by MikkoAleksanteri** [NatLibFi/Finto-data#547]
Käsite http://www.yso.fi/onto/yso/p1340 "tekninen objekti" jostain syystä yksikössä.

Ehdotus:
"tekninen objekti" -> "tekniset objektit (fyysiset objektit)"

sulkutarkenne tarvitaan, koska issue #498 päätökset mukaisesti luotiin uusi samanniminen käsite

**Comment by MikkoAleksanteri** [comment]
Käsite http://www.yso.fi/onto/yso/p1674 "fyysinen kokonaisuus" jostain syystä yksikössä.

Ehdotus:
"fyysinen kokonaisuus" -> "fyysiset kokonaisuudet"

**Comment by MikkoAleksanteri** [comment]
Vähemmistöpäätös (Mikko, Mirja) 6.3.2015:

"tekninen objekti" -> "tekniset objektit (fyysiset objektit)"
muokattu dataan.

Päätös tulee vielä hyväksyttää YSO-kokouksessa.

**Comment by tpalonen** [comment]
Fyysinen kokonaisuus muutettu monikkoon. Ks issue #548
