### ISSUE TITLE
agentit

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#552]
Monimerkityksinen huomautus ja termi, onko jako tarpeen? Ei erityistarvetta ruotsiksi.

**Comment by mariaforsen** [comment]
Ks. YSO-huomautuksissa monta merkitystä listaa: https://docs.google.com/spreadsheets/d/1igl6qGGXJE0q0s_be_iawWIyuZEze2bFg2ldZlzU6KA/edit#gid=1100133302

**Comment by mariaforsen** [comment]
Ruotsiksi samalla tavalla monimerkityksinen sana. Kieliopillisena olisi varmaan agentti yksikössä? Asiamiehet jo on, joten tarvitaanko siinä merkityksessä tätä, vai voisiko lisätä esim siihen KT:ksi esim. agentit (asiamiehet) tms.?

**Comment by tpalonen** [comment]
Mirja selvittää.

**Comment by mirmaid** [comment]
Muutosehdotus YSEssä https://github.com/Finto-ehdotus/YSE/issues/4794
