### ISSUE TITLE
Koostekäsite: puuvilla, pellava, hamppu

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#553]
Näitä ei jostain syystä ole ollut käsiteltävien listalla:

puuvilla
pellava
hamppu

Huom! Myös uusi YSO-käsite öljyhamppu joka on hampun alla!

**Comment by mirmaid** [comment]
Poistetaan jako, jätetään yläkäsitteeksi kuitukasvit ja/tai öljykasvit ja lisätään RT:ksi kasvikuidut?
