### ISSUE TITLE
Viestintärauha, kotirauha jne.

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#556]
Viestintärauha, hautarauha, joulurauha, julkisrauha, kotirauha, uskonrauha ja työrauha (?). YSOssa näillä on eri yläkäsitteitä, mutta ovat kuitenkin samankaltaisia keskenään.

**Comment by tpalonen** [comment]
PÄÄTÖS:
- hautarauha LT oikeudelliset objektit
- uskonrauha LT oikeudelliset objektit
- kotirauha LT oikeudelliset objektit + RT perusoikeudet
- viestintärauha LT oikeudelliset objektit
- julkisrauha LT oikeudelliset objektit
- joulurauha LT olosuhteet
- rauha LT olosuhteet
- luonnonrauha LT olosuhteet
- työrauha (työyhteisöt) LT olosuhteet
- työrauha (työmarkkinat) LT olosuhteet
- välirauha LT yhteiskunnalliset ajanjaksot; käsitetyypiksi instanssi
