### ISSUE TITLE
Liikuntapaikat jne. 

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#557]
Hierarkia olisi syytä käydä läpi käsitteiden liikunta-alueet, liikuntapaikat, liikuntatilat, urheiluhallit ja urheilukentät osalta. Ks. myös radat.

**Comment by mirmaid** [comment]
- kilparadat: YSA LT radat, YSO LT radat ja liikuntapaikat. Onko jälkimmäinen ok?
- kuntoradat: YSAssa ei LT:tä radat, hyväksymmekö radoiksi myös pururatatyyppiset?
- moottoriradat, raviradat: LT liikuntapaikat kuulostaa oudolta näissä, eikö radat riittäisi?
- ampumaradat: YSAn ratkaisu ei kai toimi YSOssa, vähän erilaisia ratoja kuin muut mutta lienee ok?

Muilta osin hierarkia korjattu YSAssa (muutokset seuraavassa päivityksessä).

**Comment by MikkoAleksanteri** [comment]
YSO 9.1.2016:
(YK: yläkäsite, AK: assosiatiivinen käsite)

    kilparadat: YSA LT radat, YSO LT radat ja liikuntapaikat. Onko jälkimmäinen ok?
PÄÄTÖS: kilparadat YK radat AK liikuntapaikat

    kuntoradat: YSAssa ei LT:tä radat, hyväksymmekö radoiksi myös pururatatyyppiset?
PÄÄTÖS: ei muutosta

    moottoriradat, raviradat: LT liikuntapaikat kuulostaa oudolta näissä, eikö radat riittäisi?
PÄÄTÖS: YK radat

    ampumaradat: YSAn ratkaisu ei kai toimi YSOssa, vähän erilaisia ratoja kuin muut mutta lienee ok?
PÄÄTÖS: ei muutosta
