### ISSUE TITLE
Koostekäsite: loukkaantuminen

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#562]
RATKAISU: muutetaan sulkutarkenteet (muutos) > (fyysinen) ja (tunteminen) > (psyykkinen). Käsitellään vielä loukkaantuminen (psyykkinen) vs. loukkaaminen/loukkaukset (bli stött / kränkning) YSA-kokouksessa.

**Comment by tpalonen** [comment]
Sulkutarkenteet muutettu.

**Comment by mirmaid** [comment]
YSA 2/2015

**Comment by mirmaid** [comment]
Ratkaistu ja toteutettu YSAssa ja YSOssa.
