### ISSUE TITLE
kulttuurit (kulttuurimuodot) ja kulttuuri (toimintavat)

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#565]
Jako tulee YSAsta. Näiden sulkutarkenteet olisi hyvä muuttaa.

**Comment by tpalonen** [comment]
Sulkutarkenteet eivät niinkään ongelma kuin se, että alakäsitteet pitäisi käydä läpi ja sijoittaa uudelleen näiden kahden yläkäsitteen suhteen. Mikko selvittää.

**Comment by MikkoAleksanteri** [comment]
Huom. myös käsite toimintakulttuuri, tämän alle voisi mennä esim. kulutuskulttuuri, hoitokulttuuri, oikeuskulttuuri ym.

**Comment by tpalonen** [comment]
Myös osakulttuureihin voisi siirtää muutaman. Esim. homo, lesbo, poika, tyttökulttuuri.

**Comment by MikkoAleksanteri** [comment]
Kokonaisuudessaan siis:

- kulttuurit (kulttuurimuodot) http://www.yso.fi/onto/yso/p1546
- kulttuuri (toimintavat) http://www.yso.fi/onto/yso/p372
- toimintakulttuuri http://www.yso.fi/onto/yso/p2036
- osakulttuurit http://www.yso.fi/onto/yso/p8552
