### ISSUE TITLE
sade ST raesade

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#567]
Hierarkia väärä ruotsiksi, koska ruotsiksi on regn (sade) aina vesisadetta. Ontologiassa ei ole vesisadetta erikseen joten voisiko olettaa että sade= ensisijaisesti vesisade, ja laittaa raesade LT sääilmiöt (kuten on myös esim. lumisateen kohdalla)?

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 04.01.2016:
raesade LT sääilmiöt

**Comment by tpalonen** [comment]
Lisäsin raesade RT sade ja lumisade RT sade.
