### ISSUE TITLE
käsityö, käsityöt (elottomat objektit), käsityöt (työ)

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#568]
Miksi on käsityöt jaettu? Käsityö yksikkömuodossa, eli työhön viittaava sana on jo erikseen sanastossa.

**Comment by mirmaid** [comment]
YSO-kokous 7.1.2016: poistetaan käsityöt (työ) (deprecatedReplacedBy käsityö), siirretään sen alakäsitteet käsitteen käsityö alle. Käsityölle LT työ työn sisällön mukaan, sulkutarkenne (toiminta). Käsityöt (elottomat objektit) > käsityöt (objektit).
