### ISSUE TITLE
"lapset (kooste)" -käsitteen muutos

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#57]
_From [SNyk...@gmail.com](https://code.google.com/u/112439428317292360191/) on January 20, 2014 15:45:04_

1. What is to be changed/Mitä muutetaan "lapset (ikään liittyvä rooli)"
"lapset (kooste)"
"lapset (perheenjäsenet)"
"lapset (sosioekonomiseen ryhmään liittyvä rooli)" 2. Why the change is needed/Miksi muutetaan YSAssa vain yksi "lapset"
onko perusteltua jakaa YSOssa näin moneksi? 3. Realized changes/Toteutetut muutokset

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=54_

**Comment by tpalonen** [comment]
Lapset-asia on nyt saatu käsiteltyä koostekokouksissa. Päätimme poistaa "lapset (sosioekonomiseen ryhmään liittyvä rooli)" käsitteen, mutta muu jako säilyy. "Lapset (ikään liittyvä rooli)" muutettiin muotot "lapset (ikäryhmät)". Ks. issuet #607 ja #387 .
