### ISSUE TITLE
muodot, lajit

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#572]
lajit LT luokitukset (tieto). Urheilulajit-käsitteen alla on jonkin verran varsinaisia lajien nimiä (ilmeisesti niin uusia että ovat YSO-kokouksen päätöksiä), muuten lajinimiä ei ole tässä hierarkiassa. Periaate ilmeisesti että tämäntyyppiset käsitteet (luokitustapa?) haluttu erottaa konkreettisista ilmentymistä ( @kseppala ). Samantyyppinen olisi esim. kuntamuodot. Miten jatkossa?

**Comment by tpalonen** [comment]
Kuntamuodot-tyyppiset käsitteet ("kaupungit (kuntamuodot)" jne) päätettiin poistaa ks. #421.

**Comment by tpalonen** [comment]
Itse säilyttäisin tämänhetkisen YSO-hierarkian sellaisenaan seuraavin muutoksin:

bioindikaattorit LT muu rooli
maakuntaeläimet LT muu rooli + RT nimikkolajit
maakuntalinnut LT muu rooli + RT nimikkolajit
maakuntakasvit LT muu rooli + RT nimikkolajit
maakuntakivet LT muu rooli + RT nimikkolajit
muinaistulokkaat LT muu rooli + RT tulokaslajit
vapaalasku LT talviurheilu + RT alppilajit
suojuoksu LT urheilu + RT juoksulajit
ultrajuoksu LT urheilu + RT juoksulajit
vuorijuoksu LT urheilu + RT juoksulajit
ninjutsu LT budo + RT budolajit
