### ISSUE TITLE
uskonnolliset tuotokset

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#574]
Nyt on alakäsitteitä ainakin kahdentyyppisiä: 

```
aneet
antikristus
apokryfit
armo
armolahjat
dogmit
evankeliumi
evankeliumit
fatwat
hadith
hartauspuheet
hautauspuheet
jumalat
jumalatodistukset
jumalattaret
kaanonit (valikoimat)
kaitselmus
karma
katekismukset
kirkko (ilmiöt)
kiusaukset
käskyt
luomakunta
profetiat
psalmit
pseudepigrafit
pyhät kirjat
Qumranin kirjoitukset
rukoukset (tuotokset)
saarnat
siunaukset (tuotokset)
sutrat
synodaalipuheet
tunnustuskirjat
uskontunnustukset
virsikirjat
Vuorisaarna
```

Pitäisikö osa siirtää muualle, esim. karma, kaitselmus, jumalat. jumalattaret, armo, armolahjat, antikristus? Tai luoda uusi yläkäsite niille? Nämä eivät ole samanlaisia kuin esim. virsikirjat, kaanonit, evankeliumit jne, vaan enemmän "uskonnollisia abstrakteja objekteja", uskon objekteja tms.

**Comment by tpalonen** [comment]
Päätettiin, että siirretään karma, katselmus, jumalat, armo ym sen tyyppiset käsitteet LT uskonnolliset käsitykset. Maria laatii listan niistä, jotka siirrettäisiin ja tuo YSO-kokouksen hyväksyttäväksi.

**Comment by mariaforsen** [comment]
Ehdotan että ainakin nämä olisi siirrettävissä termin uskonnolliset käsitykset alle: 
antikristus
armo 
armolahjat
evankeliumi
jumalat
jumalattaret
kaitselmus
karma
kirkko (ilmiöt)
kiusaukset

**Comment by livirtan** [comment]
Ovatko antikristus, armolahjat, jumalat, Pyhä Henki ym. todellakin uskonnollisia käsityksiä? Ymmärrän käsitys-sanan sitten eri tavalla. Minusta ne ovat mentaalisia objekteja, alalajina voisi olla uskontoon liittyvät objektit. Uskonnollisten käsitysten alla ei ole nyt jumalakäsitykset-käsitettä, mikä taas tuntuisi kuuluvan juuri siihen kategoriaan.

Samaa mieltä olen siitä, mitä Maria sanoo nykyisten uskonnollisten tuotosten kahdenlaisesta luonteesta. Ehdotus: siirretään nuo abstraktit armo, synti, jumalat yms. mentaalisten objektien puolelle omaksi ryhmäkseen ja pidetään kulttuurisissa objekteissa konkreettisemmat tapaukset, kuten evankeliumit ja uskontunnustukset.

Voiko kirkko (ilmiöt) tosiaan olla olioiden kategoriassa?

Ehdotan mystiikan siirtoa uskonnollisiin ilmiöihin.

**Comment by tpalonen** [comment]
Mirja ja Mikko tutkivat sopivia yläkäsitteitä näille käsitteille.

**Comment by mariaforsen** [comment]
Huom! Uskonnollisten käsitysten alle on jo sijoitettu samankaltaisia (esim. Pyhä Henki) kuin ne "abstraktisemmat" uskonnolliset tuotokset - yllä olevan päätöksen 31 Aug 2015 mukaan. Jos haluamme sitä perua niin täytyy muistaa siirtää nämäkin muualle. 

Ymmärrän toki ettei uskonnolliset käsitykset-termi ole ongelmaton yläkäsitteenä, mutta miten voitaisiin saada parempi yläkäsite, varsinkin jos halutaan mahdollisimman "neutraali" sellainen? Vaihtoehto olisi keksiä ihan uusi käsite, mutta mikä se voisi olla? Tai jakaa "uskonnolliset abstraktit tuotokset"  ja "uskonnolliset konkreettiset tuotokset"? 

"Uskonnollinen käsitys" on sellainen termivalinta että sitä voi hyväksyä yhtä hyvin ateisti kuin uskonnollinen ihminen, eri tieteenalojen edustajat jne. Käsityksen määritelmä: 1) havaintoon, kokemukseen t. ajatteluun perustuva mielikuva t. tieto 2) ajatus, ajattelutapa, näkemys, mielipide, asenne, vakaumus, luulo, arvelu, vaikutelma.

**Comment by mirmaid** [comment]
Olen Liisan kanssa samoilla linjoilla käsitykset-sanan merkityksestä, ts. ihmisellä voi olla käsitys vaikka kuolemanjälkeisestä elämästä (se on/ei ole olemassa, millaista se on jne.), mutta se ei ole itsessään käsitys. 

- Mainituista antikristus, jumalat ja jumalattaret ovat toimijoita, jotka YSOn nykyisessä hierarkiassa kuuluisivat minusta joko _uskontoon liittyvä rooli_ tai _toimintaan liittyvä rooli_ -ryhmään. 

- kiusaukset voisi olla YK mentaaliset objektit
- evankeliumi sopii minusta myös yksikössä uskonnollisiin tuotoksiin
- armo on vaikea, hyvyys olisi saman tyyppinen, sen YK yhteiskunnalliset ominaisuudet ei ehkä ole ihan täysin onnistunut. Hyvä löytyy myös (YK käsitteet), tai lunastus (uskonto) YK uskontoon liittyvät tapahtumat / pelastus YK toisenlaiseksi muuttaminen, tai armahdus & anteeksianto YK henkilön aseman muuttaminen. Minusta lähinnä abstrakti objekti. Toisaalta jopa uskonnolliset kokemukset voisi olla mahdollinen.
- armolahjat ovat myös abstrakteja objekteja - lahjoiksi ne kaikkialla määritellään mutta eivät sovi sen alakäsitteeksi nykyisellään
- kaitselmus - toiminta-hierarkiaan?
- kuolemanjälkeinen elämä - uskontoon liittyvät tapahtumat -ryhmässä on samankaltaisia, mutta tapahtumallisuus on tässä kovin vähäistä. Olemisen alla on muita elämiä ja eksistenssi. Toisaalta olisi hyvä saada samaan paikkaan kuin aiemmat elämät?
- karma - kohtalon YK kulttuuriset objektit

**Comment by mariaforsen** [comment]
Ok hyvä, mutta evankeliumi (sanoma Jeesuksesta ihmiskunnan pelastajana) ei ole konkreettinen asia kuten evankeliumit (=kukin Uuden testamentin neljästä ensimmäisestä kirjasta; evankeliumiteksti) vaan abstrakti käsite, joten vaikeaa nähdä miten voisi olla (konkreettisten) tuotosten alla? Vaikeaa on myös nähdä miten karma yms. voi olla samassa joukossa (kulttuuriset objektit) kuin esim. leikekirjat, sketsit, tiivistelmät, sitaatit jne.? Olemisen alla on nyt huonosti sopivia yläkäsitteitä ja on jo aikaisemmin todettu että niille pitäisi tehdä jotain ks. issue https://github.com/NatLibFi/Finto-data/issues/684 

Uskonnolliset tuotokset termin alla on tällä hetkellä myös seuraavat "ei konkreettiset" asiat, jotka eivät sovi tekstien yms. viereen (Mirjan viime kommentissa mainittujen lisäksi) : kadotus, kirkko (ilmiöt), luomakunta, magia, mystiikka, noituus, paavius, paholainen, uskonto (uskominen). Osalle näistä YK uskontoon liittyvä rooli, vaikka esim. muslimit, munkit, jumalat ja paholainen ovat aika eri asioita?

**Comment by MikkoAleksanteri** [comment]
Ok hyvä, mutta evankeliumi (sanoma Jeesuksesta ihmiskunnan pelastajana) ei ole konkreettinen asia kuten evankeliumit (=kukin Uuden testamentin neljästä ensimmäisestä kirjasta; evankeliumiteksti) vaan abstrakti käsite, joten vaikeaa nähdä miten voisi olla (konkreettisten) tuotosten alla?

Käsite "uskonnolliset tuotokset" (http://www.yso.fi/onto/yso/p1014) ei ole konkreettinen, vaan oabstarkti objekti. Käsitteen hierarkiapolku:  oliot > abstraktit objektit > kulttuuriset objektit > uskonnolliset tuotokset

**Comment by mariaforsen** [comment]
Siinä tapauksessahan pitäisi siirtää pois konkreettiset, miten vain ei ole varmaan käsitteellisesti oikein että molemmat tyypit ovat samassa paikassa.

**Comment by mirmaid** [comment]
Lähdin nyt liikkeelle tuosta lyhyestä listasta kun en ehtinyt millään katsoa kaikkia, ja toisaalta tarkoitus oli pohjustaa keskustelua, en halua päättää näitä yksin :simple_smile:. _Oleminen_ on ilman muuta hankala ja tuleekin käsittelyyn muun toiminta-hierarkian kanssa, mainitsen sen vaan koska siellä on näitä vähän vastaavia. Samoin nuo konkreettinen vs. abstrakti on ongelmia (muuallakin kuin tässä). Mutta ehkä - toivottavasti - ratkaistavissa olevia.

**Comment by mirmaid** [comment]
YSO-kokous 16.11.2016:
- antikristus, paholainen, jumalat ja jumalattaret YK _yliluonnolliset olennot_ 
- kiusaukset YK _mentaaliset objektit_

**Comment by mariaforsen** [comment]
Uskonnollisten tuotosten alla on edelleen kaksi aivan erilaista tyyppiä, konkreettisia ja abstraktisia:
    aiemmat elämät 
    aneet
    antikristus <uskonnolliset käsitykset? (siinä on jo alakäsitteenä:  predestinaatio, Pyhä Henki, synti, teodikea, vai siirretäänkö ne tänne?
    apokryfit 
    armo
    armolahjat
    dogmit
    evankeliumi
    evankeliumit
    fatwat
    hadith
    hartauspuheet
    hautauspuheet
    jumalat 
    jumalatodistukset
    jumalattaret
    kadotus
    kaitselmus
    karma
    katekismukset
    kirkko (ilmiöt)
    kiusaukset
    kuolemanjälkeinen elämä
    käskyt
    luomakunta
    magia
    mystiikka
    noituus
    paavius
    paholainen
    profetiat
    psalmit
    pseudepigrafit
    pyhät kirjat
    Qumranin kirjoitukset
    rukoukset (tuotokset)
    saarnat
    siunaukset (tuotokset)
    sutrat
    synodaalipuheet
    tunnustuskirjat
    uhrilahjat
    uskonto (uskominen)
    uskontunnustukset
    virsikirjat
    votiivit
    Vuorisaarna
Siirretäänkö siis konkreettisemmat "tekstimäiset/teosmaiset", esim. katekismukset, votiivit, virsikirjat, pyhät kirjat jne. pois? Jos tarkoitus on pitää uskonnolliset tuotokset "abstrakti-hierarkiassa"?

Tämä pitänee ratkaista ennen #800

**Comment by mirmaid** [comment]
Osa sopisi myös (kirjallisiin) teoksiin.

**Comment by YSO-kokous** [comment]
aiemmat elämät > elämä? käsitteessä on oletuksena että myös aiemmat elämät ovat biologisia, joten jos lähtökohdaksi ottaa itse käsite (eikä oma kanta/suhtautuminen käsitteen todellisuudenmukaisuuteen) niin myös elämä voisi olla mahdollinen yläkäsite > **elämä**
aneet
antikristus jo päätetty
armo
armolahjat
dogmit
evankeliumi
evankeliumit
fatwat
hadith
hartauspuheet
hautauspuheet
jumalat 
jumalatodistukset
jumalattaret
kadotus
kaitselmus
karma 
katekismukset
kirkko (ilmiöt)
kiusaukset jo päätetty
kuolemanjälkeinen elämä
käskyt -ei liity uskontoon > jonkinlainen viestintä tai keskinäinen toiminta? Kymmenen käskyä sen sijaan voisi laittaa samaan paikkaan kuin vastaavat uskonnolliset säännöt ja tekstit (on ruotsiksi budorden, ja näyttää vähän kaukaa haetulta käskyjen (befallningar) alla
luomakunta
magia > kulttuuriset objektit? Sen alla mm. loitsut ja kiroukset 
mystiikka (oikeastaan kaksimerkityksinen) >kulttuuriset objektit? 
noituus >kulttuuriset objektit? Sen alla on mm. jooga, loitsut, Graal, Nooan arkki, kiroukset, horoskoopit, aura jne. 
paavius
paholainen jo päätetty
profetiat
psalmit
pseudepigrafit -Melindassa käytetty melkein vain uskonnollisista, joten ok täällä? Tai mahd. muun yläkäsitteen alla, muiden samankaltaisten kanssa ("uskonnolliset tekstit" olisi tosi monelle yläkäsite)
pyhät kirjat
Qumranin kirjoitukset
rukoukset (tuotokset)
saarnat
siunaukset (tuotokset)
sutrat
synodaalipuheet
tunnustuskirjat
uhrilahjat
uskonto (uskominen)
uskontunnustukset
virsikirjat
votiivit
Vuorisaarna

**Comment by YSO-kokous** [comment]
Jos otetaan _abstraktit kokonaisuudet_, siirretään sinne _henkimaailma_.

**Comment by satuniininen** [comment]
Päätökset toteutettu. Uskonnollisiin tuotoksiin jäi vielä seuraavat:

apokryfit
helvetti
Jumalan valtakunta
kiirastuli
päivänsanat
paratiisi
taivas
tuonela

Osa näistä on _muut paikat_ -käsitteen poiston yhteydessä siirrettyjä. https://github.com/NatLibFi/Finto-data/issues/800

Lisäksi huomasin, että YSAssa on _magia_ LT _uskomusjärjestelmät_, joten onko jotain syytä, miksei YSOssa voida tehdä samoin? https://github.com/Finto-ehdotus/YSE/issues/6031

**Comment by mariaforsen** [comment]
Yllä olevista pitäisi varmaan apokryfit ja päivänsanat siirtää.

**Comment by mirmaid** [comment]
apokryfit YK kirjalliset teokset
päivänsanat YK kirjalliset teokset - tarkistetaan eng. label
helvetti jne. > uskontoon liittyvät abstraktit objektit

Poistetaan uskonnolliset tuotokset -käsite.
