### ISSUE TITLE
laki & lait -sulkutarkenteet

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#576]
"laki (ilmiöt)"
"lait (tuotokset)"
Ilmiöitä läpi käytäessä päätettiin siirtää "laki (ilmiöt)" tuotos-puolelle (yhteiskunnalliset objektit). Tästä syystä kummankaan em. käsitteen sulkutarkenteet eivät enää ole järkeviä. Mitä tilalle?

Lisäpähkinä: pitäisikö "rikoslaki" siirtää "laki (ilmiöt)" alle, koska viittaa lakikokonaisuuteen?

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 10.6.16:

mietitään lisää, @mirmaid

**Comment by mirmaid** [comment]
Rikoslaki on laki, mielestäni ok paikassa nykyisellään.

**Comment by mirmaid** [comment]
YSO-kokous 24.3.2017:

- rikoslain nykyinen paikka ok
- yksikkö/monikko-asia käsitellään issuessa 536
