### ISSUE TITLE
Kooste: tupakka

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#577]
tupakka (nautintoaineet)
tupakka (nautintoainekasvit)

Jostain syystä jäänyt käsittelemättä. Huom! purutupakka päätettiin juuri laittaa "tupakka (nautintoaineet)"-käsitteen alle.

**Comment by mirmaid** [comment]
RATKAISU: poistetaan tupakka (nautintoainekasvit), lisätään jäljellejäävälle RT nautintoainekasvit.
