### ISSUE TITLE
Koulutusalan organisaatiot

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#578]
YSOssa LT palveluyritykset (YSAssa ei LT:tä). Ratsastuskoulut siirrettiin YSOssa käsitteen "koulutusorganisaatio" alle (YSAssa yritykset). Samassa paikassa on mm. uimakoulut, kielikeskukset, tiedekunnat jne. Autokoulut puoltanee paikkansa koulutusorganisaation alakäsitteenä yhtä hyvin kuin uimakoulut tai ratsastuskoulut.

**Comment by mirmaid** [comment]
YSO-kokous 27.5.2016

koululaitos ja korkeakoululaitos LT yhteiskunnalliset järjestelmät
leirikoulu LT leirit (?)
koulutusalan organisaatiot > prefLabel koulutusorganisaatiot
autokoulut tämän alakäsitteeksi

**Comment by MikkoAleksanteri** [comment]
Tehty.
