### ISSUE TITLE
YSA-YSO-päivityksessä viittauksia deprikoituihin käsitteisiin

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#579]
YSA-YSO-päivityksessä saattaa tulla viittauksia deprikoituihin käsitteisiin sitä kautta, että YSAssa oleva käsite on YSOn puolella jaettu koosteeksi, ja myöhemmin tämä jako on poistunut. Jos uudella YSA-käsitteellä on assosiatiivinen tai LT-suhde tämäntyyppiseen käsitteeseen niin nykyään päivityksessä liitetään molemmat/kaikki jaetut käsitteet uuden YSO-käsitteen assoksi/yläkäsitteeksi, vaikka joku näistä olisi deprikoitu.

Esim. "Newtonin lait" -käsitteellä YSOssa assosiatiivinen suhde sekä voima-käsitteeseen että "voima (fyysiset ominaisuudet)" -käsitteeseen. Jälkimmäinen on hiljattain YSOssa poistettu.

**Comment by osma** [comment]
Jatketaan seurantaa täällä: http://jira.kansalliskirjasto.fi/browse/FINTO-95
