### ISSUE TITLE
Koostekäsite: paikkaus

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#584]
RATKAISU: 

paikkaus (ylläpitävä muuttaminen) - poistetaan sulkutarkenne
paikkaus (hampaiden) > hampaan paikkaus

**Comment by tpalonen** [comment]
Deprekoin "paikkaus (hampaiden)" ja laitoin replacedby-suhteen hampaan paikkaus -käsitteeseen.
