### ISSUE TITLE
rakennukset / museot

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#585]
YSOssa on osa museoina toimivista rakennuksista museot-käsitteen alakäsitteinä (esim. Aleksis Kiven kuolinmökki), tai sen alakäsitteiden alla (kotimuseot ST Lebellin kauppiaantalo, kulttuurihistorialliset museot ST Holmin talo, taidemuseot ST Villa Gyllenberg jne.), osa taas on vain rakennuksina (esim. Ateneum). Uusia käsitteitä nyt Miinan mökki ja Kotkaniemi, joille ehdotettiin monihierarkiaa. Vastaavat pitäisi ratkaista johdonmukaisesti.

**Comment by livirtan** [comment]
Vrt. issue 559, samaa tematiikkaa

**Comment by tpalonen** [comment]
Työstän tätä paraikaa. Pieni sivuhuomio: museo on rakennuksen rooli ja saattaa muuttua. Esim. Arppeanum muuttui 2015 vuonna museosta valtioneuvoston virkamiesten toimitilaksi.

**Comment by MikkoAleksanteri** [comment]
YSO-kokous:

hyväksytään.

**Comment by tpalonen** [comment]
Entiset museot-hierarkiassa olleet yksilöt siirretty rakennuksiin ja lisätty RT-suhteet. Ehdotuksessa mainitut RT-lisäykset vielä tekemättä.

**Comment by tpalonen** [comment]
Tehty kaikki muutokset.
