### ISSUE TITLE
eläinten hierarkia

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#586]
YSOssa eläimet-käsitteen alakäsitteitä on ryhmitelty eri tavoin, esim. "eläimet käytön mukaan". Eläimet taksonin mukaan -ryhmää lukuunottamatta ainakin suurinta osaa voisi ajatella rooleina (ei kuitenkaan madot, selkärangattomat). Käyttäjää ajatellen käytännölliseltä tuntuisi sijoittaa eläimet hierarkiaan lajin, heimon, luokan tms. mukaan silloinkin kun kyse on roolista, esim. palveluskoirat, kulkukissat, kirjekyyhkyt. Ryhmittelyjen nimet eivät myöskään ole välttämättä toimivia, esim. kulkukoirat ja -kissat ovat "eläimiä käytön mukaan", muinaiseläimet ja sukupuuttoon kuolleet eläimet ovat "eläimiä elinkaaren mukaan" ja yhteiskuntahyönteiset ovat "eläimiä pesimistavan mukaan".

**Comment by MikkoAleksanteri** [comment]
YSO-kokous10.6.16:

@mirmaid tekee ehdotuksen uudesta jaottelusta tähän issueen.

**Comment by mirmaid** [comment]
Ks. myös https://github.com/NatLibFi/Finto-data/issues/724

**Comment by mirmaid** [comment]
- palveluskoirat LT koira (kuten ajokoirat)

- jos kotieläin määritellään laajasti tarkoittamaan kaikkia ihmisen huostassa olevia eläimiä (koska nyt alakäsitteenä tuotantoeläimet), voisi myös sirkuseläimet, koe-eläimet ja kirjekyyhkyt sijoittaa kotieläimiin.

- jos ryhmittelevät käsitteet jäävät, pitäisi muuttaa nimityksiä:

- eläimet elinkaaren mukaan > eläimet lajin elinkaaren mukaan

**Comment by mirmaid** [comment]
Myös metsästyshaukat, YK nyt petolinnut.

**Comment by mirmaid** [comment]
Palataan asiaan, kun hierarkisoivien käsitteiden kohtalosta on päätetty.

**Comment by mirmaid** [comment]
Mirja toteuttaa hierarkiamuutoksen.

**Comment by mirmaid** [comment]
^ Toteutin selkeitä tapauksia. 
Vielä 

- metsästyshaukat > haukat?

- kalat ja linnut elinympäristön mukaan: LT kalat, LT linnut (vaellus, paikka ja muutto eivät ole elinympäristöjä, joten vaikka tämäntyyppisiä siirtoja ei hyväksyttäisi, ne pitäisi kuitenkin nostaa LT eläimet). En ole ihan selvillä mitä eroa sillä oikeastaan on, ovatko nämä lintujen alla vai eläinten alla, hierarkian oikeellisuuden kannalta (tai sitten on muitakin epäloogisia, ovatko vinttikoirat jne. roturyhmät taksoneita, entä voivatko pienpedot ja suurpedot olla petoeläinten alla jos petoeläimet on taksoni-polussa?).

- jos kotieläin määritellään laajasti tarkoittamaan kaikkia ihmisen huostassa olevia eläimiä (koska nyt alakäsitteenä tuotantoeläimet), voisi myös sirkuseläimet ja koe-eläimet sijoittaa kotieläimiin.

**Comment by mirmaid** [comment]
- linnut ja kalat elinympäristön mukaan: siirretään YK linnut, kalat
- metsästyshaukat YK haukat
- kotieläimet: -hevoset hevosen alle. Siitoseläimet, tuotantoeläimet, sirkuseläimet, koe-eläimet eläimet käytön mukaan. Kulkukissat, kulkukoirat, lukukoirat kissan ja koiran alle. Heitteille jätetyt eläimet ja löytöeläimet YK kotieläimet.

**Comment by mirmaid** [comment]
linnut ja kalat elinympäristön mukaan: ryhmittelevä käsite deprekoitu, toimiiko ok?

Laitoin myös vetoeläimet YK eläimet käytön mukaan

Jatketaanko käsittelyä vielä tässä issuessa, vai vain osana ryhmittelevien käsitteiden yleistä läpikäyntiä?

**Comment by mirmaid** [comment]
Lisätään nyt selkärangattomat RT kaikki selkärangattomat taksonit. Lisätään editorial note selkärangattomat-käsitteelle mahdollisesta monihierarkiasta alakäsitteille myöhemmin, jos (tekninen) ongelma hierarkisoivien käsitteiden monihierarkian osalta ratkeaa.
