### ISSUE TITLE
ohjaajat

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#587]
Termi muutettu merkitykseltään kapeammaksi. Melindassa on kuitenkin käytetty paljon myös muissa merkityksissä kuin vain taiteellinen (tietty moni tulos on "opinto-ohjaajat" jne., mutta myös pelkkä "ohjaajat" löytyy paljon kun käy tarkemmin läpi). Ruotsiksi on "handledare" käytetty jopa 63 kertaa. Nyt handledare on pudonnut pois ontologian puolella (muutos huonompaan käyttäjien kannalta, varsinkin kun vastaaviakaan termejä ei ole, esim. instruktör tms.). Esimerkkejä suomenkielisen "ohjaajat"-termin käytöstä:
-Voimauttavan vertaisohjauksen käsikirja.
-Ohjaustyön opas : yhteistyössä kohti toimijuutta / Sanna Vehviläinen.
-The elements of effective student nurse mentorship in placement learning environments : systematic review and Finnish and British mentors’ conceptions / Merja Jokelainen.
-Tangon taikaa : tankotanssikulttuurin kehitys Suomessa / Carmen Kekki.
-Handledning ur handledarnas synvinkel : - en kvalitativ studie om hur handledningen upplevs och tillämpas på praktikfältet / Camilla Aspfors, Mikaela West.
-Handledning : kvalitativ studie av engelskspråkiga sjukskötarstuderandes upplevelse av praktik / Marie Erlands. (huom. ei opinto-ohjauksesta kyse)
-Ryhmänohjaus estämään nuorten syrjäytymistä / Jukka Innanen.

jne. 

Pitäisikö jakaa, että myös ohjaajat toisessa merkityksessä saadaan takaisin mukaan?

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 04.01.2016:

Käsitellään YSAn kautta, voidaanko muuttaa esim. yläkäsite ja lisätä ryhmiä?

**Comment by mariaforsen** [comment]
Ruotsin kannalta ei riitä että lisätään yläkäsitteitä tai ryhmiä, koska ruotsiksi on aivan eri termi elokuva/teatteri-merkitykselle (regissörer). Ongelma on että ruotsiksi ovat sekä handledare (KT instruktörer) että regissörer tosi tärkeitä termejä (vrt. eng. directors vs. instructors).

**Comment by mirmaid** [comment]
Muutosehdotus YSEssä https://github.com/Finto-ehdotus/YSE/issues/4792

**Comment by mariaforsen** [comment]
Käsitellään myös JUHOssa (jossa laajemmassa "handledare"-merkityksessä) YSA-päätöksen jälkeen.
