### ISSUE TITLE
kaapelointi

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#588]
On näköjään YSOssa jaettu, mutta jos halutaan pitää jakoa täytyy varmaan muuttaa kaapelointi (tekniset järjestelmät) > kaapeloinnit (tekniset järjestelmät). Palveleeko jako käyttäjiä vai vaikeuttaako? "Kaapelointi (paikalleen laittava luonti)" voi olla aika hämmentävä asiasanana ja onko jako todella tarpeen, ks. Melinda..?

**Comment by tpalonen** [comment]
Päätös 10.6.2016:
- poistetaan "kaapelointi (tekniset järjestelmät)". Jäljellejäävälle käsitteelle ei tarvitse laittaa sulkutarkenteellista altlabelia.
