### ISSUE TITLE
"taidelajit" versus "taide (erikoisala) - ero epäselvä

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#59]
_From [SNyk...@gmail.com](https://code.google.com/u/112439428317292360191/) on January 20, 2014 15:51:50_

1. What is to be changed/Mitä muutetaan "taidelajit"
"taide (erikoisala) 2. Why the change is needed/Miksi muutetaan ei selkeitä rajanvetoja käsitteiden välillä, molemmissa esim. "teatteri" ja "arkkitehtuuri"

Tausta:
YSO-päivitysmuistiinpanot 1.10.2013: kysytään Katrilta, mikä on taidelajin ja erikoisalan ero, esimerkkinä teatteri katri vastaa: ei muista, on ehkä ollut jokin ero (mediaontologia??), nyt ei toimi koska osa käsitteistä jaettu molempiin ja osa moniperinnällä (osasyy ehkä että kaikki eivät erikoisaloja)
Katri vastaa myöhemmin s-postilla: taustalla m-cult ja heidän erottelut: mcult_yso_ehdotukset_010408.doc
kumpaakaan käsitteistä ei YSAssa 3. Realized changes/Toteutetut muutokset

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=56_

**Comment by tpalonen** [comment]
Liisa Virtasen esittämä ehdotus (27.5.2015):

Taidekäsitteistö

Poistetaan: 	taiteet (ilmiöt) 
taidelajit (ei YSAssa)
taide (erikoisala)
Jää: 		taiteet 
taide 

taiteet 

LT/RT taide? LT kulttuuriset objektit? Kyse sekä toiminnasta että sen tuloksista 
(nyt taidelajit ja taide (erikoisala) ovat tapahtumat ja toiminta -osion alla, samoin tieteet)

KT taidelajit (voisi myös lisätä KT taiteenlajit) 
KT taide (erikoisala) 
KT taiteet (ilmiöt) 

ST
arkkitehtuuri
    	 maisema-arkkitehtuuri
      	 näyttelyarkkitehtuuri
      	 sisustusarkkitehtuuri
biotaide
elokuva (taiteet) KT elokuva (taide) (sulkutarkenne, jos/kun halutaan erottaa monikollisesta käsitteestä)
esinetaide
esittävät taiteet
    	esitystaide
   	musiikki KT musiikki (erikoisala), KT musiikki (taidelajit)
        	ooppera (taiteet) KT ooppera (taidelajit) (sulkutarkenne erottamaan monikollisesta muodosta)
      	sirkus (taiteet) KT sirkus (taidelajit) (sulkutarkenne erottamaan monikollisesta muodosta)
      	tanssi (taiteet) KT tanssi (erikoisala), KT tanssi (taidelajit) (sulkutarkenne
	erottamaan monikollisesta muodosta)  
     	teatteri (taiteet) KT teatteri (taidelajit), KT teatteri (erikoisala) (sulkutarkenne 
	erottamaan monikollisesta muodosta)
julistetaide (tähän grafiikan alta) RT grafiikka
kalligrafia
kansitaide
kehotaide
keramiikkataide  
kirjataide
   	(kirjamaalaus käsitteen maalaus (taiteellinen luonti) alle)
koristetaide
        	(koristemaalaus käsitteen maalaus (taiteellinen luonti) alle)
       	 ornamentiikka
korutaide
kuvataide KT kuvataide (erikoisala), KT kuvataide (taidelajit)
   	grafiikka
Menetelmät (akvatinta ym. siirretään menetelmien/painomenetelmien alle, kuten on jo tehty litografialle ja serigrafialle – näkyvät tosin virheellisesti edelleen grafiikan alakäsitteinä).
julistetaide grafiikan alta siirretään, LT taiteet, RT grafiikka
(tietokonegrafiikka ei ole grafiikan vaan tietotekniikan alla) 
kuvanveisto
    	maalaustaide
guassi -> siirretään käsitteen maalaus (taiteellinen luonti) alle, jossa on mm. akryylimaalaus
ikonitaide (Jääkö tähän vai erikseen omanaan lajinaan? Ikoneita voidaan tehdä muutenkin kuin maalaamalla, esim. mosaiikeista)
marmorointi -> siirretään käsitteen maalaus (taiteellinen luonti) alle
ootraus -> siirretään käsitteen maalaus (taiteellinen luonti) alle
pastelli -> siirretään käsitteen maalaus (taiteellinen luonti) alle
sekatekniikka -> suoraan taiteellisen luonnin alle? sekatekniikkaa on muuallakin kuin maalaustaiteessa
piirustustaide
	maalaustaide tekniikan mukaan -> pois tästä
		pastelli -> siirretään käsitteiden maalaus (taiteellinen luonti) ja piirustus alle 
	piirustustaide aiheen mukaan
		elävän mallin piirustus – on jo poistettu tästä hierarkiasta, vaikka näkyy vielä
	piirustustaide tekniikan mukaan
		pastelli -> siirretään käsitteiden maalaus (taiteellinen luonti) ja piirustus alle 
käsitetaide
lasitaide
maataide
mediataide KT mediataide (taidelajit), KT mediataide (erikoisala) 
	tietokonetaide
	verkkotaide
	videotaide	
metallitaide
mitalitaide  
musiikki KT musiikki (taidelajit), KT musiikki (erikoisala) 
paperitaide
performanssi   
postitaide
prosessitaide
rahataide 
sanataide
    	kaunokirjallisuus (alakäsitteineen) (LT:ksi myös kirjallisuus) 
sirkus (taidelajit) -> sirkus (taiteet), jos halutaan erottaa monikollisesta muodosta
	
sisustustaide
skenografia KT skenografia (taidelajit), KT skenografia (taiteellinen luonti) 
tanssi (taidelajit) - -> jää vain tanssi (taiteet), tanssi (erikoisala) poistuu
teatteri (taidelajit) - -> jää vain teatteri (taiteet), teatteri (erikoisala) poistuu
tekstiilitaide
        (silkkimaalaus vain käsitteen maalaus (taiteellinen luonti) alle)
tilataide 
tulitaide   
valokuvataide
valotaide
visuaaliset taiteet
yhteisötaide 
ympäristötaide 
äänitaide


taide
LT ”kulttuuriset kokonaisuudet”? kulttuuriset järjestelmät? kulttuuri (toimintatavat)? vai ajatellaanko tämä jatkossakin toimintaan kuuluvaksi?
ST/RT taiteet
ST 
taide aikakauden mukaan
        aigeialainen taide
        bysanttilainen taide
        esihistoriallinen taide
        karolinginen taide
        kelttiläinen taide
        moderni taide        
        nykytaide
        ottolainen taide
        primitiivinen taide (primitivismi jää paikalleen)
        sumerilainen taide

Edellä mainitut (siirretään käsitteen tyylit (ilmiöt) alta) ovat ennen kaikkea aikakauteen ja/tai paikkaan sidottuja käsitteitä (joihin luonnollisesti liittyy myös tiettyjä tyylillisiä piirteitä tai useita eri tyylejä).
art brut
Art brut, nykykansantaide, outsider art: siirtäisin nämäkin taide-käsitteen alle, sillä niiden käsitesisältö on vahvasti tekijästä määrittyvää (mikä kyllä tuo mukaan tyylipiirteitä).
interaktiivinen taide 
julkinen taide
kansantaide
    nykykansantaide
katutaide 
        katumusiikki – moniperintä? (musiikki, taide)
        katuteatteri -  moniperintä?  (teatteri, taide)
kaupunkitaide
kokeellinen taide
monumentaalitaide
outsider art
paikkasidonnainen taide
poliittinen taide
soveltava taide
sähköinen taide
uskonnollinen taide
RT prosenttitaide (LT periaatteet)

Nykyisen taidelajit -käsitteen alta siirretään seuraavat aiemmin mainitsemattomat pois:
installaatiot -> LT taideteokset (monikollisena viittaa teoksiin)
kineettinen taide > LT tyylit 
kirjallisuus (taidelajit) –> pois taidelajeista, tämä ja kaikki alakäsitteet eivät ole taidelajeja, eivät myöskään kirjallisuus (erikoisala) -käsitteen alakäsitteet, yläkäsite voisi olla kulttuuriset objektit (siellä on jo esim. kansalliskirjallisuus).   RT sanataide (jonka alla puolestaan kaunokirjallisuus)
konkreettinen taide > LT tyylit (olemassa viittaus konkretismi – kuvataide KÄ konkreettinen taide)


Taideteokset: mitä tämän alle kannattaa koota? Nyt siinä on aika vähän, otsikoksi sopisi pikemminkin kuvataideteokset. Onko taideteos rooli ?

**Comment by tpalonen** [comment]
Tein taidelajit-käsitteestä Liisan ehdottaman taiteet-käsitteet (siirsin "taidelajit" oldlabeliksi), koska se tuntui YSOssa edustavan vanhastaan parhaiten Liisan ehdotusta.

Liisan ehdottamasta poiketen tein seuraavan: kineettinen taide LT taiteet. Wikipedia: "Kineettinen taide perustuu liikkeeseen, kuten mobilet tai liikkuvia osia sisältävät veistokset ja rakennelmat." Käsite on minusta siis selvästi johdettavissa formaattiin: tehdään (veistos)taidetta liikkuvista objekteista.

**Comment by tpalonen** [comment]
Kirjallisuus, taide ja taiteet tyydyttävässä tilassa. Teen tietokonegrafiikasta erillisen issuen.

**Comment by tpalonen** [comment]
Tietokonegrafiikkaissue:
https://github.com/NatLibFi/Finto-data/issues/685
