### ISSUE TITLE
muinaisjäännökset

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#591]
Ovat nyt roolin alla, hierarkia: ominaisuudet > ulkoiset ominaisuudet > rooli (tehtävä) > muu rooli > muinaisjäännökset Parempi yläkäsite olisi esim. kulttuuriset objektit. Esim. pyramidit, sfinksit, muumiot eivät ole rooleja.

**Comment by tpalonen** [comment]
PÄÄTÖS 10.6.2016:

hautalöydöt LT löydöt + RT muinaisjäännökset
muinaisesineet LT muinaisjäännökset
muinaislinnat LT muinaisjäännökset
muumiot LT elottomat objektit + RT muinaisjäännökset
obeliskit LT elottomat objektit + RT muinaisjäännökset
pyramidit LT rakennukset rakennustyypin mukaan + RT muinaisjäännökset
riimukivet LT elottomat objektit + RT muinaisjäännökset
sfinksit LT taruolennot, yliluonnolliset olennot + RT muinaisjäännökset
suolöydöt LT löydöt + RT muinaisjäännökset
