### ISSUE TITLE
Koostekäsite: tilat

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#594]
RATKAISU: poistetaan tilat (maa-alueet), tehdään tästä muodosta kuitenkin käytä-viittaukset. Ulkotilat LT tilat. Tilat (maa-alueet) alakäsitteet YSAn nykyisen ryhmittelyn mukaan. Maatilat ja metsätaloustilat LT ihmisen määrittämä paikka.

**Comment by tpalonen** [comment]
Useimmilla "tilat (maatilat)" alakäsitteillä ei ole YSAssa yläkäsitettä. Laitoin näille kaikille LT ihmisen määrittämä paikka.
