### ISSUE TITLE
Koostekäsite: sovellukset

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#597]
RATKAISU: jaetaan:

- sovellukset (tietotekniikka)
- sovellukset (käyttötavat)

**Comment by tpalonen** [comment]
Huom! Muista jakaa myös ajoitus (ks issue #401 ) ja rajapinnat (ks issue #366 )

**Comment by tpalonen** [comment]
Nyt on kaksi käsitettä, mutta koostekäsite puuttuupi. Ajoitukselle tein saman.
