### ISSUE TITLE
YSOn hierarkisoivat käsitteet 

### ISSUE THREAD

**Issue by MikkoAleksanteri** [NatLibFi/Finto-data#601]
YSOn hierarkisoivat käsitteet on päätetty erottaa omaksi tyypikseen. 

SPARQL:

SELECT *
WHERE {
    ?subject a  yso-meta:Concept.
FILTER NOT EXISTS {?subject om:definedConcept ?object
  FILTER regex(str(?object), "^http://www.yso.fi/onto/ysa/").
 }
}

Tuloksena 227 käsitettä, lista: https://www.kiwi.fi/pages/viewpage.action?pageId=40077708. Nämä kannattanee käydä läpi suoraan TBCssä SPARQL tuloslistan mukaan. Osa varmaan halutaan jättää kuvailukäyttöön.

**Comment by tpalonen** [comment]
Fiksasin vähän tuota sparkkelia kun se ei aluksi toiminut ja päivitin tähän. Tuloksena on tosiaan paljon käsitteitä, joista vain osa  (ehkä puolet) on näitä hierarkisoivia käsitteitä. Loput ovat erilaisia eriskummallisuuksia, joilla ei syystä tai toisesta ole definedconcept-suhdetta YSAan: esim. koisokasvit, luopiot, magmakivet, permiläiset jne.

**Comment by tpalonen** [comment]
Tässä käsitteet, jotka olen muuttanut hierarkisoiviksi käsitteiksi.

aatteelliseen ryhmään liittyvä rooli
abstraktit objektit
ajanjakso
alueelliseen identiteettiin liittyvä rooli
arvoon liittyvä rooli
biologiset ilmiöt
biologiset ominaisuudet
biologiset tapahtumat
elollinen fyysinen kokonaisuus
eloton fyysinen kokonaisuus
elottomat objektit
fysikaaliset tapahtumat
fyysinen kokonaisuus
fyysiset objektit
henkilön aseman muutos
henkilön aseman muuttaminen
henkilöön liittyvä muutos
ihmisen määrittämä paikka
ihmisen määrittämät alueet
ihmisen määrittämät vyöhykkeet
ikään liittyvä rooli
järjestetyt tapahtumat
järjestävä muuttaminen
kalenteriin liittyvä ajanjakso
kasvullinen luonti
kaupankäyntiin liittyvät tapahtumat
kieleen liittyvä rooli
kielelliset ilmiöt
koneellinen luonti
kulttuuriset ilmiöt
kulttuuriset järjestelmät
kulttuuriset objektit
käyttöön liittyvä rooli
käyttöönottava muuttaminen
lopettava muuttaminen
luonnon muodostama paikka
luonnon muodostamat alueet
luonnon muodostamat vyöhykkeet
luonnontieteellinen ajanjakso
luonnontieteellinen muutos
luonnontieteelliset ilmiöt
luonnontieteelliset järjestelmät
materiaalista luonti
mentaaliset ilmiöt
mentaaliset ominaisuudet
muu ajanjakso
muu paikka
muu rooli
muut ilmiöt
muut järjestelmät
oikeudelliseen asemaan liittyvä rooli
oikeustekniset ilmiöt
oliot
opiskeluun liittyvät tapahtumat
orgaaniset objektit
paikalleen laittava luonti
paikkaan liittyvä rooli
sisäiset ominaisuudet
sosioekonomiseen ryhmään liittyvä rooli
spontaani tapahtuma
sukulaisuuteen liittyvä rooli
sukupuoleen liittyvä rooli
taiteellinen luonti
taloudelliset ilmiöt
taloudelliset tapahtumat
taloudelliset tuotokset
tapahtumat ja toiminta
tekniset järjestelmät
tekniset objektit (abstraktit objektit)
tekniset objektit (fyysiset objektit)
terveydentilaan liittyvä rooli
tiedollinen luonti
toimintaan liittyvä rooli
toisenlaiseksi muuttaminen
ulkoiset ominaisuudet
uskonnolliset ilmiöt
uskonnolliset tapahtumat
uskonnolliset tuotokset
uskontoon liittyvä objekti
uskontoon liittyvä rooli
vaikutukseen liittyvä rooli
viestintäalan organisaatio
väestöryhmään liittyvä rooli
väkivaltaiset tapahtumat
yhteiskunnallinen ajanjakso
yhteiskunnalliset ilmiöt
yhteiskunnalliset järjestelmät
yhteiskunnalliset objektit
yhteiskunnalliset tapahtumat
ylläpitävä muuttaminen
äänneopilliset ilmiöt

**Comment by tpalonen** [comment]
Tässä lista sellaisista käsitteistä, joita en merkinnyt hierarkisoiviksi käsitteiksi, koska en ollut varma, haluttaisiinko näitä kenties käyttää kuvailussa. Tässä on mm. toiminta-hierarkian pääkategorioita. Lista olisi hyvä käydä läpi ja päättää käsitteiden kohtalo.


erikoisala
hallinnollinen piiri
havainnointi ja aistiminen
keskinäinen toiminta
kielihistorialliset ilmiöt (vain yksi alakäsite)
kirjallisuuden tyylit
kulutus ja käyttö
lauseopilliset ilmiöt
liikkuminen ja liikuttaminen
liikuttaminen
luonti
matemaattiset käsitteet
muoto-opilliset ilmiöt
musiikilliset tuotokset
muuttaminen
oleminen
omana tai hallussa pitäminen
omistuksen siirtäminen
rahavarojen siirtäminen
rooli (tehtävä)
semanttiset ilmiöt
sosiolingvistiset ilmiöt
sotilaalliset organisaatiot
suhteet
taidelajit
tunteminen
yhteiskunnalliset rajoitukset

**Comment by tpalonen** [comment]
Definedconcept-suhdetta vailla olevien YSO-käsitteiden käsittely tehdään Google Drivessa.
