### ISSUE TITLE
kuvaus

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#602]
MOT:
1. valo- t. elokuvaamisesta. Opetusfilmin kuvaus. Valo-, elokuvaus. Muotikuvaus. Lähikuvaus.
2. muusta kuvantamisesta. Röntgen-, kaiku-, magneettikuvaus. Keuhkokuvaus.
3. kuvaileva esitys, kuvailu, kertomus, selostus. Sanallinen, matemaattinen kuvaus jstak. Henkilö-, matkakuvaus. Luonteenkuvaus. Toimenkuvaus. Antaa kuvaus jstak tapahtumasta.
4. fys. kuvan syntyminen optisessa laitteessa t. järjestelmässä.

Allärsissa ja Allfossa on ollut skildring, eli kolmosmerkityksessä. Englanniksi on kuitenkin valittu photography. Melindassa käytetty eri merkityksissä, etenkin 1. ja 3. Onko jako tms. tarpeen? (Melindaa katsoessa täytyy huomioida että tulee mukaan muitakin -kuvaus asiasanoja, eli tarkistaa onko asiasanana todella käytetty kuvaus vai joku muu kuvaus.) Ruotsiksi voisi ratkaista esim.: "fotografering och filmning" (visuaalinen)  ja skildring (sanallinen/kerronta), mutta jos täytyy valita vain yksi merkitys, putoaa toinen varmaan pois kokonaan.

**Comment by MikkoAleksanteri** [comment]
Lisäksi löytyy käsite

kuvailu, http://www.yso.fi/onto/yso/p334

jolla YSOssa ja YSAssa nyt hieman eri merkitykset.

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 4.1.16: 

vaatii lisäpohdintaa, Mikko alustaa seuraavaan kokoukseen

**Comment by mirmaid** [comment]
YSAan otettu myös kuvaus (liikkuva kuva), joka on päivittynyt myös YSOon. YSOn _kuvaukset (tuotokset)_ -merkitystä ei haluttu YSAan, koska sen erottamista yksiköllisestä pidettiin kuvailua ja hakua hankaloittavana.
