### ISSUE TITLE
Koostekäsite: hoito

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#603]
RATKAISU: poistetaan hoito (kunnossa pitäminen). Siirretään alakäsitteen jäljellejäävän hoito-käsitteen alakäsitteiksi. Maria listaa tähän ongelmatapaukset ja ratkaistaan niiden hierarkia erikseen.

Jäljellejäävän hoito-käsitteen pitkä alakäsitelista on sekava ja osittain hierarkia ei päde. Alakäsitteiden oikea paikka pitää selvittää erikseen.

**Comment by mariaforsen** [comment]
Nämä alakäsitteet käsitteelle hoito (kunnossapitäminen) eivät täsmää ruotsiksi:
varainhoito > taloudelliset tapahtumat/tuotokset/ilmiöt?
taloudenhoito > taloudelliset tapahtumat/tuotokset/ilmiöt?
kodinhoito > ylläpitävä muuttaminen (siellä on myös esim. puhtaanapito) tms. ?

**Comment by tpalonen** [comment]
Tehty päätetyt muutokset. Marian listaamat kolme käsitettä käytävä vielä läpi.

**Comment by mariaforsen** [comment]
Hypnoosi voisi olla LT mentaalinen toiminta. Sitä voidaan tehdä muissakin tarkoituksissa kuin hoitona jne.

**Comment by tpalonen** [comment]
PÄÄTÖS 13.6.2016:

hypnoosi LT muuntuneet tajunnantilat 
transsi LT muuntuneet tajunnantilat

Huom! Muuntuneet tajunnantilat on vasta tulossa YSOon.

Päätetään loput, kun toimintahierarkia on ratkaistu.
