### ISSUE TITLE
Koostekäsite: siirto

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#604]
RATKAISU:

hiustensiirto LT lääketieteelliset toimenpiteet
alkionsiirto, elimensiirto, ksenotransplantaatio, kudoksensiirto, verensiirto LT lääketieteelliset toimenpiteet, poistetaan LT siirto

Nyt alakäsitteiden jako on tehty suomen pohjalta, eikä vastaa ruotsin förflyttning/överföring -jakoa. Ruotsiksi voisi ajatella mahdollisuutta "förflyttning eller överföring", och ei toimi. Suomeksi on erittäin vaikeaa keksiä ruotsin jakoa vastaavia sulkutarkenteita, esim. voimansiirto, energiansiirto eivät ole viestintää (nyk. sulkutarkenne överföring-termiä vastaavalle siirto-käsitteelle).

**Comment by tpalonen** [comment]
Minun tehtäväkseni tuli esittää vastaavaa jakoa myös YSAan. Minusta kuitenkin "siirto (viestintä)" on merkitykseltään lähellä "tiedonsiirto"-käsitettä. Melinda-kuvailu on monimerkityksistä ainoastaan siinä suhteessa, että joko siirto on a) fyysistä (potilaiden siirto sairaalassa, sillan siirto) tai b) abstraktimpaa (organisaatioiden väliset toimintojen siirrot, fuusioitumiset tms, pelaajan siirtyminen joukkueesta toiseen, metsän käyttöoikeuden siirto). Mutta nämä voisi laajasti tulkiten nähdä samana käsitteenä. 

Käsitejaon säilyttämisen lisäksi toinen vaihtoehto olisikin, että YSAan ei tehtäisi kahtiajakoa, jolloin sen voisi poistaa YSOstakin, mutta lisättäisiin "siirto (viestintä)" ohjaustermiksi tiedonsiirrolle. Tässä tapauksessa kuitenkin käsitteen alakäsitteet olisi hyvä tarkistaa myös YSAn puolella.

Tai jos käsitejako säilyy niin jokin muu termi kuin "siirto (viestintä)" olisi hyvä, koska se assosioituu vahvasti tiedonsiirtoon, joka kuitenkin ontologiasta jo löytyy.

En osaa sanoa, miten tämä kuvio suhteutuu ruotsin kieleen. @mariaforsen mitä olet mieltä?

**Comment by mariaforsen** [comment]
Ruotsiksi monta eri mahdollista vastinetta, ks. esim. MOT sanakirja:
1 (siirtäminen) flyttning [-en,-ar,-arna], förflyttning [-en,-ar,-arna], överföring [-en,-ar,-arna]
2 (siirtäminen toiseen toimeen tai toimipaikkaan) förflyttning [-en,-ar,-arna], omplacering [-en,-ar,-arna]
3 (kuljetus) transport [-en,-er,-erna]
saada siirto få transport
4 (luovutus) överlåtelse [-n,-r,-rna]
hallinnansiirto överlåtelse av besittning
5 atk överföring [-en,-ar,-arna], skift [-et,=,-en]
6 tal endossement [-et,=,-en], endossemang [-et,=,-en], indossament [-et,=,-en], endossering [-en,-ar,-arna], girering [-en,-ar,-arna], cession [-en,-er,-erna]
7 tal (rahasummien siirto) transfer [-n,-,-]
8 kirjanp transport [-en,-er,-erna]
9 lääk (elimensiirto) transplantation [-en,-er,-erna]
munuaisensiirto njurtransplantation
10 lääk (verensiirto) transfusion [-en,-er,-erna]
verensiirto blodtransfusion
11 mus transponering [-en,-ar,-arna], transposition [-en,-er,-erna]
12 urh (pelaajan siirto toiseen seuraan) transfer [-n,-,-]
13 (peleissä) drag [-et,=,-en]
kahden siirron matti matt i två drag
14 kuv drag [-et,=,-en], schackdrag [-et,=,-en]
valtiovarainministerin etevä siirto ett skickligt schackdrag av finansministern
15 (vaihto liikennevälineestä toiseen) övergång [-en,-ar,-arna], omstigning [-en,-ar,-arna]
