### ISSUE TITLE
Koostekäsite: harjoittelu

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#605]
RATKAISU: poistetaan harjoittelu (taidon) ja sulkutarkenne (liikunta) jäljellejäävästä käsitteestä. Alakäsitteet siirretään kaikki jäljellejäävän käsitteen alle.

**Comment by mariaforsen** [comment]
Nyt jäivät sitten kaikki alakäsitteetkin, esim. voimaharjoittelu ja muita fyysisiä harjoitteluja tiedollisen luonnin alle...

**Comment by mariaforsen** [comment]
Miten tämä ratkaistiin? Näyttää vielä olevan yhtä virheellisenä kuin ennen.

**Comment by tpalonen** [comment]
Toiminta-hierarkian pääkategoriat on vielä päättämättä. Sopiva yläkäsite harjoittelulle löytyy siinä vaiheessa, kun pääkategoriat on päätetty. Tiedollinen luonti todennäköisesti tulee poistumaan.
