### ISSUE TITLE
Koostekäsite: pojat

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#606]
RATKAISU: pojat (ikään liittyvä rooli): vaihdetaan sulkutarkenteeksi (ikäryhmät), LT lapset (ikäryhmät) ja sukupuoleen liittyvä rooli. 

Pojat (perheenjäsenet) on ok.

**Comment by tpalonen** [comment]
Muutin myös "lapset (ikään liittyvä rooli)" muotoon "lapset (ikäryhmät)".
