### ISSUE TITLE
Koostekäsite: arvo

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#610]
RATKAISU:
raja-arvo LT matemaattiset käsitteet. Siirretään tänne myös keskiarvot, likiarvot, ominaisarvot, ääriarvot.

ohjearvot, raja-arvot, säätöarvot LT tieto

goodwill...verotusarvo + rasva-arvot, ravintoarvo, tunnearvo LT arvo (ominaisuudet)

Poistetaan käsite arvo (tieto).

**Comment by tpalonen** [comment]
Keskiarvot-käsitteen luoman analogian inspiroimana ja Mirjan kanssa alle minuutin aiheesta palaveerattuani siirsin samassa paikassa (LT numeeriset menetelmät) olleen mediaanit-käsitteet myös LT matemaattiset käsitteet.

**Comment by mariaforsen** [comment]
Sanastossa on nyt sekä arvo että arvot ilman mitään tarkenteita, onko kaikille yksikkö/monikko-muodon perusteella selvää mihin viittaavat? Ruotsiksi ei ainakaan välttämättä ole niin. Näissä tapauksissa olemme muistaakseni ennen laittaneet sulkutarkenteita, ainakin yksikkömuodolle.

**Comment by tpalonen** [comment]
Issuessa #536 tehtiin jonkunlainen linjaus. Tosin siitä ei kirjattu oikeastaan mitään järkevää sääntöä ylös. Päätettiin kuitenkin, että vastaanotto ja vastaanotot tarvitsevat sulkutarkenteet ja merkintä vs. merkinnät taas ei tarvitse. Jälkimmäisessä yksikkömuoto viittaa selkeästi toimintaan ja monikko toiminnan tulokseen, vastaanotto-esimerkissä yksikkö-monikko-ero ei muodosta tällaista merkityseroa. Arvo/arvot-ero ei minunkaan mielestäni ole suomeksikaan selvä, joten olen sulkutarkenteiden kannalla.

**Comment by mariaforsen** [comment]
Issue on suljettu, mutta onko päätetty arvo/arvot-asiasta jotain?

**Comment by tpalonen** [comment]
Sulkutarkenteet käsitellään toisessa issuessa: https://github.com/NatLibFi/Finto-data/issues/536
