### ISSUE TITLE
tekniikka (tieteet), tekniikka (laitteet), tekniikka (menetelmät)

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#611]
YSO-kokoukseen. Lähes mahdoton sanoa milloin kyse on vain tai lähinnä jostain jaetun käsitteen merkityksistä. Esim. analogiatekniikka voisi kuulua kaikkiin kolmeen?

**Comment by tpalonen** [comment]
Tästä on kyse. On siis kolme eri tekniikkaa:

1) tekniikka (erikoisalat)

Tämän alakäsitteenä:
    avaruustekniikka
    biotekniikka
    elintarviketekniikka
    geotekniikka
    hammastekniikka
    jäähdytystekniikka 
    jne.

2) tekniikka (laitteet)

Tämän alakäsitteenä:
    esitystekniikka
    huipputekniikka
    kodintekniikka
    näyttämötekniikka 
    jne.

3) tekniikka (menetelmät)

Tämän alakäsitteenä:
    analogiatekniikka
    digitaalitekniikka
    découpage
    galvanotekniikka
    hybriditekniikka
    jne.

**Comment by mariaforsen** [comment]
Ainakin tekniikka (erikoisala) pitäisi varmaan poistaa tai mahdollisesti muuttaa sana kokonaan (tekniikka-ala tms.). Pelkästään sana "teknik" itsessään ei ainakaan ruotsiksi ole mikään ala.

**Comment by tpalonen** [comment]
**Ehdotus**
Step 1: Poistetaan "tekniikka (menetelmät)" ja siirretään sen alakäsitteet tapauskohtaisesti muualle, esim. käsitteiden "tekniikka (tieteet)" tai "menetelmät" alle.
Step 2: Siirretään "tekniikka (tieteet)" pykälää ylemmäs hierarkiassa eli YK yhteiskunnalliset järjestelmät. Muutetaan käsitteen preflabel muotoon "tekniikka (yhteiskunnalliset järjestelmät)" tai jokin yksinkertaisempi sulkutarkenne.

**Perusteluja**
- Yksinkertaistamalla jakoa helpotetaan sisällönkuvailijan ja tiedonhakijan työtä.
- Käsite "tekniikka (tieteet)" viittaa tekniikkaan toimialana. "Tekniikka (menetelmät)" taas viittaa teknikkaan hengentuotoksena, keksintönä. Käsitteinä nämä ovat vahvasti päällekkäiset: kun sovelletaan jotakin teknistä menetelmää (esim. lasertekniikka, äänitekniikka), samalla toimitaan myös kyseisellä teknisellä toimialalla.
- Ne menetelmät-käsitteet, jotka selvästi viittaavat toimintapaan pikemmin kuin teknologiaan (esim. muistitekniikat, valmistustekniikka, tanssitekniikat) voitaisiin siirtää myös suoraan menetelmät-käsitteen alle, mikä vähentäisi "tekniikka (menetelmät)"-käsitteen tarvetta hierarkkisena käsitteenä.
- Siirtoa menetelmistä tieteeseen puoltavat myös englannin vastineet: "tekniikka (tieteet)" on käännetty "technology (sciences)" ja "tekniikka (menetelmät)" termillä "technique".  Menetelmät-hierarkiassa on kuitenkin 16 alakäsitettä, jotka ovat muotoa technology, kun taas "tekniikka (tieteet)" puolella ei ole yhtään technique-päätteistä käsitettä (löytyy tosin pyrotechnics).
- Olen itse ehdottanut toisaalla, että menetelmät-hierarkiasta poistettaisiin kaikki muut paitsi *
menetelmät-loppuiset käsitteet. Tässä esitetty ehdotus olisi linjassa kyseisen ehdotukseni kanssa.
Ks: https://github.com/NatLibFi/Finto-data/issues/81
"Menetelmät -käsitteen ja analyysimenetelmät ym. alle vain ne käsitteet, jotka ovat muotoa *menetelmät. Muut käsitteet toimintaan tai olioihin. Tämän jälkeen menetelmät-käsite ja sen alakäsitteeksi jääneet *menetelmät voisi siirtää LT yhteiskunnalliset objektit."

**Comment by mirmaid** [comment]
Tekniikka menetelmänä on paljon käytetty kuvailussa, joten vaikka se olisikin hierarkian kannalta tarpeeton, jotain pitäisi tehdä kaikille viitteille jotka käsittelevät esim. käsityön, näyttelemisen tai kurkkulaulun :-) tekniikoita. Voidaan toki selvittää onko korvattavissa menetelmät-termillä. Monikko sopisi tässä merkityksessä usein.

**Comment by mirmaid** [comment]
Tekniikka tieteenä on hyvin lähellä teknologia-käsitettä, olisikohan näiden yhdistäminen jollain tavalla mahdollista? Myös teknologia pitää sisällään "laite"-merkityksenkin, mutta onko (laitteet) enää tarkenteena tätä päivää? Varmaankin voi olla myös tietokoneohjelmia? Kuvailussa ei termi tekniikka (laitteet) tunnu kovin tarpeelliselta (pelkkä laitteet varmaan riittäisi).

**Comment by tpalonen** [comment]
Eli ehdotat että jäisi kaksi käsitettä?
- tekniikka/teknologia [kumpi sitten valitaankaan preffiksi]
- tekniikka menetelmänä

Miksipäs ei. Tosin voi näyttää hassulta, että *tekniikka-loppuisilla on yläkäsitteenä teknologia, tai toisinpäin. Mutta toisaalta monilla *tekniikka-loppuisilla on altlabelina *teknologia (biotekniikka, geenitekniikka, nanobiotekniikka, kemian tekniikka, muovitekniikka jne) ja sama tilanne myös *teknologia-loppuisilla (energiateknologia, geroteknologia, hyvinvointiteknologia, puuteknologia ja ympäristöteknologia). Eli tämä molempien termien esiintyminen yhdessä monissa käsitteissä kyllä näyttäisi tukevan ehdotustasi. 

Tekniikka/teknologia-käsitteen yläkäsite voisi olla tekniset järjestelmät.

**Comment by mirmaid** [comment]
Pitäisikö vielä selkeyttää? Vrt. alakäsitteet tekniikat vs. teknologia.

**Comment by mariaforsen** [comment]
Kaikki -tekniikka loppuiset tekniikat:in alakäsitteet pitäisi varmaan siirtää muiden -tekniikkaloppuisten termien sekaan teknologian alle?

**Comment by jarmosaarikko** [comment]
https://www.kielitoimistonsanakirja.fi/#/tekniikka?searchMode=all
- 3.  jnk valmistuksessa t. suorittamisessa käytettävä menetelmä, teko- t. suoritustapa; teko- t. suoritustaito.

**Comment by mirmaid** [comment]
analogiatekniikka, digitaalitekniikka YK teknologia

Ei siirrettäviä:
kauppatekniikka
kokoustekniikka
muistitekniikat
opiskelutekniikka
puhetekniikka
sävellystekniikat
tanssitekniikat
valmistustekniikka

neulakinnastekniikka YK neulonta KT kinnasompelu (päätermin muutos?)
vesisärötys YK kohdistuva toiminta

tyhjiötekniikka YK teknologia
kryoniikka YK teknologia

tutkimustekniikka > issue (miten käytetty, mihin viittaa, termimuoto)

**Comment by mirmaid** [comment]
Pohjustukseksi vielä: aikaisemmin oli siis kolme tekniikka-käsitettä, joista nykyinen "tekniikat" vastaa käsitettä "tekniikka (menetelmät)". Teknologia puolestaan sisältää aikaisemmat "tekniikka (tieteet)" ja "tekniikka (laitteet)" -käsitteet. 

Teknologian nykyisissä alakäsitteissä on suunnilleen ajateltu, että alkuosa kertoo, minkä alan teknologia/tekniikka on kyseessä, eli hammastekniikka tai metsäteknologia ovat tekniikkaa, jonka kohdealana on hampaat tai metsä. Sitten taas tekniikat-käsitteen alakäsitteissä alkuosa kertoisi menetelmän, jolla jotain tehdään, eli esim. kalvotekniikka ei ole kalvoihin kohdistuvaa vaan kalvojen avulla toteutettavaa ja analogiatekniikassa samoin kyse on menetelmästä vs. digitaalitekniikka jne. 

Ongelmana tässäkin jaossa on tietysti, että nämä menevät sekaisin käytännössä, kuten kävi ilmi tyhjiötekniikan suomen- ja englanninkielisistä wikipediasivuista. Tai siitä, että nanotekniikka ja mikrotekniikka ovat eri paikoissa - nanotekniikanhan voi nähdä kohdistuvan nanorakenteisiin, tai tekevän asioita niiden avulla.

**Comment by mirmaid** [comment]
Jos nyt tehdään niin, että tekniikat-käsitteen alle jäävät vain ne, joihin ei sisälly teknologian häivääkään, on varmaan hyvä siirtää muualle myös kaikki ei-tekniikka-päätteiset, eli kirjataan tähän:

animaatio
découpage
intarsia
kryoniikka
liikkeenkaappaus
montaasi
nestaus
vesisärötys

**Comment by mirmaid** [comment]
Tässä samalla huomasin, että käänteisosmoosi on livahtanut erotusmenetelmien alle, siellä ei ole muita erotusmenetelmiä...
