### ISSUE TITLE
penikkatauti

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#612]
Kaksi eri merkitystä, ks. esim. Lääketieteen termit. Ruotsiksi eri termejä riippuen merkityksestä. Tarvitseeko jakaa tms. vai riittäisikö esim. huomautus siitä että käytetään vain eläinlääk. merkityksessä? Melindassa käytetty pari kertaa myös ihmisten kohdalla. Koska nämä taudit/oireet ovat aivan eri asioita  on tärkeää ettei käytetä sekavasti.

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 4.1.16:

Tulee varmasti jakaa, viedään YSAan.

**Comment by mirmaid** [comment]
Muutosehdotus YSEssä https://github.com/Finto-ehdotus/YSE/issues/4788

**Comment by mirmaid** [comment]
Hyväksytty penikkatauti (eläintaudit) ja penikkatauti (rasitusvammat) (YSA-kokous 7.3.2017).
