### ISSUE TITLE
yhtäläissiipiset

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#613]
Onko tämä Zygoptera vai Homoptera? Eri termivaihtoehtoja ruotsiksi. Jos Zygoptera: jungfru- och flicksländor, jos Homoptera: växtsugare. Motkin antaa ristiriitaisia tietoja (vrt. ruotsi, englanti, suomi). Wikipediassa väitetään että "Hentosudenkorennot (Zygoptera), aikaisemmalta nimeltään yhtäläissiipiset" http://fi.wikipedia.org/wiki/Hentosudenkorennot Nyt englanniksi damselflies (eli Zygoptera) ja yläkäsite sudenkorennot, mutta esim. YSA:ssa alakäsitteinä kaskaat, kempit, kirvat, eli Homopteran mukaan. Allärsissa växtsugare (Homoptera), mutta Allfossa Zygopteraan viittaava vaihtoehto.

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 4.1.2016

->selvitetään Melindan merkitykset ja päätetään sitten, Tuomas selvittää

**Comment by tpalonen** [comment]
Melinda-käytössä viitattu selvästi enemmän Homopteraan (11 kertaa) kuin Zygopteraan (2 kertaa).

**Comment by tpalonen** [comment]
Mirja selvittää.

**Comment by mirmaid** [comment]
Myös laji.fi:n mukaan zygoptera=hentosudenkorennot. Homopteraa ei ole, wikipedian mukaan se on korvattu kolmella uudella ryhmällä. Muutetaan YSAssa muotoon hentosudenkorennot ja korjataan Melindan viitteet.
