### ISSUE TITLE
YSAn ketjuista hiddenLabelit

### ISSUE THREAD

**Issue by osma** [NatLibFi/Finto-data#614]
YSAn paikoissa ja joskus muissakin termeissä käytetään ketjuja, esim. "Helsinki -- Kontula". VESAssa tällaisia pystyi hakemaan esim. "helsinki k*" mutta Fintossa pitää käyttää täsmälleen tuota ketjullista kirjoitusasua eli "helsinki -- k" jotta sama löytyisi.

YSAan voisi lisätä hiddenLabeliksi ketjuja sisältäville termeille version termistä ilman väliviivoja, siis esimerkiksi "Helsinki Kontula". Tämän voisi tehdä jo MARC-SKOS-muuntimessa.

**Comment by mariaforsen** [comment]
Sama juttu toteutettu näköjään Allärsinkin kohdalla, hienoa!
