### ISSUE TITLE
metsästys/kalastus 

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#616]
On nyt jaettu: metsästys (alkutuotanto) + metsästys (pyynti). Tämä on ruotsiksi lähinnä ketjutusta ja vaikeuttaa käyttäjille. Miksi on jaettu ja voisiko jaon purkaa?

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 4.1.16:

poistetaan "metsästys (alkutuotanto)" ja ohjataan jäljelle jäävään. Poistetaan myös kooste. Poistetaan jäljelle jäävältä sulkutarkenne.

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 4.1.16:

tehdään sama käsiteille "kalastus (XXX)", kaikki alakäsiteet jäljellejäävän alle
