### ISSUE TITLE
tagalog vs. tagalogin kieli, samaa tarkoittavat käsitteet?

### ISSUE THREAD

**Issue by osma** [NatLibFi/Finto-data#617]
Huomasin, että YSOssa on ilmeisesti tagalogin kieli kahteen kertaan:
http://dev.finto.fi/yso/fi/page/p1677 "tagalog"
http://dev.finto.fi/yso/fi/page/p26322 "tagalogin kieli"

Näistä edellä mainitun linkit YSAan ja Allärsiin ovat rikki. Tulkitsen, että YSAsta ja Allärsista nämä tuplat on poistettu mutta YSOon on jäänyt kaksi samaa tarkoittavaa käsitettä. Pitäisi varmaan poistaa näistä toinen.

Liittyy mahdollisesti issueen #252 josta en kuitenkaan ymmärtänyt mitä siinä on tehty tai päätetty.

**Comment by tpalonen** [comment]
"Tagalog" poistunut YSOsta.
