### ISSUE TITLE
Koostekäsite: joukkueet

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#618]
Jostain syystä ei ole ollut käsiteltävien listalla koostekäsitekokouksissa.

joukkueet (sotilasosastot) [sv: plutoner]
joukkueet (urheilu) [sv: lag (grupper]

Joukkueet (urheilu) käsitteellä kaksi alakäsitettä. Joukkueet (sotilasosastot) käsitteellä ei YSA-ryhmiä.

**Comment by mariaforsen** [comment]
Vaatii eri termejä ruotsiksi ja kai suomeksikin on tärkeää pitää nämä erillään..?

**Comment by mirmaid** [comment]
Jaettu YSAssa, huom. defined concept -suhteet.

**Comment by tpalonen** [comment]
En löydä YSAsta kuin yhden joukkueet.

**Comment by mariaforsen** [comment]
Tässä täytyy ehkä täsmentää että "joukkueet (urheilu)" toki jo löytyy terminä "urheilujoukkueet", mutta mikä tahansa joukkue (muu kuin urheilu tai sota) ei ole. Se on ruotsiksi "lag". Allärs: joukkueet = lag (grupper) + plutoner.

**Comment by mirmaid** [comment]
Jaettu YSAssa.

**Comment by mirmaid** [comment]
Joukkueet jaettu, urheilujoukkueet poistettu.
