### ISSUE TITLE
verkkourkinta LT

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#619]
Nyt yläkäsite: havainnointi ja aistiminen. Olisiko parempi yläkäsite esim. rikokset, huijaus tai petos? Nykyinen varmasti outo käyttäjien silmissä.

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 4.1.16:

nostetaan yhtä tasoa ylemmäksi eli LT keskinäinen toiminta
