### ISSUE TITLE
Käsite "Arvosanat" monimerkityksinen

### ISSUE THREAD

**Issue by satuniininen** [NatLibFi/Finto-data#623]
Käsitteessä huomautus: Arvosana on joko arvosteluasteikon yksikkö tai tietty kurssi jossakin korkeakoulun oppiaineessa.

MOT: arvosana
1. arvosteluasteikon yksikkö, tällaisella esitetty arvostelu. Yleisarvosana. Kouluarvosanat. Arvosana 9. Arvosana laudatur. Saada kiitettävä, hyvä, huono arvosana.
2. tietty kurssi vars. jssak korkeakoulun oppiaineessa; sen vaatima tutkinto. Suomen kielen laudatur-arvosana. Suorittaa arvosana kasvatustieteessä. 

MOT Korkeakoulusanasto:  
fi: arvosana  
Selite: Yliopiston opintokokonaisuus: perusopinnot, aineopinnot tai syventävät opinnot.  
en: study block
Selite: Termillä myös merkitys 'suoritusarvio' jolloin käännös on "grade". 

Melindassa käytetty kouluarvosana-merkityksessä, joten käännetty englantiin "grades".

Pitäiskö huomautus muuttaa ja rajata käyttö ykkösmerkitykseen?

**Comment by mariaforsen** [comment]
Kannatan rajausta ykkösmerkitykseen, ruotsiksi ei ole myöskään vastaavaa kakkosmerkitystä.

**Comment by tpalonen** [comment]
PÄÄTÖS 13.6.2016

poistetaan YSAn kautta

**Comment by mirmaid** [comment]
Huomautus poistettu YSAssa ja YSOssa.
