### ISSUE TITLE
Kooste: Ellipsit ja sterilointi

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#625]
Nämä kaksi koostejakoa säilytetään YSOssa. Nämä jaetaan myös YSAssa. Defined concept -suhteet pitäisi siis merkata oikeisiin YSA-käsitteisiin. Ei muuta.

ellipsit (geometriset kuviot)
ellipsit (kielelliset ilmiöt)

sterilointi (lääketieteelliset toimenpiteet)
sterilointi (puhdistaminen)

**Comment by mirmaid** [comment]
Kooste-käsite varmaan poistetaan myös?

**Comment by tpalonen** [comment]
Suhteet kunnossa ja kooste poistettu.
