### ISSUE TITLE
harjoitusmenetelmät ja joogan alakäsitteet

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#626]
Päätettiin poistaa (ks. https://docs.google.com/spreadsheets/d/1YK1cWueZvd7JKcQR3OFolPDz8JoQceAqhP2sD_gmQ50/edit#gid=934204703). 

Varsinkin ala-käsite jooga on ongelmallinen sijoittaa koska on oikeastaan "monimerkityksinen" (alun perin filosofinen/uskonnollinen "oppisuunta", johon kuuluu vain osana fyysinen puoli, mutta nykyään varsinkin länsimaissa myös lähinnä fyysistä harjoittelua (riippuu joogalajista). Monihierarkia olisi juuri tämän termin kannalta hyvä: LT liikunta ja LT itämainen filosofia (jooga on osa intialaista filosofiaa), mutta esim. unijooga taas ei ole liikuntaa. Jooga LT harjoitukset (joogassa yleisemmin on sekä mentaaliset että fyysiset harjoitukset tärkeitä) voisi olla hyvä ratkaisu ja tämän alle sopisivat myös joogan alakäsitteet . Myös jako kahteen termiin: "jooga (intialainen filosofia)" ja "jooga (liikunta) voisi olla mahdollinen vaihtoehto, mutta se ei vielä ratkaise esim. unijoogan sijoitusta. Eli termin sijoittaminen harjoitusten alle olisi ehkä paras vaihtoehto. 

Kum nye voi sisältää sekä liikkeitä, hierontaa, rentoutusta yms., mutta on myös osa tiibetiläistä lääketiedettä ja voi toimia hoitomenetelmänä. Harjoitukset voisi olla ok LT (länsimaissa usein nimenomaan liikkeitä jne.)

Asahi on selvästi liikunnallista (vaikka siihenkin kuuluu mielikuvien avulla työskentely), joten LT voisi olla liikunta. Jos korostetaan myös "mentaalisia osia" voisi LT olla harjoitukset.

**Comment by tpalonen** [comment]
YSO-kokouksessa päätettiin 1.7.2015 säilyttää harjoitusmenetelmät. Alakäsitteille voisi kuitenkin olla parempia paikkoja hierarkiassa. Selvitettävä.

**Comment by mirmaid** [comment]
YSO-kokous 16.10.2015

- asahi, kum nye, taiji LT terveysliikunta
- jooga LT kulttuuriset tuotokset

**Comment by MikkoAleksanteri** [comment]
16.10. päätökset toteuteuttu dataan.

Pitäisi vielä mittiä joogan alakäsitteet, tulisiko esim. nauru- ja unijooga siirtää jonnekin muualle?

**Comment by mirmaid** [comment]
YSO-kokous 23.10. 
- naurujooga LT terveysliikunta, RT jooga
- muut alakäsitteet jätetään paikalleen
