### ISSUE TITLE
erikoisala 

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#627]
Onko erikoisala todella sopiva sana esim. näissä tapauksissa: kirjallisuus (erikoisala), musiikki (erikoisala), oikeus (erikoisala), taide (erikoisala), tieteet (erikoisala), tekniikka (erikoisala)..? Ks. MOT: "erikoistumista vaativa ala, spesialiteetti. Lääketieteen erikoisalat." Ainakin ruotsiksi (specialområde) on tämä termi ongelmallinen käyttää tällä tavalla. Jako voi olla ok (ainakin joissakin tapauksissa), mutta nyt ei ole välttämättä selvää käyttäjille mihin tällaiset oikeasti viittaavat. Erikoisala-termi itsessään on myös muutettu monikkoon ja nämä sulkutarkenteetkin pitäisi varmaan muuttaa monikkoon jos suomeksi halutaan silti tätä termiä käyttää.

**Comment by tpalonen** [comment]
Musiikissa ja taiteessa ei ole enää tuota erikoisalaa sulkutarkenteena. Ks. #59

**Comment by tpalonen** [comment]
Muutin suomenkieliset monikkoon. En kuitenkaan laittanut yksikkömuotoa oldlabeliksi, koska se ei tässä tunnu palvevan käyttäjää millään tavalla.

**Comment by mirmaid** [comment]
YSO-kokous 16.10.2015

- oikeus (erikoisalat) LT yhteiskunnalliset järjestelmät. Muutetaan sulkutarkenne muotoon (oikeudenala).
- politiikka LT yhteiskunnalliset järjestelmät
- taide LT kulttuuriset järjestelmät
- teollisuus LT yhteiskunnalliset järjestelmät
- tieteet LT yhteiskunnalliset järjestelmät
- toimialat LT yhteiskunnalliset järjestelmät

- poistetaan käsite erikoisalat

**Comment by MikkoAleksanteri** [comment]
Toteutettu dataan. Lisätty poistetulle "erikoisalat"-käsitteelle yso-meta:deprecatedReplacedBy "yhteiskunnalliset järjestelmät"
