### ISSUE TITLE
pohjoinen ulottuvuus

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#629]
On nyt aloitteet käsitteen alla. Siitä tehtiin 90-luvulla aloite, mutta kyllä se nykyään näyttää lähinnä yhteystyöltä. Ks. http://formin.finland.fi/public/default.aspx?nodeid=15579&contentlan=1&culture=fi-FI

**Comment by mirmaid** [comment]
YSO-kokous 16.10.2015

LT yhteiskunnalliset järjestelmät
