### ISSUE TITLE
käsitteet palvelut (toiminta) ja palvelut (tuotokset) ja niiden alakäsitteet

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#63]
_From [SNyk...@gmail.com](https://code.google.com/u/112439428317292360191/) on January 20, 2014 16:04:10_

1. What is to be changed/Mitä muutetaan käsitteet palvelut (toiminta) ja palvelut (tuotokset) ja niiden alakäsitteet 2. Why the change is needed/Miksi muutetaan YSAssa vain yksi, jonka kaikki alakäsitteet dumpattu palvelut (toiminta)-alle ilman käsiteanalyysiä 3. Realized changes/Toteutetut muutokset

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=60_

**Comment by mirmaid** [comment]
Ratkaistu issuessa 390.
