### ISSUE TITLE
muinaiskansat: ainoa yläkäsite "muinaiskansaan liittyvä rooli" on deprekoitu

### ISSUE THREAD

**Issue by osma** [NatLibFi/Finto-data#630]
muinaiskansat-käsitteen (http://www.yso.fi/onto/yso/p14665) ainoa yläkäsite "muinaiskansaan liittyvä rooli" on deprekoitu, pitäisi varmaankin keksiä sille jokin muu yläkäsite.

**Comment by tpalonen** [comment]
Fixed
