### ISSUE TITLE
Koostekäsite: sidonta

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#635]
RATKAISU: jätetään vain 1 sidonta. YSAssa lisätään soveltuvat KÄ-viittaukset hiilensidonta, kirjansidonta ja kukkien sidonta -termeille. LT järjestävä muuttaminen.

**Comment by mariaforsen** [comment]
Molemmat on näköjään vahingossa poistettu..

**Comment by tpalonen** [comment]
Kappas! Hyvä kun huomasit! Korjasin.

**Comment by mirmaid** [comment]
Tähän liittyen, Melindassa käytetty muutaman kerran lyijyn sidonta, fosforin sidonta ja pölyn sidonta. 
_Puujauhon käytön arviointi soratien pölynsidonnassa_ 
_Tagungsband zum Workshop über den wissenschaftlichen Erkenntnisstand über das Feinstaubfilterungspotenzial (qualitativ und quantitativ) von Pflanzen am 1. Juni 2007 in Berlin/Adlershof_
_Abatement of phosphorus- and lead-induced environmental risks by means of apatite ore mine tailings_
