### ISSUE TITLE
abduktio

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#638]
YSOssa on vielä myös abduktio -- filosofia (poistettu YSAsta)  > pitäisi varmaan poistaa. Onko silti ongelmallista vielä se että pelkkä abduktio-termille ei myöskään ole minkäänlaista tarkennetta tai selitettä, varsinkin kun luokka on 00 (tosin 02 YSAssa). Abduktio on monimerkityksinen, mm. lääketieteellinen ilmiö.

**Comment by mirmaid** [comment]
YSO-kokous 16.10.2015

Vaihdetaan luokaksi 02.
