### ISSUE TITLE
stabiilius, vakavuus, vakaus

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#639]
Minusta ratkaisu ei edelleenkään ole kovin toimiva. Ainakaan kun katsoo käyttöä Melindassa. Siellä stabiilius käytetään paljon nimenomaan fysikaalisena asiana. Nyt se on LT mentaaliset ominaisuudet YSOssa, ja sen mukaan on siis ruotsinkin vastine valittu. Vakauskin on käytetty Melindassa enemmän kuvannollisena (esim. talous..) vaikka YSOssa on LT fyysiset ominisuudet ja ruotsin vastine valittu sen mukaan. 

MOT esim: 
1.vakaus: vakaaminen. 
2. vakaus: vakavuus, stabiilius. Kemiallinen vakaus. 

Ja Motin eri sanakirjojen sekä muun logiikan mukaan tulisi oikeastaan 3 kertaa stabilitet ruotsiksi. Eli kaikki nämä yllä olevat olisivat stabilitet, mutta miten erotella, millaisilla sulkutarkenteilla, kun käyttö näyttää olevan päällekkäinen suomeksi? 

Esim. nykyinen stabilitet (mentala egenskaper) antaisi käyttäjille ihan väärän tuloksen, kun se on kuitenkin käytetty fyysisenä Melindassa. 

Olisiko mitenkään mahdollista tehdä esim. stabiilius/vakaus, korvattu termi: vakavuus. Näin olisi enää kaksi stabilitet. Yhtä sekasortoa tällä hetkellä ja varsinkin kun miettii mitä hakutuloksia tulisi kielten välisillä hauilla.

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 4.1.16:

vaatii selvittelyä myös YSAn puolella, ks. esim. vakauden ohjaustermi ym.

**Comment by mirmaid** [comment]
Mentaalinen ominaisuus -merkitys on ainakin Melindan perusteella tarpeeton (ja kuulostaakin aika kummalliselta).

**Comment by mirmaid** [comment]
Näitä tosiaan käytetään hankalasti ristiin, vaikka merkityskentissä on eroja: toisaalta fysiikka (esim. kulkuneuvon vakaus) tai abstraktimmin tilanteen pysyminen muuttumattomana, politiikkaan ja talouteen mutta myös kemialliseen koostumukseen. Lääketieteessä potilaan tila voi olla stabiili, mutta sama termi voi liittyä liikkumiseen tai kivun kokemiseen.

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: **vakaa**:
1. aloillaan, paikallaan kestävästi pysyvä, vankka, tukeva, horjumaton, heilumaton, liikahtamaton, stabiili. _Vakaata kättä ja tarkkaa silmää vaativa työ. Vakaa tasapaino. Ohjattavuudeltaan vakaa auto. Suuntavakaa. Aluksen kulku oli vakaata. Seisoa vakaana, vakaassa asennossa._
2. pysyvä, vakiintunut, muuttumaton, varma. _Vakaat olot. Vakaa kehitys. Vakaa hintataso, rahan arvo. Taloudellisesti vakaa asema. Edustaa vakaata poliittista linjaa._
3. rauhallinen, maltillinen, tyyni, tasainen; jäyhä; luja, johdonmukainen, vankkumaton. _Vakaa suomalainen talonpoika. On siinä vakaassa uskossa, että – –. Vakaa käsityksemme on, että – –. Vakaana aikomuksenani oli – –. Tämä on vakaa päätökseni._

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: **vakava:**
1. totinen, tosissaan oleva; nauramaton; syvällinen (pinnallisen, hilpeän, kevyen tms. vastakohtana); vakaa (3), vakavamielinen. _Kuoleman-, haudanvakava. Koetti pysyä vakavana, vaikka nauratti. Yleisö kuunteli puhetta vakavana. Vakava ilme. Vakavat kasvot. Vakavassa mielessä tehty ehdotus. Vakava varoitus. Elämän vakavat puolet. Näytelmän vakava sanoma. Kiinnittää jhk vakavaa huomiota. Ottaa asia vakavalta kannalta suhtautua asiaan vakavasti. Vakava musiikki taidemusiikista. Vakava kristitty. Vakava arvokkuus._
2. paha, ankara; huolestuttava; vaikea, tukala; vaarallinen, kohtalokas. _Vakava erehdys. Vakava syytös, haaste, vahinko, välikohtaus. Vakava sairaus. Sairaus sai vakavan käänteen. Tilanne on muuttunut yhä vakavammaksi. Valtiontalouden tila on vakava. Laiminlyönnistä voi olla vakavia seurauksia._
3. tavallisemmin: vakaa (1).

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: **stabiili:**
vakaa, varma, vankka, kiinteä, pysyvä, horjumaton. Stabiili tasapaino. Stabiili markkinatilanne.

**Comment by mirmaid** [comment]
Jätetäänkö kaikki samaan: vakavuus, vakaus KÄ stabiilius (TAI vakavuus, stabiilius KÄ vakaus)?

Jos jaetaan, onko esim. _vakaus (fysiikka)_ ja _stabiilius (muuttumattomuus)_ ok? Voin kyllä kuvitella ettei ole aina täysin toimiva, mutta tähän tuskin löytyy laajasti hajoavan käytön takia mitään tieteenala-tyyppistä tarkennetta (tai sitten tarvitaan useita: "yhteiskunta", "talous", "lääketiede", "tietoliikennetekniikka", "kemia").

**Comment by mariaforsen** [comment]
Tämä olisi ok ruotsin osalta.

**Comment by YSO-kokous** [comment]
Tehdään YSE-ehdotus, jossa ensisijaisesti ehdotetaan käsitteiden yhdistämistä ja toissijaisesti Mirjan edellä esittämää kahtiajakoa.
