### ISSUE TITLE
lääkemääräykset

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#640]
Ruotsiksi läkemedelsordinationer (recept). LT on nyt määräykset / bestämmelser, ei toimi ruotsiksi. Ei ole samalla tavalla määräys kuin muut ST eli kaavamääräykset, rakentamismääräykset, turvallisuusmääräykset (se että on resepti ei velvoita silti mihinkään). Ruotsiksi voisi olla asiakirjojen (missä myös esim. lähetteet) tms. alla.

**Comment by mirmaid** [comment]
YSO-kokous 16.10.2015

LT asiakirjat
