### ISSUE TITLE
viitat ST ponchot

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#641]
Ei toimi ruotsiksi. Poncho: rektangulärt tygstycke (med en öppning för huvudet), som hängs över axlarna.
Cape: ärmlöst rundskuret plagg som läggs över axlarna. Voisiko poncho mahdollisesti olla suoraan vaatteiden alla?

**Comment by mirmaid** [comment]
YSO-kokous 16.10.2015

LT vaatteet käyttötavan mukaan
