### ISSUE TITLE
YSOn yksilökäsitteet

### ISSUE THREAD

**Issue by MikkoAleksanteri** [NatLibFi/Finto-data#643]
YSOssa on päätetty erottaa (erisnimipohjaiset) yksilökäsitteet yleiskäsitteistä oman tyyppisiksi käsitteiksi.

Tyyppi: yso-meta:Individual

Tarvitaan vielä linjaus sekä määritelmä siitä, mikä tekee yksilön.

Listaus käsitteistä, joiden suomenkielinen prefLabel alkaa isolla alkukirjaimella:
https://docs.google.com/spreadsheets/d/1yQit-mCRlD3SZiiHUufoC7vNq2u-bjeR_vsqt2FliZM/edit?usp=sharing

**Comment by tpalonen** [comment]
Liisan muistio.
Yleisen suomalaisen ontologian instanssit		7.12.2015/LV	


YSOn instanssilla tarkoitetaan yksilökäsitettä. 
•	Yksilökäsite vastaa yhtä ainutkertaista tarkoitetta, joka on nimetty isolla alkukirjaimella alkavalla erisnimellä. 
o	Versaalialkukirjaimesta on suomen kielen oikeinkirjoitussääntöjen  takia joitakin poikkeuksia, mutta näissäkin tapauksissa on kyse yhdestä tarkoitteesta; näillä käsitteillä on erillinen identiteettinsä (esim. talvisota) . 
	Käsitteen nimityksen alkukirjaimen koko ei siis yksinään voi toimia YSOn instanssin kriteerinä.
•	Instanssi on hierarkiassaan alimpana, sillä ei ole alakäsitteitä.
•	Instanssi on yksikkömuotoinen lukuun ottamatta joidenkin järjestettyjen tapahtumien nimiä.
•	Instanssi voidaan useimmiten määritellä ajankohdan, sijaintipaikan ja/tai sisällön kannalta tarkkarajaisesti.
•	Instanssiin liittyy tietty konkreettisuuden aste: nekin instanssit, jotka ovat YSOssa abstrakteja olioita, saavat konkreettisen määrämuotoisen ilmenemismuodon (esim. sopimukset, lait). Mitä teoreettisempi käsite on, sitä epätodennäköisemmin sitä voidaan pitää instanssina.

Seuraava lista luettelee tyypillisiä YSOn instansseja. Lista ei ole täydellinen. 
•	yksittäiset rakennukset, linnoitukset, liikenneväylät, satamat, puistot, luonnonsuojelualueet
o	ihmisen määrittämiä paikkoja ja alueita
o	konkreettisia, paikkaan sidottuja 
o	esim. Kesäranta, Tarvaspää, Jäämerentie, Urho Kekkosen kansallispuisto
•	kulttuuri- ja liikuntatapahtumat, huvitilaisuudet, sodat, taistelut
o	järjestettyjä tapahtumia
o	nimetyt järjestetyt tapahtumat ovat instansseja, vaikka ne olisivat toistuvia (esim. Helsinki City Marathon) 
o	tapahtumalla on nimetty tai osoitettavissa oleva organisoija 
o	esim. Pori Jazz, Tampereen teatterikesä, Vietnamin sota, Raatteen tien taistelu
•	tietokoneohjelmat, käyttöliittymät
o	teknisiä abstrakteja objekteja ja teknisiä järjestelmiä
o	sisällöllisesti määrämuotoisia
o	esim. Corel Draw, Ubuntu
•	sopimukset, projektit, julistukset, tutkinnot, rekisterit, ohjelmointikielet, lait
o	yhteiskunnallisia objekteja
o	sisällöllisesti määrämuotoisia
o	esim. eläinsuojelulaki, Yleissopimus lapsen oikeuksista, Master of Business Administration, Fortran, Haminan rauha
•	teokset
o	Raamattu, Kalevala, Kalevipoeg
o	YSOssa on näitä vähän eikä määrä lisäänny

Instansseja eivät ole esimerkiksi taudit, orgaaniset objektit (esim. eläin- ja kasvilajit), kemialliset yhdisteet, menetelmät ja yhteiskunnalliset liikkeet.

**Comment by YSO-kokous** [comment]
Lisätään YSOn kehityslinjauksiin ylläolevan pohjalta laadittu tiivistys periaatteista, joilla yksilökäsite-tyyppiä käytetään. Lisätään myös maininta muista käsitetyypeistä.

**Comment by YSO-kokous** [comment]
Keskustelu linjauksista on jatkunut. Osa vastuuhenkilöistä on kokenut issueen kirjatut linjaukset ongelmallisiksi ja ristiriitaisiksi. Yllä kirjatuissa linjauksissa sanotaan, että yksilökäsitteellä on tietty konkreettisuuden aste, mutta se voi silti olla abstrakti. Yksilökäsitteen termi voi olla erisnimi, mutta ei kuitenkaan tarvitse olla erisnimi. Sanotaan, että yksilö on ainutkertainen, mutta kuitenkin esimerkkeinä mainitaan yhtäältä toistuvia tapahtumia ja toisaalta tietokoneohjelmia, joista julkaistaan uusia versioita. Sanotaan, että yksilö yleensä voidaan määritellä ajallisesti tarkkarajaisesti, mutta tämä ei toteudu esim. toistuvien tapahtumien osalta. Sanotaan, että yksilö on yleensä sisällöllisesti tarkkarajainen, mutta esim. tietokoneohjelmien sisältö muuttuu uusien versioiden myötä.

Esimerkiksi yksilökäsitteest on mainittu mm. lait. Lakiin voidaan kuitenkin ilmeisesti tehdä päivityksiä ja se voidaan julkaista uudelleen täsmälleen samalla nimellä.

Vrt. RDA:n mukaan yksilöitä ovat yksittäiset kappaleet, yksittäiset kopiot. Toisin sanoen yksilö on yksi fyysinen käsinkosketeltava kirja tai levy. Ja tästä voitaneen johtaa, että mikään ei-fyysinen ei RDA:n mukaan voi olla yksilö.

**Comment by YSO-kokous** [comment]
Yksilökäsitetyyppiä käytetään, kun kyseessä on fyysisesti olemassa oleva objekti ja tuota objektia on olemassa vain yksi kappale.

**Comment by mirmaid** [comment]
Tällä hetkellä näyttää ainakin sodat olevan yksilökäsitteitä?

**Comment by ilona-x** [comment]
käytetäänkö myös kun kyseessä on teos tai vastaava, joka on täysin kertaluonteinen, esim. julistus, tai sopimus?

**Comment by mirmaid** [comment]
Tuomas tekee listauksen.

**Comment by tpalonen** [comment]
Poistin myös ohjelmointikielet ja tietokoneohjelmat, jotka olivat yksilökäsitteitä. Tämän jälkeen YSOssa on yksilökäsitteitä 1441 kpl. Näistä 526 on rakennukset-hierarkiassa. Ja muita 915 kpl. Silmäilimme rakennukset-hierarkiaan kuuluvat läpi ja niiden osalta yksilökäsite-status näytti hyvältä. Tässä taulukossa listattuna nämä muut eli 915 kpl läpikäytäväksi.
[YSOn yksilökäsitteet (ei rakennushierarkian käsitteitä) 2023-12-14.xlsx](https://github.com/NatLibFi/Finto-data/files/13674751/YSOn.yksilokasitteet.ei.rakennushierarkian.kasitteita.2023-12-14.xlsx)

**Comment by mirmaid** [comment]
Sprintti 9.4.
- puistot (ml. huvipuistot jne.), luonnonsuojelualueet, kampukset, lentoasemat ym. paikkakäsitteet, mukaan lukien reitit ja radat, säilyvät yksilöinä
- sillat, linnoitukset, maatilat, stadionit, padot, muurit
- taivaankappaleet

**Comment by mirmaid** [comment]
Tuomas tuottaa taulukot kaikista yksilökäsitteistä, jotka

1) eivät ole ihmisen määrittämän paikan tai rakennuksen tai taivaankappaleen alakäsitteitä, nämä voidaan muuttaa tarkistuksen jälkeen sparkkelilla yleiskäsitteeksi

2) listaus ihmisen määrittämän paikan alla olevista yksilökäsitteistä, tarkistetaan onko joukossa muutettavia

**Comment by tpalonen** [comment]
^ varmaankin pitää listata YSOn paikka-käsitteen alakäsitteet, koska yksilöitä on sekä alueet- että ihmisen määrittämät paikat -hierarkioissa.

**Comment by YSO-kokous** [comment]
YSOn paikkahierarkiaan sisältyvät yksilökäsitteet yläkäsitteineen:
[YSOn paikkahierarkian yksilökäsitteet 030624.xlsx](https://github.com/user-attachments/files/15532496/YSOn.paikkahierarkian.yksilokasitteet.030624.xlsx)

**Comment by YSO-kokous** [comment]
YSOn yksilökäsitteet, jotka eivät ole paikka- tai taivaankappaleet-käsitteiden alisessa hierarkiassa:
[YSOn yksilökäsitteet jotka eivät ole paikkoja tai taivaankappaleita 030624.xlsx](https://github.com/user-attachments/files/15532594/YSOn.yksilokasitteet.jotka.eivat.ole.paikkoja.tai.taivaankappaleita.030624.xlsx)

**Comment by YSO-kokous** [comment]
Poistettu yksilökäsitestatus ja muutettu yleiskäsitteeksi kaikki YSOn yksilökäsitteet, jotka eivät ole paikka- tai taivaankappaleet-käsitteiden alisessa hierarkiassa. Näihin hierarkioihin jäi muutama käsite, joille yksilökäsitestatus sopii, esim. _Torinon käärinliina_. Nämä muutetaan käsin takaisin yksilökäsitteiksi.

**Comment by mirmaid** [comment]
Listaus takaisin yksilökäsitteiksi muutettavista & käsitteistä joita voisi vielä pohtia:

luostarit (organisaatioissa, jääkö yleiskäsitteiksi/jääkö hierarkia nykyiselleen)
lomakodit 
Onnela
Keimolan moottoristadion

muinaislinnat > ihmisen määrittämä paikka (?) (vrt. linnavuoret)

(vs. lentoasemat, museot, stadionit, taiteilijakodit yksilökäsitteitä)

Linnunrata
aurinkokunta
Struven ketju (vrt. Salpalinja)

Torinon käärinliina

Qumranin kirjoitukset (?)

**Comment by mirmaid** [comment]
Linjaus:
Yksilökäsite-tyyppiä käytetään vain, kun kyseessä on fyysinen objekti, jota on olemassa vain yksi kappale.
