### ISSUE TITLE
valjakkourheilu

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#644]
Käytetään suomeksi sekä koirista että hevosista? Näille eri termit ruotsiksi, eikä asiaa niputeta tällä tavalla. Nyt ruotsiksi draghundssport, mutta se ei täsmää kaikkien Melinda-osumien kanssa.

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 4.1.16:

Merkitys myös suomeksi vain koirien kanssa urheilu. -> Siirretään ST hiihtoratsastus ja valjakkoajo LT eläinurheilu. 

Lisätään käsitteelle "valjakkourheilu" huomautus: "Valjakkourheilu koirien kanssa."

**Comment by tpalonen** [comment]
hiihtoratsastuksella ja valjakkoajolla oli molemmilla LT hevosurheilu. Säilytin tämän LT:n, en lisännyt LT eläinurheilu, koska olisi ollut epätarkempi.
