### ISSUE TITLE
Kansojen hierarkia (uralilaiset, eurooppalaiset jne)

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#645]
Väestöryhmään liittyvän roolin alla on runsaasti käsitteitä, esim. uralilaiset hierarkian alla on lähemmäs sata käsitettä. Monissa tapauksissa hierarkiat pätevät aina tiettyyn pisteeseen asti, mutta kokonaisuudessaan ne ovat kömpelöitä. Asuma-alue, kieli ja etninen identiteetti menevät sekaisin. Hierarkia esittää esim. että vironvenäläiset, amerikansuomalaiset ja suomenruotsalaiset ovat uralilaisia. Uussuomalaiset ovat suomalaisia, mutta tuskin kuitenkaan suomalaisugrilaisia. Ovatko amerikanruotsalaiset tai grönlantilaiset eurooppalaisia kuten hierarkia väittää? Uralilaiset-käsitettä ei löydy YSAsta, mutta hierarkia tulee suurelta osin YSAsta. *kansat-päätteiset käsitteet on tosin korvattu YSOn hierarkiassa tyyliin itämerensuomalaiset kansat > itämerensuomalaiset.

RATKAISU:
1) Uralilaiset-käsite poistetaan
2) Hierarkiavirheiden välttämiseksi ehdotan seuraavaa hieman väkivaltaista ratkaisua: kaikki valtio/kieli-tasoisten kansakäsitteiden alakäsitteet siirretään suoraa väestöryhmään liittyvä rooli -käsitteen alle ja näille RT siihen käsitteeseen, jonka alta ne otettiin pois. Näitä siirrettäviä olisivat siis seuraavien käsitteiden alakäsitteet:

meksikolaiset
australialaiset
latvialaiset
virolaiset
belgialaiset
britit
kreikkalaiset
espanjalaiset
ruotsalaiset
suomalaiset
tanskalaiset
saksalaiset

Eipä tämä mikään täydellinen ratkaisu ole, mutta ISA relationship is a ISA relationship.

**Comment by tpalonen** [comment]
Ks. myös issue #368.

**Comment by tpalonen** [comment]
Mirja kommentoi: "Onko kansat organisaatio vai järjestelmä? Vrt. myös kulttuuri (kulttuurimuodot)."

**Comment by YSO-kokous** [comment]
Ks. myös https://github.com/NatLibFi/Finto-data/issues/897

**Comment by YSO-kokous** [comment]
Tulkitaan hierarkiaa paikan mukaan, aina kun mahdollista:
lappilaiset LT pohjoismaalaiset
ulkosuomalaiset LT väestöryhmään liittyvä rooli RT suomalaiset
uussuomalaiset LT suomalaiset
amerikansuomalaiset LT amerikkalaiset + ulkosuomalaiset (australiansuomalaiset vastaavasti)
vironvenäläiset LT virolaiset

Poistetaan: uralilaiset, suomalais-ugrilaiset, itämerensuomalaiset

**Comment by mariaforsen** [comment]
Mitä tehdään volgansuomalaiset + volgansuomalaiset kansat -asialle? Tekemäni issue on näköjään suljettu, mutta ongelma edelleen olemassa.

**Comment by tpalonen** [comment]
Tein muutokset. En raaskinut ottaa suomenruotsalaisia pois suomalaisten alta, vaikka suomenruotsalaiset eivät olekaan uralilaisia. Hierarkia tuntui liian tärkeältä.

**Comment by tpalonen** [comment]
Osa käsitteistä ei nykyisin toteuta tässä mainittua linjausta "Tulkitaan hierarkiaa paikan mukaan, aina kun mahdollista". Esim. saksalaiset-käsitteen alakäsitteet baltiansaksalaiset, suomensaksalaiset, volgansakasalaiset.

Käydään kansojen hierarkia uudelleen läpi ja muutetaan linjauksen mukaiseksi. Esim. baltiansaksalaiset  LT eurooppalaiset + RT saksalaiset.

**Comment by mirmaid** [comment]
Entä kansat-käsitteen suhde väestöryhmään liittyvän roolin alla oleviin kansojen nimiin? Nyt burjaatit RT kansat, ei muita vastaavia. YSAssa kansat oli yläkäsite. YSOon otettu YSAn lakkauttamisen jälkeen esim. khmerit, korjakit - nämä huomioitava myös, jos RT-suhde lisätään.

**Comment by mirmaid** [comment]
Poistetaan RT burjaatit. 
Käydään kansojen hierarkia uudelleen läpi ja muutetaan linjauksen mukaiseksi. Esim. baltiansaksalaiset LT eurooppalaiset + RT saksalaiset. (Tuomas hoitaa)

**Comment by mirmaid** [comment]
Sprintti 9.4.
Hyväksytään Tuomaksen ehdotus. (Tuomas toteuttaa)
