### ISSUE TITLE
plasma

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#646]
Jäljellä olevat plasmat ei ole käsitelty loppuun asti, ks. luokat ja suhteet.

**Comment by mariaforsen** [comment]
Sen lisäksi on nyt sekä: plasma (kaasu) että plasma (kaasut). Yksi niistä täytyy poistaa.

**Comment by osma** [comment]
Lisäksi löytyy siis YSOsta vielä "plasma (orgaaninen rakenne)", joka on linkitetty YSAn käsitteeseen "plasma (neste)" ja viitannee esim. veriplasmaan.

YSOn "plasma (kaasut)" on samoin linkattu YSAn "plasma (neste)"-käsitteeseen, tämä nyt ainakin on väärin.
