### ISSUE TITLE
uskonnot (opit), uskonnolliset liikkeet, näiden alakäsitteet

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#650]
Alakäsitteet pitäisi olla johdonmukaisemmin näiden alla. Nyt YSO-kokouksessa laitettiin skientologia uskonnot (opit)-termin alle, mutta uskonnolliset liikeet-termin alle on laitettu aikaisemmin esim. kopismi, moonilaisuus, Kōfuku no kagaku, New Age -liike, gnostilaisuus, rastafari, swedenborgilaisuus vaikka näilläkin on omat erilliset oppinsa, eli siis eivät ole sen enempää jonkin toisen uskonnon "sisäisiä liikkeitä" kuin skientologia yms. Vrt Moraalinen varustautuminen, kastajaliikkeet yms. kristillisiä liikkeitä. Tosin rajaveto uuden uskonnon ja toisen uskonnon sisäisen liikkeen välillä on joskus vaikeaa tehdä. Sananmuoto -liike on myös voinut vaikuttaa tässä.

**Comment by tpalonen** [comment]
Tuomas ja Maria konsultoivat jotakuta/joitakuita uskontotieteilijää rajatapauksien osalta. Tehdään päätös tämän pohjalta

Huomioi myös uskonnolliset yhteisöt ja Jehovan todistajat!

**Comment by tpalonen** [comment]
Konsultoin Helsingin yliopiston uskontotieteen laitoksen tutkijaa Teemu Tairaa. Tässä keskustelun satoa:

Totesimme, että tällä hetkellä YSOssa olevassa kahtiajaossa "uskonnolliset liikkeet"-kategoria määrittyy suhteessa "uskonnot"-kategoriaan siten, että uskonnollisilla liikkeillä on joko a) selkeä emouskonto, jonka sisällä kyseinen liike vaikuttaa tai b) on kyse suurpiirteisemmin liikkeestä tai ilmiöstä, jolle on vaikea määrittää selkeitä rajoja ja jonka ei voi katsoa muodostavan itsenäistä, muista uskonnoista irrallaan olevaa uskontokuntaa (New Age -liike sopii tähän määritelmään). Uskonnot-kategorian alle taas kuuluvat melko selvärajaiset, vakiintuneet, institutioaaliset uskonnot, jotka eivät ole jonkin toisen uskonnon alahaaroja.

Ongelmaksi tämän jaon tekee ontologisesti se, että YSOssa esiintyy nyt kaksi tapaa hierarkisoida  emouskontoon sisältyviä haaroja tai liikkeitä: joko ne ovat hierarkkisesti emouskonnon alakäsitteitä, tai ne kuuluvat "uskonnolliset liikkeet"-hierarkiaan. Hierarkiaa on siis rakennettu kahdella keskenään ristiriidassa olevalla logiikalla. Esimerkiksi herätysliikkeet alakäsitteineen sopisi myös uskonnot-hierarkian puolelle luterilaisuuden alle.

Teemu toi esiin erilaisia uskontojen kategorisointiin liittyviä ongelmia, mutta ei kuitenkaan pitänyt YSOn lähestymistapaa mitenkään periaatteellisella tasolla vääränä. Tässä pari muutosehdotusta, joita hän kuitenkin teki:

- cargo-kultit, Divine Light Mission, kopimismi ja rastafari: nämä voisi siirtää uskontojen alle; ovat enemmän uskontomaisia kuin liikemäisiä
- veda-uskonto: tämän voisi siirtää hindulaisuuden alle, vaikkakin hierarkia olisi eräässä mielessä anakronistinen (veda-uskonto oli olemassa jo ennen hindulaisuutta), mutta veda-uskontoa ei joka tapauksessa esiinny irrallaan hindulaisuudesta
- wicca: tämän voisi siirtää uuspakanuuden alle; suurin osa wiccoista pitää itse itseään pakanoina

**Comment by mirmaid** [comment]
YSO-kokous 21.10.2016:
Maria ja Tuomas työstävät, uskonnolliset liikkeet -käsitteen alakäsitteille etsitään myös "emouskonto" joka sopisi toiseksi yläkäsitteeksi. Päätetään sen jälkeen kokouksessa jätetäänkö näille monihierarkia.

**Comment by mariaforsen** [comment]
Ei ole varmaan mitään syytä pitää juuri schwenckfeldiläisyys uskonnollisten yhteisöjen alaterminä, kun kaikki muut vastaavat ovat muualla (uskonnollisten yhteisöjen alla on vain Morbacka ja schwenckfeldiläisyys, ja Morbackakin on hieman kyseenalainen...)

**Comment by mirmaid** [comment]
cargo-kultit, Divine Light Mission, kopimismi ja rastafari > uskonto ja uskonnot
wicca YK uuspakanuus
veda-uskonto: ei muutosta
schwenckfeldiläisyys YK uskonnolliset liikkeet RT kristinusko
evankelikalismi YK protestantismi
herätysliikkeet YK uskonnolliset liikkeet RT kristinusko
esireformatoriset liikkeet RT kristinusko
gnostilaisuus YK uskonto ja uskonnot
henkitanssi YK uskonnolliset liikkeet + nativistiset liikkeet
hurmoksellisuus: ei muutosta
Jeesus-liike RT kristinusko
kartanolaisuus RT kristinusko
kastajaliikkeet RT kristinusko
moonilaisuus YK uskonto ja uskonnot
Moraalinen varustautuminen & Oxfordin ryhmäliike RT kristinusko
Plymouthin RT kristinusko
swedenborgilaisuus RT kristinusko
