### ISSUE TITLE
Erikoisontologioiden YSO-ekvivalentit käsitteet ja niiden näyttäminen Fintossa

### ISSUE THREAD

**Issue by frosterus** [NatLibFi/Finto-data#651]
Esimerkiksi JUHOsta katsottaessa käsitettä talouspolitiikka:
http://finto.fi/juho/fi/page/?uri=http%3A%2F%2Fwww.yso.fi%2Fonto%2Fyso%2Fp978

Monet käsitteet on duplikoitu, eli JUHO-käsitteestä on ekvivalennsi YSO-käsitteeseen. Ne näkyvät nyt kahteen kertaan hierarkiassa ja alakäsitteinä ja hakutuloksissa.

Käyttäjälle tämä näyttää erittäin hämmentävältä.

Ks. https://github.com/NatLibFi/Skosmos/issues/222

**Comment by osma** [comment]
Tässä issuessa siis ajatuksena, että ongelmaan voisi puuttua datan puolella. Joko ontologian kehitysversiossa (eliminoidaan päällekkäisyyksiä poistamalla käsitteitä) tai julkaisun yhteydessä yhdistämällä tai poistamalla käsitteitä.

**Comment by tpalonen** [comment]
KOKO-työpaja #4 22.9.2016 vienee tätä asiaa eteenpäin. Tarkoituksena löytää siellä linjanveto erikoisontologian ja YSOn välisten päällekkäisyyksien toteutukselle.

**Comment by mirmaid** [comment]
Käsitellään tarpeen mukaan eteenpäin OY-kokouksissa.
