### ISSUE TITLE
Hierarkisoivien käsitteiden nimitykset ja ryhmien yhdenmukaisuus

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#652]
Ilmiöitä läpikäytäessä nousseita (temaattisia) ryhmittelyjä (kaipaavat selkeämpiä nimiä kuin nykyiset "iset"-päätteiset muodot):
- yleiset abstraktit (objektit/ominaisuudet/prosessit)
- biologiset (= biologian alaan kuuluvat)
- fysikaaliset (= fysiikan alaan kuuluvat?)
- kemialliset?
- mentaaliset/henkiset/psykologian alaan kuuluvat
- yhteiskunnalliset
- taloudelliset (LT yhteiskunnalliset?)
- oikeudelliset (LT yhteiskunnalliset?)
- kulttuuriset
- uskonnolliset

Muita ratkaistavia nimiä / ryhmittelyjä:
- tapahtumat - toiminta - ilmiöt = prosessit? (esim. nyt biologiset tapahtumat ja biologiset ilmiöt)
- järjestelmät - kokonaisuudet

**Comment by mirmaid** [comment]
Yhteiskunnalliset/kulttuuriset -jaosta ks. issue #2

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 18.1.16:

kulttuuriset vs yhteiskunnalliset: vastuuhenkilö: Mikko

**Comment by mirmaid** [comment]
Tällä hetkellä _taloudelliset tuotokset_ on ainoa jäljelläoleva "tuotokset" -ryhmä.

**Comment by mirmaid** [comment]
Voisiko mentaaliset muuttaa > psyykkiset?

**Comment by mirmaid** [comment]
Fysikaaliset vs. fyysiset

- fyysiset kokonaisuudet
- fyysiset objektit
- fysikaaliset tapahtumat

Lisäksi on yleiskäsitteitä, joissa vastaava alku (ja joilla voi olla suuria alakäsitejoukkoja).

**Comment by mirmaid** [comment]
_Kulttuuriset ilmiöt_ -hierarkisoivat käsitteellä on vain yksi alakäsite.

**Comment by mirmaid** [comment]
Poistetaan kulttuuriset ilmiöt.
Taloudelliset tuotokset > taloudelliset objektit.
