### ISSUE TITLE
eristys

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#654]
"Maria ja Mirja tekee ehdotuksen" listalta: https://docs.google.com/spreadsheets/d/1igl6qGGXJE0q0s_be_iawWIyuZEze2bFg2ldZlzU6KA/edit#gid=1100133302

Jos päädytään jakoon voisi tarkenteet olla ruotsiksi esim: isolering (social) ja isolering (teknik) Ensimmäinen toimii riippumatta onko eläin, ihminen, vanki, potilas kyseessä.

**Comment by MikkoAleksanteri** [comment]
Ratkaistu YSAn puolella, odotetaan päivitystä.
