### ISSUE TITLE
hajoaminen

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#656]
Listalta: https://docs.google.com/spreadsheets/d/1igl6qGGXJE0q0s_be_iawWIyuZEze2bFg2ldZlzU6KA/edit#gid=1100133302

Ruotsiksi olennaisimmat upplösning, sönderfall, nedbrytning. Tärkeimmät voisi mahdollisesti yhdistää jos päädytään siihen ettei tehdä jakoa suomeksi.

**Comment by mirmaid** [comment]
Upplösning: vastineet: liuotus, resoluutio (erikseen parlamentsupplösning, upplösning av samboende)
Sönderfall käytetty tietoaineistossa 9 kertaa (2 perheen hajoaminen, 4 kemia/biokemia (yhdessä myös nedbrytning), 2 kirkkohistoria (tässä myös splittring), kerran liittovaltiosta
Nedbrytning eniten käytetty

**Comment by mariaforsen** [comment]
Vaikeaa saada yksi-yhteen-vastavuutta ruotsiksi, myös vaikka jaettaisiin.
