### ISSUE TITLE
hajotus

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#657]
Listalta: https://docs.google.com/spreadsheets/d/1igl6qGGXJE0q0s_be_iawWIyuZEze2bFg2ldZlzU6KA/edit#gid=1100133302

Vaikuttaa olevan käytetty melkein vain biologisena/kemiallisena. Tämä merkitys on myös ruotsin vastineella sönderdelning. Voisiko määritellä käytettäväksi näin, eikä esim. "hallituksen hajotuksessa"? Esim. laittamalla sopivia ryhmiä.

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/7415
