### ISSUE TITLE
haku

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#658]
Listalta: https://docs.google.com/spreadsheets/d/1igl6qGGXJE0q0s_be_iawWIyuZEze2bFg2ldZlzU6KA/edit#gid=1100133302
Ruotsiksi olisi kaksi vastinetta: sökning (etsiminen..) + ansökning (pyrkiminen..) 
Ks Melindaa ja vrt merkitykset 2 ja 4 MOTissa. Olisiko syytä/mahdollista jakaa?

**Comment by mirmaid** [comment]
Ks. https://github.com/Finto-ehdotus/YSE/issues/4649
