### ISSUE TITLE
kartoitus

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#659]
Listalta: https://docs.google.com/spreadsheets/d/1igl6qGGXJE0q0s_be_iawWIyuZEze2bFg2ldZlzU6KA/edit#gid=1100133302
Halutaanko tätä jakaa suomeksi? Siinä tapauksessa ruotsiksi: kartläggning, kartering. Muuten käy kyllä kartläggning sekä maantieteelliseen että yleiseen merkitykseen, eli ei erityistä tarvetta jakaa ruotsiksi. Ja merkityksethän ovat perimmiltään melko samat riippumatta mitä kohdetta kartoitetaan, oli se sitten maastoa tai jotakin ilmiötä. Käytetty todella paljon Melindassa.

**Comment by mirmaid** [comment]
Päätetty koostekäsitteiden käsittelyn yhteydessä ettei jaeta.
