### ISSUE TITLE
kraatterit

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#660]
Listalta: https://docs.google.com/spreadsheets/d/1igl6qGGXJE0q0s_be_iawWIyuZEze2bFg2ldZlzU6KA/edit#gid=1100133302

Käyttäjä joka on kiinnostunut tulivuoren kraatterista haluaa tuskin osumia törmäys/meteoriittikraattereista. Muoto on toki samankaltainen, mutta merkitykset/aihealueet eri, eli voiko olla tarpeen jakaa? Siinä tapauksessa sama ruotsiksi.

**Comment by mirmaid** [comment]
YSO-kokous 7.1.2016: kraatterit KT törmäyskraatterit, meteoriittikraatterit. Kalderat LT kraatterit.
