### ISSUE TITLE
vesiviljely

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#661]
Vertaa suhteet, ryhmät jne. YSA/Allärsissa ja YSOssa sekä englannin "hydroponics". Ruotsiksi nyt akvakultur joka viittaa nimenomaan "eläinten viljelyyn", ei kasvien (=hydrokultur=hydroponics). Mihin loppujen lopuksi viitataan ontologian puolella tällä käsitteellä? Tarpeen jakaa, selventää tai yhdenmukaistaa kielten välillä?

**Comment by mirmaid** [comment]
Jaettu YSA-kokouksessa 4-2016.
