### ISSUE TITLE
ilmestykset

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#662]
Oliko niin ettei ilmestykset voisi olla itsenäinen asiasana? Ruotsiksi on uppenbarelser tärkeä ja käytetty termi, joten en voi ainakaan mennä poistamaan sitä Melindasta kaikki ne kerrat mitä se on siellä käytetty. Ennen on ollut Allärsissa sekä gudsuppenbarelse että uppenbarelse, mutta Allfossa ei nyt ole yhtään niistä. Ilmestyksiä voi tosiaan olla monenlaisia, näyt ovat vain yksi tapa millä ne voivat ilmetä. Suomeksikin ilmestykset on käytetty 9 kertaa Melindassa.

**Comment by mirmaid** [comment]
Hyväksytty YSA-kokouksessa 3-2016.
