### ISSUE TITLE
Johanneksen kirkko

### ISSUE THREAD

**Issue by livirtan** [NatLibFi/Finto-data#663]
Ysossa on käytettävänä käsitteenä Johanneksen kirkko (erikseen kirjoitettuna), jolle ei ole vastinetta Ysassa. Poistettaneen? (Johanneksen kirkko - Helsinki KÄ Johanneksenkirkko on ok). Englanninkieliset termit tietueissa erilaiset.

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 11.4.2016:

->poistetaan. Tarkistetaan kumpi englanninkielinen käännös on oikein.

**Comment by MikkoAleksanteri** [comment]
Muutokset toteutettu, jäljelle jäi siis käsite p25064

Engl labelit täytyy vielä tarkistaa. Jäljelle jääneellä nyt "Johanneksenkirkko Church (Helsinki)", poistetulla "Church of Saint John (Helsinki)", Wikipediassa "St. John's Church". 	@satuniininen

**Comment by satuniininen** [comment]
Englanti tehty.
