### ISSUE TITLE
Syömishäiriöt

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#665]
Jostain syystä YSOssa anoreksia ja bulimia eivät ole syömishäiriöiden alakäsitteitä, vaan oireita. Ortoreksialla on molemmat yläkäsitteinä. Syömishäiriöt riittänee?

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 11.4.2016:

Siirretään anoreksia ja bulimia LT syömishäiriöt. Ortoreksia LT vain syömishäiriöt.

**Comment by MikkoAleksanteri** [comment]
Toteutettu dataan.
