### ISSUE TITLE
Selluliitti

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#666]
YSOssa LT tulehdus. YSAssa RT tulehdus. Lääketieteen termit: ihonalaisen sidekudoksen epätarkkarajainen, usein etenevä bakteeritulehdus; ks. myös flegmoni; 2. ohimoluun kartiolisäkkeen lokeroston tulehdus, 3. (kosmetologiassa:) pienten rasvakertymien takia epätasainen iho. Engl. wikipedia erikseen cellulite ja cellulitis (tulehdus). Ei käytetty tulehdus-merkityksessä Melindassa.

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 11.4.2016

selluliitti LT rasvakudokset
