### ISSUE TITLE
pioneerit

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#668]
Monimerkityksinen, pitäisikö lisätä sulkutarkenne? Ruotsiksi harkittu, nyt ainakin lisätty ohjaus: "pionjärer (föregångare)" sanalle föregångare (edelläkävijät), ettei ainakaan tulisi niin paljon virheitä tietokantoihin (varsinkin ruotsiksi käytetty paljon merkityksessa "edelläkävijät" vaikka luokat jne. sotilaallinen).

**Comment by mirmaid** [comment]
YSO-kokous 7.1.2016: lisätään pioneerit (edelläkävijät) KÄ edelläkävijät
