### ISSUE TITLE
Englanninkielisiä tarkenteita ja huomautuksia suomenkielisissä käsitteissä

### ISSUE THREAD

**Issue by livirtan** [NatLibFi/Finto-data#669]
1. Europan: suomenkielisessä termissä on engl. tarkenne, ruots. ja engl. ei tarkennetta ollenkaan.
2. Sundsberg (manor)
3. Keltainen kirjasto: huomautus englanniksi

**Comment by MikkoAleksanteri** [comment]
Korjattu.
