### ISSUE TITLE
Taiteiden yö

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#670]
On suomeksi ja ruotsiksi "neutraali", eli toimii riippumatta missä kaupungissa järjestetty, mutta englanniksi jostain syystä lisätty sulkutarkenne "Helsinki", pitäisikö se poistaa?

**Comment by mirmaid** [comment]
YSO-kokous 7.1.2016: poistetaan tarkenne

**Comment by satuniininen** [comment]
Enkku korjattu.
