### ISSUE TITLE
Asekätkentä

### ISSUE THREAD

**Issue by livirtan** [NatLibFi/Finto-data#671]
Asekätkennän LT on nyt liikuttaminen, joka antaa ymmärtää, että kyse olisi mistä tahansa aseiden piiloon panemisesta. Näin ei ole, vaan vaan käsite viittaa YSAssa/YSOssa tiettyyn tapahtumaan/tapahtumasarjaan. Ehdotan yläkäsitteeksi operaatiot tai järjestetyt tapahtumat.

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 11.4.2016:

Asekätkentä huomautus: "Asekätkentä oli jatkosodan jälkeen Suomessa suoritettu salainen aseiden hajavarastointioperaatio."

LT yhteiskunnalliset tapahtumat

**Comment by MikkoAleksanteri** [comment]
Toteutettu dataan.
