### ISSUE TITLE
tanssimusiikki, tanssit ST

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#674]
Ne jotka jaettu musiikki vs. tanssi ovat edelleen monikossa myös tanssimusiikkina. Kuuluuko sellaiset todella olla monikossa (jos ylipäätään pidetään tämä jako)? Ruotsiksi ei ole luontevaa, mutta haluan varmistaa ennen kuin muutan mitään. Svenska ämnesord:issa on myös yksikössä. Nyt on YSOssa osa musiikista monikossa ja osa yksikössä, esim. salsa, humpat, blues, country, jivet jne.

**Comment by mariaforsen** [comment]
Mitäköhän tässä on päätetty?

**Comment by mirmaid** [comment]
Käsitellään issuessa #484
