### ISSUE TITLE
Mielenterveysongelmat

### ISSUE THREAD

**Issue by livirtan** [NatLibFi/Finto-data#675]
Mielenterveysongelmat, nyt LT ongelmat LT yhteiskunnalliset ilmiöt. Olisiko kuitenkin parempi, jos LT olisi mentaaliset tai biologiset ilmiöt? Käytännössä hyvin lähellä mielenterveyshäiriöitä.

**Comment by tpalonen** [comment]
Ratkaistu ilmiöiden läpikäynnin yhteydessä. Nykyinen LT abstaktit objektit.
