### ISSUE TITLE
Groteskin huomautus

### ISSUE THREAD

**Issue by livirtan** [NatLibFi/Finto-data#676]
Groteskilla on nyt huomautus "eräs varsinaisesti renessanssin suosima koristekuviotyyli" (ei tule YSAsta). Tämän huomautuksen voisi varmaan poistaa, sillä se antaa käsitteelle liian suppean ja nykykäytössä perifeerisen merkityksen.

**Comment by mirmaid** [comment]
YSO-kokous 7.1.2016: poistetaan huomautus.
