### ISSUE TITLE
Yhteisvastuu-keräys

### ISSUE THREAD

**Issue by livirtan** [NatLibFi/Finto-data#678]
Yhteisvastuu-keräys on nyt LT keräys LT omistuksen siirtäminen. Ehdotan siirtämistä: LT järjestetyt tapahtumat, esim. yhteiskunnalliset tapahtumat. Wikipedia: Tapahtuma on perustettu vuonna 1949 sodanaikaisen Kansanapu-keräyksen jatkajaksi...

Voisi tehdä myös viittauksen muodostaYhteisvastuukeräys.

**Comment by tpalonen** [comment]
PÄÄTÖS 13.6.2016:
Yhteisvastuu-keräys LT yhteiskunnalliset tapahtumat
