### ISSUE TITLE
Nordek

### ISSUE THREAD

**Issue by livirtan** [NatLibFi/Finto-data#680]
Nordek: Vuosina 1968-70 Norjan, Ruotsin Suomen ja Tanskan välille suunniteltu, toteutumatta jäänyt talousliitto.

On nyt LT  organisaatiot (järjestelmät). Olisiko parempi LT hankkeet?

**Comment by mirmaid** [comment]
YSO-kokous 7.1.2016: vaihdetaan LT:ksi hankkeet.
