### ISSUE TITLE
Alueelliset kulttuuritoiminnat

### ISSUE THREAD

**Issue by livirtan** [NatLibFi/Finto-data#681]
Alueteatteritoiminta LT keskinäinen toiminta
Alueorkesteritoiminta LT orkesteritoiminta LT taiteellinen luonti

Ehdotan molemmille LTksi "taiteellinen luonti". (Kulttuuritoiminnan alle ei näytä kootun eri toimintoja, se voisi muuten olla hyvä LT.)

**Comment by tpalonen** [comment]
PÄÄTÖS 13.6.2016
- alueteatteritoiminta LT kulttuuritoiminta
- orkesteritoiminta LT kulttuuritoiminta
