### ISSUE TITLE
Palkinnot

### ISSUE THREAD

**Issue by livirtan** [NatLibFi/Finto-data#682]

**Comment by livirtan** [comment]
Nyt palkinnot LT elottomat objektit LT fyysiset objektit. Ehdotan siirtämistä abstraktien objektien puolelle, onhan niissä sisältö fyysistä objektia tärkeämpi.

**Comment by tpalonen** [comment]
PÄÄTÖS 13.6.2016:
- palkinnot LT yhteiskunnalliset objektit
