### ISSUE TITLE
p24750 - ei termiä

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#683]
YSOssa on tällainen ryhmittelevä käsite, jolla on yksi alakäsite "kirjallisuus -- antiikki". Käsitteellä ei ole siis termiä. Mitähän tässä on ajateltu? Olisiko sopiva termi "kirjallisuus aikakauden mukaan"?

**Comment by mirmaid** [comment]
YSO-kokous 7.1.2016: poistetaan käsite p24750.
