### ISSUE TITLE
oleminen käsitteen alakäsitteet

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#684]
Päätimme 30.11.2015, että YSOn oleminen-käsite säilytetään ja tehdään siitä ehdotus YSAan. Sitä ei siis ole ollut YSAssa.Todettiin, että oleminen on olennainen käsite ja eri asia kuin eksistenssi. Jos oleminen mielletään filosofiseksi käsitteeksi, sen alakäsitteet YSOssa eivät tällä hetkellä tue tätä ajatusta. Näille pitäisi siis keksiä uusi paikka. Tässä alakäsitteet.

```
asuminen
aukiolo
eksistenssi
immanenssi
istuminen
kesänvietto
lomailu
läsnäolo
mökkeily
pinnaus
poissaolot
päivystys
rinnakkaiselo
seisominen
transsendenssi
valvominen
```

**Comment by tpalonen** [comment]
Käsitellään muun toimintahierarkian yhteydessä.

**Comment by mariaforsen** [comment]
Askeesi pitäisi olla LT elämäntapa.

**Comment by mirmaid** [comment]
YSA-kokous käsitteli ehdotuksen _oleminen_-termin lisäämisestä. Kokous päätti kuitenkin, että oleminen-termiä ei lisätä ja käsite poistetaan myös YSOsta, erottamista eksistenssistä ei nähty mahdollisena (myöskään muilla kielillä).

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/6800

**Comment by mariaforsen** [comment]
Eikö tämä asia ole nyt loppuunkäsitelty ja suljettavissa?

**Comment by tpalonen** [comment]
Nämä ratkaisu osana toiminta-hierarkian läpikäyntiä. Käsitekohtaiset ratkaisut löytyvät täältä:
https://github.com/NatLibFi/Finto-data/issues/754
