### ISSUE TITLE
Valistus

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#689]
Tämän käsittely koostekäsitevaiheessa jäi kesken. YSOssa on siis kaksi valistus-käsitettä.

valistus (aatteet)
valistus (keskinäinen toiminta)

PÄÄTÖS (ks Issue #450 ): YSA-kokoukseen ehdotus KÄ-viittauksista, esim. valistus (kasvatus) KÄ kansanvalistus jne.

Onko asia edennyt ja miten YSA-muutos vaikuttaa YSOon ja pitäisikö "valistus (keskinäinen toiminta)" poistaa?

Marian kommentti: "Jos YSA/Allärsissa halutaan rajata valistus termin käyttö siihen historialliseen kontekstiin, pitäisikö luokka 57 poistaa? Ruotsiksi on tosiaan "upplysningen" vastine, ja kun olen korjannut upplysning-sotkua tietokannoissa olen huomannut se olevan hyvin ongelmallista, koska valistus on usein myös käytetty "tiedotustoiminnasta" ja kasvatuksesta (olen joutunut poistamaan kokonaan ruotsin vastineita koska "upplysningen" ei sovi näihin tietueisiin). En poistaisi YSOn ratkaisua, joka on selkeä, Melinda-käytön vastaava, ja toimiva ruotsiksikin. On kyllä mielestäni ongelmallista niputtaa valistus historiallisena aatevirtauksena ja valistus "tiedottamisena" samaan asiasanaan. "

**Comment by mirmaid** [comment]
Ehdotettu aiemmin: valistus (kasvatus) → kansanvalistus

Paljon termejä, joita voisi käyttää valistus-termin sijasta: päihdetyö, ehkäisevä päihdetyö, päihdekasvatus, raittiuskasvatus, raittiustyö, terveyskasvatus, kansanvalistus.

**Comment by mirmaid** [comment]
Jos ohjaustermit ylläoleviin + tarkenne jäljellejäävään (valistus (aatteet)) ei riitä, ehdottaisin kuitenkin toiselle tarkenteeksi keskinäisen toiminnan sijasta kasvatus tai tiedotus.

**Comment by mirmaid** [comment]
YSAssa on muuten myös _valistusfilosofia_, onko sillä oikeastaan eroa valistusaatteeseen?

**Comment by YSO-kokous** [comment]
Pidetään kaikki ja **valistus (keskinäinen toiminta)** muotoon **valistus (tiedon jakaminen)**

**Comment by mirmaid** [comment]
Ehdotus YSEssä https://github.com/Finto-ehdotus/YSE/issues/5227
