### ISSUE TITLE
Nauta

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#691]
Wikipedian mukaan naudan (=laji) LT olisi nautaeläimet (=alaheimo). Näin myös YSAssa mutta YSOssa on jostain syystä nauta samalla tasolla kuin nautaeläimet. Monella käsitteellä on nämä kumpikin yläkäsitteinä (lehmät, vasikat, suomenkarja jne.). Pitäisi varmaan korjata nauta LT nautaeläimet – voi ehkä ajatella että muidenkin nautaeläinten naaraita, poikasia ja koiraita (:-D) nimitetään lehmiksi, vasikoiksi ja sonneiksi (tosin myös muita kuin nautaeläimiä voidaan nimittää näin), suomenkarja kuitenkin pitäisi kai olla vain LT nauta.

**Comment by tpalonen** [comment]
PÄÄTÖS 13.6.2016

- nauta LT nautaeläimet
- lehmät, vasikat, sonnit, suomenkarja LT nauta
