### ISSUE TITLE
Kypsennys

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#692]
YSOssa keittäminen, paistaminen ja savustus on siirretty pois kypsennyksen alta. Keittämisen kohdalla ehkä perusteltua mutta muuten en ymmärrä.

**Comment by tpalonen** [comment]
PÄÄTÖS 13.6.2016:

- paistaminen LT kypsennys
- savustus LT kypsennys + RT säilöntä
- suolaus LT toisenlaiseksi muuttaminen + RT säilöntä + RT ruoanvalmistus
- keittäminen RT kypsennys
