### ISSUE TITLE
Tiedostamaton

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#693]
Englannin kielessä kirjoitusvirhe. Lisäksi käännös voisi olla paremmin linjassa ruotsin ja suomen kanssa.

**Comment by satuniininen** [comment]
En ole tätä itse kääntänyt, mutta luulen, ettät tuohon muotoon on päädytty siksi, että englannin "unconscious" on vähän monimerkityksinen (myös tiedoton, tajuton), ja lisäksi on haluttu tehdä eroa käsitteeseen "piilotajunta".  Linjaus suomen ja ruotsin kanssa ei ole aivan ongelmatonta. 

Lähteenä lienee ollut tämä:  https://en.wikipedia.org/wiki/Unconscious_mind

Korjasin kirjoitusvirheen ja lisäsin altLabelin "the unconscious". Preflabelin jätin toistaiseksi nykyiseen muotoon, mutta lisäsin sen ongelmalistalle ja palaan asiaan myöhemmin.
