### ISSUE TITLE
verkkokauppa (www-sivustot) - yks. vs. mon.

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#70]
_From [SNyk...@gmail.com](https://code.google.com/u/112439428317292360191/) on January 20, 2014 16:22:47_
1. What is to be changed/Mitä muutetaan Sana verkkokauppa on jaettu. Miksi verkkokauppa (www-sivustot), joka viittaa "konkreettiisiin" kauppoihin on yksikössä? Muutkin kaupat tässä merkityksessä ovat monikossa ja silloin ymmärtää paremmin eron verrattuna siihen toiseen verkkokauppa-sanaan joka "ilmiönä" kuuluukin olla yksikössä. 2. Why the change is needed/Miksi muutetaan johdonmukaisuus ja yhteneväisyys 3. Realized changes/Toteutetut muutokset Päätös 12.12.2013: "verkkokauppa (www-sivustot)" muutetaan monikkomuotoon

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=67_

**Comment by mirmaid** [comment]
YSAssa lisätty verkkokaupat ohjaustermiksi verkkokauppa-asiasanalle. https://github.com/Finto-ehdotus/YSE/issues/5217

**Comment by YSO-kokous** [comment]
Deprekoidaan verkkokaupat, uudelleenohjaus käsitteeseen verkkokauppa.

**Comment by mariaforsen** [comment]
On toteutettu.
