### ISSUE TITLE
Korjausehdotuksia GTK:lta: bayesilainen menetelmä, fytoremeditaatio jne (englannin käännökset)

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#700]
Olemme saaneet Geologian tutkimuskeskuksen Jari Väätäiseltä palautetta (Katri Seppälän välityksellä) alla olevista englannin käännöksistä.

1) Bayesilainen menetelmä http://finto.fi/yso/fi/page/p17803 on englanniksi Bayesian analysis mieluummin kuin Bayes method

2) Fytoremediaatio http://finto.fi/yso/fi/page/p21646 on englanniksi phytoremediation eikä phytoremeditation.

3) Geolääketieteen http://finto.fi/yso/fi/page/p8815 parempi englanninkielinen nimi on medical geology 

4) Ilmanpaine http://finto.fi/yso/fi/page/p2941 on ilmatieteellisenä terminä atmospheric pressure ja teknisenä terminä air pressure. Koska YSO:ssa ko. termi on ryhmässä 14 Klimatologia, Meteorologia, Ilmatiede, sen käännöksen pitäisi olla siis atmospheric pressure eikä air pressure.

5) Ilmastonmuutokset http://finto.fi/yso/fi/page/p5729 on englanniksi climate changes mieluummin kuin climatic changes.

6) Jääjärvet http://finto.fi/yso/fi/page/p23231 on englanniksi glacial lakes mieluummin kuin ice lakes.

7) Jalokivet http://finto.fi/yso/fi/page/p11152 on englanniksi precious stones eikä jewels. Jewel tarkoittaa kivikorua.

8) Kromimalmit http://finto.fi/yso/fi/page/p1824 suositeltu termi on englanniksi chromite ores (eikä chromium ores), koska kromiitti on ainoa kromimalmi.

9) Lajiutuminen http://finto.fi/yso/fi/page/p15045 on käännetty virheellisesti specification (biology). Oikea käännös olisi speciation.

10 Louhinta http://finto.fi/yso/fi/page/p887 on englanniksi mieluummin pelkkä mining kuin mining extraction.

11) Maailmanperintökohteet http://finto.fi/yso/fi/page/p8476 on englanniksi world heritage sites mieluummin kuin world heritage areas

12) Maannostumisen http://finto.fi/yso/fi/page/p1671 suositeltavampi käännös olisi pedogenesis kuin soil formation.

13) Maaperägeologia http://finto.fi/yso/fi/page/p17072 on käännetty virheellisesti soil geology. Oikea käännös olisi surficial geology.

14) Maatalousjätteet http://finto.fi/yso/fi/page/p11887 on englanniksi mieluummin agricultural waste kuin farm waste.

15) Magneettikentät http://finto.fi/yso/fi/page/p19032 on käännetty virheellisesti magnet fields. Pitäisi olla magnetic fields.

16) Metamorfinen kivilaji mustaliuske http://finto.fi/yso/fi/page/p19289 on englanniksi  black schist eikä black shale. Black shale tarkoittaa mustaa savikiveä ennen kuin se metamorfoituu mustaliuskeeksi.

17) Moreeni http://finto.fi/yso/fi/page/p2519 on YSOssa käännetty virheellisesti moraine. Moraine tarkoittaa suomeksi moreenimuodostumaa, joka koostuu moreenista. Itse moreeniaines on englanniksi till.

18) Petoeläimet http://finto.fi/yso/fi/page/p14567 termin englanninkieliseksi nimeksi on tässä yllättäen valittu tieteellinen nimi Carnivora. Parempi englanninkielinen käännös on predators, kuten AFO-ontologiassa http://finto.fi/afo/fi/page/p260.

19) Piilevät http://finto.fi/yso/fi/page/p7853 on käännetty englanniksi bacillariophyta (vanha latinapohjainen nimi). Parempi englanninkielinen käännös on diatoms. Vähintään nimi pitäisi kirjoittaa isolla etukirjaimella Bacillariophyta.

20) Pohjavesialueet http://finto.fi/yso/fi/page/p9966 on käännetty groundwater basins. Tämä tarkoittaa lähinnä rakennetta tai muodostumaa, joka kerää pohjavettä. Parempi vastine sille, mitä pohjavesialueella suomenkielessä yleensä tarkoitetaan on ehkä groundwater province.

21) Rikinpoisto http://www.yso.fi/onto/yso/p15163 on käännetty YSOssa harvinaisella termillä desulphuration. Paljon yleisemmässä käytössä on termi desulfurization.

22) Turvemaat http://finto.fi/yso/fi/page/p17343 termin YSOn englanninkielisen version peat soils sijasta parempi käännös olisi peatlands, joka sopii paremmin ylemmän luokan maa-alueet alle kuin turvetta maalajina kuvaava sana peat soils.

**Comment by satuniininen** [comment]
Tehty
