### ISSUE TITLE
koulutettavuus

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#702]
Ruotsiksi bildbarhet, eli ei käy eläinten yhteydessä tms.

**Comment by mirmaid** [comment]
YSO-kokous 21.10.2016:
Maria tekee muutosehdotuksen ehdotusjärjestelmään.

**Comment by mariaforsen** [comment]
Muutosehdotus tehty.

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/4922
