### ISSUE TITLE
Televisiosarjat, radiosarjat, televisio-ohjelmat, radio-ohjelmat

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#703]
Näiden alakäsitteet pitäisi käydä läpi. Nykyisellään näiden alla on kaikkea iloisesti sekaisin. Olisi varmaankin parasta, että tässä ei sotkettaisi genreä ja vastaanottovälinettä keskenään. Jännityssarjoja tai tieteissarjoja voi tehdä myös radioon (esim. Yleisradion kuunnelmasarja Linnunradan käsikirja liftareille).  Pakkaa sekoittaa nykyisellään myös Netflixin kaltaiset suoratoistopalvelut ja televisiosarjat alkaa vaikuttaa terminä jo hieman vanhanaikaiselta.
Tässä poiminta hierarkiasta:

ajankohtaisohjelmat
asiaohjelmat
dokumenttiohjelmat
keskusteluohjelmat
kulttuuriohjelmat
lastenohjelmat
makasiiniohjelmat
musiikkiohjelmat
nuortenohjelmat
perheohjelmat
puheohjelmat
radio-ohjelmat
sarjaohjelmat
. . radiosarjat
. . rikossarjat
. . saippuaoopperat
. . sairaalasarjat
. . televisiosarjat
. . . . draamasarjat
. . . . fantasiasarjat
. . . . jännityssarjat
. . . . komediasarjat
. . . . nettisarjat
. . . . rikossarjat
. . . . sairaalasarjat
. . . . sotasarjat
. . . . tieteissarjat
. . tieteissarjat
. . tilannekomediat
televisio-ohjelmat
ulkomaiset ohjelmat
urheiluohjelmat
uskonnolliset ohjelmat
viihdeohjelmat

**Comment by mirmaid** [comment]
YSO-kokous 21.10.2016:
Tuomas tekee taulukon ja käydään se läpi sen jälkeen.

**Comment by tpalonen** [comment]
Taulukko, jossa kaikki YSOn "ohjelmat (radio- tai tv-ohjelmat)"-käsitteen alakäsitteet:
https://docs.google.com/spreadsheets/d/1gQUYv0smmO9rK8syPbb9LavXrzELDfCVleoBOySInYw/edit#gid=708951922

**Comment by mirmaid** [comment]
Jos haluamme jatkaan ryhmittelujä "jnk mukaan", tässä voisi jaotella alakäsitteet "ohjelmat aiheen/sisällön mukaan" ja "ohjelmat viestimen mukaan", tjsp. Tämän ulkopuolelle jäisivät kuitenkin sarjaohjelmat ja ulkomaiset ohjelmat. En sitten tiedä pitäisikö ryhmittelyn olla voimassa myös hierarkiassa alaspäin, jolloin televisio-ohjelmien alakäsitteinä ei voisi olla sisällön mukaan määrittyviä ohjelmatyyppejä.

Nykyiselläänkään hierarkia ei kyllä minusta ole erityisen sotkuinen. Ehkä nostaisin televisiosarjat-käsitteen alakäsitteet pykälää ylemmäs. Opetusohjelmat-ketjut taitavat olla oikeita ketjuja ja ne pitäisi ehkä käsitellä YSAssa, olen tainnut epähuomiossa tulkita ne tarkenteiksi.

**Comment by mirmaid** [comment]
Siirretään televisiosarjat-alakäsitteet pykälää ylemmäs. Kuunnelmat YK ohjelmat (media).
