### ISSUE TITLE
monitoimisuus

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#704]
Ruotsiksi mångprofessionella arbeten ja englanniksi vastaava multiprofessional work, mutta suomeksi käytetään myös muissa asiayhteyksissä, ks. Melindaa. Vaatii määrittelyä/jakoa? Parempi käännös ruotsiksi mahdollisesti mångsyssleri, mutta se ei päde koneista jne.

**Comment by mirmaid** [comment]
Ks. https://github.com/Finto-ehdotus/YSE/issues/4656
