### ISSUE TITLE
Aselajit-hierarkia

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#705]
Aselajit sekä maavoimat / merivoimat / ilmavoimat-hierarkia olisi syytä käydä läpi. Monihierarkiaa esiintyy paljon. Onko tämä ok?`Ovatko yksittäiset joukot ja aselajit ISA maavoimat? Sopisiko näille partof-suhde? Tämänhetkistä hierarkiaa:

maavoimat
. . ilmatorjunta (maavoimat)
. . jalkaväki
. . panssarijoukot
. . pioneerit
. . ratsuväki
. . tykistö
. . viestijoukot
merivoimat
. . sotalaivasto
ilmavoimat
. . laskuvarjojoukot

**Comment by mirmaid** [comment]
YSO-kokous 21.10.2016:
@tpalonen tekee taulukon, jota sen koommin käsitellään.

**Comment by tpalonen** [comment]
Taulukko:
https://docs.google.com/spreadsheets/d/1QvRXDnI4a8gjVBxqSGG-VT-_HcuJEXg2VX_yyYSiHFk/edit#gid=1995844306

**Comment by mirmaid** [comment]
Part-of -suhde kuulostaa ihan järkevältä, tähän voisi vielä kysyä Esa Hämäläisen kantaa. 

Oliko sotilaallisissa organisaatioissa muuta epäselvää kuin tämä kysymys? Itse poistaisin varmaan tästä nuo "jnk mukaan" ryhmittelyt, koska kattavat niin pienen osan alakäsitteistä, enkä tiedä ovatko ihan selkeitäkään.

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/Aselaji

**Comment by YSO-kokous** [comment]
Poistetaan ryhmittelevät käsitteet sotilaalliset organisaatiot -käsitteen alta.
Tutkitaan Wikipediaa ja muita lähteitä ja pohditaan, voisiko ISA-suhteet korvata partof-suhteilla.

**Comment by mirmaid** [comment]
Aselajien alakäsitteille RT aselajit. 

Selvitetään, kannattaako nykyisiä is-a-suhteita muuttaa partOf-suhteiksi. (Mirja / millainen on lopputulos)

**Comment by mirmaid** [comment]
Ilmatorjuntajoukot: en saa selville, kuuluuko nykyään maavoimiin, vai muihinkin puolustushaaroihin. Itse asiassa niin kauan kuin puhutaan Suomesta, aselajit-yläkäsite on YSOn hierarkian kannalta oikein (is-a), kun taas suhde puolustushaaraan pitäisi olla ennemmin partOf (toki vastaavaa hierarkiavirhettä on paljon muuallakin YSOssa). Jos korjataan > partOf, yläkäsitteeksi tulee joko suoraan sotilaalliset organisaatiot, tai maavoimien osalta joko aselajit, tai sitten ne myös samoin (jos ajatellaan, että aselajit viittaa vain Suomen armeijaan).

**Comment by mirmaid** [comment]
Aselajit ok. Korjataan hierarkiavirheet > RT-suhde.
