### ISSUE TITLE
Yksikkö: ongelmallisia tapauksia

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#706]
Joissain tapauksissa yksikkömuodon muodostaminen termille tuntuu ongelmalliselta. Näistä pitäisi tehdä linjauspäätös, jotta yksikkömuodot voitaisiin jatkossa muodostaa systemaattisesti. Kiwistä löytyy linkit tämänhetkisiin poikkeuksiin eli tapauksiin, joissa yksikkömuotoa ei lisätä:

https://www.kiwi.fi/pages/viewpage.action?pageId=54658730

Tässä listaa ongelmatapauksista, joista vaadittaisiin linjanvetopäätös.

1) Eläinlajit ja kasvilajit: yksikkö tarkoittaa tiettyä lajia. Jos esim. heimon nimen muuttaa yksikköön, se saattaa olla tietyn lajin nimi.

2) Käsitteet, jotka viittaavat johonkin ryhmään tai monikolliseen kokonaisuuteen. Kun termi muutetaan yksikköön, se ei enää viittaa käsitteen kokonaisuuteen, vaan yhteen yksilöön tai kokonaisuuden osaan. Tällaisissa tapauksissa yksikkömuodollinen termi ei välttämättä päde hierarkkisesti. 
2.1.) Kielikunnat. "suomalais-ugrilainen kieli" ei ole kielikunta. 
2.2.) Kansojen nimet. Berberi, chileläinen, savolainen.
2.3.) Organisaatiot tai ryhmät. Esim. Jehovan todistajat, metsäveljet.

3) Käsitteet, joiden yksikkömuoto olisi tavalla tai toisella harhaanjohtava tai epäintuitiivinen. Esim. Pyhän Klaaran sisaret, köyhät Klaara-sisaret, Hilbertin ongelmat.

**Comment by mariaforsen** [comment]
Linjaus riippuu myös siitä mitä halutaa yksikkömuotojen lisäämisellä saavuttaa. Jos haluaa lähinnä varmistaa että hakija pääsee perille riippumatta käyttääkö yksikkö vai monikko ja jos halutaan voida sanoa käyttäjille että yksiköllä voi yhtä hyvin hakea niin silloin ei varmaan voida seurata liian tarkasti yllä olevia ohjeita, vaan arvioida tapauksesta tapaukseen palveleeko yksikön lisääminen käyttäjä vai eikö. 

Tässä kannattaa myös huomioida että yksikkömuodot ovat piilotettuja termejä, eli niillä ei ole vaikutusta käyttäjän käsitykseen siitä mitä käsite tarkoittaa jne. (toisin kuin korvatut termit, jotka tähän asti eivät välttämättä ole edes synonyymejä tarkassa mielessä, vaan jotka on otettu että käyttäjä löytäisi perille tai että saataisiin hyvin lähellä toisiaan olevat asiat kätevästi niputettu saman asiasanan alla...) 

Esim. pitäisikö lisätä pöllö termille pöllöt, norsu termille norsut, suomalainen termille suomalaiset jne. (juuri näissä tapauksissa on toki kirjoitusmuodot melkein samat muuten, mutta näin ei aina ole ja olisi hyvä jos käyttäjä saisi näitä tuloksia muodosta riippumatta). 

Missä tilanteessa olisi esim. niin että jos hakija hakee sanalla eskimo, jesuiitta ja saakin eskimot, jesuiitat tms. niin nämä olisi väärin laittaa? Vaikeaa kuvitella sellaista tilannetta? 

Mahdollinen linjaus voisi myös olla että ellei yksikkömuodot lisäämisestä ole haittaa niin se pitäisi lisätä..? Koska hyötyä siitä kai on jos haut entistä useammin johtavat perille..? 

Olisi ehkä myös syytä välttää liian monimutkaisten periaatteiden luomista, koska se tarkoittaa että myös käyttäjien pitäisi niistä tietää ja ymmärtää niitä, eli taas lisää muistamista...

**Comment by mirmaid** [comment]
Kiwistä kopioitu linjaus (https://www.kiwi.fi/pages/viewpage.action?pageId=54658730)

1) Mikäli termin sulkutarkenne on monikossa, sitä ei muuteta yksikköön päätermin mukana. Näin ollen esim. "kalvot (orgaaniset objektit)" käsitteen yksikkömuoto on "kalvo (orgaaniset objektit)".

2) Tieteelliset lajinimet, sukujen nimet jne. (esim. englanninkielisissä labeleissa). Näiden osalta ei kannata yrittääkään keksiä perusmuotoja.

3) Lahkojen, heimojen ym. nimet, esim. "haukikalat", "tilhet", "nautaeläimet". Olisi turvallisinta jättää nämä ilman perusmuotoa. Yksikkömuoto voi viitata eri asiaan.

4) Kansojen nimet englanniksi, esim. "Sami people". Nämäkin kannattaisi jättää ilman perusmuotoa. "Sami person" tuntuisi oudolta ja pelkkä "Sami" on liian epämääräinen. Suomeksi ja ruotsiksi yksikkö lisätään.

5) Monikkoon vakiintuneiden yksilökäsitteiden nimet, esim. tapahtumat tai organisaatiot. Helsingin juhlaviikot, Helsingin silakkamarkkinat.

6) Niin sanotut plurale tantum -sanat eli sanat, joilla on vain monikkomuoto (tai merkitys vain monikkomuodossa). Esim. sakset, housut, valtiopäivät, Porvoon valtiopäivät.

**Comment by mirmaid** [comment]
> 3) Lahkojen, heimojen ym. nimet, esim. "haukikalat", "tilhet", "nautaeläimet". Olisi turvallisinta jättää nämä ilman perusmuotoa. Yksikkömuoto voi viitata eri asiaan.

**Comment by tpalonen** [comment]
Alkukommentissa mainitut ongelmat vielä käsiteltävä.

**Comment by tpalonen** [comment]
Kaikki alkukommenteissa mainitut yksikköön. Tarkennetaan yksikköä koskevia linjauksia aswissa:
https://www.kiwi.fi/display/Asiasanastotjaontologiat/YSOn+kehityslinjaukset

**Comment by tpalonen** [comment]
Aswin linjauksia täsmennetty.
