### ISSUE TITLE
Sulkutarkenteellisten käsitteiden ohjaustermit

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#707]
On herännyt keskustelua, laitetaanko sulkutarkenteellisille käsitteille, joilla on sulkutarkenne, myös sulkutarkenteeton ohjaustermi. Nämä voivat auttaa sellaisissa järjestelmissä, jotka eivät tue ennakoivaa tekstinsyöttöä. Aiheuttaako ongelmia vai onko ok?

Esim.
maaliskuun vallankumous (1848)
maaliskuun vallankumous (1917)

**Comment by mirmaid** [comment]
YSO-kokous 11.1.2017:

Lisätään sulkutarkenteeton muoto. Puuttuviin lisäys automaattisesti.

**Comment by mirmaid** [comment]
Tuliko tämä hoidettua?

**Comment by YSO-kokous** [comment]
Huom. englannin osalta päätetty että sulkutarkenteettomia muotoja ei lisätä.

**Comment by MikkoAleksanteri** [comment]
> YSO-kokous 11.1.2017:
> 
> Lisätään sulkutarkenteeton muoto. Puuttuviin lisäys automaattisesti. @henriyli 

Tämä tehtävä voisi siirtyä Henriltä @joelit :lle

**Comment by mirmaid** [comment]
Onko hyvä, että nämä näkyvät esim. Finton autocomplete-valikossa ja Asterissa? Lisää sotkua valikoissa ja lisääkö myös virheen mahdollisuutta?

Esim. 
bretoni > bretoni (koira)
bretoni > bretonin kieli
bretoni (kieli) > bretonin kieli
bretoni (koira)
bretonin kieli

**Comment by mirmaid** [comment]
Myös: hyväksyntä > hyväksyminen (menettely), hyväksyntä (tarkastus) > hyväksyminen (menettely)

**Comment by mirmaid** [comment]
Samoin käsite, joka ei ole sulkutarkenteellinen, mutta sillä on sama sulkutarkenteellinen ja tarkenteeton ohjaustermi, esim. hakumenettely.

**Comment by YSO-kokous** [comment]
Asiaa käsitelty Finton viikkopalaverissa 1.12.2020: https://www.kiwi.fi/display/ontologiat/2020-12-01+Finto-palvelun+viikkopalaveri

**Comment by mariaforsen** [comment]
Onko siis suunnitelma nyt se että sulkutarkenteettomat muodot lisätään automaattisesti, mutta hidden-labeliksi? Ruotsiksi ei kovin mielellään lisätä enää tarkenteettomia muotoja, koska on tosiaan huomattu että varsinkin joissakin järjestelmissä tämä voikin aiheuttaa lähinnä ongelmia.

**Comment by mirmaid** [comment]
Listaus Joelilta:
- altLabelina preffin sulkutarkenteeton muoto
- altLabelina altLabelin sulkutarkenteeton muoto

Pohdittava onko näistä hyötyä vai pitäisikö poistaa.

**Comment by mirmaid** [comment]
Sprintti 9.4. päätös: jos ei ole teknistä syytä säilyttää/lisätä näitä, poistetaan myös olemassaolevat datasta.

**Comment by mirmaid** [comment]
PÄÄTÖS: Sulkutarkenteettomat ohjaustermit voidaan poistaa. Toteutus: Mirja ja Tuomas pyrkivät tekemään itsenäisesti SPARQL:llä, pyytävät apua jos tarvis.

**Comment by tpalonen** [comment]
Tämmöisellä taikasparklella homma onnistuu:

SELECT *
WHERE {
 ?uri skos:altLabel ?alt1, ?alt2 .
  FILTER (LANG(?alt1) = 'fi' && LANG(?alt2) = 'fi')
  FILTER (STRBEFORE(STR(?alt1), ' (') = STR(?alt2))
}
