### ISSUE TITLE
Näytelmät-käsitteen hierarkia

### ISSUE THREAD

**Issue by MikkoAleksanteri** [NatLibFi/Finto-data#708]
Näytelmät-käsite http://www.yso.fi/onto/yso/p5000 LT kirjalliset teokset.

Ovatko esim. nukkenäytelmät, televisionäytelmät ja speksit kirjallisia teoksia?

Ratkaisuehdotus: siirretään näytelmät yhtä tasoa ylemmäksi (teokset).

**Comment by mirmaid** [comment]
YSO-kokous 11.1.2017:

Siirretään näytelmät, kartat ja julkaisut käsitteen teokset alle.

**Comment by MikkoAleksanteri** [comment]
Toteutettu dataan.
