### ISSUE TITLE
aineistot-käsitteen yläkäsite

### ISSUE THREAD

**Issue by MikkoAleksanteri** [NatLibFi/Finto-data#709]
Ovatko kaikki rooleja?

http://finto.fi/yso/fi/page/p6546

Jos aineistot siirretään olioiden puolelle, voitaisiin esim. käsite mikrodata toteuttaa moniperinnällä kuten YSAssa: http://finto.fi/ysa/fi/page/Y202838

**Comment by mirmaid** [comment]
YSO-kokous 11.1.2017:

Ei muutosta.
