### ISSUE TITLE
Kirjastot, arkistot ja museot - monta merkitystä 

### ISSUE THREAD

**Issue by MikkoAleksanteri** [NatLibFi/Finto-data#710]
Esim. arkistot      http://www.yso.fi/onto/yso/p2336 LT muistiorganisaatiot. 

Kuitenkin alakäsitteenä mm. kuva-arkistot, ääniarkistot, ohjelma-arkistot, nämä eivät luonnollisesti ole muistiorganisaatioita. Sama kirjastojen ja vähemmässä määrin myös museoiden kohdalla.

Tulisiko käsitteet jakaa, esim. 
- arkistot (organisaatiot) 
- arkistot (arkistokokoelmat)

Vastaavat käsitteet jaettu esim. LCSHssa ja Saksan ja Ranskan vastaavissa sanastoissa.

**Comment by YSO-kokous** [comment]
Ei jaeta. Käsitteiden jakamisen ei nähty palvelevan tiedonhakua.
