### ISSUE TITLE
Käsittely-hierarkia: eduskuntakäsittely ja suullinen käsittely 

### ISSUE THREAD

**Issue by satuniininen** [NatLibFi/Finto-data#711]
Tällä hetkellä _eduskuntakäsittely_ ja _suullinen käsittely_ sijaitsevat samassa paikassa kuin esim. _pintakäsittely, lämpökäsittely_ yms. Onko tämä tosiaan paras mahdollinen paikka vai mennäänkö tässä liikaa suomen (ja ruotsin) kielen yhdyssanarakenteen ehdoilla? Toimintana ovat kuitenkin hyvin erityyppisiä, ja tämän seurauksena englanninkielinen hierarkia näyttää aivan poikeuksellisen älyvapaalta.

Toiminnan luonteen perusteella sopisivat hyvin myös esim. menettelyjen alle.

**Comment by mirmaid** [comment]
YSO-kokous 11.1.2017:

eduskuntakäsittely ja suullinen käsittely YK yhteiskunnalliset tapahtumat
