### ISSUE TITLE
Rodut

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#712]
YSAssa ja YSOssa rodut on tulkittu eri tavalla. Kuten tiedämme, rotu on ihmisistä puhuttaessa varsin ristiriitainen käsite. Wiki: "Koska termillä rotu ei ole olemassa yksiselitteistä luonnontieteellistä määritelmää, pyritään koko sanaa välttämään luonnontieteellisessä kielenkäytössä. Osin termin välttäminen perustuu haluttomuuteen kuvata ihmisen (Homo sapiens) biologista diversiteettiä. Sitä korvaamaan on pyrkimys käyttää termejä, esimerkiksi alalaji (subspecies), muunnos (varietas), alamuunnos (subvarietas), muoto (forma) ja alamuoto (subforma)."

YSOssa on ollut ammoisina aikoina jako "rodut (etniset ryhmät)" ja "rodut (roolit)", mutta tämä jako on purettu jo FinnONTOn aikoihin. Sittemmin YSOon on jäänyt yksi rodut-käsite, jolla on suhde YSAn rodut-käsitteeseen. Ja YSOssa "etninen rooli" ja "etniset ryhmät" -käsitteille on lisätty oldlabel "rodut (etniset ryhmät)". YSOn ja YSAn käsitteillä on kuitenkin eri alakäsitteet: YSAssa europidit, mongolidit, negridit, ja YSOssa maatiaisrodut.

Ks. myös issue #572

**Comment by mirmaid** [comment]
YSO-kokous 11.1.2017:

Ei muutosta.
