### ISSUE TITLE
Erityinen tuki, varhainen tuki, EU-tuet ynnä muut tuki-käsitteet

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#713]
YSOssa on tukiloppuisia käsitteitä paljon ja näitä on eri puolilla hierarkiaa. Sosiaalietuudet alla on useita: asumistuki, elatustuki, hoitotuki jne. Toisaalta erityinen tuki ja varhainen tuki ovat keskinäistä toimintaa. Ja EU-tuet taas ovat taloudellisten tuotosten alla.

EHDOTUS: Olisiko hyvä koota kaikki tuet yhden käsitteen alle? "Tuet" tjsp?

**Comment by mirmaid** [comment]
YSO-kokous 11.1.2017:

Ei muutosta.
