### ISSUE TITLE
Akustiikka -koostekäsite

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#714]
akustiikka (erikoisalat)
akustiikka (fysikaaliset ilmiöt)

Tätä ei ole jostain syystä käsitelty koostekäsitteiden yhteydessä. Tai en ainakaan löytänyt mistään merkintää.

Säilytetäänkö vaiko ei?

**Comment by mirmaid** [comment]
YSO-kokous 11.1.2017:

Ehdotettu yhdistämistä, kysytään MUSAn näkemystä.

**Comment by mirmaid** [comment]
MUSAssa huomautus: (1) Ääntä ja äänen ominaisuuksia tutkiva tieteen (mekaniikan) ala, (2) tilassa kuuluvaan tai soittimen tuottamaan ääneen liittyvä fysikaalinen ominaisuus.

**Comment by mirmaid** [comment]
Kaikkia vastaavia termejä ei kuitenkaan olla jaettu, esim. dynamiikka, mekaniikka, estetiikka.

**Comment by mirmaid** [comment]
YSA-kokouksessa päätetty yhdistämisestä.
