### ISSUE TITLE
Sulkutarkenteet: rakenne, taide, teatteri

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#715]
Linjauksemme mukaan yksikkö/monikko-eroisilla käsitteillä pitäisi olla sulkutarkenteet. Nyt pitäisi siis löytää sopivat sulkutarkenteet seuraaville käsitepareille:

rakenne, rakenteet
taide, taiteet
teatteri, teatterit

**Comment by mariaforsen** [comment]
Meillä oli ainakin jossain vaiheessa myös sellainen sääntö että jos käsite on selkeä ilman tarkenteita ei tarvitse laittaa, eli että monikkomuodoille ei välttämättä tarvitse laittaa tarkenteita jos/kun siinä ei ole väärinkäsityksen vaaraa. Ovatko rakenteet ja taiteet sellaisia?

**Comment by mirmaid** [comment]
Alustavaa pohdintaa rakenne/rakenteet:

rakenne (ominaisuudet)
rakenteet (rakennustekniikka)
rakenteet (kielitiede/kielioppi)
rakenteet (yhteiskuntatieteet/sosiaalitieteet) ST valtarakenteet (sen YK nyt yhteiskunnalliset järjestelmät)

**Comment by YSO-kokous** [comment]
YSO-kokous totesi nämä hyviksi ehdotuksiksi:
rakenne (ominaisuudet)
rakenteet (rakennustekniikka)
rakenteet (kielitiede)

Mirjalle pohdittavaksi:
sosiaaliset rakenteet/sosiaalirakenteet? alt: rakenteet (sosiaaliset rakenteet) 
valtarakenteet YK "sosiaaliset rakenteet"

Mirjan Aalto-linkki: tämän kuvaamiseen voidaan käyttää YSOsta jo löytyvää tietorakenteet-käsitettä.
http://finto.fi/yso/fi/page/p25964

**Comment by mirmaid** [comment]
Teatteri - ratkaistu
Taide https://github.com/Finto-ehdotus/YSE/issues/6700
Rakenne https://github.com/Finto-ehdotus/YSE/issues/6544

**Comment by mirmaid** [comment]
Kaikki ratkaistu.
