### ISSUE TITLE
virheet ST, viat...

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#716]
virheet ST nyt:     

```
geenivirheet
hoitovirheet
kielivirheet
lapsukset
mittausvirheet
ohjelmointivirheet
pysäköintivirheet
rakennusvirheet
taittovirheet
tavaran virhe
tuomiovirheet
virkavirheet
```

Näistä ainakin geenivirheet ja taittovirheet (ehkä myös tavaran virhe) ovat sellaisia että eivät sovi misstag-sanan alle (nyt fel, mutta pitäisi olla fel (misstag) tms.) Ehkä yhteistä se että nämä virheet eivät ole ihmisten tekemiä... Olisiko mitenkään mahdollista että nämä olisivat esim. sanan viat alla? 

Ks. MOT: virhe...
1. erheellinen, väärä, viallinen suoritus, erehdys, hairahdus, lapsus; sellaisen tulos. 
2. vajavuutta, vajaalaatuisuutta, -kuntoisuutta tms. aiheuttava seikka, vika. Maku-, pintavirhe. Virhe tuotteen värissä. Koiran rakenteen virheet. Kaikilla meillä on omat virheemme. 

ja ks. MOT: vika...

Ei kai virheet-asiasana olisi tässä tarkoitus käyttää kakkomerkityksessä, koska siihen jo vissiin viat-asiasana olisi tarkoitus käyttää vai..? Vai miten olisi näitä oikeastaan tarkoitus käyttää? Ruotsiksi ei voida tätä ratkaista ellei ole ensin selkeät rajat suomen termille. Lisäongelmia ruotsiksi tuo se että sanastossa on myös erehdys.

**Comment by mirmaid** [comment]
YSO-kokous 11.1.2017:

Ehdotettu geenivirheet ja taittovirheet YK biologiset ominaisuudet.

**Comment by mirmaid** [comment]
taittovirheet nyt YK silmätaudit

taudit nyt YK biologiset ilmiöt, voisiko geenivirheet siirtää nyt samaan? Mielestäni samankaltainen asia.

tavaran virhe YK viat?

**Comment by mirmaid** [comment]
YSO-kokous 24.3.2017:

- taittovirheet nyt YK silmätaudit > tämä ok
- geenivirheet YK biologiset ominaisuudet
- tavaran virhe YK viat
