### ISSUE TITLE
ammunta

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#717]
Melinda-käytön ja ryhmän (sota) perusteella tämä on ontologian puolella tulkittu liian kapeasti. Käytetty paljon mm. kouluampumisten ja maanpuolustuksen yhteydessä (ysa-terminä). Löytyisikö neutraalimpi yläkäsite?

**Comment by mirmaid** [comment]
YSO-kokous 21.10.2016:
LT liikuttaminen, RT urheilu

**Comment by mariaforsen** [comment]
Mikä ongelma tässä enää on? Ruotsin osalta näyttää nyt hyvältä.
