### ISSUE TITLE
radat

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#718]
Nyt huomautus ontologian puolella: Kilpailujen tai harjoitusten suorituspaikka. Mutta Melindassa on paljon käytetty myös esim. junaradoista jne. Ja termi radat itsessään ilman tarkennetta on kyllä hyvin neutraali, joten riski on suuri että tämä miten vain käytetään vastoin tuota huomautusta.

**Comment by tpalonen** [comment]
PÄÄTÖS 10.6.2016:
- radat LT ihmisen määrittämät paikat; poistetaan huomautus
- ampumaradat LT radat
- kilparadat LT radat + LT liikuntapaikat 
- kuntoradat LT radat + LT liikuntapaikat
- luistinradat LT radat + LT liikuntapaikat
- moottoriradat LT radat + LT liikuntapaikat
- raviradat LT radat + LT liikuntapaikat
- tekojääradat LT radat + LT liikuntapaikat
