### ISSUE TITLE
eritys

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#719]
Onko tapahtunut jonkinlainen virhe/ei loppuun asti tehty juttu? Kun jako on poistettu, mutta ei kai tarkoitus ollut vain eläinten eritys ottaa mukaan. Eli huomautus (ei sääntöjen mukainen myöskään) pitäisi varmaan poistaa ja ohjaustermi eritys (eläinten).

**Comment by mariaforsen** [comment]
Ks. #418

**Comment by tpalonen** [comment]
Asia korjattu.
