### ISSUE TITLE
infiltraatio

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#720]
Minkä takia on laittetu RT biologia ontologian puolella? Englannin termi olisi ehkä myös syytä päivittää, koska tarkoitus ei kai ollut että tämä olisi vain biologista. Melindassa lähinnä hydrologista. Jaon purkamisen jälkeen ei ihan loppuun käsitelty?

**Comment by tpalonen** [comment]
PÄÄTÖS 10.6.2016:
- poistetaan RT
- Satu selvittää englanninkielisen termin

**Comment by satuniininen** [comment]
Enkku ok

**Comment by mariaforsen** [comment]
Poistin RT biologia (oli jostain syystä vielä näkyvissä).
