### ISSUE TITLE
asetyylikoliini, japanilaiset kielet kahdesti

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#722]
Nyt tuplana YSOssa

**Comment by osma** [comment]
japanilaiset kielet -tapauksesta tuli myös noottia finto-postin kautta:
> YSO-sanastossa "japanilaiset kielet" on kahdesti. Toisen voisi merkata owl:deprecated true:ksi. http://finto.fi/yso/fi/page/p19176 http://finto.fi/yso/fi/page/p28440

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 17.10.16:

-asetyylikoliini: yhdistetään, jätetään vanhemman uri, lisätään uudemman yläkäsitteet ja suhteet ja ryhmät, vanhemmalta korvattu termi.

**Comment by tpalonen** [comment]
Tehty päätetyt muutokset.
@mariaforsen: tarkistatko vielä ruotsinkielisen termin japanilaiset kielet osalta? Näillä kahdella käsitteellä oli eri termit ruotsiksi, japanska språk ja japoniska språk.
