### ISSUE TITLE
vaihtolämpöisyys, yksineuvoisuus

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#723]
Todettu YSO-kokouksessa että hierarkiassa on nyt virhe ruotsiksi, koska nuo termit ovat muodossa enkönade arter ja växelvarma djur. Mietittiin voisiko suomeksi muuttaa nuo muotoon vaihtolämpöiset lajit ja yksineuvoiset lajit tms. Tai sitten pitänee sijoittaa johonkin muualle hierarkiassa, esim. biologiset ilmiöt?

**Comment by mirmaid** [comment]
YSO-kokous 11.1.2017:
Muutosehdotus YSAan: vaihtolämpöisyys KÄ vaihtolämpöiset eläimet

Tutkitaan yksineuvoisuus ja kaksineuvoisuus/kaksikotisuus.

**Comment by mirmaid** [comment]
Vaihtolämpöisyys https://github.com/Finto-ehdotus/YSE/issues/5086

**Comment by mirmaid** [comment]
Kaksineuvoisuus/hermafroditism YK biologiset ominaisuudet. Yksineuvoisuus-termiä ei ole käytetty Melindassa lainkaan (ei myöskään enkönade arter), mutta varmaan ei voi poistaakaan (?) ja tuntuisi hassulta laittaa nämä eri paikkoihin.

**Comment by mirmaid** [comment]
Yksineuvoisuus https://github.com/Finto-ehdotus/YSE/issues/5100

**Comment by mariaforsen** [comment]
Muutos tehty YSAssa jo 5.6.2017, mutta edelleen väärin YSOssa, kuka toteuttaa?
