### ISSUE TITLE
palveluskoirat

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#724]
Hierarkia sekaisin, eikä koira ole yläkäsitteenä? Todettu YSO-kokouksessa, mutta jäi odottamaan jatkotoimenpiteitä.

**Comment by MikkoAleksanteri** [comment]
Yläkäsitteenä siis _eläimet_, ryhmittelevänä _eläimet käytön mukaan_

Eikö oikeastaan palveluskoira ole rooli? Sama pätee moniin eläimet-käsitteen alakäsitteisiin, esim. koe-eläimet
kotieläimet, kulkukissat, kulkukoirat, löytöeläimet jne. Olisiko @kseppala näkemystä asiaan, FinnONTOn periaatteet näissä?

**Comment by kseppala** [comment]
Siteeraan Eeron kanssa kirjoittamaani raporttia: Rooliksi luokittelua on pyritty rajaamaan niin, että luokkaan sisällytetään vain sellaiset käsitteet, jotka eivät ole muiden kuin toisten roolien ensisijaisia yläkäsitteitä ja joiden sijoittaminen muualle hierarkiaan edellyttäisi tarpeetonta moniperintää tai käsitteiden keinotekoista erottelua, mutta ei siltikään takaisi kattavan kuvauksen aikaansaamista. Esimerkiksi aineiston roolissa voivat olla hyvin erilaiset fyysiset objektit ja aineettomat tuotokset. Jos aineistolle annettaisiin yläkäsite sekä fyysisten objektien hierarkiasta että aineettomien tuotosten hierarkiasta, aineisto perisi molempien yläkäsitteiden piirteet. On todennäköistä, että tällaisen periaatteen noudattaminen aiheuttaisi virheitä, sillä käsitettä, jolle molempien hierarkiahaarojen piirteet periytyisivät, ei aina ole aidosti olemassa. Myöskään käsitteiden keinotekoinen eriyttäminen niin, että toinen aineisto-käsite sijoi-tettaisiin fyysisten objektien hierarkiaan ja toinen aineettomien tuotosten hierarkiaan ei ole perus-teltua, koska tällaista jakoa ei ole suomen tai ruotsin kielessä, jotka muodostavat YSO/Allson käsi-tejaon alkuperäisen perustan. Vain yhteen hierarkiaan rajoittuvat käsitteet, jotka voidaan tulkita rooleiksi, on kuitenkin saatettu sijoittaa myös muuhun kuin roolihierarkiaan, jos kyseiselle käsit-teelle on näin löytynyt luonteva paikka (esim. kotieläimet eläinten hierarkiassa).
Omasta mielestäni myös vain yhteen hierarkiaan sijoittuvat käsitteet kuten nuo palveluskoirat voisi sijoittaa rooli-hierarkiaan.

**Comment by mirmaid** [comment]
Minusta tämä liittyy laajemmin siihen vaikeaan rajanvetoon mitä tehdään ominaisuuksien ja olioiden välillä. Koirilla on useita "tehtäviä" joita voidaan kuvata näin, ja osa niistä voi viitata myös tiettyihin rotuihin. Palveluskoirat, ajokoirat, noutajat jne. viittaavat enemmän tai vähemmän paitsi tiettyä toimintaa mahdollisesti suorittaviin koiriin, myös tiettyyn käyttöön alunperin jalostettuihin rotuihin. Noutaja voi olla koiran rooli, mutta vastaava rotukategoria terrierit ei.
 
Ihmisen toimintaan liittyvät käsitteet ovat nyt rooli-hierarkiassa. Se on yksi mahdollinen näkökulma asiaan - farmaseutti on ominaisuus. En itse näe että olisi mahdotonta nähdä se myös olio-hierarkiassa ja käsitellä ammatit yhteiskunnallisina objekteina kuten nyt ovat arvonimet.
 
Ongelmahan tässä on se, että näihin ratkaisuihin kertakaikkiaan on useampia kuin yksi mahdollinen lähestymistapa. Mielestäni tällä hetkellä olio-hierarkiassa on loputtomasti käsitteitä jotka voisi mieltää myös rooleiksi.

**Comment by mirmaid** [comment]
https://github.com/NatLibFi/Finto-data/issues/822

**Comment by mirmaid** [comment]
_palveluskoirat_-termillä on YSAssa ST:nä palveluskoirarotuja

**Comment by YSO-kokous** [comment]
Lisätään ohjaustermi palveluskoirarodut KÄYTÄ palveluskoirat
Lisäksi palveluskoirille huomautus: "Tarkoitettaessa koiria, jotka tekevät työtä, rodusta riippumatta, käytetään käsitettä [työkoirat]."

**Comment by ilona-x** [comment]
Palveluskoiraoikeudet omaavat rodut
https://www.virkku.net//index.cfm?frwd=Yes&template=dynamic.cfm&sivuId=7&sivualueId=6
