### ISSUE TITLE
sabotaasi, tuhotyö

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#725]
Onko merkitys ja käyttö Melindassa nyt selkeä ja onko todella tarvetta molempiin? Tuhotyö löytyy tietty  Suomen laista (sabotaasi ei), mutta ei MOTista. Näyttää olevan jonkin verran päällekkäinen/sekava käyttö myös Melindassa. Ruotsiksi on vain yksi sana: sabotage, riippumatta laista tms. ja käyttö on laaja sekä sotilaallisesta, poliittisesta yms. että esim. yksityishenkilön tekemästä jne. Nykyiset sulkutarkenteet eivät ole ok ruotsiksi. Kuvailija tuskin osaa päätellä mikä niistä pitäisi milloinkin käyttää. Joten jos molemmat todella halutaan pitää niin tarvittaisiin tarkka määritelmä ja käyttösuositus niin että voidaan tehdä paremmat tarkenteet ruotsiksi. Vahingonteko=skadegörelse on erikseen mukana.

**Comment by mirmaid** [comment]
YSO-kokous 11.1.2017:

ruots. sabotage (brott) ja sabotage (politisk eller militär). Lisätään selitykset molemmilla kielillä.

**Comment by mirmaid** [comment]
Rikoslaki, 34 luku (Yleisvaarallisista rikoksista): Tuhotyö
Joka
1) sytyttää tulipalon,
2) räjäyttää jotakin taikka
3) saa aikaan vedentulvan tai luonnontilan muun mullistuksen
siten, että teko on omiaan aiheuttamaan yleistä hengen tai terveyden vaaraa taikka että siitä on yleistä erittäin huomattavan taloudellisen vahingon vaaraa, on tuomittava tuhotyöstä vankeuteen vähintään neljäksi kuukaudeksi ja enintään neljäksi vuodeksi.
Tuhotyöstä tuomitaan myös se, joka omaisuutta vahingoittamalla tai tuhoamalla taikka tuotanto-, jakelu- tai tietojärjestelmän toimintaan oikeudettomasti puuttumalla aiheuttaa vakavan vaaran energiahuollolle, yleiselle terveydenhuollolle, maanpuolustukselle, oikeudenhoidolle tai muulle näihin rinnastettavalle yhteiskunnan tärkeälle toiminnolle.
Yritys on rangaistava.

**Määritelmäehdotus**: Tuhotyö on rikoslain mukaan yleisvaarallinen rikos, joka aiheuttaa yleistä hengen tai terveyden vaaraa, huomattavan taloudellisen vahingon vaaraa, tai vakavaa vaaraa energiahuollolle, yleiselle terveydenhuollolle, maanpuolustukselle, oikeudenhoidolle tai muulle näihin rinnastettavalle yhteiskunnan tärkeälle toiminnolle.

**Comment by mirmaid** [comment]
Sabotaasi
Kielitoimiston sanakirja: vars. sotilaallisena t. pol. voimakeinona käytettävä tahallinen vahingonteko, tihutyö, tuholaistoiminta, tuholaisuus.

**Määritelmäehdotus**: Varsinkin sotilaallisena tai poliittisena voimakeinona käytettävä tahallinen vahingonteko. (Lähde: Kielitoimiston sanakirja)

**Comment by YSO-kokous** [comment]
Lisätään määritelmät YSAssa. Sabotaasin määritelmä muotoon: Sotilaallisena tai poliittisena voimakeinona käytettävä tahallinen vahingonteko.
