### ISSUE TITLE
Haamilaiset kielet

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#726]
Seemiläis-haamilaisten kielten nimitys on muuttunut muotoon afroaasialaiset kielet. Wikipedia: "Kielikuntaa on aiemmin kutsuttu myös seemiläis-haamilaisiksi kieliksi, mutta nimityksestä on nykyisin luovuttu, koska kielten jaolla seemiläisiin ja haamilaisiin kieliin ei ole kielitieteellistä perustetta."

Nimitys on YSOssa jo muutettu. Hierarkiasta löytyy kuitenkin vielä vanhentunut käsite haamilaiset kielet, jonka alla on useita kieliä: berberikielet, egyptin kieli, hausan kieli, oromon kieli, somalin kieli. Nykykäsityksen mukaan afroaasialaisissa kielissä ei ole mitään erillistä haamilaista haaraa. Wikipedia: "The Hamitic languages were classified as including the Berber, Cushitic and Egyptian branches. However, since these branches have not been shown to form an exclusive (monophyletic) phylogenetic unit of their own, separate from other Afroasiatic languages, linguists no longer use the term in this sense. Each of these branches is instead now regarded as an independent sub-group of the larger Afroasiatic family."

EHDOTUS: poistetaan käsite "haamilaiset kielet" ja siirretään sen alakäsitteet suoraa afroaasialaiset kielet alle. Lisätään "haamilaiset kielet"-käsitteelle replacedby-suhde afroaasialaisiin kieliin.

**Comment by mirmaid** [comment]
YSO-kokous 11.1.2017:
Poistetaan käsite "haamilaiset kielet" ja siirretään sen alakäsitteet suoraa afroaasialaiset kielet alle. Lisätään "haamilaiset kielet"-käsitteelle replacedby-suhde afroaasialaisiin kieliin.

Sama YSAssa.

**Comment by tpalonen** [comment]
HUOM! YSAssa edelleen haamilaiset kielet. @mirmaid
