### ISSUE TITLE
Testit: tapahtumia vai objekteja?

### ISSUE THREAD

**Issue by MikkoAleksanteri** [NatLibFi/Finto-data#727]
Ks.

http://finto.fi/yso/fi/page/p3971

KÄYTETTÄVÄ TERMI testit
YLÄKÄSITE 

```
kokeet
```

ALAKÄSITTEET   

```
AUDIT
Behavioural Inattention Test
biotestit
geenitestit
huumetestit
kuntotestit
Mini-Mental State Examination
psykologiset testit
Turingin testi
vieritestit
```

ASSOSIATIIVISET KÄSITTEET  

```
tarkastus
testaus
```

KUULUU RYHMÄÄN    

```
55 Psykologia
56 Tiede. Tutkimus
```

MUUNKIELISET TERMIT 
tests   

englanti
test    

ruotsi

**Comment by YSO-kokous** [comment]
Käydään läpi testit-hierarkian alaiset yksilökäsitteet ja tutkitaan, löytyisikö niille parempi paikka objektihierarkiasta, esim. menetelmät-hierarkiasta.

**Comment by mirmaid** [comment]
Testit YK yhteiskunnalliset objektit, ei muita muutoksia.
