### ISSUE TITLE
Oikeudelliset tapahtumat: oikeudenkäynti, rikosprosessi jne

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#728]
Oikeudellisissa tapahtumissa on läpikäytävää. Esim. rikosprosessin alakäsitteet eivät ole ISA-suhteisia alakäsitteitä rikosprosessille. Samoin rikosprosessi ISA oikeudenkäynti ei ole pätevä. Kokonaisuus pitää käydä läpi ja tehdä ehdotus muutoksista.

Edit 19.5.2016:
- Pidättäminen on siirretty pois rikosprosessista, LT pakkokeinot. Onko pakkokeinot yläkäsite järkevä?
- Rikosprosessi siirrettiin LT oikeudelliset tapahtumat
- Siviiliprosessi siirrettiin LT oikeudelliset tapahtumat

**Comment by mirmaid** [comment]
Wikipedia: _Oikeudenkäynnillä rikosasiassa tarkoitetaan laajassa mielessä tuomioistuinkäsittelyn lisäksi myös sitä edeltävää rikoksen tutkintavaihetta._ Eli vähän niin ja näin, oliko tuo _oikeudenkäynti_ yläkäsitteenä väärin. Siihen pitäisi ainakin olla RT-suhde näistä prosesseista. Nykyiset rikosprosessin alakäsitteet voisivat olla partOf-suhteessa rikosprosessiin ja LT voisi olla oikeudelliset tapahtumat.

**Comment by mirmaid** [comment]
EIF?

**Comment by ilona-x** [comment]
oikeudenkäynti | oikeusprosessi | oikeudenkäyntimenettely | prosessi | tuomioistuinmenettely
https://tieteentermipankki.fi/wiki/Oikeustiede:oikeudenk%C3%A4ynti

rikosprosessi | rikosasia | rikosoikeudenkäynti
https://tieteentermipankki.fi/wiki/Oikeustiede:rikosprosessi

siviiliprosessi
riita-asian oikeudenkäynti
https://tieteentermipankki.fi/wiki/Oikeustiede:siviiliprosessi

**Comment by YSO-kokous** [comment]
oikeudenkäynti RT rikosprosessi, siviiliprosessi
esitutkinta YK oikeudelliset tapahtumat + partof rikosprosessi
vangitseminen YK oikeudelliset tapahtumat + partof rikosprosessi

Kysytään OIKO-ontologian ylläpidon kantaa YSOn nykyhierarkiaan (siviiliprosessi, rikosprosessi, pakkokeinot alakäsitteineen jne): https://www.kiwi.fi/display/Finto/Sanastojen+ja+ontologioiden+vastuutahot
Jos pakkokeinojen alakäsitteet säilyvät sellaisenaan on pakkokeinot siirrettävä toiminta-hierarkiaan.

**Comment by mirmaid** [comment]
Toteutetaan päätetyt muutokset. Verrataan hierarkiaa OIKOon ja yritetään sen ja pakkokeinolain avulla siistiä hierarkiaa.

**Comment by mirmaid** [comment]
OIKOssa: 
tekninen tarkkailu YK tarkkailu
telekuuntelu YK kuunteleminen
televalvonta YK valvonta

itseapu, pidättäminen ja tutkintavankeus YK pakkokeinot

Pakkokeinolaissa mainitaan itseavun ja pidättämisen lisäksi esim. vangitseminen, joka ei kuitenkaan kummassakaan sanastossa ole pakkokeinojen alakäsite. OIKOn hierarkia heijastelee mahdollisesti vanhempaa YSO-hierarkiaa, ei välttämättä erityistä selvitystä näistä käsitteistä. Pakkokeinot on OIKOssa rajoitusten alakäsite (olio-hierarkiassa).

YSOssa pakkokeinot on nyt toimenpiteiden alla toiminta-hierarkiassa. Teknisellä tarkkailulla on tuplahierarkia pakkokeinot & tarkkailu. Telekuuntelulla ei ole suhdetta kuuntelemiseen (tuplahierarkia mahdollinen). Televalvonnalla on triplahierarkia, joka on ok, mutta keskinäinen toiminta yläkäsite voisi olla yhtä lailla kahdella muullakin. Tämän voisi johdonmukaistaa. 

Vangitseminen ja takavarikko olisi varmaankin syytä siirtää pakkokeinojen alakäsitteeksi, jos pakkokeinojen osalta ei tehdä muutoksia. Rajoitukset-yläkäsite ei vaikuta paremmalta kuin toimenpiteet.

Kielitoimiston sanakirja: pakkokeino: Oik. lain suojaamiin yksilön etuihin puuttuvia **toimenpiteitä**, joita käytetään rikostutkinnassa.

Wikipedia: Pakkokeinot ovat pakkokeinolaissa esitutkintaviranomaisen käyttöön annettuja **menetelmiä**, joilla oikeutetaan muutoin lailla suojatut puuttumiset henkilöihin ja omaisuuteen, kun se on esitutkinnassa tarpeen.

Menetelmät tuntuu luontevalta yläkäsitteeltä "keinot"-käsitteelle, mutta jos siirretään, alakäsitteet kannattaa siirtää oikeudellisiin tapahtumiin tai keskinäiseen toimintaan (itseasiassa muodoltaan nämä ovat suomeksi enemmän aktiivista toimintaa kuin tapahtumia, joissa ei olisi varsinaista suorittajaa, mutta samoin on osa muistakin oikeudellisten tapahtumien alakäsitteistä). Lisäksi RT pakkokeinot.

Kielitoimiston sanakirja: keino: toimenpide, menettely t. mahdollisuus jnk toteuttamiseksi t. saavuttamiseksi, toiminta-, menettelytapa, menetelmä, neuvo, konsti.

**Comment by mirmaid** [comment]
vangitseminen ja takavarikko YK pakkokeinot
pakkokeinot: lisätään YK keskinäinen toiminta (pois televalvonnalta)
