### ISSUE TITLE
Sosiaalinen yrittäjyys ja yhteiskunnallinen yrittäjyys

### ISSUE THREAD

**Issue by satuniininen** [NatLibFi/Finto-data#730]
Eivätkö nämä tarkoita molemmat samaa asiaa? Melindassa sosiaalista yrittäjyyttä on käytetty jonkin verran aineistoissa, jotka käsittelevät esim. kollegiaalisuutta tai sosiaalisen median käyttöä yritystoiminnassa, mutta se kai ei vielä varsinaisesti tee yrittämisestä luonteeltaan erityisen sosiaalista. 

Näyttäisi myös siltä, että silloin kun kuvailtava aineisto on ollut englanniksi ja aiheena social entrepreneurship, niin asiasanaksi on herkästi laitettu sosiaalinen yrittäjyys yhteiskunnallisen sijaan, vaikka englanniksi näiden välillä ei varsinaisesti tehdä eroa.

Voisiko käsitteet yhdistää?

**Comment by mirmaid** [comment]
Yhdistetty YSAssa
