### ISSUE TITLE
agentiivisuus

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#731]
Huomautus: Tarkoittaa toiminnallisuutta ja toimijuutta. Agentiivisuuteen liitetään usein myös intentionaalisuus, tajunnallisuus ja tapahtuman kontrollointi.

YSA-kokous 1/2016 päätti lisätä sulkutarkenteen (kielitiede) ja tutkittavaksi jäi mitä tehdään filosofian agentiivisuudelle. Käytetty Melindassa. LCSH: Agent (Philosophy) ja Action (Philosophy). YSAssa on myös toimijuus, Allärs: agentskap.

Voiko toimijuus-termiä/käsitettä käyttää filosofian yhteydessä (agentiivisuus (filosofia) KÄ toimijuus)? Jos ei, mikä olisi toimiva ratkaisu huomioiden myös ruotsinkielisen muodon (@mariaforsen)?

**Comment by mariaforsen** [comment]
Ruotsiksi ei tarvita näitä lisää, agentivitet ja agentskap ovat riittäviä.

**Comment by MikkoAleksanteri** [comment]
Lähteitä:

http://plato.stanford.edu/entries/agency/

https://en.wikipedia.org/wiki/Agency_%28philosophy%29 (suom. vastine: https://fi.wikipedia.org/wiki/Toimijuus)

Toimijuus-käsitettä on käytetty kuvailuss yleisemmin muun kuin filosofian yhteydessä. Näyttäisi kuitenkin olevan pohjimmiltaan samasta juuresta versoneista asioista. Ratkaisuehdotus:

**agentiivisuus (filosofia) KÄ toimijuus**
