### ISSUE TITLE
Esitykset

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#733]
Esitykset ovat tällä hetkellä kulttuurisia objekteja. Pikemminkin ne ovat tapahtumia. Pitäisikö ne siis siirtää tapahtumiin? 

Otimme jo askeleen tätä ratkaisua kohti päättämällä 13.5.2016 siirtää kantaesitykset esitysten alle.

**Comment by MikkoAleksanteri** [comment]
YSO-kokous:

hyväksytään

**Comment by tpalonen** [comment]
Siirsin "esitykset" "yhteiskunnalliset tapahtumat"-käsitteen alle.
