### ISSUE TITLE
TSK-palautetta YSO-käsitteisiin

### ISSUE THREAD

**Issue by MikkoAleksanteri** [NatLibFi/Finto-data#735]
Feedback from vocab: YSO
Hei, MAO-ontologian täydennysprojektin asiantuntijaryhmissä tehtiin seuraavat kehityehdotukset YSOon

1) työstö (p1542) Ehdotus: Vaihdetaan yläkäsitteeksi 'muokkaus' (nyt yläkäsite on 'toisenlaiseksi muuttaminen'), koska se on täsmällisempi yläkäsite. Vrt. MAO/TAOn 'työstö'-käsitteeseen, joka on sijoitettu 'kohteen mekaanisen muokkauksen' alakäsitteeksi.

2) sepeli (p18760) Vaihdetaan yläkäsitteeksi 'kiviaines'. Nykyinen yläkäsite 'tienpäällysteet' on liian suppea. 

3) entistäminen (p18319) Vaihdetaan yläkäsitteeksi 'ylläpitävä muuttaminen', koska Museoviraston asiantuntijoiden mukaan entistäminen on luonteeltaan ylläpitävää eikä toisenlaiseksi muuttamista.

4) restaurointi (ks. entistäminen p18319) Ehdotetaan lisättäväksi 'restaurointi' omana käsitteenään 'ylläpitävän muttamisen' alakäsitteeksi (nyt restaurointi on YSOssa ohjaustermi entistämisen kohdalla). Museoviraston asiantuntijoiden mukaan restaurointi on oma käsitteensä entistämisen ja konservoinnin rinnalla.

5) parvekkeet (p16115) Muutetaan YSOssa käsitteen 'parvekkeet' yläkäsitteeksi 'rakennusosat' (nyt yläkäsitteenä virheellisesti 'runkorakenteet'). MAOssa samantapaiset käsitteet 'aitiot' ja 'lehterit', joiden yläkäsitteenä on 'rakennusosat'.

6) tyyppitalot (p22543) Muutetaan YSOssa käsitteen 'tyyppitalot' yläkäsitteeksi 'rakennukset', koska kaikki tyyppitalot eivät ole asuinrakennuksia (nyt yläkäsitteenä 'omakotitalot'). 

7) rakennusperintö (p11034) Nykyistä yläkäsitettä 'kulttuuriset järjestelmät' täsmällisempi yläkäsite on 'kulttuuriperintö'. 

 8) maskeeraus (p26) Nykyinen yläkäsite on 'skenografia', mutta asiantuntijoiden mukaan maskeeraus ei ole skenografiaa. Muutimme TAOon yläkäsitteeksi 'taiteellinen luonti', joka on myös 'skenografian' yläkäsite. 

9) moderni tanssi (p15266) Nykyinen yläkäsite on 'nykytanssi', mutta 'moderni tanssi' ei ole eräänlaista nykytanssia. Modernin tanssin yläkäsitteen pitäisi olla 'tanssi (taidelajit)'.

10) yhdyskuntasuunnittelu (p10194) Yhdyskuntasuunnittelun ja sen alakäsitteiden suhde ei vastaa alan käsitystä näiden käsitteiden välisistä suhteista. Museoviraston asiantuntijoiden mukaan 'maankäytön suunnittelu' on näistä käsitteistä laajin, ja se pitää sisällään myös esimerkiksi vesialueiden suunnittelun. Siksi MAOssa muutettiin hierarkia niin, että yläkäsite on 'maankäytön suunnittelu' ja sen alakäsitteitä ovat 'kaupunkisuunnittelu', 'kuntasuunnittelu', 'liikennesuunnittelu', 'maakunnan suunnittelu', 'seutusuunnittelu', 'valtakunnalliset alueidenkäyttötavoitteet', 'yhdyskuntasuunnittelu' ja 'yhteissuunnittelu'. Ehdotamme YSOonkin muutettavaksi 'yhdyskuntasuunnittelun' sekä sen nykyiset alakäsitteet 'maankäytön suunnittelun' alakäsitteiksi. 

Ystävällisin terveisin Mari

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 10.6.2016:

1) työstö (p1542) vaihdetaan yläkäsitteeksi 'muokkaus'
2) sepeli (p18760) Vaihdetaan yläkäsitteeksi 'kiviaines', nykyiset LT:t RT:ksi. (tehdään issue käsitteen "kaivannaiset" alakäsitteistä)
3) -> käsitellään toiminta-käsitteen uudistamisen yhteydessä, ks. issue #754 
4) -> tuottaa haasteita ruotsi- ja englanninkielen kannalta, ei eroa käsitteillä. Mietitään lisää...
5) parvekkeet (p16115) muutetaan YSOssa yläkäsitteeksi 'rakennusosat'
6) tyyppitalot (p22543) Muutetaan YSOssa käsitteen 'tyyppitalot' yläkäsitteeksi 'rakennukset'
7) rakennusperintö (p11034) yläkäsite 'kulttuuriperintö'. 
8) maskeeraus (p26) yläkäsitteeksi 'taiteellinen luonti', RT skenografia
9) moderni tanssi (p15266) yläkäsite 'tanssi (taidelajit)'.

**Comment by MikkoAleksanteri** [comment]
10) -> vaatii taustatyötä, @tpalonen selvitää asiaa

**Comment by tpalonen** [comment]
10) Ehdotan, että muutetaan hierarkia muotoon:

maankäytön suunnittelu
. . liikennesuunnittelu
. . kaupunkisuunnittelu
. . maakunnan suunnittelu
. . seutusuunnittelu
. . yhdyskuntasuunnittelu

Lisäksi: yhteissuunnittelu LT suunnittelu tavan mukaan; poistetaan huomautus

Yhdyskuntasuunnittelu viittaa kuntatasoon, maankäytön suunnittelu on yleisempi termi. Kielitoimiston sanakirja: "yhdyskuntasuunnittelu: maa- ja vesialueiden käytön, palvelujen yms. suunnittelu kuntien ja niiden asukkaiden lähiympäristön tasolla"
ks. myös http://www.ym.fi/fi-fi/maankaytto_ja_rakentaminen/maankayton_suunnittelun_ohjaus

Yhteissuunnittelulla on YSOssa huomautus: "Tarkoittaa yhdyskuntasuunnittelua, johon viranomaisten lisäksi osallistuvat alueen asukkaat." YSAssa huomautusta ei ole ja esim. Melinda-käyttö on paljon laajempaa, esim. tuotesuunnittelua, opetustilojen suunnittelua.

**Comment by tpalonen** [comment]
Tein päätökset 1-9 sillä erolla, että laitoin tyyppitalot yläkäsitteeksi rakennukset rakennustyypin mukaan, koska se on tarkempi yläkäsite. 

Kohta 10 vielä ratkaisematta.

**Comment by YSO-kokous** [comment]
Päätös: yhteissuunnittelu LT suunnittelu tavan mukaan; poistetaan huomautus

Konsultoidaan vielä TSK:ta: onko maankäytön suunnittelu näin kattava? Esim. yhdyskuntasuunnittelu käsittänee muutakin kuin maankäytön suunnittelua (palvelut yms). Vrt TEPAn määritelmä maankäytön suunnittelusta.

**Comment by tpalonen** [comment]
Maankäytön suunnittelu ratkaistu toisessa issuessa (https://github.com/Finto-ehdotus/YSE/issues/5186) eli tässä issuessa olevat asiat loppuun käsitelty. Siteeraus tuosta toisesta issuesta:

_PÄÄTÖS

Koska nämä kaksi näkökulmaa eivät ole yhteensovitettavissa, toteutetaan maankäytön suunnittelun hierarkia neutraalisti, nojaamatta kumpaankaan näkökulmaan.

maankäytön suunnittelu LT suunnittelu + RT yhdyskuntasuunnittelu_
