### ISSUE TITLE
Sotatoimet-käsitteen alakäsitteet

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#736]
maihinnousu
miehitys
operaatio Barbarossa
operaatio Mincemeat
piiritys
pommitukset
sotaretket
Stella Polaris -operaatio
taistelut
valloitus

Osa alakäsitteistä on toiminta-tyyppisiä ja olisi hyvä siirtää sinne: maihinnousu, miehitys, valloitus.

**Comment by tpalonen** [comment]
**Ehdotus**

maihinnousu YK keskinäinen toiminta
miehitys YK keskinäinen toiminta
piiritys YK keskinäinen toiminta
valloitus YK keskinäinen toiminta

Vrt. hyökkäys, jonka ylkäsite on keskinäinen toiminta.
Ei muita muutoksia.

**Comment by YSO-kokous** [comment]
Nykyinen yläkäsite (ja tapahtumat-hierarkiaan kuuluminen) todettiin kaikkien ehdotettujen osalta hyväksi. Ei siis muutoksia.
