### ISSUE TITLE
vertaisarviointi

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#738]
MOTissa kaksi merkitystä: 
1. käytäntö jossa tieteelliseen julkaisuun tarjottu artikkeli, apurahahakemus tms. alistetaan saman alan asiantuntijoiden arvioitavaksi.
2. arviointimenetelmiä jotka perustuvat työsuoritusten, tuotteiden, palvelujen tms. vertailuun. Vertaisarviointi vertailukehittämisen osana. 

Ruotsinnos vastaa nyt kakkosmerkitystä. Pitäisikö määrtiellä, jakaa tms.? Ryhmät viittaisivat kakkosmerkitykseen, mutta Melindassa paljon käytetty nimenomaan koulutuksen ja akateemisen yhteydessä. Englanniksi nyt peer review.

**Comment by mirmaid** [comment]
YSO-kokous 21.10.2016:
Maria tekee muutosehdotuksen ehdotusjärjestelmään.

**Comment by mariaforsen** [comment]
Muutosehdotus tehty.

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/4921
