### ISSUE TITLE
jäähtyminen / kylmeneminen

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#739]
Mikä näiden ero tarkalleen on..? Ks. kommentit editorissa.

**Comment by mirmaid** [comment]
Melinda: 

jäähtyminen: 9 viitettä
- kaukolämmön paluuveden jäähtyminen
- metalliseoksen jäähtyminen
- hitsausliitoksen jäähtyminen
- elintarvikkeiden jäähtyminen (jäähdytettäessä)
- hypotermia
- ilmaston jäähtyminen x3 (tähän laittaisin itse kylmeneminen, yhdessä se on toisena vaihtoehtona)

kylmeneminen: 4 viitettä
- ilmaston kylmeneminen x3
- metalliseoksen jäähtyminen (kuvailussa myös termi jäähtyminen)

**Comment by mirmaid** [comment]
Google:

"ilmaston kylmeneminen" - n. 1000 viitettä
"ilmaston jäähtyminen" - n. 300 viitettä

**Comment by YSO-kokous** [comment]
Muotoillaan määritelmät.

**Comment by mirmaid** [comment]
kylmeneminen: jnk muuttuminen aikaisempaa kylmemmäksi, esim. ilman lämpötilasta
jäähtyminen: jnk (usein aluksi kuuman) muuttuminen viileämmäksi

**Comment by mariaforsen** [comment]
Nykyiset ruotsinnokset täsmäävät melko hyvin yllä olevien määritelmien kanssa.

**Comment by satuniininen** [comment]
Englanti myös ok.

**Comment by mirmaid** [comment]
Ylläolevat määritelmät lisätty YSAan. Vaatiiko muita toimenpiteitä?
