### ISSUE TITLE
mesipistiäiset, mehiläiset

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#740]
Onko lat. nimi todella Apoidea (nyt KT englanniksi) vai onko se Apidae? Muutetaan ruotsinnos kun merkitys on varmistunut. Mihin tarkalleen termi mehiläiset viittaa? Anthophila, Apis (honeybees..) vai yleisempänä terminä?

**Comment by tpalonen** [comment]
PÄÄTÖS 10.6.2016:
- mehiläiset englanniksi hobey bees (Apis). Eli poistetaan englanninkielinen termi "bees".
- mesipistiäiset latinaksi Anthophila. Satu selvittää englanninkielisen vastineen.

**Comment by satuniininen** [comment]
Englanti tehty.

**Comment by mariaforsen** [comment]
Eli Tieteen termipankissa yms. paikoissa on väärää tietoa? Siellä lat. on Apidae ja myös eri eng.

**Comment by tpalonen** [comment]
Laji.fi:n mukaan mesipistiäiset on Anthophila.
https://www.laji.fi/taxon/MX.289375

**Comment by mariaforsen** [comment]
Onkohan se sitten aivan oikein? Ks. https://en.wikipedia.org/wiki/Anthophila_(moth)

**Comment by mariaforsen** [comment]
Mehiläiset on jo ratkaistu.

Laji:fistä tuli seuraava vastaus: Mesipistiäisten tieteellinen nimi on vaihdellut paljon ajan saatossa.  
Nykyisen käsityksen mukaan mesipistiäiset ovat mesipistiäismäisten yläheimoon (Apoidea) kuuluva eliöryhmä, joka koostuu seitsemästä eri heimosta (Andrenidae, Apidae, Colletidae jne.). Samaan yläheimoon kuuluvat myös petopistiäiset mm. (Crabronidae), hietapistiäiset
(Sphecidae) ja kartiopistiäiset (Ampulicidae). Anthophila-nimen käyttö pohjautuu Michael Engelin suositukseen vuodelta 2005 (ks. liitteenä oleva artikkeli). Toinen laajalti käytössä ollut nimi, jota mm. Dyntaxassa käytetään, on Apiformes. Jotkut tutkijat ovat käyttäneet myös nimeä Apidae sensu lato (Apidae s.l.). Tieteen termipankissa ja wikipediassa on käytetty virheellisesti nimiä Apidae ja Apoidea mesipistiäisistä.
