### ISSUE TITLE
leirit

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#743]
Nyt LT ihmisen määrittämä paikka. Alakäsitteet eivät (ainakaan kaikki) ole paikkoja. Keskitysleirit vs. rippikoululeirit.

**Comment by mirmaid** [comment]
Voisi olla yhteiskunnalliset tapahtumat. Tämäntyyppisissä rajaus objekteihin/tapahtumiin on kyllä aika sopimuksenvaraista...

**Comment by YSO-kokous** [comment]
leirit YK yhteiskunnalliset objektit
