### ISSUE TITLE
merkkikielet, viittomakieli

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#744]
Onko molemmat tarpeen? Ks. käyttöä esim. Melindassa. 

Viittaako tämä mahdollisesti nimenomaan "symbolikieleen" (symbolspråk) ? Siinä tapauksessa on käännös mahdollinen, mutta nyt käytetty myös muissa merkityksissä, joten olisiko siinä tapauksessa määritelmä tarpeen? 

Meshissä merkkikieli vain korvattuna viittomakielelle.  Esim. IATE ei tunne merkkikieliä ollenkaan. Motissa ei minkäänlaista määrittelyä, vain esimerkki vangeista..

Salakielet erikseen sanastossa.

Wikipedia:
"Kuulevien viittomakielet

Viittomakieliä tai viitottuja kommunikaatiomenetelmiä syntyy myös kuulevien yhteisöissä. Usein kyse ei ole kuitenkaan varsinaisesti kielestä, vaan merkkijärjestelmästä. Amerikan intiaanit käyttivät heimojen välisessä viestinnässä viitottua pidgin-kieltä kun heimojen puhutut kielet olivat erilaisia. Salaseurat ja rikolliset ovat käyttäneet käsien liikkeisiin perustuvia merkkikieliä. Viittomia tai käsimerkkejä käytetään myös silloin, kun puhe on mahdotonta tai pitää pysyä hiljaa, kuten sotilasoperaatioissa ja sukeltaessa.

Kuulevat käyttävät puheen tukena eleitä, jotka ovat kulttuuriin sidonnaisia. Etenkin Italiassa eleet ovat niin voimakkaasti puhutun italian osa, että jotkut italialaiset pystyvät ilmaisemaan monimutkaisiakin käsitteitä pelkillä eleillä."

Ruotsiksi ollut sama termi: teckenspråk. Hätäratkaisuna on keksitty "dövas teckenspråk", mutta se ei vaikuta olevan suosittu. Englanniksi samankaltainen tilanne?

**Comment by mirmaid** [comment]
Teckenspråk on käsittääkseni laajempi kuin pelkkä viittomakieli, joka tarkoittaa vain kuurojen käyttämättä kieltä. Esim. babyteckenspråk on suomeksi tukiviittomat, ja wikipediassa käsketään olla sekoittamatta sitä viittomakieleen. 

Merkkikielellä viitataan usein kuvasymboleihin, kyse voi olla puhetta tukevasta/korvaavasta kommunikaatiosta tai sitten kuvasymbolien käytöstä jossakin kontekstissa. Varmaan usein olisi ilmankin tätä selvitty, mutta voiko poistaakaan: 77 viitettä Melindassa enkä tiedä mihin tämän voisi yhdistää.

**Comment by YSO-kokous** [comment]
PÄÄTÖS:
- Tehdään YSE-ehdotus "merkkikielet"-käsitteen korvaamisesta "merkkijärjestelmät"-käsitteellä. Vaihdetaan viittomakielen ruotsin vastineeksi teckenspråk. HUOM! Osa kuvailusta mahdollisesti ohjattava muihin käsitteisiin.
