### ISSUE TITLE
Plasma, pesänselvitys

### ISSUE THREAD

**Issue by MikkoAleksanteri** [NatLibFi/Finto-data#745]
YSA-YSO-päivitys:

plasma, kumpi sulkutarkenne: (nesteet) (yso), vai (neste) (ysa). LT nesteet

pesänselvitys new broader selvitys. YSOn vanha broader järjestävä muuttaminen. Jätetäänkö vanha LT?

**Comment by tpalonen** [comment]
PÄÄTÖS:
- säilytetään toistaiseksi muoto "plasma (nesteet)", syyskuun 2016 KOKO-työpajassa tehdään tarkempi linjauspäätös sulkutarkenteista
- pesänselvitys LT selvitys (poistetaan LT järjestävä muuttaminen)

**Comment by MikkoAleksanteri** [comment]
Tehty.
