### ISSUE TITLE
Ketjumuotoiset tarkenteet

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#747]
Lista on tehty 2014 joten termeissä on voinut tapahtua muutoksia.

Artemis -- atk
abduktio -- filosofia
induktio -- filosofia
induktio -- fysiikka
ajurit -- tietotekniikka
assimilaatio -- kielitiede
assimilaatio -- sosiologia
ekstaasi -- huumeet
emissio -- fysiikka
energiankulutus -- aineenvaihdunta
energiantuotto -- fysiologia
friisit -- kansat
friisit -- kuvataide
haasteet -- oikeustiede
haraus -- maanmuokkaus
haraus -- merenmittaus
interferenssi -- fysiikka
interferenssi -- kielitiede
itsenäistyminen -- psykologia
karuna -- hoitomenetelmät
Kiinan-Japanin sota -- 1894-1895
Kiinan-Japanin sota -- 1937-1945
kiinnitys -- oikeustiede
kirjanpainaja -- kovakuoriaiset
kieli -- ruumiinosat
kurkku -- ruumiinosat
kurkku -- vihannekset
kutojat -- linnut
kutsut -- viestit
kuuleminen -- fysiologia
kuuleminen -- oikeustiede
kuvantaminen -- atk
leimautuminen -- biologia
leimautuminen -- sosiologia
liiketerapia -- psykoterapia
linssit -- hernekasvit
lunastus -- uskonto
markkinat -- tapahtumat
massa -- fysiikka
messut -- musiikki
mittarit -- perhoset
muoto-oppi -- kielitiede
muoto-oppi -- musiikki
paino -- kielitiede
palomuurit -- tietoturva 
portaalit -- atk
sinkki -- soittimet
sovitus -- uskonto
subjekti -- kirjallisuudentutkimus
subjekti -- filosofia
taivutus -- kielitiede
taivutus -- mekaaninen teknologia
tankkaus -- polttoaineet
tankkaus -- ravinto
väylät -- atk
vesimittarit – hyönteiset
vesimittarit -- mittauslaitteet
voimantuotto -- fysiologia

**Comment by mariaforsen** [comment]
YSA/YSO-tarkistuksen jälkeen ehdotan seuraavat muutokset:

induktio (filosofia), induktio (fysiikka)
ajurit (tietotekniikka)
assimilaatio (kielitiede), assimilaatio (sosiologia)
ekstaasi (huumeet)
energiankulutus (aineenvaihdunta) - sekä sulkutarkenteen lisääminen käsitteelle "energiankulutus"
energiantuotto (fysiologia)
friisit (kansat), friisit (kuvataide)
haasteet (oikeustiede) -sekä sulkutarkenteen lisääminen käsitteelle "haasteet"
haraus (maanmuokkaus), haraus (merenmittaus)
interferenssi (fysiikka), interferenssi (kielitiede)
itsenäistyminen (psykologia) -sekä sulkutarkenteen lisääminen käsitteelle "itsenäistyminen"
karuna? -> YSO:ssa ei ole paikannimiä, joten tarkenne ontologian puolella ei periaatteessa ole tarpeen? Emme ole lisänneet tarkenteita ellei sana esiinny tuplasti sanastossa..?
kirjanpainaja (kovakuoriaiset) -myös termi "kirjanpainajat", mutta onko tarkenne tarpeen..?
kutsut (viestit) -sekä sulkutarkenteen lisääminen käsitteelle "kutsut"
kieli (rumiinosat) -sekä sulkutarkenteen lisääminen käsitteelle "kieli" 
kurkku (ruumiinosat), kurkku (vihannekset)
kutojat (linnut)
kuuleminen (fysiologia) -sekä sulkutarkenteen lisääminen käsitteelle "kuuleminen" ja luokka 69, vai mihin tämä oikeastaan viittaa? MOT:issa nimenomaan nämä kaksi merkitystä.. Vaatii ehkä jotain muitakin toimenpiteitä.

**Comment by mariaforsen** [comment]
Myös "laitoskirjastot -- hoitolaitokset", ruotsiksi "sjukhusbiblioteket" ja "laitoskirjastot -- yliopistot", ruotsiksi "institutionsbibliotek (universitet)" pitäisi ehkä muuttaa sulkutarkenteellisiksi?

**Comment by mirmaid** [comment]
kieli (rumiinosat) -sekä sulkutarkenteen lisäys käsitteelle "kieli" > kulttuuriset järjestelmät voisi olla ihan hyvä, mutta meillä on lisäksi myös kielet...

kutsut (viestit) -sekä sulkutarkenteen lisäys käsitteelle "kutsut" > varmaan kutsut (juhlat), tosin Kielitoimiston sanakirjan mukaan "(kodissa) järjestetty (juhlia vaatimattomampi) tilaisuus, johon on kutsuttu vieraita ja jossa on tarjoilua, kestit, kekkerit, pidot."

kuuleminen (fysiologia) -sekä sulkutarkenteen lisäys käsitteelle "kuuleminen" ja luokka 69, vai mihin tämä oikeastaan viittaa? MOT:issa nimenomaan nämä kaksi merkitystä.. Vaatii ehkä jotain muitakin toimenpiteitä. > tarkenne (oikeustiede) on ainakin liikaa jos puhutaan lapsen kuulemisesta koulussa tms. Vaatii kyllä jonkun tarkenteen YSAankin, nyt käytetty väärin. 

kuvantaminen (lääketiede) -sekä sulkutarkenteen lisäys käsitteelle "kuvantaminen" > kuvantaminen -- lääketiede päätettiin poistaa YSAsta

linssit (hernekasvit) -sekä sulkutarkenteen lisäys käsitteelle "linssit" > wikipedian "optiikka" voisi olla hyvä?

markkinat (tapahtumat) -sekä sulkutarkenteen lisäys käsitteelle "markkinat" > talous?

messut (musiikki) -sekä sulkutarkenteen lisäys käsitteille "messut" ja "messu" > messu (jumalanpalvelus)?

mittarit (perhoset) -sekä sulkutarkenteen lisäys käsitteelle "mittarit" > "mittaus"?

paino (kielitiede) -sekä sulkutarkenteen lisäys käsitteelle "paino" > ohjausterminä on paino -- fysiikka

palomuurit (tietoturva) ? (Mirja: tai tietotekniikka)

portaalit & väylät (atk) -> ? > "tietotekniikka"?

sinkki (soittimet) -sekä sulkutarkenteen lisäys käsitteelle "sinkki" > metallit

**Comment by mirmaid** [comment]
YSO-kokous 15.6.2016

- laitoskirjastot (yliopistot) ja sairaalakirjastot. Muut laitoskirjastot (esim. vanhainkodit) = vain kirjastot
- energiankulutus (aineenvaihdunta) - sekä sulkutarkenteen lisäys käsitteelle "energiankulutus"?
- haasteet (oikeustiede) -sekä sulkutarkenteen lisäys käsitteelle "haasteet" (ST julkiset haasteet nyt väärässä paikassa) (eng. oik. challenges) - "haastavat tilanteet" (?)
- itsenäistyminen (psykologia) -sekä sulkutarkenteen lisäys käsitteelle "itsenäistyminen" > valtiot ja yhteisöt (?)
- kieli (ruumiinosat) -sekä sulkutarkenteen lisäys käsitteelle "kieli" > ratkaistaan sulkutarkenne jälkimmäiselle yksikkö-monikko-ratkaisun yhteydessä
- kutsut (viestit) -sekä sulkutarkenteen lisäys käsitteelle "kutsut" > kutsut (juhlat)
- kuuleminen (fysiologia) ja kuuleminen (keskinäinen toiminta) / kuuleminen (mielipiteet) / kuuleminen (päätöksenteko) / kuuleminen (vaikuttaminen) (?)  
- kuvantaminen (lääketiede) -sekä sulkutarkenteen lisäys käsitteelle "kuvantaminen" > kuvantaminen -- lääketiede päätettiin poistaa YSAsta
- linssit (hernekasvit) -sekä sulkutarkenteen lisäys käsitteelle "linssit" > "optiikka"
- markkinat (tapahtumat) -sekä sulkutarkenteen lisäys käsitteelle "markkinat" > taloustiede (?)
- messut (musiikki) -sekä sulkutarkenteen lisäys käsitteille "messut" ja "messu" > messu (jumalanpalvelus) ja messut (tapahtumat)
- mittarit (perhoset) -sekä sulkutarkenteen lisäys käsitteelle "mittarit" > "mittaus"
- paino (kielitiede) -sekä sulkutarkenteen lisäys käsitteelle "paino" > ohjausterminä on paino -- fysiikka > (fysiikka)
- palomuurit (tietoturva)
- portaalit & väylät (atk) -> "tietotekniikka"
- sinkki (soittimet) -sekä sulkutarkenteen lisäys käsitteelle "sinkki" > raskasmetallit

**Comment by MikkoAleksanteri** [comment]
Kertauksena vielä aiheeseen liittyen tesaurusstandardin näkemys sulkutarkenteiden valinnasta:

ISO 25964-1:2011

" -- qualifier should be as brief as possible, ideally consisting of one word. Often a broader term, the qualifier should indicate the context or subject area to which the concept belongs.”

**Comment by mirmaid** [comment]
Päivitetty lista:

induktio -- filosofia
induktio -- fysiikka
ajurit -- tietotekniikka
assimilaatio -- kielitiede
assimilaatio -- sosiologia
ekstaasi -- huumeet
energiantuotto -- fysiologia
friisit -- kansat
friisit -- kuvataide
haraus -- maanmuokkaus
haraus -- merenmittaus
interferenssi -- fysiikka
interferenssi -- kielitiede
karuna -- hoitomenetelmät
kirjanpainaja -- kovakuoriaiset
kurkku -- ruumiinosat
kurkku -- vihannekset
kutojat -- linnut
leimautuminen -- biologia
leimautuminen -- sosiologia
liiketerapia -- psykoterapia
lunastus -- uskonto
muoto-oppi -- kielitiede
muoto-oppi -- musiikki
sovitus -- uskonto
subjekti -- kirjallisuudentutkimus
subjekti -- filosofia
taivutus -- kielitiede
taivutus -- mekaaninen teknologia
tankkaus -- polttoaineet
tankkaus -- ravinto
vesimittarit – hyönteiset
vesimittarit -- mittauslaitteet
voimantuotto -- fysiologia

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 17.10.16:

ketjuja ei tarvita ohjaustermeiksi, ellei toisin käsitteen kohdalla mainittu

**Comment by tpalonen** [comment]
15.6.2016 pidetyn YSO-kokouksen jälkeen ratkaisematta vielä seuraavat:

energiankulutus (aineenvaihdunta) - sekä sulkutarkenteen lisäys käsitteelle "energiankulutus"?
haasteet (oikeustiede) -sekä sulkutarkenteen lisäys käsitteelle "haasteet" (ST julkiset haasteet nyt väärässä paikassa) (eng. oik. challenges) - "haastavat tilanteet" (?)
itsenäistyminen (psykologia) -sekä sulkutarkenteen lisäys käsitteelle "itsenäistyminen" > valtiot ja yhteisöt (?)
kieli (ruumiinosat) -sekä sulkutarkenteen lisäys käsitteelle "kieli" > ratkaistaan sulkutarkenne jälkimmäiselle yksikkö-monikko-ratkaisun yhteydessä
kuuleminen (fysiologia) ja kuuleminen (keskinäinen toiminta) / kuuleminen (mielipiteet) / kuuleminen (päätöksenteko) / kuuleminen (vaikuttaminen) (?)
kuvantaminen (lääketiede) -sekä sulkutarkenteen lisäys käsitteelle "kuvantaminen" > kuvantaminen -- lääketiede päätettiin poistaa YSAsta
linssit (hernekasvit) -sekä sulkutarkenteen lisäys käsitteelle "linssit" > "optiikka"
markkinat (tapahtumat) -sekä sulkutarkenteen lisäys käsitteelle "markkinat" > taloustiede (?)
mittarit (perhoset) -sekä sulkutarkenteen lisäys käsitteelle "mittarit" > "mittaus"
paino (kielitiede) -sekä sulkutarkenteen lisäys käsitteelle "paino" > ohjausterminä on paino -- fysiikka > (fysiikka)
palomuurit (tietoturva)
portaalit & väylät (atk) -> "tietotekniikka"
sinkki (soittimet) -sekä sulkutarkenteen lisäys käsitteelle "sinkki" > raskasmetallit

**Comment by mirmaid** [comment]
Huomasin tässä yhteydessä, että toisen kutojat-käsitteen tarkenne ammatti on yksikössä, muilla vastaavilla käsitteillä tarkenne on monikossa.

**Comment by mirmaid** [comment]
Kuuleminen päätetty ysa-ongelmakokouksessa, ks. https://github.com/Finto-ehdotus/YSE/issues/4653

**Comment by mariaforsen** [comment]
Eikö tämä ole nyt loppuunkäsitelty? Ainoastaan energiankulutus on vielä ratkaisematta ja siitä on erillinen YSE-issue.

**Comment by tpalonen** [comment]
Kieli-käsitteen osalta keskustelu löytyy täältä. Päätettiin, että termimuoto on "kieli ja kielet". Lisäksi sanastossa "kieli (ruumiinosat)". https://github.com/Finto-ehdotus/YSE/issues/5842

Energiankulutuksen osalta keskustelu käydään täällä: https://github.com/Finto-ehdotus/YSE/issues/5471
