### ISSUE TITLE
vankeinhoito LT käyttöönottava muuttaminen

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#748]
Olisiko parempi LT esim. sosiaalipalvelut, jonka alla "kriminaalihuolto" on, hoito tms.?

**Comment by mirmaid** [comment]
Kyllä melkein uskaltaa sanoa että _mikä tahansa_ on parempi...

**Comment by tpalonen** [comment]
PÄÄTÖS 10.6.2016:
- vankeinhoito LT sosiaalipalvelut
