### ISSUE TITLE
Kirjola

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#749]
Huomautus: Kartano ja kylä Halikossa 
Ruotsiksi (ja englanniksi) nimenomaan kartano, eikä kyliä pitäisi YSOssa olla (eikä monimerkityksisiä), voitaisiinko rajata jotenkin?

**Comment by tpalonen** [comment]
PÄÄTÖS 10.06.2016:
- muutetaan huomautus muotoon "Kartano Halikossa."
