### ISSUE TITLE
kliininen tutkimus

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#750]
Kaksi merkitystä, ruotsiksi kaksi eri termiä. Ks. https://fi.wikipedia.org/wiki/Kliininen_tutkimus ja käyttö Melindassa. Onko syytä jakaa tms.?

**Comment by tpalonen** [comment]
Mirja tutkii.

**Comment by mirmaid** [comment]
MeSHissä _kliniska prövningar_ on suomeksi _kliiniset kokeet_. Jos sen ottaisi omana terminään, onko enää vaarana sekoittuminen potilaan tutkimiseen? KT kliininen lääketutkimus, kliininen tutkimustoiminta (lääketieteellinen tutkimus) tms.

Toinen olisi esim. kliininen tutkimus (potilaat) TAI kliininen tutkimus (lääketieteelliset toimenpiteet) TAI kliininen tutkimus (terveydenhuolto).

**Comment by YSO-kokous** [comment]
**Hyväksytään ehdotus, eli

kliininen tutkimus (lääketieteelliset toimenpiteet)
kliiniset kokeet KORVATUT TERMIT kliininen tutkimus (lääkkeet ja hoitomenetelmät), kliininen lääketutkimus, kliininen tutkimustoiminta, ASSO kliininen farmakologia**

Mirja tekee määritelmät/huomautukset ja lukitsee sulkutarkenteet.

**Comment by mirmaid** [comment]
Käsittelyssä YSEssä https://github.com/Finto-ehdotus/YSE/issues/5226
