### ISSUE TITLE
paikannus

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#751]
Huomautus nyt: 
"kohteen sijainnin määrittäminen vertausjärjestelmässä
Kohteen sijainti voidaan määritellä muun muassa koordinaatti- tai osoitejärjestelmässä, aluejaossa, matkaviestinverkon solukkojärjestelmässä tai valitun reitin tai tunnettujen kohteiden suhteen.Englannin termiä "pinpointing" käytetään usein silloin, kun kohteen sijainti näytetään kartalta. {@fi}"
Eli jotain vikaa. YSA:ssa ei huomautusta ollenkaan.

**Comment by tpalonen** [comment]
PÄÄTÖS 10.06.2016:

- poistetaan huomautus kokonaisuudessaan
