### ISSUE TITLE
piirustukset

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#752]
Jotain mennyt vikaan sen jälkeen kun jaettiin YSO:ssa koska nyt on Kuvataide-ryhmä "piirustukset (tekniset)"-termillä, mutta "piirustukset (taide)"-termillä ei ollenkaan ryhmää. Tarkista myös RT ja LT!

**Comment by tpalonen** [comment]
PÄÄTÖS 10.06.2016

piirrokset (kuvataide)
- lisätään ryhmä 92
- lisätään altlabel "piirrokset"
- siirretään kalliopiirrokset LT elottomat objektit

piirrokset (tekniset)
- poistetaan ryhmä 92
- lisätään ryhmät 00, 37, 91
- poistetaan RT piirustustaide
