### ISSUE TITLE
löydöt / löydökset

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#753]
Onko kaikille ero selvä ja mikä se ero tarkalleen on? Ks. MOT ja käyttö Melindassa. Epäselvää mikä olisi oikea termi ruotsiksi (fynd vs. upptäckter). Olisi hyvä määritellä niin että käytettäisiin johdonmukaisesti...

**Comment by mirmaid** [comment]
Löydöt: sadasta ensimmäisestä viitteestä tietoaineistossa lähes kaikki käsittelevät arkeologisia löytöjä (muutama viite esim. malmilöydöt, rengastetut linnut). YSAssa on nyt arkeologiset löydöt KÄ muinaisjäännökset, mikä selkeästi ei ole toiminut ja on varmaan syytä poistaa. Arkeologiset löydöt olisi ihan ok erillisenä sananakin, mutta ero muinaisjäännökset-termiin on tietysti epämääräinen. Tämä on ruotsiksi kai _fynd_. Upptäckter on mielestäni ennemmin "keksinnöt", "havainnot"?

**Comment by mirmaid** [comment]
Löydökset on omaan korvaani yksinomaan lääketieteellinen termi, mutta YSAssa se on ryhmässä 00 ja Melindassa sitä on käytetty muissakin merkityksissä, samoin yllättäen Googlella löytyy paljon esim. arkeologista ja niin myös Kielitoimiston sanakirjan mukaan. Ruotsiksi tämäkin on _fynd_. MeSHissä tosin _oireet ja löydökset_ = _tecken och symtom_.

**Comment by mirmaid** [comment]
Kaunokirjallisuudessa löydöt on varmaan paljon laajemmassa käytössä. Tietoaineistossa suurin osa ratkeaisi tarkentamalla:

löydökset (lääketiede)
arkeologiset löydöt

**Comment by YSO-kokous** [comment]
Jätetään löydöt = fynd. Korjataan Melindassa kaikki muut kuin lääketieteelliset viitteet vastaamaan tätä. Selvitetään tämän jälkeen tarvitaanko löydökset-termiä, ja mikä olisi siinä tapauksessa ruotsinkielinen vastine.

**Comment by mariaforsen** [comment]
TEPAssa löydös käännetään mm. "sjukdomstecken".

**Comment by mirmaid** [comment]
Lääketiede 2.0: löydös, finding [fi'nding],{e}, fynd -et,{r} kliinisesti merkittävä havainto, esim. potilaan tutkimisessa, laboratoriotutkimuksissa tai kuvantamisessa havaittu poikkeavuus

sjukdomstecken olisi hyvä, mutta oikeuslääketieteessä kyse voi olla myös vammasta tms. jäljestä joka ei liity sairauteen, ja löydös voi (ehkä?) olla myös se, että ei ole mitään poikkeavaa (negatiivinen löydös)

**Comment by mariaforsen** [comment]
Näin on, sjukdomstecken ei ole aivan sama asia.

**Comment by mirmaid** [comment]
Melindaan jää kourallinen lääketieteellisiä julkaisuja joissa on käytetty termiä _löydökset_ ysa-asiasanana. Niissä joissa on myös ruotsinkielinen kuvailu, on käytetty Allärs-termiä _fynd_. Suomeksi tämä ratkeaisi tarkenteellisella muodolla _löydökset (lääketiede)_ - voisi ehkä kääntää _fynd (medicin)_. Silloin kuitenkin tarvittaisiin sulkutarkenne _löydöt_-käsitteen ruotsinkieliselle vastineelle. 

Yhdessä aineistossa käytetty eri merkityksessä: _Findings : hidden stories in first-hand accounts of scientific discovery._ Tästä voisi ehkä vain poistaa?

**Comment by YSO-kokous** [comment]
Muutosehdotus YSEen: lisätään sulkutarkenne löydökset (lääketiede) = medicinska fynd.
