### ISSUE TITLE
Toiminta-hierarkian uusi ehdotus

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#754]
EHDOTUS UUDESTA HIERARKIAMALLISTA

Olemme todenneet YSOn vanhan toimintahierarkian epäkäytännölliseksi ja kehittäneet uudenlaista hierarkiamallia. Erinäisten kokeilujen ja harhapolkujen jälkeen päädyimme pohtimaan samanlaista jakoa, joka on Finto-projektissa toteutettu jo YSOn ominaisuuksien ja tapahtumien puolella. Tähän tuntuu liittyvän vähemmän ongelmia kuin muihin testaamiimme ratkaisumalleihin, ja se vaikuttaa myös selkeämmältä ja käytännöllisemmältä kuin vanha toimintahierarkian jako. Tässä uusi hierarkiamalli ja esimerkkejä alakäsitteistä:
- yhteiskunnallinen toiminta (aatelointi, akkreditointi, eheyttäminen) 
- mentaalinen toiminta (ihailu, ikävystyminen, rakastuminen)
- taloudellinen toiminta (devalvaatio, hinnankorotus, listautuminen)
- tekninen toiminta (alkalointi, editointi, fermentointi)
- keskinäinen toiminta (anteeksipyyntö, eroaminen)
- kulttuurinen toiminta (?) (konservointi, kultaus, värjäys)
- uskonnollinen toiminta (?) (piispanvihkimys, pyhitys)
- biologinen toiminta (?) ( synnytys)

Aiemmasta mallista poiketen myös suoraan toiminta-käsitteen alle voidaan ripustaa käsitteitä. Tämä koskee käsitteitä, jotka ovat niin yleisiä tai moneen toimialaan liittyviä, että niille olisi vaikeaa löytää tarkempaa yläkäsitettä, esim. alennus, aloitus, ehkäisy, hajotus. 
Uusi hierarkia edellyttää vanhan toimintahierarkian läpikäyntiä kokonaisuudessaan ja käsitteiden uudelleensijoittamista uusiin pääluokkiin. Muutos on merkittävä: YSOn toimintahierarkiassa on yli 4500 käsitettä, jotka nyt sijoittuvat uudella tavalla hierarkiaan. Muutos vaikuttaa myös erikoisontologioihin, joiden käsitteillä on suhteita YSOn käsitteisiin. Pyydämme kuitenkin huomioimaan, että YSOn toimintahierarkian käsitteiden merkitys ei tule muuttumaan. Muutokset koskevat tapaa hahmottaa toimintaa pääkategorioiden tasolla.

Aiempiin Finto-projektin hierarkiaratkaisuihin (ominaisuudet, tapahtumat) nähden toimintahierarkiamallissa on yksi lisäkategoria: tekninen toiminta. Se tuntui sopivalta yläotsikolta käsitteille, joissa olennaista on työkalujen tai teknologian käyttö. Tällaista käsitteistöä on ontologiassa melko paljon ja katsoimme, että se olisi hyödyllistä erottaa muusta käsitemassasta. Toisaalta jaosta puuttuu pari ominaisuus- ja tapahtumahierarkioissa esiintyvää kategoriaa: fysikaalinen ja kemiallinen. Syynä tähän on se, että toiminta on hahmotettu luonteeltaan ihmisen tekemäksi (joissain tapauksissa myös eläinten) ja tahdonalaiseksi. Fysikaalisen ja kemiallisen kategorioihin taas on YSOssa rajattu sellaisiin ilmiöihin ja tapahtumiseen, joiden voidaan käsittää ilmenevän ihmisen toiminnasta riippumatta, esim. auringonpurkaukset, kiehuminen.

Arvioimme myös uudella tavalla sitä, mikä kuuluu toimintaan ja mikä tapahtumiin. Edellä mainitun tahdonalaisuuden kriteerin pohjalta päädymme siirtämään muutos-käsitteen alakäsitteineen tapahtumien puolelle, tarkistaen vielä kokonaisuuden käsitekohtaisesti.

Tähänkin ratkaisumalliin liittyy omia haasteitaan. Termitasolla ”yhteiskunnallinen toiminta” arveluttaa: se ei ole yleiskäsitemäinen, merkitykseltään lavea, vaan herättää mielleyhtymiä poliittiseen toimintaan. Myös keskinäisen toiminnan uudelleen nimeämisestä on keskusteltu; toisaalta on pohdittu, tarvitaanko hierarkiassa enää keskinäistä toimintaa, kun on olemassa merkitykseltään likeinen yhteiskunnallinen toiminta. Kysymysmerkkinä ovat edelleen myös biologinen, kulttuurinen ja uskonnollinen toiminta: onko riittävästi näihin aloihin liittyviä käsitteitä, jotka kuvaavat tahdonalaista toimintaa, jotta tällaiset yläluokat olisivat tarpeen? 

PERUSTEET MUUTOSTARPEELLE

Nykyinen FinnONTOssa kehitetty toimintahierarkian jako on koettu ongelmalliseksi. Se perustuu löyhästi Wordnetissä esitettyihin toimintakategorioihin, mutta sekä YSOn että Wordnetin toimintajaon periaatteista löytyy hyvin vähän dokumentaatiota. Toimintahierarkian kategoriat eivät ole selkeärajaisia: vakoilu on havainnointia, mutta salakuuntelu keskinäistä toimintaa. Jälkikäyttö on käyttöä, mutta käyttöönotto on muuttamista. Yksittäisten käsitteiden sijoittaminen hierarkiaan on välillä haastavaa. Lisäksi eräät hierarkisoivat käsitteet on käyttäjäpalautteenkin kautta havaittu jo termitasolla vaikeasti ymmärrettäviksi, esim. koneellinen luonti, ylläpitävä muuttaminen.

YSOn hierarkian päähaarojen jakoperiaatteet eivät ole vanhassa YSOssa olleet yhdenmukaiset, vaan kussakin haarassa on tehty yksilöllisiä ratkaisuja. Esimerkki tästä on juuri toimintahierarkia, jonka Wordnet-johdannainen malli ei muistuta lähestymistavaltaan muita YSOn pääkategorioita. Olemme nyt pyrkineet rakentamaan pääkategorioiden kesken hierarkioita yhdenmukaisella logiikalla ja temaattisilla periaatteilla. Arvelemme sen lisäävän hierarkian käyttäjäystävällisyyttä.

MUITA HARKINNAN ALLA OLLEITA VAIHTOEHTOJA

Uutta ratkaisutapaa pohtiessamme tutustuimme filosofis-ontologiseen kirjallisuuteen, kielitieteeseen sekä eri kansainvälisten ontologioiden ylähierarkioihin. Tätä kautta ei kuitenkaan tuntunut löytyvän käyttökelpoista tapaa hahmottaa ja jakaa toimintaa. Filosofiassa toiminta tai tapahtumat jaetaan usein tahdonalaiseen ja tahdosta riippumattomaan, mikä on YSOn toimintahierarkian kannalta olennaista vain pohdittaessa sitä, mikä rajataan toiminnan ulkopuolelle, mutta ei niinkään toiminnan sisäiseen jaon osalta. 

Kielitieteen, kielifilosofian ja tunnettujen kansainvälisten ontologioiden (mm. Dolce, CYC) malleja tutkittiin myös. Esimerkiksi kielitieteen syntaksissa perinteinen tapa hahmottaa toimintaa on jakaa se a) toimintaan, jolla on objekti ja b) toimintaan, jolla ei ole objektia. Kielifilosofi Emmon Bach taas jakaa toiminnan pitkittyneeseen ja hetkelliseen toimintaan, ja jälkimmäisen edelleen tapahtumiksi (happenings) ja huipentumiksi (culminations). Näitä hahmotustapoja yhdistää se, että kategoriat kuvaavat toimintaa varsin abstraktilla ja teoreettisella tasolla, mikä ei palvele käyttäjää. Myös yksittäisten käsitteiden sijoittaminen tällaiseen jaotteluun on usein ongelmallista.
Todettuamme teoreettisten lähestymistapojen heikkoudet mietimme, olisiko parempi ratkaisu tiivistää nykyistä jakoa yhdistämällä olemassa olevia toimintakategoria ja kaventamalla yläluokkien määrää aiemmasta.  Esimerkkinä yhdistämisestä olisi esim. henkilön aseman muuttaminen- ja keskinäinen toiminta käsitteiden yhdistäminen. Käytyämme läpi otoksen toimintahierarkiaan kuuluvia käsitteitä kehitimme uuden aiempaa pelkistetymmän hierarkiamallin, joka rakentui neljästä kategoriasta. Nämä olivat:
- mentaalinen toiminta (tms)
- keskinäinen toiminta (tms)
- liikkuminen (tms)
- käsittely (tms, "käyttö ja muuttaminen")

Näistä kolme ensimmäistä löytyy myös vanhasta toimintahierarkiasta. Käsittely-käsitteen alle tulisi suuri osa niistä käsitteistä, jotka vanhassa mallissa ovat muuttamisen ja luonnin alla. Nelijaossa törmättiin kuitenkin siihen ongelmaan, että se ei ole yhteismitallinen: muut kategoriat määrittyvät toiminnan luonteen mukaan, mutta keskinäinen toiminta määrittyy toiminnan kohteen mukaan. Jos kohde on ihminen (tai eläin), toiminta on keskinäistä, jos ei, se on käsittelyä. Keskinäistä toimintaa parempi nimitys voisikin olla ”sosiaalinen toiminta”, joka kuvaisi enemmän toiminnan luonnetta. Lisäksi tunnistimme ristiriidan keskinäisen toiminnan piiriin kuuluvassa käsitteistössä: niiden voidaan katsoa jakautuvan a) sellaisiin, joissa toiminnan toinen osapuoli on passiivinen vastaanottaja (eläinrääkkäys, nimenanto) ja b) sellaisiin, joissa molemmat osapuolet ovat aktiivisia (keskustelu, kättely). Ensiksi mainitut tuntuvat kuitenkin olevan lähempänä ”käsittely”-kategorian käsitteitä kuin muita keskinäisen toiminnan käsitteitä. Ongelmaksi yksittäisten käsitteiden osalta tulisi, painotetaanko sitä, että toiminta on luonteeltaan käsittelymäistä vai sitä, että toiminnalla on kaksi ihmisosapuolta (tai mahdollisesti ihminen ja eläin).

**Comment by MikkoAleksanteri** [comment]
Uutta mallia mietittäessä tulee ottaa huomioon myös ontologian temaattiset ryhmät: http://finto.fi/yso/fi/groups 

Kun käsitteet kuuluvat jo nyt omiin temaattisiin ryhmiinsä, onko tällöin järkevää tehdä myös hierarkkisesta jaottelusta temaattista?

Ehdotetussa mallissa pitää myös miettiä erityisesti "keskinäinen toiminta"-käsitettä suhteessa muihin: eikö tämä ole erilainen (ei-temaattinen) näkökulma alakäsitteisiin kun muut aihepiiri-pohjaiset käsitteet?

**Comment by tpalonen** [comment]
Tässä vielä eräiden ontologioiden ja kielifilosofien tapoja jakaa toimintaa.

WORDNET

Wordnet - an Electronic Lexical Database (1998: 70): 

“A first cut was made between verbs headed by verbs denoting actions and events on the one hand, and states on the other hand. Most verbs are of the former kind, and these were subdivided into 14 more specific semantic domains --- : verbs of motion, perception, contact, communication, competition, change, cognition, consumption, creation, emotion, perception, possession, and bodily care and functions, and verbs referring to social behavior and interactions.”
[Huom: tekstissä perception kahteen kertaan]

Wordnetin vastineet FinnONTO-YSOssa

Wordnet:                                            YSOn vastine

”states”	                                          ”oleminen”
”motion”	                                          ”liikkuminen ja liikuttaminen”
”perception”                                     "havainnointi ja aistiminen”
”contact”	                                           -
”communication”	                          ”viestintä” (”keskinäinen toiminta” alakäsite)
“competition”	                                   -
“change”	                                          “muutos” sekä “muuttaminen”
“cognition”	                                  “kognitio” (“mentaalinen toiminta” alakäsite)
“consumption”                                 “kulutus ja käyttö”
“creation”	                                  “luonti”
“emotion”	                                  “tunteminen” (“mentaalinen toiminta” alakäsite)
“possession”	                                  “omana tai hallussa pitäminen”
“bodily care and functions”              -
“social behavior and interactions”	  ”keskinäinen toiminta”
-	                                                  ”mentaalinen toiminta”

_____________________________________________________

DOLCE
- Dolce-ontologiassa toiminta kuuluu tapahtumien alle (tuorein ontologian versio 3.9. vuodelta 2006) toiminta sisältyy tapahtumiin.

dol:perdurant
. . dol:event
. . . . dol:accomplishment
. . . . . . edns:action
. . . . . . . . edns:activity
. . . . . . . . . . pla:information-gathering
. . . . . . . . . . pla:planning-acticity
. . . . . . . . . . . . pla:decision-activity
. . . . . . . . . . inf:bodily-motion
. . . . . . . . . . inf:voicing
. . . . . . . . . . . . inf:speech
. . . . . . . . edns:communication-event
. . . . . . dol:achievement
. . . . . . edns:cognitive-event
. . . . dol:stative
. . . . . . dol:process
. . . . . . dol:state
. . . . . . . . edns:cognitive-state
. . . . . . . . pla:decision-state

__________________________________________________________________

CYC
- CYC-ontologiassa


BASIC FORMAL ONTOLOGY (BFO), versio 2.0 (2012)

BFO:n prosessikategoriat

processual entity
. . process
. . process aggregate
. . processual context
. . fiat part of process
. . boundary of process 

A processual entity is something that occurs or happens, has temporal parts (as well as, perhaps, spatial parts), and depends on a continuant. For example, Joe's life has parts such as infancy, childhood, adolescence, and adulthood and involves a continuant, Joe. A processual entity is any of the following: 
•	A process is something that happens over time and has distinct ends, such as a life, a holiday, or a diagnostic session. 
•	A process aggregate is a collection of processes such as the playing of the individuals in a band, or the flying of a set of planes in a day. 
•	A fiat part of process is part of a process having no distinct ends, such as the most interesting part of a holiday, or the most serious part of an operation. 
•	A processual context is the setting for some other occurrent, for example, relaxation as the setting for rejuvenation, or a surgery as a setting for an infection. 
•	A boundary of a process is the instantaneous temporal boundary of a process, such as when a robot starts to clean up the lab, or a birth. 

http://artint.info/html/ArtInt_318.html

**Comment by MikkoAleksanteri** [comment]
The Penman Upper Model:
(http://www.fb10.uni-bremen.de/anglistik/langpro/kpml/um89/um89-root.htm)

![penman upper model](https://cloud.githubusercontent.com/assets/8804680/15965287/87e13426-2f25-11e6-8f2c-010eba31d412.gif)

**Comment by MikkoAleksanteri** [comment]
Ylläesitetyn Penman mallia soveltaen voisi miettiä esim. seuraavaa toiminnan jaottelua:

- (materiallin) käsittely 
- mentaalinen toiminta
- keskinäinen toiminta
- verbaalinen toiminta

**Comment by MikkoAleksanteri** [comment]
Vaihtoehtoinen malli uudeksi jaotteluksi:


- mentaalinen toiminta 
- keskinäinen toiminta
- itsenäinen toiminta
- liikkuminen
- käsittely 

Tässä pyrittäisiin säilyttämään vanhasta mallista olennaiset osat, mutta selkiyttämään jaottelua päällekkäisyyttä karsimalla. Tässä mallissa siis vanha muokkautuisi seuraavasti:

havainnointi ja aistiminen + mentaalinen toiminta = **mentaalinen toiminta**

**keskinäinen toiminta** [säilyy ennallaan]

oleminen, omana ja halussapitäminen, kulutus ja käyttö = **itsenäinen toiminta** 

**liikkuminen** [säilyy ennallaan]

liikuttaminen, luonti, muuttaminen = **käsittely**

kontrolli [siirretään muualle, alakäsitteet eivät aina toimintaa]

muutos [siirretään tapahtumapuolelle]

**Comment by tpalonen** [comment]
Toimintahierarkian vaihtoehtoja testattu/testataan alla olevassa Google Sheetissä:
https://docs.google.com/spreadsheets/d/1M3obdYpHkM-OdjahejMeRToNHQbQ1ObCZrr5bIkZRtU/edit#gid=467051910

**Comment by kseppala** [comment]
Pitkää kuvausta on vaikea kommentoida, kun en tiedä, miten kommentit voisi kiinnittää tiettyyn tekstikohtaan, mutta tässä jonkinlainen lista. Kaikki kommentit ovat yksittäisiä huomioita ja kysymyksiä, koska varsinainen hierarkian toimivuuden arviointi edellyttäisi testausta, johon meillä ei ole mahdollisuutta.

- Mikon huomio "Kun käsitteet kuuluvat jo nyt omiin temaattisiin ryhmiinsä, onko tällöin järkevää tehdä myös hierarkkisesta jaottelusta temaattista?" on mielestäni tärkeä

Hierarkian ylätaso:
- yhteiskunnallinen toiminta: voi olla paikoittain hankala rajata, kuten kommentoit
- tekninen toiminta: tuntuu vaikealta rajata, esim. editointi: väline voi liittyä tekniikkaan, olennaisemmalta käsitteelle tuntuu kuitenkin sisällön muokkaus, jota en itse miellä tekniseksi toiminnaksi
- keskinäinen toiminta > sosiaalinen toiminta: ei sosiaalinenkaan toiminta ole ongelmaton, entäs "epäsosiaalinen" toiminta? keskinäinen on neutraalimpi
- kulttuurinen toiminta: tuntuu toiminnnan osalta vaikeammalta kuin muissa käsiteryhmissä

- kuten ominaisuuksien kohdalla, mahdollisuus valita yläkäsite ylätasolta vähentää hierarkian toimivuuteen kohdistuvia paineita, mutta toisaalta voi lisätä todennäköisyyttä sille, että hierarkioista ei muodostu yhdenmukaisia eri ontologioissa, eikä kovin hyödyllisiä, kun toiminta-tasoa tarkempaa hierarkisointia ei aina edellytetä

- vaikutukset erikoisontologioihin: erikoisontologioiden toiminta/tapahtuma-käsitteet joudutaan kuitenkin käymään yksitellen läpi ainakin niiltä osin, joissa erikoisalan käsitteen lähin yläkäsite on poistettu uudesta hierarkiasta; myös se että vanha yläkäsite siirtyy toiseen hierarkian haaraan edellyttää ainakin pistokokeina tehtäviä tarkistuksia; on tarkistettava, onko uusi hierarkia sopiva myös kaikille erikoisaloilta tuleville alakäsitteille, sillä joskus ongelmat paljastuvat vasta alakäsitteiden kautta

- perusteet muutostarpeelle: Kaikki Tapoja luokitella toimintaa ontologioissa ja kielitieteessä -tiedostossa listatuista hierarkioista aiheuttavat varmasti jollekin jossakin kohtaa vaikeuksia. Niin myös FinnONTOn malli ja tämä uusi ehdotuksenne, vaikka onkin maanläheisempi vaihtoehto kuin monet aiemmin laadituista. Siksi pitäisi mielestäni miettiä, mitä hyötyä hierarkisoinnista saadaan (aikoinaan FinnONTOssa ajateltiin, että samankaltaisuudesta Wordnetin kanssa voisi olla hyötyä, koska Wordnetiä pidettiin tuolloin mahdollisena linkityskohteena). Kommenteissa on viitattu ontologian kehittäjän työn helpottamiseen, mutta kysyisin samaa kuin ominaisuuksien osalta: oletteko miettineet, miten se että eritellään esim. yhteiskunnalliset ilmiöt, yhteiskunnallinen toiminta ja yhteiskunnalliset ominaisuudet, auttaa ontologian hyödyntäjiä? Näin muodostuu isoja ryhmiä, joissa käsitteet voivat olla keskenään hyvinkin erilaisia. En ehdota, että hierarkian pitäisi olla tarkempi, mutta tulevatko hyödyt käyttäjille kuitenkin vasta käsitteiden välisten assosiatiivisten suhteiden kautta?

**Comment by mirmaid** [comment]
Huom. muutos-käsitteen alakäsitteinä joitakin huonosti sopivia, esim. rasitus, kuormitus (ennemmin jhk kohdistuva rasitus kuin "rasittuminen"=muuttuminen rasittuneeksi).

**Comment by tpalonen** [comment]
YSO-kokouksen päätös 11.8.
- vertaillaan Mikon ehdottamaa ontologista jakoa ja Mirjan ja Tuomaksen ehdottamaa temaattista jakoa taulukossa testierällä käsitteitä
- konsultoidaan TSK:ta testierän jälkeen ja tehdään lopullinen päätös toimintahierarkian jaosta
- käydään kuitenkin ensin ilmiöt-hierarkia loppuun, joten tähän päästään vasta muutaman viikon päästä käsiksi

**Comment by MikkoAleksanteri** [comment]
> Vaihtoehtoinen malli uudeksi jaotteluksi:
> 
>     mentaalinen toiminta
>     keskinäinen toiminta
>     itsenäinen toiminta
>     liikkuminen
>     käsittely

Ehdottamaani mallia hiukan lisää pohdittuani tulin siihen tulokseen, että liikkuminen-käsite ei ehkä kuitenkaan ole paras mahdollinen; likkuminen kun voi olla keskinäistä tai itsenäistä toimintaa. Ylätaso voisikin olla seuraava:

    mentaalinen toiminta
    keskinäinen toiminta
    itsenäinen toiminta
    käsittely

**Comment by kseppala** [comment]
Voitko Mikko kertoa tarkemmin, miten poistuvat ylätason käsitteet suhteutuisivat ehdottamiisi: sisältyvätkö tietyn poistuvan ylätason käsitteen kaikki alakäsitteet yhteen uusista/jäljellle jäävistä yläluokista vai käytäisiinkö poistuvan yläluokan alakäsitteet yksittäin läpi ja sijoitettaisiin jäljelle jääneisiin yläluokkiin? Onko sinulla määritelmäluonnoksia noille yläluokille?

**Comment by MikkoAleksanteri** [comment]
@kseppala tuossa ylempänä olevassa viestissäni olin yrittänyt vähän suhteuttaa vanhaan, eli

> Tässä pyrittäisiin säilyttämään vanhasta mallista olennaiset osat, mutta selkiyttämään jaottelua päällekkäisyyttä karsimalla. Tässä mallissa siis vanha muokkautuisi seuraavasti:
> 
> havainnointi ja aistiminen + mentaalinen toiminta = mentaalinen toiminta
> 
> keskinäinen toiminta [säilyy ennallaan]
> 
> oleminen, omana ja halussapitäminen, kulutus ja käyttö = itsenäinen toiminta
> 
> liikkuminen [säilyy ennallaan]
> 
> liikuttaminen, luonti, muuttaminen = käsittely
> 
> kontrolli [siirretään muualle, alakäsitteet eivät aina toimintaa]
> 
> muutos [siirretään tapahtumapuolelle]

Mitä olisit tästä mieltä? Mallissa on varmasti vielä paljon parannettavaa ja sen soveltuvuus ylipäätään pitäisi testata itse käsitteitä perkaamalla.

**Comment by kseppala** [comment]
Testaamatta en pysty tarkemmin kommentoimaan, mutta kannatan tätä lähestymistapaa temaattisen jaon sijaan, sillä epäilen ettei tematiikka sovi toimintahierarkian periaatteeksi (käsitteillä pitäisi olla muutakin yhteistä kuin vain se, että ne liittyvät samaan aiheeseen - samaan teemaan kun voi liittyä hyvin erilaista toimintaa) ja temaattinen jako saattaisi synnyttää turhaa moniperintää silloin, kun käsitteet eivät selkeästi liity vain yhteen teemaan.

**Comment by mirmaid** [comment]
Pikaista pohdintaa..

Tämän mallin voisi nähdä niinkin, että on toimintaa joka
a) kohdistuu toimijaan itseensä
b) kohdistuu johonkin muuhun, joka
  b1) on eloton
  b2) on elävä olento

Toisaalta aina ei ole helposti pääteltävissä, onko kohde (kaikissa tapauksissa) elollinen/eloton, ei ehkä sekään, mikä on kohde, esim. "viestintä": onko kohde "se mitä viestitään", tai "se, jolle viestitään". Toimijaan itseensä kohdistuva toiminta vaihtelee sen suhteen miten aktiivista-passiivista se on. Se tulee osittain lähelle myös tapahtuma-kategoriaa (esim. profiloituminen).
 
Myös se, onko toiminta itseen vai johonkin muuhun kohdistuvaa, on joskus epäselvää: esim. eroaminen (?). Jos tämä on keskinäistä toimintaa, keskinäisen toiminnan toisen osapuolen ei voi edellyttää olevan (ainakaan selkeästi) elollinen, vrt. kirkosta eroaminen.

**Comment by tpalonen** [comment]
KOMMENTTEJA AIEMPAAN
Keskinäinen toiminta on sikäli ongelmallinen kategoria, että kaikkea yksinkin tehtävää toimintaa voi tehdä yhdessä (esim. istuminen). Ja kuten Mirja on todennut, keskinäinen toiminta, jossa toinen taho on passiivinen (esim. stailaus) on päällekkäinen käsittely-kategorian kanssa. Lisäksi keskinäinen toiminnan määritystä sekoittaa se, että se voi ensinnäkin olla yhdessä tekemistä, jossa toiminta kohdistuu tekijöiden ulkopuolelle (esim. aktivismi); tai se voi olla yhdessä tekemistä, jossa toiminta kohdistuu vastakkaiseen osapuoleen (esim. seurustelu); tai se voi olla em. käsittely-tyyppistä toimintaa, jossa toinen osapuoli on toiminnan tekijä ja toinen sen kohde.

Mentaalinen toiminta taas on ongelmallinen, koska se määrittää toimintaa eri periaatteella kuin keskinäinen/itsenäinen. Itsenäinen toiminta voi olla mentaalista, keskinäinen toiminta voi olla mentaalista (esim. ihailu). Ihailu-esimerkkiä edelleen avaten, ihailu voi olla keskinäistä kolmella tavalla: me ihailemme yhdessä Michael Jacksonia; me ihailemme toisiamme; minä ihailen sinua (mutta sinä et minua).

Minusta Mirjan edellä esittämä ehdotus on tähän astisista lähimpänä jonkinlaista positivistista ideaalia, jossa kategoriat perustuvat luonnollisen kielen toimintaperiaatteisiin eivätkä jätä varaa tulkinnalle. 

VIELÄ. YKSI. EHDOTUS.
Tässä vielä lähemmäs verbisyntaksia viety malli:

1) toiminta, jolla ei ole objektia
2) toiminta, jolla on objekti
2.1) toiminta, jolla on suora objekti
2.2) toiminta, jolla on suora ja epäsuora objekti

"Viestintä" menisi tässä mallissa 2.2. kategoriaan, koska siinä on sekä viesti että viestin vastaanottaja.

Esim. "kyläily" menisi tässä mallissa kategoriaan 1, koska sillä ei ole suoraa objektia.

**Comment by YSO-kokous** [comment]
> keskinäinen toiminta: kahden (elollisen) toimijan välinen toiminta
> itsenäinen toiminta: ensisijassa toimijan itsensä suorittama toiminta, jonka toteuttamiseen ei tarvita toista osapuolta, mutta jota voidaan tehdä yhdessä. Ei vaadi toiminnan kohdetta (tämä erottaa käsitteen käsittelysta)
> mentaalinen toiminta: ensisijassa mielensisäinen prosessi, johon ei tarvitse sisältyä fyysistä liikettä
> käsittely: elollisen toimijan ja elottoman kohteen välinen toiminta

> a) kohdistuu toimijaan itseensä
> b) kohdistuu johonkin muuhun, joka
> b1) on eloton
> b2) on elävä olento

**Comment by tpalonen** [comment]
Uusi toiminta-hierarkian ehdotus hyväksyttiin Ontologiakehittäjien yhteistyöryhmän kokouksessa. Aloitetaan hierarkian läpikäynti käymällä muutos-käsitteen alakäsitteitä läpi ja päättämällä näille uusi yläkäsite. Läpikäynti tapahtuu tässä taulukossa:

https://docs.google.com/spreadsheets/d/1CWldnmSdXmHUOn13ZiPYNZQEYYwUWPzHLXMslMMuuEQ/edit?usp=sharing

**Comment by YSO-kokous** [comment]
PÄÄTÖS
Koska läpikäytävää on paljon, hyväksytyn uudistuksen läpikäynti aloitetaan muutos-käsitteen alakäsitteistä. Läpikäynti tapahtuu alla olevassa taulukossa, johon merkitään kunkin käsitteen uusi yläkäsite:

https://docs.google.com/spreadsheets/d/1CWldnmSdXmHUOn13ZiPYNZQEYYwUWPzHLXMslMMuuEQ/edit?usp=sharing

muutos-käsite itsessään siirtyy tapahtumat-käsitteen alakäsitteeksi.

**Comment by YSO-kokous** [comment]
PÄÄTÖS
Yllä oleva muutos-hierarkian taulukko on käyty läpi ja ratkaisut merkitty käsitekohtaisesti. Mikäli nykyinen yläkäsite säilyy, Uusi yläkäsite -kohta on jätetty tyhjäksi. Pohdittavaksi jäi joukko käsitteitä, joiden kohdalla lukee "muutos vai tapahtuma?". Siirrytään nyt muun toiminta-hierarkian läpikäyntiin ja palataan tämän jälkeen ratkaisematta jääneisiin.

**Comment by YSO-kokous** [comment]
Haastavien käsitteiden läpikäynti:
https://docs.google.com/spreadsheets/d/1nFt57T-E5-Avz2ETk_fghIVcWALtY0SzYEC6DmmMG-8/edit?usp=sharing
