### ISSUE TITLE
karjantarkkailu LT tarkkailu

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#757]
Tarkkailun alakäsitteet sekalaisia ontologian puolella, onko karjantarkkailu tähän sopiva (nautakarjan ruokinnan ja tuotannon tarkkailu pitämällä niistä kirjaa) ? Tekninen tarkkailu taas on ihan eri ja selkeästi sopiva tarkkailun alle. Ruotsiksi sana on eri: boskapskontroll, eikä sitä ruotsiksi laittaisi tarkkailun alle.

**Comment by tpalonen** [comment]
PÄÄTÖS 10.06.2016
Ei muodosta ongelmaa suomen kielen puolella. Ei toimenpiteitä tällä erää.
