### ISSUE TITLE
juutalaiset

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#758]
Juutalaiset-termi jaettu ontologiassa:  

-juutalaiset (uskontokunnat) 
ST Chabad-Lubavitch, karaiitit, mizrahijuutalaiset

-juutalaiset (väestöryhmään liittyvä rooli) 
ST aškenasijuutalaiset, sefardijuutalaiset 

Muut sanastot, esim. SAO, LCSH jne. eivät tunne tällaista jakoa, eivätkä sanakirjatkaan. Juutalaisuus on toki "synnynnäistä" ja on sekä "maallistuneenmpia" juutalaisia että uskonnollisia, mutta tällaiseen jakoon ei varmaan kannata ryhtyä sanastossa (johtaisi myös siihen että kuvailijan täytyisi useimmiten laittaa molemmat).. Myös alakäsitteet näyttävät nyt olevan satunnaisesti laitettu.

**Comment by tpalonen** [comment]
PÄÄTÖS 10.6.2016:
- poistetaan "juutalaiset (väestöryhmään liittyvä rooli)". Yhdistetään alakäsitteet. Ei lisätä jäljellejäävälle sulkutarkenteellista altlabelia.
