### ISSUE TITLE
Kaivannaiset

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#759]
Kaivannaiset-käsitteen alakäsitteet:

```
kiviaines
maa-aines
maakaasu
maaöljy
malmit
mineraalit
noduulit
```

Kaivannainen on näille oikeastaan rooli. Esim. Wikipedia: "Mineraali eli kivennäinen on luonnossa kiinteässä muodossa esiintyvä alkuaine tai epäorgaaninen yhdiste, jolla on tietty koostumus ja tavallisesti säännöllinen kiderakenne."

Vrt. Öljy ei YSOn mukaan ole kaivannainen vaan rasva.

**Comment by tpalonen** [comment]
****Ehdotus.** 
Kaikilta poistetaan YK kaivannaiset ja lisätään RT kaivannaiset sekä uusi yläkäsite:

kiviaines YK luonnonmateriaalit
maa-aines YK luonnonmateriaalit
maakaasu YK kaasut + luonnonmateriaalit
maaöljy (on jo YK öljy, tämä riittää)
malmit YK luonnonmateriaalit + RT mineraalit
mineraalit YK kemialliset yhdisteet*
noduulit YK luonnonmateriaalit

* vrt YSO: "Mineraalit ovat alkuaineista koostuvia tavallisesti kiteisessä olomuodossa olevia kemiallisia yhdisteitä."

**Pohdittavaksi**
Mikä on käsitteiden "kivi" ja "kiviaines" ero? Ovatko molemmat tarpeen? Kiven yläkäsite on luonnonmateriaali. Kiviaineksellekin sopisi sama yläkäsite. Ruotsiksi kivi on "sten (material)" ja kiviaines "stenmaterial".

**Comment by YSO-kokous** [comment]
kiviaines YK aine + RT kaivannaiset
maa-aines YK aine + RT kaivannaiset
maakaasu YK kaasut + RT kaivannaiset
maaöljy: on jo YK öljy, tämä riittää + RT kaivannaiset
malmit YK kivi + RT malmimineraalit, kaivannaiset, malmiesiintymät, malminetsintä
mineraalit YK aine
noduulit YK kivi

**Comment by tpalonen** [comment]
Maakaasu-käsitteellä oli yläkäsitesuhteet myös fossiiliset polttoaineet- ja polttokaasut-käsitteisiin. Poistin yläkäsitesuhteen kaivannaisiin ja säilytin loput.
