### ISSUE TITLE
runkorakenteet

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#762]
TSK ehdotti parvekkeet-käsitteen siirtämistä suoraan rakennusosat-käsitteen alle. Runkorakenteet-käsitteellä on muitakin samantyyppisiä alakäsitteitä, jotka mahdollisesti eivät ole varsinaisia runkorakenteita?

**Comment by mariaforsen** [comment]
Ruotsin osalta ainakin kupolit voisi siirtää rakennusosien alle. 
https://byggipedia.se/byggteknik/byggnadsstomme/stomsystem/

**Comment by mariaforsen** [comment]
Monikielisyyden kannalta käsite saattaa olla muutenkin epäselvä:
(talon) stomkonstruktion 
(auton) ramkonstruktion;
(aluksen) skrovkonstruktion

**Comment by mirmaid** [comment]
portaat YK elottomat objektit RT rakennusosat
holvit, kupolit YK rakennusosat
seinät, palkit YK rakennusosat, RT runkorakenteet
