### ISSUE TITLE
fokalisaatio

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#763]
Tieteen termipankki: http://tieteentermipankki.fi/wiki/Kirjallisuudentutkimus:fokalisointi - "Fokalisoija on kerronnan agentti, jonka havainnot ja asenne antavat kertovalle diskurssille suunnan."

YSOssa valittiin LT viestintä. Ontologisesti johdonmukainen olisi "muuttaminen", mutta vähintään yhtä hyvä kuin viestintä olisi tarkempi "kerronta".

**Comment by YSO-kokous** [comment]
YK näkökulma
