### ISSUE TITLE
tanssipaikat

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#764]
Nyt vain ST diskot. Tänne sopisi myös tanssilavat, ehkä myös yökerhot.

**Comment by tpalonen** [comment]
**Ehdotus**

tanssilavat YK tanssipaikat
yökerhot RT tanssipaikat

Tanssipaikat kuuluvat paikka-hierarkiaan. Yökerhon tulkitseminen paikaksi tuntuu oudolta. Siksi säilyttäisin nykyisen yläkäsitteen "organisaatiot (järjestelmät)".

**Comment by YSO-kokous** [comment]
Toteutetaan tehdyt ehdotukset.
