### ISSUE TITLE
mekanismit

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#765]
YSO LT tekniset objektit (fyysiset objektit). Melindassa käytetty kuitenkin abstraktissa merkityksessä. Kielitoimiston sanakirja: 2. jhk vaikuttavasta, jtak aiheuttavasta säännönmukaisesta tapahtumasarjasta.

**Comment by mirmaid** [comment]
wikisanakirja: (kuvallisesti) järjestelmä, joka säännönmukaisesti aiheuttaa tietyn seurauksen

Ehdotus: poistetaan huomautus, YK järjestelmät

**Comment by YSO-kokous** [comment]
Poistetaan huomautus, YK järjestelmät.
