### ISSUE TITLE
rakennelmat

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#766]
Kielitoimiston sanakirja: yksinkertainen, väliaikainen t. abstrakti rakenne, luomus. Nyt joitakin outoja alakäsitteitä, kuten teltat, kanavasulut, kaivot, vallit.

**rakennelmat**
. aidat
. . . pensasaidat
. aitaukset
. bunkkerit
. kaivot
. . . arteesiset kaivot
. . . porakaivot
. . . . . lämpökaivot
. . . rengaskaivot
. . . saostuskaivot
. kanavasulut
. kasvihuoneet
. kasvilavat
. leikkimökit
. maitolavat
. pergolat
. portit
. säleiköt
. teltat
. vallit
. öljynporauslautat

**Comment by tpalonen** [comment]
En näe suurinta osaa näistä käsitteistä ongelmallisena. Monet näistä ovat määritelmällisesti rakennelmia, esim. _"Öljynporauslautta on merelle sijoitettu rakennelma"_ (Wiki). Bunkkeri: _"betoninen t. kallioon louhittu korsumainen puolustusrakennelma"_ (Kielitoimiston sanakirja). Teltat-käsitteelle en keksi muuta yläkäsitettä kuin "elottomat objektit", mutta rakennelmat taitaa olla sittenkin parempi vaihtoehto. Seuraavat siirtäisin:

säleiköt YK elottomat objektit
vallit YK ihmisen määrittämä paikka

**Comment by mariaforsen** [comment]
Rakennelmat on nyt kaiken lisäksi käännetty "enklare byggnader" YSO-kokous-käsittelyn seurauksena, joten osa ala-käsitteistä, ainakin öljynporauslautat pitäisi todella siirtää muualle.

**Comment by tpalonen** [comment]
Asia ratkaistu täällä ja rakennelmat poistettu YSOsta: https://github.com/Finto-ehdotus/YSE/issues/7893
