### ISSUE TITLE
sisarukset-käsitteen alakäsitteet

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#768]
YSAssa termeillä esikoiset, kuopukset, kaksoset jne. on toisena LT:nä lapset. YSOssa voisi lisätä lapset (perheenjäsenet) ainakin RT:ksi.

**Comment by mirmaid** [comment]
Esikoiset, kuopukset olisiko hyvä olla toisena yläkäsitteenä? Nyt ainoa lapsi YK lapset (perheenjäsenet) - samantyyppinen. (miksiköhän se on yksikössä, maailman ainoa lapsi...  :simple_smile:)

**Comment by YSO-kokous** [comment]
Esikoiset, kuopukset > toinen YK lapset (perheenjäsenet). Kaksoset jne. RT lapset (perheenjäsenet).
