### ISSUE TITLE
Kaukasialaiset kielet ja paleoaasialaiset kielet ja papualaiset kielet

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#770]
Saman tyyppinen ongelmatiikka kolmessa kielikunta-käsitteessä.

1) Kaukasialaiset kielet sisältää paljon alakäsitteitä, mm. abhaasin kieli ja georgian kieli. Yläkäsitteenään kielet kielikunnan mukaan. Kaukasialaiset kielet eivät kuitenkaan ole kielikunta. Wikipedia: "Linguistic comparison allows these languages to be classified into several language families, with little or no discernible affinity to each other. However, the languages of the Caucasus are sometimes mistakenly referred to as a family of languages."

Ehdotan seuraavia vaihtoehtoja:
a) kaukasialaiset kielet LT kielet [nykyinen yläkäsite kielet kielikunnan mukaan]
TAI
b) kaikki kaukasialaisten kielten alakäsitteet LT kielet + RT kaukasialaiset kielet
TAI
c) luodaan uudet korrektit yläkäsitteet kullekin kielelle sen mukaan, mihin kielikuntaan ne kuuluvat. Esim. georgian kieli LT "kartvelilaiset kielet"

---

2) Sama problematiikka liittyy myös paleoaasialaisiin kieliin, joiden alakäsitteinä on eskimo-aleuttilaiset kielet, eskimokielet ja jeniseiläiset kielet. Wikipedia: "Paleosiberian (Palaeosiberian, Paleo-Siberian) languages or Paleoasian languages (Palaeo-Asiatic) (from Greek palaios, "ancient") is a term of convenience used in linguistics to classify a disparate group of linguistic isolates as well as a few small families of languages spoken in parts both of northeastern Siberia and of the Russian Far East. They are not known to have any linguistic relationship to each other". Lisäksi eskimokielet pitäisi olla eskimo-aleuttilaisten kielten alakäsite. Wikipedia: "The Eskimo–Aleut language family is divided into two branches, the Eskimo languages and the Aleut language." Eskimo-aleuttilaiset kielet ja jeniseiläiset kielet ovat omia kielikuntiaan.

Ehdotan seuraavia toimenpiteitä:
1) eskimokielet LT eskimo-aleuttilaiset kielet
2) eskimo-aleuttilaiset kielet & jeniseiläiset kielet LT kielet kielikunnan mukaan
2) paleoaasialaiset kielet LT kielet (+RT kielikunnat?)

---

3) Sama visaisuus liittyy myös papualaisiin kieliin, joiden alakäsitteinä on huan kieli ja mauwaken kieli. Wikipedia: "The term does not presuppose a genetic relationship. - - - Besides the Austronesian languages, there are some 800 languages divided into perhaps sixty small language families, with unclear relationships to each other or to any other languages, plus a large number of language isolates."

Ehdotan seuraavia vaihtoehtoja:
a) papualaiset kielet LT kielet [nykyinen yläkäsite kielet kielikunnan mukaan]
TAI
b) huan kieli & mauwaken kieli LT kielet + RT papualaiset kielet

**Comment by MikkoAleksanteri** [comment]
YSO-kokous:
1. ratkaistu aiemmin
2. korjataan ehdotuksen mukaiseksi YSAssa @mirmaid 
3. hyväksytään ehdotukset a) ja b), toteutetaan YSAan @mirmaid

**Comment by mirmaid** [comment]
kohta 2
eskimokielet LT eskimo-aleuttilaiset kielet - on jo näin YSAssa, joten korjaus ei siirry YSOon
eskimo-aleuttilaiset kielet & jeniseiläiset kielet LT kielikunnat YSAssa
paleoaasialaiset kielet LT kielet (+RT kielikunnat?) - ei RT

**Comment by mirmaid** [comment]
kohta 3
a) papualaiset kielet LT kielet [nykyinen yläkäsite kielet kielikunnan mukaan] - OK
TAI
b) huan kieli & mauwaken kieli LT kielet + RT papualaiset kielet - jätin LT papuakielet, joka on oikein, vaikka ei olekaan kielikunta (samoin tehty muitakin).

**Comment by YSO-kokous** [comment]
Nämä ok.
