### ISSUE TITLE
Monitoimisuus, muoto (rakenteellinen), notkeus, refleksiivisyys jne.

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#771]
Jostain syystä ominaisuudet-listauksen ulkopuolelle on jäänyt vielä pieni joukko käsitteitä ja näiden uusi paikka hierarkiassa pitäisi päättää. Nämä ovat:

monitoimisuus   LT sisäiset ominaisuudet
muoto (rakenteellinen)    LT sisäiset ominaisuudet
notkeus   LT sisäiset ominaisuudet
refleksiivisyys   LT sisäiset ominaisuudet
ympätistön tila   LT sisäiset ominaisuudet
monikanavaisuus   LT ulkoiset ominaisuudet
päätoimisuus   LT ulkoiset ominaisuudet
rajat   LT ulkoiset ominaisuudet

**Comment by mariaforsen** [comment]
Osa olivat ruotsin vastineen takia ongelmallisia.

**Comment by mirmaid** [comment]
YSO-kokous 11.1.2017:

Ongelmatapaukset käsittelyssä YSAssa.
