### ISSUE TITLE
Fyysiset ominaisuudet, fysikaaliset ominaisuudet, aineen ominaisuudet

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#772]
Näiden välinen ero ja varsinkin fyysisten ja fysikaalisten välinen ero on hyvin epäselvä. Pitäisikö fyysiset ja fysikaaliset ominaisuudet yhdistää? Entä aineen ominaisuudet? Ellei yhdistetä, pitäisi tehdä selkeä linjaus merkityserosta ja siitä, minkälaisia käsitteitä kunkin käsitteen alle hierarkisoidaan. Tällä hetkellä käsitteiden ero ei ole lainkaan selvä.

**Comment by mirmaid** [comment]
Käsitellään issuessa https://github.com/NatLibFi/Finto-data/issues/698
