### ISSUE TITLE
myytit

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#773]
LT kansantarinat. Käytetty Melindassa laajemmin: markkinaliberalismin myytit jne. Vaihdetaanko yläkäsite vai yritetäänkö ohjata käyttöä esim. termeihin uskomukset, käsitykset?

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja:
1. jumalia, yliluonnollisia olentoja, maailman syntyä tms. käsittelevä taru, jumalaistaru. Antiikin myytit. Maailman luomisesta kertovat myytit.
2. tarunomainen asia, kuvitelma, uskomus. Äitiyteen liittyvät myytit.
3. suuresti ihailtu, legendaarinen henkilö. Marilyn Monroesta on tullut myytti. 

wikisanakirja:
tarina tai uskomus, joka selittää asioita, joista ei ole ensikäden tietoa tai joiden paikkansapitävyyttä ei voida todistaa

**Comment by YSO-kokous** [comment]
YK kulttuuriset objektit, RT kansantarinat/kansankertomukset, mytologia? @tpalonen

**Comment by tpalonen** [comment]
RT kansankertomukset ja mytologia ok. Lisäisin myös RT:n syntykertomukset. Se on KULOssa myytit-käsitteellä RT:nä.

**Comment by mirmaid** [comment]
Syntykertomukset nyt alakäsitteenä.

**Comment by mariaforsen** [comment]
Termi ja sen suhteet näyttää nyt hyvältä.

**Comment by mirmaid** [comment]
Lisätään RT mytologia, kansankertomukset ja kansantarinat.
