### ISSUE TITLE
kirjallisuuden tyylit

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#774]
Oliko tämä käsite päätetty säilyttää? Olemme ilmeisesti siirtäneet alakäsitteet tyylit-käsitteen alle. Onko ero genreen (KT kirjallisuuden lajit) riittävän selkeä jotta kannattaa säilyttää?

**Comment by tpalonen** [comment]
Tämän alla on myös KITO-, KAUNO- , VALO- ja TAO-käsitteitä eli pitää konsultoida heitä, onko käsite heidän mielestään tarpeellinen. Tosin voisin kuvitella, että underground ja neorealismi ovat VALOn näkökulmasta muuta kuin kirjallisuuden tyylejä toisin kuin KOKOssa nykyään on.

**Comment by tpalonen** [comment]
@kseppala
MAO/TAOssa on käsitteitä, jotka on ripustettu yläkäsitesuhteella YSOn kirjallisuuden tyylit -käsitteeseen. Nämä käsitteet ovat: modernismi [mao/p1452], modernismi [tao/p117] ja neorealismi [tao/p532]. Niillä on yläkäsitteenä lisäksi myös MAO/TAOn oma "tyylikaudet ja taidesuuntaukset". Lisäksi näillä on myös vastaavuuslinkki YSOn samannimisiin modernismi- ja neorealismi-käsitteisiin. Olemme miettineet YSOn puolella, onko tälle kirjallisuuden tyylit -käsitteelle ylipäätään tarvetta. Vastaavia käsitteitä voisi luoda mistä taidemuodosta tahansa, mutta muun kuin kirjallisuuden osalta näin ei ole tehty. Toisaalta monet tyylisuunnat liittyvät useampaan eri taidemuotoon. Esim. modernismia on niin arkkitehtuurissa kuin musiikissakin. MAO/TAOn kannalta on jopa yllättävää, että modernismi on rajattu nimenomaan kirjallisuuden kontekstiin.


YSOssa nämä käsitteet onkin tulkittu merkitykseltään laajemmin, eli viittaavat taidesuuntaukseen yleisesti ilman rajausta pelkästään kirjallisuuden piiriin. MAO/TAOn käsitteiden linkitys YSOon on siis sikäli virheellinen, että MAO/TAOn merkitysrajauksen vuoksi käsitteet eivät näissä ontologioissa vastaa täysin toisiaan. Toinen laajempi ongelma on se, että YSOn tyylit-käsite on siirretty ilmiöt-hierarkiasta kulttuuriset objektit -hierarkiaan. Tästä seuraa, että edellä mainittujen käsitteiden kaksi yläkäsitettä johtavat nykyisessä YSOn hierarkiassa kahteen päähaaraan ja nykyisten kehityslinjausten mukaan tällainen monihierarkia ei ole sallittu.


Ongelma saattaa olla hieman vaikeasti hahmotettava (ainakin se on itselleni sitä). Mutta yksi tapa ratkaista se (mikäli tämä MAO/TAOlle sopisi) olisi poistaa edellä mainituilta MAO/TAO-käsitteiltä yläkäsitesuhde kirjallisuuden tyyleihin, jolloin tulkittaisiin, että ne ovat kirjallisuuskontekstia laajempia käsitteitä, ja tämän lisäksi siirrettäisiin "tyylikaudet ja taidesuuntaukset"-käsite YSOn kulttuuriset ilmiöt -käsitteen alle, kuten YSOn ilmiöt-käsitekin.

**Comment by YSO-kokous** [comment]
Katri Seppälä kommentoi:

_Nykyisessä, juuri Fintossa julkaistavaksi valmisteltavassa versiossa ongelmaa ei ole. Muokatussa MAO/TAOssa:

- mainituilla MAO/TAO-käsitteillä on yläkäsitteinä MAO:tyylikaudet ja taidesuuntaukset ja YSO:tyylit, ei kirjallisuuden tyylit
- MAO/TAO-käsitteillä on ekvivalenssi YSOn vastaaviin käsitteisiin
- MAO:tyylikaudet ja taidesuuntaukset ja YSO:tyylit ovat ekvivalentteja; niillä on molemmilla sama yläkäsite YSO:kulttuuriset objektit

Kun uusi MAO/TAO tulee teille lähipäivinä julkaistavaksi, voit vielä itse tarkistaa tilanteen ja poistaa Github-keskusteluaiheen, jos katsot sen tarpeettomaksi - tai pyytää meiltä lisätietoa, jos jokin asia on epäselvä._

**Comment by tpalonen** [comment]
Koska "kirjallisuuden tyylit" oli käytetty yläkäsitteenä ainoastaan MAO/TAOssa eikä nykyisin siis enää siinäkään niin tältä osin estettä käsitteen poistamiselle ei ole.

Ehdotus: poistetaan YSOsta "kirjallisuuden tyylit".
