### ISSUE TITLE
sieppaukset

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#778]
Aiemmin ollut LT järjestetyt tapahtumat, nyt siirretty tilapäisesti LT tapahtumat, koska järjestetyt tapahtumat poistui. Jäi ratkaisematta tapahtumien läpikäynnin yhteydessä.

Sieppaus-rikosnimikettä ei ole Suomessa. Onko rikos vai esim. keskinäiseen toimintaan liittyvä tapahtuma?

**Comment by mirmaid** [comment]
YSO-kokous 15.3.2017:

YK keskinäiseen toimintaan liittyvät tapahtumat
