### ISSUE TITLE
Uskonnolliset tapahtumat

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#779]
Pitäisikö muuttaa muotoon "uskontoon liittyvät tapahtumat"?

Vrt. uskontoon liittyvät objektit, uskontoon liittyvät ominaisuudet

**Comment by MikkoAleksanteri** [comment]
YSO-kokous 4.8.2016:

OK.

**Comment by tpalonen** [comment]
Suomi tehty. Pitäisikö englannin ja ruotsin label myös vaihtaa?

**Comment by satuniininen** [comment]
Enkku tehty

**Comment by mariaforsen** [comment]
Tehty myös ruotsiksi. Onko tämä todella ainoa "tapahtumat" johon tällainen muutos tarvitaan...

**Comment by mirmaid** [comment]
Varmaan voisi toimia monessa muussakin kohdassa nykyisiä labeleita paremmin. Tässä kai kuitenkin ongelma oli sekoittuminen "uskonnolliset tilaisuudet" -käsitteeseen.
