### ISSUE TITLE
luonnontieteellinen muutos & biologiset tapahtumat

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#780]
Näissä ryhmissä samantyyppisiä käsitteitä, esim. itäminen LT luonnontieteellinen muutos, kukinta LT biologiset tapahtumat. Voisiko ryhmiä osittain yhdistää tai selkeyttää eroa, "luonnontieteellinen" sisältää myös biologian, mutta ryhmässä ehkä enemmän fysiikan, kemian, geologian jne. alaan kuuluvia käsitteitä. Luonnontieteellinen on muutenkin jakona ongelmallinen, koska vastaavaa ei esiinny muissa pääkategorioissa (luonnontieteelliset ominaisuudet/objektit), eikä alakäsitteiden kuvaama muutos ole välttämättä "luonnontieteellinen" vaan "luonnossa tapahtuva".

**Comment by tpalonen** [comment]
Myös fysikaaliset tapahtumat ja biologiset ilmiöt -hierarkioissa nyt samantyyppisiä käsitteitä.

**Comment by mariaforsen** [comment]
Sanastossa myös "luonnontieteelliset järjestelmät", pitäisikö sekin korjata vastaavalla tavalla?

**Comment by mirmaid** [comment]
Myös _luonnontieteelliset ajanjaksot_ sisältää vastaavia.

**Comment by YSO-kokous** [comment]
Tuomas tekee taulukon, jossa listattuna:

-

**Comment by YSO-kokous** [comment]
luonnontieteelliset järjestelmät: ehdotettu jaettavaksi biologisiin ja fysikaalisiin järjestelmiin. Käsitellään järjestelmät-hierarkian läpikäynnin yhteydessä.

**Comment by tpalonen** [comment]
Tässä taulukko, jossa biologiset tapahtumat, luonnontieteellinen muutos ja fysikaaliset tapahtumat -käsitteiden alakäsitteet:

https://docs.google.com/spreadsheets/d/1kMwcVOPxXDRf55oMB0ZV-E-x7IJ9x39-E0SAN6aE2qQ/edit?usp=sharing

**Comment by YSO-kokous** [comment]
Taulukko on käyty läpi. Toteutetaan taulukkoon merkityt ratkaisut dataan. @tpalonen toteuttaa.
https://docs.google.com/spreadsheets/d/1kMwcVOPxXDRf55oMB0ZV-E-x7IJ9x39-E0SAN6aE2qQ/edit?usp=sharing

**Comment by YSO-kokous** [comment]
Tehty yllä päätetty nimenmuutos eli poistetaan sanastosta luonnontieteelliset ajanjaksot ja luodaan korvaavaksi käsitteeksi biologiset ajanjaksot, josta tehdään hierarkisoiva käsite. Lisäksi seuraavat muutokset.

geologiset kaudet YK ajanjaksot
ilmastokaudet YK ajanjaksot
kaamos YK luonnonilmiöt
kuivakausi YK ajanjaksot
sadekausi YK ajanjaksot
puoliintumisaika YK ajanjaksot
vuodenajat YK ajanjaksot
vuorokaudenajat YK ajanjaksot
tasannevuodet YK biologiset tapahtumat
vaihdevuodet YK biologiset tapahtumat [vrt. andropaussi]

**Comment by YSO-kokous** [comment]
Palataan yllä olevaan tpalonen-taulukkoon loppuvuodesta 2021.

**Comment by mirmaid** [comment]
Palataan taulukkoon v. 2022. Kokeillaan, voitaisiinko pitää sprinttiviikon tapaisia työpajapäiviä muutama myös keväällä.

**Comment by mirmaid** [comment]
Jäljellä 

- luonnontieteelliset ajanjakso, jonka uudelleennimeämisestä on jo aiemmin sovittu. Ryhmä on toisaalta aika suppea ja vähän sattumanvarainen. Voisiko sen jopa poistaa?
- luonnontieteelliset järjestelmät

**Comment by mirmaid** [comment]
Taulukko ilmeisesti jo käyty läpi aiemmin.

**Comment by mirmaid** [comment]
Luonnontieteelliset ajanjaksot: siirretään alakäsitteet suoraan ajanjaksojen alle.

depolarisaatio/repolarisaatio - tarvitaanko tarkenne?
luutuminen, muodonvaihdos, äänenmurros: lisätään YK muutos
toiminta-tyyppiset > toiminta-hierarkiaan taulukon mukaan
raskaus, tiineys > biologiset ilmiöt

**Comment by mirmaid** [comment]
depolarisaatio/repolarisaatio - tarvitaanko tarkenne?
