### ISSUE TITLE
muuntelu

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#787]
Ruots. variation. Molemmat käytetty aika paljon muuhunkin kuin biologiseen, esim. kieleen tai musiikkiin liittyviin viitteisiin.. Ks. Melinda. Ontologian puolella lisätty tarkenne. Pitääkö jakaa tms. ? Sanastossa myös muunnelmat/variationer.

**Comment by mirmaid** [comment]
KULAssa (ja KULOssa) on termi muuntelu - KT variaatio, RT toisinnot. Termi toisinnot on nykyisin myös YSAssa.

Termiä muuntelu on käytetty sisällönkuvailussa paljon KULAn tarkoittamassa merikityksessä. Folkloristiikassa sitä käytetetään, kun tutkitaan suullisen perinteen (esimerkiksi tietyn kansansadun) ajallista, alueellista, sosiaalista tms. vaihtelua.

KULOssa muuntelun yläkäsitteenä on kulttuuriset ilmiöt, käsitteen toisinnot yläkäsite on kulttuuriset tuotokset. Molemmille käsitteille (muuntelu ja toisinnot) on tarvetta sisällönkuvailussa.

https://github.com/Finto-ehdotus/YSE/issues/5249

**Comment by mirmaid** [comment]
Voidaan varmaan lisätä tarkenne muuntelu (biologia) rajaamaan merkitystä. Kun sanastossa on jo muunnelmat ja toisinnot, yleistermi vaihtelu, sekä vastikään lisätty variaatio (kielitiede), tarvitaanko vielä muuntelu-termiä muussa kuin biologian yhteydessä?

**Comment by YSO-kokous** [comment]
Muuntelu (folkloristiikka) KÄ muunnelmat, toisinnot TAI muuntelu (folkloristiikka)?

**Comment by mariaforsen** [comment]
Pyrkimys on ollut välttää yksikkö/monikko-tuplia, kannatan sitä edelleen. Ainakin ruotsin osalta käy yhtä hyvin käyttää variationer kuin variation.
