### ISSUE TITLE
arkielämä, kansanelämä, katuelämä ym.

### ISSUE THREAD

**Issue by MikkoAleksanteri** [NatLibFi/Finto-data#788]
Erilaisia -elämä -käsitteitä löytyy ilmiöiden alta. Näille olisi varmaan hyvä löytää joku yhtenäinen linja/yläkäsite.
- arkielämä (LK yhteiskunnalliset ilmiöt)
- kaksoiselämä (LK yhteiskunnalliset ilmiöt)
- kansanelämä (LK yhteiskunnalliset ilmiöt)
- katuelämä (LK yhteiskunnalliset ilmiöt)
- kulttuurielämä (LK kulttuuriset ilmiöt)
- leirielämä (LK yhteiskunnalliset ilmiöt)
- opiskelijaelämä (LK yhteiskunnalliset ilmiöt)
- perhe-elämä (LK yhteiskunnalliset ilmiöt)
- seuraelämä (LK yhteiskunnalliset ilmiöt)
- seurakuntaelämä (LK yhteiskunnalliset ilmiöt)
- sukupuolielämä (LK biologiset ilmiöt)
- työelämä (LK yhteiskunnalliset ilmiöt)
- yksityiselämä (LK yhteiskunnalliset ilmiöt)
- yöelämä (LK yhteiskunnalliset ilmiöt)

**Comment by tpalonen** [comment]
YSO-kokous 4.11.2016:

Siirretään kaikki edellä mainitut käsitteen "oleminen"-käsitteen alle. Käsiteltäneen uudestaan toiminta-hierarkian läpikäynnin yhteydessä.

**Comment by YSO-kokous** [comment]
PÄÄTÖS

tekoelämä YK kohdistuva toiminta
tunne-elämä YK biologiset ilmiöt
uskonelämä YK yhteiskunnalliset ilmiöt
(kilvoittelu YK itsenäinen toiminta + RT uskonelämä)
(spiritualiteetti YK uskontoon liittyvät ominaisuudet + RT uskonelämä)
työelämä YK yhteiskunnalliset ilmiöt
yksityiselämä YK yhteiskunnalliset ilmiöt
yöelämä YK yhteiskunnalliset ilmiöt
arkielämä YK yhteiskunnalliset ilmiöt
leirielämä YK yhteiskunnalliset ilmiöt
opiskelijaelämä YK yhteiskunnalliset ilmiöt
perhe-elämä YK yhteiskunnalliset ilmiöt
seuraelämä YK yhteiskunnalliset ilmiöt
seurakuntaelämä YK yhteiskunnalliset ilmiöt
sukupuolielämä YK yhteiskunnalliset ilmiöt
kaksoiselämä YK yhteiskunnalliset ilmiöt
kansanelämä YK yhteiskunnalliset ilmiöt
katuelämä YK yhteiskunnalliset ilmiöt
kulttuurielämä YK kulttuuriset ilmiöt [alakäsitteet musiikkielämä ja taide-elämä säilyvät]
