### ISSUE TITLE
kanavat

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#789]
Monimerkityksinen termi, pitääkö jakaa, lisätä sulkutarkenteita tms.?

**Comment by mariaforsen** [comment]
Todettu myös JUHO-kokouksessa, jossa päätetty että odotetaan YSOn ratkaisua.

**Comment by MikkoAleksanteri** [comment]
Maria tekee issuen ehdotusjärjestelmään.
