### ISSUE TITLE
Kuori

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#790]
Kuoren nykyinen LT on kasvinosat. Käsitettä on kuitenkin käytetty kuvailussa laajemmin. Yleisin merkitys on puunkuori, mutta käsitettä on käytetty esim. merkityksessä munan kuori ja kotilon kuori.

Vaihtoehtona tässä on joko:
a) siirtää käsite korkeammalle hierarkassa, jolloin sen merkitys lavenee TAI
b) jakaa käsite useaksi eri käsitteeksi, esim. kasvinosat ja ruumiinosat. Tosin munankuori ei ole ruumiinosa.

**Comment by mariaforsen** [comment]
Siirto ylemmäs tai jako niin että koskee sekä kasvit että eläimet on ok ruotsiksi, koska molemmissa merkityksissä käytetään "skal".

**Comment by YSO-kokous** [comment]
puunkuori KÄ kaarna, tuohi @jarmosaarikko

**Comment by jarmosaarikko** [comment]
**Kuori**  YK ei voi olla 'kasvinosat'. Ohjausterminä on nyt  "kuori (kasvinosat)".

EHDOTUS (A) --> **kuori** 
YK **fyysiset kokonaisuudet** -- ohjaustermi "suojakuori"  -- ei erotella kuoren tyyppiä lainkaan.

Mikäli halutaan jakaa, niin kielitoimiston mukaan yleiskäsite jakautuun kolmeen tyyppiin: 
1.  jtak esinettä, ainetta tms. peittävä ohuehko **ainekerros**. Puun, omenan, leivän, makkaran kuori myös →←. Kiisselin kuori. Munankuori myös ←→. Maankuori. Syödä perunat kuorineen.
EHDOTUS (B 1/4)--> **kuori (elollinen)**  
YK elottomat fyysiset kokonaisuudet  
ST  puunkuori KT kaarna, tuohi, korkki;     "kuori (kasvinosat) ohjaustermiksi tähän?
skos:note Esimerkiksi siemenen kuori, hedelmän kuori, perunan kuori, munan kuori,

2. ohuehko suojaava (t. koossa pitävä) **päällys**. Kellon, laakerin kuoret. Kiukaan kuori. Kirjekuori.
Erik. eräiden alkeellisten eläinten ruumista t. sen osaa peittävä kova pintakerros. Simpukan, etanan kuori. Äyriäisten kitiinikuori.
EHDOTUS (B 2/4) --> **kuori (eloton)**    
YK elolliset fyysiset kokonaisuudet
RT maankuori,   jonka YK on nyt "luonnontieteelliset järjestelmät".
skos:note  Esimerkiksi kirjekuori, kitiinikuori, kotilon kuori, kellon kuori, elektronikuori, lääkekapselin kuori

3. **kuv**. Kovan, karkean kuoren alla sykkii lämmin sydän. Kuoreensa sulkeutunut ihminen. Vetäytyä kuoreensa.
EHDOTUS (B 3/4) -->  "sisäinen kuori"   
YK mentaaliset objektit
(mikäli on tarpeen erottaa muista kuorista, kirjallisuutta löytynee?)

JS: on myös neljäs merkitys **kirkon kuori**,  joka on kirkon osa, jossa sijaitsee alttari.
EHDOTUS  (B 4/4)--> **kuorit**
YK "huoneet"  
Ryhmä 37 Rakentaminen ja 91 Arkkitehtuuri
  --  wikipediassa https://fi.wikipedia.org/wiki/Kuori_(arkkitehtuuri)

**Comment by YSO-kokous** [comment]
Siirretään ylemmäs hierarkiassa, tehdään YSE-ehdotus uudesta termistä puunkuori.

**Comment by jarmosaarikko** [comment]
@satuniininen ---  pitäisikö olla  kuitenkin 
**kuori** LT kasvinosat   
**puunkuori**  LT kasvimateriaalit  (KT kaarna)   
**tuohi** LT puunkuori
*korkki** LT puunkuori    
Oletan, että tuohi käsitellään kuvailussa yleensä materiaalina samoin kuin korkki, kivi tai puu (luonnonmateriaalit)

**Comment by satuniininen** [comment]
https://github.com/Finto-ehdotus/YSE/issues/6685
