### ISSUE TITLE
Kielletty monihierarkia: alkoholismi, epämuotoisuuskammo jne.

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#791]
Tein Sparklen 22.8.2017 ja löysin YSOsta seuraavat kielletyt monihierarkiat. Näillä käsitteillä siis yläkäsite kahdesta eri päähaarasta, mikä ei ole sallittua. (YK = yläkäsite). Nämä käsitteet ovat:

1. epämuotoisuuskammo YK pelot (spesifiset) + fobiat
2. klaustrofobia YK pelot (spesifiset) + fobiat
3. korkean paikan kammo YK pelot (spesifiset) + fobiat
4. julkisten paikkojen pelko YK pelot (spesifiset) + fobiat
5. sosiaalisten tilanteiden pelko YK pelot (spesifiset) + fobiat
- - -
6. flebografia YK tutkimusmenetelmät + diagnostiikka
7. iirisdiagnostiikka YK tutkimusmenetelmät + diagnostiikka
8. irtosolututkimus YK tutkimusmenetelmät + diagnostiikka
9. sikiödiagnostiikka YK tutkimusmenetelmät + diagnostiikka
10. varjoainetutkimus YK tutkimusmenetelmät + diagnostiikka
- - -
11. harha-aistimukset YK aistimukset + mielenterveyshäiriöt
11.b optiset harhat YK harha-aistimukset
- - - 
12. kaivannaisteollisuus YK teollisuus + alkutuotanto
12.b kaivosteollisuus YK prosessiteollisuus + kaivannaisteollisuus
12.c turveteollisuus	 YK kaivannaisteollisuus 
12.d kiviteollisuus YK kaivannaisteollisuus
- - - 
13. alkoholismi YK päihderiippuvuus + taudit
14. kielellinen erityisvaikeus	YK kehityksen erityisvaikeudet + puhehäiriöt
15. klassinen arkeologia YK arkeologia + antiikintutkimus
16. kouluyhteisö YK yhteisöt + oppitunnit
17. sanajärjestys  YK kielelliset ominaisuudet + järjestys
18. tofu YK soijatuotteet + kasviproteiinivalmisteet + vihannesvalmisteet
19. verenseisautus	YK parannusmagia + kansanlääkintä
20. gravimetria YK mittaus + kvantitatiivinen analyysi
- - -
Näiden lisäksi oli kolme uutta (08/2017) käsitettä, joilla on kiellettymonihierarkia, mutta nämä ratkaistaneen muualla:
cover-versiot YK sovitukset + musiikkiesitykset + äänitykset
encoret YK ohjelmistot + musiikkiesitykset
klaaviharjoitukset YK säveltapailu + nuotinluku

**Comment by YSO-kokous** [comment]
Päätös:

epämuotoisuuskammo YK fobiat
klaustrofobia YK fobiat


@mariaforsen tekee YSE-ehdotuksen: pitäisikö "pelko (tunteet)" ja "pelko (spesifiset)" yhdistää?

**Comment by tpalonen** [comment]
Toteutettu epämuotoisuuskammosta sosiaalisten tilanteiden pelkoon.
