### ISSUE TITLE
poistettujen ketjujen uudelleenohjaukset

### ISSUE THREAD

**Issue by MikkoAleksanteri** [NatLibFi/Finto-data#792]
Tehdään sparkkeli ja tarkistetaan että ohjaukset ovat järkeviä. Esim: http://finto.fi/yso/fi/page/p19483 (ilma -- lämpötila) voisi olla parempi että ohjaukset käsitteisiin "ilma" ja "lämpötila" (nyk. "fyysiset ominaisuudet" ja "lämpötila").

**Comment by tpalonen** [comment]
Taulukko löytyy täältä:
https://docs.google.com/spreadsheets/d/1jhu1QiaHb1dODujeX1J7OQVwzNJs6d_OWcXngiQJZtA/edit?usp=sharing

**Comment by MikkoAleksanteri** [comment]
Esimerkkikäsitteen toinen ohjaus (fyysiset ominaisuudet) korjattu (ilma).

**Comment by mirmaid** [comment]
Ainakin vesi -- lämpötila replacedBy-suhde on itse asiassa vain lämpötila-käsitteeseen ja fyysiset ominaisuudet on "deprecated subclass of". 
Kuuleminen -- oikeustiede -ketjulle parempi ohjaus kuin _keskinäinen toiminta_ voisi olla _kuuleminen (menettely)_, mutta en tiedä kannattaako näille enää tehdä mitään.

**Comment by mirmaid** [comment]
^ Korjataan kuuleminen -- oikeustiede. Ei tarvita enää muita muutoksia.
