### ISSUE TITLE
Sivilisaatio - objekti vai tapahtuma?

### ISSUE THREAD

**Issue by MikkoAleksanteri** [NatLibFi/Finto-data#793]
Merkityksen mukaan tulee päättää yläkäsite
http://www.yso.fi/onto/yso/p14980
alakäsitteenä nyt "vieraat sivilisaatiot"

MOT Kielitoimiston sanakirja:
**sivilisaatio**3 sivistys, kulttuuri (1). Avaruuden vieraat sivilisaatiot.

**Comment by mirmaid** [comment]
As an uncountable noun, civilization also refers to the process of a society developing into a centralized, urbanized, stratified structure.  https://en.wikipedia.org/wiki/Civilization

Molemmat aspektit ovat varmasti termissä läsnä ja Melindan perusteella myös kuvaillussa aineistossa. Nykyinen YK yhteiskunnalliset järjestelmät on minun puolestani ok.

**Comment by YSO-kokous** [comment]
Poistetaan ohjaustermi sivilisaatiot KÄ kulttuurit.
