### ISSUE TITLE
anomia

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#794]
Nyt LT yhteiskuntaolot, ei sovi kovin hyvin kaikissa tapauksissa. Käsitteellä huomautus: Normittomuuden tila, toimintaa ohjaavien normien puuttuminen. Käsitettä on käytetty sekä yhteiskuntatieteellisessä että psykologisessa tutkimuksessa.

Lääketieteen termit:  sosiol., psyk. normittomuus | (yhteisön tai yksilön) sosiaalisten arvojen heikkous

Melinda esim. http://linda.linneanet.fi/F/GIQIIKL2Y3J361JFNPVIKJH1HKA9MRG5SYQITN8J1ER8QU1I1F-15512?func=full-set-set&set_number=008226&set_entry=000011&format=999
http://linda.linneanet.fi/F/GIQIIKL2Y3J361JFNPVIKJH1HKA9MRG5SYQITN8J1ER8QU1I1F-10867?func=full-set-set&set_number=008226&set_entry=000022&format=999

Huom. Osa viitteistä Melindassa käsittelee anomista afasiaa, jako sen osalta käsittelyssä https://github.com/Finto-ehdotus/YSE/issues/4815

**Comment by mirmaid** [comment]
Voisi olla esim. yhteiskunnalliset ominaisuudet?

**Comment by tpalonen** [comment]
PÄÄTÖS 14.11.2016:
anomia YK yhteiskunnalliset ominaisuudet
