### ISSUE TITLE
yhteiskunnalliset järjestelmät, valtiomuodot

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#795]
Onko ok että monarkia on yhteiskunnallinen objekti (via valtiomuodot) ja oligarkia yhteiskunnallinen järjestelmä?

Anarkia on nyt LT yhteiskuntaolot, mikä on kyllä oikein, mutta olisiko paremmassa seurassa yhteiskunnallisissa järjestelmissä? Vrt. myös wikipedia https://fi.wikipedia.org/wiki/Valtiomuoto, https://sv.wikipedia.org/wiki/Statsskick, https://en.wikipedia.org/wiki/State_%28polity%29#Theories_of_state_function

**Comment by mirmaid** [comment]
Ehdotus: kaikki yhteiskunnallisiin järjestelmiin

**Comment by YSO-kokous** [comment]
Valtiomuodot YK yhteiskunnalliset järjestelmät.
