### ISSUE TITLE
eläinratavalo

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#796]
YSAssa LT ilmakehän valoilmiöt (muita alakäsitteitä haloilmiöt, kangastukset, revontulet ja sateenkaaret). 

YSOssa LT valo (sähkömagneettinen säteily), jonka muut alakäsitteet ovat keinovalo ja luonnonvalo. 

Mielestäni YSAn ratkaisu on tässä parempi (vähän hassu mielikuva tulee tuosta jälkimmäisestä). Laskettu ilmakehän valoilmiöihin myös täällä: http://www.arcturusastronomy.fi/index.php?page=ilmakehaen-valoilmioet

**Comment by tpalonen** [comment]
PÄÄTÖS 14.11.2016:
eläinratavalo YK ilmakehän valoilmiöt
