### ISSUE TITLE
Yksittäiset murteet ja murteet ja kielet -monihierarkia

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#797]
Nykyisin murteiden hierarkisointi on hieman epäjohdonmukaista. Osittain yksittäiset murteet löytyvät sekä murteet-hierarkiasta että kielet-hierarkiasta, jälkimmäisessä tapauksessa sen kielen alakäsitteenä, jonka murteesta on kysymys. Pitäisi päättää linjaus, jota jatkossa noudatetaan ja jonka mukaan nykyinen hierarkia systematisoidaan. Vaihtoehdot: a) yksittäiset murteet vain murteet hierarkiaan, b) monihierarkia. 

Esimerkkejä:
länsimurteet YK murteet + YK suomen kieli
lyydiläismurteet YK karjalan kieli

**Comment by mirmaid** [comment]
Lisätään selkeille tapauksille (murre/murteet-loppuiset) tuplahierarkia. (Tuomas hoitaa)

**Comment by tpalonen** [comment]
Lisätty tuplahierarkia seuraaville:

kaakkoismurteet: itämurteet JA murteet
hämäläismurteet: länsimurteet JA murteet
lounaiset välimurteet: länsimurteet JA murteet
lounaismurteet: länsimurteet JA murteet
pohjalaismurteet (suomen kieli): länsimurteet JA murteet
eteläpohjalaismurteet: pohjalaismurteet (suomen kieli) JA murteet
keski- ja pohjoispohjalaismurteet: pohjalaismurteet (suomen kieli) JA murteet
peräpohjalaismurteet: pohjalaismurteet (suomen kieli) JA murteet
inkerinsuomi: kaakkoismurteet JA murteet
Uudenmaan murteet: suomenruotsi JA murteet
Turunmaan murteet: suomenruotsi JA murteet
sveitsinsaksa: saksan kieli JA murteet
anglonormanni: ranska JA murteet
flaamin kieli: länsigermaaniset kielet JA murteet
hazaran kieli: persia JA murteet

**Pohdittavaksi:**
Näiden suhteen ei ole konsensusta, kutsutaanko niitä kieliksi vai murteiksi. En siksi lisäisi monihierarkiaa. Mutta lisätäänkö kuitenkin RT murteet?

amerikansuomi
ruotsinsuomi
suomenruotsi
riikinruotsi
amerikanenglanti
australianenglanti
brittienglanti
intianenglanti
kanadanenglanti
kanadanranska
filipino

Alla oleville voisi samalla perusteella harkita RT murteet, mutta toisaalta se tuntuu poliittiselta kannanotolta.

galegon kieli
latgallin kieli
kveenin kieli
lyydin kieli
võrun kieli
niittymarin kieli
vuorimarin kieli
ruteenin kieli
kasubin kieli

Tein myös issuen: https://github.com/Finto-ehdotus/YSE/issues/12698

**Comment by tpalonen** [comment]
EDIT: Näiltä tuplahierarkia eli murteet-yläkäsite kuitenkin pois, koska ovat muutenkin murrehierarkiassa:

kaakkoismurteet: itämurteet JA murteet
hämäläismurteet: länsimurteet JA murteet
lounaiset välimurteet: länsimurteet JA murteet
lounaismurteet: länsimurteet JA murteet
pohjalaismurteet (suomen kieli): länsimurteet JA murteet
eteläpohjalaismurteet: pohjalaismurteet (suomen kieli) JA murteet
keski- ja pohjoispohjalaismurteet: pohjalaismurteet (suomen kieli) JA murteet
peräpohjalaismurteet: pohjalaismurteet (suomen kieli) JA murteet
inkerinsuomi: kaakkoismurteet JA murteet
