### ISSUE TITLE
kurkku ja nielu

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#798]
YSAssa

kurkku (ruumiinosat): LT ruoansulatuselimet ja hengitystiet
nielu: LT hengitystiet, ruoansulatuselimet ja purentaelimistö

YSOssa 

kurkku (ruumiinosat): LT vain ruoansulatuselimet (ei suhdetta hengitystiet-käsitteeseen)
nielu: YK vain ruoansulatuselimet (ei mitään suhdetta YSAn muihin laajempiin)

MeSH

kurkku: KÄ nielu, LT hengityselimet, mahasuolikanava ja purentaelimistö
kurkunpää: LT hengityselimet

Lääketieteen termit

kurkku: nielu, kurkunpää tai molemmat
nielu: lihasten ja limakalvojen verhoama ontelo nenäontelon, suuontelon ja kurkunpään takana (ruuansulatuskanavan ja hengitysteiden yhteinen osa)
kurkunpää: kaulan etuosassa sijaitseva, henkitorven yläosaan liittyvä rustoinen elin, jonka avulla ihminen voi mm. pysäyttää hengitysilman kulun ja tuottaa ääniä

**Comment by mirmaid** [comment]
Ehdotus: lisätään kummallekin LT hengityselimet, RT hengitystiet, nielulle lisäksi RT purentaelimistö.

**Comment by tpalonen** [comment]
PÄÄTÖS 14.11.2016:
- lisätään nykyisen yläkäsitteen lisäksi kurkulle ja nielulle YK hengityselimet, AK hengitystiet, nielulle lisäksi AK purentaelimistö

(YK = yläkäsite, AK = assositiivinen käsite)
