### ISSUE TITLE
tutkimus ja tutkimustoiminta

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#799]
Kannattaisiko näille kaikille lisätä ysa-ryhmä 56 Tiede. Tutkimus? Nyt sitä on käytetty lähinnä niin että jos termi ei liity johonkin tiettyyn alaan, se saa tuon 56 ryhmän, muuten alanmukaisen ryhmän (esim. huippututkimus & empiirinen tutkimus 56, kuluttajatutkimus 75, empiirinen oikeustutkimus 69). Toisinaan on laitettu molemmat (vedenalainen tutkimus 13, 56).

**Comment by YSO-kokous** [comment]
Ryhmä 56 sai kannatusta.

**Comment by YSO-kokous** [comment]
Ks. myös https://github.com/NatLibFi/Finto-data/issues/81
