### ISSUE TITLE
muut paikat ja alakäsitteet

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#800]
Ehdotan että "muut paikat" poistetaan ja alakäsitteet sijoitetaan paremmin. Alakäsitteet nyt: 

    fiktiiviset paikat
    helvetti
    henkimaailma
    Jumalan valtakunta
    kiirastuli
    paratiisi
    taivas
    tuonela
    Villi länsi

Suurin osa siis "uskonnollisia käsityksiä" (joita ei välttämättä aina mielletä "paikoiksi" vaan myös esim. "tiloiksi"). Täytynee ratkaista sen jälkeen kun on päätetty mihin "uskonnolliset tuotokset" viittaa (konkreettinen esim. katekismukset, Qumranin kirjoitukset VS. abstraktinen "uskonnollisen ajatuksen tuotos" esim. armo, karma, kuolemanjälkeinen elämä..) Kuolemanjälkeinen elämä voisi mahdollisesti olla yläkäsite helvetille, kiirastulelle, paratiisille, taivaalle ja tuonelalle (riippuen mielletäänkö nämä enemmän paikoiksi vai tiloiksi).

Villi Länsi voisi mahdollisesti olla LT ihmisen määrittämät paikat (ilman ihmistoimintaa se olisi vain yksinkertaisesi maantieteellinen alue jne.)

Fiktiiviset paikat suoraan paikkojen alle? Vai onko oikeastaan niin että tämä pitäisi käsitellä niinkuin sisällönkuvailussa tehdään, eli lähteä siitä että fiktiivinen paikka on paikka siinä missä muutkin, "lisäyksenä" vain ettei ole olemassa reaalimaailmassa? Siinä tapauksessa tämä voisi periaatteessa olla yhtä hyvin ihmisen määrittämien paikkojen alla kuin luonnon muodostamien alla...

**Comment by YSO-kokous** [comment]
PÄÄTÖKSET:

fiktiiviset paikat: paikka
helvetti: uskonnolliset tuotokset
henkimaailma: uskonnolliset tuotokset
Jumalan valtakunta: uskonnolliset tuotokset
kiirastuli: uskonnolliset tuotokset
paratiisi: uskonnolliset tuotokset
taivas: uskonnolliset tuotokset
tuonela: uskonnolliset tuotokset
Villi länsi: ihmisen määrittämät alueet
