### ISSUE TITLE
juhlapäivät, vuotuisjuhlat

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#801]
YSAssa otsikon termeillä on RT-suhde. YSOssa vuotuisjuhlat on juhlapäivät-käsitteen yläkäsite. 

Kielitoimiston sanakirja: Vuotuisjuhla tarkoittaa vuosittain toistuvaa juhlaa. 

KULO: Tarkoittaa vuosittain vietettäviä kansallisia ja kansainvälisiä merkkipäiviä ja kirkollisia juhlapäiviä

https://fi.wikipedia.org/wiki/Juhlap%C3%A4iv%C3%A4

**Comment by mirmaid** [comment]
Näillä vuotuisjuhlat YSAssa LT:nä, lihavoiduilla myös YSOssa yläkäsitteenä:
    **adventti
    aprillipäivä
    halloween**
    helatorstai
    **helkajuhla**
    helluntai
    isänpäivä
    **joulu**
    **juhannus**
    Kalevalan päivä
    karkauspäivä
    **kekri
    kynttilänpäivä
    laskiainen**
    loppiainen
    Lucian päivä
    **praasniekat**
    pyhäinpäivä
    **pääsiäinen**
    svenska dagen
    unikeonpäivä
    **uusivuosi
    vappu**
    **venetsialaiset (juhlat)
    viattomien lasten päivä
    ystävänpäivä**
    äitienpäivä

**Comment by mirmaid** [comment]
YSOssa YK juhlapäivät, lihavoiduilla myös YSAssa sama LT:
    helatorstai
    helluntai
    isänpäivä
    **itsenäisyyspäivät**
    Kalevalan päivä
    kansainvälinen naistenpäivä (ei LT:tä YSAssa)
    **kansallinen veteraanipäivä**
    **kansallispäivät**
    loppiainen
    Lucian päivä
    pyhäinpäivä
    svenska dagen
    unikeonpäivä
    äitienpäivä

**Comment by mirmaid** [comment]
Yleensä käytetty vuotuisjuhlista, toisinaan myös merkkipäivistä (esim. Malja nuoruudelle: sanoja nuoren juhlaan). YSAssa/YSOssa on myös merkkipäivät.

**Comment by tpalonen** [comment]
EHDOTUS:
- vuotuisjuhlat YK juhlat + RT juhlapäivät
- juhlapäivät YK juhlat + RT vuotuisjuhlat
- Juhlapäivien alakäsitteet siirretään vuotuisjuhlien alle.

**Comment by mariaforsen** [comment]
Ruotsin kannalta tämä termistö on ongelmallinen, YSOssa on nimittäin juhlat=fester ja juhlapäivät=högtider. Tämä on osittain "virheellinen yksinkertaistus", tämän taustalla eri käsitteenmuodostus.. 

Kielitoimiston sanakirja:
juhla: 1. jnk kunniaksi t. muistoksi vietettävä päivä t. pitempi aika, juhla-, merkkipäivä. 
2. jnk kunniaksi t. muistoksi tm. syystä järjestettävä arvokashenkinen tm. arkisesta poikkeava yleisö- t. yksityistilaisuus, juhlatilaisuus; myös kokoontumisesta yhteen seurustelun, hauskanpidon tms. takia, kekkerit, "bileet". 
3. määräaiheeseen keskittyvä, us. monipäiväinen tapahtuma, päivät; vrt. festivaali. 

Eli suomeksi juhlat on monikäyttöinen termi, mutta ruotsin kannalta "högtider" ja "fester" olisi molemmat tärkeitä erillisinä termeinä (ehkä sen takia juhlapäivien vastineena on "högtider", vrt https://sv.wikipedia.org/wiki/Helgdag )

**Comment by mirmaid** [comment]
Päätös:
siirretään juhlapäivät YK juhlat RT vuotuisjuhlat
kaikki alakäsitteet YK vuotuisjuhlat

YSE-issue kielivastaavuudesta juhlapäivät/högtider.
