### ISSUE TITLE
kirjallisuus X:n mukaan vs kaunokirjallisuuden alakäsitteet

### ISSUE THREAD

**Issue by MikkoAleksanteri** [NatLibFi/Finto-data#802]
YSO-kokouksen (16.11.2016) huomio:

Nyt kaunokirjallisuuden http://finto.fi/yso/fi/page/p4 alla esim. nais- ja mieskirjallisuus jotka voisivat ehkä olla myös kirjallisuus X:n mukaan alla.

**Comment by mariaforsen** [comment]
Ainoa mahdollinen olisi siinä tapauksessa varmaan kirjallisuus sisällön mukaan (koska nämä on rajattu kaunokirjallisuuteen).

**Comment by YSO-kokous** [comment]
Esim. mieskirjallisuus ja naiskirjallisuus -käsitteillä yläkäsite on jo kaunokirjallisuus eli ei voida lisätä yläkäsitteeksi kirjallisuus X:n mukaan, koska ovat samassa hierarkiapolussa.
