### ISSUE TITLE
marjat

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#805]
Marjat-käsitteen alakäsitteet olisi syytä käydä läpi. Mustikka- ja puolukka-käsitteet ovat nykyisin YSAssa saaneet merkityksen lajina. Näin ollen marjat on väärä yläkäsite, koska se tarkoittaisi sitä, että mustikkalaji on kasvinosa. Kaikki ne marjat, joita tämä ongelma koskee, olisi siis paras siirtää lajihierarkiaan.

ahomansikka
herukat
jalomaarain
juolukka
karpalo
karviainen
lakka (marjat)
luonnonmarjat
mansikka
mesimarja
mustikka
pensasmustikka
pihlajanmarja
puolukka
ruusunmarja
tyrni
vadelma

**Comment by mirmaid** [comment]
Näiden käsitteiden (hedelmät ja marjat) alakäsitteinä on kasvilajeja, mutta LT kasvinosat ei silloin ole oikea. Toisaalta olisi ongelmallista poistaa osa hedelmistä ja marjoista ja siirtää ne kasvilajien taksonomiaan, jos osa kuitenkin jää alakäsitteiksi.

Samaan tapaan ongelmallisia ovat esim. puulajit, kun sama termi viittää myös materiaaliin.

**Comment by mirmaid** [comment]
lajeja: ahomansikka, juolukka, karpalo (virallisesti isokarpalo), karviainen, lakka (virallisesti muurain), mesimarja, mustikka, pensasmustikka (laji.fi ei tunne, mutta wikipedian mukaan laji), puolukka (laji), tyrni, vadelma
sukuja: herukat

jalomaarain = mesimarjan ja alaskanmesimarjan risteytys (voiko olla LT mesimarja, koska on kahden alalajin risteytys?)
mansikka = suku, tai puutarhamansikka (ST ahomansikka) - korjattava
pihlajanmarja, ruusunmarja LT marjat, muut RT marjat

**Comment by mirmaid** [comment]
**hedelmät**
lajeja: ananas, aprikoosi, avokado, banaani (suku banaanit), karambola, luumu, mango (wikipediassa on erikseen mango eli mangopuu ja mango (hedelmä)), meloni (uskokaa tai älkää), papaija, persikka, päärynä (suku päärynät), taateli (välimerentaateli, suku taatelit), viikuna (aitoviikuna, suku viikunat), greippi, limetti, mandariini, sitruuna

kriikuna = alalaji, LT luumu

kiivi = kiiviköynnöksen hedelmä (voinee myös tulkita lajiksi, ks. Kassu)
kirsikka = kirsikkapuun hedelmä, kirsikat = Cerasus = alasuku (kirsikkapuut) (voisi varmaan monikossa sijoittaa lajihierarkiaan, wikipedia on tässä käytännöllisempi kuin Kassu, jossa kirsikat = Prunus, tähän kuuluvat myös mm. tuomet, mantelit ja luumut)
omena = omenapuun hedelmä, omenapuut = suku (on YSOssa)
viinirypäle = viiniköynnösten hedelmä
appelsiini = appelsiinipuun hedelmä, voisi myös tulkita = appelsiinipuu (Citrus sinensis)

**Comment by mirmaid** [comment]
Tunnettuja ruokana käytettäviä marjoja ovat esimerkiksi banaani, sitrushedelmät, passiohedelmä, papaija, munakoiso, kurkku, tomaatti, paprika ja kurpitsa.

Yleiskielessä marjalla on eri merkitys kuin kasvitieteessä. Yleiskielessä marja tarkoittaa pientä, mehevää ja pyöreähköä hedelmää. Näistä kasvitieteellisesti eivät ole marjoja esimerkiksi mansikka ja vadelma.
https://fi.wikipedia.org/wiki/Marja_(kasvitiede)

Kummalla mennään?

**Comment by mirmaid** [comment]
Kasvitieteellisesti omena on epähedelmä...

**Comment by YSO-kokous** [comment]
Tehdään seuraavat muutokset:

Siirretään kasvilaji-hierarkiaan seuraavat ja lisätään RT marjat:
ahomansikka, juolukka, karpalo (virallisesti isokarpalo), karviainen, lakka (virallisesti muurain), mesimarja, mustikka, pensasmustikka (laji.fi ei tunne, mutta wikipedian mukaan laji), puolukka (laji), tyrni, vadelma, herukat, jalomaarain, mansikka [huom! tarkistettava mansikan ja ahomansikan suhde]

Säilytetään marjat-hierarkiassa seuraavat:
pihlajanmarja, ruusunmarja

**Comment by YSO-kokous** [comment]
Toteutetaan hedelmien osalta seuraavat muutokset:

Seuraavat siirretään kasvit-hierarkiaan ja lisätään RT hedelmät:

ananas, aprikoosi, avokado, banaani (suku banaanit), karambola, luumu, mango (wikipediassa on erikseen mango eli mangopuu ja mango (hedelmä)), meloni (uskokaa tai älkää) (vesimeloni on sitten taas ihan oma juttunsa), papaija, persikka, päärynä (suku päärynät), taateli (välimerentaateli, suku taatelit), viikuna (aitoviikuna, suku viikunat), greippi, limetti, mandariini, sitruuna, kiivi, appelsiini

HUOM! kriikuna LT luumu

Säilytetään hedelmät-hierarkiassa seuraavat:
viinirypäle, omena

Muutetaan "kirsikka" muotoon "kirsikat" eli tulkitaan Cerasus-alasuvuksi.

**Comment by mirmaid** [comment]
Hedelmät-hierarkiaan jäivät nyt oliivi, omena, sitrushedelmät ilman alakäsitteitä, taateli ja viinirypäle. Sanastossa oli myös lajiin viittaavat oliivipuu ja taatelipalmu, joten oli pakko tulkita oliivi ja taateli pelkiksi hedelmiksi.

**Comment by tpalonen** [comment]
Mietin tätä vielä. Tässähän on taustalla se, että marjat viittaa kahteen eri käsitteeseen: kansankielessä se viittaa mehevään, pienikokoiseen ja syötävään kasvinosaan. Biologiassa

**Comment by tpalonen** [comment]
Marjat-hierarkian osalta toteutettu. Marjat-käsitteen alakäsitteiksi jäivät luonnonmarjat, pihlajanmarja ja ruusunmarja.

**Comment by YSO-kokous** [comment]
Marjat YK hedelmät on ok
kirsikan monikkomuodosta on tehty YSE-ehdotus

**Comment by tpalonen** [comment]
Meloni siirretty YK kurkkukasvit (yso:p1242).
