### ISSUE TITLE
hoitolaitokset, huoltolaitokset

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#806]
Miten nämä tarkalleen eroavat (että voitaisiin luoda ruotsiksi sulkutarkenteita) ? Ks. käyttö Melindassa. Ryhminä ensimmäisellä 48 ja 73, toisella 73. Vrt. alakäsitteet. Ruotsiksi vastineet vårdinrättningar, vårdanstalter, eli ovat synonymisia (vaatii ruotsin osalta toimenpiteitä, mutta niitä ei voi tehdä ennen kuin merkitysten rajat ovat selvät). Käytetäänkö huoltolaitokset todella vain sellaisista missä asutaan? Toisaalta on myös hoitolaitosten alla sellaisia missä myös voidaan asua.

**Comment by mirmaid** [comment]
Lääketiede 2.0: hoitolaitos: sairaala tai muu hoitoa antava laitos

Melindan perusteella voisi minusta tehdä huoltolaitokset KÄ hoitolaitokset - hoitolaitoksella viitataan kyllä usein mukavampiin paikkoihin (esim. fysikaaliset hoitolaitokset, kylpylät) kuin ne joita on listattu huoltolaitokset-termin alakäsitteiksi. Lähinnä kuitenkin ongelmallisia ovat ehkä ne tapaukset joissa kyse on "pakkolaitoksista", esim. Goffman: _Minuuden riistäjät: tutkielma totaalisista laitoksista_, Bessant etc. _Violations of trust: how social and welfare institutions fail children and young people_ tai Frangeur: _Pojkar, pli och pedagogik: vanart och manligheter på Bonaanstalten 1905-194_.

**Comment by YSO-kokous** [comment]
PÄÄTÖS

- tehdään YSE-ehdotus: huoltolaitokset KÄ hoitolaitokset
