### ISSUE TITLE
laitoshoito, laitoshuolto

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#807]
MOT: 
1. vars. pitkäaikainen huolenpito jksta sosiaali- tms. laitoksessa.
2. laitoksissa tehtävä siivous- ja kunnossapitotyö. 

Ks. Melinda ja termin suhteet. YSOon lisätty huomautus joka ei taida päteä YSAn puolella (esim. RT siivous) eikä Melindassa. Ruotsiksi vastineet ovat synonymisia (eikä ollenkaan ykkösmerkitys)

Vaatii siis varmasti toimenpiteitä ja uusia käännöksiä.

**Comment by mirmaid** [comment]
Lääketiede 2.0: laitoshoito: ympärivuorokautinen jatkuva hoito sairaalassa tai muussa hoitolaitoksessa; vrt. avohoito

Kaikkien ihmisten huoltoa tarkoittavien korvaaminen laitoshoito-termillä voi olla hankalampaa kuin vastaava huoltolaitokset/hoitolaitokset -yhdistäminen? Esim. Autero: _Laitosnuoren tarina_ - voiko puhua laitoshoidosta huostaanotettujen nuorten kohdalla? Suomeksi hoito sopii kun kyse on potilaista tai vanhuksista, mutta terveiden nuorten kohdalla se tuntuu vähän ongelmalliselta. 

2. merkitys voisi olla suomeksi **laitoshuolto (kunnossapito)** - tähän ehkä voidaan sisällyttää myös ruokahuolto, mutta se on myös omana terminään. Mutta onko tälle merkitykselle ruotsiksi mitään termiä?

**Comment by YSO-kokous** [comment]
PÄÄTÖS

- rajataan merkitykset siten, että laitoshoito viittaa kaikkien mahdollisten hoitoa tarvitsevien hoitoon ja laitoshuolto laitoksen kunnossapitoon, siivoamiseen tms.
- tehdään YSE-ehdotus: muutetaan laitoshuollon preflabeliksi "laitoshuolto (kunnossapito)".
- poistetaan YSOsta laitoshuollon huomautus. korvataan se tällä: "Laitoksissa tehtävä siivous- ja kunnossapitotyö."

**Comment by mirmaid** [comment]
Laitoshuolto muutettu ohjaustermiksi laitoshoidolle laitoshoidolle.

**Comment by YSO-kokous** [comment]
Tehty samoin myös YSOssa.
