### ISSUE TITLE
Huomautukset, joissa esiintyy "käytä", "käytetään" tai "käyttää"

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#809]
Tein SPARQLen käsitteistä, joiden huomautuksessa esiintyy joko "käytä", "käytetään" tai "käyttää". Ovatko tällaiset huomautukset optimaalisia? Esim. notaatio: "Musiikin yhteydessä käytä nuottikirjoitus." Tällaiset huomautukset tuntuvat palvelevan vain ammattisisällönkuvailijoita. Eikö olisi parempi, että huomautukset olisivat selkokielisiä ja selventäisivät tavallisille käyttäjälle käsitteen tarkan merkityksen?

Tässä linkki taulukkoon, jossa kaikki YSO-käsitteet, joissa tällainen huomautus:
https://docs.google.com/spreadsheets/d/1T1b5WO4A1V4uQfUIVIR-F8L9ofCbxNOfRD2e4zJtmXI/edit?usp=sharing

Huom! Osa taulukon huomautuksista ei liity tähän problematiikkaan, vaan niissä esiintyy sattumalta jokin edellä mainituista sanoista.

**Comment by tpalonen** [comment]
Siivosin taulukosta pois epäolennaiset käsitteet.

**Comment by MikkoAleksanteri** [comment]
YSO-kokous:

Tuomas työstää itsenäisesti.

**Comment by YSO-kokous** [comment]
Päätettiin, että selvästi käyttöhuomautus-tyyppiset huomautukset poistetaan skos:note-kentästä ja siirretään skos:scopeNote-kenttään. Tarpeen vaatiessa huomautusta on syytä muokata ontologiakontekstiin sopivammaksi (esim. "käytetään termiä X" muotoon "käytetään käsitettä X") ja YSOn yleisiä huomautuskentän muotoa koskevia linjauksia vastaavaksi. Mikäli käyttöhuomautuksessa esiintyy viittaus toiseen käsitteeseen, korvataan huomautuksessa käsitteen termi käsitteen urilla, joka on hakasulkeiden sisällä. Esim. "Barokin ja klassismin ajan musiikissa soittimistoltaan vapaavalintainen bassosäestys. Vastaavasta säestysperiaatteesta käytetään termiä kenraalibasso." muutetaan muotoon "Barokin ja klassismin ajan musiikissa soittimistoltaan vapaavalintainen bassosäestys. Vastaavasta säestysperiaatteesta käytetään käsitettä [http://www.yso.fi/onto/yso/p9311]."

**Comment by tpalonen** [comment]
Tein tarvittavat muokkaukset ja siirrot skos:scopenote-kenttään edellä esitetyin speksein. Tällainen tuli läpikäydessä vastaan.

**stabilointi**
00 ryhmä
Huomautus:"Stabilointi-termiä käytetään kemian alalla."

Jos käsitettä käytetään vain kemian alalla, pitäisikö ryhmä 00 poistaa ja vaihtaa tilalle 09?

**Comment by YSO-kokous** [comment]
@mirmaid tutkii stabilointi-asiaa. @mariaforsen toteuttaa huomautusten muokkauksen ruotsin osalta.

**Comment by mariaforsen** [comment]
Onko kuitenkin osa huomautuksista tarkoituksella jätetty ilman suoraa linkkiä? Esim. lääkintävoimistelijat, käsi- ja taideteollisuusoppilatokset, kuvataide, kuntayhtymät... ovat edelleen vanhassa muodossa ja ilman linkitystä.

**Comment by mariaforsen** [comment]
Ruotsiksi muutettu huomautusten muotoilua ja lisätty "linkityksiä" huomautuksiin, tyyliin:
-"Används endast i historiska sammanhang. I övriga fall används begreppet x."
-"Begreppet används fr.o.m. xxxx, tidigare användes begreppet x."
-"Begreppet användes fram till xxxx, därefter används begreppet x."

**Comment by YSO-kokous** [comment]
PÄÄTÖS
- aina kun huomautuskentässä (note, definition, scopenote) mainitaan jokin toinen YSOn käsite, muutetaan tämä linkiksi. @jarmosaarikko huomioi tämän ja koostaa vastaavat linjauskysymykset (lähteen ilmaisu jne) käsiteltäväksi YSO-kokousta varten. Tavoitteena saada kaikki olennaiset asiat kirjattua YSO-kehityslinjauksiin.
- @mariaforsen  tekee "används"-SPARQL:n ja muuttaa tarvittavat käsitteet edellä määritellyn linjauksen mukaisesti. Linkki huomautukseen ym.
- @satuniininen  tekee vastaavan englannin SPARQL:n ja tarvittavat muutokset.

**Comment by satuniininen** [comment]
Lisäsin Tuomaksen SPARQLeen muodon "käytetty"

**Comment by satuniininen** [comment]
Englanti tehty.

**Comment by mariaforsen** [comment]
Selvennykseksi vielä: tämä on toteutettu myös ruotsin osalta.

**Comment by mariaforsen** [comment]
Täytynee muistaa tämä myös jatkossa kun käsitellään uusia ja muuttuneita (jotka tulevat YSA/Allärsista), niin että muokataan huomautusta YSOn puolella linjausten mukaisiksi (eli lisätään käsitelinkkejä jne.) Tätä ei näköjään aina ole muistettu, eli viimeistään ennen siirtymistä kannattaa varmaan tehdä SPARQL-kyselyn uudestaan.

**Comment by YSO-kokous** [comment]
Uudet vastaavat listaukset olisi hyvä tehdä esim. vuoden 2021 loppupuolella.

**Comment by mirmaid** [comment]
Jarmo päivittää kyselyä, Mirja ja Maria käyvät läpi tulokset.

**Comment by jarmosaarikko** [comment]
Seuraava haku listaa notet joissa tietty termi, mutta poistaa sellaiset, joissa on "[" hakasulku (eli inkki).  
Filter-lausetta vaihtamalla voi poimia suomen- tai ruotsinkieliset notet.
```
SELECT *
WHERE {
{
    ?s skos:note ?l .
   FILTER(regex(lcase(?l), "käytössä|käytetty|käytetään|käytä|används|användes"))
   FILTER  ( !contains(lcase(?l), "[") ) .
  FILTER(LANGMATCHES(LANG(?l), "fi"))
#  FILTER(LANGMATCHES(LANG(?l), "sv"))
}
}

```

**Comment by mirmaid** [comment]
Tehty suomeksi.

**Comment by mariaforsen** [comment]
Tehty myös ruotsiksi.
