### ISSUE TITLE
menetelmät, analyysit, tutkimus jne

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#81]
_From [SNyk...@gmail.com](https://code.google.com/u/112439428317292360191/) on January 20, 2014 16:46:59_
1. What is to be changed/Mitä muutetaan "menetelmät"
   "analyysit"
   "analyysimenetelmät"
   "tutkimusmenetelmät"
   "tutkimus"
   "tekniikka (menetelmät)"
   "tieteet (erikoisala)" 2. Why the change is needed/Miksi muutetaan sekava joukko, ei selkeitä rajanvetoja käsitteiden välillä

Tausta:

YSO-päivitysmuistiinpanot 3.10.2013: menetelmät, analyysit, tutkimusmenetelmät, tutkimus ym käytävä läpi kokonaisuudessaan, esim. tutkimuksen alla paljon käsitteitä jotka voisivat olla tutkimusmentelmien alla, tarvittaisiin määritelmät

kehysanalyysi sijoitettiin "tutkimusmentelmiin" vaikka samankaltaisia "tutkimuksen" alla, päätös tehtiin koska tuleivaisuudessa siirretään tutkimuksen alakäsitteitä tutkimusmenetelmiin

Katrin kommentit (17.10.2013): nämä pitäisi käydä seikkaperäisesti läpi
Keskeneräisiä muistiinpanoja:
tutkimustoiminnan alla suoraan kaikenlaista tutkimusta,mm.kirjallisuuden tutkimus, markkinatutkimus, miestutkimus
tutkimuksen alla taas kaksostutkimus, käyttäjätutkimus, psykometriikka, survey-tutkimus jne.
analyysi on kognitiota (mentaalinen toiminta)
tutkimus on tutkimustoimintaa (tiedollinen luonti)
tieteet on erikoisala (ilmiöt)
menetelmät ovat henkisiä tuotoksia (oliot)

Keskeisin ongelma:
Menetelmät ovat olioita. Kaikki muut ovat sentään nykyisin tapahtumat ja toiminta -hierarkiassa, vaikka ovatkin vähän eri mestoissa.

Tahtotila:
tutkimus ja tutkimusmenetelmät samaan päähierarkiaan?
analyysi ja analyysimenetelmät samaan päähierarkiaan?

Toteutusehdotukset:
1. voitaisiinko menetelmät siirtää toimintaan tai ilmiöihin? tekisi monihierarkian mahdolliseksi

1a) menetelmät yhteiskunnallisiin ilmiöihin

1b) tutkimuksenmenetelmät tutkimuksen alle, analyysimenetelmät analyysin alle
1. tutkimustoiminnan voisi siirtää tutkimuksen alle?

nyt se luo yhden turhahkon lenkin hierarkiaketjuun

2.1. ehkä näin syntyvät tutkimustoiminta & tutkimus -mashuppiin
voisi lisätä groupconcepteja? (kohteen mukaan, tutkimustavan mukaan jne) 3. Realized changes/Toteutetut muutokset

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=78_

**Comment by tpalonen** [comment]
TAVOITETILA:
- menetelmien, analyysin ja tutkimuksen alakäsitteet ovat saman luonteisia ja niiden olisi hyvä olla samalla puolella hierarkiaa.
- tutkimus ja tutkimustoiminta alakäsitteet pitäisi jakaa järkevämmin. esim. tutkimus tutkimuskohteen mukaan tyyppisellä ryhmittelyllä

**Comment by mirmaid** [comment]
Analyysimenetelmät-käsitteen alla nyt samanlaisia kuin analyysi x:n mukaan ryhmissä.

**Comment by tpalonen** [comment]
tutkimustoiminta nyt siirretty LT kohdistuva toiminta. Sillä ei ole enää alakäsitteitä. tutkimus-käsitteelle on luotu kaksi ryhmittelevää alakäsitettä: "tutkimus kohteen mukaan" (alakäsitteinä mm. SETI-tutkimus, aivotutkimus, geenitutkimus jne) ja "tutkimus menetelmän mukaan" (alakäsitteinä mm. arviointitutkimus, empiirinen tutkimus, kenttätutkimus jne).

Todettiin, että monet "tutkimus kohteen mukaan" alla olevista voisi siirtää myös "tieteet (erikoisalat)"-käsitteen alle, esim. informaatiotutkimus, musiikintutkimus. @tpalonen käy läpi tämän kokonaisuuden ja tekee ehdotuksen siirrettävistä. Ongelma tuli esiin, kun todettiin, että musiikkiarkeologia käsitteellä on periaatteessa kielletty monihierarkia (arkeologia + musiikintutkimus), koska arkeologia on tiede ja musiikintutkimus on toimintaa.

**Comment by YSO-kokous** [comment]
tutkimustoiminta nyt siirretty LT kohdistuva toiminta. Sillä ei ole enää alakäsitteitä. tutkimus-käsitteelle on luotu kaksi ryhmittelevää alakäsitettä: "tutkimus kohteen mukaan" (alakäsitteinä mm. SETI-tutkimus, aivotutkimus, geenitutkimus jne) ja "tutkimus menetelmän mukaan" (alakäsitteinä mm. arviointitutkimus, empiirinen tutkimus, kenttätutkimus jne).

Todettiin, että monet "tutkimus kohteen mukaan" alla olevista voisi siirtää myös "tieteet (erikoisalat)"-käsitteen alle, esim. informaatiotutkimus, musiikintutkimus. @tpalonen käy läpi tämän kokonaisuuden ja tekee ehdotuksen siirrettävistä. Ongelma tuli esiin, kun todettiin, että musiikkiarkeologia käsitteellä on periaatteessa kielletty monihierarkia (arkeologia + musiikintutkimus), koska arkeologia on tiede ja musiikintutkimus on toimintaa.

**Comment by mirmaid** [comment]
Aloitetaan tämän issuen purkaminen tästä:

Todettiin, että monet "tutkimus kohteen mukaan" alla olevista voisi siirtää myös "tieteet (erikoisalat)"-käsitteen alle, esim. informaatiotutkimus, musiikintutkimus. @tpalonen käy läpi tämän kokonaisuuden ja tekee ehdotuksen siirrettävistä. Ongelma tuli esiin, kun todettiin, että musiikkiarkeologia käsitteellä on periaatteessa kielletty monihierarkia (arkeologia + musiikintutkimus), koska arkeologia on tiede ja musiikintutkimus on toimintaa.

**Comment by tpalonen** [comment]
Tutkimus kohteen mukaan -hierarkian läpikäynti. Alakäsitteet ratkaisuineen.

aivotutkimus
alhaisen lämpötilan tutkimus
aluetutkimus
antiikintutkimus
arktinen tutkimus
avaruustutkimus
diskurssintutkimus
elokuvatutkimus
elämäkertatutkimus
enologia
esinetutkimus
esitystutkimus
geenitutkimus
genealogia
genretutkimus
historiantutkimus
informaatiotutkimus
kaupunkitutkimus
kehittävä työntutkimus
kehitystutkimus
kielentutkimus
kirjallisuudentutkimus
korkean lämpötilan tutkimus
korpustutkimus
kotiseutututkimus
kulttuurienvälinen tutkimus
kulttuurintutkimus
kulutustutkimus
kuntotutkimus
kuntoutustutkimus
kylätutkimus
käsialantutkimus
lapsitutkimus
lukemistutkimus
luolatutkimus
luonnontutkimus
maisemantutkimus
markkinatutkimus
markkinointitutkimus
materiaalitutkimus
matkailututkimus
mediatutkimus
merentutkimus
metsäntutkimus
mielentilatutkimus
miestutkimus
mikroskopia
musiikintutkimus
myyttitutkimus
naistutkimus
nimistöntutkimus
nuorisotutkimus
organisaatiotutkimus
pelitutkimus
perhetutkimus
poikatutkimus
politiikantutkimus
rauhantutkimus
SETI-tutkimus
sosiaalitutkimus
sukupuolentutkimus
sukututkimus
taiteellinen tutkimus
taiteentutkimus
tekstintutkimus
terveystutkimus
tiedotustutkimus
tieteentutkimus
tulevaisuudentutkimus
tyttötutkimus
työntutkimus
unitutkimus
vammaistutkimus
viestintätutkimus
väestötutkimus
ympäristötutkimus
yritystutkimus

**Comment by mirmaid** [comment]
Sprintti 10.4.
- tutkitaan erikseen vielä naistutkimus/miestutkimus/poikatutkimus/tyttötutkimus - voiko nämä käsitellä sukupuolentutkimuksen alakäsitteinä?

**Comment by mirmaid** [comment]
Jatko: tutkimus menetelmän mukaan - onko alakäsitteissä sellaisia, joissa ei oikeasti ole kysymys menetelmästä (seulontatutkimus, perustutkimus, tilaustutkimus mainittu)

**Comment by tpalonen** [comment]
Tein yllä listaamani muutosehdotukset. Ennen sulkemista tähän issueen voisi merkitä jonkin "MUTU-2024"-tyyppisen tägin erikoisontologioiden ylläpitäjiä varten. Asiasta keskusteltaneen OY-kokouksessa. ping: @mirmaid

**Comment by mirmaid** [comment]
^ Tässä oli vielä avoimia kysymyksiä edellä, miten jatketaan?

**Comment by mirmaid** [comment]
Ratkaistaan tässä issuessa vielä

- 10.4. avoimeksi jääneet kysymykset
- mahd. tutkimus kohteen mukaan vs. tutkimus menetelmän mukaan -jakoon liittyvät kysymykset (muistitietotutkimus nyt sovitusti molemmissa, onko muita vastaavia?)
- onko tutkimusmenetelmät-käsitteellä alakäsitteitä, jotka sopisivat paremmin muualle (voivat olla toimintaa tms.)

**Comment by mariaforsen** [comment]
Sukupuolentutkimuksesta: naistutkimus/miestutkimus/poikatutkimus/tyttötutkimus ovat kai sukupuolentutkimuksen tutkimusalueita? https://yle.fi/a/7-903404 
https://yle.fi/a/7-1279335 Tai oikeastaan naistutkimus on kyllä myös sukupuolentutkimuksen aikaisempi nimitys...

**Comment by mirmaid** [comment]
Naistutkimus jne. YK sukupuolentutkimus

**Comment by mirmaid** [comment]
Käydään tutkimusmenetelmät-käsitteen alakäsitteet läpi samalla kuin muutkin menetelmät, osa alakäsitteistä jo siirtymässä lääketieteellisiin toimenpiteisiin.
