### ISSUE TITLE
Käsityö (p5559) on muuttunut merkitykseltään

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#810]
TSK:lta saatu palaute.

"MAO-päivityksessä ilmeni, että vanhan YSOn 'käsityö' (p5559, joka löytyy Finton MAO/TAOsta ) on nyky-YSOssa muuttunut eri käsitteeksi (= käsityö (toiminta), p5559). Koska käsite on muuttunut, p5559 pitäisi deprekoida ja käsityö (toiminta) - käsitteelle pitäisi antaa uusi URI."

@kseppala

**Comment by mirmaid** [comment]
Asiasanaa käsityö on aikaisemminkin käytetty laajemmin kuin vain oppiaineesta. YSAssa ja YSOssa on paljon käsitteitä joita voi käyttää oppiaineesta ja ko. tiedon tai taidon alasta, eikä kaikkia ole koottu termin oppiaineet alle (vrt. esim. matematiikka). Käsite ei siis ole muuttunut, vaan sen merkitys on aikaisemminkin ollut laajempi. Sitä voi edelleen käyttää myös oppiaineesta. (@kseppala)

**Comment by kseppala** [comment]
MAOssa syntynyt ongelma johtuu siitä, että YSOssa on aiemmin ollut käsite käsityö (oppiaineet), joka on merkitty ekvivalentiksi MAOn käsityö (oppiaineet) kanssa. Kun YSOsta on poistettu käsityö (oppiaineet) erillisenä käsitteenä, sen URI p5559 on annettu käsitteelle käsityö (toiminta). Tällöin käsitteen merkitys on YSOn näkökulmasta muuttunut. Ei ole käsitettä, joka olisi yhtä aikaa oppiaine ja toimintaa, vaan kyse on jommasta kummasta, vaikka käsitteisiin viitattaisiin samalla termillä. Muutoksesta seuraa, että ekvivalentin käsitteen MAO-alakäsitteet tulevat YSOn käsityö (toiminta) -käsitteen alakäsitteiksi, mikä ei ole oikein, sillä esim. tekstiilityö ja tekninen työ halutaan esittää nimenomaan oppiaineina. Nyt kun YSOssakin on oppiaineet/taitoaineet-hierarkia, MAOn käsitteet kuuluvat sinne ja YSOssakin ratkaisu on epätasapainossa, koska ainoastaan kotitalous on taitoaineiden alakäsitteenä, mutta käsityöaineet toiminta-hierarkiassa. Erikoisontologian kehityksessä pitää huomata, että ekvivalenssi on poistettava käsityö (oppiaineet) ja käsityö (toiminta) väliltä ja alakäsitteet siirrettävä oikeaan hierarkiaan. Tällaisia muutoksia ei voi havaita SPARQL-tarkistuksilla ja esim. KOKO koostuu väärin, ellei käsitemuutoksia tuoda näkyviin URI-muutoksina.

**Comment by mirmaid** [comment]
Tekninen työ ja tekstiilityö ovat YSOssa alakäsitteinä käsityölle, eikä pidetty ongelmana sitä että ovat nyt toiminta-hierarkiassa. Halutaanko MAOssa jostain syystä nimenomaan säilyttää (oppiaineet)-tarkenne labelissa? YSOn hierarkian saattaminen täydelliseen tasapainoon oppiaineiden osalta tuntuu aika toivottomalta tehtävältä muuten kuin auktorisoimalla kaikki jossakin opinahjossa opetettavat asiat erikseen oppiaineina, mutta tätä ei varmasti kuvailijoiden keskuudessa toivota, ja tietokantojen perkaaminen jälkikäteen olisi täysin mahdotonta.

**Comment by kseppala** [comment]
Kyllä käsitteet on MAOssa aikoinaan päätetty eritellä, koska käsityö-sanalla voidaan viitata useaan eri käsitteeseen. Käsite-ero näkyy myös siinä, että käsityöllä toimintana ja oppiaineena on omat alakäsitejoukkonsa, eivätkä nämä eri käsitteiden alakäsitteet ole toisiinsa rinnastuvia vieruskäsitteitä. Pääasia kommentissamme ei kuitenkaan ollut YSOn oppiainehierarkia, vaan se että eri YSO-versioiden välillä samaa URIa käytettiin ensin viittaamaan vain käsityöhön oppiaineena ja myöhemmin käsityöhön oppiaineena ja toimintana, mikä johti ongelmiin MAOn YSO-päivityksessä - se että jälkimmäistä käyttötapaa on koko ajan sovellettu YSAa käytettäessä, ei poista ontologiakehityksen ongelmaa.

**Comment by mirmaid** [comment]
Oletin että käsityö (oppiaineet) on syntynyt koska YSAssa on LT oppiaineet. En tunne museosektorin kuvailutarpeita mitenkään erityisen hyvin, mutta tuntuisi että jos siellä on tarpeellista erottaa käsityö oppiaineena kaikesta muusta käsityöstä, olisi samalla tavalla tarpeellista erottaa muut oppiaineet vastaavista tiedon/toiminnan aloista. Käsityö ei ole ainoa toiminta-muotoinen oppiaine - esim. tietojenkäsittely tai luova kirjoittaminen ovat myös oppiaineiden nimiä, niillä vain ei satu olemaan sitä yläkäsitteenä. 

Yritän vain jotenkin ymmärtää mikä tässä on se todellinen ongelma. Jos on käytetty labelia käsityö (oppiaineet) ja vastaavaa URIa, ja ko. URIn label on muuttunut laajemmaksi, mikä ongelma tästä seuraa? Ymmärtäisin tilanteen toisin päin jos aikaisemmin label olisi ollut käsityö ja siihen olisi myöhemmin lisätty tarkenne mutta säilytetty sama URI, koska silloin voisi todella olla niin että suurimmassa osassa tapauksia uusi label olisi väärä. Käsityön osalta uusi label ei poissulje entistä, joten en keksi miksi pitäisi poistaa tämä käsite ja luoda uusi. Kyllä niinkin tietysti voidaan tehdä ja uudelleenohjata sitten siihen tästä nyk. URIsta, jos se jotenkin ideatasolla ratkaisee asian mielekkäämmin.

**Comment by tpalonen** [comment]
YSO-kokous 8.2.17:

- YSOssa on aiemmin ollut "käsityöt (työ)"-niminen käsite. Deprekoidaan nykyinen "käsityö (toiminta)"-käsite (p5559). Herätetään henkiin käsite "käsityöt (työ)" (p485), joka muutetaan muotoon "käsityö (toiminta)". Lisätään uudelleenohjaus p5559-käsitteestä p485-käsitteeseen.

**Comment by tpalonen** [comment]
Tein YSO-kokouksen päätöksen mukaiset toimenpiteet. Lisäksi siirsin ""käsityö (toiminta)"-käsitteen (p5559) alakäsitteet p485-käsitteen alakäsitteiksi.

Käsitteiden tiedoissa oli kuitenkin eroja. Deprekoidulla p5559-käsitteellä oli p485-käsitteestö poiketen RT-suhteet näihin käsitteisiin:
kädentaidot
käsityönopettajat
käsityöt (objektit)

Ja lisäksi p485-käsitteestä poiketen nämä temaattiset ryhmät:
26 Tekstiiliteollisuus
57 Kasvatus
94 Taideteollisuus

Sekä p485-käsitteestä poiketen tämä LCSH-linkki:
<http://id.loc.gov/authorities/subjects/sh85058715>

En lisännyt näitä p485-käsitteelle. Pitäisikö ne kuitenkin lisätä?

**Comment by YSO-kokous** [comment]
PÄÄTÖS: lisätään p485-käsitteelle seuraavat tiedot:

RT-suhteet näihin käsitteisiin:
kädentaidot
käsityöt (objektit)

Ja lisäksi p485-käsitteestä poiketen nämä temaattiset ryhmät:
26 Tekstiiliteollisuus
94 Taideteollisuus

Lisäksi p485-käsitteestä poiketen definedconcept-linkit olivat seuraavat:
allars:Y19361
ysa:Y96656
