### ISSUE TITLE
gravitaatioaallot 

### ISSUE THREAD

**Issue by MikkoAleksanteri** [NatLibFi/Finto-data#812]
Onko painovoima-aallot ja gravitaatioaallot sama asia ollenkaan? Engl. gravity waves ja gravitational waves? Yleensä painovoima-aalloilla viitataan gravitaatioaaltoihin, muuten tuohon ohjaustermiin voisi lisätä sulkutarkenteenkin, mutta ymmärtääkseni ne toisetkin (veden tms.) painovoima-aallot ovat fysiikkaa. LCSH:ssa on Gravity waves (Astrophysics), ehkä sitä uskaltaisi käyttää (toisena Gravitys waves ilman tarkennetta, LT Hydrodynamics). Gravitaatiosäteily olisi yksiselitteisempi, wikipediassa (suomeksi, eng. "waves") ja tieteen termipankissa, mutta Google viitteet ovat n. 350 vs n. 50000.

**Comment by mirmaid** [comment]
YSO-kokous 9.2.2017:
painovoima-aallot (gravitaatiosäteily)
