### ISSUE TITLE
emigrantit

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#816]
Huomautus suomeksi nyt: "Tarkoittaa henkilöä, joka uskonnollisista tai poliittisista syistä on joutunut jättämään kotimaansa. Käytetään lähinnä historiallisessa yhteydessä, muissa tapauksissa käytä pakolaiset"
Ruotsinkielinen termi emigranter ei ole merkitykseltään näin kapea, vaan on paljon käytetty myös esim. sellaisista maastamuuttajista jotka ovat lähteneet ulkomaille paremman elämän toivossa taloudellisista syistä jne. Käytetään historiallisessa merkityksessä. Ruotsin osalta tärkeä termi kun puhutaan esim. 1800- 1900-luvun Suomesta Amerikkaan lähteneistä, eikä termin merkitystä voida "keinotekoisesti" vain tässä sanastossa rajata liian kapeaksi. 

MOT: "siirtolainen, (maan)pakolainen". Onko käytetty Melindassa myös muista emigranteista kuin vain uskonnollisista tai poliittisista sysitä lähteneistä? Näin on tietty ruotsiksi kuvailtu. Olisiko mahdollista muokata huomautusta niin ettei rajautuisi vain uskonnollisiin ja poliittisiin syihin? Ruotsiksi ei ole huomautusta, vaan on ajateltu että kuvailija käyttää kontekstista tai merkityksestä riippuen utvandrare, emigranter, migranter, flyktingar jne. 

Ongelma todettu uudestaan YSO-kokouksessa.

**Comment by MikkoAleksanteri** [comment]
Facta 2001:
![emigrantit facta](https://cloud.githubusercontent.com/assets/8804680/22206842/76d99b92-e185-11e6-9d46-f6ecab6228b6.jpg)

Otavan suuri tietosanakirja:
![emigrantit ost](https://cloud.githubusercontent.com/assets/8804680/22206862/8dab9a64-e185-11e6-8e92-7909108f1d55.jpg)

**Comment by mariaforsen** [comment]
Nationalencyklopedin: emigrant är en person som utvandrar från ett land till ett annat land.

**Comment by tpalonen** [comment]
YSO-kokous 8.2.17:

- Ehdotetaan, että käsitteiden merkitysero ilmaistaan ruotsiksi sulkutarkenteella. Emigranter sopii sekä emigranttien että siirtolaisten vastineeksi, mutta vaatii vielä tarkenteen. Termimuotoja käsitellään Allärs-asiantuntijoiden kesken.
- Käsitteet määrittyvät seuraavasti:
- **emigrantit**: Tarkoittaa henkilöä, joka uskonnollisista tai poliittisista syistä on joutunut jättämään kotimaansa. Käytetään lähinnä historiallisessa yhteydessä, muissa tapauksissa käytä pakolaiset
- **siirtolaiset**: henkilö joka muuttaa pysyvässä tarkoituksessa toiseen maahan (hankkiakseen sieltä toimeentulonsa)
- **maastamuuttajat**: henkilö, joka muuttaa toiseen maahan lähtömaan näkökulmasta tarkasteltuna

**Comment by YSO-kokous** [comment]
Mirja lisää huomautukset YSAan.

**Comment by mirmaid** [comment]
Lisätty määritelmät YSAan.

**Comment by YSO-kokous** [comment]
Satu tarkistaa en-vastineet ja huomaukset, muutoin issue on valmis suljettavaksi.
