### ISSUE TITLE
organisaatiot (järjestelmät), organisaatio

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#817]
Ontologiaperiaatteet muutettiin niin ettei tarvita sulkutarkennetta jos label on yksilöivä. "Organisaatiot" on selkeä asiasanana, eikä sitä voi sekoittaa organisaatioon toimintana? Sanastossa siis nyt myös organisaatio (ilmiöt) - onko tämä tällä sulkutarkenteella täysin yksiselitteinen? Vai olisiko nimenomaan kyse organisaatio (toiminta) -merkityksestä? Vai mihin tämä organisaatio (ilmiöt) oikein viittaa? Sanastossa on nimittäin myös termi "organisointi", päällekkäisyyttä? 

MOT:  organisaatio: järjestely, toimivaksi kokonaisuudeksi järjestäminen, organisointi; järjestämisen tulos, järjestetty toimintakokonaisuus; järjestö

**Comment by mirmaid** [comment]
Käsitellään issuessa https://github.com/NatLibFi/Finto-data/issues/536
