### ISSUE TITLE
muut järjestelmät

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#818]
Alakäsitteet:
    hallintajärjestelmät
    infrastruktuurit
    klusterit
    konteksti
    ohjausjärjestelmät
    ontologiat (tiedonhallinta)
    todellisuus
    verkostot
    viestimet
    ympäristö

Olisiko syytä miettiä onko tämä koherentti kokonaisuus, varsinkin todellisuus ja ympäristö voisi ehkä olla muuallakin?

**Comment by mirmaid** [comment]
YSO-kokous 9.2.2017:

hallintajärjestelmät YK tekniset järjestelmät
infrastruktuurit YK yhteiskunnalliset järjestelmät
klusterit YK järjestelmät
konteksti YK ominaisuudet
ohjausjärjestelmät YK järjestelmät

**Comment by mirmaid** [comment]
YSO-kokous 15.3.2017:

ontologiat (tiedonhallinta) YK tekniset objektit (abstraktit objektit) TAI tietomallit
todellisuus YK järjestelmät
verkostot YK järjestelmät
viestimet YK yhteiskunnalliset järjestelmät
ympäristö YK järjestelmät

**Comment by MikkoAleksanteri** [comment]
Muutokset toteutettu ja muut järjestelmät -käsite deprekoitu.
