### ISSUE TITLE
vastineet

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#819]
Monimerkityksinen termi ja ryhmä 00, sekä käytettykin Melindassa eri merkityksissä. Olisiko jako/määrittely tarpeen? 

Ks. MOT: 
1. jtak vastaava esine, asia tms.; samaan käyttöön t. tarkoitukseen soveltuva esine, asia tms. kuin jk toinen. 
2. (vars. kirjallinen) vastaus arvosteluun, moitteeseen tms. 
Oik. vastaajan oikeudenkäynnissä antama selvitys, joka sisältää hänen vaatimuksensa.
3. korvaus, hyvitys, vastike. 

1 motsvarighet, motstycke
2 (esikuva) förebild
3 (vars. sanakirjassa) ekvivalent 
4 (korvaus) ersättning, valuta 
5 (vastaus arvosteluun tms) genmäle, bemötande (svar)
6 oik replik, svaromål

**Comment by mirmaid** [comment]
Melindassa 43 viitettä

- kymmenkunta vanhinta on julistuksia/asetuksia koskien setelirahaa 1700-luvulla
- suurin osa muista käsittelee sanavastineita eri kielissä
- jonkin verran myös vastineesta oikeudenkäynnissä
- joitakin kertoja liittyen vastineisiin ja vastineoikeuteen lehtikirjoittelussa
- jokin yksittäinen merkityksessä "jotakin vastaava asia" (esim. käytetään jnk sijasta)

**Comment by mirmaid** [comment]
Sanavastineista osalle voisi käydä [käännösvastineet](http://tieteentermipankki.fi/wiki/K%C3%A4%C3%A4nn%C3%B6stiede:k%C3%A4%C3%A4nn%C3%B6svastine)

**Comment by mirmaid** [comment]
vastineet (oikeus/prosessioikeus) lienee ok

**Comment by mirmaid** [comment]
vastineet (viestintä/media/?) http://www.jsn.fi/periaatelausumat/vastine/

**Comment by mirmaid** [comment]
kymmenkunta vanhinta on julistuksia/asetuksia koskien setelirahaa 1700-luvulla - mitä tehdään näille?

**Comment by YSO-kokous** [comment]
Sanavastineista osalle voisi käydä käännösvastineet. Toisaalta osassa aineistoa kyse on muusta sanaston tutkimuksesta, ei kääntämisestä.

Ehdotus: vastineet (kielitiede) omana terminään TAI KÄ vastaavuus TAI KÄ käännösvastineet (otettaisiin uutena) + vastaavuus

**Comment by YSO-kokous** [comment]
Kymmenkunta vanhinta on julistuksia/asetuksia koskien setelirahaa 1700-luvulla - vaihdetaan tilalle vastaavuus? (kysytään Pasilta/Ilonalta/Mikolta)

**Comment by mirmaid** [comment]
Jaettu YSAssa.
