### ISSUE TITLE
pakotteet, sanktiot

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#820]
Ruotsiksi tähän asti ollut: sanktioner, sanktioner (bestraffning) -merkitysero ei ollenkaan selkeä kuvailijalle ja on mahdotonta valita oikein näiden termien perusteella. Mikä on tarkka merkitysero ja miten nämä käytetään suomeksi? Ryhmät kuitenkin samat. Tähän pitäisi saada selvyyttä ennen kuin voidaan luoda tarkoituksenmukaisia sulkutarkenteita ruotsiksi. Englanniksi vastaava tilanne?

MOT: 
pakote: painostuskeinona käytetty pakkotoimi; oik., sosiol. normin rikkojaan kohdistuva epämiellyttävä seuraamus, sanktio

sanktio: 1. oik. oikeussäännöksen noudattamista tehostava keino (tav. rangaistus), tehoste, seuraamus; kansainvälisessä oikeudessa: (taloudellinen t. pol.) pakote. Sakko, vahingon korvaaminen ym. sanktiot. YK:n sotaa käyviin maihin kohdistamat taloudelliset sanktiot.
2. psyk., sosiol. seuraamus, esim. palkkio t. rangaistus, jonka avulla pyritään ohjaamaan yksilön käyttäytymistä.
3. oik. lain tms. vahvistaminen.

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/5325
