### ISSUE TITLE
Yhden käsitteen alt on toisen pref

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#821]
YSOssa on labeleita, jotka esiintyvät yhden käsitteen altlabelina ja toisen käsitteen preflabelina. Tapauksia on vajaa sata, ks. alla oleva taulukko. YSA-YSO-päivitin ei ilmeisesti ole tunnistanut näitä. 

https://docs.google.com/spreadsheets/d/1nHJw-lwiIvof5apcYf6OEwZW46X1k9bfYD2wNG3IOyQ/edit?usp=sharing

EHDOTUS: poistetaan kyseiset altlabelit

Käytin tällaista SPARQL-kyselyä:

SELECT * 
WHERE {
       ?concept skos:prefLabel ?label .
        ?ysoconcept skos:altLabel ?label .
      ?concept a yso-meta:Concept .
      ?ysoconcept a yso-meta:Concept .
        FILTER (lang(?label) = 'fi')
        FILTER(?concept != ?ysoconcept)
}

**Comment by mirmaid** [comment]
YSO-kokous 9.2.2017:

Tuomas käy listan läpi ja poistaa altLabelin, paitsi jos kyse on eri merkityksestä ja altLabeliin on syytä lisätä sulkutarkenne. Lista myös YSAan jääneistä tapauksista. Maria ja Satu hoitavat vastaavat englannin- ja ruotsinkieliset tapaukset.

**Comment by tpalonen** [comment]
Mustiinpanoja:
genealogia - pitäisikö genealogia-käsitteen preflabelissa olla sulkutarkenne? käsite ei viittaa sukututkimukseen. nyt sukututkimus-käsitteellä on altlabel "genealogia (sukututkimus)".

**Comment by satuniininen** [comment]
Tehty englannin osalta.

**Comment by YSO-kokous** [comment]
Ei lisätoimenpiteitä YSOn osalta (ei lisätä sulkutarkenteita). @mirmaid käy issuessa olevan listan läpi ja poistaa ohjaustermi-päätermi-ristiriidat YSAsta.

Kirjataan huomautus Aswiin YSOn kehityslinjauksiin:
"Jos sama termi esiintyy sekä yhden käsitteen ohjausterminä että toisen käsitteen käytettävänä terminä, ohjaustermille lisätään sulkutarkenne, mutta käytettävälle termille lisätään sulkutarkenne vain, jos väärinkäsityksen riski on merkittävä ja luonteva sulkutarkenne löytyy helposti."

**Comment by mirmaid** [comment]
Huomautus taitaa olla vielä lisäämättä? @tpalonen

**Comment by tpalonen** [comment]
Huomautus on lisätty kommenttina linjausten perään.
https://www.kiwi.fi/display/Asiasanastotjaontologiat/YSOn+kehityslinjaukset

**Comment by YSO-kokous** [comment]
Asiakaswikissä YSOn kehityslinjauksissa on nyt muutama lisäys kommenttina. Käsitellään näitä seuraavassa pienryhmäkokouksessa ja mikäli hyväksytään niin siirretään itse linjaustekstiin.
