### ISSUE TITLE
Kulkuneuvojen hierarkia

### ISSUE THREAD

**Issue by satuniininen** [NatLibFi/Finto-data#825]
Tällä hetkellä kulkuneuvojen alla, mutta ovatko miehittämättömät alukset enää varsinaisesti kulkuneuvoja? Jos siirretään pykälän ylemmäksi hierarkiassa niin yläkäsitteeksi tulisi _elottomat objektit_ (siellä ovat myös _ufot_).

**Comment by mirmaid** [comment]
vrt. myös avaruusasemat, avaruusalukset. Kulkuneuvojen alla myös muuta joka ei ensisijaisesti kuulu sinne.

**Comment by satuniininen** [comment]
kulkuneuvo:

kielitoimiston sanakirja: kulkuneuvo kulku-, liikenneväline. _Auto, juna, lentokone, laiva, polkupyörä ym. kulkuneuvot. Maa-, vesikulkuneuvo._ 

Wikisanakirja: 
1. keino kulkemiseen          
2. kulkuväline; paikasta toiseen liikkumiseen tarkoitettu ajoneuvo tai muu väline tai laite, jolla voidaan kuljettaa matkustajia tai erilaisia taakkoja


Ehdotan seuraavia siirtoja:

**öljynporauslautat** ->tekniset objektit (fyysiset objektit) 
**jäänmurtajat** -> tekniset objektit (fyysiset objektit) 
**miehittämättömät ajoneuvot** -> tekniset objektit (fyysiset objektit) 
**miehittämättömät ilma-alukset** -> tekniset objektit (fyysiset objektit) 
**avaruusalukset** ->  tekniset objektit (fyysiset objektit) 

**asuntolaivat** -> asunnot?

**perävaunut** -> kuljetusvälineet tai kuljetuskalusto
**säiliövaunut**-> kuljetusvälineet tai kuljetuskalusto
**veturit** (alakäsitteineen) -> kuljetusvälineet tai kuljetuskalusto
**junanvaunut** (alakäsitteineen) -> kuljetusvälineet tai kuljetuskalusto?
Vai  tulkitaanko nämä siten, että sisältyvät Wikisanakirjan kakkosmerkitykseen eli taakkojen kuljettamiseen?

**traktorit** -> työkoneet
**tiekoneet** (alakäsitteineen) ->  työkoneet
**moottorityökoneet** -> työkoneet (eli monihierarkia pois)

Ongelmallisia:

- sota-alukset, sotilasajoneuvot, sotilaslentokoneet (kaikilla myös alakäsitteitä)
- kirjastoautot, hälytysajoneuvot, myymäläautot jne tiettyä palvelua tarjoavat kulkuvälineet
- asuntovaunut (voi liikkua tai pysyä paikallaan, vrt. _asuntolaivat_, enemmän ehkä kuitenkin matkantekoväline)

**Comment by YSO-kokous** [comment]
PÄÄTÖS:
öljyporauslautat YK rakennelmat
jäänmurtajat: ei muutoksia

Jatketaan myöhemmin.

**Comment by YSO-kokous** [comment]
asuntolaivat -> asunnot RT laivat
perävaunut -> vaunut
säiliövaunut-> vaunut
veturit (alakäsitteineen) -> koneet
junanvaunut (alakäsitteineen) -> vaunut
vaunut > kuljetusvälineet
raitiovaunut > maakulkuneuvot RT vaunut

**Comment by satuniininen** [comment]
Tähänastiset päätökset toteutettu

**Comment by YSO-kokous** [comment]
Jäljellä vielä:
miehittämättömät ajoneuvot -> tekniset objektit (fyysiset objektit)
miehittämättömät ilma-alukset -> tekniset objektit (fyysiset objektit)
avaruusalukset -> tekniset objektit (fyysiset objektit)
traktorit -> työkoneet
tiekoneet (alakäsitteineen) -> työkoneet
moottorityökoneet -> työkoneet (eli monihierarkia pois)

Ongelmallisia:

sota-alukset, sotilasajoneuvot, sotilaslentokoneet (kaikilla myös alakäsitteitä)
kirjastoautot, hälytysajoneuvot, myymäläautot jne tiettyä palvelua tarjoavat kulkuvälineet
asuntovaunut (voi liikkua tai pysyä paikallaan, vrt. asuntolaivat, enemmän ehkä kuitenkin matkantekoväline)

**Comment by YSO-kokous** [comment]
moottorityökoneet -> työkoneet (eli monihierarkia pois): **ei poisteta monihierarkiaa**
tiekoneet (alakäsitteineen) -> työkoneet: **jätetään YK maarakennuskoneet, poistetaan muut**
traktorit -> työkoneet: _RT moottorityökoneet, ei muita muutoksia_

**Comment by YSO-kokous** [comment]
miehittämättömät ajoneuvot, miehittämättömät ilma-alukset, avaruusalukset: **ei muutosta**
