### ISSUE TITLE
kaupungit, kunnat ym.

### ISSUE THREAD

**Issue by MikkoAleksanteri** [NatLibFi/Finto-data#826]
kaupungit ovat nyt YK kunnat

tämä ei kokonaisuutena varmaan päde, eikä erilaiset kaupungit ole välttämättä kuntia

erilaisia *kaupungit -käsitteitä myös esim. YK ihmisen määrittämät alueet

tulisi ratkaista kokonaisuutena

**Comment by MikkoAleksanteri** [comment]
17 tulosta haulle '*kaupungit'

esikaupungit
kaupunginosat
lähiöt
62 Yhteiskuntasuunnittelu. Yhdyskuntasuunnittelu. Aluesuunnittelu
suburbs (en), förstäder (sv)
http://www.yso.fi/onto/yso/p5582

kaivoskaupungit
kaupungit
62 Yhteiskuntasuunnittelu. Yhdyskuntasuunnittelu. Aluesuunnittelu
mining towns (en), gruvstäder (sv)
http://www.yso.fi/onto/yso/p27832

kaupungit
kunnat
kaivoskaupungit
kaupunkimallit, kaupunkiseudut, kuntamuodot, muinaiskaupungit, puukaupungit, puutarhakaupungit, seutukaupungit, teollisuuskaupungit
... (8)
62 Yhteiskuntasuunnittelu. Yhdyskuntasuunnittelu. Aluesuunnittelu , 71 Hallinto. Organisaatiotutkimus. Julkinen hallinto
... (2)
towns and cities (en), städer (sv)
http://www.yso.fi/onto/yso/p1688

kulttuuripääkaupungit
pääkaupungit
50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi , 62 Yhteiskuntasuunnittelu. Yhdyskuntasuunnittelu. Aluesuunnittelu , 71 Hallinto. Organisaatiotutkimus. Julkinen hallinto
... (3)
capitals of culture (en), kulturhuvudstäder (sv)
http://www.yso.fi/onto/yso/p17961

muinaiskaupungit
ihmisen määrittämät alueet
kaupungit
52 Historia
ancient cities (en), fornstäder (sv)
http://www.yso.fi/onto/yso/p25702

pikkukaupungit
kunnat
62 Yhteiskuntasuunnittelu. Yhdyskuntasuunnittelu. Aluesuunnittelu , 71 Hallinto. Organisaatiotutkimus. Julkinen hallinto
... (2)
small towns (en), småstäder (sv)
http://www.yso.fi/onto/yso/p12059

puukaupungit
ihmisen määrittämät alueet
kaupungit
91 Arkkitehtuuri
wooden towns (en), trästäder (sv)
http://www.yso.fi/onto/yso/p20399

puutarhakaupungit
ihmisen määrittämät alueet
kaupungit
62 Yhteiskuntasuunnittelu. Yhdyskuntasuunnittelu. Aluesuunnittelu
garden cities (en), trädgårdsstäder (sv)
http://www.yso.fi/onto/yso/p3854

pääkaupungit
kunnat
kulttuuripääkaupungit
pääkaupunkiseutu
62 Yhteiskuntasuunnittelu. Yhdyskuntasuunnittelu. Aluesuunnittelu , 71 Hallinto. Organisaatiotutkimus. Julkinen hallinto
... (2)
capital cities (en), huvudstäder (sv)
http://www.yso.fi/onto/yso/p1687

satamakaupungit
kunnat
62 Yhteiskuntasuunnittelu. Yhdyskuntasuunnittelu. Aluesuunnittelu
port cities (en), hamnstäder (sv)
http://www.yso.fi/onto/yso/p5645

satelliittikaupungit
kunnat
62 Yhteiskuntasuunnittelu. Yhdyskuntasuunnittelu. Aluesuunnittelu
satellite towns (en), satellitstäder (sv)
http://www.yso.fi/onto/yso/p15865

seutukaupungit
kunnat
kaupungit
Pieniä tai keskisuuria kaupunkeja, joilla on omat vaikutusalueensa, mutta jotka eivät ole maakuntakeskuksia tai osia suuremmista kaupunkiseuduista.
... (1)
62 Yhteiskuntasuunnittelu. Yhdyskuntasuunnittelu. Aluesuunnittelu , 71 Hallinto. Organisaatiotutkimus. Julkinen hallinto
... (2)
small towns (en), regionstäder (sv)
http://www.yso.fi/onto/yso/p27073

suurkaupungit
kunnat
metropolialueet
metropolit
62 Yhteiskuntasuunnittelu. Yhdyskuntasuunnittelu. Aluesuunnittelu
large cities (en), storstäder (sv), metropoler (sv)
http://www.yso.fi/onto/yso/p17197

tapulikaupungit
kunnat
52 Historia
staple towns (en), stapelstäder (sv)
http://www.yso.fi/onto/yso/p18773

teollisuuskaupungit
kunnat
kaupungit, teollisuusyhdyskunnat
62 Yhteiskuntasuunnittelu. Yhdyskuntasuunnittelu. Aluesuunnittelu
industrial cities (en), industristäder (sv)
http://www.yso.fi/onto/yso/p27629

vapaakaupungit
kunnat
52 Historia
free cities (en), freetowns (en), fristäder (sv)
http://www.yso.fi/onto/yso/p7132

ystävyyskaupungit
kunnat
ystävyyskunnat
65 Valtio-oppi. Politiikka. Kansainvälinen politiikka , 71 Hallinto. Organisaatiotutkimus. Julkinen hallinto
twin towns (cities and towns) (en), vänorter (städer) (sv), vänstäder (sv), vänorter (sv)
http://www.yso.fi/onto/yso/p15169

**Comment by mirmaid** [comment]
Myös https://github.com/Finto-ehdotus/YSE/issues/5180

Nykyinen tilanne on sekava, kaupungit ST kaivoskaupungit, eikö muutkin sopisi paremmin kaupunkien kuin kuntien alakäsitteiksi? Ja ehkä sitten kaupungit pois kuntien alta?

**Comment by YSO-kokous** [comment]
Kaikki *kaupungit-päätteiset YK kaupungit
kaupungit YK hallintoalueet + julkisyhteisöt
