### ISSUE TITLE
sovitus (uskonto)

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#827]
On ollut försoning Allärsissa, joka voi viitata yhtä hyvin sovitukseen ihmisen ja jumalan välillä kuin ihmisten väliseen. Käytettykin sillä tavalla Melindassa, esim. Reconciliation : restoring justice / John W. de Gruchy ; The reconciliation of peoples : challenge to the churches / ed. by Gregory Baum, Harold Wells ; Efter kriget : den svåra vägen till försoning / Johanna Mannergren Selimovic ; Voiko historiaa hyvittää? : historiallisten vääryyksien korjaaminen ja anteeksiantaminen / toimittanut Jan Löfström ; Remembering and forgetting after war : narratives of truth, justice and reconciliation in a Bosnian town / Johanna Mannergren Selimovic...

Myös sovinto löytyy YSAsta, mutta huomautuksella joka viittaa oikeustieteeseen, ja sen vastine ruotsiksi on eri sana - förlikning. Hyvityskin löytyy mutta se viittaa oikeuteen ja kauppaan. 

Jos lisätään tarkenne (religion) myös ruotsiksi niin menetetään ihmisten välinen-merkitys, mikä olisi tosi harmillista ruotsin kannalta. Myös Svenska ämnesordi:ssa on försoning ja linkki LCSH:n reconciliation (EI merkityksessä yhteensovittaminen..) Jos ei tehdä mitään niin käyttäjät laittavat jatkossakin Melindassa myös politiikkaan (rauhan yms.) ja ihmissuhteisiin liittyvälle aineistolle asiasana försoning, eikä sekään ole ok. 

Onko mahdollista löytää laajempi tarkenne vai onko oikeastaan niin että suomen kannalta tässä yhteydessä käytettäisiin sovinto, ja jos näin on niin onko mahdollista poistaa sovinto-termin huomautus joka viittaa vain oikeustieteeseen?

**Comment by mirmaid** [comment]
Sovinto, miten käytetty? Merkitys "sovinnonteko". Onko sovitus (uskonto) hyvä tarkenne?
