### ISSUE TITLE
sotilashenkilöt

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#829]
Ei ole YSAssa. Onko todella tarpeen vai voisiko hierarkia olla sama kuin YSAssa, eli sotilashenkilöstö yläkäsitteenä? Ja tämä voisi poistaa vai olisiko mahdollista laittaa jompikumpi korvatuksi? Vai onko tarkoitus lisätä myös sotilashenkilöt YSAan? Ruotsiksi sotilashenkilöstö= militärer (personal) tai militär personal ja sotilashenkilö= militär (person).

**Comment by YSO-kokous** [comment]
Tämä on jo hierarkisoiva käsite -tyyppiä Ei vaadi toimenpiteitä. Korjataan ruotsin osalta.
