### ISSUE TITLE
muutos-käsitteen alakäsitteet

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#831]
Muutos-kategoriasta löytyy käsite [leimautuminen (sosiologia)](http://www.yso.fi/onto/yso/p17320), jonka yläkäsite yhteiskunnallinen muutos on virheellinen, kyse on yksilön leimautumisesta sosiaalisesti. Nykyisistä oikea yläkäsite olisi henkilöön liittyvä muutos.

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus @satuniininen
