### ISSUE TITLE
koulukodit & kasvatuslaitokset

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#832]
[koulukodit](http://www.yso.fi/onto/yso/p14132)
[kasvatuslaitokset](http://www.yso.fi/onto/yso/p14131)
Mielestäni edeltäjä-seuraaja -suhde on näille ok, mutta en yhdistäisi näitä YSOssa. 

ks. esim. http://wiki.narc.fi/portti/index.php/Koulukodit_ja_kasvatuslaitokset. Koulukoti-nimitys on otettu käyttöön 1940-luvulla, tuntuisi virheelliseltä käyttää sitä 1800-luvun laitoksista, vaikka näillä ei mitään aivan selkeää rajaa olekaan: _1920-30-luvulla kasvatuslaitossijoituksissa ryhdyttiin painottamaan sosiaalista näkökulmaa rikosoikeudellisen sijaan. Vuoden 1937 lastensuojelulaki määritteli kasvatuslaitossijoituksen lastensuojelun välineeksi. Sotien jälkeen oli vuorossa taas uusi sosiaalipoliittinen muutos: kasvatuslaitoksista tuli koulukoteja ja pahantapaisuuden sijasta alettiin keskustella nuorten sopeutumattomuudesta._ http://agricola.utu.fi/julkaisut/kirja-arvostelut/index.php?id=898

Myös ruotsiksi näillä on eri labelit.

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotukset. Mirja muotoilee huomautukset.

**Comment by mirmaid** [comment]
**Koulukodit**
Lastensuojelulaitos, jossa annetaan kasvatusta, hoitoa ja perusopetusta ja siihen liittyvää muuta opetusta sekä ammatillista koulutusta sellaisille lastensuojelulain perusteella sosiaalilautakunnan huostaan otetuille lapsille ja nuorille henkilöille, joita ei voida tarkoituksenmukaisesti kasvattaa ja hoitaa perhehoidossa, lastenkodissa tai muussa lastensuojelulaitoksessa. (vähän lyhennetty https://www.finlex.fi/fi/laki/ajantasa/1978/19780769?search%5Btype%5D=pika&search%5Bpika%5D=koulukodeista)
Kasvatuslaitoksia alettiin perustaa 1800-luvulla. Laitoksiin sijoitettiin tuomioistuinten päätöksillä 7–14-vuotiaita lapsia ja laitokset toimivat vankeinhoitohallituksen alaisina. Kasvatuslaitosten nimet muutettiin koulukodeiksi vuonna 1946, kun rangaistuslaitosten maineesta pyritiin eroon. (Wikipediasta)

**Comment by YSO-kokous** [comment]
Hyväksytään
