### ISSUE TITLE
oikeusapu & yleinen oikeusapu

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#834]
oikeusapu

1) Oikeusapu tarkoittaa sitä, että kansalainen voi saada itselleen oikeudellisen asian hoitamista varten avustajan kokonaan tai osittain valtion varoilla.

Aikaisemmin käytetty termiä yleinen oikeusapu. Molemmat ovat lakitermejä (Oikeusapulaki, Laki yleisestä oikeusavusta, Laki yleisestä oikeusaputoiminnasta), mutta yhdistäminen voisi silti toimia koska oikeusapu-sana sisältyy myös tähän aikaisempaan termiin? Samoin ruotsiksi. Myös edeltäjä-seuraaja-suhde on ihan ok, koska termimuutos liittyy lainmuutokseen.

(lisäys ohjaustermiksi: oikeusapu KT julkinen oikeusapu)

2)  Tarkoitti aikaisemmin tuomioistuimen toiselle tuomioistuimelle antamaa apua. (Vuodesta 2002 lähtien oikeusapu on tarkoittanut kansalaisille oikeusasioiden hoidossa järjestettyä apua ja virka-apu on tarkoittanut mm. tuomioistuimen toiselle tuomioistuimelle antamaa apua.)

oikeusapu tuomioistuimelle KÄ virka-apu

Melindassa oikeusapu-termiä on käytetty 1-merkityksessä (muutamissa vanhimmissa viitteissä niin niukat tiedot ettei sisällöstä voi olla aivan varma).

**Comment by YSO-kokous** [comment]
Kohta 1: jätetään edeltäjä-seuraajasuhde
Kohta 2: tehdään ohjaustermi
