### ISSUE TITLE
elokuvateatterit YK teatterit

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#835]
Ruotsiksi (biografer (film) LT teatrar) tämä ei täsmää (teatteri on "eläviä" esityksiä koskeva). Onkohan tässä valittu YK turhan "sanapainotteisesti"? Olisiko mahdollista valita joku muu yläkäsite?

**Comment by YSO-kokous** [comment]
Korvataan entinen yläkäsite ja laitetaan uusi:
elokuvateatterit YK organisaatiot (järjestelmät)
