### ISSUE TITLE
yhdyskuntapsykologia

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#836]
Nyt sv. samhällspsykologi (lokalsamhällen) ja eng. community psychology (regional communities). Onko todella näin, Melindassa vain 12 viitettä enkä oikein havainnut tällaista eroa? Sanastossa siis myös yhteisöpsykologia, sv. samhällspsykologi (gemenskaper) ja eng. community psychology. Tämä käsite aiheuttaa siis ongelmia kielirajojen yli. Googlessa ei osumia (!), muuta kuin Finto-asiasanana. Täsmääkö todella tarkenteet ja onko ylipäätään tämä käsite tarpeen, vai olisiko poistettavissa?

**Comment by YSO-kokous** [comment]
@mariaforsen tekee YSE-issuen.

**Comment by mirmaid** [comment]
Tämä on jo ratkaistu.
