### ISSUE TITLE
asema (yhteiskunnalliset ilmiöt) 

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#838]
Tämä termi ei ole YSAssa. Epäselvää onko sv. "ställning" paras mahdollinen vastine. Sanastossa (ja YSAssa) on myös käsite sosiaalinen asema. Onko tämä melkein sama asia, vai halutaanko tällä viitata johonkin muuhun? Siinä tapauksessa jonkinlainen selite olisi varmaan hyvä? 

Sosiaalisesta asemasta esim. Wikipedia: Sosiaalinen status on arvostus, kunnioitus tai arvovalta, jonka yksilö saavuttaa asemassaan yhteiskunnassa. Sosiaalinen status tarkoittaa myös yhteiskunnallista asemaa. Ja "sitä millaisessa asemassa olet yhteiskunnassa"..?

Ks. Kielitoimiston sanakirja "asema".

**Comment by YSO-kokous** [comment]
Muutetaan käsite hierarkisoivaksi käsitteeksi.
