### ISSUE TITLE
konvergenssi

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#840]
Mihin tämä viittaa? Huomautus on sääntöjen vastainen:
"yhteen suuntautuminen, lähentyminen, yhtyminen
YSA: Termillä on useita merkityksiä. 1) Yhteen suuntautuminen, lähestyminen. 2) Kehittyminen kohti samaa lopputilaa. 3) Biologiassa eri alkuperää olevien eliölajien kehittyminen samaan suuntaan ympäristön vaikutuksesta. 4) Kielitieteessä eri kielten kehittyminen samaan lopputilaan. 5) Matematiikassa päättymättömän lukujonon läheneminen raja-arvoon siten, että erotus voidaan saada kuinka pieneksi tahansa menemällä tarpeeksi pitkälle"

**Comment by YSO-kokous** [comment]
@mariaforsen tekee YSE-issuen.
