### ISSUE TITLE
esteet (elottomat objektit) ja esteet (ilmiöt)

### ISSUE THREAD

**Issue by satuniininen** [NatLibFi/Finto-data#841]
YSO-kokouksessa ehdotettiin sulkutarkenteen (ilmiöt) muuttamista muotoon (vaikeuttavat tekijät). Sen yhteydessä keskusteltiin myös siitä, onko elottomat objektit  asianmukainen sulkutarkenne toisaalta onko jako ylipäätään tarpeen.

Kielitoimiston sanakirja antaa esteelle kolme merkitystä: 
1. etenemistä vaikeuttava t. estävä (maaston) muodostuma, luonnonilmiö tms. Jääeste. Liikenne-este. Ylittää esteet. Sumu oli esteenä lentoliikenteelle.
Sot. etenemistä haittaava rakennelma. Piikkilankaeste. Panssarieste.
Urh. estejuoksussa t. -ratsastuksessa käytettävä puomi, vesihauta, penkere tms. Kuiva-, vesieste.
Mon. estejuoksu. 3 000 metrin esteet.
2. liikettä estävä esine t. rakenneosa. Liukueste.
3. seikka, tapahtuma tms., joka haittaa jtak tapahtumaa t. estää sen. Laillinen, ylivoimainen este. Työeste. Hänelle tuli este. Lakko oli esteenä kokoukselle. Päästä kulkemaan esteettä.

YSOn nykyisessä jaossa merkitykset 1 ja 2 niputettu yhteen. Onko kuitenkaan esim. luonnonmuodostuma tai sumu luontevaa mieltää elottomaksi objektiksi tai objektiksi ylipäätään? Rajanveto merkitysten välillä on vaikeaa eivätkä ehdotetut sulkutarkenteet välttämättä ohjaisi kuvailijaa/tiedonhakijaa kielitoimiston käsitejakoa mukailevaan ratkaisuun.

**Comment by mirmaid** [comment]
Kävin läpi ensimmäiset sata viitettä Melindassa; konkreettiset:
_Hevosurheilu_
_La barricade_: esteet - kadut
_Suluttamisopas 2014 luonnos_: esteet, raivaus
_The ultimate parkour & freerunning book_
_Agilityesteiden rakentaminen koirille_

**Comment by mirmaid** [comment]
Hidasteet käytetty muuten liikenne-yhteydessä, mutta kerran Viestintäpalvelujen yleistymisen esteet (tässä ei varmaan toimisi farthinder :-)).

**Comment by YSO-kokous** [comment]
Poistetaan jako @tpalonen

**Comment by tpalonen** [comment]
Kumpi säilytetään vai luodaanko kokonaan uusi käsite? Mikä yläkäsitteeksi?

**Comment by YSO-kokous** [comment]
Poistetaan vanhan esteet-käsitteet ja luodaan uusi esteet-käsite ilman sulkutarkennetta. Tälle yläkäsitteeksi vaikutukseen liittyvä rooli. Ryhmäksi 00. Ei määritelmää. Defined concept: YSA: esteet; Allärs: hinder.

Vanhat alakäsitteet siirretään seuraavasti:

avioesteet YK esteet
kaupan esteet YK esteet
hidasteet YK elottomat objektit
meluesteet YK esteet
puomit YK elottomat objektit

**Comment by mirmaid** [comment]
Miksiköhän tämä on assignattu minulle...

**Comment by tpalonen** [comment]
Toteutettu dataan.
