### ISSUE TITLE
transgressio

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#843]
YSAssa ryhmä 00, YSOssa 11. Transgressio (geologia) olisi mahdollinen, mutta käsittääkseni tarkoittaa ainakin lähes samaa kuin rannansiirtyminen, joka on jo YSAssa. https://en.wikipedia.org/wiki/Marine_transgression

Enemmän käytetty kirjallisuudentutkimuksen terminä, Kirjasampo: _Kirjallisuuden tutkimuksen ilmaus, jolla tarkoitetaan rajojen rikkomista._ Joitakin kertoja samassa merkityksessä myös muun taiteen/kulttuurintutkimuksen/opetuksen alalla. Wikisanakirja: normin rikkominen, eettisten tai moraalisten rajojen ylittäminen

https://www.vocabulary.com/dictionary/transgression
1. the act of transgressing; the violation of a law or a duty or moral principle
2. the spreading of the sea over land as evidenced by the deposition of marine strata over terrestrial strata

**Comment by mirmaid** [comment]
transgressio (geologia) KÄ rannansiirtyminen
transgressio (sulkutarkenne) - ideoita?

**Comment by YSO-kokous** [comment]
PÄÄTÖS

-tehdään YSE-ehdotus. "transgressio (geologia)" KÄ rannansiirtyminen on käypä. kehitetään toiselle merkitykselle jokin sopiva sulkutarkenne (yhteiskunnallinen/sosiaalinen/tms).

**Comment by mirmaid** [comment]
Muutettu YSAssa, yläkäsite muuttuu YSOssa (varmaan halutaan deprekoida käsite, vastaava poistettu YSAssa).
