### ISSUE TITLE
Toimistot ovat sekä organisaatioita että paikkoja

### ISSUE THREAD

**Issue by YSO-kokous** [NatLibFi/Finto-data#845]
Suuri osa *toimistot-loppuisista käsitteistä on sekä toimistot-käsitteen että palveluyritykset-käsitteen alakäsitteitä. Näin ne ovat sekä paikkoja että organisaatioita. Jompi kumpi näistä olisi hyvä valita yläkäsitteeksi ja toinen esim. muuttaa assosiatiiviseksi. Tässä kaikki *toimistot-käsitteet, joilla on kyseinen hierarkia:

arkkitehtitoimistot
asianajotoimistot
etsivätoimistot
insinööritoimistot
konsulttitoimistot
lakiasiaintoimistot
mainostoimistot
matkatoimistot
mediatoimistot
ohjelmatoimistot
tilitoimistot

ps. Pitäisikö YSOn kehityslinjauksiin kirjata monihierarkia-kohtaan, että käsite ei saa samaan aikaan olla sekä paikka että jokin muu?

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/4800

**Comment by mirmaid** [comment]
Myös ristiriita sv. vastineissa: Allärs, Bella, Kauno: byråer, Allfo: kontor

**Comment by mariaforsen** [comment]
Korjattu YSOssa.

**Comment by mirmaid** [comment]
Ks. myös https://github.com/Finto-ehdotus/YSE/issues/7300

**Comment by mirmaid** [comment]
Siirretään kaikki toimistot-loppuiset takaisin toimistojen alle (paitsi mahdollisesti jos osa on enemmän "virastoja"). Lisätään toimistoille toiseksi yläkäsitteeksi organisaatiot. 

Listataan palveluyritysten alakäsitteistä sellaiset, jotka eivät ensisijaisesti myy palveluita. Siirretään ne suoraan yritysten alle, jos ei ilmene ongelmatapauksia.

**Comment by mirmaid** [comment]
^ Työstetty yhdessä.
