### ISSUE TITLE
trimmaus

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#847]
Viritys-käsitteen jaon yhteydessä ilmeni ongelmia myös tämän suhteen ruotsiksi. Nimittäin viritys (moottorit)=trimning (motorer), mutta sanastossa on myös ennestään pelkkä "trimning"=trimmaus. Trimmaus on nyt sekä ryhmässä 22 että 39. Onko mahdollista määritellä termin merkitys yhteen näistä vai pitääkö jakaa? Ks. myös "trimmata" Kielitoimiston sanakirjassa. Melindassa käytetty lähinnä koirien trimmauksesta, mutta myös muutama poikkeus.

**Comment by YSO-kokous** [comment]
Päätös:

Rajataan käsitteen merkitys eläinten trimmaukseen. Poistetaan ryhmä 39. Lisätään tarkentava huomautus. Tehdään nämä muutokset YSAn kautta.

**Comment by mariaforsen** [comment]
Ruotsiksi nyt muutettu tämän päätöksen mukaiseksi: trimning (djur)
