### ISSUE TITLE
tulosteet

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#848]
Ks. hierarkia > tuloste ei ole ominaisuus... Nykyinen sulkutarkenne on ruotsiksi (output), mikä on todella hämmentävää käyttäjille. Parasta olisi jos ontologialinjaukset sallivat että monikko jää ilman tarkenne (kaikki ruotsinkieliset ainakin ymmärtävät että utskriftER ei voi olla muuta kuin tulostuksen "tulos", eli tulostetut paperit jne.), mutta jos tämä jostain syystä hylätään tarvitsemme toisenlaisen tarkenteen, eikä ainakaan nykyiset yläkäsitteet toimi tarkenteina. Tulostus=utskrift (maskinellt skapande) ja se on selvää että tämä yksikkömuoto vaatii tarkenteen. Tosin nykyinen tarkenne (joka on yläkäsite) on kyllä hämmentävä/sopimaton.

**Comment by jarmosaarikko** [comment]
tulosteet voidaan nähdä paperin roolina. Paperista syntyy tuloste, kun siihen liitetään tietoa.  Jos paperi vaikka rutistetaan ruttuun, se voi olla roska, jos siihen tehdään reikiä tai se taitellaan, se on taideteos, esim. origami.    Myös tiedosto voi olla tuloste.  Eli tuloste voidaan tehdä paperille tai tiedostoon.

**Comment by YSO-kokous** [comment]
Tulosteiden tulkitseminen roolina tai objektina jakaa hieman mielipiteitä. Säilytämme toistaiseksi nykyisen hierarkian. Jos ja kun vastaavia kiistakysymyksiä tulee lisää, näitä voisi koota yhteen ja konsultoida TSK:ta asiasta uudelleen.
