### ISSUE TITLE
perinne, traditio

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#849]
Näiden määritelmät (asiasanoina) ? Pitäisikö lisätä huomautuksia tms. (ellei ole mahdollista yhdistää)? Ruotsiksi (ja englanniksi?) nämä molemmat ovat "tradition". Nyt ruotsinkieliset vastineet hyvin kyseenalaisia, mutta jotta saadaan paremmat/selkeämmät vastineet täytyy varmistaa miten näitä on tarkoitus käyttää myös suomen osalta. Molemmilla on KT perinteet ja sama ryhmä, eli 50. 

Myös perimätieto olisi oikeastaan tradition ruotsiksi (nyt virheellinen "hävd").

Kielitoimiston sanakirja:

perinne: peritty tapa, käytänne t. tieto, perimä-, perinnäistapa t. -tieto, traditio. 
   Erik.  kansan muistitiedon varassa säilyttämästä henkisestä kulttuurista.

traditio: perinne, perimätieto, perinnäistapa; usein noudatettu tapa. 

perimätieto: sukupolvelta toiselle suullisesti periytynyt tieto, perinne, traditio

**Comment by YSO-kokous** [comment]
@mariaforsen tekee YSE-issuen.
