### ISSUE TITLE
Ketjumuotoisten maantieteellisten tarkenteiden esittäminen ontologiassa

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#85]
_From [mafors...@gmail.com](https://code.google.com/u/100004162283516840686/) on January 21, 2014 12:00:15_
1. What is to be changed/Mitä muutetaan Musiikkitalo 2. Why the change is needed/Miksi muutetaan On muitakin musiikkitaloja kuin Helsingin. On kai linjauksia vastaan että jättää avoimeksi monimerkityksellisen sanan tarkoitus..? Huomautuksia käyttäjä ei aina näe, eivätkä varmaan ole "koneellisesti luettavissa". Ruotsiksi on Helsingfors suluissa lisätty jo tesauruksen puolella. Esim. kirkkojen kohdalla on samalla lailla sulkuja lisätty. 3. Realized changes/Toteutetut muutokset

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=82_

**Comment by MikkoAleksanteri** [comment]
MARCiin pohjautuva ketjutusmalli ei tosiaan ole järkevä tai käyttökelpoinen ontologiassa. Jos kuitenkin MARCin ratkaisun koneluettavuus halutaan säilyttää, voitaisiin miettiä muitakin vaihtoehtoja kuin sulkutarkenne. Näin data saataisiin palautettua takaisin MARCiksi ilman häviötä. Vaihtoehdot ontologian puolella nähdäkseni ovat siis:

1. Sulkutarkenne (jolloin rakenteellisuus ja koneluettavuus menetetään)
2. Joku uusi property, esim. dublin coren Spatial? ks. http://dublincore.org/documents/dcmi-terms/#terms-spatial

**Comment by osma** [comment]
Käännösten lisääminen Skosmoksessa on tässä issuessa: https://github.com/NatLibFi/Skosmos/issues/560

**Comment by osma** [comment]
Lisäksi YSA-URI pitää resolvoida labeliksi: https://github.com/NatLibFi/Skosmos/issues/572

**Comment by MikkoAleksanteri** [comment]
Päätettiin käyttää dct:Spatial ominaisuutta, viitataan YSAn (jatkossa YSO-paikat) maantieteellisiin käsitteisiin. 

Kaikki maantieteellisen tarkenteen sisältävät ketjut on nyt muutettu sulkutarkenteiksi ja vastaava maant. käsite lisätty dct:Spatial-ominaisuutta käyttäen.
