### ISSUE TITLE
virkailijavaihto

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#850]
Onko tämä termi aivan välttämätön? Ei sanakirjoissa/sanastoissa, Googlessa vain vähän, Melinda 13, Eduskunnan sanastossa ei ollenkaan, mutta kyllä virkamiesvaihto KÄYTÄ henkilövaihto. Vaatii jonkinlainen tarkenne ruotsiksi. Myös virkamiesvaihto joka on ok ja =tjänstemannautbyte.

**Comment by YSO-kokous** [comment]
@mariaforsen tekee YSE-issuen. Lisäkysymys: mikä on virkailijavaihdon ja työkierron ero?
