### ISSUE TITLE
ammattinimike muuttunut

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#851]
- lääkintävoimistelijat (sjukgymnaster) - fysioterapeutit (fysioterapeuter): edeltäjä-seuraaja?
- hammashuoltajat (tandhygienister) - suuhygienistit (munhygienister): edeltäjä-seuraaja olisi suomeksi ok, http://w3.verkkouutiset.fi/arkisto/kotimaa/76112.html
- kuvaamataidonopettajat (teckningslärare) - kuvataideopettajat (bildkonstlärare): edeltäjä-seuraaja?

**Comment by mirmaid** [comment]
- kunnanlääkärit (kommunalläkare) - terveyskeskuslääkärit (hälsocentralläkare): Laki yleisestä sairaanhoidosta tuli voimaan jo vuonna 1943. Uuden lain edellyttämänä jokaisessa kunnassa tuli olla kunnanlääkäri ja useamman kunnan yhteinen aluelääkäri. -- Uuden lain myötä [1972] kunnanlääkärijärjestelmä purettiin ja jokainen kunta velvoitettiin perustamaan terveyskeskus yksin tai yhdessä naapurikuntien kanssa. Terveyskeskuksissa yhdistettiin ”saman katon alle” yleislääkärijohtoiset terveyspalvelut (esimerkiksi yleislääkärin vastaanotto, neuvola, hammashoito, pitkäaikaissairaiden osastohoito). http://opinnot.internetix.fi/fi/muikku2materiaalit/lukio/te/te3/3_suomalainen_hoitojarjestelma_2000-luvulla/3.4_historian_siipien?C:D=1819528&m:selres=1819528

**Comment by mirmaid** [comment]
- kanta-aliupseerit (stamunderofficerare) - toimiupseerit (befattningsofficerare) - opistoupseerit (institutofficerare): edeltäjä-seuraaja?
- sotaväen päälliköt (befälhavare för militären) - puolustusvoimain komentajat (kommendörer för försvarsmakten): edeltäjä-seuraaja?

**Comment by mirmaid** [comment]
- värvätyt (värvade) - sotilasammattihenkilöt (yrkesmilitärer): wikipedian mukaan nykyään aliupseerit. Sotilashenkilöstön termit voisi varmistaa Esalta.

**Comment by YSO-kokous** [comment]
Edeltäjä-seuraaja-suhteet seruaaville: 
lääkintävoimistelijat (sjukgymnaster) - fysioterapeutit (fysioterapeuter)
hammashuoltajat (tandhygienister) - suuhygienistit (munhygienister)
kuvaamataidonopettajat (teckningslärare) - kuvataideopettajat

RT suhde seuraavalle:
kunnanlääkärit (kommunalläkare) - terveyskeskuslääkärit (hälsocentralläkare)

Konsultoidaan Esa Hämäläistä sotilastermeistä.

**Comment by mirmaid** [comment]
Sotilastermeille luotu edeltäjä-seuraaja-suhteet Esan kannanoton mukaan. Aliupseerit-käsite vähän ongelmallinen, haluaako joku tutkia lisää vai jätetäänkö nykyinen ratkaisu?

**Comment by YSO-kokous** [comment]
Ei muita toimenpiteitä.
