### ISSUE TITLE
moduulit

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#852]
YSAssa ryhmät 00, 37 ja 91. YSOssa vain 37 ja 91, YK tekniset objektit (abstraktit objektit). Melindassa käytetty vapaammin, mm. _Kohti kokonaisvaltaisempaa opetusta: moduuliopetuksen ensitoteutukset Lepaalla_, _Kvasikonformikuvaukset: yhtäpitäviä määritelmiä_ (matematiikan gradu), _A guide to morphosyntax-phonology interface theories: how extra-phonological information is treated in phonology since Trubetzkoy’s Grenzsignale_, _GSM-verkon kautta tapahtuvan laiteohjauksen tekniikka_ - tämä on varmaan tekninen objekti (tai järjestelmä), mutta ei ryhmää 37/91.

**Comment by mirmaid** [comment]
Mitähän tälle olisi järkevintä tehdä?

**Comment by satuniininen** [comment]
Melindassa:

moduulit 150 kertaa
modulaarisuus 41 kertaa
moduulirakentaminen 9 kertaa
moduulit + modulaarisuus 12 kertaa

_Moduulit_-käsitteen käyttö Melindassa on paljon laajempaa, kuin hierarkia ja ryhmät antavat ymmärtää. Lisäksi _moduulit_ ja _modulaarisuus_ esiintyvät hyvin samantyyppisissä aineistoissa ja eikä kuvailukäytön pohjalta voi tehdä selvää eroa niiden välille. Näiden lisäksi sanastoon on erotettu _moduulirakentaminen_ omaksi täsmällisemmäksi käsitteekseen.

Ehdotus: 

- Yhdistetään **moduulit** KÄYTÄ **modulaarisuus**, ohjaustermeiksi _moduulit_ ja mahdollisesti _moduulirakenteet_
- Käydään läpi _moduulit_-käsitteellä kuvaillut ja ohjataan ne --> _modulaarisuus_ tai _moduulirakentaminen_. Sen jälkeen mietitään ratkaisu ylijääville. Tarkistetaan samalla hierarkia ja ryhmät.

**Comment by YSO-kokous** [comment]
@satuniininen tekee YSE-ehdotuksen.

**Comment by satuniininen** [comment]
https://github.com/Finto-ehdotus/YSE/issues/6662
