### ISSUE TITLE
arvostelmat

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#853]
YSAssa ryhmät 00 ja 02, huomautus: Sanalla on kaksi merkitystä: 1) Arvostelu. 2) Logiikassa väite, joka voi olla tosi tai epätosi. Allärs: propositioner (logik). YSOssa vain ryhmä 02. Melindan viitteistä (10) kaikki paitsi yksi ovat filosofiaa tai taidefilosofiaa/estetiikkaa.

**Comment by mirmaid** [comment]
Ryhmä kannattaa rajata 02:ksi ja poistaa huomautus, mutta tarvitaanko sulkutarkennetta, ja jos tarvitaan, onko logiikka hyvä? Sopiiko se myös kun kyse on estetiikasta: http://tieteentermipankki.fi/wiki/Estetiikka:esteettinen_arvostelma?

**Comment by mariaforsen** [comment]
Ei se ainakaan ruotsin osalta.
