### ISSUE TITLE
Taide-/taiteet-käsitteiden LCSH-siltaukset

### ISSUE THREAD

**Issue by satuniininen** [NatLibFi/Finto-data#854]
Muutama hankala siltaustapaus keskusteltavaksi:

YSOssa on käsitteet _taide_ ja _taiteet_. LCSHssa vastaavasti: 
Art NOTE:  Here are entered general works on the visual arts.
Arts NOTE: Here are entered works on the arts in general, including the visual arts, literature, and the performing arts.

Näistä siltaisin LCSHn art-käsitteen closeMatchillä YSOn kuvataiteisiin  ja arts-käsitteen broadMatchillä sekä taiteeseen että taiteisiin.

LCSH jatkaa art/art-jaottelua myös alakäsitetasolla, mutta hierarkia ei aina kerro, onko kyseessä jaottelu kuvataiteisiin ja taiteisiin yleensä vai löytyykö taustalta jokin muu jakolinja. 
Esim:
Art, Byzantine: http://id.loc.gov/authorities/subjects/sh85007589.html
Arts, Byzantine: http://id.loc.gov/authorities/subjects/sh90000478.html
vrt. YSOn bysanttilainen taide

Tämän ja muut vastaavat voisi sillata kahdella narrowMatchillla? Melinda-käytön perusteella YSAn bysanttilaisen taiteen ohessa käytetään molempia LCSH-käsitteiä.

**Comment by YSO-kokous** [comment]
Sillataan art-käsite closeMatchillä YSOn kuvataiteisiin ja Art, Byzantine & Arts, Byzantine narrowMatchilla bysanttilaiseen taiteeseen.

Satu kysyy Osman näkemystä Arts-käsitteen siltaamisesta closeMatchilla taide ja taiteet -käsitteisiin.

**Comment by osma** [comment]
Keskusteltiin tästä @satuniininen kanssa, minusta se closeMatch on OK silloin kun ei pysty selkeästi määrittelemään, että kysymyksessä on hierarkkinen merkitysero.

**Comment by YSO-kokous** [comment]
Lähdetään siitä, että closeMatch-suhteen käyttö yhdestä käsitteestä useampaan on ok. Satu tekee pienen testiotoksen ja käsitellään vielä uudelleen, jonka jälkeen lopullinen päätös.

**Comment by osma** [comment]
Oikeastaan kai useammasta käsitteestä yhteen, jos siis tarkastellaan suuntaa YSOsta LCSH:een

**Comment by satuniininen** [comment]
Ideaalitilanne olisi yhtenäinen linjaus molempiin suuntiin, eli tällöin myös YSOn bysanttilainen taide siltautuisi closeMatch-suhteella käsitteisiin Art, Byzantine ja Arts, Byzantine.

**Comment by satuniininen** [comment]
Jatketaan käsittelyä Google docsissa: https://tinyurl.com/y935uhla

**Comment by YSO-kokous** [comment]
Toteutetaan taulukon mukaiset muutokset.
