### ISSUE TITLE
Muutos käsitteessä: uusi käsite ja uusi URI vai vanha käsite ja vanha URI?

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#856]
Erityisesti koostekäsitekokonaisuuksissa tapahtuneiden muutosten jälkeen on keskusteltu käytännöistä käsitteen muuttuessa. On nostettu esiin, että mikäli käsite muuttuu merkitykseltään erilaiseksi, kyse ei enää ole samasta käsitteestä. Näin ollen pitäisi luoda uusi käsite eikä muokata nykyistä. Ks. keskustelu aiheesta:
https://github.com/NatLibFi/Finto-data/issues/810

Vastaan on nyt tullut joukko toisistaan poikkeavia tapauksia, joissa käsite muuttuu tavalla tai toisella. Emme ole vielä määritelleet sitä, milloin käsite muuttuu siinä määrin, että on syytä tehdä uusi käsite ja milloin ei. Alla on esimerkkitapausten käsitteen muutoksista. Näiden kautta olisi hyvä muodostaa mahdollisimman selkeä linjaus asiaan liittyen ja tämän voisi lisätä myös asiakaswikin kehityslinjauksiin.

Näihin olisi hyvä saada myös kommentti TSK:lta, joka alunperin nosti ongelman esiin. @kseppala

**vaasit**
- http://finto.fi/yso/fi/page/p21035
- käsite on saanut YSAn puolella sulkutarkenteen "vaasit (antiikki)"
- käsite on saanut aiemmin (vuoden 2012 jälkeen) myös huomautuksen "Tarkoittaa antiikin ajan astioita ja ruukkuja. Materiaalina voi olla kivi, lasi tai savi."

**viritys**
- http://finto.fi/yso/fi/page/p9141
- käsite kuuluu ryhmään 89 Musiikki
- käsite jaettu YSAn puolella: "viritys (moottorit)" ja "viritys (soittimet)". YSOn käsite vastaa YSAn jälkimmäistä, eli tätä kautta käsitteelle on tulossa uusi sulkutarkenne.

**kaniinit**
- http://finto.fi/yso/fi/page/p673
- käsite muuttumassa YSAn kautta muotoon "kani", eli suvusta lajiksi.
- huom! "Kaniini on sukunsa (Oryctolagus) ainoa laji."

**romanssit (teokset)** ja **romanssit (sävellykset)**
- http://finto.fi/yso/fi/page/p7452
- romanssit (sävellykset) on deprekoitu käsite
- tämä jako on nyt otettu myös YSAan muodossa "romanssit (kirjallisuudenhistoria)" ja "romanssit (musiikki). termit pitäisi näin ollen vaihtaa. ja "romanssit (sävellykset)" pitäisi palauttaa henkiin.

**Comment by YSO-kokous** [comment]
Katri Seppälä @kseppala kommentoi tapauksia seuraavasti:

> VAASIT

_Koska käsitteessä on jo aiemmin ollut huomautus, joka on rajannut käyttöä ja sulkutarkenne vain tuo aiemmin huomautuksessa olleen tiedon myös osaksi labelia, käsite ei tarkenteen lisäämisellä muutu._

> VIRITYS

_Itse viritys-termi ja yläkäsite ylläpitävä muuttaminen jättävät avoimeksi, minkä virittämisestä on kyse. Tällaisessa tapauksessa pitäisi miettiä, voidaanko käsitteen aiheryhmää pitää riittävänä rajaamaan
käsitesisältöä, kun yläkäsite ei sitä tee, eikä käsitteellä ole määritelmää tai huomautusta. Ehkä pitäisi tarkistaa, onko käsitettä osattu käyttää aiheryhmän tarkoittamalla tavalla? Jos käsite on jo aiemmassa YSO-käytössä rajautunut musiikkiin, se ei labelin tarkenteen myötä muutu._

> KANIINIT

_Laji ja suku ovat eri käsitteitä, vaikka molempiin voitaisiin viitata samalla termillä._

> ROMANSSIT (TEOKSET) ja ROMANSSIT (SÄVELLYKSET)

_Tämä on osittain samanlainen tapaus kuin viritys, sillä romanssit (teokset) -käsitteet osalta vain aiheryhmätieto osoittaa kyseessä olevan kirjallisuuteen liittyvä käsite (teoksiahan on muuallakin kuin
kirjallisuudessa, eikä yläkäsite kulttuuriset objektit rajaa muita kulttuurin aloja pois). Jos voidaan katsoa, että aiheryhmä on riittävä käsitteen käytön rajaamiseen, romanssit (teokset) ja romanssit (kirjallisuuden historia) ilmeisesti ovat yksi ja sama käsite vai eroaako kirjallisuuden historia -rajaus kirjallisuus-aiheryhmän rajauksesta? Jos romanssit (sävellykset) ja romanssit (musiikki) ovat yksi ja sama käsite, poistetun käsitteen URI pitäisi ottaa uudelleen käyttöönotetulle käsitteelle._

**Comment by tpalonen** [comment]
Ks. myös https://github.com/NatLibFi/Finto-data/issues/804

**Comment by mirmaid** [comment]
Aiheesta on jo linjattu sivulla https://www.kiwi.fi/display/Finto/YSO-pohjaisten+ontologioiden+yhteiset+kehityslinjaukset.
