### ISSUE TITLE
Oppilaitosten nimissä tapahtuneet muutokset

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#857]
Laki ammatillisista oppilaitoksista 487/1987 http://www.finlex.fi/fi/laki/alkup/1987/19870487 on kumonnut joukon aikaisempia lakeja, ja oppilaitosten nimityksissä on tapahtunut muutoksia niin että YSAssa on uusi ja vanha nimitys. 

Onko näissä tarve yhdistää jos ruotsiksikin on kaksi eri termiä? Issue on tehty kotitalousoppilaitoksista, https://github.com/Finto-ehdotus/YSE/issues/5326, https://github.com/NatLibFi/Finto-data/issues/756.

kotiteollisuusoppilaitokset / hemslöjdsläroinrättningar > käsi- ja taideteollisuusoppilaitokset / läroinrättningar för hantverk och konstindustri

sairaanhoito-oppilaitokset / sjukvårdsläroanstalter > terveydenhuolto-oppilaitokset / hälsovårdsläroinrättningar

**Comment by mirmaid** [comment]
kotiteollisuusoppilaitokset > käsi- ja taideteollisuusoppilaitokset
sairaanhoito-oppilaitokset > terveydenhuolto-oppilaitokset

**Comment by mirmaid** [comment]
ammattikoulut > ammattioppilaitokset (nimitys ruotsiksi pysynyt samana?)

**Comment by mirmaid** [comment]
ammattikurssikeskukset > ammatilliset aikuiskoulutuskeskukset

**Comment by mirmaid** [comment]
avoin korkeakoulu > avoin yliopisto

**Comment by mirmaid** [comment]
ammattikoulujen opettajaopistot > ammatilliset opettajakorkeakoulut

**Comment by mariaforsen** [comment]
YSA/Allärs: 
ammattikoulut=yrkesskolor
ammattioppilaitokset= -  (yrkesundervisningsanstalter finlexissä)
ammatilliset oppilaitokset=yrkesläroanstalter (näin finlexissäkin)

Onko todella tarkoituksenmukaista että käyttäjä joutuu erottelemaan näitä ja kuinka hyvin se onnistuu kiireessä? 

Kielitoimiston sanakirja: 
ammattikoulu: ammattioppilaitoksesta
ammattioppilaitos: ammatillista peruskoulutusta antava oppilaitos. 
ammatillinen oppilaitos: ei löydy

Finlexissä näköjään oma terminologiansa ja omanlaiset käännöksensä myös (sellaisia ei yleisessä käytössä). Olisiko mahdollista yhdistää jotenkin? Jos muutoksia ei tehdä, on ehkä parasta että laitamme ruotsin vastineet Finlexin mukaan. Ei ehkä paras mahdollinen ratkaisu "yleiseen" sanastoon (vaikka lakikielessä voi olla hyväkin).

**Comment by mirmaid** [comment]
Toteutettu edeltäjä-seuraaja-suhteet, mutta mitä (vai kaikki) halutaan silti yhdistää ja mikä olisi siinä tapauksessa paras päätermiksi?

**Comment by satuniininen** [comment]
_Ammattiliset oppilaitokset_ on YSOssa tulkittu merkitykseltään laajemmaksi siten, että se kattaisi myös myös esim. ammattikorkeakoulut. En kuitenkaan löytänyt mitään tyhjentävää määritelmää, joka tukisi tätä tulkintaa. 

Opetushallinnon sanasto tarjoaa englanniksi: 
ammatillinen oppilaitos = vocational institution
ammattikoulu = ei mitään
ammattioppilaitos = ei mitään, mutta monialainen ammattioppilaitos = multi-disciplinary vocational institution

Näiden kolmen osalta kannattaisin yhdistämistä. Päätermiksi _ammattioppilaitokset_ tai _ammatilliset oppilaitokset_, mieluiten ehkä jälkimmäinen, koska se kuulostaa eniten yleiskieliseltä, eikä vaadi välttämättä muutoksia jokaisen koulutusuudistuksen jälkeen. Sitä on myös käytetty kirkkaasti eniten Melindassa.

**Comment by mariaforsen** [comment]
Kannatan yhdistämistä. Olisiko kuitenkin hyvä pitää erillään nämä ja ammattikorkeakoulut, esim. lisäämällä huomautuksen? Käyttäjien kannalta ja muutenkin.

**Comment by mirmaid** [comment]
YSE-ehdotus tehty ammattikouluista. Lisäksi siis vielä

ammattikurssikeskukset / yrkeskurscentraler > ammatilliset aikuiskoulutuskeskukset / yrkesutbildningscentrer för vuxna

avoin korkeakoulu / öppna högskolan > avoin yliopisto / öppna universitetet. YSOssa näillä on nyt LT-ST-suhde.

ammattikoulujen opettajaopistot / lärarinstitut för yrkesskolor > ammatilliset opettajakorkeakoulut / yrkespedagogiska lärarhögskolor

kotiteollisuusoppilaitokset / hemslöjdsläroinrättningar > käsi- ja taideteollisuusoppilaitokset / läroinrättningar för hantverk och konstindustri

sairaanhoito-oppilaitokset / sjukvårdsläroanstalter > terveydenhuolto-oppilaitokset / hälsovårdsläroinrättningar

**Comment by YSO-kokous** [comment]
@satuniininen ja @mariaforsen tutkivat, onko edellä mainituissa käsitteitä, jotka voisi yhdistää ja tekevät YSE-ehdotuksen näistä. Issuen voi sulkea tämän jälkeen.

**Comment by satuniininen** [comment]
Minun puolestani nämä voivat jäädä erilleen. Jatkon kannalta kuitenkin toivoisin, että oppilaitosten ja koulutusalojen nimiä otettaisiin sanastoon entistä varovaisemmin, sillä ne ovat usein lyhytikäisiä ja alttiita muuttumaan.

**Comment by YSO-kokous** [comment]
Ei lisätoimenpiteitä.
