### ISSUE TITLE
koulutus-termeissä tapahtuneet muutokset

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#858]
Halutaanko yhdistää myös silloin kun ruotsinkielinenkin termi on vaihtunut?

**Comment by mirmaid** [comment]
ammattikoulutus > ammatillinen koulutus

**Comment by mirmaid** [comment]
keskiasteen koulutus > toisen asteen koulutus

**Comment by mirmaid** [comment]
työllisyyskoulutus > työvoimakoulutus

**Comment by YSO-kokous** [comment]
ammattikoulutus / yrkesutbildning > ammatillinen koulutus / yrkesinriktad utbildning. Nyt LT-ST-suhde sekä YSAssa että YSOssa. > tehdään ehdotus yhdistämisestä

keskiasteen koulutus / mellanstadieutbildning > toisen asteen koulutus / andra stadiets utbildning > edeltäjä-seuraaja

työllisyyskoulutus / sysselsättningsutbildning > työvoimakoulutus / arbetskraftsutbildning > edeltäjä-seuraaja

**Comment by mirmaid** [comment]
ammattikoulutus / yrkesutbildning > ammatillinen koulutus / yrkesinriktad utbildning. Nyt LT-ST-suhde sekä YSAssa että YSOssa. > tehdään ehdotus yhdistämisestä

- yhdistäminen hyväksytty YSA-kokouksessa

**Comment by mirmaid** [comment]
Toteutettu edeltäjä-seuraaja-suhteet, mutta halutaanko myös näitä silti yhdistää ja mikä olisi siinä tapauksessa paras päätermiksi? @mariaforsen

**Comment by YSO-kokous** [comment]
Ei vaadi toimenpiteitä.
