### ISSUE TITLE
subjektiivisuus, subjektiviteetti

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#860]
Molemmat luokassa 02 Filosofia, ja ensimmäinen myös luokassa 56 Tiede. Tutkimus. YSAssa (mutta ei YSOssa) on subjektiviteetti-termillä huomautus: Subjektiviteetilla tarkoitetaan ihmisen arvomaailmaa, arvioita omasta elämästään, tärkeitä elämänalueita jne. Huom. Subjektiviteetti ei löydy MOTista, TEPAsta tms. sanakirjoista tai Wikipediastakaan. Vastaavaa erotusta ei ole ruotsiksi. 

Olen luomassa (parempia) tarkenteita ruotsiksi. YSAn huomautuksen perusteella voisi mahdollisesti toisella olla tarkenne psykologia ja ensimmäisellä filosofia, mutta se ei myöskään toimi nykytilanteessa kun molemmat ovat ryhmässä 02 ja Melindassakin käytetty sekavasti. Ovatko molemmat varmasti tarpeen ja jos on, niin olisiko mahdollista tehdä eron selvemmäksi jollain tavalla?

**Comment by mariaforsen** [comment]
Melindassa tosiaan hyvin monenlaista aineistoa, onko mahdollista erotella järkevästi, vai onko niissä kaikissa jokin yhdistävä tekijä merkityksessä? Ruotsiksi (ja esim. SAOssa) pelkkä subjektivitet, mutta jos merkitykset eritellään selkeästi, on tietty mahdollista luoda tarkenteita. 
Vrt. esim.
Objectivity and subjectivity in social research / Gayle Letherby, John Scott and Malcolm Williams 
Yhteisö : filosofian näkökulmia yhteisöllisyyteen / Jussi Kotkavirta ja Arto Laitinen (toim.
Modality, subjectivity, and semantic change : a cross-linguistic perspective / Heiko Narrog.
Phenomenology and embodiment : Husserl and the constitution of subjectivity / Joona Taipale.
Itsenäisyyden ja avun käytön jännitteessä : laaja-alaisen toimintakyvyn subjektiivinen kokeminen ja hallinnan keinot CP-vammaisella aikuisella kuntoutuksen viitekehyksessä / Elina Takkinen.

**Comment by satuniininen** [comment]
Myöskään työhuoneen käsikirjaston _Psykologian sanasto_ ja _Filosofian sanat ja konseptit_ eivät kumpikaan tunne subjektiviteettia.  Vastaukset.fi sen sijaan määrittää seuraavasti: _Subjektiviteetti on filosofinen käsite, joka littyy tietoisuuten, hallintoon, ihmisyyten, todellisuuteen ja totuuteen. Se on sosiaalinen tila, joka ilmenee yhteiskunnassa lukemattomien vuorovaikutusten kautta._

Kuten Maria jo mainitsi, kuvailukäyttö on sekavaa. Jos jotain punaista lankaa yrittää löytää, niin ehkä subjektiivisuus viittaa enemmän yksilön ominaisuuteen ja subjektiviteetti jonkinlaiseen tilaan, jonka raameissa subjektiivisuutta tai subjektiivista toimintaa toteutetaan. Koska täsmällisiä kielivastineita ei myöskään ole löydettävissä, kallistuisin varovaisesti yhdistämisen kannalle.

**Comment by YSO-kokous** [comment]
Yse-ehdotus: poistataan subjektiviteetti ja korvataan kuvailussa käsitteillä subjekti (filosofia) ja subjektiivisuus. Myös uudelleenohjaus molempiin.

**Comment by mirmaid** [comment]
Uudelleenohjaus tehty vain käsitteeseen subjekti (filosofia), varmaankin tarkoituksella (?)
