### ISSUE TITLE
sotilasammattihenkilöt

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#861]
Miten tulkita? Tämä on ilmeisesti tarkalta merkitykseltään aliupseerina tai määräaikaisena aliupseerina palvelevan palvelusarvo (ks. http://www.finlex.fi/fi/laki/alkup/2006/20061355 ) mutta näköjään tulkittu sekä Allärsissa että osittain Melindassakin yleisempänä terminä (henkilö joka ammatiltaan on sotilas/palvelee armeijassa..)

Ks. Melindaa, esim.: Ammattien ja ansaitsemisen etiikka : näkemyksiä ammattien, johtamisen ja liike-elämän arvoista / toimittanut Timo Airaksinen ; Nainen matkalla sotilasammattiin : näkemyksiä Maanpuolustusopistolta / Niina Jalovaara ; Näkyvä ja näkymätön kuri : tieto, valta ja vaikuttaminen sotilasdiskurssissa / Aki-Mauri Huhtinen jne. 

Määritelläänkö ja miten? Sen jälkeen päätetään mitä korjauksia tehdään ruotsiksi. 

Huom. sanastossa myös sotilashenkilöt ja sotilashenkilöstö.

**Comment by YSO-kokous** [comment]
Tarkennetaan huomautusta @mirmaid . Edeltäjä-seuraaja-suhteet ovat tulossa YSAn kautta.

**Comment by YSO-kokous** [comment]
Hyväksytään
