### ISSUE TITLE
sotapelit

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#862]
Yläkäsite nyt digitaaliset pelit. Näitä on kyllä muitakin kuin digitaalisia, olisiko syytä muuttaa yläkäsitteeksi esim. pelit, pelit sisällön mukaan (kuten esim. seikkailupelit, taistelupelit, urheilupelit..)?

**Comment by tpalonen** [comment]
Kannatan yläkäsitteeksi pelit sisällön mukaan.

**Comment by YSO-kokous** [comment]
Yläkäsitteeksi pelit sisällön mukaan.
