### ISSUE TITLE
Alkuaineet-käsitteen alakäsitejoukon siistiminen

### ISSUE THREAD

**Issue by satuniininen** [NatLibFi/Finto-data#863]
Alkuaineiden alta pitäisi siivota pois käsitteet, jotka ovat muuta kuin alkuaineita.

Tällä hetkellä sieltä löytyy virheellisesti isotoopit, joka ei itsessään ole alkuaine. Samoin hiilen alakäsite aktiivihiili.

**Comment by satuniininen** [comment]
Ongelmallisia käsitteitä:
epämetallit
halogeenit
jalokaasut
isotoopit
aktiivihiili
metallit
alkalimetallit
harvinaiset maametallit
jalometallit
platinametallit
kevytmetallit
raskasmetallit

**Comment by satuniininen** [comment]
Ratkaisuehdotus:
Siirretään ongelmalliset alkuaineryhmien nimet soveltuvaan paikkaa _aine-_käsitteen alle. Kaikille yksittäisille alkuaineille monihierarkia sekä _alkuaineet_-käsitteeseen, että omaan alkuaineryhmäänsä. 

epämetallit LT aine
halogeenit LT aine
jalokaasut LT kaasut
isotoopit LT aine
aktiivihiili LT aine
metallit LT aine
alkalimetallit  LT metallit
harvinaiset maametallit LT metallit
jalometallit LT metallit
platinametallit LT metallit
kevytmetallit LT metallit
raskasmetallit LT metallit
puolimetallit LT metallit/aine?

Huom. _torium_  on tällä hetkellä ainoana suoraan alkuaineiden alla, lisätään toiseksi yläkäsitteeksi metalli.

**Comment by YSO-kokous** [comment]
Päätös:
aktiivihiili LT aine käytön mukaan + RT hiili
isotoopit LT aine rakenteen mukaan + RT alkuaineet

Muiden asioiden osalta: @mirmaid tutkii

**Comment by mirmaid** [comment]
Ei tehdä muita muutoksia. Alkuaineryhmien voidaan katsoa viittaavan ryhmään sisältyviin alkuaineisiin.
