### ISSUE TITLE
saumat

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#864]
On ruotsiksi sömmar, mutta tämä kattaa vain kankaiden yms. saumat (eli merkitys 1a). Melindassa käytetty paljon myös muista (1b=ruotsiksi mm. skarv..) Onko mahdollista jakaa tms.? Liitokset=fogar. 

Kielitoimiston sanakirja: 
1. kahden reunan liitos(kohta).
a. kankaiden, nahkojen, muovien, levyjen yms. liitoksista. Takin, kenkien saumat. Koneella ommeltu sauma. Edestakais-, katesauma. Peltikaton saumat. Hitsi-, kuuma-, valusauma. Ratketa, irrota saumoistaan.
b. rakenneosien välinen rako (joka us. täytetään tiivistys- t. sideaineella). Sillan liikuntasaumat. Rakennuslevyjen saumat. Saumoistaan vuotava vene. Saumojen paikkaaminen, tiivistäminen.

**Comment by YSO-kokous** [comment]
@mariaforsen tekee YSE-issuen. YSO-kokous ehdottaa käsitteen jakamista kahtia.

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/6495
