### ISSUE TITLE
ruumis YK ruumiinosat

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#865]
Ruumis yläkäsite ruumiinosat - hierarkiavirhe ainakin ruotsiksi.

**Comment by YSO-kokous** [comment]
Päätös:
ruumis YK orgaaniset objektit
ruumiinosat partof ruumis

Pohditaan toisessa yhteydessä, tulisiko ruumiinosat-käsitteen alakäsitteille lisätä myös partof ruumis vai periytyykö tämä ominaisuus yläkäsitteensä kautta näille käsitteille konepäättelyssä.
