### ISSUE TITLE
aine käytön mukaan - pitäisikö siirtää rooli-hierarkiaan?

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#866]
Aine-käsitteen alla oleva ryhmittelevä käsite "aine käytön mukaan" muodostaa kokonaisuuden, joka tuntuisi suurelta osin sopivan paremmin rooli-hierarkiaan. Mm. juomat, raaka-aineet, ruoat löytyvät täältä. Nämä vertautuvat vahvasti "käyttöön liittyvä rooli"-käsitteen alta löytyviin käsitteisiin kuten eväät, korvikkeet, saaliit.

http://finto.fi/yso/fi/page/p746

EHDOTUS: "aine käytön mukaan"-kokonaisuus olisi hyvä käydä läpi ja siirtää rooli-hierarkiaan paremmin kuuluvat sinne.

Esim. "hunaja" käsitteellä ei voi tällä hetkellä olla yläkäsitteenä sekä makeutusaineet että mehiläistuotteet koska nämä sijaitsevat eri päähaaroissa.  Ehdotetun siirron jälkeen monihierarkia olisi mahdollinen.

**Comment by mirmaid** [comment]
Liittyy myös tähän työstöön: https://github.com/NatLibFi/Finto-data/issues/575
