### ISSUE TITLE
sähkösaostus

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#867]
On ollut ongelmalistalla alusta asti, eli ei ollenkaan käännöstä ruotsiksi. Olen konsultoinut alan asiantuntijoita: ruotsiksi eri termi riippuen onko kyseessä metallin pinnoitus vai jäteveden puhdistaminen. 

-Jäteveden puhdistaminen= elektrokoagulation/elektroflockning eng. electrocoagulation 
-Metallin pinnoitus= elektrolytisk utfällning eng. electro-deposition? joka on nyt eng. vastineena YSOssa

Ryhmässä 09 ja 30. 

Mihin näistä tämä asiasana viittaa? Melindassa käytetty eniten metallin pinnoituksesta, mutta myös jätevesien puhdistusmentelmänä. Merkitys täytyy selventää ennen kuin päätämme ruotsinkielisestä vastineesta.

**Comment by satuniininen** [comment]
Sama ongelma englanniksi, jätevesien puhdistusmenetelmä on _electrocoagulation_, metallin pinnoitus  _electrodeposition_ tai  _electroplating_.

**Comment by satuniininen** [comment]
Melindassa YSA-asiasanana viisi kertaa, joista yksi käsittelee jätevesiä ja neljä metallien pinnoitusta. Jaetaan?

**Comment by YSO-kokous** [comment]
Tehdään YSE-issue käsitejaosta. @satuniininen
