### ISSUE TITLE
kukat (koristekasvit)

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#868]
Kaikkia kukkia ei suinkaan käytetä koristekasveina (lähinnä rooli). Löytyisikö parempi sulkutarkenne? Melindassa kukat asiasanana esim. tämäntyyppisillä kirjoilla: Suomen luonto : lasten suuri luontokirja / Viljami Ovaskainen ; Neidonkenkä ja kiirunankello : tarinoita pohjoisen luonnosta / Jussi Viitala, Lauri Korpi, Osmo Kautto ; Understanding flowers and flowering : an integrated approach / Beverley Glover.

**Comment by YSO-kokous** [comment]
Päätös:

"kukat (koristekasvit)" muutetaan muotoon "kukat (kasvit)" ja muutetaan yläkäsitteeksi kasvit. Lisätään sekä tälle että "kukka (kasvinosat)" käsitteelle tarkentava huomautus. "kukat (kasvit)" tulkitaan YSOssa kaikiksi sellaisiksi kasveiksi, jotka kukkivat.

Lisäksi tehdään YSE-ehdotus kasvinosat-hierarkiassa olevista yksikkömuotoisista käsitteistä: pitäisikö nämä muuttaa monikkoon?

Tuomas hoitaa.
