### ISSUE TITLE
metsätilat, metsätaloustilat

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#870]
Onko merkittävästi eri asioita? Ruotsiksi nyt ongelmalistalla. MOT, TEPA jne. ei tunne metsätaloustilaa, eikä Google anna paljoa (lähinnä Finto..)

**Comment by YSO-kokous** [comment]
@mariaforsen tehdään YSE-ehdotus käsitteiden yhdistämisestä. Pyydetään kommenttia Päivi Lipsaselta.
