### ISSUE TITLE
setlementtiliike

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#871]
Onko yläkäsite "uskonnolliset liikkeet" liian rajaava? Lyhyen opiskelun jälkeen liikkeen toiminta ei vaikuta ensisijaisesti uskonnolliselta. Sopiva yläkäsite voisi olla organisaatiot (vrt. AA-liike, Arts & Crafts -liike) tai yhteiskunnalliset liikkeet (vrt. hippiliike).

https://fi.wikipedia.org/wiki/Setlementtiliike

**Comment by jarmosaarikko** [comment]
Samaa mieltä Tuomaksen kanssa. "Suomen Setlementtiliitto on poliittisesti ja uskonnollisesti sitoutumaton sivistys- ja sosiaalista työtä tekevä kansalaisjärjestö sekä setlementtiyhdistysten keskusjärjestö."  Joten ei ole uskonnollinen liike.  
YK "organisaatiot (järjestelmät)"  Ryhmät 73 ja 57.  RK  "aluetyö, sosiaalipalvelut, koulutuspalvelut"

**Comment by YSO-kokous** [comment]
YK yhteiskunnalliset liikkeet. @mirmaid tutkii ryhmät.
