### ISSUE TITLE
lämpötalous

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#872]
YSOssa on lämpötalous (aineenvaihdunta) ja lämpötalous (energiatalous). YSAssa tehty lämpötalous (aineenvaihdunta) KÄ lämmönsäätely.

**Comment by YSO-kokous** [comment]
Deprekoidaan "lämpötalous (aineenvaihdunta)" ja tälle uudelleenohjaus > lämmönsäätely. Poistetaan sulkutarkenne käsitteeltä "lämpötalous (energiatalous)".
