### ISSUE TITLE
ennakointi

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#874]
Ks. Kielitoimiston sanakirja, ennakoida: 
1. ottaa ennakolta huomioon. Laskelmissa on ennakoitu myös tuleva tarve.
2. edeltää t. enteillä olemassaolollaan, toiminnallaan jtak myöhempää. Uutta tyyliä ennakoiva rakennus. Levottomuudet ennakoivat kapinaa.
3. ennustaa. Inflaation ennakoitiin kiihtyvän. 

Eli varmaan 1. ja 3. merkitys mahdollisia. Allärsissa ollut "prognostisering", mutta se pätee lähinnä 3. merkitykseen. Ensimmäinen olisi förutseende, antecipering tms. Melindassa näyttää olevan käytetty molemmissa merkityksissä. Pitäisikö jakaa? 

Vrt. esim. Maatalouskoneet liikenteessä : liikennetilanteiden ennakointi / Veli-Matti Tuure, Careful! : the surprising science behind everyday calamities - and how you can avoid them / Steve Casner, ja toisaalta Data mining and predictive analytics / Daniel T. Larose, Chantal D. Larose, Hyvinvointiyhteiskunta 2030 / Leena Ilmola, John Casti, Signaali ja kohina : miksi monet ennusteet epäonnistuvat, mutta jotkin eivät / Nate Silver ; suomentanut Kimmo Pietiläinen.

Tarvitaan JUHO-käännöksessä.

**Comment by YSO-kokous** [comment]
Käännetään Kielitoimiston sanakirjan ensimmäisen merkityksen mukaisesti.

**Comment by mirmaid** [comment]
Asioiden ottaminen ennakolta huomioon TAI Tulevien olosuhteiden huomioiminen ennakolta (TAI olosuhteiden ja kehityksen)...
