### ISSUE TITLE
projektit, hankkeet

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#875]
Näille molemmille on vain yksi sana ruotsiksi: projekt (vrt. myös eng. project). Allärsissa/ALLFOssa on kuitenkin nyt hankkeen vastineena "planer (initiativ)". Mahdollisena ratkaisuna voisi olla esim. "större projekt" tai "planerade projekt", mutta tämä riippuu sanan merkityksestä. Onko mahdollista määritellä hankkeen merkitys? Jos valittaisiin yksi MOTin merkityksistä, olisi mahdollista luoda järkevämpi ruotsink. vastine (ruotsin kannalta olisi tietysti "hankkeet ja projektit"=projekt, mutta se ei varmaan ole vaihtoehto suomen kannalta).

Kielitoimiston sanakirja: 
1. aie, aikomus, yritys, aloite, suunnitelma. 
2. määräasian toteuttamiseen tähtäävä us. laajamittainen työ, projekti. 

Ks. myös esim. https://www.projekti-instituutti.fi/materiaalit/projektijohtamisen_sanastoa

Ratkaisu tarvittaisiin myös JUHO-työtä varten.

**Comment by YSO-kokous** [comment]
@mariaforsen tekee YSE-ehdotuksen käsitteiden yhdistämisestä. Ehdotuksessa kannattaa mainita myös JUHO.
