### ISSUE TITLE
hallintotoimi

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#876]
On YSOn puolella hierarkisoitu termin "kunnan toimialat" alle. Tämä ei kuitenkaan käsitellä siinä merkityksessä missään muussa merkittävässä sanastossa tai sanakirjassa, ks. MOT, Tieteen termipankki, TEPA, Eduskunnan sanasto, Eurovoc jne. Näissä se tulkitaan administrative action/measure, förvaltningsakt/åtgärd ja näin on myös ruotsiksi ollut alusta asti Allärsissakin. Olisiko syytä muuttaa yläkäsite, esim. "toimenpiteet"? Tarvitaan myös JUHO-työtä varten.

**Comment by YSO-kokous** [comment]
@tpalonen ottaa JUHO-ylläpitoon yhteyttä. Olisiko käsite parempi tulkita Marian ehdottamalla tavalla? Vai tarvittaisiinko molemmat merkitykset (toimiala ja toimenpide)? Mikäli viitataan toimenpiteisiin, pitäisikö käsite muuttaa monikkoon?

**Comment by mariaforsen** [comment]
JUHO-kokous: Viittaa "toimenpiteisiin" (ei kunnan toimiala)

**Comment by tpalonen** [comment]
Eilen JUHO-kokouksessa nousi asia esiin ja tässä hallintotoimen tarkempi määritelmä.

_hallintotoimi_
**Määritelmä** 
hallintotehtävän hoitamiseen liittyvä toiminta yksittäistapauksessa
**Selite** 
Hallintotoimen ulkoisena muotona on tavallisesti hallintopäätös, joka sisältää ratkaisun hallintoasiassa. Hallintotoimia käytetään etenkin hallinnollisessa sääntelyssä ja valvonnassa. Myös julkisia palveluja toteutetaan hallintotoimina, joita käytetään varsinkin tosiasiallisessa hallintotoiminnassa.
**Kirjoittaja**
Olli Mäenpää (hallinto-oikeuden professori)

**Comment by YSO-kokous** [comment]
Tehdään YSE-ehdotus termin muuttamisesta monikkomuotoon, merkityksen tarkentamisesta tai jakamisesta.

**Comment by mirmaid** [comment]
Muutettu monikkoon YSAssa, hierarkia korjattava YSOssa.
https://github.com/Finto-ehdotus/YSE/issues/5679

**Comment by YSO-kokous** [comment]
Tehdään uutena YSAssa.

**Comment by mirmaid** [comment]
Uusi tullut YSOon, vanha ei poistuneissa?

**Comment by YSO-kokous** [comment]
Hallintoimi deprekoitu YSOsta, uudelleenohjaus hallintotoimiin.
