### ISSUE TITLE
Pneumatologia tarkoittaa kahta asiaa

### ISSUE THREAD

**Issue by YSO-kokous** [NatLibFi/Finto-data#877]
Pneumatologian huomautus on seuraava: "Pneumatologia voi tarkoittaa kahta asiaa. 1) Oppi ihmissieluista. 2) Oppi Pyhästä Hengestä". Tätä ei jostain syystä ilmeisesti käsitelty issuen https://github.com/NatLibFi/Finto-data/issues/200 yhteydessä.

EHDOTUS: Jaetaan käsite tai muutetaan huomautusta.

**Comment by satuniininen** [comment]
**Tieteen termipankki:**
Henkien ja sielujen tutkimusta koskeva käsite. Termi pneumatologia pohjautuu stoalaisten sielua merkitsevään pneuma-käsitteeseen ja tarkoittaa henkien ja sielujen tutkimusta. Sitä on käytetty eri aikoina eri tavoin. Tunnettu on D'Alembertin (1717-1783) käsitys johdannossa Diderotin toimittamaan suureen Ensyklopediaan (Discours préliminaire de l'encyclopédie (1751)), jossa hän sanoi pneumatologian käsittävän ihmisten lisäksi myös Jumalan ja enkelien sielujen tutkimuksen.

EHDOTUS: Poistetaan huomautus.

**Comment by YSO-kokous** [comment]
Poistettu huomautus.
