### ISSUE TITLE
vedostus

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#878]
Nyt ryhmissä: 
 82 Kustannustoiminta. Julkaisutoiminta. Kirjapainoala
 92 Kuvataide. Maalaustaide. Grafiikka. Kuvanveisto
 96 Valokuvaus. Elokuva
Näillä eri merkityksiä, ks. MOT, ja eri ruotsin vastineita. 
vedostaa > tehdä vedos > vedos: 
1. ladelmasta t. kuvalaatasta tarkistusta varten otettu painojäljennös; kuvat. taidegrafiikassa yksittäinen jäljennös (koevedos t. lopullinen kuva). Koe-, korjaus-, taittovedos. Grafiikan vedokset. > voisi olla provtryckning tms. 
2. valok. valokuvan negatiivista otettu jäljennös. 

Allärsissa on ollut 2 vastinetta, nyt olisi tarkoitus korjata (...niin että saadaan kopiointi=kopiering JUHOssakin). Onko mahdollista rajata kuvataide- ja valokuvausryhmiin? Tai ainakin määritellä niin että saadaan varmasti oikea vastine ja merkityskenttä ruotsiksikin? Ks. myös esim. https://pmlehti.fi/graafisen-alan-sanasto/

**Comment by YSO-kokous** [comment]
Maria ehdottaa käsitejakoa YSEen, määrittelee miten termit ruotsiksi jakautuvat ja pohjustaa käyttöä Melindan pohjalta.

**Comment by mariaforsen** [comment]
#6108
