### ISSUE TITLE
afroamerikkalainen musiikki

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#879]
Tämän käsitteen alla nyt esim. blues ja jazz. Asian tekee hankalaksi genrejen sitominen tiettyyn etniseen ryhmään tai alkupisteeseen. Jazziin esim. liittyy kuitenkin myöhempiä alalajeja, joita on vaikea nähdä afroamerikkalaisina.

EHDOTUS:
Siirretään afroamerikkalaisen musiikin alakäsitteet populaarimusiikin alle. Säilytetään RT afroamerikkalainen musiikki.

**Comment by tpalonen** [comment]
Vaatisi käsittelyä Muusa-ryhmässä.

**Comment by mirmaid** [comment]
Tuomas tekee YSE-issuen.
