### ISSUE TITLE
skenografia (taiteellinen luonti)

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#880]
TSK-ehdottaa poistoa: https://github.com/Finto-ehdotus/YSE/issues/5436

**Comment by YSO-kokous** [comment]
Poistetaan tämä käsite, ja sulkutarkenne käsitteeltä skenografia (taiteet). Lisätään tämän suhteet käsitteelle skenografia (taiteet) (+uudelleenohjaus siihen), lavastus ja puvustus RT-suhde.
