### ISSUE TITLE
neandertalinihminen

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#883]
YSAssa LT ihmiset. 

Wikipedia:
They are considered either a distinct species, Homo neanderthalensis, or more rarely as a subspecies of Homo sapiens (H. s. neanderthalensis). -- Scientists still dispute whether Neanderthals should be classified as a distinct species—Homo neanderthalensis—or as Homo sapiens neanderthalensis, placing Neanderthals as a subspecies of H. sapiens. DNA researcher Svante Pääbo referred to the ongoing "taxonomic wars" over whether Neanderthals were a separate species or subspecies as the type of debate that cannot be resolved, "since there is no definition of species perfectly describing the case."

Neandertalmänniska (Homo neanderthalensis), eller Neandertalare, (ibland kategoriserad som en underart till människan, Homo sapiens subsp. neanderthalensis)...

Neandertalinihminen (Homo neanderthalensis) on ihmisten (Homo) suvun laji -- Jotkut pitävät neandertalilaista omana ihmislajinaan ja nykyihmisen ja denisovanihmisen sisarlajina, mutta jotkut määrittelevät sen ihmisen (Homo sapiens) yhdeksi alalajiksi.

**Comment by YSO-kokous** [comment]
Tähän olisi hyvä saada isompi otanta erilaisten autoritääristen organisaatioiden kannasta asiaan ja tehdä päätös tämän pohjalta.

**Comment by mariaforsen** [comment]
Nationalencyklopedin:
"Likheterna mellan neandertalmänniskan och den moderna människan är så stora att man 1964 föreslog att det rörde sig om två underarter, Homo sapiens neanderthalensis och Homo sapiens sapiens. Denna klassificering var förhärskande under stora delar av 1970- och 80-talen. Detaljerade DNA-studier har emellertid visat att de två grupperna skildes åt för över 400 000 år sedan. Både neandertalmänniskan och den moderna människan utvecklades ur Homo heidelbergensis, neandertalmänniskan i Europa och den moderna människan i Afrika." 
Eli ainakin Nationalencyklopedin mukaan on se käsitys että molemmat ovat Homo sapiens vanhentunut (ollut hyväksyttynä 1970-80-luvuilla). Myöhemmät DNA-tutkimukset ovat osoittaneet tämän vääräksi.

**Comment by YSO-kokous** [comment]
Ratkeaa #885 yhteydessä, jos päädytään yhdistämään ihminen ja ihmiset -käsitteet.
