### ISSUE TITLE
ihminen / ihmiset

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#885]
http://laji.fi/taksoni/MX.46533?locale=fi, https://laji.fi/taxon/MX.51110
Sulkutarkenteet olisivat varsin ongelmallisia tässä yhteydessä, vaatisi ainakin tarkempaa tutkimista. Monikkoa ei ole käytetty yksinomaan tässä taksonomisessa merkityksessä ja yksikönkin kohdalla tarkenne (laji) saattaa olla ongelmallinen, vaikka sopiikin osin myös filosofian/elämänfilosofian alan teoksiin.

**Comment by satuniininen** [comment]
Käyttökerrat Melindassa: 

ihminen NOT kaunokki 7165
ihmiset NOT kaunokki 314
molemmat yhdessä 48

Monikollinen esiintyy pääsääntöisesti aineistoissa, joissa  ihmistä käsitellään ryhmänä yksilöitä ja näkökulmana on ihmisyys sosiaalisena tai yhteiskunnallisena roolina, esim: 

Myyr York : Humans of Myyr York
650 asukkaat 
650 ihmiset 
650 kaupungit 
650 valokuvat
650 henkilövalokuvaus 

sota ja mielenrauha 
650 sota
650 ihmiset 
650 sota |x kokemukset 
650 psyykkiset vaikutukset

Yksiköllinen esiintyy aineistoissa, joissa näkökulma on enemmän luonnontieteellinen, erityisesti biologinen, lääketieteellinen tai filosofinen. 

Kaikenkaikkiaan käyttö on sen verran kirjavaa, että selkeyttämiselle olisi tarvetta. Vaihtoehtoja ovat:

**1. yhdistäminen ihmiset KT ihminen**
Tällöin monikon käyttö laajenisi myös aineistoihin, kuten _Matka sydämeen : kaikki kehomme tärkeimmästä elimestä; Sapiens : Ihmisen lyhyt historia;  Eläin ja ihminen : mikä meitä yhdistää?_
Sanastosta löytyy myös _henkilöt_.

**2. sulkutarkenteiden lisääminen, esim:**

ihmiset (väestötiede)
ihmiset (yksilöt)
ihmiset (ihmisyksilöt)
ihmisyksilöt KT ihmiset (yksilöt)

ihminen (luonnontiede)
ihminen (ihmislaji)
ihminen (laji)
ihmislaji KT ihminen (laji)

**Comment by jarmosaarikko** [comment]
kannatan muotoa
ihmiset 
ihmislaji
pitäisikö tällaisiin hankaliin pareihin lisätä myös skos:note    "scopenote"?

**Comment by YSO-kokous** [comment]
Jokainen tutkii tahollaan Melinda-esiintymiä ja muodostaa mielipiteensä Satun ehdotusten pohjalta. Käsitellään tämän jälkeen.

**Comment by mariaforsen** [comment]
Kannatan yhdistämistä. SAOssa on tosin toisin päin kuin ykkösvaihtoehdosssa, eli: människan ja korvattuna människor, Homo sapiens
En näe miten termin "ihmislaji" lisääminen ratkaisisi mitään?

**Comment by tpalonen** [comment]
Kannatan yhdistämistä. Käsitteitä näytetään käytetyn tosiaan kuvailussa varsin päällekkäisesti. En yleisestikään näe tarvetta tällaisille erillisille "ihminen sinänsä"-tyyppisille käsitteille yleiskäsiteontologiassa. Se, mihin tieteenalaan tai kontekstiin kuvailtava kirja/dokumentti kuuluu, voidaan varmaankin ilmaista jollain muulla asiasanalla.

**Comment by YSO-kokous** [comment]
@satuniininen tekee YSE-ehdotuksen.

**Comment by satuniininen** [comment]
https://github.com/Finto-ehdotus/YSE/issues/6699
