### ISSUE TITLE
jälkihoito

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#888]
Käsitelty YSA-kokouksessa: https://github.com/Finto-ehdotus/YSE/issues/5483

**Comment by YSO-kokous** [comment]
Tuomas yhdistää. Tehdään uusi käsite YSOssa ja uudelleenohjaus kummastakin deprekoitavasta käsitteestä. Ryhmät 00 ja 48.

**Comment by tpalonen** [comment]
Tein muutokset. @mariaforsen tarkistatko uuden jälkihoito-käsitteen ruotsinnoksen sekä Allärs-linkin? @satuniininen tarkistatko uuden käsitteen englanninnoksen ja LCSH-linkin? Ktos!
