### ISSUE TITLE
kaiku

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#889]
Nyt LT äänet. Wikipedia: _Kaiku tarkoittaa signaalin, esimerkiksi äänen, kuulemista tai radiosignaalin vastaanottamista alkuperäisen signaalin viivästyneenä kopiona._ 

Melindassa _kaiku_-termiä on käytetty kaikenkaikkiaan vähän, mutta osa viitteistä käsittelee esim. tutkan kaikua. Olisiko siis parempi YK fysikaaliset ilmiöt? 

Kaikuluotauksen määritelmän voisi poistaa? Vaikka se on Kielitoimiston sanakirjasta, se on vähän suppea: _kaikuilmiöön perustuva veden syvyyden t. vedessä olevan esineen sijainnin määrittäminen t. aineen rakenteen tutkiminen_. Melindassa on aineistoa mm. lepakoiden kaikuluotauksesta. (ryhmäksi ehkä myös 45, 07)

**Comment by YSO-kokous** [comment]
Päätös:
kaiku YK fysikaaliset ilmiöt + RT äänet
Poistetaan kaikuluotauksen määritelmä.
