### ISSUE TITLE
JUPOn ja JUHOn kautta tulleet muutosehdotukset

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#890]
Voitaisiin käydä pikaisesti läpi. Huomioita eroista yksikkö-monikkomuodoissa, YSA/YSOn altLabel JUPOn pref ym. Koska eivät ole varsinaisia ehdotuksia vaan enemmänkin kysymyksiä/kommentteja voisimme yhdessä päättää mitä halutaan muuttaa jne.

**Comment by tpalonen** [comment]
Disclaimer: Tässä pelkkä listaus. Parantelen & syvennän tätä kommenttiani vielä.

kuntien menot
kuntien tulot
valtion menot
kuulontutkimus
siirtymäaika - miksi yksikössä YSOssa?
siirtymätalous - miksi yksikössä YSOssa?
sopimuspaikka - miksi yksikössä YSOssa?
strategia - miksi yksikössä YSOssa?
valtion talousarvio (valtion tulo- ja menoarvio on vanhentunut termi VALTERin mukaan)
fuusio (ydinreaktiot) - muotoon ydinfuusio?

valmius ja valmiudet eri käsitteet JUHOssa

ohjaajat
YSOssa tämä viittaa elokuvien yms. ohjaajiin, eli käsitetasolla on viittaus YSOon tässä tapauksessa väärä jos tämä termi JUHOssa viittaa mihin tahansa ohjaajiin, ks. related. YSOn ruotsinkielinen vastine regissörer ei päde muuhun kuin elokuvien yms. ohjaajiin, eli ei voida laittaa YSOn ruotsinkielinen termi vastineeksi JUHOssa kun merkitys ei ole sama (ellei haluta muuttaa samaan merkitykseen kuin YSOn) HUOM! Muutosehdotus tehty YSAan, joten tätä ei kannata käsitellä täällä ennenkuin on käsitelty YSA-kokouksessa.

postivirkamiehet - vanhentunut termi

telekuuntelu ja televalvonta JUHOssa erillisiä käsitteitä

**Comment by YSO-kokous** [comment]
Tuomas merkitsee YSA-kokouksessa 2017-5 käsiteltävät issuet JUHO-labelilla, ja tekee puuttuvat issuet.

**Comment by YSO-kokous** [comment]
JUPO-kommentit-listaus: Tuomas käy läpi. Mirja tarkistaa terveysalan termit Lääketieteen termeistä ja tekee muutosehdotukset YSEen. Kysytään muista Katrilta.

**Comment by mirmaid** [comment]
Uusin versio jupo-taulukosta: https://docs.google.com/spreadsheets/d/1gdRnv8fOGSCzPi7JykN5h2pAM6srSYvFSiHj7DahYh0/edit#gid=1447191250

**Comment by tpalonen** [comment]
Kävin listan läpi. Tiedoksi: @mirmaid.

**Comment by mirmaid** [comment]
Tehdään YSE-issuet taulukon keltaisista ja valkoisista riveistä (jos ei ole vielä ollut).

**Comment by mirmaid** [comment]
Taulukko käyty läpi ja issuet lisätty harkinnan mukaan.
