### ISSUE TITLE
harjoitusmenetelmät

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#892]
Ei YSA/Allärs:issa. Mihin viittaa? Ruotsiksi täytyy valita träningsmetoder vs. övningsmetoder (sanastossa nyt myös valmennusmenetelmät=träningsmetoder)

**Comment by YSO-kokous** [comment]
Ruotsin vastineeksi sopii parhaiten träningsmetoder. Tehdään YSE-issue eli ehdotetaan käsitettä YSAan.

**Comment by mirmaid** [comment]
Lisätty YSAan, linkitys puuttuu vielä.
