### ISSUE TITLE
kamppailu-urheilu

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#893]
Vain YSOssa (ei YSA). Sanastossa myös kamppailulajit (mikä on kai yleisempi nimitys ja löytyy myös sanakirjoissa jne.) Ruotsiksi kampsport (muita ei tarvita). Onko mahdollista poistaa YSOsta? Vai onko tarkoitus ottaa myös YSAan? Jotain on tehtävä ainakin ruotsin osalta.

**Comment by YSO-kokous** [comment]
Poistetaan kamppailu-urheilu. Siirretään sen alakäsitteet YK urheilu. Lisätään alakäsitteille myös RT kamppailulajit.
