### ISSUE TITLE
kulttuurintutkimus, kulttuurien tutkimus

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#894]
Ruotsiksi on ollut kulturforskning ja kulturvetenskap, mikä ei toimi (ovat oikeastaan synonyymejä). Onko molemmat välttämätöntä pitää erillisinä termeinä? Onko käyttö johdonmukaista, ei näytä siltä Melindassa.

**Comment by YSO-kokous** [comment]
Tehdään ehdotus YSEn kautta joko termien yhdistämisestä tai jaottelusta esim. "nykykulttuurin tutkimus" / kulttuurin/kulttuurien tutkimus. Kysytään kommentteja Helsingin ja Itä-Suomen yliopistoilta ja SKS:ltä.

**Comment by tpalonen** [comment]
https://github.com/Finto-ehdotus/YSE/issues/6556
