### ISSUE TITLE
liikkuminen

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#895]
Allärs: motionering
ALLFO: rörelse 

YSOssa myös liike=rörelse (fenomen)

Vrt. YSOn alakäsitteet ja YSAn. Eli YSOssa tulkittu laajempana (kuin pelkkä ihmisten fyysinen liikkuminen omin voimin jne., johon "motionering" viittaa)? Olisiko syytä selventää/määritellä? Kun on selvää mihin kaikkeen viittaa voidaan valita oikea ruotsinkielinen vastine (vaatinee erikoisratkaisua, esim. röra sig?)

Melindassa nyt esim. 
-The assessment and reduction of motion artifact in dry contact biopotential electrodes / Alper Cömert.
-Actor movement : expression of the physical being : a movement handbook for actors / Vanessa Ewan and Debbie Green.
-Liikunta kansalaisten elämänkulussa : tulkintoja liikkumisesta ja liikunnanedistämisestä / Hannu Itkonen ja Kati Kauravaara (toim.).

**Comment by YSO-kokous** [comment]
@mirmaid tutkii. Jollei muuta ratkaisua saada niin röra sig lienee paras vaihtoehto.

**Comment by mirmaid** [comment]
Suomeksi liikkuminen on merkitykseltään laaja, Melindassa yli 1100 viitettä. Käytetty sekä ihmisen/ihmisten siirtymisestä paikasta toiseen, että fyysisestä liikkumisesta (liikunta, motoriikka, performanssi). Jako on työläs mutta varmaan mahdollinen, jos tarpeen?

**Comment by YSO-kokous** [comment]
Tehdään jakoehdotus, osittain mahd. ohjattavissa olemassaoleviin termeihin.

**Comment by satuniininen** [comment]
https://github.com/Finto-ehdotus/YSE/issues/6775
