### ISSUE TITLE
magmakivet

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#896]
Eikö tämä pitäisi poistaa? YSAssa magmakivilajit KT magmakivet. Ruotsiksi synonymisia, näin näyttää olevan myös TEPAssa jne.

**Comment by YSO-kokous** [comment]
Samoin myös sedimenttikivet, metamorfiset kivet.

**Comment by tpalonen** [comment]
Tehty. Deprekoin myös ryhmittelevän käsitteen "kivi syntytavan mukaan", koska sen alle ei jäänyt enää käsitteitä näiden muutosten jälkeen.
