### ISSUE TITLE
uusiutuminen

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#899]
Päätettiin tässä https://github.com/Finto-ehdotus/YSE/issues/4786 että uudistaminen=förnyande, mikä tarkoittaa että täytyy muuttaa uusiutuminen=förnyande ruotsin osalta. Emme kuitenkaan voida valita vastinetta ennen kuin on selvää mihin suomenkielinen termi viittaa. Jos uusiutuminen määritellään lääketieteelliseksi voidaan laittaa esim. återfall. Melindassa on kuitenkin paitsi lääketieteellisenä (sairauden uusiutuminen-merkityksessä) käytetty myös esim. näiden aineistojen kuvailuun: 

Building organizational creativity : a multitheory and multilevel approach for understanding and stimulating organizational creativity / Anna-Maija Nisula. 

Luonnonvarayhdyskunnat ja muuttuva ympäristö : resilienssitutkimuksen näkökulmia Itä-Suomeen / Juha Kotilainen ja Ilkka Eisto (toim.)

Place and tourism promotion : urban regeneration? / by Edmund Christopher Matotay.

Tukisolujen merkitys ihmisen alkion kantasolujen erilaistumattomuudelle / Sanna Vuoristo.

Teollisuuden uusiutuminen / [julk.: Teollisuuden keskusliitto].

Kokeile Jeesusta : tapaustutkimus uskossa raitistuneista ja arjessa päihteiden väärinkäyttöön uudelleen retkahtaneista miehistä / Sari Rautarinta.

Vrt. myös MOT: 

uusiutuminen s (taudin) lääk
recidiv [-et,=,-en], recidivering [-en,-ar,-arna], återfall [-et,=,-en]

uusiutua
1. ilmaantua uudelleen, toistua, uusia (5). Määräajoin uusiutuva ilmiö. Uusiutuva tauti.
2. vaihtua, muuttua uudeksi, korvautua uudella, uudistua. Metsän, ihon uusiutuminen. Uusiutuvat luonnonvarat. 

uusiutua
1 (toistua) upprepas, upprepa sig, hända igen
2 (ilmaantua uudelleen) återkomma, komma tillbaka 
3 (uudistua) förnyas
4 lääk (taudista) recidivera, återkomma 
5 biol regenereras [=,regenererades,regenererats]

Onko mahdollista määritellä tarkemmin mihin uusiutuminen pitäisi käyttää?

**Comment by YSO-kokous** [comment]
Rajataan uusiutuminen (lääketiede) tms. ja mietitään ratkaisu muille uusiutuminen-termillä kuvailluille.

**Comment by satuniininen** [comment]
https://github.com/Finto-ehdotus/YSE/issues/5811
