### ISSUE TITLE
YSO-käsitteiden selite- ja lähde-kentiltä puuttuu kielikoodeja

### ISSUE THREAD

**Issue by Finto-data** [NatLibFi/Finto-data#9]
_From [osma.suominen@helsinki.fi](https://code.google.com/u/osma.suominen@helsinki.fi/) on October 04, 2013 11:10:16_

Monien YSO-käsitteiden selitteissä ja lähdetiedoissa on puutteelliset kielikoodit. SKOS-versiossa näkyy esim. näin:

```
skos:scopeNote "Konserttitalo Lahdessa"^^xsd:string .

dc:source "Lähde: CD-perussanakirja"^^xsd:string .
```

Tämän vuoksi nämä tiedot eivät näy ONKI Lightissa, kts. issue https://code.google.com/p/onki-light/issues/detail?id=144 Pitäisi varmaan Matiaksen skriptillä tms. korjata kielikoodiksi fi näiden propertyjen arvoille, jos kielikoodia ei ole entuudestaan asetettu (tai on datatyyppinä xsd:string kuten ylläolevissa esimerkeissä).

_Original issue: http://code.google.com/p/onki-data/issues/detail?id=5_

**Comment by MikkoAleksanteri** [comment]
Onko issue vielä relevantti? @osma

**Comment by osma** [comment]
Kaikilla selitteillä (skos:note) on kielikoodit paitsi tällä yhdellä:

```
<http://www.yso.fi/onto/yso/p17734> <http://www.w3.org/2004/02/skos/core#note> "Term in use from 1991 onwards. For earlier, see vocational course centres." .
```

Lähteissä (dc:source) on kaksi tapausta, joista puuttuu kielikoodi:

```
<http://www.yso.fi/onto/yso/p21446> <http://purl.org/dc/elements/1.1/source> "Eurooppa-valmistelukunta-verkkosivusto" .
<http://www.yso.fi/onto/yso/p4752> <http://purl.org/dc/elements/1.1/source> "L\u00E4hde: L\u00E4\u00E4ketieteen termit" .
```

Nämä pitäisi korjata käsipelillä YSOon. Mikko?

**Comment by MikkoAleksanteri** [comment]
> Kaikilla selitteillä (skos:note) on kielikoodit paitsi tällä yhdellä:
> 
> <http://www.yso.fi/onto/yso/p17734> <http://www.w3.org/2004/02/skos/core#note> "Term in use from 1991 onwards. For earlier, see vocational course centres." .
> 
> Lähteissä (dc:source) on kaksi tapausta, joista puuttuu kielikoodi:
> 
> <http://www.yso.fi/onto/yso/p21446> <http://purl.org/dc/elements/1.1/source> "Eurooppa-valmistelukunta-verkkosivusto" .
> <http://www.yso.fi/onto/yso/p4752> <http://purl.org/dc/elements/1.1/source> "L\u00E4hde: L\u00E4\u00E4ketieteen termit" .
> 
> Nämä pitäisi korjata käsipelillä YSOon. Mikko?

Puuttuvat kielikoodit lisätty.
