### ISSUE TITLE
käskyt / kymmenen käskyä

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#900]
YSA: käskyt ST päiväkäskyt, kymmenen käskyä
YSO: päiväkäskyt YK yhteiskunnalliset objektit; käskyt YK uskonnolliset tuotokset, SK kymmenen käskyä

Ehdottaisin, että käskyt siirretään yhteiskunnallisiin objekteihin ja päiväkäskyt sen alle myös YSOssa. Voisiko kymmenellä käskyllä olla monihierarkia (nyt uskonnolliset tuotokset on kulttuuristen tuotosten alla), YK käskyt ja uskonnolliset tuotokset?

Melindassa suurin osa aineistosta joka on kuvailtu termillä _käskyt_, käsittelee kymmentä käskyä (jälkimmäinen otettu sanastoon vasta 2014). Näihin on syytä lisätä myös kymmenen käskyä, mutta otetaanko _käskyt_-termi pois?

**Comment by YSO-kokous** [comment]
- luodaan uusi käsite "käskyt", jolle samat tiedot kuin YSA-käsitteellä:
http://finto.fi/ysa/fi/page/Y111296
- deprekoidaan YSOsta "käskyt" (p20276), uudelleenohjaus käsitteisiin "kymmenen käskyä" ja uuteen "käskyt"-käsitteeseen
- käskyt YK yhteiskunnalliset objektit
- päiväkäskyt YK käskyt
- kymmenen käskyä YK uskonnolliset tuotokset (eli ei YK käskyt)

Mirjan kysymys: "_Näihin on syytä lisätä myös kymmenen käskyä, mutta otetaanko käskyt-termi pois?"_
Päätös: otetaan käskyt-termi pois

**Comment by tpalonen** [comment]
Tein päätökset. @mariaforsen tarkistatko uuden käskyt-käsitteen ruotsinnoksen ja Allärs-linkin? @satuniininen tarkistatko uuden käsitteen englanninnoksen ja LCSH-linkin? Ktos!

**Comment by satuniininen** [comment]
Englanti ok
