### ISSUE TITLE
(taide) vs. (taiteet) sulkutarkenteena

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#903]
Tämä herätti keskustelua YSA-kokouksessa. Kumpaa näistä pitäisi suosia? Esim. neorealismi (taide/taiteet). YSOsta löytyy erikseen sekä taide [ohjaustermi taidelajit] että taiteet. Jälkimmäisen alakäsitteinä mm. kansantaide, poliittinen taide, esihistoriallinen taide. Lisäksi löytyy YSA-ryhmä "09 Taide yleensä."

**Comment by YSO-kokous** [comment]
Yksi lisämahdollisuus olisi ottaa tarkenteeksi (taiteet) silloin, kun se on yläkäsite, muulloin esim. (tyylit), kun se on yläkäsite. Tämä ei kuitenkaan kata kaikkia tapauksia.

**Comment by YSO-kokous** [comment]
Alustava ratkaisu: sulkutarkenteeksi (taiteet) kun se on yläkäsite YSOssa. Käsitellään asiaa vielä issuessa #536.
