### ISSUE TITLE
YSO-paikat -käsitteellä YSO-käsite yläkäsitteenä

### ISSUE THREAD

**Issue by MikkoAleksanteri** [NatLibFi/Finto-data#905]
Joillain YSAsta juontuvilla maantieteellisillä käsitteillä on yläkäsitteenä ei-maantieteellinen käsite. Esim tiettyjen valtateiden yläkäsite tiet: http://finto.fi/ysa/fi/page/Y99490

Aiheuttaa haasteita YSO-paikkojen osalta: http://finto.fi/yso-paikat/fi/page/p213358

**Comment by YSO-kokous** [comment]
Valtatien yläkäsitteeksi merkitään maantieteellinen käsite, joko valtio(t), tai kun se on mahdollista, pienempi maantieteellinen alue (maakunta silloin kun tie on yhden maakunnan alueella).

**Comment by mirmaid** [comment]
Jatkuu tässä issuessa: https://github.com/NatLibFi/Finto-data/issues/930
