### ISSUE TITLE
Geologiset kaudet

### ISSUE THREAD

**Issue by satuniininen** [NatLibFi/Finto-data#908]
Geologiset kaudet on LCSH:ssa jaoteltu aihekohtaisesti, ks. esim. [Kenotsooinen maailmankausi](http://id.loc.gov/search/?q=Cenozoic&q=cs%3Ahttp%3A%2F%2Fid.loc.gov%2Fauthorities%2Fsubjects).

Tehdäänkö YSOn puolelta siltaukset näihin kaikkiin, ja jos tehdään niin millä suhteella? Vastaavantyyppisiä siltauksia on myös tyylisuunnista, esim. [realismi](https://finto.fi/yso/en/page/?clang=fi&uri=p2883).

**Comment by YSO-kokous** [comment]
Sillataan kaikki narrowMatch-ominaisuudella.
