### ISSUE TITLE
monikulttuurinen avioliitto, seka-avioliitto

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#909]
YSA-kokous päätyi pitämään termit erillään ja voisi myös tulkita niin että seka-avioliitto on monikulttuurisen avioliiton yläkäsite. Mitä tehdään? https://github.com/Finto-ehdotus/YSE/issues/5445

**Comment by YSO-kokous** [comment]
Muutetaan suhde yläkäsite-alakäsite-suhteeksi, poistetaan huomautukset.

**Comment by tpalonen** [comment]
Toteutettu dataan.
