### ISSUE TITLE
slaavit

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#910]
YSOssa YK eurooppalaiset. _Suurin osa slaavilaisista kansoista elää Euroopassa._

suomalaiset YK pohjoismaalaiset AK ulkosuomalaiset

vrt. balkanilaiset - kreikkalaiset - kyproksenkreikkalaiset

**Comment by YSO-kokous** [comment]
Slaavit LT väestöryhmään liittyvät rooli
Kaikille ST-suhteisille tuplahierarkia, paitsi venäläiset jää vain slaavit-käsitteen alle, RT eurooppalaiset.
