### ISSUE TITLE
väsyminen

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#911]
Ruotsiksi ollut utmattning. Tämä on käytetty myös ja varsinkin ihmisistä. Ks. Melinda, esim. Kahden tunnin lajinomaisen harjoittelun vaikutukset väsymykseen ja reaktiovoimat suksislopestylessä / Aki Happonen ; Huomio henkiseen työhyvinvointiin / Maija Kääriäinen. Onko tämä todella vain fysiikka ja YSOn sanakirjamääritelmän mukainen? Siinä tapauksessa täytyy lisätä ainakin ruotsiksi tarkenne ja ehkä muuttaa koko termiä.

**Comment by YSO-kokous** [comment]
Vrt. ihmisistä väsymys, aineen yhteydessä taas väsymislujuus. Onko tälle tarvetta, ja jos on, mikä olisi hyvä sulkutarkenne (esim. tekniikka/tekninen?).

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/6689
