### ISSUE TITLE
täyttö

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#912]
Ruotsiksi påfyllning. Tämä ei täsmää kaikissa tapauksissa. Melindassa käytetty myös eläinten ja lintujen täytöstä, mutta sille olisi oma asiasana "eläinten täyttö", voisiko ohjata siihen niissä tapauksissa? Kun merkityskenttä on selvä valitaan ruotsinkielinen vastine (fyllande?)

**Comment by YSO-kokous** [comment]
Ehdotus termin poistosta YSEen.
