### ISSUE TITLE
Jokien suhteet

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#913]
Nyt linjauksissa: _isoille vesistöille (jotka ulottuvat useamman kunnan alueelle) ei laiteta kuntaa yläkäsitteksi_. Käytännössä kuitenkin yläkäsitteitä on useamman kunnan alueelle ulottuvilla joilla, joten tätä voisi muokata.

Pitäisikö kosken yläkäsitteenä olla (myös) joki? (Kukkolankoski/Tornionjoki)

**Comment by mirmaid** [comment]
PNR:n 1:2milj ja 1:4,5milj mittakaavan vesistöille ei laiteta yläkäsitettä, kaikille muille vesistöille lisätään PNR:n yläkäsite.

**Comment by mirmaid** [comment]
Lisätään vesistöjen osille yläkäsitteeksi myös vesistön nimi.

**Comment by mirmaid** [comment]
Vesistöjen osista voi pyytää listauksen ja päivittää.

**Comment by YSO-kokous** [comment]
Sparklataan YSO-paikoista käsitteet, joiden tyyppitiedoissa "osa" (http://www.yso.fi/onto/yso/p126432) ja "koski".

**Comment by YSO-kokous** [comment]
Tässä SPARQL: https://api.triplydb.com/s/nbM90ENQK

**Comment by mirmaid** [comment]
https://api.triplydb.com/s/eILowgfLx

**Comment by jarmosaarikko** [comment]
Olen samaa mieltä kuin edella: kosket ovat osa jokea.
Koen, että yläsuhteena vesistön viittaus paikkakuntaan voisi tehdä eri tavalla sillä vesistö ei ole paikkakunnan osa samalla tavalla kuin joku muu maa-alue. MIelestäni tällöin pitäisi olla RT-suhde eikä partOf-suhde. Esim. Hattula https://finto.fi/yso-paikat/fi/page/p94129 - osakäsitteenä: mm.  Alajoki ja Takajärvi (Hattula : järvi).  

PNR:n paikanlajiteeman "vedet" kohteiden isPartOf-suhteena voi olla olla vain vesistö tai valuma-alue. Tämän helpottamiseksi YSO-paikoissa vesistöt voitaisiin käsitellä omassa skeemassaan, jossa olisi oma sisäkkäisten valuma-alueiden hierarkia.  Samalla monen paikkakunnan alueelle ulottuvat vesistöt kuten **joet** voidaan linkittää niihin assosiatiivisella RT- tai dc:spatial -suhteella. Wikidatassa tämä suhde on kuvattu ominaisuudella "sijaitsee hallinnollisessa yksikössä"
Esim. "Vartiokylälahti" ei ole osa käsitettä Helsinki, vaan Suomenlahti  ja se sijaitsee Helsingissä. https://www.wikidata.org/wiki/Q11900566


Huom: Tämä käsitykseni ilmeisesti poikkaa vuonna 2019 kirjatusta periaatteesta ison mittakaavan käsitteiden linkitämisestä.

**Comment by mirmaid** [comment]
Tarkistetaan ylläolevat listaukset, onko kaikki päivitetty.

**Comment by mirmaid** [comment]
Ehdotettu:
Useamman valtion alueella kulkevan joen yläkäsite on maanosa, paitsi jos kyse on kahden valtion alueella kulkevasta joesta tai rajajoesta, tällöin merkitään ko. valtiot. Useamman maakunnan alueella kulkevan joen yläkäsite on valtio. Yhden Suomen maakunnan tai kunnan alueella kulkevan joen yläkäsite on maakunta tai kunta. Ulkomaisten jokien yläkäsite on aina valtio tai maanosa.

**Comment by tpalonen** [comment]
Tässä korjattu SPARQL-kysely joka hakee sourcesta maininnat "Virtaveden osa" tai "Koski":
https://api.triplydb.com/s/vIPJFq6wu

Obs! SPARQL:n hakutuloksista jää uupumaan Pirilänkoski-koski ja Naiskoski-koski, koska näissä koskitieto mainitaankin notessa eikä sourcessa. 
Pirilänkoski: http://www.yso.fi/onto/yso/p188858
Naiskoski: http://www.yso.fi/onto/yso/p188436

**Comment by tpalonen** [comment]
Ei kuulunut tehtävänantoon, mutta tein vielä huvikseni SPARQL:n joka hakee: 1) kaikki joiden skos:notessa on "Puro" ja lisäksi kaikki joiden label on muotoa *puro tai *oja
https://api.triplydb.com/s/tOZlXPlDX

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/12776

**Comment by tpalonen** [comment]
Minusta tämä ehdotus on aika selkeä. https://github.com/NatLibFi/Finto-data/issues/913#issuecomment-1851495334
Kannatan.

**Comment by mirmaid** [comment]
Hyväksytään edellä ehdotettu linjaus. Täydennetään hierarkiaa työresurssien mukaan.

**Comment by mirmaid** [comment]
Lisää jokien suhteista: 

- lisätäänkö jokien ja niiden sivujokien välille RT-suhde?
- lisätäänkö pienemmille joille ja sivujoille yläkäsitteeksi päävesistöalue (järville on lisätty)?
- lisätäänkö päävesistön ja laskujoen välille RT-suhde vai hierarkkinen suhde?

Lisätäänkö Suomen ja toisen valtion alueelle sijoittuvan joen tai rajajoen yläkäsitteeksi vain valtiot, vai Suomen osalta maakunta/kunta (ja lisätäänkö lisäksi Suomi)? Vrt. tiet - merkitty vain valtio, mutta myös Eurooppatie 63 tehty näin.

**Comment by ilona-x** [comment]
> Lisätäänkö Suomen ja toisen valtion alueelle sijoittuvan joen tai rajajoen yläkäsitteeksi vain valtiot, vai Suomen osalta maakunta/kunta (ja lisätäänkö lisäksi Suomi)? Vrt. tiet - merkitty vain valtio, mutta myös Eurooppatie 63 tehty näin.
> 

Nyt Suomen osalta on laitettu tarkin mahdollinen yläkäsite. Esimerkiksi [Jänisjoki (Tohmajärvi)](http://www.yso.fi/onto/yso/p109416) on yläkäsitteenä Tohmajärvi, Joensuu ja Venäjä. YSE-issue: https://github.com/Finto-ehdotus/YSE/issues/9097

**Comment by mirmaid** [comment]
Jokien ja teiden yläkäsitteet tehdään yleisen linjauksen mukaan myös silloin, kun ne ulottuvat Suomen ja toisen valtion/valtioiden alueelle.

- lisätään jokien ja niiden sivujokien välille RT-suhde
- päävesistön ja laskujoen välille hierarkkinen suhde
- koskella merkitään hierarkkinen suhde jokeen, jonka osa se on, mutta ei esim. järveen, kanavaan tai vesireittiin
- lisätäänkö pienemmille joille ja sivujoille yläkäsitteeksi päävesistöalue / ei lisätä
- lisätään kaikille vesistöille (Kemijoen vesistö jne.) YK Suomi

**Comment by mirmaid** [comment]
Tarkistetaan linjaustekstit: https://www.kiwi.fi/display/Finto/YSO-paikat

Tehdäänkö jotain suunnitelmaa hierarkian päivityksestä?

**Comment by mirmaid** [comment]
16.12.2024
Linjaukset tarkistettu. Ei tehdä erillistä suunnitelmaa hierarkia päivityksestä.
