### ISSUE TITLE
lisäys

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#914]
Näyttää olevan käytetty eri merkityksissä (ja ryhmä onkin 00), mutta näille kaikille ei sovi nykyinen ruotsink. vastine "ökning" (det att ngt görs större i antal el. omfattning; det att ngt blir större i antal el. omfattning). Paljon kasviin liittyyvää, voisiko se aihe ainakin olla erikseen?

Ks. Melinda, nyt esim. 
-Energiasäästötarkastelu pientalossa / Mikko Moilanen. 
-Laajentamissuunnitelma lypsykarjatilalle : case Kekkonen / Hanna Kekkonen, Jarkko Kekkonen.
-Seeds : the ultimate guide to growing successfully from seed / Jekka McVicar ; photography by Marianne Majerus ; Vadelman (Rubus idaeus) mikrolisäys : paikallisen vadelmakannan lisäys / Niina Sirkka, Salla-Maaria Tiikkaja. (sv. lähinnä förökning)
-Vuoden 2004 alun alkoholiolojen muutokset Suomessa myyntitilastojen ja lehdistökirjoittelun valossa / Thomas Karlsson ... [ja muita] ; Köp nu! : 25 steg som garanterat ökar din försäljning / Krister Maxe. (sv. ökning sopii)
-Val201-peptidin vaikutus eturauhassyöpäsoluissa / Ilpo Rajala, Jouko Roukala, Ida Smith. (sv. ökning ok?)
-Selvitys uusiutuvan energian lisäämisen kustannuksista ja edistämiskeinoista. ; Liikkuva ja hyvinvoiva Suomi 2010-luvulla : ehdotus kansalliseksi liikuntaohjelmaksi julkisen ohjauksen näkökulmasta. (sv. ökning?)
-Semantiikka ja pragmatiikka Asterixin suomennoksessa ja ruotsinnoksessa / Maire Kosonen. ; Elintarvikkeiden täydentäminen raudalla : mallinnettu saanti suomalaisilla aikuisilla / [Susanna Raulio]. (sv. olisi lähinnä tillägg/tillsättning, ökning ei sovi ollenkaan)

Lisäys=lisäämisen/lisääntymisen tulos=ökning
Lisäys=kasvu=tillväxt 
Lisäys=lisääntyminen=förökning
Lisäys=lisääminen=tillsättning/tillägg

Kielitoimiston sanakirja:
1. lisääminen. Fluorin lisäys veteen. (tillsättning, tillägg)
2. lisääntyminen, kasvu. Kalakannan viimeaikainen lisäys. (tillväxt..? förökning..?)
3. lisäämisen t. lisääntymisen tulos, lisätty t. lisääntynyt määrä. (ökning)

Eli:
-Kun lisätään jotain "uutta" johonkin toiseen/vanhaan/olemassa olevaan (esim. fluorin lisäys veteen)= tillsättning/tillägg 
-Kun joku olemassa oleva asia laajenee/tulee lisää sitä samaa ainetta/asiaa tms.=ökning
-Kun kasvit/eläimet lisääntyvät (riippumatta onko se ihminen joka toiminnallaan antaa siihen edellytykset, esim. perennojen lisäys)=förökning (nyt förökning=lisääntyminen=uusien eliöyksilöiden syntymisestä saman lajin vanhemmista yksilöistä)  ->  Olisiko mahdollista ratkaista tämä esim. uudella termillä (+ohjauksella) "kasvien lisäys" tms.? (sv. "förökning av växter")

**Comment by YSO-kokous** [comment]
@mariaforsen tekee YSE-issuen: "kasvien lisäys" omaksi käsitteekseen. Melinda-kuvailussa vähintään 90% käytöstä tuntuu olevan tätä kasvien lisäystä. Tarvitaanko erillistä lisäys-käsitettä? Käyttö muussa kuin kasvimerkityksessä varsin vähäistä.
