### ISSUE TITLE
maisema

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#915]
Maiseman huomautus YSOssa: "Maisema on kokonaisuus, joka muodostuu geomorfologisista, ekologisista sekä kulttuurihistoriallisista tekijöistä sekä niiden vuorovaikutussuhteista. Maisema on luonnonlakien mukaan toimiva, elävä ja kehittyvä dynaaminen kokonaisuus. Maisema -käsitteeseen liittyy myös ihmisen mielikuvia ja henkisiä sekä esteettisiä käsityksiä. _Useimmat suomalaiset maisemasta puhuessaan tarkoittanevat näköalaa tai maisemakuvaa, maiseman silmin havaittavaa ilmiasua_." On pitkä ja hieman sekava, varsinkin loppu-osa tuntuu oudolta huomautuksena ontologiassa.

**Comment by YSO-kokous** [comment]
Poistettiin.
