### ISSUE TITLE
tölkit, purkit

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#917]
Molemmat =burkar. Nyt kuitenkin tölkit=konservburkar, sehän on oikeastaan säilyketölkit/purkit, mutta sitä ei ole suomeksi mukana edes korvattuna, eikä se täsmää Melindan kanssa.  Olisiko yhdistäminen (purkit ja tölkit) tai tarkempi määrittely (jolloin voidaan luoda tarkenteita tms.) mahdollisia ratkaisuja?

**Comment by YSO-kokous** [comment]
Purkit säilyy entisellään, KT tölkit. Tölkit poistetaan, tilalle juomatölkit KT tölkit.
