### ISSUE TITLE
Kirkko / kirkot

### ISSUE THREAD

**Issue by satuniininen** [NatLibFi/Finto-data#918]
ks. #536 

[kirkko (ilmiöt)](http://finto.fi/yso/en/page/p8835?clang=fi) Melindassa 2073 kertaa
[kirkot (organisaatiot)](http://finto.fi/yso/en/page/p938?clang=fi) Melindassa 953 kertaa

Samantyyppinen kuin taannoinen seurakunta / seurakunnat, joka päädyttiin yhdistämään. 
Käsitteet menevät herkästi sekaisin ja kuvailukäyttö on ollut polveilevaa. Melindassa monikollista muotoa on käytetty paljon tarkoittamaan todennäköisesti kirkkorakennusta, esim. teoksessa _Kenen tekemää alttaritaidetta? : vuosina 2000-2010 rakennettujen luterilaisten kirkkojen taiteilijavalintojen tarkastelua._ 
Niissä tapauksissa yksiköllinen kirkko kuulostaa vieraalta, mutta muutoin monikollisen korvaaminen yksiköllisellä voisi toimia.

Esim.
Katso ihmistä : näkökulmia kristilliseen ihmiskäsitykseen
650 kristinusko
650 ihmiskuva
650 kirkot --> kirkko

Uskon silta Suomenlahden yli : suomalaisten kirkolliset yhteydet Viroon vuosina 1918-1939
650 kirkot --> kirkko
650 kansainväliset suhteet 
650 heimoaate
650 evankelis-luterilainen kirkko

Ecumenical attack against racism : ‡b the anti-racist programme of the World Council of Churches, 1968-1974
650 ekumenia
650 kirkot --> kirkko
650 kansainväliset järjestöt
650 rasismi

**Comment by YSO-kokous** [comment]
Tehdään YSE-ehdotus: jätetään yksiköllinen kirkko, kirkot KÄ kirkkorakennukset, mahd. uutena kirkkokunnat (KT kirkot).

**Comment by satuniininen** [comment]
https://github.com/Finto-ehdotus/YSE/issues/5957
