### ISSUE TITLE
dekadenssi

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#923]
YSA-ongelmakokous päätti, ettei ole tarvetta dekadenssi (muutos) -käsitteelle: _dekadenssi (muutos) uudelleenohjaus käsitteeseen rappio_.
https://github.com/Finto-ehdotus/YSE/issues/5771

**Comment by tpalonen** [comment]
Mitä tehdään säilyvän käsitteen sulkutarkenteille? Käyttöhuomautus olisi varmasti hyvä ja siinä viittaus rappio-käsitteeseen.

**Comment by MUUSA-kokous** [comment]
Käyttöhuomautus olisi varmasti hyvä ja siinä viittaus rappio-käsitteeseen.

**Comment by MUUSA-kokous** [comment]
Käyttöhuomautus olisi varmasti hyvä.

**Comment by mariaforsen** [comment]
Ohjaustermi "dekadenssi (kirjallisuuden tyylit) olisi varmaan hyvä piilottaa (jos täytyy säilyttää)

**Comment by tpalonen** [comment]
Ilmeisesti ratkaistu toisaalla, koska käsitteellä ei enää YSOssa ole sulkutarkenteellisia altlabeleja.
