### ISSUE TITLE
Tarpeettomaksi muuttuneen sulkutarkenteen säilyttäminen altLabelina

### ISSUE THREAD

**Issue by satuniininen** [NatLibFi/Finto-data#924]
YSO-kokouksessa 6.4.2018 pohdittiin, tarvitseeko tarpeettomaksi muuttunutta sulkutarkennetta säilyttää  käsitteen altLabelina, vaikkei sitä enää tarvita tekemään eroa toiseen käsitteeseen. 

Taustaa: 
YSOn rukous (toiminta) ja rukoukset (tuotokset) on muutettu YSAssa muotoihin rukoileminen ja rukoukset.

1. Poistetaanko kokonaan sulkutarkenne YSOn käsitteeltä rukoukset (tuotokset), vai siirretäänkö sulkutarkenteellinen muoto altiksi?

2. Entä sulkutarkenne ruotsinkielisessä altLabelissa böner (alster)?

Mikäli sulkutarkenteellisia muotoja halutaan yhä säilyttää, niin voisiko niitä ajatella hiddenLabeleiksi, jotta ne olisivat löydettävissä mutta pysyisivät poissa silmistä.

**Comment by YSO-kokous** [comment]
Päätös:

- Onko tarvetta teknisessä mielessä? Jos ei ole, sulkutarkenteellista muotoa ei tarvitse säilyttää. Käsitellään viikkopalaverissa.

**Comment by mirmaid** [comment]
Finto-viikkopalaveri 24.4.2018:

säilytetään hiddenlabeleina, mietitään vielä tarkempi ominaisuus vrt yksikkömuodot

**Comment by YSO-kokous** [comment]
Käytetään näissä tapauksissa ominaisuutta yso-meta:oldPrefLabel suomeksi ja ruotsiksi. @joelit lisää ko. ominaisuuden.

**Comment by joelit** [comment]
Luodaan kehitysversioon yso-meta:oldPrefLabel, joka julkaistaan Skosifyllä skos:hiddenLabeliksi. Otetaan huomioon uuteen kehitystietomalliin.
