### ISSUE TITLE
työvälineet

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#925]
YSAssa työvälineiden alla ei ole suoraan yksittäisiä työkaluja, vaan ne löytyvät alakäsitteiden alta. YSOssa on siirretty käsitteitä hierarkiassa ylemmäs tai koottu muualta työvälineiden alle joitakin yksinomaan (?) käsikäyttöisiä välineitä, esim. kirves, harava?

**Comment by mirmaid** [comment]
Wikipedia: _Käsityökalu on väline, joka toimii käden jatkeena mm. ruoan valmistamisessa, rakentamisessa, maan muokkauksessa ja koneiden korjauksessa ja valmistuksessa._

**Comment by YSO-kokous** [comment]
Tehdään seuraavat:
haravat, kirveet, vesurit YK käsityökalut
paineilmatyökalut YK sähkötyökalut

Voiko ruuvimeisseli olla sähkötyökalu? Vrt. ruuvinväännin. Tehdään asiasta YSE-issue.
