### ISSUE TITLE
mittarit

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#926]
_Mittarit (mittaus)_ on YSOssa _käyttöön liittyvä rooli_, mutta sillä on alakäsitteitä jotka eivät ole pelkkiä rooleja.

**Comment by YSO-kokous** [comment]
Siirretään alakäsitteet muualle @mirmaid

**Comment by mirmaid** [comment]
Testit, kokeet ovat tapahtumia, mittarit rooli (ominaisuus). Ehdotan että kaikki siirretään yk. objekteihin.

**Comment by mirmaid** [comment]
https://github.com/NatLibFi/Finto-data/issues/727

**Comment by mirmaid** [comment]
Mittarit (mittaus) YK yhteiskunnalliset objektit.
