### ISSUE TITLE
Joidenkin monikkomuotoisten termien turhat sulkutarkenteet

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#928]
Sanastossa on turhia (vanhentuneiden periaatteiden mukaisia) sulkutarkenteita monikkomuotoisten termien kohdalla (silloin kun sama sana löytyy sanastosta myös yksikkömuodossa). Ruotsin osalta osa tarkenteista on jo poistettu. YSAssa ei yleensä ole tarkennetta. Esim. näissä tapauksissa tarkennetta ei välttämättä enää tarvita YSOssakaan:

kansantanssit (tanssit)  KORJATTU -tarkistettu 13.12.2021
elokuvat (teokset)  KORJATTU -tarkistettu 2021
kansat (väestöryhmät)  KORJATTU -tarkistettu 2021
kilpailut (tapahtumat) ISSUE (odottaa käsittelyä) https://github.com/Finto-ehdotus/YSE/issues/7177
kivet (luonnonobjektit) KORJATTU -tarkistettu 2021
muodot (fyysiset ominaisuudet) KORJATTU -tarkistettu 2021
merkitykset (tieto) KORJATTU -tarkistettu 2021
luokitukset  (tieto) KORJATTU -tarkistettu 2021
logot (tuotokset) KORJATTU -tarkistettu 2021
lait (tuotokset) KORJATTU -tarkistettu 2021
kulttuurit (kulttuurimuodot) KORJATTU -tarkistettu 2021
koulut  (oppilaitokset) KORJATTU -tarkistettu 2021
uskonnot (opit) KORJATTU -tarkistettu 2021
unet (mentaaliset objektit) KORJATTU -tarkistettu 2021
organisaatiot (järjestelmät) KORJATTU -tarkistettu 2021
pakkaukset (objektit) KORJATTU -tarkistettu 2021
perheet (ryhmät) KORJATTU -tarkistettu 2021
poliisit (ammatit) KÄSITELTY https://github.com/Finto-ehdotus/YSE/issues/6974
puheet (tuotokset) KORJATTU -tarkistettu 2021
puut (kasvit) KÄSITELTY https://github.com/Finto-ehdotus/YSE/issues/7190
tieteet (erikoisalat) KORJATTU -tarkistettu 2021
valot (tekniset objektit) KORJATTU -tarkistettu 2021
radiot (laitteet) KÄSITELTY
ristit (objektit) KORJATTU -tarkistettu 2021
rukoukset (tuotokset) KORJATTU -tarkistettu 2021
sirkukset (organisaatiot) KORJATTU -tarkistettu 2021
sodat (tapahtumat) KORJATTU -tarkistettu 2021
tasavallat (valtiot) KORJATTU -tarkistettu 2021
televisiot (laitteet) KÄSITELTY
teoriat (tuotokset) KORJATTU -tarkistettu 2021
bibliografiat (luettelot) KORJATTU -tarkistettu 2021

Osa täytynee ratkaista vasta tämän jälkeen: https://github.com/NatLibFi/Finto-data/issues/536
Linjaus: "HUOM! jos preflabel on yksilöivä, sulkutarkenne ei välttämätön erityisesti jos se ei selvennä käsitteen merkitystä"

**Comment by YSO-kokous** [comment]
Haarukoidaan ko. käsitteet sparqlilla.

**Comment by tpalonen** [comment]
- sparql-kysely 1: lista, jossa haetaan sulkutarkenteelliset yso-preffit käsitteillä joilla on myös singularpreflabel
- sparql kysely 2:  lista, jossa  haetaan YSOn sulkutarkenteellisten prefLabelien vastaavat YSA prefLabelit, jossa ei ole sulkutarkennetta

**Comment by tpalonen** [comment]
Sparql-kysely 1:n mukainen lista: YSOn monikkomuotoiset preflabelit, joissa sulkutarkenne:
https://docs.google.com/spreadsheets/d/1UbSaCFLH3y56GRrXe2U5rN8uaN8V3mNrNBRjG1VH_Lo/edit?usp=sharing

**Comment by mariaforsen** [comment]
Suurin osa issuen alussa mainituista tapauksista on ainakin jo ratkaistu (tarkistettu 13.12.21)

**Comment by mirmaid** [comment]
Ja listat pahasti vanhentuneita tässä vaiheessa.

**Comment by mirmaid** [comment]
Ei tarpeen käydä enää listauksia läpi.
