### ISSUE TITLE
Tiet-hierarkiassa olevat yksilökäsitteet: valtatiet yms.

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#930]
YSO-kokouksessa päätetty: deprekoidaan tiet-yksilökäsitteet (Valtatie 5 jne) ja näille uudelleenohjaus YSO-paikkojen vastaaviin. Tuomas toteuttaa tämän. Lisäksi lisätään YSO-paikoissa näille käsitteille uusi yläkäsite tapauskohtaisesti sen mukaan, millä alueella kukin tie on. Mirja toteuttaa tämän.

**Comment by tpalonen** [comment]
Deprekoin ja uudelleenohjasin. Tässä lista kaikista käsitteistä, joille suoritin nämä toimenpiteet.

Eurooppatie E18
Hiidentie
Huovintie
Hämeen härkätie
Jäämerentie
Kehä III
Kuninkaantie
Kyrönkankaantie
Länsiväylä
Pasilanväylä
Pohjanmaan rantatie
Revontultentie
Route 66
Saariston rengastie
Silkkitie
Sininen tie
Suuri Savontie
Suuri rantatie
Valtatie 1
Valtatie 10
Valtatie 12
Valtatie 13
Valtatie 18
Valtatie 2
Valtatie 21
Valtatie 22
Valtatie 3
Valtatie 4
Valtatie 5
Valtatie 6
Valtatie 7
Valtatie 8
Valtatie 9
Ylinen Viipurintie

@mirmaid jatkanee tästä.

**Comment by YSO-kokous** [comment]
Usean valtion alueelle ulottuvat tiet merkitään kunkin valtion alakäsitteeksi. Tämä kirjataan myös Asiakaswikiin YSO-paikkalinjauksiin. Poikkeuksena Silkkitie käsitellään YSO-kokouksessa: kuuluuko YSO-paikkoihin vai YSOon?

Huom! Pasilanväylä (Vrt. Vuotos). Kuuluuko tämäkään YSO-paikkoihin?

**Comment by jarmosaarikko** [comment]
Käsitteeltä https://finto.fi/yso-paikat/fi/page/p99490 puuttuu prefLabel sekä tyyppimerkintä.  Lisäksi alakäsitteet on nyt merkitty skos:narrower -merkinnällä. 
Ehdotan korjattavaksi seuraavasti:
- lisätään prefLabelit  valtatiet{@fi}, highways{@en} ja huvudvägar{@sv}   (ei riksvägar, sillä tässä on myös E-tiet mukana)
- merkitään käsitteen tyypiksi a skos:Collection
- lisätään exactMatch YSO käsitteeseen **valtatiet** http://www.yso.fi/onto/yso/p28219
- lisätään huomautus, että tämä on ryhmittelevä käsite, jota ei käytetä kuvailussa. Kuvailussa käytetään edellä viitattua vastaavaa YSO-käsitettä
- merkitään alakäsitteet (eli yso-paikoissa olevat erilaiset tiet ja väylät) suhteella **skos:member**  skos:narrower ja skos:narrowerPartitive -suhteiden asemesta.
- lisätään alakäsitteille yläkäsitteet ja tarkenteet tämän issuen 17.12.2020 päätöksen mukaisesti

**Comment by mirmaid** [comment]
Kopioitu paikkojen ongelmasivulta kiwistä:

Valtatie 1: Uusimaa, Varsinais-Suomi
Valtatie 2: Uusimaa, Varsinais-Suomi, Kanta-Häme, Satakunta (Pirkanmaa)
Valtatie 3: Uusimaa, Kanta-Häme, Pirkanmaa, Etelä-Pohjanmaa, Pohjanmaa
Valtatie 4: Suomi (TAI Uusimaa, Päijät-Häme, Keski-Suomi, Pohjois-Pohjanmaa, Lappi)
Valtatie 5: Suomi (TAI Päijät-Häme, Etelä-Savo, Pohjois-Savo, Kainuu, Pohjois-Pohjanmaa, Lappi)
Valtatie 6: Suomi (TAI Uusimaa, Kymenlaakso, Etelä- Karjala, Pohjois-Karjala, Kainuu)
Valtatie 7: Uusimaa, Kymenlaakso
Valtatie 8: Varsinais-Suomi, Satakunta, Pohjanmaa, Keski-Pohjanmaa, Pohjois-Pohjanmaa
Valtatie 9: Suomi (TAI Varsinais-Suomi, Kanta-Häme, Pirkanmaa, Keski-Suomi, Etelä-Savo, Pohjois-Savo, Pohjois-Karjala)
Valtatie 10: Varsinais-Suomi, Kanta-Häme
Valtatie 11: Pirkanmaa, Satakunta
Valtatie 12: Satakunta, Pirkanmaa, Kanta-Häme, Päijät-Häme, Kymenlaakso
Valtatie 13: Keski-Pohjanmaa, Pohjanmaa, Keski-Suomi, Etelä-Savo, Etelä-Karjala
Valtatie 14: Etelä-Savo, Etelä-Karjala
Valtatie 15: Kymenlaakso, Etelä-Savo
Valtatie 16: Etelä-Pohjanmaa, Keski-Suomi
Valtatie 18: Keski-Suomi, Etelä-Pohjanmaa, Pohjanmaa
Valtatie 19: Etelä-Pohjanmaa, Pohjanmaa
Valtatie 20: Pohjois-Pohjanmaa
Valtatie 21: Lappi
Valtatie 22: Pohjois-Pohjanmaa, Kainuu
Valtatie 23: Suomi (TAI Satakunta, Pirkanmaa, Keski-Suomi, Etelä-Savo, Pohjois-Savo, Pohjois-Karjala)
Valtatie 24: Päijät-Häme, Keski-Suomi
Valtatie 25: Uusimaa
Valtatie 26: Kymenlaakso, Etelä-Karjala
Valtatie 27: Pohjois-Pohjanmaa, Pohjois-Savo
Valtatie 28: Keski-Pohjanmaa, Pohjois-Pohjanmaa, Kainuu
Valtatie 29: Lappi

**Comment by mirmaid** [comment]
Kopioitu paikkojen ongelmasivulta kiwistä:

Historialliset tiet: huomioidaanko nykyinen kattavuus vai aikaisemmat paikannimet?
Hiidentie: nyt LT Salo (suurin osa tiestä), mutta myös Somero: laitetaanko molemmat kaupungit vai Varsinais-Suomi?
Hämeen Härkätie: Varsinais-Suomi, Kanta-Häme
Jäämerentie: Lappi, entä Venäjän puoleinen osa (Petsamon piiri, ei YSAssa) - tässä myös eroa mitä Jäämerentiellä tarkoitetaan nyt vs. historiallisesti, ja LT voisi olla myös Valtatie 4, jos vain nykykäsitys huomioidaan.
Koiviston museotie |z Äänekoski: väärinpäin yso-paikat/lisätty LT (?), samoin
Peräkunnantie |z Ruovesi
Kuninkaantie ja Sininen tie: Suomi, Norja, Ruotsi, Venäjä
Suuri rantatie: Kuninkaantie (?)
Eurooppatie E18: LT Eurooppa tai Irlanti, Iso-Britannia, Norja, Ruotsi, Suomi, Venäjä
Eurooppatie E63: LT Suomi
Kantatie 51: LT Uusimaa
Kantatie 54: Päijät-Häme, Kanta-Häme
Kehä III: Uusimaa TAI Kirkkonummi, Espoo, Helsinki, Vantaa
Kyrönkankaantie: Suomi (TAI Pohjanmaa, Etelä-Pohjanmaa, Pirkanmaa, (Kanta-Häme? riippuen siitä mitä pidetään alkupisteenä), Satakunta)
Länsiväylä: Uusimaa TAI Helsinki, Espoo, Kirkkonummi
Pohjanmaan rantatie: Suomi, Ruotsi
Porrassalmen museotie: Mikkeli
Revontultentie: Suomi, Ruotsi, Norja
Route 66: Yhdysvallat
Saariston rengastie: Varsinais-Suomi
Suuri Savontie: Kanta-Häme, Päijät-Häme, Etelä-Savo TAI Suomi
Taistelutantereentie: Vöyri
Ylinen Viipurintie: Kanta-Häme, Päijät-Häme, Kymenlaakso, Etelä-Karjala, Viipurin piiri (ei YSAssa) TAI Suomi, Venäjä

**Comment by mirmaid** [comment]
Kopioitu paikkojen ongelmasivulta kiwistä:

Lisätäänkö näille [teille] tyyppi ja alkupisteeseen linkki (entä loppupisteeseen), jos löytyy?

**Comment by mirmaid** [comment]
Kopioitu paikkojen ongelmasivulta kiwistä:

Samoin vesiväylät:
kanavat-termin alakäsitteet, Koillisväylä, Luoteisväylä, Äänekoski-Vaajakoski-vesiväylä

**Comment by mirmaid** [comment]
https://github.com/NatLibFi/Finto-data/issues/905#issuecomment-363757037

**Comment by mirmaid** [comment]
Valtatiet: jos tie kulkee kokonaan tietyn maakunnan (tai kunnan) alueella, se merkitään yläkäsitteeksi. Muussa tapauksessa yläkäsitteeksi merkitään valtio ja maakunnat RT:ksi. 

Useamman valtion alueella kulkevan tien yläkäsitteeksi merkitään maanosa ja RT:ksi valtiot.

**Comment by mirmaid** [comment]
^ Tehdään muutama esimerkki molemmilla tavoilla. Palataan asiaan huomenna.

**Comment by mirmaid** [comment]
Useamman valtion alueella kulkevan tien yläkäsite on maanosa, paitsi jos kyse on kahden valtion alueella kulkevasta tiestä, tällöin merkitään ko. valtiot. Useamman maakunnan alueella kulkevan tien yläkäsite on valtio. Yhden Suomen maakunnan alueella kulkevan tien yläkäsite on maakunta. Yhden Suomen kunnan alueella kulkevan tien yläkäsite on kunta. Ulkomaisten teiden yläkäsite on aina valtio tai maanosa.

**Comment by mirmaid** [comment]
Vielä:
- Jäämerentie: Lappi, entä Venäjän puoleinen osa (Petsamon piiri, ei YSAssa) - tässä myös eroa mitä Jäämerentiellä tarkoitetaan nyt vs. historiallisesti, ja LT voisi olla myös Valtatie 4, jos vain nykykäsitys huomioidaan.

- Suuri rantatie: Kuninkaantie (?)

- Koiviston museotie |z Äänekoski: väärinpäin yso-paikat, samoin Peräkunnantie |z Ruovesi (näille varmaan konversiossa tullut virheellisesti tarkenne, poistetaanko?)

**Comment by mirmaid** [comment]
Vesiväylät:
kanavat-termin alakäsitteet, Koillisväylä, Luoteisväylä, Äänekoski-Vaajakoski-vesiväylä

Näiden hierarkia?

**Comment by mirmaid** [comment]
Koiviston museotie |z Äänekoski: väärinpäin yso-paikat, samoin Peräkunnantie |z Ruovesi (näille varmaan konversiossa tullut virheellisesti tarkenne, poistetaanko?): poistetaan tarkenteet

**Comment by ilona-x** [comment]
> Vesiväylät: kanavat-termin alakäsitteet

Laitan tähän näkyviin listan YSA:n kanavat termin alakäsitteistä ja niiden nykyisistä yläkäsitteistä YSO-paikoissa:

Keiteleen kanava (ei yläkäsitettä)
Kymijoen kanava (ei yläkäsitettä, kanavaa ei ole rakennettu (tästä on poistoehdotus YSE:ssä https://github.com/Finto-ehdotus/YSE/issues/12643 )
Lempäälän kanava (yläkäsite Lempäälä)
Mäntyharjun kanava (poistettu YSO-paikoista, sillä kanavaa ei ole rakennettu)
Panaman kanava (ei yläkäsitettä)
Rikalan kanava (ei yläkäsitettä)
Saimaan kanava (YK Lappeenranta & Venäjä)
Strömman kanava (YK Kemiönsaari)
Suezin kanava (ei yläkäsitettä)
Taipaleen kanava (YK Varkaus (kaupunki))
Varkaantaipaleen kanava (YK Mikkeli)

**Comment by mirmaid** [comment]
Kanavien yläkäsite samalla periaatteella kuin teiden.
Pyhän Henrikin tie ja Pyhän Olavin reitti - kuten tiet
Vesireitit: yläkäsite vesistö
Koillisväylä, Luoteisväylä: YK valtameret

**Comment by mirmaid** [comment]
Jokien hierarkia: ehdotettu, että MML:stä tulevat yläkäsitteet muutettaisiin RT-suhteiksi, jolloin myös suurimmilla joilla voisi olla vastaava suhde. Ehdotettu myös, että jokien hierarkia voisi olla samankaltainen kuin teillä, mutta että tieto yläkäsitteistä lisätään sen mukaan, mikä on helposti varmistettavissa. Palataan tähän syksyllä.

**Comment by mirmaid** [comment]
Ratkaistu issuessa https://github.com/NatLibFi/Finto-data/issues/913.
