### ISSUE TITLE
juhlajulkaisut (http://www.yso.fi/onto/yso/p18076) - ruotsiksi ja suomeksi eri käsite

### ISSUE THREAD

**Issue by MikkoAleksanteri** [NatLibFi/Finto-data#931]
YSO-kokouksessa todettua:

juhlajulkaisut kattavat suomeksi kaikki julkaisutyypit, ja tämän alle olisi haluttu esim. juhlajulkaisulevyt (tribuutit). Ruotsiksi kuitenkin "festskrifter" eli vain kirjallinen aineisto.

**Comment by mariaforsen** [comment]
Festskrifter on erittäin tärkeä ja paljon käytetty termi (myös MDO, Genre jne.) Jos todella halutaan muutoksia yksi mahdollinen ratkaisu on ottaa juhlakirjat=festskrifter ja luoda juhlajulkaisuille vastineeksi "jubileumspublikationer". Koska sitä ei kuitenkaan juuri käytetä (vaan festskrifter) olisi sitten tärkeää ohjata myös suomeksi käyttämään tarkempi termi juhlakirjat aina kun aineisto koskee niitä (muuten vaarana on se että suomeksi käytetään jatkossakin lähinnä juhlajulkaisut, mutta ruotsiksi käytetään aina festskrifter). Jos tehdään muutoksia tähän, se vaatii myös laajoja korjauksia tietokantoihin.

**Comment by mariaforsen** [comment]
https://github.com/Finto-ehdotus/YSE/issues/7413
