### ISSUE TITLE
sairaus

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#934]
Kielitoimiston sanakirja: elimistön t. psyykkisen toiminnan häiriö (joka tuottaa fyysistä, psyykkistä t. sosiaalista haittaa), tauti; sairaana olo. 

Oliko tämän tarkoitus viitata sairaana oloon? Nyt käyttäjä (joka ei ole täysin perehtynyt sääntöihin) voi yhtä hyvin tulkita tämän taudin synonyminä, eli "elimistön t. psyykkisen toiminnan häiriö". Sanastossa on myös taudit. Olisiko syytä tarkentaa esim. tarkenteella tms. muutoksia? Tilanne ruotsiksi on: sjukdom (tillstånd)=sairaus ja sjukdomar=taudit. Eli epäselvää käyttäjälle.

**Comment by jarmosaarikko** [comment]
Kielitoimiston sanakirja: 
**tauti** (määritettävissä oleva) **sairaus**. 
**tautinen**  1. jossa t. jolla on jk tauti, **sairas**. 
**tautivuode** us. ylät. **sairasvuode**. Joutua tautivuoteeseen.

**Comment by satuniininen** [comment]
Itse lähtisin purkamaan tätä kartoittamalla ensin käsillä olevat vaihtoehdot. Nähdäkseni meillä on ainakin kaksi erilaista lähestymistapaa, eli 

1. selventävä ja taudeista erottava lisämääre, esim.
- sairaus (tila)
- sairaus (olotila)
- sairaus (sairastaminen)
- sairaus ja sairastaminen

2. yhdistäminen sairaus + taudit
- sairaus KT taudit (näin Meshissä)

Käytetty Melindassa 2110 kertaa, usein terveyden tai terveydentilan vastakohtana. Näkökulmia on useita kokemuksellisuudesta terveyssosiologiaan ja kaikkeen siltä väliltä.

**Comment by YSO-kokous** [comment]
Tehdään YSE-ehdotus. Yhdistäminen/poistaminen ei vaikuta mahdolliselta.

**Comment by satuniininen** [comment]
https://github.com/Finto-ehdotus/YSE/issues/6909
