### ISSUE TITLE
Kirkkoherrat, kappalaiset & papit

### ISSUE THREAD

**Issue by jarmosaarikko** [NatLibFi/Finto-data#935]
**Kirkkoherralle** http://www.yso.fi/onto/yso/p6345  on nyt eng. vastineena "parish ministers",   
Voisiko kuitenkin olla "vicars".  LCSH vastine "Vicars, parochial" http://id.loc.gov/authorities/subjects/sh85143146

**papit** http://www.yso.fi/onto/yso/p5468
Voisiko **ministers (church)** tai sitten tuo **parish ministers** lisätä englanninkieliseksi ohjaustermiksi 

Nyt siellä on englannikielisenä vastineena **clergymen**, joka minun mielestäni on huono, kun papit voivat olla naisiakin.  Clergymen näyttäisi myös olevan ohjaustermi käsitteelle Clergy (papisto).
LCSH:ssa on myös **Priests** http://id.loc.gov/authorities/subjects/sh85106637, jonka ohjausterminä **Pastors**.  eli samalla tavalla kuin YSO:ssakin eli sopisiko ehkä paremmin eng. vastineeksi?
Editorial Notes: subdivision [Clergy] under individual Christian denominations, e.g. [Catholic Church--Clergy].  

**kappalaiset** http://www.yso.fi/onto/yso/p6346 
Tämän yläkäsite voisi olla kirkon työntekijät http://www.yso.fi/onto/yso/p2488  kuten papeillakin.

**Comment by satuniininen** [comment]
Siltauksia ja en-vastineita tarkistettu.
