### ISSUE TITLE
kehitysvammaisuus, kehitysvammat

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#936]
Sanastossa on molemmat, mutta niiden välillä ei ole edes RT-suhdetta. Miten nämä on tarkoitus käyttää? Ruotsiksi kehitysvamma + kehitysvammaisuus + kehityshäiriö = utvecklingsstörning, muutoksia vaaditaan. 

Näyttää siltä että kehitysvammaisuus ja kehitysvamma käsitellään monesti samana asiana, ks. esim. http://verneri.net/yleis/kehityshairio-ja-kehitysvammaisuus http://www.kvtietopankki.fi/kehitysvammaisuus https://fi.wikipedia.org/wiki/Kehitysvamma

**Comment by YSO-kokous** [comment]
Tehdään ehdotus kehitysvammat, kehitysvammaisuus KÄ kehityshäiriöt.

**Comment by satuniininen** [comment]
https://github.com/Finto-ehdotus/YSE/issues/6677

**Comment by mariaforsen** [comment]
Kehitysvammaisuus on nyt poistettu joten siltä osin ongelma on ratkaistu.
