### ISSUE TITLE
bioala

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#937]
Mihin tämä viittaa? Ei sanastoissa. Käytetty vain vähän Melindassa. Nykyinen ruotsinnos "biologiska området" epävarma.

**Comment by mirmaid** [comment]
Eikö tämä olis enemmänkin biobranschen?

**Comment by mariaforsen** [comment]
Nimenomaan, mutta biobranschen on ruotsiksi eri tavoilla/merkityksissä käytetty ja viittaa ennen kaikkea elokuvateatterialaan, joten tarvitaan tarkennetta ja sen takia täytyy tietää mihin tarkalleen viittaa.

**Comment by YSO-kokous** [comment]
KT biotekninen ala, biotekniikan ala (vai päätermiksi?), sv. biotekniska branschen

@mirmaid tekee YSE-issuen

**Comment by mariaforsen** [comment]
Ehdotus tehty: https://github.com/Finto-ehdotus/YSE/issues/7260
