### ISSUE TITLE
jälkihuolto, jälkihoito

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#938]
Ruotsiksi täytynee lisätä tarkenteita (eftervård (socialvård), eftervård (sjukvård)?), mutta onko kaikille selvää miten nämä käytetään? Toisen ryhmä on kuitenkin myös 00, eikä määritelmiä ole. Voidaanko olettaa että jälkihuolto käytetään vain ja ainoastaan sosiaalipalveluista ja jälkihoito vain ja ainoastaan sairaanhoidosta? Näin ei valitettavasti näytä olevan Melindassa. Muita tarkenne-ehdotuksia?

**Comment by mirmaid** [comment]
Molempia käytetään varmaan mistä vaan, mutta voidaanko rajata kun ei hoitoa ja huoltoakaan ole rajattu?

**Comment by satuniininen** [comment]
Entä jos **jälkihoidosta** otettaisiin pois lääketieteen ryhmä ja jätettäisiin pelkkä 00? Tällöin lavean käytön ei pitäisi olla mikään ongelma. 

**Jälkihuoltoa** sen sijaan on käytetty varsin yhdenmukaisesti sosiaalihuollon yhteydessä, joten en ihan suorilta olisi valmis yhdistämään sitä jälkihoitoon. Olisiko mitään mahdollisuutta saada sitä ilmaistua ruotsiksi jollain muulla termillä/fraasilla, jotta **jälkihoitoon** voisi jäädä pelkkä **eftervård** ilman tarvetta sulkutarkenteelle?

**Comment by YSO-kokous** [comment]
Lisätään määritelmä tai käyttöhuomautus _jälkihuolto_-termille.

**Comment by satuniininen** [comment]
Tarkoittaa sosiaalihuollon tarjoamia tukitoimia esimerkiksi sijaishuollon päättymisen tai vankilasta vapautumisen jälkeen.

@mirmaid

**Comment by mariaforsen** [comment]
Määritelmä puuttuu vielä. Lisään tarkenne "socialvård" kun termi on määritelty siihen myös suomeksi.
