### ISSUE TITLE
reflektioteoria

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#940]
YSO eng. "reflection theory" mutta onko todella näin, vai miten laaja tämän termin merkitys on tarkoitus olla? Onko se oikeastaan "reflection theory of compensation"? Eli nimeomaan Thierryn luoma teoria? Suom. KT palkitsemisen reflektioteoria ja yläkäsite psykologiset teoriat.  

Pelkkä "reflection theory" näyttää viittaavan laajemmin: 
"Reflection theory is the idea that our knowledge reflects the 'real world'." http://www.qualityresearchinternational.com/socialresearch/reflectiontheory.htm

Ruotsiksi ei käännöstä, mutta jos todella on kyseessä nimenomaan Thierryn "reflection theory of compensation" niin laitetaan se mahdollisesti lainaterminä.

Ks. https://books.google.fi/books?id=kd7IYC4-o3sC&pg=PT26&lpg=PT26&dq=%22reflectiontheory%22+henk+%22thierry%22&source=bl&ots=Cy5olD8a_W&sig=19ihjxXsa3I2o6sko2HxTrTiF70&hl=en&sa=X&ved=0ahUKEwifktaLqdPSAhUFfywKHXYsCq4Q6AEIGjAA#v=onepage&q=%22reflectiontheory%22%20henk%20%22thierry%22&f=false

https://www.tritonia.fi/fi/e-opinnaytteet/tiivistelma/6798

**Comment by satuniininen** [comment]
Melindassa tätä on käytetty vain kahdessa aineistossa, jotka molemmat käsittelevät palkitsemisen reflektioteoriaa. Jos halutaan kuitenkin säilyttää laajemmassa merkityksessä niin ryhmät ja suhteet pitäisi miettiä uudestaan.

Muutetaan reflektioteoria KÄ palkitsemisen reflektioteoria?

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/6676

**Comment by satuniininen** [comment]
Melindassa neljä kertaa, joista kolme käsittelee palkitsemisen reklektioteoriaa. 

Neljännessä (https://melinda.kansalliskirjasto.fi/byid/001787882) asiasanoina sekä reflektioteoria että reflektiivisyysteoria. Onkohan tässä kyseessä joku tietty yhtenäinen teoria vai riittäisikö esim. reflektio?
