### ISSUE TITLE
politiikka-termien ysa-ryhmät

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#941]
Osalla politiikka-käsitteen alakäsitteistä ei ole ryhmää _65 Valtio-oppi. Politiikka. Kansainvälinen politiikka_. Lisätäänkö?

Näille mahdollisesti ei: datapolitiikka, henkilöstöpolitiikka, kokoelmapolitiikka, näyttelypolitiikka, tuotepolitiikka (yhteisön sisäinen politiikka)
Myös: informaatiopolitiikka (?), ohjelmapolitiikka (?), kustannuspolitiikka (?) - samanlaisia kuin edelliset, mutta tulevat jo lähemmäs "varsinaista" politiikkaa

**Comment by YSO-kokous** [comment]
Ei seuraaville: datapolitiikka, henkilöstöpolitiikka, kokoelmapolitiikka, näyttelypolitiikka, tuotepolitiikka, kustannuspolitiikka.
