### ISSUE TITLE
sitoutuminen

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#943]
Käytetty jonkin verran (ehkä n. 5-10% viitteistä) kemian kontekstissa (usein esim. lääkeaineista). MeSHissä on _proteiineihin sitoutuminen_, en osaa sanoa soveltuuko se aina. YSAssa on _kemialliset sidokset_, mutta se saattaa tuntua vaikealta käyttää jos tutkimuskohteena on esim. osteoporoosilääkkeen sitoutuminen luuhun tms.

**Comment by YSO-kokous** [comment]
Ruotsiksi ei löydy yhtä laajamerkityksistä termiä. Mahdollisia tarkenteita suomenkieliselle (psykologia), (psyykkinen), (mentaalinen toiminta). Lisäksi sitoutuminen (kemia)? Tarvitaanko muuta?
