### ISSUE TITLE
rakennukset 

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#944]
Muutetaanko kaikki YSOn rakennukset yhteisöiksi?

**Comment by mirmaid** [comment]
Edelleen omasta mielestäni ristiriitaista, että Idän pikajuna tai Air Force One on auktorisoitu LCSH:ssa käsitteinä (150), jos yksittäiset rakennukset kuitenkin käsitellään aina yhteisöinä...

**Comment by ksornova** [comment]
Tässä LC:n ohjeistus vuodelta 2017: Buildings and other structures H1334
https://www.loc.gov/aba/publications/FreeSHM/H1334.pdf

**Comment by ksornova** [comment]
mitä tulee näihin alusten, laivojen, junien tms. nimiin, RDA:ssa, hakutiedoissa ja AACR2:ssa löytyy samanlaiset ohjeet (katso alla). Sen sijaan nykyisestä RDA:n beta-versiosta en ole löytänyt mitään mainintoja tästä (toisaalta ohjeet vielä työn alla).

**RDA** 
11. 0 Ad hoc events (e.g., athletic contests, exhibitions, expeditions, fairs, and festivals) and **vessels (e.g., ships and spacecraft) are considered to be corporate bodies.**

**Hakutiedot 21.1.2.1, s. 27**
…**yhteisöjä ovat** tiettyä tehtävää tai tarkoitusta varten toimeenpannut, nk. ad hoc -tapahtumat, kuten urheilukilpailut, näyttelyt, messut ja festivaalit sekä **alukset yms. (AACR2 21.1B1).** 

**AACR 24.1A**
Ambiguous Entities
Treat the ambiguous entities (entities that could be treated as either name headings or subject headings) listed below **as general corporate bodies** and establish them under the provisions of chapter 24, AACR2, **tagging them as X10**.
…
Airplanes, Named
Ships
Space vehicles
…

**Comment by mirmaid** [comment]
Odotetaan RDA:n ratkaisua.
