### ISSUE TITLE
keräsalaatti

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#948]
Mihin tarkalleen viittaa? Latinankielinen nimi? Allärsissa jostain syystä plocksallad, mutta se ei taida olla oikein. Vrt. eng. cabbage lettuce

**Comment by mirmaid** [comment]
Mun käsitykseni vastaa tätä: https://www.iltalehti.fi/pippuri/2014121918923443_ah.shtml, mutta näköjään käytetään myös yleisnimenä kerän muotoisille, esim. jäävuorisalaatti jne.

Tällainenkin löytyi: https://hyotykasviyhdistys.fi/tuote-osasto/siemenet/vihannekset/salaatit/kerasalaatti/

**Comment by mariaforsen** [comment]
Jos kyseessä todella lat. "Lactuca sativa var. capitata"=sv. huvudsallat. Jos vain "Lactuca sativa"=sv. sallat.

**Comment by mirmaid** [comment]
Siivotaan salaattien hierarkia, konsultoidaan Kassua/Päiviä ym.

**Comment by ilona-x** [comment]
Onkohan YSO-termin salaattikasvit tarkoitus viitata tähän: Salaatit – Lactuca - sallater (sv)   https://laji.fi/taxon/MX.39939/taxonomy

Salaattien (Lactuca) alta löytyy puolestaan: Salaatti (ruokasalaatti) – Lactuca sativa - trädgårdssallat (sv)  https://laji.fi/taxon/MX.40788/taxonomy

Ja tämän alta:
parsasalaatit (Lactuca sativa Asparagina-Ryhmä) sparrissallat (sv) 
keräsalaatit (Lactuca sativa Capitata-Ryhmä) huvudsallat (sv) 
lehtisalaatit (Lactuca sativa Crispa-Ryhmä) plocksallat (sv) 
sidesalaatit (Lactuca sativa Romana-Ryhmä) bindsallat (sv)

**Comment by mirmaid** [comment]
Salaatit (kasvit) KÄ salaattikasvit. Lisätään latinalaiset nimet.

**Comment by mariaforsen** [comment]
Sen jälkeen kun latinalaiset nimet on lisätty suomeksi, käydään läpi ruotsin osalta ja tarkistetaan että vastineet ovat oikeat.

**Comment by mirmaid** [comment]
Katsotaan tämä vielä yhdessä.

**Comment by mirmaid** [comment]
Keräsalaatti on kyllä sikäli hankala, että sille varsinaiselle keräsalaatille ei ole muuta tarkempaa nimeä, mutta myös muita keränmuotoisia salaatteja nimitetään toisinaan keräsalaateiksi. Eli varmaan pakko hyväksyä laajempi tulkinta tai poistaa kokonaan.

**Comment by mirmaid** [comment]
^^ Lisätään tarkenne salaatit (ruokalajit). 

salaattikasvit > salaatti (salaattikasvit) (lat. Lactuca sativa)
keräsalaatti lt. Lactuca sativa Capitata-ryhmä
lehtisalaatti lt. Lactuca sativa Crispa-ryhmä

**Comment by mariaforsen** [comment]
Sv. lehtisalaatti= sallat > plocksallat (=var. crispa)
