### ISSUE TITLE
arvet

### ISSUE THREAD

**Issue by jarmosaarikko** [NatLibFi/Finto-data#949]
liittyen 3.9. yso-kokouksessa pohdittuun  
voisiko lisätä  **arvet** RT  **fibroosi** ja päinvasoin
**fibroosi** KT _sidekudostuminen_, _arpeutuminen_     RT **arvet**

Terveyskirjasto:
**arpi** cicatrix; parantunut vaurioalue, jossa kudos on korvautunut runsaskollageenisella sidekudoksella;

**Comment by mariaforsen** [comment]
Mesh: fibroosi alakäsite arpi, mutta siinä taitaa olla eri hierarkiaperiaatteita. Kun kuitenkin Meshissä ovat tällä tavoin linkattu toisiinsa niin olisi kai RT-suhde ok YSOssa.
