### ISSUE TITLE
Diminuutio

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#950]
Musiikkialan käsite. Määritelmä "Sävelten (äänten) aika-arvojen rytmillinen tihentyminen, jonka vastakohta on additio." LT sävellysoppi ja rytmioppi

Ongelma: Diminuutio ei ole eräänlainen sävellysoppi tai eräänlainen rytmioppi (tai näiden oppien alahaara) Eli pitäisi miettiä LT uusiksi. Yksi ratkaisu yläkäsitteeksi voisi olla kulttuuriset ominaisuudet. Diminuution kai voi tulkita olevan sävelteoksen ominaisuus?

**Comment by tpalonen** [comment]
PÄÄTÖS:

    ehdotetaan uutta käsitettä "sävellystekniikka", joka tulisi tälle yläkäsitteeksi
    lisätään RT ﻿ornamentiikka

**Comment by mariaforsen** [comment]
Ratkaistu ja toteutettu YSOssa.
