### ISSUE TITLE
Intervallit

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#951]
Musiikkikäsite. 
Nykyinen LT säveljärjestelmät ei ole sopiva YSOn kannalta. Vrt. määritelmä: "Kahden sävelkorkeuden tai äänitaajuuden välinen etäisyys". Olisiko tämä kulttuurinen ominaisuus?

**Comment by YSO-kokous** [comment]
ks. myös _taiteisiin liittyvät abstraktit objektit_ ja _kulttuuriset objektit_ (jonka alla _musiikilliset tuotokset_)

**Comment by jarmosaarikko** [comment]
**intervalli** ei ole säveljärjestelmä. Se on kahden taajuuden välinen ero. Sopisi kohtaan **fyysiset ominaisuudet** http://www.yso.fi/onto/yso/p1400   "Kvantitatiivisia, aineelliseen liittyviä ominaisuuksia, joita tyypillisesti mitataan mittayksiköin. Voivat liittyä elolliseen tai elottomaan olioon."  mittayksiköt intervalleissa lienevät sävelaskeleita?

**Comment by mariaforsen** [comment]
On ratkaistu: LT fysikaaliset ominaisuudet
