### ISSUE TITLE
kasvien ja eläinten laji/suku

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#952]
Mietitään johdonmukaisia sääntöjä ruotsiksi. Todennäköisesti erotetaan sulkutarkenteella, mutta tultiin myös siihen tulokseen että yksikkömuodon kohdalla ei oikeastaan ole tarvetta tarkenteelle (koska se on sellaisenaan selkeä, eikä voi viitata sukuun tms.) ?

Esimerkkitapaus:
kottarainen, kottaraiset (heimo) 
sv. stare, starar (familj) 
-eli kottarainen ja stare ovat sellaisenaan selkeitä ilman tarkenteita, koska jos kyseessä on heimo/suku niin sana on monikossa, lukija ei siis voi vahingossakaan tehdä sellaista virhepäätelmää että "kottarainen" viittaisi kottaraisheimoon?

Miten suomeksi toimitaan? Yleensähän olemme päättäneet että monikko-muodolle ei laiteta tarkenteita, silloin kun se on selkeä ilman, mutta lajien kohdalla asia on toisin päin, eli yksikkömuoto on selkeä, mutta monikkomuoto voi viitata molempiin (tässä tapauksessa kyseessä useita kottaraisia TAI kottaraisheimo).

Standardin (ja linjauksemme) mukaan pitää välttää turhia tarkenteita.

**Comment by YSO-kokous** [comment]
Monikkomuotoisten heimojen ja sukujen yksikkömuotojen lisäämisestä sekä yksikkömuotojen sulkutarkenteista tarvitaan linjaus YSOn kehityslinjauksiin.

**Comment by mariaforsen** [comment]
Missä foorumissa tämä käsitellään seuraavaksi?
Tässä https://www.kiwi.fi/display/Asiasanastotjaontologiat/YSOn+kehityslinjaukset ei näytä olevan vielä linjausta.

**Comment by tpalonen** [comment]
Katsotaan saataisiinko mahtumaan ensi OY:n asialistalle. Huomasin kehityslinjauksista muutenkin muutaman puutteen, jotka pitäisi lisätä. Kehityslinjauksissa ei esim. ole, että jokaisella käsitteellä tulee olla jokin yläkäsite.

**Comment by mirmaid** [comment]
Otetaan vielä kevään OY-kokoukseen. Tuomas lisää esityslistaluonnokseen.

**Comment by mirmaid** [comment]
Jatketaan nykyistä käytäntöä (laji), (suku) ja (heimo) -tarkenteiden käytössä.
