### ISSUE TITLE
valokuvaus valoherkille materiaaleille

### ISSUE THREAD

**Issue by MUUSA-kokous** [NatLibFi/Finto-data#955]
Tämä on jo olemukseltaan hieman kryptinen käsite, koska on ryhmittelevä käsite, mutta ei vastaa termimuodoltaan muita ryhmitteleviä käsitteitä. Ilmeisesti tähän on otettu mallia VALO-ontologiasta. Alakäsitteitä ovat:

dagerrotypia
lämpökuvaus
mikrokuvaus
satelliittikuvaus
stereokuvaus

Näistä kuitenkin sateliittikuvaus ja stereokuvaus eivät liene oikein? Toisaalta löytyy myös ryhmittelevä käsite "valokuvaus tekniikan mukaan", jonka luulisi riittävän ryhmittelyyn.

EHDOTUS: Poistetaan "valokuvaus valoherkille materiaaleille" ja hierarkisoidaan alla olevat uudelleen valokuvaus-hierarkiassa.

**Comment by mirmaid** [comment]
Poistetaan ko. ryhmittelevä käsite, alakäsitteet valokuvaus tekniikan mukaan -alle. Hyvä avaus Muusalta, näitä lisää!
