### ISSUE TITLE
toteaminen

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#956]
Toiminta-hierarkiaa läpikäydessä kirjattu "tehtäneen issue". Käytetty Melindassa 10 kertaa: 2 x kuoleman toteaminen, 2 x lukihäiriön toteaminen, kerran osteoporoosin toteaminen, 2 x mikrobien toteaminen (vain toinen lääketiedettä), kerran syyllisyyden (?) toteaminen, kerran laadun (?) toteaminen. Kerran asiasanana on "vakaumuksen toteaminen".

Osaan sopii _diagnostiikka_, joihinkin _määritys_, jotkut eivät tarvitse mitään termiä toteamisen tilalle. Kuoleman toteamiseen nämä eivät sovi, en osaa sanoa tarvitaanko välttämättä jotain termiä. _Tutkimus_ voisi ehkä sopia.

**Comment by mariaforsen** [comment]
Ruotsin osalta tämä ei ollut ongelmallinen. Onko tämä nyt tarkoitus poistaa?
