### ISSUE TITLE
rakennushallinto

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#959]
finto-palaute "Kansalliskarkistosta on tullut palautetta siitä, että rakennushallinto (http://www.yso.fi/onto/yso/p18754) on väärässä paikassa valtiovarainhalinnon alakäsitteenä.Eivät sanonneet, mihin se kuuluisi, mutta olisiko halinnonalojen alle (http://www.yso.fi/onto/yso/p3954)?"

Kun muutos on tehty, laitetaan viestiä Katerinalle.

**Comment by mirmaid** [comment]
Käsitellään YSO-kokouksessa, laitetaan viestiä Katerinalle, että käsittely jatkuu siellä.
