### ISSUE TITLE
YSA/Allärs-termeillä useita YSO-vastineita

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#960]
vahvistus https://github.com/Finto-ehdotus/YSE/issues/5160 - **korjattu**
siirto https://github.com/Finto-ehdotus/YSE/issues/6929 - **korjattu**
tunnustus https://github.com/Finto-ehdotus/YSE/issues/5484 - **korjattu**
ajoitus https://github.com/Finto-ehdotus/YSE/issues/5449 - **korjattu**
äidinkieli https://github.com/Finto-ehdotus/YSE/issues/5232 - **korjattu**
itsenäisyys (yksilöt) - **korjattu**
flamenco - **korjattu**
MP3 - **korjattu**
Grafis V6 - **korjattu**
purkaminen (osiin) - **korjattu**
tekniikka https://github.com/Finto-ehdotus/YSE/issues/6931 - **korjattu**
verkkokauppa https://github.com/Finto-ehdotus/YSE/issues/5217 - **korjattu**
lehtorit https://github.com/Finto-ehdotus/YSE/issues/6930 - **korjattu**
akustiikka https://github.com/Finto-ehdotus/YSE/issues/5324 - **korjattu**
Fle3 Tuomas deprekoi käsitteen Fle (tietokoneohjelmat) - **korjattu**
vetäytyminen https://github.com/Finto-ehdotus/YSE/issues/5776 - **korjattu**
formalismi https://github.com/Finto-ehdotus/YSE/issues/6932 - **korjattu**
kalvot https://github.com/Finto-ehdotus/YSE/issues/5773 - **korjattu**
hallitukset (valtiot) - **korjattu**
cha-cha-chat (sävellykset) - **korjattu**
ääni (ihmisääni) https://github.com/Finto-ehdotus/YSE/issues/5427 - **korjattu**
vastaanottotoiminta https://github.com/Finto-ehdotus/YSE/issues/4789 - **korjattu**
esteet https://github.com/NatLibFi/Finto-data/issues/841 - **korjattu**
estetismi https://github.com/Finto-ehdotus/YSE/issues/6626 - **korjattu**
sovellukset (tietotekniikka) https://github.com/Finto-ehdotus/YSE/issues/5159 - **korjattu**
hyvinvointi https://github.com/Finto-ehdotus/YSE/issues/6933 - **korjattu**
piirustukset https://github.com/Finto-ehdotus/YSE/issues/5147 - **korjattu**

**Deprekoidaan, replacedBy-suhde YSO-paikat-käsitteeseen.**
Penedo
Äänekoski-Vaajakoski-vesiväylä
Luoteisväylä
Varkaantaipaleen kanava
Taipaleen kanava
Koillisväylä
Suezin kanava
Rikalan kanava
Keiteleen kanava
Kymijoen kanava
Strömman kanava
Mäntyharjun kanava
Lempäälän kanava
Panaman kanava
Saimaan kanava
Saimaan syväväylä

**Comment by mirmaid** [comment]
näthandel

symönster

lektorer

regeringar

Grafis V6

Varkaantaipale kanal

Saimens djupfarled

akustik

membran

Panamakanalen

esteticism

intermezzon (instrumentalmusik)

människan

Suezkanalen

hinder

MP3

Saima kanal

araliaväxter

Nordvästpassagen

självständighet (individer)

gränssnitt

Fle3

flamenco

tillbakadragande

Keitele kanal

cha-cha-cha (kompositioner)

formalism

Mäntyharju kanal

röst

Strömma kanal

Kymmene älvs kanal

Taipale kanal

modersmål

Rikala kanal

Nordostpassagen

erkännande

Penedo

vattenväg Äänekoski-Vaajakoski

teknik

datering

applikationer

Lempäälä kanal

samba (danser)

Koskis gård (Koskis)

**Comment by tpalonen** [comment]
Sointulaa ei deprekoida? Vrt. Penedo.

**Comment by tpalonen** [comment]
Konsultoin Muusa-ryhmäläisiä flamencosta. Päätös: säilytetään käsitteet nykyisellään eli "flamenco (tanssi)" ja "flamenco (perinnemusiikki)".

**Comment by mirmaid** [comment]
Sointula muutettu paikaksi.

**Comment by YSO-kokous** [comment]
Tehdään näistä YSE-issuet:

Kehärata
Muurmannin rata
Pisararata
Rantarata
Siperian rata
Runoilijan tie
Piilaakso
Suvilahti
Vuotos [muista poiketen tämä voinee jäädä YSOon, mutta termimuotoa sekä yläkäsitettä voisi miettiä uudestaan]

Tehdään YSE-issue(t) myös näistä käsitteistä: luonnonsuojelualueet, kansallispuistot ja lentoasemat.

**Comment by mirmaid** [comment]
^ Suvilahti on jo ratkaistu, tosin YSA-linkki puuttuu (voisi ehkä lisätä). 

151 | __ \|a Santa Clara Valley (Santa Clara County, Calif.)
451 | __ \|a Silicon Valley (Calif.)

**Comment by mirmaid** [comment]
- siirrretään rautatiet ja Runoilijan tie & Piilaakso YSO-paikkoihin
- Vuotos, Pisararata - YK rakennushankkeet, RT nykyisiin yläkäsitteisiin
- Suvilahdelle YSA-linkki
- luonnonsuojelualueet, kansallispuistot > issuet
- lentoasemat: odottaa Kanton monikielisyyden toteutumista

**Comment by mirmaid** [comment]
Huom.
Varmaan myös Via Baltica...onkohan vielä muita?

**Comment by mirmaid** [comment]
Wikipedia erottaa Santa Clara Valleyn ja Piilaakson?
