### ISSUE TITLE
YSAssa/Allärsissa ja YSOssa eri prefLabel

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#961]
YSA
https://docs.google.com/spreadsheets/d/1OI18aZSC3H-FRsmUsov66CYrDwGkQL_iCJiT8hawJaI/edit#gid=221987467

**Comment by mirmaid** [comment]
Allärs
https://docs.google.com/spreadsheets/d/17juWidMd27CoD5Z4bF2AHKIAiAMKF4pUzHTkt-pV_Jg/edit#gid=1355513329

**Comment by mirmaid** [comment]
Osa listan termeistä on muuttuneissa, osa ok ilman muutosta (muutos voidaan tehdä konversiossa). Osa on esim. yksikkö/monikko-tapauksia, jotka kannattaa käydä läpi yhdessä. 

Selkeät tapaukset (esim. päivittimen skippaama prefLabel-muutos) voisin varmaankin korjata ilman yhteistä käsittelyä?

**Comment by mirmaid** [comment]
Lisätään yksikkö-monikkoparit omaan issueensa. Muut ongelmatapaukset käsitellään tässä issuessa.

**Comment by mirmaid** [comment]
Yksikkö-monikko: https://github.com/NatLibFi/Finto-data/issues/536

**Comment by mirmaid** [comment]
Eläin- ja kasvilajien ja sukujen/heimojen tarkenteet. Ei selkeää linjausta nyt siitä, onko (yksikölliselle) lajin nimelle lisättävä tarkenne.

**Comment by YSO-kokous** [comment]
Linjausehdotus: merkitään tarkenne myös lajinimelle.

**Comment by mariaforsen** [comment]
Tapahtumat on tulkittu laajemmassa merkityksessä YSOssa kuin YSAssa (vrt. alakäsitteet). Allärs:evenemang, ALLFO:händelser -> konversion jälkeen? Händelse ei ole sama asia kuin evenemang.

**Comment by mirmaid** [comment]
Eläin- ja kasvilajien ja sukujen/heimojen tarkenteet: sovittiin yso-kokouksessa 9.5.2019 että tarkenteita ei lisätä YSAan, vaan ne päivittyvät tietueisiin konversiossa sen mukaan, onko termi yksikössä vai monikossa. Tarkistetaan konversion jälkeen, onko näissä korjattavaa Melindassa.
