### ISSUE TITLE
YSO-käsitteellä ei YSA-vastinetta

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#962]
bichonit - poistetaan
budo - poistetaan
itämerensuomalaiset - **poistettu**
kaakaokasvit - **poistettu**
kameliat - **ok**
kandidaatit - **lisätty tarkenne (oppiarvot)**
kansalaisten asema - poistetaan
kansanmusiikkijuhlat - **ok**
koisokasvit - **ok** 
koulutusorganisaatiot - poistetaan
kurjenmiekkakasvit - **ok**
lammaskoirat - **ok**
laukkakasvit - poistetaan
luonnonobjektit - poistetaan
malvakasvit - **ok**
matemaattiset käsitteet - muutetaan hierarkisoivaksi
mentaaliset tapahtumat - muutetaan hierarkisoivaksi
molossityyppiset koirat - poistetaan
monoamiinit - **Mirja tutkii / ok**
obinugrilaiset - poistetaan
oikeudellinen suoja - poistetaan
oikeudelliset tapahtumat - muutetaan hierarkisoivaksi
oleminen - **poistettu**
parsakasvit - **ok**
pellavakasvit - **ok**
permiläiset - poistetaan
pinserit ja snautserit - poistetaan
rockfestivaalit - **ok**
silli (laji) - **ok**
suomalais-ugrilaiset - **poistettu**
sveitsinpaimenkoirat - **ok**
synty - poistetaan
säilytykseen liittyvät objektit - muutetaan hierarkisoivaksi
talviliikunta - **ok**
tatarkasvit - **ok**
tiedonsiirtotekniikat - poistetaan
tietokonekielet - poistetaan
tiibetiläiset rodut - poistetaan
tuotantoyritykset - poistetaan
uralilaiset - **poistettu**
vaihdettavuus  [yso:p22215] - **korjattu**
verot - tehdään ehdotus syksyn kokoukseen
volgansuomalaiset - poistetaan
ylösajavat koirat - poistetaan

**Comment by mariaforsen** [comment]
YSOssa on  sekä suomalais-ugrilaiset että suomalais-ugrilaiset kansat (ruotsiksi yksi termi), onko molemmat välttämättömiä?

**Comment by mariaforsen** [comment]
Ks. myös https://github.com/NatLibFi/Finto-data/issues/645

**Comment by tpalonen** [comment]
Kansanmusiikkijuhlien ja rockfestivaalien kohtaloa on jo kertaalleen pohdittu YSOssa ja ne päätettiin silloin säilyttää. https://github.com/NatLibFi/Finto-data/issues/648
_"PÄÄTÖS 13.6.2016
Säilytetään YSOssa ne, joita on käytetty Melindassa. Nämä ovat:
    kansanmusiikkijuhlat
    rockfestivaalit
Poistetaan loput. Replaced by: musiikkijuhlat."_

**Comment by mariaforsen** [comment]
Pitäisi poistaa vastaavalla tavalla vielä obinugrilaiset, permiläiset ja volgansuomalaiset! Kuten yllä mainittu.

**Comment by mariaforsen** [comment]
Eikö obinugrilaiset, volgansuomalaiset ja permiläiset ole samalla tavalla poistettavia?

**Comment by tpalonen** [comment]
Edellä mainitut "poistetaan" ja "muutetaan hierarkisoivaksi" päätökset toteutettu YSOon.
