### ISSUE TITLE
YSA-termillä useita Allärs-vastineita

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#963]
http://yasgui.org/short/WDShRBHI8

- Jos termeillä on sama vastine YSOssa, on konversion jälkeen tehtyä jakoa mahdotonta takautuvasti korjata tietueisiin. Ongelmatapaukset pitäisi käsitellä ennen konversiota.

https://github.com/Finto-ehdotus/YSE/issues/6989
https://github.com/Finto-ehdotus/YSE/issues/6108
https://github.com/Finto-ehdotus/YSE/issues/5160
https://github.com/Finto-ehdotus/YSE/issues/6963
https://github.com/Finto-ehdotus/YSE/issues/6964
https://github.com/Finto-ehdotus/YSE/issues/6977
https://github.com/Finto-ehdotus/YSE/issues/6965
https://github.com/Finto-ehdotus/YSE/issues/6976
https://github.com/Finto-ehdotus/YSE/issues/6975
https://github.com/Finto-ehdotus/YSE/issues/5147
https://github.com/Finto-ehdotus/YSE/issues/6968
https://github.com/Finto-ehdotus/YSE/issues/6929
https://github.com/Finto-ehdotus/YSE/issues/6986
https://github.com/Finto-ehdotus/YSE/issues/6417
https://github.com/Finto-ehdotus/YSE/issues/6933
https://github.com/Finto-ehdotus/YSE/issues/4849
https://github.com/Finto-ehdotus/YSE/issues/7008

Nämä yllä olevat pitäisi ehkä käsitellä ennen konversiota? Muut listalla olevat ratkaistaan "kompromissina" ALLFOssa (eli Allärsissa on ollut 2, mutta ALLFOssa on vain 1)

**Comment by mirmaid** [comment]
Toisin päin http://yasgui.org/short/rJ13EPHjx

**Comment by mirmaid** [comment]
yhdyskuntarakenne, yhteiskuntarakenne = samhällsstruktur (områdesstruktur), samhällsstruktur (social struktur) (muutettu Allärs) - onko selkeä suomeksi?
erioikeudet, etuoikeudet = privilegier (särskilda rättigheter), privilegier (företrädesrätt) (muutettu Allärs) - onko selkeä suomeksi?

**Comment by tpalonen** [comment]
YSO-kokous 15.4.2019:
Yhdyskunta/yhteiskuntarakenne ja eri/etuoikeudet käsiteparit ovat merkityseroiltaan selkeät. Ei tarvitse tehdä lisätoimenpiteitä.
