### ISSUE TITLE
ikääntyneet, vanhukset

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#964]
Miten nämä eroavat toisistaan? Eli tarvitaan tarkkoja määritelmiä niin että voidaan ruotsiksi luoda tarkenteita: äldre (?), äldre (?). Jos suomeksi todella halutaan pitää nämä molemmat sanastossa? Ruotsiksi näiden kohdalla on nyt vakava virhe: åldringar, äldre = sama asia

**Comment by mirmaid** [comment]
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&ved=2ahUKEwjv79Hm-KbgAhWMiKYKHS6DDB0QFjACegQIBxAC&url=https%3A%2F%2Fwww.theseus.fi%2Fbitstream%2Fhandle%2F10024%2F117860%2FLaakso_Martta_Leinonen_Heini_2016_11_25.pdf.pdf%3Fsequence%3D1&usg=AOvVaw3Gku72e5iURFvwAX-FITB8

**Comment by satuniininen** [comment]
Myös _ikääntyminen_ ja _vanheneminen_.

**Comment by mariaforsen** [comment]
https://github.com/Finto-ehdotus/YSE/issues/7926
