### ISSUE TITLE
Kulttuuriantropologia vs perinnetieteet

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#965]
Näiden hierarkia on erilainen YSAssa ja YSOssa. Lihavoidulla eriävät käsitteet.

- YSAssa kulttuuriantropologian alakäsitteinä: dialoginen antropologia, etnofarmakologia, etnofilosofia, etnografia, etnolingvistiikka, etnomatematiikka, etnosemantiikka, fenomenologinen antropologia, filosofinen antropologia, **kaupunkikansatiede**, lingvistinen antropologia, lääketieteellinen antropologia, marxilainen antropologia, media-antropologia, oikeusantropologia, poliittinen antropologia, psykologinen antropologia, symboliantropologia, taideantropologia, taloudellinen antropologia, uskontoantropologia, visuaalinen antropologia.
- YSAssa perinnetieteiden alla **folkloristiikka** ja **kansatiede**.
- YSOssa kulttuuriantropologian alakäsitteinä: dialoginen antropologia, etnofarmakologia, etnofilosofia, etnografia, etnolingvistiikka, etnomatematiikka, **etnomusikologia**, etnosemantiikka, fenomenologinen antropologia, filosofinen antropologia, **folkloristiikka**, **kansatiede**, lingvistinen antropologia, lääketieteellinen antropologia, marxilainen antropologia, media-antropologia, oikeusantropologia, poliittinen antropologia, psykologinen antropologia, symboliantropologia, taideantropologia, taloudellinen antropologia, uskontoantropologia, visuaalinen antropologia
- YSOssa perinnetieteiden alla **etnomusikologia** ja **uskontotiede**.

Mitä tehdä?

**Comment by mariaforsen** [comment]
Ainakin ruotsin osalta oikeampi yläkäsite uskontotieteelle on humanistiset tieteet.

**Comment by YSO-kokous** [comment]
kansatiede, uskontotiede, folkloristiikka YK humanistiset tieteet + RT perinnetieteet [perinnetiede on vahvasti suomenkielinen kategoria]
kaupunkikansatiede YK kansatiede
kansatiede RT kulttuuriantropologia
folkloristiikka RT kulttuuriantropologia
etnomusikologialta pois YK perinnetieteet ja korvataan RT-suhteella perinnetieteet
