### ISSUE TITLE
kilpailu (toiminta)

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#969]
YSAn entinen termi _kilpailu_. Konversiossa > _kilpailu (toiminta)_. Onko syytä jakaa tai löytyykö parempaa tarkennetta? Ruotsiksi _konkurrens_. Urheiluun liittyvät aineistot mahdollisesti ongelma.

**Comment by mariaforsen** [comment]
https://github.com/Finto-ehdotus/YSE/issues/7177
