### ISSUE TITLE
merkinnät ST päivämäärät

### ISSUE THREAD

**Issue by mariaforsen** [NatLibFi/Finto-data#970]
Merkinnät ei ole ok yläkäsite termille päivämäärät, ainakaan ruotsiksi. Voidaanko siirtää, esim. YK tieto tai YK yhteiskunnalliset objektit tai YK yhteiskunnalliset ajanjaksot, ks. näiden muut AK.

**Comment by mirmaid** [comment]
YK kalenteriin liittyvät ajanjaksot
