### ISSUE TITLE
YSOn vanhat ohjaustermit

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#971]
YSOssa on jonkin verran ohjaustermejä, joissa on esim. aikaisemmasta yläkäsitteestä muodostettu sulkutarkenne tai sulkutarkenne, joka on luotu selkeyttämään käsitejakoa, joka on kuitenkin myöhemmin todettu tarpeettomaksi päätermissä (esim. jako on poistettu). Nämä saattavat olla enemmän hämmentäviä kuin selkeyttäviä.

**Comment by mirmaid** [comment]
Sulkutarkenteellinen ohjaustermi käsitteellä, jolla on prefLabelissa eri sulkutarkenne:

bibliografia (erikoisalat) > bibliografia (tieteet)
aura (okkultismin ilmiöt) > aura (rajatieto)
vektorit (abstrakti) > vektorit (matematiikka)
valtiopäivät (poliittinen historia) > valtiopäivät (istuntokaudet)
itsenäisyys (vaikutteista) > itsenäisyys (yksilöt)
itsenäisyys (vallasta) > itsenäisyys (valtiot)

**Comment by mirmaid** [comment]
Sulkutarkenteettomalla käsitteellä sulkutarkenteellinen ohjaustermi:

emergenssi (muutos)
sodanjohto (toiminta)
työnjohto (toiminta)
trikkikuvaus (elokuvaus)
jälkiteollinen yhteiskunta (yhteiskuntajärjestelmät)

**Comment by mirmaid** [comment]
Sulkutarkenteellinen ohjaustermi käsitteellä, jolla on myös uudempi sulkutarkenteellinen ohjaustermi:

alistus (ratkaistavaksi) > alistusmenettely

**Comment by mirmaid** [comment]
Yksittäistapauksia:

cha-cha-cha (latinalaisamerikkalainen populaarimusiikki)
elimet (anatomia) - YSAn peruja, mutta ei ole muuta elimet-termiä

**Comment by mirmaid** [comment]
https://github.com/NatLibFi/Finto-data/issues/924

**Comment by YSO-kokous** [comment]
Vrt. tässä issuessa päätetty deprekoitujen sulkutarkenteellisten käsitteiden sulkutarkennemuodon lisäämistä seuraajakäsitteelle. Näin ei tehty kuin muutaman käsitteen osalta. Ks. issuessa mainittu taulukko: https://github.com/NatLibFi/Finto-data/issues/494

**Comment by mirmaid** [comment]
Kysytään saadaanko issuessa #924 päätetty oldPrefLabel toteutettua pikaisesti, vai voidaanko nämä label-muodot poistaa?

**Comment by mirmaid** [comment]
Ks. myös kysely https://api.triplydb.com/s/odfG9Ul91

**Comment by mirmaid** [comment]
^ Ylläolevassa varmaan suurin osa sulkutarkenteellisista altLabeleista ihan ok, mutta oldPreffit voisi siirtää pois.

**Comment by mirmaid** [comment]
Näitä voisi muutenkin siirtää oldPrefLabel-kenttään, mutta mielestäni vain silloin, kun termimuoto on tosiaan ollut YSOn prefLabel täsmälleen siinä muodossa (esim. bibliografia (erikoisalat) - ONKI3:ssa tarkenne on yksikössä. On mahdollista, että on jossain vaiheessa ollut monikollisena tarkentaana meidän YSOssa, mutta ei pysty enää varmistamaan...).

**Comment by mirmaid** [comment]
Mirja käy listat läpi, oikeat vanhat preffit siirretään olfPrefLabel-kenttään, muut hämmentävät muodot poistetaan.

Lisätään linjauksiin olPrefLabel-kentän käyttöohje: Kenttään merkitään aikaisempi päätermimuoto sellaisessa tapauksessa, että sitä ei haluta jättää näkyville ohjausterminä (jos sitä pidetään käyttäjän kannalta hämmentävänä).
