### ISSUE TITLE
monikkomuotoiset ohjaustermit tansseille

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#972]
Tango (tanssit) -käsitteellä on ohjaustermeinä tangot/tangor. Lisätäänkö vastaavat ohjaustermit myös muille tansseille, vai poistetaanko nämä?

**Comment by mirmaid** [comment]
Ehkäpä sanastokokoukseen tämä.

**Comment by mariaforsen** [comment]
Kannatan lisäämistä.

**Comment by YSO-kokous** [comment]
Kielikellon juttu vierasperäisistä sanoista (yleislainat, erikoislainat, sitaattilainat).
https://www.kielikello.fi/-/vierasperaisten-sanojen-asu
_"ensiksi yleislainat, kieleen täysin mukautuneet lainasanat, joiden äännerakenne on samanlainen kuin ”omienkin” sanojemme (esim. kaappi, tyyny, sikari, sitruuna), toiseksi erikoislainat, uudet, kieleen vain osaksi kotiutuneet lainasanat, joissa saattaa esiintyä vieraita äänteitä ja äänneyhtymiä, mutta jotka kuitenkin ovat mukautuneet omiin taivutustyyppeihimme (esim. biologia, strateginen, reformoida), ja lopuksi sitaattilainat, jotka kirjoitetaan ja mahdollisuutta myöten äännetäänkin alkukielen mukaisesti (esim. arbiter elegantiarum, public school)."_

**Comment by mirmaid** [comment]
Lisätään, jos monikko on yleisesti käytetty. Tarkenteeksi (tanssit).

**Comment by mariaforsen** [comment]
Lisätty monikkomuodot tansseille ruotsin osalta niille, joilla on yleinen monikkomuoto (lähteenä ensisijaisesti SAOL ja SO).
