### ISSUE TITLE
Sulkutarkenteelliset yksikkömuodot

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#973]
Näissä voi olla virheitä (esim. sulkutarkenne muutettu yksikköön) tai vanhentuneita muotoja (tarkenteena aikaisempi yläkäsite). Tarkistettava.

**Comment by mariaforsen** [comment]
Sama tarkistus ruotsiksi, onko tähän jokin SPARQL?

**Comment by tpalonen** [comment]
TBC:ssä toimii tälläinen SPARQL, joka kysyy kaikki piilotermit, joissa on sulkumerkki. Ruotsinkielisiä kysyttäessä pitäisi muuttaa FILTER(lang(?singularpref)-kohtaan ja FILTER(lang(?singularalt) -kohtaan "fi" tilalle "sv".
_SELECT *
WHERE { {
?subject ysometa:singularPrefLabel ?singularpref .
FILTER(lang(?singularpref) = "fi")
FILTER (regex(?singularpref, '\\(')) 
} 
UNION
{
?subject ysometa:singularAltLabel ?singularalt .
FILTER(lang(?singularalt) = "fi")
FILTER (regex(?singularalt, '\\(')) 
} }_

Yasguissa toimii tällainen, johon sama fi>sv-muutos, jos halutaan ruotsinkielisten tulokset.

_PREFIX yso: <http://www.yso.fi/onto/yso/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?subject ?pref ?hidden
WHERE {
GRAPH <http://www.yso.fi/onto/yso/> {
?subject skos:hiddenLabel ?hidden .
FILTER(lang(?hidden) = "fi")
FILTER (regex(?hidden, '\\('))
OPTIONAL {
?subject skos:prefLabel ?pref 
FILTER(lang(?pref) = "fi")  
} } }_

**Comment by mirmaid** [comment]
Tehdäänkö vaan niin, että Mirja ja Maria käyvät listat läpi ja kirjaavat tähän, jos on hämäriä tapauksia? 

Esim. affiksit: sulkutarkenne liitteet-ohjaustermille on (kielitiede), joka on ollut YSAn vanha ketjumuotoinen label. Nykyinen yläkäsite on morfeemit. Jätetäänkö tällaisessa tapauksessa entinen tarkenne, vai vaihdetaanko?

**Comment by mirmaid** [comment]
PD-ohjelmat (täydennyskoulutus): YSOon on lisätty sulkutarkenteellinen ohjaustermi, jonka kanta on sama kuin päätermi. Jätetäänkö tällaiset edelleen?

**Comment by mirmaid** [comment]
****

aloitteet: ohjausterminä aloitteet (pyrkimykset) (tämä olisi oldPrefLabel)
arvot (ilmiöt)
eräoppaat (palveluammatit)
hallitukset (hallintoviranomaiset)
hävittäjät (lentokoneet)
kalvot (orgaaninen rakenne)
kannet (säilytys)
ketjut (ilmiöt)
korit (rakenne)
mitat (fyysiset ominaisuudet)
pelko (tunteet)
pojat (ikään liittyvä rooli)
rodut (rooli)
sotilaspiirit (hallintoalueet)
tulvat (fysikaaliset ilmiöt)
tähdenpeitot (fysikaaliset ilmiöt)
värit (aine)

**Comment by mariaforsen** [comment]
Käydään läpi ruotsiksikin. Poistettu myös turhia/vahingollisia sulkutarkenteettomia muotoja, eli esim.:
elegier (kompositioner), ohjaustermi "elegier" poistettu
elegier (dikter), ohjaustermi "elegier" positettu

**Comment by mariaforsen** [comment]
Vahingossa unassigned.

**Comment by mirmaid** [comment]
Aloitteet: siirretty, onko ok?

**Comment by mirmaid** [comment]
Mirja käy vielä listan läpi ja siirtää oldPrefLabelit.
