### ISSUE TITLE
alikasvos

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#975]
YSOon lisätty Kielitoimiston sanakirjan määritelmä: _pääpuustoa nuorempi (ja matalampi) puusto_, ja sen mukaan on valittu yläkäsite _puusto_. 

Wikipedia: Alikasvos on metsänhoidollinen nimitys, joka käytännössä tarkoittaa taimikkovaiheen ohittaneen metsikön pääpuustoa selvästi nuorempia puuyksilöitä ja pensaskerrosta. Alikasvos voidaan laajemmin käsittää sekä pensas- että kenttäkerroksen muodostamaksi, ja siihen kuuluu pensaita (esimerkiksi kataja, pajut, taikinamarja, paatsama), puiden taimia, saniaisia, varpuja ja korkeita ruohovartisia kasveja. https://fi.wikipedia.org/wiki/Alikasvos

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Undergrowth

**Comment by mariaforsen** [comment]
Ok ruotsiksi kunhan edelleen viittaa metsään.

**Comment by mirmaid** [comment]
Vaihdetaan Tieteen termipankin määritelmä, jätetään yläkäsite ennalleen?

**Comment by jarmosaarikko** [comment]
Metsäalan kymmenluokituksessa on 231.32 alikasvos: käsittely uudistamista varten  (undergrowth: manipulation preparatory to natural regeneration) ,  jossa aluokat: raivaus,  kulotus, laidunnus, myrkyttäminen.
Tämä vastaa tuota edellä viitattua Wikipedian laajempaa määritelmää!
Samoin: https://dictionary.cambridge.org/dictionary/english/undergrowth
Tämä vastaa enemmän käsitettä  "**aluskasvillisuus**", mutta onko se sama?  

Ellei se ole sama käsite, niin alikasvos voisi tällöin viitata vain puiden ja pensaiden osuuteen aluskasvillisuudesta.
Tällöin määritelmä olisi: **Alikasvos (undergrowth): metsän pääpuustoa selvästi lyhyempi ja nuorempi puusto**.
https://forest.fi/glossary/?haku=under#word-undergrowth-alikasvos
