### ISSUE TITLE
desktop publishing

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#976]
Määritelty nyt Yliopistopainon määritelmän mukaan julkaisujärjestelmäksi: _tietokoneesta, skannerista ja tulostimesta rakentuva painotuotteíden valmistusjärjestelmä_. Viittaisiko kuitenkin enemmän julkaisemiseen toimintana? Toki ohjaustermi _pöytäpaino_ myös viittaa järjestelmään, samoin Kielikello: https://www.kielikello.fi/-/desktop-publishing. 

Wikipedia: _Desktop publishing (DTP) is the creation of documents using page layout software on a personal ("desktop") computer._ https://en.wikipedia.org/wiki/Desktop_publishing

Mediasanasto: _Henkilökohtaisen tietokoneen ja tietokonetulostuksen käyttö (juttujen kirjoittaminen ja sivujen taitto) lehden teossa. Yleistä erityisesti uutiskirjeiden tekemisessä._

**Comment by mirmaid** [comment]
Määritelmä joka tapauksessa vähän aikaantunut (?)

**Comment by mariaforsen** [comment]
Olisiko määritelmä poistettavissa? Tuskin tätä termiä käytetään väärin.

**Comment by mirmaid** [comment]
Poistetaan määritelmä, YK julkaisutoiminta.
