### ISSUE TITLE
hoivatyö 

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#977]
Määritelmä Kielitoimiston sanakirjasta: _vars. lasten ja vanhusten hoitaminen (kotona)_. Mikähän tämän kattavuus ja suhde _hoitotyöhön_ tarkalleen olisi?

**Comment by mariaforsen** [comment]
Ruotsiksi tämä ei niinkään taida rajoittua kotona hoitamiseen, hankala kyllä. Mutta ehkä voidaan ruotsiksikin yksinkertaisesti lisätä vastaava määritelmä. Mutta eipä taida myöskään termin hoivatyö käyttö todellisuudessa rajoittua vain kotona hoitamiseen. Ovatko nämä mahdollisesti yhdistettävissä?

**Comment by mirmaid** [comment]
Määritelmä on poistettu. https://github.com/Finto-ehdotus/YSE/issues/8331
