### ISSUE TITLE
informatiikka

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#978]
Määritelmä nyt: _tieteenhaara, joka tutkii tietohuollon kysymyksiä erityisesti tietopalvelun näkökulmasta_ (Tietohuollon sanasto). Käytetty paljon ja laajasti, vrt. myös [Uudet informatiikan ja informaatiotutkimus](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=28&ved=2ahUKEwjEntHj4bbkAhVr_CoKHc93CG44FBAWMAd6BAgCEAI&url=https%3A%2F%2Fpdfs.semanticscholar.org%2F42e3%2Fe79fd4d0dc9ffce812c326ef2325c2ae7d0e.pdf&usg=AOvVaw3s9m7zWZ67xZKUn0Jn2P5b).

**Comment by mariaforsen** [comment]
Olisiko määritelmä poistettavissa? Mainitun artikkelin tapa määritellä on ainakin ruotsin osalta sopivampi, varsinkin näin yleissanastossa.

**Comment by ilona-x** [comment]
SAOssa tuossa laajemassa merkityksessä: 
https://id.kb.se/term/sao/Informatik
Informatik
Relaterad: 
Databehandling | Informationsvetenskap | Informationsteknik

**Comment by ilona-x** [comment]
Tähän liittyen tuli mieleen, että pitäisikö informatiikalla ja kirjastotieteellä olla RT-suhde informaatiotutkimukseen?

LCSH:ssa eri informatiikat (esim. bioinformatiikka) näyttäisivät olevan Information science -käsitteen alakäsitteitä http://id.loc.gov/authorities/subjects/sh85066150

**Comment by mirmaid** [comment]
Poistetaan huomautus. Informatiikka, kirjastotiede RT informaatiotutkimus.
