### ISSUE TITLE
Ruotsin maakunnat ja läänit

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#980]
YSO-paikoissa on Ruotsin lääneistä auktorisoitu vain muutama. Usein läänillä ja maakunnalla on sama nimi (Skåne/Skånen lääni), jolloin käsitteessä ei ole tehty selkeää erottelua, mutta Wikidata-linkit on tehty maakunnan Wikidata-sivuun. 

Silloinkin kun läänillä on eri nimi kuin maakunnalla (Uplanti/Uppsalan lääni, Tukholman lääni), läänien nimiä on käytetty vain joitakin kertoja kuvailussa (mahdotonta sanoa, onko toisaalta käytetty vastaavaa kaupungin nimeä). Vrt. myös wikipedia: _Ruotsin maakunnilla ei nykypäivänä ole mitään poliittis-hallinnollista merkitystä, mutta kulttuurisissa ja historiallisissa yhteyksissä niitä käytetään ahkerasti. Monet ihmiset tuntevat suurempaa yhteenkuuluvuutta kotimaakuntaansa kuin kotilääniinsä._

Jonkinlainen selkeytys tai erillislinjaus Ruotsin läänien ja maakuntien auktorisoinnista ja linkityksestä olisi kuitenkin hyvä saada. 

https://github.com/Finto-ehdotus/YSE/issues/6532
https://github.com/Finto-ehdotus/YSE/issues/6094

**Comment by mirmaid** [comment]
[Lista Ruotsin maakunnista ja lääneistä](https://docs.google.com/document/d/1BUNg4ddcnmcszq3IpN3CzQcFpzsw2Ncb/edit)

**Comment by mariaforsen** [comment]
Kannatan erillistä auktorisointia ja niin että ainakin ruotsiksi lääneillä on (kuten yleiskielessäkin) nimityksenä "x län", ja maakunnilla vain "x". Näin on myös esim. SAOssa, ks. https://id.kb.se/find?q=norrbotten
https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/l%C3%A4n 
https://www.ne.se/uppslagsverk/encyklopedi/enkel/landskap

**Comment by mirmaid** [comment]
Auktorisoidaan läänit erikseen muodossa N:n lääni, KT N (lääni). Maakunnille ohjaustermiksi N (maakunta).
