### ISSUE TITLE
singular alt on toisen käsitteen pref

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#981]
Esim. persialainen/iranilaiset. Onko tämä ongelma?

**Comment by mirmaid** [comment]
taiteenlajit/taide

**Comment by mirmaid** [comment]
Jos singular alt on toisen käsitteen pref, lisätään altLabelille (monikossa ja yksikössä) tarkenne.

**Comment by YSO-kokous** [comment]
Tällä SPARQL-kyselyllä saa nämä etsittyä. Ruotsin ja englannin osalta rivin _FILTER(LANGMATCHES(LANG(?label), "fi"))_ kieli muutettava (eli "fi" muotoon "sv" tai "en"):

SELECT *
WHERE {
    ?c1 ysometa:singularAltLabel ?label .
    ?c2 skos:prefLabel ?label 
FILTER(LANGMATCHES(LANG(?label), "fi"))
FILTER(?c1 != ?c2)
}

**Comment by mirmaid** [comment]
Lisätään tarkenne singular-muotoon ja jos soveltuu, myös monikolliseen altLabeliin.

**Comment by mariaforsen** [comment]
Tarkistus tehty ruotsiksi ja lisäyksiä tehty yllä olevan periaatteen mukaisesti (tosin löytyi myös aika paljon ongelmia, mutta näistä on tehty erillisiä issueita).

**Comment by mirmaid** [comment]
Tehty myös suomeksi lukuunottamatta deprekoituja käsitteitä.
