### ISSUE TITLE
lait yleis- vai yksilökäsitteitä

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#982]
Tällä hetkellä epäjohdonmukaisuutta.

**Comment by YSO-kokous** [comment]
Muutetaan kaikki lait-hierarkian alaiset käsitteet yksilökäsitteistä yleiskäsitteiksi.

Perusteena Terminologian sanasto:
fi        yksilökäsite
sv       individualbegrepp n
en      individual concept
fr        concept m unique
määritelmä
käsite, joka vastaa yhtä ainutkertaista tarkoitetta
huomautus
Yksilökäsitteisiin viitataan erisnimillä kuten 'Jupiter' ja 'Itämeri'. Sanastotyössä käsitellään yksilökäsitteitä melko harvoin.

**Comment by YSO-kokous** [comment]
Toteutettu dataan.
