### ISSUE TITLE
muinaisjäännökset

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#983]
Kysytty Museovirastosta:

YSAan hyväksyttiin termi kiinteät muinaisjäännökset. MAOssa sen alakäsitteinä on:
•	kalliomaalaukset 
•	kalliopiirrokset 
•	kiviröykkiöt 
•	kodanpohjat 
•	käräjäpaikat 
•	luolamaalaukset 
•	muinaislinnat 
•	muinaisvalkamat 

Näistä YSAssa on vain kaksi ensimmäistä ja muinaislinnat, joille voi lisätä tämän yläkäsitteen. YSAssa muinaisjäännökset-termin alla olevista mielestäni myös jatulintarhat, muinaishaudat, riimukivet (sekä obeliskit, pyramidit ja sfinksit jos ne ylipäätään luokitellaan muinaisjäännöksiksi), ovat kiinteitä muinaisjäännöksiä. Onko teillä Museovirastossa kantaa tähän?

Museovirasto:
_Nyt kun kulttuuriympäristöön liittyviä käsitteitä on MAOssa täydennetty ja määritelty, kiinteät muinaisjäännökset määritellään MAOssa muinaismuistolain suojelemiksi kohteiksi. http://finto.fi/maotao/fi/page/?uri=http%3A%2F%2Fwww.yso.fi%2Fonto%2Fmao%2Fp928 
Olisiko tämä hyvä linjaus myös YSOssa?_ 

https://www.finlex.fi/fi/laki/alkup/1963/19630295

**Comment by YSO-kokous** [comment]
kuvakivet YK elottomat objektit + RT kiinteät muinaisjäännökset [kuvakivi ei ole rooli/ominaisuus]
asuinpainanteet YK elottomat objektit + RT kiinteät muinaisjäännökset [asuinpainenne ei ole rooli]

**Comment by YSO-kokous** [comment]
Näitä ei vielä toteutettu mutta päätettiin:

kalliomaalaukset, kalliopiirrokset, muinaislinnat, jatulintarhat, muinaishaudat, riimukivet RT kiinteät muinaisjäännökset
Ei muita muutoksia.
