### ISSUE TITLE
alkuperäiskansat

### ISSUE THREAD

**Issue by YSO-kokous** [NatLibFi/Finto-data#985]
Tämän alla nyt aboriginaalit ja adivasit. Varmasti monet muutkin ovat alkuperäiskansoja. Ratkaisu tuntuu erikoiselta, kun muut kansat on hierarkisoitu lähinnä maantieteen mukaisesti. Pitäisikö nykyiset alakäsitteet siirtää muuanne?

**Comment by mariaforsen** [comment]
Ainakin ruotsin osalta käy aboriginer YK australier (=benämning på invånare i Australien i allmänhet och även på aboriginer)

**Comment by YSO-kokous** [comment]
aboriginaalit YK australialaiset
adivasit YK aasialaiset
