### ISSUE TITLE
valtio (instituutio), kirkko (instituutio)

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#986]
Pitäisikö näiden yläkäsite olla ennemmin instituutiot? 
Nyt: 
valtio YK julkisyhteisöt YK yhteisöt YK organisaatiot YK yhteiskunnalliset järjestelmät
(valtiot YK organisaatiot)
kirkko YK yhteiskunnalliset järjestelmät 
(kirkkokunnat YK organisaatiot) 
instituutiot YK organisaatiot YK yhteiskunnalliset järjestelmät 

Toisaalta pitäisikö ennemmin olla valtiot YK julkisyhteisöt?

**Comment by YSO-kokous** [comment]
Tehdään seuraavat muutokset:
valtio (instituutio) YK instituutiot + RT julkisyhteisöt
kirkko (instituutio) YK instituutiot
