### ISSUE TITLE
Lisähuomautukset muutamalle hierarkisoivalle käsitteelle?

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Finto-data#988]
Lisäsin hierarkisoiville käsitteille seuraavat skos:notet

'This is a hierarchical concept not to be used in subject cataloging.'@en .
'Käsite on tyypiltään hierarkisoiva. Käsitettä ei ole tarkoitettu käytettäväksi kuvailussa.'@fi .
'Begreppstypen är hierarkiserande. Begreppet är inte avsett för användning vid innehållsbeskrivning.'@sv .

Pitäisikö lisäksi lisätä jonkinlainen scopenote sellaisille hierarkisoiville käsitteille, jotka terminsä puolesta näyttävät ehkä yleiskäsitteiltä ja joku voisi erehtyä niitä käyttämään kuvailussa? Esim. jotenkin näin: "Käytä mieluummin _tätä käsitettä_."? Hierarkisoivia käsitteitä on YSOssa 83. Ainakin nämä alla listatut hierarkisoivat ovat minusta sellaisia, että niihin käyttöhuomautuksen voisi lisätä.

ajanjaksot
asema (yhteiskunnalliset ominaisuudet)
biologiset ominaisuudet
kielelliset ominaisuudet
itsenäinen toiminta
keskinäinen toiminta
kulttuuriset ilmiöt
luonnontieteelliset järjestelmät
oliot
rooli (tehtävä)
sotilaalliset organisaatiot
sotilashenkilöt
suhteet
tapahtumat ja toiminta
tekniset järjestelmät
yhteiskunnalliset ilmiöt
yhteiskunnalliset tapahtumat

**Comment by mariaforsen** [comment]
Termistä sotilaalliset organisaatiot on yse-issue, toivon että toinen poistuu.

**Comment by mirmaid** [comment]
Nämä huomautukset onkin nykyään käyttöhuomautuksia.

**Comment by mirmaid** [comment]
Ei lisätä ehdotuksia kuvailussa käytettävistä termeistä, ei todennäköisesti suurta vaikutusta.
