### ISSUE TITLE
Monikkomuotoisia altLabeleita yksikkömuotoisille käsitteille?

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-data#993]
Asia nousi esiin [korona-käsitteen](https://github.com/Finto-ehdotus/YSE/issues/8617) yhteydessä. Tyypillisiä yksikköjä ovat esim. ruumiinosat, kasvinosat ja samalla logiikalla myös taivaankappaleiden osat. Pitäisikö näille lisätä monikkomuotoisia ohjaustermejä?

**Comment by mirmaid** [comment]
Liittyy myös tähän https://github.com/Finto-ehdotus/YSE/issues/9734

**Comment by mirmaid** [comment]
Ruumiinosat:

**Comment by mirmaid** [comment]
Kasvinosat:

**Comment by mirmaid** [comment]
Taivaankappaleiden osat:

**Comment by mirmaid** [comment]
Eläinlajit:

**Comment by mariaforsen** [comment]
Yllä olevat ruotsiksi: Maria

**Comment by fantsby-m** [comment]
> Ruumiinosat: (Matti)

hampaan juuret
hermostot
höyhenpeitteet
istukat
karvapeitteet
leuat
mantelitumakkeet (tyvitumakkeiden alakäsite)
mykiöt
nielurisat
sisäkorvat
tärykalvot
tyvitumakkeet
utareet
vaivaisenluut
välikorvat

**Comment by ilona-x** [comment]
> Kasvinosat: (Ilona)

latvus ?
latvusto ?
juuristo ?

Ylläolevat varmaan voi lisätä monikkoon, mutta mikä on näiden "latvus & latvusto" ja "juuret & juuristo" suhde? 🤔 
Kielitoimiston sanakirja sanoo esim. latvusto = latvukset. Eli pitäisikö monikon latvukset ohjata sitten sekä latvukseen että latvustoon. 

näille voisi lisätä monikkomuodon ohjaustermiksi:

johtosolukot    (johtosolukko)
maavarret    (maavarsi)
mykorritsat    (mykorritsa)
rungot    (runko)
varret    (varsi)

ei tarpeen lisätä monikkomuotoa:
apoplasti
jälsi
ligniini
nila
puunkuori
siitepöly

**Comment by mariaforsen** [comment]
Ruotsiksi voisi olla monikkomuotoja ainakin näiden kohdalla (ja sen lisäksi osalla voi olla jo siinä mielessä että yksikkö- ja monikkomuoto ovat samoja):

hjärnor
cerebrospinalvätskor
tandrötter
tandemaljer
mitralklaffar
fjäderdräkter
moderkakor
skallbaser
analöppningar
ansikten
benstommar
bröstkorgar
bukhålor
bukväggar
halsar
huvuden
hårbeklädnader
hårbottnar
inneröron
käkar
magar
mellanöron
muskelmassor
nackar
ryggar
ryggsträngar
tarmkanaler
trumhinnor
ögonlinser

lisäksi: 
hjärtan
mjältar
sköldkörtlar
levrar
blindtarmar
bukspottkörtlar
gallblåsor
magsäckar
matstrupar
munnar
strupar
tjocktarmar
tunntarmar
våmmar 
äntarmar

Nämä kaikki monikkomuodot löytyvät sanakirjasta svenska.se.

**Comment by mirmaid** [comment]
Katsotaan vielä yhteisesti, mitkä ehdotetuista lisätään.

**Comment by mirmaid** [comment]
Tehty lukuunottamatta ruumiinosia.

**Comment by mariaforsen** [comment]
Tehty myös ruotsiksi.
