### ISSUE TITLE
KITO huomautusbannerin lisäys

### ISSUE THREAD

**Issue by Finto-ehdotus** [NatLibFi/Finto-data#995]
Tiketti  KK-02738325
LIsätään tässä vaiheessa KITO ontologialle vastaavan banneri kuin [MUSO:ssa](https://finto.fi/muso/fi/), että sanaston on poistunut käytöstä.

Teksti banneriin:
"Kirjallisuudentutkimuksen ontologia KITO on yhdistetty Yleiseen suomalaiseen ontologiaan YSOon. KITOa ei enää ylläpidetä eikä sen termejä päivitetä. Kirjallisuudentutkimuksen kuvailussa käytetään YSOn käsitteitä. Uusia tämän aihealueen termejä voi ehdottaa YSOon ehdotusjärjestelmässä."@fi

"The Finnish ontology of literature research KITO has been included into the General Finnish Ontology (YSO). KITO is no longer maintained and the terms are not updated. For content description in literature research use YSO-concepts.  New concepts and terms in this subject area can be suggested for YSO through a form linked on its homepage."@en

Ruotsiksi ei tarvita, kun sisältöä ei ollut ruotsiksi. Mutta tässä kuitenkin, jos banneri valikoituu käyttöliittymän mukaan:

"KITO ontologi för litteraturforskning har uppgått i den allmänna finländska ontologin ALLFO. KITO upprätthålls inte längre och termerna i den uppdateras inte. Vid beskrivning av litteraturforskning används ALLFO-begrepp. Nya termer föreslås till ALLFO via förslagssystemet."@sv

**Comment by jarmosaarikko** [comment]
Sama operaatio myös [KULO-ontologialle]( https://finto.fi/kulo/fi/)

Teksti banneriin:
"Kulttuurien tutkimuksen ontologia KULO on yhdistetty Yleiseen suomalaiseen ontologiaan YSOon. KULOa ei enää ylläpidetä eikä sen termejä päivitetä. Kulttuurien tutkimuksen kuvailussa käytetään YSOn käsitteitä. Uusia tämän aihealueen termejä voi ehdottaa YSOon ehdotusjärjestelmässä."@fi

"The Finnish ontology of cultural research KULO has been included into the General Finnish Ontology (YSO). KULO is no longer maintained and the terms are not updated. For content description in cultural research use YSO-concepts. New concepts and terms in this subject area can be suggested for YSO through a form linked on its homepage."@en

Ruotsiksi ei tarvita, kun sisältöä ei ollut ruotsiksi. Mutta tässä kuitenkin, jos banneri valikoituu käyttöliittymän mukaan:

"KULO ontologi för kulturforskning har uppgått i den allmänna finländska ontologin ALLFO. KULO upprätthålls inte längre och termerna i den uppdateras inte. Vid beskrivning av kulturforskning används ALLFO-begrepp. Nya termer för kulturforskning föreslås till ALLFO via förslagssystemet."@sv

**Comment by jarmosaarikko** [comment]
testataan ensin devillä

**Comment by jarmosaarikko** [comment]
KITO ja KULO -sanastoille huomautusbannerit on nyt julkaistu Fintossa.
